### ISSUE TITLE
Please ignore the lact suggestion, that's completely wrong.

### ISSUE THREAD

**Issue by Toffy2323** [ublue-os/bazzite#1000]
Please ignore the lact suggestion, that's completely wrong. 

Follow https://github.com/ublue-os/bazzite#alternative-handhelds

Our guides cover fan control.

_Originally posted by @KyleGospo in https://github.com/ublue-os/bazzite/issues/999#issuecomment-2068215672_

**Comment by Toffy2323** [comment]
Please provide a real suggestion than posting a link to info page, completed my issue without a fix

**Comment by Toffy2323** [comment]
Where? I can't see it

**Comment by KyleGospo** [comment]
Please do not open another issue here, if you need more help than our guide offers ask in the forum.
