### ISSUE TITLE
Bazzite's network not working

### ISSUE THREAD

**Issue by SniperWasTaken** [ublue-os/bazzite#1018]
### Describe the bug

I was trying to setup bazzite on the ROG Ally, but when im trying to, it shows me it can't reach the internet

### What did you expect to happen?

I was expecting to get past the setup of the steam's gaming mode

### Hardware

Asus ROG Ally

### Extra information or context

It takes too long to connect to the internet, i tried restarting but no use

**Comment by KyleGospo** [comment]
If you're dual booting, try fully shutting off the device and then booting Bazzite.
