### ISSUE TITLE
How to rollback to NVIDIA 550.67?

### ISSUE THREAD

**Issue by dicksonleong** [ublue-os/bazzite#1021]
### Describe the bug

NVIDIA 550.76 is a mess:
- my logs got spammed with "Error setting GPU limit" (see https://forums.developer.nvidia.com/t/550-76-edid-readout-problem-and-nvidia-powerd-error-looping/290141)
- when try to launch proton game it either crash on startup or freeze the whole KWin desktop (Xorg running at 100% CPU). The logs doesn't provide much useful information.
- wake up from sleep will show blank screen

All of these problems doesn't happens in F39+NVIDIA 550.67 image.

Any idea how I can rollback to NVIDIA 550.67 without rolling back to the previous image (F39)? I have tried

```
rpm-ostree override replace https://download1.rpmfusion.org/nonfree/fedora/releases/40/Everything/x86_64/os/Packages/a/akmod-nvidia-550.67-1.fc40.x86_64.rpm
``` 

But it doesn't seems to work.

### What did you expect to happen?

Able to rollback to NVIDIA 550.67

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable (index: 0)
                   Digest: sha256:89efa201e1890da7f57585aef6941161bfff50cf0e6dfbe9c92875f5b0bb6280
                  Version: main (2024-04-26T01:27:41Z)
               BaseCommit: db57d38507ab703168f8823d0105fa06b1955e4fb6a6585644ae6e4757c86c24
                   Commit: a5fc7a620c8b27b3202d8d6c11744818b053fa98e4d0942501dbf8eaf4d0b37c
                           ├─ copr:copr.fedorainfracloud.org:matte-schwartz:sunshine (2024-04-14T12:22:05Z)
                           ├─ copr:copr.fedorainfracloud.org:rodoma92:kde-cdemu-manager (2024-04-20T12:39:00Z)
                           ├─ copr:copr.fedorainfracloud.org:rok:cdemu (2024-02-20T12:07:53Z)
                           ├─ fedora (2024-04-19T08:53:31Z)
                           ├─ rpmfusion-free (2024-04-20T12:11:51Z)
                           ├─ rpmfusion-free-updates (2024-04-24T11:18:06Z)
                           ├─ rpmfusion-free-updates-testing (2024-04-24T11:18:21Z)
                           ├─ rpmfusion-nonfree (2024-04-20T12:18:23Z)
                           ├─ rpmfusion-nonfree-updates (2024-04-24T11:37:34Z)
                           ├─ rpmfusion-nonfree-updates-testing (2024-04-24T11:37:39Z)
                           ├─ updates (2024-04-25T00:52:10Z)
                           └─ updates-archive (2023-10-06T17:04:49Z)
                   Staged: no
                StateRoot: default
   InactiveLocalOverrides: akmod-nvidia-3:550.67-1.fc40.x86_64
          LayeredPackages: duf htop podman-compose
```

### Hardware

Acer Laptop, Ryzen 7940HS, NVIDIA RTX 4070

**Comment by KyleGospo** [comment]
You can rebase to :39 or an image by date for the time being.

**Comment by msmafra** [comment]
There is a fresh new version 550.78 addressing some bug with 40xx series"Fixed a regression that led to Xid errors when loading the NVIDIA driver on some notebook systems with RTX 4xxx series GPUs.".
I don´t know if it's related to your problem

https://www.nvidia.com/en-us/geforce/drivers/results/224350/

**Comment by sovietpop** [comment]
Yes, im going to rollback too , the new Nvidia driver (i think) cause a lot of problems.

**Comment by dicksonleong** [comment]
> You can rebase to :39 or an image by date for the time being.

So it is not possible to downgrade the driver version using rpm-ostree?

> There is a fresh new version 550.78 addressing some bug with 40xx series"Fixed a regression that led to Xid errors when loading the NVIDIA driver on some notebook systems with RTX 4xxx series GPUs.". I don´t know if it's related to your problem
> 
> https://www.nvidia.com/en-us/geforce/drivers/results/224350/

Looks possible - and seems like the package is already available at rpmfusion-update-testing repository: https://download1.rpmfusion.org/nonfree/fedora/updates/testing/40/x86_64/a/. @KyleGospo is it possible to upgrade the `akmod-nvidia` myself using rpm-ostree to test it?

**Comment by dicksonleong** [comment]
That's unfortunate. Guess I will wait for 550.78 then. Thanks 🙂
