### ISSUE TITLE
Gaming mode doesn't work after upgrade

### ISSUE THREAD

**Issue by S1ngl3-x** [ublue-os/bazzite#1025]
### Describe the bug

After upgrade that brought along fedora 40 gaming mode no longer works. KDE boots after system start up and icon "Go back to gaming mode" tries to open gaming mode and then falls back to KDE.

### What did you expect to happen?

Gaming works when using the gaming edition for hometh

### Output of `rpm-ostree status`

```shell
Ostree was to update.

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:67bb1f9dd52a420f080fd67e71a60bb6f732c12bacab7d27476dfbdca601c757
                  Version: 40.20240427.0 (2024-04-27T22:36:59Z)
          LayeredPackages: sunshine
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f87d5dd11724f35cf8f47a1d22e38777d22160412737ad8d8a288fe23758eb1d
                  Version: 39.20240419.0 (2024-04-19T17:09:55Z)
          LayeredPackages: sunshine
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 
                   Pinned: yes
```

### Hardware

Bazzite edition:
Home theater PC
KDE
AMD
Gamig mode - yes

System hw:
AMD Ryzen 5 5600X 
AMD RX 7900XT
32gb ram
2tb ssd

### Extra information or context

Tried running system update, didn't help.
Tried running Bazzite portal to initialize everything along with gaming mode, didn't help.

After rolling back to previous deployment, everything works correctly.

**Comment by tpkee** [comment]
Same problem on Gnome

**Comment by mbouron** [comment]
I also got this issue when upgrading from deck-39 to deck-40. `steam` (game mode) errors out with "Unable to open a connection to X", then it fallbacks to the kde session.
Had to rollback to deck-39 for the time being.

**Comment by S1ngl3-x** [comment]
Tried again and still broken. Here are all the logs.


[bazzite40-os
[bazzite40-neofetch.txt](https://github.com/ublue-os/bazzite/files/15175020/bazzite40-neofetch.txt)
tree.txt](http
[bazzite39-ostree.txt](https://github.com/ublue-os/bazzite/files/15175022/bazzite39-ostree.txt)
s://github.com/ublue-os/bazzite/files/15175019/bazzite40-ostree.txt)
[bazzite39-neofetch.txt](https://github.com/ublue-os/bazzite/files/15175023/bazzite39-neofetch.txt)


I've noticed neofetch thinks I have 5700X instead of 5600X, but that's most probably unrelated to the issue with gaming mode.

**Comment by KyleGospo** [comment]
Try our :testing branch, there's a known issue with HDR on 7xxx GPUs we're trying to get fixed in stable ASAP.

**Comment by S1ngl3-x** [comment]
I can confirm switching to testing branch and updating fixed the issue.
However it created a new one: black screen on multiple reboots. I rolled back immediately once I could get display output after boot screen.

Gonna wait for next stable update and then hopefully close this issue.

**Comment by S1ngl3-x** [comment]
Not in a hurry or anything but wanted to ask if stable release is coming? I am still on bazzite based on fedora 39 and still got that issue with black screen after upgrading to what used to be "testing branch". 

Should I file a new bug report? But I don't know how to log black screen after boot (but I've tested I can ssh into it).

**Comment by S1ngl3-x** [comment]
3.5.0 (2024-06-30) Resolved everything, closing
