### ISSUE TITLE
Bazzite 40 images don't use Semver on `org.opencontainers.image.version` label, breaks BlueBuild builds

### ISSUE THREAD

**Issue by gmpinder** [ublue-os/bazzite#1028]
### Describe the bug

The `org.opencontainers.image.version` label currently does not contain a Semver of the Fedora version.

```
$> skopeo inspect docker://ghcr.io/ublue-os/bazzite:40 | jq '.Labels["org.opencontainers.image.version"]'
"nightly"

$> skopeo inspect docker://ghcr.io/ublue-os/bazzite:stable | jq '.Labels["org.opencontainers.image.version"]'
"nightly"

$> skopeo inspect docker://ghcr.io/ublue-os/bazzite:latest | jq '.Labels["org.opencontainers.image.version"]'
"nightly"
```

[BlueBuild currently requires this label](https://github.com/blue-build/cli/blob/main/src/image_metadata.rs#L18) to be set with a Semver in order to properly pull the correct `akmods` image for our [`akmods` module](https://blue-build.org/reference/modules/akmods/) since we need to know what version of Fedora the user is running.

### What did you expect to happen?

It's expected that this label should continue to have the same version as the upstream image. The Bazzite 39 image has the proper version as does the main 40 images.

```
$> skopeo inspect docker://ghcr.io/ublue-os/bazzite:39 | jq '.Labels["org.opencontainers.image.version"]'
"39.20240419.0"

$> skopeo inspect docker://quay.io/fedora/fedora-kinoite:40 | jq '.Labels["org.opencontainers.image.version"]'
"40.20240427.0"

$> skopeo inspect docker://quay.io/fedora/fedora-kinoite:39 | jq '.Labels["org.opencontainers.image.version"]'
"39.20240410.1"

$> skopeo inspect docker://ghcr.io/ublue-os/kinoite-main:40 | jq '.Labels["org.opencontainers.image.version"]'
"40.20240427.0"

$> skopeo inspect docker://ghcr.io/ublue-os/silverblue-main:40 | jq '.Labels["org.opencontainers.image.version"]'
"40.20240427.0"
```

**Comment by p5** [comment]
You may be able to extract the Fedora version from the kernel release string label.  I am doing this in my personal image to track the CoreOS kernel.

**Comment by gmpinder** [comment]
> You may be able to extract the Fedora version from the kernel release string label. I am doing this in my personal image to track the CoreOS kernel.

We're using this label as intended. This is a regression in the Bazzite build as its upstream image sets it properly as do all the other images Ublue builds.
