### ISSUE TITLE
GPD Win Mini 2024 screen rotated to portrait

### ISSUE THREAD

**Issue by Ganju0** [ublue-os/bazzite#1033]
### Describe the bug

The installer was landscape but upon installing and going to the kde desktop, was portrait. Steam gamepadui was portrait after final setup

### What did you expect to happen?

Landscape screen. The display on the win mini 2024 is native landscape, 120hz, VRR

### Output of `rpm-ostree status`

```shell
rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:25e6c62e647e7bef2a461f24d0c7fea72a86fb95edb66bae00f350e42364bf55
                  Version: nightly (2024-04-26T17:04:40Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b8cc9aa32ee1dde43c920fcd373a0e7b5d3c89eca810c93402fea9969455bc5d
                  Version: main (2024-04-25T06:48:14Z)
```

### Hardware

G1617-01

**Comment by Diamonace** [comment]
I think the problem should be with this file——/usr/share/gamescope-session-plus/device-quirks.

The file where contains “GPD WIN” says：

"–force-orientation right "

maybe change the text into “–force-orientation normal” could solve this problem.

But this file is a read-only filesystems.

I try to use “sudo mount -o remount,rw” or “sudo chmod a+rw” or “sudo setenforce 0”, all failed.

So now the question becomes how can I modify “device-quirks” which is read-only filesystems?

**Comment by Poopman1000** [comment]
Also have the same experience

**Comment by Ganju0** [comment]
For anyone following this, a game scope patch is being worked on

**Comment by artw** [comment]
it's not (only?) gamescope. it's /usr/libexec/bazzite-hardware-setup adding video= flag for the kernel. the workaround is to disable bazzite-hardware-setup and delete the flag with rpm-ostree kargs --delete-if-present

**Comment by Ganju0** [comment]
I think its more complicated than that. For one, the mini 2023 and 2024 have the same device ID so you need a different way to flag it. Theres discussion about it in the bazzite discord where patching the kernel was brought up but instead gamescope is being patched to detect the display resolution. Its a bit above my paygrade. You can read about the patch below

https://github.com/ChimeraOS/gamescope-session/pull/86

**Comment by artw** [comment]
possibly. I only got this thing yesterday, but the image does not flip anywhere since I got rid of the kernel arg

**Comment by Ganju0** [comment]
I think they want a solution so that when people install bazzite it just works so people with a 2024 mini don't have to install and modify the kernel

**Comment by Ganju0** [comment]
Fixed in new iso

**Comment by kenpuluma** [comment]
GPD is actually selling 2024 mini model with 7640U CPU, which will result in the same rotation issue after the https://github.com/ublue-os/bazzite/pull/1062 fix.
