### ISSUE TITLE
No UI scaling option in gamescope on Legion Go

### ISSUE THREAD

**Issue by fehbari** [ublue-os/bazzite#1037]
Not sure if I'm missing something, but under gamescope there's no UI scaling option and everything looks very small for my taste. I tried this on both variants of bazzite-deck v3.0.0 (KDE and Gnome). Strangely, the option is there if I open Steam Big Picture from desktop mode.

Unfortunately for me that's an accessibility issue, as I find the smaller elements and fonts difficulty to read at times.

FWIW my partner's ROG Ally has the option, so the issue seems specific to the Legion Go.

![image](https://github.com/ublue-os/bazzite/assets/3378355/abff0785-347d-4681-8372-01abab724d65)

![image](https://github.com/ublue-os/bazzite/assets/3378355/6ea1c311-0bb2-4fad-8f64-d9d13e4d5639)

![image](https://github.com/ublue-os/bazzite/assets/3378355/909b5682-ee99-4af6-8b92-43276b4d018e)

**Comment by aerielb** [comment]
You can fix this by - 

1. Install plugin loader
2. Open decky settings, enable dev mode
3. In the dev menu (of decky) enable valve internal menu
4. Enable dev mode in system settings
5. Go to the valve internal menu at the bottom of the settings list and enable control of internal display scaling
6. Go to display settings and adjust scaling

**Comment by fehbari** [comment]
> You can fix this by -
> 
> 1. Install plugin loader
> 2. Open decky settings, enable dev mode
> 3. In the dev menu (of decky) enable valve internal menu
> 4. Enable dev mode in system settings
> 5. Go to the valve internal menu at the bottom of the settings list and enable control of internal display scaling
> 6. Go to display settings and adjust scaling

Oooh, this is incredible and definitely works. Don't know how you find it but you just saved me eyesight. Thank you!

Can this be added to the setup instructions for the Legion Go? Happy to do it myself too if you want.

**Comment by KyleGospo** [comment]
Please! We always appreciate better documentation

**Comment by fehbari** [comment]
Will do it then. 🙂 

@KyleGospo Readme is enough or should I add it somewhere else?
