### ISSUE TITLE
Gaming Mode doesn't work

### ISSUE THREAD

**Issue by Decker-01** [ublue-os/bazzite#1039]
### Describe the bug

The System directly boot into desktop mode. The gaming mode button does not work properly. The screen flickers and Steam is shut down but then i'm send back right to desktop mode.
The error appeared after the SteamOS update in Gaming mode.

### What did you expect to happen?

I expected that the system boot directly into gaming mode.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:67bb1f9dd52a420f080fd67e71a60bb6f732c12bacab7d27476dfbdca601c757
                  Version: 40.20240427.0 (2024-04-27T22:36:59Z)
            LocalPackages: lact-0.5.4-0.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:25e6c62e647e7bef2a461f24d0c7fea72a86fb95edb66bae00f350e42364bf55
                  Version: nightly (2024-04-26T17:04:40Z)
            LocalPackages: lact-0.5.3-0.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" '
```

### Hardware

![grafik](https://github.com/ublue-os/bazzite/assets/166182283/cbd95d72-eac5-475c-a7f4-8fef16887bd7)

TV is a Sony Oled 4k TV.

**Comment by anyoneyun** [comment]
Same here

**Comment by anultravioletaurora** [comment]
Same issue here with similar specs on a fresh install

I go through the Bazzite Portal on the first start up but on the reboot I still get kicked back to Gnome

**Comment by anyoneyun** [comment]
I can tell you all that rebasing to testing does fix it, so you can try that!
