### ISSUE TITLE
Gnome 46 remote login not working

### ISSUE THREAD

**Issue by mpetuska** [ublue-os/bazzite#1043]
### Describe the bug

Trying to enable new gnome 46 remote login feature doesn't work. The toggle enables, but no port is being generated/assigned. Also if I clise the settings app and reopen it, the toggle reverts back to off state.

### What did you expect to happen?

Remote login to enable properly and bind to a port.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:2fe1600a06aa6827efcdb9854b5349d50c685629655125732ccb42c6758925bd
                  Version: 40.20240427.0 (2024-04-27T22:40:11Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:6130a8a54ee5e3512d56b38fad3a88286e1e1d48bed30a2e999513e0b2381023
                  Version: main (2024-04-24T21:33:49Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

                                          
     %%%%%%====%%%%%%%%%%                
   %%%%%%%%    %%%%%%%%%%%%%%             󱋩  bazzite-deck-gnome:stable 
  %%%%%%%%%    %%%%%%%%%%%%%%%%           󰣛  Fedora Linux 40 (Silverblue) x86_4
  %%%%%%%%%    %%%%%%%%%%%%%%%###           Linux 6.8.7-302.fsync.fc40.x86_64
  %%%%%%%%%    %%%%%%%%%%%%%######        󰅐  12 mins
  ==                  =======######      
  ==                  =========#####      󰾰  MS-7D75
  %%%%%%%%%    %%%%%%%####======#####     󰻠  AMD Ryzen 7 7700X (16) @ 5.57 GHz
  %%%%%%%%%    %%%%%#######=====#####     󰍛  AMD Radeon RX 6950 XT
  %%%%%%%%%    %%%#########=====#####       6.16 GiB / 31.08 GiB (20%)
  %%%%%%%%%    %%##########=====#####       893.65 GiB / 929.93 GiB (96%) - b]
  %%%%%%%%%====###########=====######     󰍹  3840x2160 @ 60Hz (as 1920x1080) []
   %%%%%%%%====#########======######     
    %%%%%%%=====#####========######       󰕮  Gnome 46.0
     %%%%###===============#######          Mutter (Wayland)
      %#######==========#########           bash 5.2.26
        #######################             ptyxis-agent
          ###################             󰏖  2335 (rpm), 76 (flatpak-system), )
              ###########            
                                           ● ● ● ● ● ● ● ●

**Comment by KyleGospo** [comment]
Deck images use SDDM and Valve's session model, features like this will not work. Desktop images use GDM as normal.

**Comment by mpetuska** [comment]
Is it possible to get gamemode ui boot on desktop images? Wondering if I should rebase.
