### ISSUE TITLE
Colors all weird when coming back from sleep

### ISSUE THREAD

**Issue by dragoonDorise** [ublue-os/bazzite#1046]
### Describe the bug

Sleep from gaming mode, wake the computer. All your screen is in different shades of weird colors, pink, yellow, etc.

### What did you expect to happen?

Show proper colors :)

### Hardware

AMD Ryzen 7 5800X3D
AMD 7900XTX
Asrock Fatal1ty MB

**Comment by GnomeBeans** [comment]
I have a similar issue on my tv set. Its a roku. In order to fix the issue I go back to home and reselect the hdmi/display port output and the issue is resolved until it happens next time. Sometimes this occurs when boots as well. I also experience a green bios on boot but nothing is unusable.

**Comment by dragoonDorise** [comment]
It turned out to be a bad HDMI cable :/
