### ISSUE TITLE
Broken frame limiter on Asus ROG Ally after 3.0.0 update

### ISSUE THREAD

**Issue by semioys** [ublue-os/bazzite#1048]
### Describe the bug

After a successful update to 3.0.0, the built-in frame limiter stopped working. Before the update it worked as expected.

What I tried:
- clean install, same result.
- deactivate "unified frame limit management" in the Developer Settings, same result.

For now, I'm using `DXVK_FRAME_LIMIT` in game launch options (mangohud limiter works too), but it's not convenient.

### What did you expect to happen?

Working built-in frame limiter.

### Hardware

Asus ROG Ally

**Comment by Velgus** [comment]
Seems to also be the case on the Win Max 2 (6800U).

**Comment by mvasl** [comment]
It seems to me, that it only works if the game is vsync'ed. Without vsync framerate is not limited.

**Comment by kubepy** [comment]
Some information.
I am using `ghcr.io/ublue-os/bazzite-deck-gnome:39-testing-20240414`  images, the frame limiter is working well.
even I was in `40-stable` os trying to replace `gamescope` & `mangoapp` binary files to that `39-testing-20240414` version, the frame limiter still not work.
So it is not gamescope or mangoapp issue?

**Comment by vgf89** [comment]
I also have this issue on my LCD Steam Deck (beta client, but iirc it was also not working on stable client). Steam overlay frame rate limiter doesn't work in most games, but it worked fine back in SteamOS. In-game V-Sync setting has way more lag than the SteamOS/overlay frame rate limiter in most of my games...
