### ISSUE TITLE
HIP rendering is not available in Blender with RX 6700 XT

### ISSUE THREAD

**Issue by adms-hu** [ublue-os/bazzite#1051]
### Describe the bug

Blender can't recognize the GPU for HIP rendering with Cycles.

![image](https://github.com/ublue-os/bazzite/assets/20518615/c0e219b7-390e-4c2f-8aff-7975a046a72b)

### What did you expect to happen?

I installed the Fedora 39 based Bazzite first, and rebased, updated to the newer version on the next day. I ended up reinstalling the whole system with the newer Bazzite 3.0 image directly, but still no luck.

**I used the deck version both times.**

I tried to use and install the following Blender versions, both with the latest **3.6LTS** and the **4.1 latest** stable:

- Flatpak
- TAR, directly from Blender's site
- Steam version
- Fedora box with distrobox.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:6c949606735197c6582ada17078e27999cb256ea7cb0c19f08ce81681e2e1b79
                  Version: nightly (2024-04-26T17:03:38Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:46cc0a2f05f5bcad14dc300f1a023f4181cc907986241d89c06363a32d3a51b9
                  Version: main (2024-04-25T06:47:00Z)
```

### Hardware

Motherboard: MSI B250M Mortar
Memory: 16 GB RAM
CPU: Intel Core i7 7700K
GPU: ASUS TUF Gaming Radeon RX 6700 XT OC

**Comment by rayrayrayraydog** [comment]
@adms-git You asked me to check for this on my bazzite-deck HTPC w/ 6700XT.  Yes, I get the same message "no compatible devices" in the HIP menu in Blender.  GPU works fine in games and everywhere else you'd expect.

**Comment by tybird13** [comment]
I have the same issue, and this is blocking me from using Blender on Bazzite!

**Comment by tybird13** [comment]
I found the solution to my issue!

I was using the Flatpak version of blender, which apparently doesn't have the ROCm libraries. 

The solution was to download the tar.xz directly from blender.org
