### ISSUE TITLE
Blank Screen with Cursor on Startup

### ISSUE THREAD

**Issue by PixelRepak** [ublue-os/bazzite#1053]
### Describe the bug

The system displays a blank screen with only the mouse cursor visible upon powering up. This occurs consistently after a complete system shutdown.  A forced shutdown and restart resolves the issue temporarily, allowing the login screen to appear normally.

Steps to Reproduce:
1. Perform a complete system shutdown.
2. Power on the system.
3. Observe the screen

### What did you expect to happen?

The login screen should appear.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:c66c919da92842b6533f79554dab9031136aa4f5798c57b851ba4cc4dbf36da9
                  Version: 40.20240427.0 (2024-04-27T22:34:11Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:ebe3b398f20a2ff315cd8007dc475150b5bbe4cd8b0d0812312107a7cef2861f
                  Version: main (2024-04-25T06:46:12Z)
```

### Hardware

Operating System: Bazzite 40
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.7-302.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × Intel® Core™ i7-10700KF CPU @ 3.80GHz
Memory: 62.6 GiB of RAM
Graphics Processor: AMD Radeon RX 7800 XT
Manufacturer: ASUS

### Extra information or context

- A forced shutdown and restart resolves the issue temporarily.
- This behavior occurs every time the system is powered on after a complete shutdown.

**Comment by Equal8082** [comment]
I have the same issue, but when this issue began I also noticed extremely slow shutdown times because of something related to `systemd-journal-flush.service` hanging. I'm not sure if the issues could be related.

### Output of `rpm-ostree status`
```
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:c66c919da92842b6533f79554dab9031136aa4f5798c57b851ba4cc4dbf36da9
                  Version: 40.20240427.0 (2024-04-27T22:34:11Z)
            LocalPackages: lact-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:fcb21048f072f4f4a19f7daf8a9edcb3f0d66f8af34b61b2700866aa6aec2f58
                  Version: nightly (2024-04-26T17:02:20Z)
            LocalPackages: lact-0.5.4-0.x86_64
```

### Hardware
Operating System: Bazzite 40
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.7-302.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570 AORUS ELITE WIFI

**Comment by TheMCNerd2017** [comment]
I'm also having this same issue along with the long shutdowns after updating my laptop to Bazzite 40. I've already reported the issue in the bazzite-help discord channel a few days ago and uploaded logs there, but figured I would also post that information here too. I'm also on the latest Bazzite as of posting this (40.20240427.0), not the version listed below.

**rpm-ostree status output**
```
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:49623772190377d10594502a9fbba719bcd549964cd8a50daa931f7b79858c55
                  Version: main (2024-04-24T17:09:10Z)
          LayeredPackages: edk2-ovmf qemu virt-manager
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:fd93148ed9948d13811c14cb55d011f2ed17a061920753e841e02f4f75d8856d
                  Version: 39.20240116.0 (2024-04-19T17:16:29Z)
          LayeredPackages: edk2-ovmf qemu virt-manager
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"'
```

**Hardware**
CPU: Intel i9-13950HX
RAM: 128GB DDR5 5600 MHz ECC
GPU 1: Intel Raptor Lake-S UHD Graphics
GPU 2: Nvidia RTX 5000 Ada Generation Laptop GPU
Manufacturer: LENOVO
Product Name: 21FACTO1WW
System Version: ThinkPad P16 Gen 2

**Software**
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.7-302.fsync.fc40.x86_64
Graphics Platform: X11

**Logs**
[dmesg.txt](https://github.com/ublue-os/bazzite/files/15156543/dmesg.txt)
[journalctl.txt](https://github.com/ublue-os/bazzite/files/15156545/journalctl.txt)
[systemd-blame.txt](https://github.com/ublue-os/bazzite/files/15156546/systemd-blame.txt)

**Comment by RubyRezal** [comment]
This issue seems to have returned with Bazzite 44.

```
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:testing
                   Digest: sha256:17dc2f61b5c51cdafc42add10d0f6f61108e89ccbaa1f31f475399a219968243
                  Version: testing-44.20260515.2 (2026-05-15T17:54:48Z)
          LayeredPackages: coolercontrol liquidctl

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:ddb61d1ca94a2c7a0fc3b2ef45194a8d058df6fd7f1a26fa2612fb99aee6b9a4
                  Version: 44.20260515 (2026-05-15T07:01:06Z)
          LayeredPackages: coolercontrol liquidctl

```
