### ISSUE TITLE
Idk if this has been reported

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#1056]
Bazzites logo while updating steam client show up with a white background instead of bazzite background

[]![PXL_20240430_135514602.jpg](https://github.com/ublue-os/bazzite/assets/43518479/233302c1-2150-45e9-b48f-03dac9c8e124)

![PXL_20240430_135511107.jpg](https://github.com/ublue-os/bazzite/assets/43518479/e564fc71-3335-4604-beb1-c08de9c72811)

**Comment by Brunvik** [comment]
Happening on Steam Deck LCD and HTPC for me too

**Comment by KyleGospo** [comment]
Fixed in testing and will hit stable soon.
