### ISSUE TITLE
Boilr flatpak is broken on bazzite for steam deck, but works fine on my pc (bazzite nvidia)

### ISSUE THREAD

**Issue by totaltommygun** [ublue-os/bazzite#1057]
### Describe the bug

Whenever I try to open boilr on my deck it just never opens, and crashes.

[logs.txt](https://github.com/user-attachments/files/15910103/logs.txt)

### Output of `rpm-ostree status`

tristan@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:67bb1f9dd52a420f080fd67e71a60bb6f732c12bacab7d27476dfbdca601c757
                  Version: 40.20240427.0 (2024-04-27T22:36:59Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b8cc9aa32ee1dde43c920fcd373a0e7b5d3c89eca810c93402fea9969455bc5d
                  Version: main (2024-04-25T06:48:14Z)
          LayeredPackages: sunshine

### Hardware

Operating System: Bazzite 40
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.7-302.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Custom APU 0405
Memory: 11.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

### Extra information or context

edited to be easier to read

**Comment by herbalizer404** [comment]
same for me

**Comment by richplant** [comment]
Same issue on the ROG Ally, running `v40.20240508.0`

**Comment by nerdosity** [comment]
Can confirm the issue on my ROG Ally. 
I can confirm crashing in the same way: 

- boilr flatpak
- boilr appimage
- corekeyboard
