### ISSUE TITLE
Goverlay missing

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#1063]
### Describe the package

i notice goverlay was removed, is it going to be added back?

### Image

Desktop

**Comment by nicknamenamenick** [comment]
Nope.  Announcement will be made soon regarding the latest build of Bazzite.  Too many users were breaking their configurations unintentionally with it, so we found it was better to avoid the support tickets and remove it.  You can still install it with a Distrobox container or `rpm-ostree` but we will not be supporting broken configuration files when irresponsibly using the application.

**Comment by Dark-Thoughts** [comment]
How does one configure mangohud with an always enabled global profile without goverlay? What even were the supposed breakages it caused? What configurations got broken and how? The related news about it does not go into any details either.

**Comment by Dark-Thoughts** [comment]
Seems like you can still install the Fedora repo version of Goverlay. It's just slightly outdated at the moment.
`dnf install goverlay`
