### ISSUE TITLE
Cannot update on the steam deck

### ISSUE THREAD

**Issue by maximtitovich** [ublue-os/bazzite#1064]
### Describe the bug

When I launch update from gnome menu or type in ujust update, I get this error

### What did you expect to happen?

Update to succeed.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:abc2bd7e26359b519a2092ee8ad02893ec9fbf6ee6d4c862511846903f4a7360
                  Version: 39.20240415.0 (2024-04-16T02:23:14Z)
          LayeredPackages: openrazer-meta razergenie

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:abc2bd7e26359b519a2092ee8ad02893ec9fbf6ee6d4c862511846903f4a7360
                  Version: 39.20240415.0 (2024-04-16T02:23:14Z)
```

### Hardware

Jupiter

### Extra information or context

I tried to google any solution, no luck. Found a similar topic on discourse and then it disappeared. I'm new to Fedora linux, so might be obvious fix.

**Comment by KyleGospo** [comment]
Can you run `rpm-ostree update` and paste the full output of that command here?

**Comment by maximtitovich** [comment]
> Can you run `rpm-ostree update` and paste the full output of that command here?

Sure, forgot to attach it, sorry
`── 20:32:56 - System update ────────────────────────────────────────────────────
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
Checking out tree 8b91445... done
Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:matte-schwartz:sunshine copr:copr.fedorainfracloud.org:sentry:kernel-ba fedora-cisco-openh264 updates fedora rpmfusion-free-updates-testing rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates-testing rpmfusion-nonfree-updates rpmfusion-nonfree hardware_razer rpmfusion-nonfree-steam copr:copr.fedorainfracloud.org:phracek:PyCharm google-chrome rpmfusion-nonfree-nvidia-driver updates-archive
Updating metadata for 'copr:copr.fedorainfracloud.org:sentry:kernel-ba'... done
error: Updating rpm-md repo 'copr:copr.fedorainfracloud.org:sentry:kernel-ba': cannot update repo 'copr:copr.fedorainfracloud.org:sentry:kernel-ba': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://download.copr.fedorainfracloud.org/results/sentry/kernel-ba/fedora-40-x86_64/repodata/repomd.xml (IP: 13.33.141.35)
System update failed: 
   0: Command failed: /usr/bin/rpm-ostree upgrade
   1: /usr/bin/rpm-ostree failed: exit status: 1

Location:
   src/steps/os/linux.rs:273`

**Comment by KyleGospo** [comment]
`sudo rm /etc/yum.repos.d/_copr_sentry-kernel-ba.repo`

**Comment by maximtitovich** [comment]
> `sudo rm /etc/yum.repos.d/_copr_sentry-kernel-ba.repo`

Is it safe to delete this repo? Does it have some kernel things? I'm just assuming now based on the title.

**Comment by noelmiller** [comment]
> > `sudo rm /etc/yum.repos.d/_copr_sentry-kernel-ba.repo`
> 
> Is it safe to delete this repo? Does it have some kernel things? I'm just assuming now based on the title.
> 
> As a workaround, I rebased to kde version of the repo which is bazzite-deck and updates worked. Seems like to be an issue with gnome pre 3.0 image.
> I will maybe revert sometime later and try the fix above.

If you want to update to 3.0, you need to remove that copr repo. This got enabled in an image at some point and it should not be there. All of the kernel updates are handled in the image itself. The command Kyle is providing is what you will need to run before you update.
