### ISSUE TITLE
Steam Download Fix causes machine to reboot when downloading in Steam

### ISSUE THREAD

**Issue by jacobckelly** [ublue-os/bazzite#1073]
### Describe the bug

The Steam Download Fix which is enabled by default in Bazzite appears to cause the machine to reboot when downloading Steam games. Timing is intermittent and can't be locked down to a specific event whilst downloading, but the issue is resolved when the fix is removed.

### What did you expect to happen?

Machine not to reboot unexpectedly when downloading in Steam

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
Digest:sha256:811511ac2ef8cee7a15aa5fb84b0433704a2f78bd5e49b63f39ca3a20f56a93a
Version: 40.20240502.0 (2024-05-02T23:40:23Z)
LocalPackages: ctxusb-24.2.0.65-1.x86_64 ICAClient-24.2.0.65-0.x86_64
```

### Hardware

CPU: AMD 7950X3D
GPU: NVIDIA 4090
Motherboard: ASUS X670E Extreme
NIC: Marvell AQtion 10Gb Ethernet 

Internet connection is a 1Gbit link, but games often download faster due to other 10Gbit machines on the same network providing files.

### Extra information or context

Just to note this occurrs without the Citrix packages I layered onto the image as well.

**Comment by jacobckelly** [comment]
Just on a further note, every update Steam Download Fix appears to reapply itself, leading itself to if I forget to disable it, hard restarting my machine. I'm fine with the work around but any chance we can stop it reapplying?

**Comment by KyleGospo** [comment]
The download fix is a single bash script that changes a config in steam. It will never re-run as it has no mechanism to do that.
