### ISSUE TITLE
How to download ISOs without bazzite.gg?

### ISSUE THREAD

**Issue by sfyfedotcom** [ublue-os/bazzite#1076]
### Describe the bug

https://bazzite.gg doesn’t seem to be working, so I can’t download ISOs from there. How else can you download ISOs?

### What did you expect to happen?

The repository to have links to the ISO files (e.g. in releases)

**Comment by KyleGospo** [comment]
Site is hosted on GitHub and Cloudflare, it's up for me and up according to down detector, would take an act of god to take it down with that setup.

**Comment by sfyfedotcom** [comment]
Stuck on loading on my iPad

![image](https://github.com/ublue-os/bazzite/assets/10885475/6c09dabf-d6db-4ed5-bf2f-4d5e066dfebc)

“Unable to connect” on my ROG Ally

![image](https://github.com/ublue-os/bazzite/assets/10885475/62761929-c305-4d43-a1ab-69b3f8f5899f)

Everything else loading fine (e.g. IMDb.com) on both

**Comment by KyleGospo** [comment]
No, they're too large for GitHub. ISOs are stored on a paid Cloudflare R2 instance.

**Comment by sfyfedotcom** [comment]
Could links to them be added to the `README.md`?

I’m using Google DNS (8.8.8.8 and 8.8.4.4) on both devices.

**Comment by KyleGospo** [comment]
> Could links to them be added to the `README.md`?
> 
> I’m using Google DNS (8.8.8.8 and 8.8.4.4) on both devices.

Your 2nd pic shows failed to connect with download.bazzite.gg, which is the Cloudflare R2 instance. Direct links would confuse new users and fail to download for you the exact same way.
