### ISSUE TITLE
Joycond messes up things. isn't needed

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1079]
### Describe the bug

Joycond package messes up switch controllers and joycons. I've had many issues with switch controllers in the past (from not working on bazzite, to requiring joycond click of back buttons simultaneously to work, sometimes issues like two controllers in the list). I've disabled joycond with systemctl, restarted steam deck and everything works as it should now. I'm on oled. Please remove this package from bazzite, it's not needed, everything works out of the box and the controllers sometimes go crazy because of two drivers apparently.

### What did you expect to happen?

Connect switch controller. Joycond interferes.

**Comment by unicornsandcandies** [comment]
> This is needed for some edge cases, I'll look into disabling it by default to test it's removal.

Sometimes there's no input. Current workaround is restarting steam in game mode. It's not working only on the first boot. Worth looking into it

**Comment by RodoMa92** [comment]
Yeah, can confirm. Without it my joycon weren't recognizing any input at all and the service was default disabled. As soon as I started it, they immediately start reporting events in Steam. Players LED behave weirdly tho.

**Comment by unicornsandcandies** [comment]
> Yeah, can confirm. Without it my joycon weren't recognizing any input at all and the service was default disabled. As soon as I started it, they immediately start reporting events in Steam. Players LED behave weirdly tho. Not that I do want to use them, but since I had them around I've tested associating them to the Deck just to report back :)

From my tests, it works like this.

Without joycond:
- no input on first boot at all, requires bluetooth service restart, restarting steam through power options or suspending and unsuspending your deck to fix
- pairing works properly 
-  led light up like they should've, even with gamepad order indicator working

With joycond:
- input on steam game mode from start
- leds are flashing randomly, indicating that there's a pairing issue
- you can see controller in controllers tab but there's no input/extremely buggy input in games 

It's better with joycond turned off, because it fixes most issues. It's just that you need to restart bluetooth in some way to have input.
