### ISSUE TITLE
openrgb requires use rules - not included 

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1080]
### Describe the bug

OpenRGB needs udev rules that are impossible to add on silverblue based os using their script. I didn't found any way to add them. OpenRGB works only when ran with sudo su -c "flatpak run org.openRGB.openRGB".

### What did you expect to happen?

I expected openrgb to work out of the box

**Comment by KyleGospo** [comment]
These should be preinstalled, I believe the message about them is a false positive.

**Comment by unicornsandcandies** [comment]
> These should be preinstalled, I believe the message about them is a false positive.

Devices still can't be seen. Only when running as root

**Comment by gordon-boom** [comment]
There is a separate issue about this on the flatpak version of OpenRGB. Not sure how much the Bazzite devs can do to fix this. Perhaps you can install it using rpm-ostree instead? https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/3593

**Comment by unicornsandcandies** [comment]
> There is a separate issue about this on the flatpak version of OpenRGB. Not sure how much the Bazzite devs can do to fix this. Perhaps you can install it using rpm-ostree instead? https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/3593

I tried openrgb from rpm repo already and it's even worse. It doesn't see my device (being jsaux rgb dock) even when runninng it as root. On flatpak version the device is seen but only from root account. I'm pretty sure that openrgb has some big issues with running correctly on devices but none of this happens on a steam deck - I download openrgb from desktop flathub "shop", run it and my device is being seen. When something doesn't work I just use their udev script. 

While it might be an issue on the openrgb site, steamos is able to overcome it in some way. I can't say what's diffrent in steamos because I don't have acces to this os right now, but something seems to be done diffrently, to make devices visible.

**Comment by gordon-boom** [comment]
I had to add `acpi_enforce_resources=lax` to my boot args since some motherboards have issues with i2c. Maybe SteamOS includes this argument by default?

To view your kernel args in Bazzite, run:

```sh
rpm-ostree kargs
```

If you don't see `acpi_enforce_resources=lax`, add it with this:

```
rpm-ostree kargs --append=acpi_enforce_resources=lax
```

**Comment by unicornsandcandies** [comment]
> I had to add `acpi_enforce_resources=lax` to my boot args since [some motherboards have issues with i2c](https://gitlab.com/CalcProgrammer1/OpenRGB#:~:text=Some%20Gigabyte/Aorus%20motherboards%20have%20an%20ACPI%20conflict%20with%20the%20SMBus%20controller.%20Please%20add%20a%20kernel%20parameter%20to%20resolve%20this%20conflict.). Maybe SteamOS includes this argument by default?
> 
> To view your kernel args in Bazzite, run:
> 
> ```shell
> rpm-ostree kargs
> ```
> 
> If you don't see `acpi_enforce_resources=lax`, add it with this:
> 
> ```
> rpm-ostree kargs --append=acpi_enforce_resources=lax
> ```

Unfortunately it didn't help
