### ISSUE TITLE
[bug?] [3.0.1] blue effect on bottom section of screen

### ISSUE THREAD

**Issue by BamsTheSergal** [ublue-os/bazzite#1081]
### Describe the bug

In desktop mode, I have a weird blue effect on the bottom part of my steam deck screen 

![PXL_20240506_134648811](https://github.com/ublue-os/bazzite/assets/12705993/1e32f806-3ccb-401d-a74a-eedd782feae5)
![PXL_20240506_134740546~2](https://github.com/ublue-os/bazzite/assets/12705993/c94fe7d9-b8e7-45bc-9e7c-2bd9f15a36fb)

### What did you expect to happen?

Not sure if it's something I did, but it showed up after update 3.0.0

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:c02ece6452dd8b2017f1e3b687f8107cccd0d8a7453399fd9b642df9cdb5cca9
                  Version: 40.20240502.0 (2024-05-02T23:42:25Z)
          LayeredPackages: kpeoplevcard
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:c02ece6452dd8b2017f1e3b687f8107cccd0d8a7453399fd9b642df9cdb5cca9
                  Version: 40.20240502.0 (2024-05-02T23:42:25Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Jupiter

**Comment by KyleGospo** [comment]
I believe this is a known KDE 6 bug and should be fixed soon.
