### ISSUE TITLE
Gamemode saturation switches when a mouse cursor is active.

### ISSUE THREAD

**Issue by AlexEaton** [ublue-os/bazzite#1085]
### Describe the bug

I run Bazzite-Deck Image on my Desktop PC with a RX 7900XT GPU and use Gamescope on a daily basis.

Whenever the mouse cursor is active the colour saturation looks a lot better while when the mouse cursor is inactive it looks more washed out/grey. 

This can be quite annoying for example watching a video since the content looks washed out unless I'm constantly moving the mouse cursor.

I've tested this on multiple TV screens and updated to the latest Bazzite version also tested with the steam deck on the same TV's and the issue never happened so I can guarantee it has nothing to do with any TV settings.

I have native colour temperature enabled within the Steam settings and I think it seems to be switching between the two when the mouse cursor is active it's using the Steam Deck's  colour settings while inactive I suspect it's using the native settings. It does this regardless if native colour temperature is enable or not in the steam settings.

This issue actually goes away if HDR is enabled however I'm not fond of having HDR enabled 24/7 due to the eyestrain it gives me.

I should mention I have Deckyloader but I tried disabling all my CSS themes and didn't see a change even when Decky wasn't injected.

I wasn't really sure on how to word this so sorry if some of it seems confusing I also don't use github that much.

### What did you expect to happen?

Colour saturation should not change regardless of if mouse cursor is active or not.

### Hardware

CPU: AMD Ryzen 5 5600x
GPU: XFX Speedster MERC310 AMD Radeon RX 7900XT Black (20GB VRAM)
Motherboard: Asus Rog Strix 570-F
Memory: 4x Corsair Vengeance Pro DDR4 8GB 4000Mhz (32GB)
PSU: Corsair RM750x Gold

**Comment by AlexEaton** [comment]
Update: Found a fix it seems setting colour vibrance to 0 on the steam settings fixes this.

**Comment by nickastaldo** [comment]
> Update: Found a fix it seems setting colour vibrance to 0 on the steam settings fixes this.

Wow, 2 years later and your fix corrected my problem! I didn't have exactly the same issue as you, but my colors would go from looking good to washed out randomly. Sometimes I could flip flop between it looking good and bad depending on what I was doing; for instance, in slay the spire, hovering over the cards triggered it looking bad, but once I click a card and the arrow popped up, it would look good again. Every time. And, of course, navigating through the steam menu did random color/banding issues. I tried resolution changes, toggling HDR on/off, vrr on/off, etc., but the only thing that worked was setting color vibrance to 0. Thank you!
