### ISSUE TITLE
Wrong key layout in LUKS decryption screen

### ISSUE THREAD

**Issue by itz-Jana** [ublue-os/bazzite#1087]
### Describe the bug

I installed Bazzite 40 using the official installer.
I changed my keyboard layout to DE and enabled Full Disk Encryption, where it specifically mentioned that I am using the DE keyboard layout.

After reboot my password didn't work and I realized that the LUKS decryption screen isn't using the proper keyboard layout.

I think I had a similar issue in the past with normal Silverblue and to fix it, I had to enable the regeneration of the initramfs.
Now I'm wondering if there is something that can be done to fix the root cause of the issue.

### What did you expect to happen?

I expected the correct keyboard layout to be configured on the LUKS decryption screen.

**Comment by Rakantor** [comment]
I had the same issue and did some research. It turns out this is a known limitation of Fedora Silverblue. As a workaround, run
```
rpm-ostree initramfs-etc --track=/etc/vconsole.conf
```
and reboot. Or try these [alternative workarounds](https://shivering-isles.com/2023/11/silverblue-luks-preboot-keyboard-layout).

Until a permanent fix is found, it might be helpful to mention this limitation in the installation guide.

---

From the [Fedora Docs](https://docs.fedoraproject.org/en-US/fedora-silverblue/installation/#known-limitations):

> **The keyboard layout selected during installation is not used for the LUKS unlock screen of Fedora Silverblue.**
> 
> Regardless of your selection during the installation process, the keyboard layout available for the LUKS unlock screen will default to en-US (English - United States of America). You can workaround this issue by running the following command on the first boot after the installation:
> 
>  `rpm-ostree initramfs-etc --track=/etc/vconsole.conf`
> 
> To avoid struggling when having to type the LUKS passphrase for the first time, you could set during installation a disk encryption passphrase that is easy to type with the en-US keyboard layout, and then change it to the passphrase that you actually want through the GNOME [Disks](https://apps.gnome.org/en-GB/app/org.gnome.DiskUtility) app.
> 
> See [bug #1890085](https://bugzilla.redhat.com/show_bug.cgi?id=1890085) (Red Hat Bugzilla) and [issue #3](https://github.com/fedora-silverblue/issue-tracker/issues/3) (Fedora Silverblue issue tracker) for details.
