### ISSUE TITLE
Desktop mode artifacts on Steam Deck OLED

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1089]
### Describe the bug

Desktop mode has weird artifacts (it's hard for me to explain). It happens most of the time but, what's curious to me, not always (on some boots, it's just okay). Here's a  video of this:

https://youtu.be/9k3uq6hKn0I
(please don't mind the audio issues, my microphone is currently broken)

### What did you expect to happen?

I expected the bazzite to communicate with display properly.

### Hardware

Steam Deck OLED

### Extra information or context

This DOESN'T happen on steamos. The issue never occured to me when the desktop mode is on with the deck plugged to tv (I can't replicate the issue on external screen). (Obviously) I'm using gnome image.

I'm not layering any packages nor changing anything in the config. Not even in distrobox. Issue is present from fresh install.

**Comment by KyleGospo** [comment]
Should be fixed soon, AMD Kernel bug.

**Comment by unicornsandcandies** [comment]
> Should be fixed soon, AMD Kernel bug.

Do you have any issue I can track or ETA when it will be fixed? Kernel changes can progress very slowly and while I can live without desktop mode, I would be happier having functional os

**Comment by uT27SB8Ju** [comment]
Same problem here. I also encounter heavily bitcrushed audio on Steam games (OBS does not record it but it is present with or without a headset) and gaming mode is barely functionning.

**Comment by KyleGospo** [comment]
> Same problem here. I also encounter heavily bitcrushed audio on Steam games (OBS does not record it but it is present with or without a headset) and gaming mode is barely functionning.

Audio issue is known, that is why we're not recommending OLED for most people right now. 

Can you tell me more about the gaming mode issue? I've been playing games on mine all week and haven't come across anything like that.

**Comment by KyleGospo** [comment]
> > Should be fixed soon, AMD Kernel bug.
> 
> Do you have any issue I can track or ETA when it will be fixed? Kernel changes can progress very slowly and while I can live without desktop mode, I would be happier having functional os

I don't at this time, there's a reason we're not recommending the OLED right now.

**Comment by uT27SB8Ju** [comment]
> Audio issue is known, that is why we're not recommending OLED for most people right now.

No problem. I know what I was getting into. I'm happy to help solve problems.

**Comment by uT27SB8Ju** [comment]
Sorry, I'm don't speak english. In my next message, I will write without caring much about grammar and stuff...

**Comment by uT27SB8Ju** [comment]
All of the pictures in this post are taken after a reboot of my steam deck OLED.


![signal-2024-05-09-170433_002](https://github.com/ublue-os/bazzite/assets/108619930/88764ddd-8d8f-4bf3-83b9-fe776c938a0e)
1. Screen after rebooting

![signal-2024-05-09-170433_003](https://github.com/ublue-os/bazzite/assets/108619930/e12e6ef3-3063-4ad5-a9b1-20bae61404c2)
2. I click on Hollow Knight

![signal-2024-05-09-170433_004](https://github.com/ublue-os/bazzite/assets/108619930/0c29545d-171b-404f-b5a7-c840247bdc08)
3. Pressing B or the Steam button brings up the steam menu. Pressing the quick access menu button brings up the quick access menu. I can't click on anything on the steam menu. I can access everything on the quick access menu, except for decky loader that displays this error screen. If I reopen the quick access menu, decky isn't there anymore.
 
![signal-2024-05-09-170433_005](https://github.com/ublue-os/bazzite/assets/108619930/95e64ce3-80f5-4bb5-9acb-89fd1ef695e2)
4. I click with the mouse or the touchpad on refresh, than I can go back in the home or in the settings (I noticed that the clicking sound of goings through games and stuff is gone, but not the other system sounds)

![signal-2024-05-09-170433_006](https://github.com/ublue-os/bazzite/assets/108619930/53182322-83b6-48bd-a8fc-469a5ed21c29)
5. I click on Brawlhalla (same problem)

![signal-2024-05-09-170433_007](https://github.com/ublue-os/bazzite/assets/108619930/edbb8971-66ea-443d-8357-c8c072978c03)
![signal-2024-05-09-170433_008](https://github.com/ublue-os/bazzite/assets/108619930/4b1bf119-7dc5-4938-9014-860e4a8cb013)
6. I can read news

![signal-2024-05-09-170433_009](https://github.com/ublue-os/bazzite/assets/108619930/8681a4f2-403f-42ab-98f4-c76265e070da)
7. I can access my library, the store, my media, etc...

8. I did the system update and nothing changed (at least on gaming mode)

Good luck

**Comment by unicornsandcandies** [comment]
> > > Should be fixed soon, AMD Kernel bug.
> > 
> > 
> > Do you have any issue I can track or ETA when it will be fixed? Kernel changes can progress very slowly and while I can live without desktop mode, I would be happier having functional os
> 
> I don't at this time, there's a reason we're not recommending the OLED right now.

I completely understand. I may not know how things work but how exactly will it be fixed soon if no one even reported it yet? This may be a little digression from the issue but I genuinely don't understand what to expect here.

There's this issue:
https://gitlab.freedesktop.org/drm/amd/-/issues/3361

Is this by any chance connected? Is it worth tracking this?

**Comment by unicornsandcandies** [comment]
Issue seems to be solved with this addon: 

https://addons.mozilla.org/en-US/firefox/addon/enhanced-h264ify/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

That may be an issue with AV1 codec. I'm still testing it and will update if anything more comes up.

**Comment by shymega** [comment]
If someone could test with the latest Bazzite, and report back - we can then determine if this bug is still present. Thanks.
