### ISSUE TITLE
SD card mount point is not mmcplk0p1

### ISSUE THREAD

**Issue by Traumlewis** [ublue-os/bazzite#1092]
The default SD card path from Stream os is /run/media/mmcblk0p1 .
But the phad from bazzite OS is /run/media/(OS user name)/(SD Card Name) .

This is a problem because the program and decky plugins for SteamOS are standardized on it.

Hardware:
Steamdeck (1TB)

**Comment by KyleGospo** [comment]
That has not been true on SteamOS for many versions now. 

They create a symlink to the old path for legacy support reasons which I can verify is working on all of my hardware.

**Comment by Traumlewis** [comment]
> That has not been true on SteamOS for many versions now.
> 
> They create a symlink to the old path for legacy support reasons which I can verify is working on all of my hardware.

Perfect, then I can go back to the official Steam OS. Because that doesn't make any sense at all. If the system does not control the standard file paths. This only leads to a lack of decky plugins.

**Comment by KyleGospo** [comment]
That's fine, when you do please be sure to verify what I said is correct.

I would also like to know which plugins you're having issues with, we test most of them.
