### ISSUE TITLE
Some games don't work since 40.20240505 update

### ISSUE THREAD

**Issue by lyfja** [ublue-os/bazzite#1093]
### Describe the bug

Since version 40.20240505.0 (stable), games running with Wine/Proton do not work on my machine. They crash shortly after launch. So far this has happened with Apex Legends, Warframe (both Steam) and the Honkers Railway Launcher (won't mention the actual game's name as per the project's request) which was installed via Flatpak.
(Those are the only games I've tried to play in those times.)

### What did you expect to happen?

The games should run normally without crashing.

### Output of `rpm-ostree status`

```shell
// (I've already reverted back to a deployment where my games work)

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:db36ce4506fbe78ffdac184793e18ecbfd23a900a933d8f96178608f8545e5bc
                  Version: 40.20240502.0 (2024-05-02T23:35:31Z)
                   Pinned: yes

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:c66c919da92842b6533f79554dab9031136aa4f5798c57b851ba4cc4dbf36da9
                  Version: 40.20240427.0 (2024-04-27T22:34:11Z)
                   Pinned: yes
```

### Hardware

Operating System: Bazzite 40
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.7-303.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C56
System Version: 1.0

### Extra information or context

![Screenshot_20240508_013156](https://github.com/ublue-os/bazzite/assets/45209212/93ea3b08-49f3-4c66-ac0e-90c2a71e44fc)
Warframe's error message ~~(which makes me assume that this got something to do with Wine)~~

Honkers Railway Launcher had a generic error message, and Apex Legends didn't have an error message at all.

**Comment by rekh127** [comment]
Interesting that 40.20240502.0 is working for you but later isn't!  For me at one other person in the HDR thread #1084 

20240502 isn't working (which I ran into last weekend) but 20240508 is working for me

**Comment by lyfja** [comment]
20240508 still isn't working for me. I tested a few more games that I have installed:

Among Us: works
Counter-Strike 2: **crashes**
Slay the Princess: works
Ultrakill: works
The Finals: **crashes** (same error message as Warframe)
Cities: Skylines: works
Undertale: works
Cyberpunk 2077: works
Baldur's Gate 3: works

Since CS2 crashes I assume this issue isn't related to Wine? Since it runs natively. And a lot of other games, even complex 3D ones, *do* work. Still not sure what's going on here. One of the things that was updated between 02 and 05 was the kernel, maybe the problem lies there. No idea

**Comment by KyleGospo** [comment]
You are being bit by a new kernel bug, but it's actually doing you a favor. You can fix this by enabling smart access memory in your bios, having it disabled has been kneecapping your performance. 

This is also sometimes called above 4G decoding.

**Comment by lyfja** [comment]
This seems to have solved the issue, thank you!! 

(And the setting in my bios is called "Above 4G memory/Crypto Currency mining" lmao)

**Comment by d10sfan** [comment]
For me, I'm having the same problem of some proton games not working, with a very similar error.

My BIOS does not appear to have the option for above 4g memory, etc. I've disabled csm (which was required to get bazzite to work in the first place). What would be a good solution for this?

**Comment by KyleGospo** [comment]
You may want to look into update in your bios, not having this option is drastically harming your performance on anything relatively modern.

**Comment by d10sfan** [comment]
I'm on the latest bios it looks like my motherboard doesn't support it

**Comment by rekh127** [comment]
https://github.com/xCuri0/ReBarUEFI

You may be able to add it.

But this seems like a lot to work around some kernel bug.

**Comment by d10sfan** [comment]
Yeah that does seem like alot of work and concerned about messing about with the bios like that.

Downgrading to the previous may 2 release worked ok, hopefully the newer kernel will work. I also asked the motherboard company (asrock) if they are able to provide a newer bios, although it's a pretty old motherboard so will see
