### ISSUE TITLE
After the update, the interface on the steam deck screen became strange. GNOME.

### ISSUE THREAD

**Issue by grisha765** [ublue-os/bazzite#1107]
### Describe the bug

After the update, interface elements began to behave incorrectly

### What did you expect to happen?

So that the size of the elements is normal, as before.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:ebb2a4a456d1222232c659e69bb5269d7ecaf6058d531687eab05cb6abf804d0
                  Version: 40.20240510.0 (2024-05-10T17:03:10Z)
          LayeredPackages: htop libvirt virt-manager
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:d15abd0fafe8d008e4d9c1d6a2786ab812dacdd9876566858f6a65df761a0f44
                  Version: 39.20240419.0 (2024-04-19T17:12:50Z)
          LayeredPackages: htop libvirt virt-manager
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" '
```

### Hardware

Jupiter

### Extra information or context

![Снимок экрана от 2024-05-11 23-16-30](https://github.com/ublue-os/bazzite/assets/94765905/dde88a1d-1c08-4d1b-b8ff-343d2607afd7)

**Comment by KyleGospo** [comment]
What's your display scaling set to?

**Comment by grisha765** [comment]
> What's your display scaling set to?

100%

**Comment by KyleGospo** [comment]
Not sure I'm afraid, I'm unable to reproduce this on either my OLED or LCD

**Comment by grisha765** [comment]
It was necessary to put 150% and then back to 100% and everything would be solved

**Comment by KyleGospo** [comment]
What a weird bug, but thank you for letting us know the solution.
