### ISSUE TITLE
Game Freeze after some time

### ISSUE THREAD

**Issue by martinville** [ublue-os/bazzite#1110]
### Describe the bug

Bazzite worked great on my RogAlly.
But unfortunately after some time some games become very slow. The FPS will drop to 1 FPS and then eventually freeze. After freezing a hardboot is required.

It also seems to happen when fiddling with the right hand side menu whilst testing different TDP settings. If you constantly go back and forth between the popup menu and a game it seems to cause it to freeze eventually. Feels like its leaking memory.

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

**Comment by martinville** [comment]
I ignorantly ran games at a TDP of 30w not realizing I'm pushing the hardware.
I don't think this is an issue with the software.

Can probably be closed.

**Comment by nerdosity** [comment]
> I ignorantly ran games at a TDP of 30w not realizing I'm pushing the hardware. I don't think this is an issue with the software.
> 
> Can probably be closed.

It's not a problem with hardware, it's a problem of wrong fan curves.
Push the hardware how much you feel inspired, but enable custom curves, default ones weren't working with me.

**Comment by DanielK1511** [comment]
> > I ignorantly ran games at a TDP of 30w not realizing I'm pushing the hardware. I don't think this is an issue with the software.
> > Can probably be closed.
> 
> It's not a problem with hardware, it's a problem of wrong fan curves. Push the hardware how much you feel inspired, but enable custom curves, default ones weren't working with me.

Im Having the same issue stated above, would you mind sharing how to set up custom fan curves? Is it done in BIOS?

**Comment by Sakurainy** [comment]
I have same problem,does set fan curves working?

**Comment by konradmazi12** [comment]
> > > I ignorantly ran games at a TDP of 30w not realizing I'm pushing the hardware. I don't think this is an issue with the software.
> > > Can probably be closed.
> > 
> > 
> > It's not a problem with hardware, it's a problem of wrong fan curves. Push the hardware how much you feel inspired, but enable custom curves, default ones weren't working with me.
> 
> Im Having the same issue stated above, would you mind sharing how to set up custom fan curves? Is it done in BIOS?

Hi, if you are using Handheld Daemon on Deck/Ally etc, try accessing custom fan curves via this software, there is checkmark to enable cfc.

**Comment by konradmazi12** [comment]
> I have same problem,does set fan curves working?

Kinda, its probably more like ram leak issue. I had to set up custom fan curves and then limit my vram usage and also increased my zram. Thermals could also cause this, i am using non factory nvme, first i thought it was it that was overheating and causing trouble but turned out it was cpu/gpu and zram.
