### ISSUE TITLE
Can't install Bazzite

### ISSUE THREAD

**Issue by Crostrix** [ublue-os/bazzite#1111]
### Describe the bug

I went and booted my USB Flash Drive and i chose: "Install bazzite without checks." So i clicked it and it booted then when the gui was launching i saw a gray screen, and after a few seconds i got an error: "A Problem Has Occurred" and then it shuts down.

### What did you expect to happen?

I expected an GUI to pop-up an give me the Fedora installer. But it never happened, and when i tried in a VM it works.

### Output of `rpm-ostree status`

```shell
I cant
```

### Hardware

I have an ASUS x515ea with secure boot off, and Fast Boot off, I run Arch Linux.

**Comment by Crostrix** [comment]
It was an Python Error!

**Comment by HiveHivemind** [comment]
Same problem here, it halts on the EFI partitioning process in Anaconda
