### ISSUE TITLE
white line on boot in deck image

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1113]
### Describe the bug

That's how it looks: 
![20240512_231823](https://github.com/ublue-os/bazzite/assets/112720004/58b995c3-8da4-43e9-b9ab-0ce30c3ab07e)

It's possible that there's a patch for it already and it's possible to fix, see:

![SmartSelect_20240512_232058_Firefox Nightly](https://github.com/ublue-os/bazzite/assets/112720004/5432aea4-4007-4511-8962-ecc1121f2bf1)
![SmartSelect_20240512_232109_Firefox Nightly](https://github.com/ublue-os/bazzite/assets/112720004/e5626cb7-72c5-4630-bf3d-4e87671cd67e)

https://store.steampowered.com/news/app/1675200/view/4213757668851885208

### What did you expect to happen?

Boot without graphical artifacts 

### Hardware

Steam Deck OLED

**Comment by KyleGospo** [comment]
Deck firmware thing, out of our control entirely.
