### ISSUE TITLE
i cant enter gaming mode

### ISSUE THREAD

**Issue by robotboy89** [ublue-os/bazzite#1118]
### Describe the bug

there is no return to gaming mode short cut on the desktop or anything on the desktop just the taskbar apps

### What did you expect to happen?

i was expecting to be able to use bazzite as a console os sort of thing

### Output of `rpm-ostree status`

```shell
State: busy
Transaction: upgrade 
  Initiator: client(id:cli dbus:1.239 unit:ublue-update.service uid:0)
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:a0fdd473cf0dec739237bdd9d7e92387f680d0f9aaa3e7ead73772012aea99dd
                  Version: 40.20240501.0 (2024-05-02T07:19:23Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:d083443e63f59669047868dfb86a168e39967f4ae7e9a3ac63bbdedb0ef7bc6b
                  Version: main (2024-04-25T06:51:05Z)
```

### Hardware

a dell g3 3579 laptop

### Extra information or context

not sure if this is me having a problem with the os or if it doesnt even exist for my thing or im just being a moron

**Comment by robotboy89** [comment]
in the mean time ima try and reinstall

**Comment by KyleGospo** [comment]
No gaming mode on nvidia, their drivers can't handle it
