### ISSUE TITLE
Xbox controller connected via wireless adapter does not shut off with system

### ISSUE THREAD

**Issue by jnlsn** [ublue-os/bazzite#1120]
### Describe the bug

An xbox core controller is connected to my HTPC via the official USB wireless adapter. When I shut off Bazzite I expect it to also turn off the controller. Instead the controller enters pairing mode (the xbox logo starts flashing) and needs to have the battery removed in order to stop.

### What did you expect to happen?

I expected the xbox controller to shut off when the system shuts off.

**Comment by SaulGoodman1337** [comment]
ChimeraOS does it right

**Comment by ZainAjam** [comment]
I also had this. It stopped after a reboot it seems. Hasn't yet happened again since yesterday when I first setup everything. 

When you xbox controller goes back in to pairing mode, does it actually link with the dongle again and then immediately wake up the htpc?
