### ISSUE TITLE
Black screen after update

### ISSUE THREAD

**Issue by pacoa-kdbg** [ublue-os/bazzite#1123]
### Describe the bug

After today update using 
`ujust update`  
I get a black  screen at boot.

I can use `esc` during boot to see the console but at some point it becomes black too.

If I switch early to TTY(x) it freezes at the same point the log becomes black screen 

### What did you expect to happen?

Bazzite boots to SteamGUI

### Output of `rpm-ostree status`

```shell
No way to do it
```

### Hardware

GPD Win mini 2024
CPU : 8840U
RAM: 32GB
Storage: 2TB

**Comment by pacoa-kdbg** [comment]
Booted ostree:1 and it went fine.

rolledback with 
rpm-ostree rollback

After that, booted again to ostree:0 just fine.

Tried to update again to see if current update was still causing issues and I can confirm it is

**Comment by wolfyreload** [comment]
It might be worth pinning your currently working version with `sudo apt ostree pin 0` to be on the safe side. Quite a few people have reported the blank screen issue. I hope it will get resolves soon.
