### ISSUE TITLE
Steam Deck Controller Left Stick very buggy with Mouse and Keyboard Profile

### ISSUE THREAD

**Issue by lm209** [ublue-os/bazzite#1132]
### Describe the bug

All Games without Gamepad Support, I play with the mouse and keyboard profile. The problem is that the left stick either reacts with a delay or it goes completely crazy. It can't be the controller because this problem also occurs on my PS5 controller. For example, I want to go forward and have to move the stick several times and when it moves it doesn't stop moving.

### What did you expect to happen?

this must definitely be a bug, because before everything worked fine

### Hardware

Steam Deck LCD 256GB

**Comment by KyleGospo** [comment]
Fixed in latest, bug in Valve's gamescope.
