### ISSUE TITLE
Steam Deck Bazzite/Fedora installer Resolution Unusable

### ISSUE THREAD

**Issue by pastram-i** [ublue-os/bazzite#1136]
### Describe the bug

When the installer starts on the Steam Deck, the resolution seems to be too small, so I can’t get past the keyboard/language setup. 

I’ve tried to boot the installer with both the Steam Deck only, and with an external monitor attached. Both routes only use the Steam Deck display for the installer (attached monitor just show a grey “background” screen). 

I’ve also tried to boot using Troubleshooting -> Basic Graphics Mode. However, this just never boots an installer and just sits on a black screen. 

![IMG_2664](https://github.com/ublue-os/bazzite/assets/73852781/29520084-e9d2-4b0b-a694-ea322044978d)
![IMG_2663](https://github.com/ublue-os/bazzite/assets/73852781/3dcc7929-0a9d-4bc9-8805-b58c1ae23c97)

### What did you expect to happen?

Installer UX is usable, and I can progress through the install settings. 

### Output of `rpm-ostree status`

```shell
N/A
```

### Hardware

Steam Deck (NON OLED) 256GB

### Extra information or context

N/A

**Comment by lm209** [comment]
> ### Describe the bug
> When the installer starts on the Steam Deck, the resolution seems to be too small, so I can’t get past the keyboard/language setup.
> 
> I’ve tried to boot the installer with both the Steam Deck only, and with an external monitor attached. Both routes only use the Steam Deck display for the installer (attached monitor just show a grey “background” screen).
> 
> I’ve also tried to boot using Troubleshooting -> Basic Graphics Mode. However, this just never boots an installer and just sits on a black screen.
> 
> ![IMG_2664](https://private-user-images.githubusercontent.com/73852781/331397598-29520084-e9d2-4b0b-a694-ea322044978d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzIyOTQsIm5iZiI6MTcxNTk3MTk5NCwicGF0aCI6Ii83Mzg1Mjc4MS8zMzEzOTc1OTgtMjk1MjAwODQtZTlkMi00YjBiLWE2OTQtZWEzMjIwNDQ5NzhkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxODUzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTY4YWY5NWJiMzc0MDNhNDcyY2QyMzQyOTNkYWUyOTc4Njc2NmU4MDIzMWNjMzg2ODBkNTkxNjUyZDI5OWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mpRVVVDTyrrFCHTzZYUJDwUYk0tl-mCE8OVrkeIu6Uw) ![IMG_2663](https://private-user-images.githubusercontent.com/73852781/331397600-3dcc7929-0a9d-4bc9-8805-b58c1ae23c97.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzIyOTQsIm5iZiI6MTcxNTk3MTk5NCwicGF0aCI6Ii83Mzg1Mjc4MS8zMzEzOTc2MDAtM2RjYzc5MjktMGE5ZC00YmM5LTg4MDUtYjU4YzFhZTIzYzk3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxODUzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzRkZDI5ZWFkNWM2NzIyYmE0YjZkZDViNmMxODgyNThmNmUxMDIzZWI3MTU2NWYyZjhhM2MzODAzZjAyNTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j1EJHsN3sX8Bc5GRhCxmLcOc2U0I-CiCrWfG0svC7-M)
> 
> ### What did you expect to happen?
> Installer UX is usable, and I can progress through the install settings.
> 
> ### Output of `rpm-ostree status`
> ```shell
> N/A
> ```
> 
> ### Hardware
> Steam Deck (NON OLED) 256GB
> 
> ### Extra information or context
> N/A

Yes, this is a known problem. Do you have the option of connecting the Steam Deck to the TV?

**Comment by lm209** [comment]
That's a known Bug. Only way is with a External Monitor and Troubleshooting - Basic Graphics Mode. If the Installer not started, try it a few Times. Also make Sure Storage Mode in the Bios IS Set to XHCI Not DRD

**Comment by pastram-i** [comment]
@lm209 - I've tried to attach to an external monitor, but this didn't change anything for me. 

Instead, the deck was still used as the "primary" monitor so it appeared as no change, and the external was "secondary" so only showed a light grey background. 

When I tried this on Basic Graphics Mode, I restarted many times but no installer ever presented itself. 

I did also confirm XHCI mode.

**Comment by lm209** [comment]
> @lm209 - I've tried to attach to an external monitor, but this didn't change anything for me.
> 
> Instead, the deck was still used as the "primary" monitor so it appeared as no change, and the external was "secondary" so only showed a light grey background.
> 
> When I tried this on Basic Graphics Mode, I restarted many times but no installer ever presented itself.
> 
> I did also confirm XHCI mode.

OK, that's weird. I've had the same problem. What I did back then was use an external keyboard and the tab key to keep switching in the installer (the language, account and installation path are important).

**Comment by hahelui** [comment]
Same here

**Comment by lm209** [comment]
> Same here

If the Graphics Basic Mode does not work then I can only recommend using an external keyboard and the Tab key

**Comment by pastram-i** [comment]
> > Same here
> 
> If the Graphics Basic Mode does not work then I can only recommend using an external keyboard and the Tab key

This is what I did. It’s not pleasant but after about 3-4 hours of stumbling around I managed to install. 

However - it seems that Desktop mode may be plagued with a similar (related?) issue? L

Mostly anfter install, GUI starts with KDE.  But once you click on the menu in the lower left plasmashell crashes.  Upon reboot, when going into desktop mode any time after that, plasmashell crashes straight away. 

There’s not really any indication that it’s directly related, except that Desktop mode appears to render in the same “low resolution”, in the fraction of a second I can see it before crashing.

**Comment by pastram-i** [comment]
> > > Same here
> > 
> > 
> > If the Graphics Basic Mode does not work then I can only recommend using an external keyboard and the Tab key
> 
> This is what I did. It’s not pleasant but after about 3-4 hours of stumbling around I managed to install.
> 
> However - it seems that Desktop mode may be plagued with a similar (related?) issue?
> 
> Mostly that install, GUI starts with KDE. But once you click on the menu in the lower left plasmashell crashes. Upon reboot, when going into desktop mode any time after that, plasmashell crashes straight away.
> 
> There’s not really any indication that it’s directly related, except that Desktop mode appears to render in the same “low resolution”, in the fraction of a second I can see it before crashing.

Moved this Desktop mode specific issue to [this](https://github.com/ublue-os/bazzite/issues/1145) ticket.

**Comment by pastram-i** [comment]
@KyleGospo - does the upstream fix on [1145](https://github.com/ublue-os/bazzite/issues/1145) resolve the installer as well?

**Comment by HikariKnight** [comment]
Just going to comment here that for some reason booting the ISO through ventoy to my knowledge fixes this issue and we have no idea why

**Comment by HikariKnight** [comment]
Resolution is fixed in the newer isos
