### ISSUE TITLE
CPU clocks always at 3.5GHz

### ISSUE THREAD

**Issue by zqpvr** [ublue-os/bazzite#1138]
### Describe the bug

In gamemode idle and in games the cpu stays at 3.5GHz

### What did you expect to happen?

it to not be at max while idle.

### Output of `rpm-ostree status`

```shell
deck@steamdeck:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:9ca13cc430ac17f681d5e5f04cdb2ab1083c66b517f722f63c1c6325d918db76
                  Version: 40.20240514.0 (2024-05-16T21:21:55Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:9ca13cc430ac17f681d5e5f04cdb2ab1083c66b517f722f63c1c6325d918db76
                  Version: 40.20240514.0 (2024-05-16T21:21:55Z)
```

### Extra information or context

I will upload a video later

**Comment by lm209** [comment]
This can be the CPU Boost. Do you use Decky Loader?

**Comment by lm209** [comment]
Install SimpleDeckyTDP and deactivate the CPU Boost. Restart and activate it again. It fixed it for me. And If you have PowerTools installed, i recommend to uninstalling it. It can break some tweaks from Bazzite.
