### ISSUE TITLE
'obs-vkcapture' binaries are missing from recent images

### ISSUE THREAD

**Issue by EPOCHvoyager** [ublue-os/bazzite#1141]
### Describe the bug

The COPR for it is still listed in the Containerfile and seems to be building fine, with no recent concerning commits, so I'm unsure as to what could be going on:

```
$ ls /usr/share/vulkan/implicit_layer.d/
latencyflex.json         MangoHud.x86_64.json  VkLayer_FROG_gamescope_wsi.x86_64.json
libMangoApp.x86_64.json  MangoHud.x86.json     VkLayer_FROG_gamescope_wsi.x86.json
libMangoApp.x86.json     vkBasalt.json         VkLayer_MESA_device_select.json
```

Any other directories specified in `CMakeLists.txt` in the upstream repo for installation are nowhere to be seen.

### What did you expect to happen?

I expected to be able to use `obs-gamecapture %command%` or `env OBS_VKCAPTURE=1 %command%` in a Steam game's launch options, and have them be captured by the OBS plugin. Given the binary appears to be missing, the former won't launch, and the latter has no effect.

### Output of `rpm-ostree status`

```shell
$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:a5e81dcc7489b928dfd0f160577344e72815db51908d5819337bfb1174d285e2
                  Version: 40.20240514.0 (2024-05-17T04:33:23Z)
          LayeredPackages: coolercontrol intel-clear-sans-fonts liquidctl mullvad-vpn
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:a5e81dcc7489b928dfd0f160577344e72815db51908d5819337bfb1174d285e2
                  Version: 40.20240514.0 (2024-05-17T04:33:23Z)
          LayeredPackages: coolercontrol liquidctl mullvad-vpn
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64
```

### Extra information or context

I've tried removing my personal layered packages(`mullvad-vpn` and `intel-clear-sans-fonts`) in troubleshooting, but that had no effect on the issue. I've also gotten word from another user facing the same issue on a KDE image, for apparently more than a week.

**Comment by KyleGospo** [comment]
Fixed in latest
