### ISSUE TITLE
Package Request: dosbox-staging

### ISSUE THREAD

**Issue by EPOCHvoyager** [ublue-os/bazzite#1142]
### Describe the package

Primarily for use with [Boxtron](https://github.com/dreamer/boxtron), which can be readily downloaded with ProtonPlus in the GNOME images. A Flatpak exists, but requires at least some tinkering with configuration files, and even then I couldn't get it to play ball with native Steam - but putting it inside a Distrobox did work.

It's fairly small, and the only extra dependencies as far as I can tell would be `SDL2_net` for `dosbox-staging` itself, and the few extra ones listed in the Boxtron README, like `timidity++` - as otherwise it will not work for that purpose.

### Image

Desktop

**Comment by wolfyreload** [comment]
I've created a pull request, with a ujust recipe for easy installation of boxtron in Bazzite. So not quite an out of box experience but easy enough to install for some retro pc gaming

**Comment by EPOCHvoyager** [comment]
Sounds good!
