### ISSUE TITLE
webapp-manager windows have wrong titlebar icon

### ISSUE THREAD

**Issue by AshenColors** [ublue-os/bazzite#1143]
### Describe the bug

Applications launched with webapp-manager have the default Wayland icon in the upper-left titlebar instead of the intended icon set in the .desktop file. 

### What did you expect to happen?

The titlebar icon is the same as what is defined in the .desktop file.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:e30a41828c74b309fa8a7c0e441b4876026054f83d1f7838f94bfa726ce565b4
                  Version: 40.20240514.0 (2024-05-17T14:36:19Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest
                   Digest: sha256:357e02d0892b6b25246982a4a590865975fe4b6d8105e075a6f971592c4bcef0
                  Version: 40.20240513.0 (2024-05-15T16:54:15Z)
```

### Hardware

x86-64 desktop

### Extra information or context

A known workaround is to go to `~/.local/share/applications/` and rename all `webapp-*.desktop` files to `WebApp-*.desktop` to match the set window class (case-sensitive, it seems). When next launching the application, Plasma will display the correct icon in the titlebar. Note that entries manually edited this way cannot be seen or managed in webapp-manager anymore.

This almost certainly needs to go upstream, but I can't make heads or tails of where "upstream" actually is from here or how webapp-manager is installed in Bazzite.

**Comment by AshenColors** [comment]
Rebased to bazzite-nvidia:latest and confirmed the issue is still present.

**Comment by KyleGospo** [comment]
Upstream is mint's webapp manager. I pushed a potential fix to my fork and will PR if all is well.

**Comment by KyleGospo** [comment]
https://github.com/linuxmint/webapp-manager/pull/300
