### ISSUE TITLE
jupiter-fan-control.service fails at boot

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1147]
### Describe the bug

When booting, jupiter-fan-controll sometimes fails to start.

"○ jupiter-fan-control.service - Jupiter fan control
     Loaded: loaded (/usr/lib/systemd/system/jupiter-fan-control.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead) since Sat 2024-05-18 02:58:49 CEST; 34min ago
   Duration: 569ms
   Main PID: 6376 (code=exited, status=0/SUCCESS)
        CPU: 149ms

maj 18 02:58:49 fedora systemd[1]: Started jupiter-fan-control.service - Jupiter fan control.
maj 18 02:58:49 fedora fancontrol.py[6376]: loaded critical temp from SSD hwmon: 84.85
maj 18 02:58:49 fedora fancontrol.py[6376]: jupiter-fan-control started successfully.
maj 18 02:58:49 fedora fancontrol.py[6376]: closed log file
maj 18 02:58:49 fedora fancontrol.py[6376]: returning fan to EC control loop
maj 18 02:58:49 fedora systemd[1]: Stopping jupiter-fan-control.service - Jupiter fan control...
maj 18 02:58:49 fedora fancontrol.py[6579]: loaded critical temp from SSD hwmon: 84.85
maj 18 02:58:49 fedora fancontrol.py[6579]: returning fan to EC control loop
maj 18 02:58:49 fedora systemd[1]: jupiter-fan-control.service: Deactivated successfully.
maj 18 02:58:49 fedora systemd[1]: Stopped jupiter-fan-control.service - Jupiter fan control.
deck@fedora:~$ 
"

### What did you expect to happen?

Service starting at boot and handling galileo fan

### Output of `rpm-ostree status`

```shell
deck@fedora:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:571e1c2fb00822e12a88ea0dabb631074c88356ab5213a829a7c178f3d286bfe
                  Version: 40.20240517.0 (2024-05-17T17:09:39Z)
          LayeredPackages: openrgb piper

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:a511dc6116371b4ef65aaa8e7665f5e782127bbad561e8cdb3d8262c439ba07c
                  Version: 40.20240514.0 (2024-05-17T04:37:16Z)
          LayeredPackages: openrgb piper
```

### Hardware

Steam Deck OLED

**Comment by KyleGospo** [comment]
Latest release has a new version of this service, and I've confirmed it's set to restart in the event of a failure.
