### ISSUE TITLE
Add Cider to the Portal app

### ISSUE THREAD

**Issue by RustCurve164932** [ublue-os/bazzite#1148]
Cider is a 100% free* and open source implementation of Apple Music for Windows, macOS, & Linux with an imo slick UI
![image](https://github.com/ublue-os/bazzite/assets/166953818/f9aa21d4-d196-4600-9fb2-fd8517e9ca86).

*The app itself is free. An active Apple Music subscription is obviously required to use this app

**Comment by KyleGospo** [comment]
Paid software, free version is a year out of date and archived. We won't recommend this.
