### ISSUE TITLE
Add Waterfox to the Portal

### ISSUE THREAD

**Issue by RustCurve164932** [ublue-os/bazzite#1150]
Waterfox is a fork of Firefox **ESR** with an easier to customise UI vs stock Firefox w/o diving into bare CSS files and the profile settings. Whilst its in-app customization isn't as fully-featured as a CSS theme, it's still nice for folk newer to customizing Firefox! It also has a tab sidebar which is more functional than tree style tab (in my opinion), and it can use Chromium extensions, too.

**Comment by KyleGospo** [comment]
https://github.com/BrowserWorks/Waterfox-Classic/wiki/Unpatched-Security-Advisories
