### ISSUE TITLE
Docs - `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/bazzite#1155]
Hello maintainers,

It would be nice to have a `CONTRIBUTING.md` file to know, for example, what feature / package requests are submissible, which are prioritized depending on what metrics (BDFL, GitHub Issue / universal-blue.discourse.group Upvote, package star/download count...)_

**Comment by KyleGospo** [comment]
https://universal-blue.org/contributing

**Comment by KyleGospo** [comment]
https://universal-blue.org/contributing
