### ISSUE TITLE
Set different audio and display in gamemode and desktop?

### ISSUE THREAD

**Issue by mathmolina** [ublue-os/bazzite#1156]
Hello! I have a monitor on a desktop to use for navigation and work, and other TV to play on, I would like that when entering gamemode the TV would automatically turn on e show a gamemode and the system sound would go to the HDMI and when exiting gamemode it would return to the display initially configured with the audio correct, is this possible?

It would also be really cool to disable automatic entry into gamemode and only activate it when pressing the home button on the Xbox controller.

I tried looking to see if there was any configuration in etc/envirolment, but I didn't find anything.

### Hardware

B550 Aorus
Ryzen 5700X
RX 6750XT

**Comment by unicornsandcandies** [comment]
> Gamescope doesn't have output selection built into the interface and its rules for display selection can be a bit arbitrary at times. You can:
> 
>     1. Check your user home `.gamescope-stdout.log` file (it's a hidden one), which will tell what connector your TV is in. i.e. a graphics card with 3 display ports and 1 HDMI should have DP-1, DP-2, DP-3, and HDMI-A-1.  I have a LG TV connected into DP-3 (I use a DP to HDMI adapter) so the log shows `drm: Connector DP-3 -> GSM - LG TV SSCR2` for it.
> 
>     2. Once you know the connector your TV is in, now open in your user home the `.gamescope-cmd.log` file and copy its contents.
> 
>     3. In the home folder, go to `.config/` (it's a hidden one) and create a folder called `environment.d/`. Inside it, create a new file called `gamescope-session-plus.conf`.
> 
>     4. In our new .conf file, type `GAMESCOPECMD="`, paste the content you copied from `.gamescope-cmd.log`, and type another `"`, so what we just pasted is inside our double quotes wrap. Here is an example:
>        `GAMESCOPECMD="/usr/bin/gamescope --max-scale 2 --adaptive-sync -e --xwayland-count 2 -O *,eDP-1 --default-touch-mode 4 --hide-cursor-delay 3000 --fade-out-duration 200 --cursor-scale-height 720 -R /run/user/1000/gamescope.yQe3x0S/startup.socket -T /run/user/1000/gamescope.yQe3x0S/stats.pipe"`
> 
>     5. Note from our previous step we have `*,eDP-1`.  Replace it with your connector we checked in the step 1. In my case the final file now is:
>        `GAMESCOPECMD="/usr/bin/gamescope --max-scale 2 --adaptive-sync -e --xwayland-count 2 -O DP-3 --default-touch-mode 4 --hide-cursor-delay 3000 --fade-out-duration 200 --cursor-scale-height 720 -R /run/user/1000/gamescope.yQe3x0S/startup.socket -T /run/user/1000/gamescope.yQe3x0S/stats.pipe"`
> 
> 
> Restart the system and whenever you go into game mode it should now select the proper monitor. Desktop mode will retain its own monitor configuration independently.

It's great but will it also change audio?

**Comment by BobiderBob** [comment]
Is it also possible to set up priorities here? Like first try DP-1 then DP-2?
