### ISSUE TITLE
2 - 3 new Images for Desktop

### ISSUE THREAD

**Issue by vhalragnarok-ffxiv** [ublue-os/bazzite#1157]
### Describe the package

I tried my hardest and was unable to fork this project (not from a lack of trying) to meet this goal, so I'll just request it here. I'd 100% love to help, but the furthest I got my base (no DE) image to go was to the step that installs input-remapper, discover-overlay and that group of packages, and had exit code 1 (real descriptive let me tell you) error and was basically told to shoo when I asked what was going on. So I guess the official pipeline to ask for this is here, even though I'd love to contribute the images I seek myself...

While KDE & GNOME are just fine and dandy for 90% ish of people, and 100% are the 2 sane choices, I think users could benefit from having more choices. 

For starters Sway (Sericia) has both a UBlue Image & Upstream Fedora Image. So I think the first avenue New Images... would be to have Bazzite but on Sway. Basically take the magic of steam, the kernel, along with the other changes you do, and pair them with Sway.

However Sway is a manual Tiler and doesn't appeal to everyone, so I also recommend having a Hyprland image. I left the discord because I was frustrated with trying to fork this project but someone in there mentioned they had created base images of Hyprland that could be used.

Finally, I think for those who want to layer something else exotic on, it would be really cool to have just a "Base Image", no desktop environment kind of deal. This should be targeted at more advanced users. 

This is a great project, just feels like you are locked into KDE or GNOME, and its absolutely difficult for someone like myself to change that. 

### Image

Desktop

**Comment by noelmiller** [comment]
The reason we do not offer sway or other desktop environments is because of the increased support and maintenance burden. If we support more desktop environments, we need to make sure they work on Desktop, Laptops, and Handhelds, which is a non-trivial amount of work.

You are certainly welcome to fork the existing code if you would like to support other DEs unofficially. The only future planned additional DE we are going to support is Budgie when it properly supports Wayland.

**Comment by KyleGospo** [comment]
You likely need to remove the exit error 1 packages, my guess is they have DE dependencies you were no longer including.

**Comment by castrojo** [comment]
The base-main images come without a desktop if you're looking to start with an "empty" image desktopwise: https://github.com/ublue-os/main/pkgs/container/base-main
