### ISSUE TITLE
Waydroid not launching and how to upgrade from 39 to 40 on the Steam Deck.

### ISSUE THREAD

**Issue by Sanlex96** [ublue-os/bazzite#1158]
Hello. Please, I need your assistance.

I haven't used my steam deck in months and today I decided to give it a go. I am currently using the Bazzite deck (KDE).

 I didn't notice any issues until I tried launching Waydroid. It shows the icon but refuses to launch. I looked around for solutions to this and I saw that the issue would be fixed when Fedora 40 was released.

My problem today is how to upgrade from 39 to 40. I tried updating from the Gaming Mode but it says no update. I even tried using "just update" but it still says Fedora 39 in the System Os. How exactly do I resolve this issue? Thanks for your contributions to the community.

**Comment by ShadowFlare** [comment]
I had an issue like this on some version (one of the builds based on Fedora 40 in my case), where it wouldn't update at all. I had to rebase to the stable version and then the updates worked fine; even when I rolled back to the version that previously wouldn't update it would still update just fine.

**Comment by KyleGospo** [comment]
rpm-ostree status

**Comment by Sanlex96** [comment]
Thanks for replying. Here is the rpm-ostree status:


$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39
                   Digest: sha256:f87d5dd11724f35cf8f47a1d22e38777d22160412737ad8d8a288fe23758eb1d
                  Version: 39.20240419.0 (2024-04-19T17:09:55Z)
                Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39
                   Digest: sha256:71d6d01f69c440aa40e3b633867725090b9c330ba916372b0823d7a042935e49
                  Version: 39.20240415.0 (2024-04-16T02:22:54Z)
                Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf'

**Comment by KyleGospo** [comment]
> Thanks for replying. Here is the rpm-ostree status:
> 
> 
> $ rpm-ostree status
> State: idle
> Deployments:
> ● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39
>                    Digest: sha256:f87d5dd11724f35cf8f47a1d22e38777d22160412737ad8d8a288fe23758eb1d
>                   Version: 39.20240419.0 (2024-04-19T17:09:55Z)
>                 Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf' 
> 
>   ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39
>                    Digest: sha256:71d6d01f69c440aa40e3b633867725090b9c330ba916372b0823d7a042935e49
>                   Version: 39.20240415.0 (2024-04-16T02:22:54Z)
>                 Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf' 
> 

`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable`

**Comment by Sanlex96** [comment]
Thanks for your help. I successfully upgraded to version 40 and I also fixed the issue i had with Waydroid. I will go ahead and close this. Once again, thanks a bunch.
