### ISSUE TITLE
Bootable Drive fails "check media and install"

### ISSUE THREAD

**Issue by EconomyTowel** [ublue-os/bazzite#1166]
### Describe the bug

Had already successfully installed Bazzite on a Legion Go the first time, then deleted the partitions to make a new OS for resale since there was no option to Factory Reset the OS like in Steam Deck's OS. Tried 2 different USB bootable drives including the original one. I'm getting an error that says the media doesn't pass the check somehow.

### What did you expect to happen?

I expected the installation to work the same as it did the first time.

### Output of `rpm-ostree status`

```shell
rpm-ostree status
```

**Comment by EconomyTowel** [comment]
![IMG_7582](https://github.com/ublue-os/bazzite/assets/170769501/0492a9a6-f070-44b0-956b-c3b3546f3c7b)

**Comment by EconomyTowel** [comment]
![IMG_7583](https://github.com/ublue-os/bazzite/assets/170769501/f602ec8e-6fef-4321-a86e-454b0902c342)
There’s a partition at the end (to the right, on cursor point) I’m not familiar with, maybe that needs to be deleted?

**Comment by EconomyTowel** [comment]
Is there a command to “Factory Reset” Bazzite for a new user?

**Comment by HikariKnight** [comment]
i believe the media check not working correctly atm, just select the install option without checking the media and instead just check the checksum for the iso.

**Comment by samuelwang456** [comment]
Recently, I met the same problem as you. Have you found the solution？

**Comment by EconomyTowel** [comment]
You can bypass the check and just select Install Bazzite and it goes into the Fedora installation menu. No issues installing since then.

**Comment by samuelwang456** [comment]
> You can bypass the check and just select Install Bazzite and it goes into the Fedora installation menu. No issues installing since then.

Yes, I can press ESC to skip the check and install the system, but during the use, the fan control has been a problem, the fan speed can not run according to my set, that is, the custom fan speed can not take effect, once I customize the fan speed, the fan will maintain a very low speed even if the temperature rises.

I think the fan question is probably related to ACPI BIOS ERROR.
