### ISSUE TITLE
After waking from sleep in Game Mode, the Steam UI icons and buttons disappear and controller focus inside games is lost

### ISSUE THREAD

**Issue by ZainAjam** [ublue-os/bazzite#1175]
### Describe the bug

Before putting the PC to sleep ...

![20240526_140155](https://github.com/ublue-os/bazzite/assets/32865278/3e601190-5212-4009-a06c-5b4aff5a981c)

After resuming from sleep ...

![20240526_140251](https://github.com/ublue-os/bazzite/assets/32865278/53fc3592-55db-489b-a463-67281e6b62db)

Notice that in the second picture above, the search icon, network indicator, time and profile image are missing at the top of the screen, and the controller button labels are missing at the bottom of the screen.

Also, when inside a game (tested with Batman Arkhym City), the controller does not respond after such a resume from sleep.

### What did you expect to happen?

I expected to have all the icons and labels show up at the top and bottom of the screen when in game mode after a resume from sleep. Also expect that the xbox controller would work in games after a resume from sleep.

### Hardware

- HTPC image of Bazzite v3.0.1 
- Minisforum HX99G
- 2 x 16gb DDR5 4800mhz ram
- 1 x 500gb NVME storage drive (Bazzite installed on)
- 1 x 1000gb NVME storage drive (formatted as ext4 and set for mounting with KDE partition manager)
- Xbox Series S controller with Xbox Wireless Dongle receiver
- Pepper jobs remote control with usb receiver

**Comment by unicornsandcandies** [comment]
Do you use decky loader?

**Comment by ZainAjam** [comment]
> Do you use decky loader?

I have it installed yes. Only have the steamdb plugin installed though. Is there a connection between decky loader and this problem?

**Comment by idk-some-guy** [comment]
Can confirm, started happening after the recent gamescope update.

**Comment by ZainAjam** [comment]
> Can confirm, started happening after the recent gamescope update. The workaround of power options -> restart steam fixes it but produces a very bizarre bug where all colors in game turn to greyscale and very dim. Tho might be a separate issue, for now a full systemctl restart is the only option

My current workaround is to "Quit to Desktop" and then "Return to Game mode"

**Comment by ZainAjam** [comment]
So it looks like this is an issue when the "wake movie" is set to the steam deck default. 

![20240608_095238.jpg](https://github.com/ublue-os/bazzite/assets/32865278/df2fc165-1a25-4e09-a987-8800197af083)

If wake movie is turned off or if wake movie is set to the Bazzite movie, there is no issue when waking from sleep

**Comment by quinnvoker** [comment]
> If wake movie is turned off or if wake movie is set to the Bazzite movie, there is no issue when waking from sleep

Thanks for this! I'd been struggling with being unable to play games after waking from sleep too, and had resorted to just doing full power-offs or switching to+from desktop mode to work around it. Never would have suspected it was the wake movie setting causing this.
