### ISSUE TITLE
Unconditional clearing of xdg-config/fontconfig

### ISSUE THREAD

**Issue by zebh** [ublue-os/bazzite#1178]
### Describe the bug

`bazzite-user-setup` unconditionally clears the entire user fontconfig folder on every run, see: https://github.com/ublue-os/bazzite/blob/de74bc3128db2756a0de14cd2a2a9bb958178a1e/system_files/desktop/shared/usr/libexec/bazzite-user-setup#L54

### What did you expect to happen?

Bazzite respects my font configuration.

### Extra information or context

I can see the intention, but it feels like the wrong way to handle any issue with fonts. Especially since it is unconditionally clearing _all_ user settings.

**Comment by KyleGospo** [comment]
Fix for an old bug upstream. It's been long enough so I'll remove this. Thanks
