### ISSUE TITLE
fstab issues cause system to no longer be usable

### ISSUE THREAD

**Issue by d10sfan** [ublue-os/bazzite#1185]
### Describe the bug

If an error occurs with fstab once, then the system is never able to mount /var or the user's home directory ever again.

Attempted to get some help from discord but I ended up reinstalling the os as there wasn't a resolution there. 

The files were all still there but something was causing the system to be unable to mount them even though the fstab file was correct. This persisted after a reboot as well.

### What did you expect to happen?

System to boot up and be able to login

**Comment by HikariKnight** [comment]
Sorry but we cannot "fix" people messing up their fstab, if you mess it up it will break on any linux system.
This will require using an emergency shell if possible or a live usb to fix the fstab (both require manual work)

This is why our documentation tell people to test their changes before rebooting in our documentation as it will catch issues like this, or in the case of accidentally adding invisible characters to the fstab.
And it is why we tell people to add `nofail` to the mount options on any drive they add so that if it fails to mount, it will not break the system.

**Comment by d10sfan** [comment]
The main issue here isn't that fstab can break due to user error. It's that once that happens it's impossible to fix the brtfs mounting, requiring a complete reinstall, which isn't an issue on systems that use other file systems

**Comment by d10sfan** [comment]
It would be great if there was some trouble shooting way to resolve this when it happens, since it's easy with kde partition manager to cause this issue.

**Comment by HikariKnight** [comment]
> The main issue here isn't that fstab can break due to user error. It's that once that happens it's impossible to fix the brtfs mounting, requiring a complete reinstall, which isn't an issue on systems that use other file systems
> It would be great if there was some trouble shooting way to resolve this when it happens, since it's easy with kde partition manager to cause this issue.

you will have to use emergency/rescue mode like you would do in any linux system.
as long as you have not messed up the `/` mount that will work, if you have messed up that then you would have to use a liveusb just like you would on any distro.

Getting into emergency/recovery mode is covered by our documentation
https://universal-blue.discourse.group/docs?topic=562

**Comment by d10sfan** [comment]
In this case, I was able to get into emergency mode and remove the broken fstab entries and  reboot, but the /home mount never recovered. So it isn't that I was unable to repair fstab, it's that something in the way bazzite mounts the /home from the subvolume failed for good once fstab failed once. 

I asked for help in discord, but after a few hours of attempts, there wasn't any resolution. The only solution I ended up having was to manually mount my home subvolume to a /mnt/... point, copy the files to a backup drive, and re-install the OS, because the systemd services that are supposed to mount /var/ and /var/home failed and never worked again.

The expectation here would be that there's some way to recover from this, if you manage to mess up your fstab. I understand the need to go into recovery mode and fix things, but the issue is that once you fix the fstab and are able to reboot and get past that, in this case, the /home mount never works again.

**Comment by wcunning** [comment]
I got this same behavior on a fresh install, though I picked ext4, not btrfs. At some level, there are dangerous options in the default partitioning on the Ally X if nothing else.

**Comment by d10sfan** [comment]
Yeah there seems to be issues with the fstab and it's too easy to break things compared to other distros I've used in the past.

**Comment by ImRobot777** [comment]
fstab seems to work well in bazzite that i've installed 2 weeks ago.
