### ISSUE TITLE
Flatpaks apps missing

### ISSUE THREAD

**Issue by spookicazt** [ublue-os/bazzite#1196]
### Describe the bug

Sometimes apps are seemingly disappearing. For example Firefox is missing and searching for it prompts me to Get it from the discover store. Upon doing so it states that it's already installed and launching it doesn't work. Shortcuts made on the taskbar becomes a missing icon or get modified to become a shortcut for Kate.

In my lot of apps Discord has also disappeared but it still launched from the auto start.

Any Flatpak app has the same behavior. Aka: not appearing in the start menu but seemingly still present.

### What did you expect to happen?

Apps shouldn't disappear

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:00ebd41be379043a51f9dcbdca7f73b6e4d0f47c7cf40ea2ac53d6239595b360
                  Version: 40.20240531.0 (2024-05-31T17:02:20Z)
            LocalPackages: lact-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:50df9758495bb0da75552ac99202cde06284b487d7bca4acc9bbec1561fd82a0
                  Version: 40.20240523.0 (2024-05-25T05:20:21Z)
            LocalPackages: lact-0.5.4-0.x86_64
```

### Hardware

Operating System: Bazzite 40
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.8.10-301.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5500U with Radeon Graphics
Memory: 14.9 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: HP
Product Name: HP Pavilion Laptop 15-eh1xxx

**Comment by spookicazt** [comment]
After some searching I found out the issue was that I had changed my users default shell to zsh.

More precisely, I installed zsh through brew. I then used `ujust chsh /var/home/linuxbrew/.lijnuxbrew/bin/zsh`

Restoring the shell to bash fixed it but then I'm a bit confused as to how I should set up zsh as my default terminal.

**Comment by raddevon** [comment]
Maybe there's a cleaner way to do this, but I was able to work around this issue by writing a shell wrapper script to start ZSH for interactive shells and Bash for anything else. Here's the script:

```bash
#!/bin/bash

if [ -t 0 ]; then
    exec /home/linuxbrew/.linuxbrew/bin/zsh
else
    exec /bin/bash
fi
```

The ZSH path assumes you installed with Homebrew.

Then, make the script executable:
```bash
chmod +x /path/to/shell-script.sh
```

Finally, set this script as your default shell:
```bash
sudo lchsh $USER
```
When prompted for the shell path, give it `/path/to/shell-script.sh` (replacing, of course, with the actual path; I just dropped it into my home directory). Restart once you've set the new shell, and you should see your Flatpaks work and you can have ZSH as your interactive shell.
