### ISSUE TITLE
Écran portrait 

### ISSUE THREAD

**Issue by Kadnix** [ublue-os/bazzite#1197]
### Describe the bug

J'ai un souci quand j'allume le PC en mode gaming l'écran reste au mode portrait et je n'arrive pas à le mettre en mode horizontal

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

**Comment by HikariKnight** [comment]
Please actually fill in what hardware you use, there is a reason why the template is there.
