### ISSUE TITLE
Install: Rebase from Fedora Kinoite fails to install default System Flatpaks

### ISSUE THREAD

**Issue by tealsuki** [ublue-os/bazzite#1199]
### Describe the bug

When attempting to apply the `ujust _install-system-flatpaks` stage after the manual rebase and Bazzite Portal stages, the Just recipe fails attempting to select Remotes.

### What did you expect to happen?

The batch script to correctly install all paks, and correctly selecting the Remote to download them from

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
ostree-unverified-registry: ghcr.io/ublue-os/bazzite:stable
Digest: sha256:00ebd41be379043a51f9dcbdca7f73b6e4d0f47c7cf40ea2ac53d6239595b360
Version: 40.20240531.0 (2024-05-31T17:02:20Z) LocalPackages: lact-0.5.4-0.x86_64

ostree-unverified-registry: ghcr.io/ublue-os/bazzite:stable
Digest: sha256:00ebd41be379043a51f9dcbdca7f73b6e4d0f47c7cf40ea2ac53d6239595b360
Version: 40.20240531.0 (2024-05-31T17:02:20Z)
Pinned: yes
```

### Hardware

Lenovo IdeaPad Flex 15 14ARE05 (81X2)
AMD Ryzen 3 4300U (Radeon RX Vega 6 Mobile)
8GB RAM

### Extra information or context

It first asks to select a Remote for Firefox (fedora or flathub).
Selecting flathub will fail because the Fedora package is still registered as installed (though no longer available in Bazzite).
Selecting fedora causes it to continue on (and make no changes yet)
It then fails at attempting to install WineZGUI, because it attempts to also pull from the Fedora Remote without asking, when this pak is only listed in Flathub.
The recipe throws an error either way, failing with exit code 1.

Manually installing the packages one by one using the flatpak command from the recipe
`flatpak --system -y install --or-update [pak]` will succeed because flatpak asks for the Remote each time, allowing you to select the correct one.

**Comment by tealsuki** [comment]
Relevant issue and original merge: #986 #989

**Comment by cgcomer** [comment]
I've encountered the same issue:

**Actual output:**

ccomer@main-bazzite:~$ ujust _install-system-flatpaks
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   966  100   966    0     0   3227      0 --:--:-- --:--:-- --:--:--  3230
Looking for matches…
Remotes found with refs similar to ‘app/org.mozilla.firefox/x86_64/stable’:

   1) ‘fedora’ (system)
   2) ‘flathub’ (system)

Which do you want to use (0 to abort)? [0-2]: 2
error: org.kde.gwenview/x86_64/stable is already installed from remote fedora
error: Recipe `_install-system-flatpaks` failed with exit code 1

**rpm-ostree status**
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:d9780944c8e32563427bdf239fbcda168aafc9f9b2b538f2e02f5326485b36bc
                  Version: 40.20240605.0 (2024-06-05T16:37:35Z)

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:d9780944c8e32563427bdf239fbcda168aafc9f9b2b538f2e02f5326485b36bc
                  Version: 40.20240605.0 (2024-06-05T16:37:35Z)

**Hardware**

Operating System: Bazzite 40
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.8.11-301.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6900 XT
Manufacturer: ASUS
Asus Crosshair Hero VIII Wifi
Installed Main Drive: Samsung SSD 970 EVO Plus 2TB NVME (no SMART errors)
BIOS: 4805
Secure Boot: On (despite what Info Center claims)

Hopefully, this helps.  I'm also suffering from an apparent Tainted Kernel #1209. Though I doubt these two issues are related.

**Comment by alespool** [comment]
Had the same issue right now, posting as well:

alespool@bazzite:~$ ujust _install-system-flatpaks
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1060  100  1060    0     0   5679      0 --:--:-- --:--:-- --:--:--  5698
Looking for matches…
Remotes found with refs similar to ‘app/org.mozilla.firefox/x86_64/stable’:

   1) ‘fedora’ (system)
   2) ‘flathub’ (system)

Which do you want to use (0 to abort)? [0-2]: 2
error: org.kde.gwenview/x86_64/stable is already installed from remote fedora
error: Recipe `_install-system-flatpaks` failed with exit code 1
alespool@bazzite:~$ rpm-ostree status
State: idle
Deployments:
  ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:72ae13c334ed9db3fc0eee5707d94e9d7d669fd413ea90b49043bdf1e55d51f7
                  Version: 41.20250106.3 (2025-01-07T04:23:44Z)
                     Diff: 19 added
          LayeredPackages: coolercontrol liquidctl

● ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:72ae13c334ed9db3fc0eee5707d94e9d7d669fd413ea90b49043bdf1e55d51f7
                  Version: 41.20250106.3 (2025-01-07T04:23:44Z)

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:72ae13c334ed9db3fc0eee5707d94e9d7d669fd413ea90b49043bdf1e55d51f7
                  Version: 41.20250106.3 (2025-01-07T04:23:44Z)

Hardware:
Operating System: Bazzite 41
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.8-201.bazzite.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X 16-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 XTX
Manufacturer: ASRock
Product Name: B650M-HDV/M.2
