### ISSUE TITLE
Japanese Keyboard Layout

### ISSUE THREAD

**Issue by Dormant-Hero** [ublue-os/bazzite#1202]
### Describe the package

Spoke with Kyle Gospo in the discord chat here https://discord.com/channels/1072614816579063828/1087140957096517672/1247284216467685518 and told me to post this https://paste.centos.org/view/178ef822. 

Essentially without "mozc" and "fcitx5" I was unable to type hiragana and get kanji via the IME keyboard as you would on windows (you have like 2 main alphabets hiragana and katakana. Kanji is like a group of hiragana combined when you type to make a character/kanji).  I am unsure which specific packages worked hence why Kyle told me to post what he asked me to post but I know it relates to the 2 names I put into quotes. 

Sorry if I explained terribly and you may need to google hiragana chart just to see what I mean when you try it on your end. System settings would only allow romaji (latin letters system if you like) and katakana. 

### Image

Desktop

**Comment by Dormant-Hero** [comment]
One other thing. I think I had to make fcitx5 auto start on each launch. No idea if this will be an issue when combined with the CHinese stuff but just providing feedback of my experience when someone else tests this. You have to launch that for the keyboard stuff to work. 

Icons you may see it as in your taskbar when it does work for anyone testing and if this happens to be the right applications:

![image](https://github.com/ublue-os/bazzite/assets/79374258/32105f55-de0a-45c2-a97d-bb2e881417bb)
![image](https://github.com/ublue-os/bazzite/assets/79374258/0dd8d977-1de6-4833-bbf0-0003e54c7fe8)
![image](https://github.com/ublue-os/bazzite/assets/79374258/04ed1353-07f4-442e-9ccb-11174bdbcd16)

**Comment by fjrodriguez** [comment]
I solved installing fcitx5 from flatpak. I executed: 

flatpak install org.fcitx.Fcitx5 org.fcitx.Fcitx5.Addon.Mozc 

Then, in the keyboard icon, in the top right corner, I added the Japanese keyboard: Mozc.
