### ISSUE TITLE
sunshine-workaround.service bad unit file

### ISSUE THREAD

**Issue by mjpaden** [ublue-os/bazzite#1204]
### Describe the bug

When I do a systemctl list-units, sunshine-workaround.service shows that it did not load due to a "bad-setting" (Reason: Unit sunshine-workaround.service has a bad unit file setting.) I think the second ExecStartPre line is missing an endquote.

### What did you expect to happen?

All built-in services to be loaded do so without error.

**Comment by coquizen** [comment]
I have experienced the same error. I even tried running `systemctl edit sunshine-workaround.service` to override but even with an empty `ExecStartPre=` prior to the quote balance fixed line doesn't work.
