### ISSUE TITLE
nuked bios when adding key(s)

### ISSUE THREAD

**Issue by xioren** [ublue-os/bazzite#1205]
### Describe the bug

After installing and restarting, got trough bios and grub and then was met only with a black screen. I waited to see if anything would happen and after several minutes it rebooted back to bios and showed a message about writing or adding keys; I waited. It then rebooted again and at that point just booted to a black screen, no bios. This is where I am at now, bios is corrupted and pc is not bootable.

### What did you expect to happen?

I expected Bazzite not to brick my pc.

### Output of `rpm-ostree status`

```shell
n/a
```

### Hardware

Venus series (Ryzen 9 7940HS)

**Comment by KyleGospo** [comment]
Did you install a deck or desktop image?

**Comment by xioren** [comment]
I used the desktop image. I have (had) secure boot turned off anyway so its not even necessary to mess with enrolling keys. Maybe give the user an option to skip it? It happened automatically for me. Luckily I was able to reset CMOS and boot but It does not seem like I will be able to use Bazzite.

**Comment by KyleGospo** [comment]
The key is passworded, during MOK enrollment you have to enter the phrase in our readme, or you can hit continue to skip enrollment.

Any failure in the key itself or in decrypting it would result in skipping enrollment.

**Comment by KyleGospo** [comment]
The key is passworded, during MOK enrollment you have to enter the phrase in our readme, or you can hit continue to skip enrollment.

Any failure in the key itself or in decrypting it would result in skipping enrollment.

**Comment by xioren** [comment]
Right what I am saying is this all happened with no input from me. It was black screen --> BIOS writing keys --> brick.

**Comment by KyleGospo** [comment]
I'm sorry but I'm very not sure what's going on here. What you're describing would be a failure by your motherboard manufacturer, and not something we could fix.

**Comment by xioren** [comment]
Alright, I will close the issue.

**Comment by KyleGospo** [comment]
In the meantime if you're still willing to give this a try here's a workaround:

The key enrollment is kicked off by our ISO. You can instead install stock Fedora Kinoite or Silverblue and then rebase to Bazzite with the instructions from the website.
