### ISSUE TITLE
Using an xbox wireless dongle adaptor with Bazzite, before powering off the machine, the OS does not turn off the xbox controller first

### ISSUE THREAD

**Issue by ZainAjam** [ublue-os/bazzite#1206]
### Describe the bug

Using an xbox wireless dongle adaptor with Bazzite, before powering off the machine, the OS does not turn off the xbox controller first, so the controller just loses connection to the dongle and continues in pairing mode searching for the dongle. I then have to turn it off manually.

### What did you expect to happen?

I expect that the OS uses the xbox dongle adaptor to send a power off signal to the controller before the OS and machine powers off

### Hardware

HTPC image of Bazzite v3.0.1
Minisforum HX99G
2 x 16gb DDR5 4800mhz ram
1 x 500gb NVME storage drive (Bazzite installed on)
1 x 1000gb NVME storage drive (formatted as ext4 and set for mounting with KDE partition manager)
Xbox Series S controller with Xbox Wireless Dongle receiver
Pepper jobs remote control with usb receiver

**Comment by herbalizer404** [comment]
Same for me

**Comment by KyleGospo** [comment]
I don't believe this is a feature of the xone or xpad drivers, if there's another distro you're aware of that does do this or a service that we could enable that will attempt to controller shut down at shut off time I can look into implementing it.

**Comment by ZainAjam** [comment]
> I don't believe this is a feature of the xone or xpad drivers, if there's another distro you're aware of that does do this or a service that we could enable that will attempt to controller shut down at shut off time I can look into implementing it.

It seems to work fine (mostly) when the OS is put to sleep so I assumed the same behaviour should apply when the OS shuts down

**Comment by KyleGospo** [comment]
> > I don't believe this is a feature of the xone or xpad drivers, if there's another distro you're aware of that does do this or a service that we could enable that will attempt to controller shut down at shut off time I can look into implementing it.
> 
> It seems to work fine (mostly) when the OS is put to sleep so I assumed the same behaviour should apply when the OS shuts down

That would be a great feature request for the driver upstream, but there's nothing that we're going to do for that here.

**Comment by ZainAjam** [comment]
> > > I don't believe this is a feature of the xone or xpad drivers, if there's another distro you're aware of that does do this or a service that we could enable that will attempt to controller shut down at shut off time I can look into implementing it.
> > 
> > It seems to work fine (mostly) when the OS is put to sleep so I assumed the same behaviour should apply when the OS shuts down
> 
> That would be a great feature request for the driver upstream, but there's nothing that we're going to do for that here unless there's a specific workaround already made that we can implement.
> 

Do you know if the xpad or xone drivers are on GitHub so I can suggest the feature there?

**Comment by KyleGospo** [comment]
> > I don't believe this is a feature of the xone or xpad drivers, if there's another distro you're aware of that does do this or a service that we could enable that will attempt to controller shut down at shut off time I can look into implementing it.
> 
> ChimeraOS powers down xbox controllers automatically when the system shuts down.

Thanks, I'll take a look
