### ISSUE TITLE
Legion Go autorotation screen problem

### ISSUE THREAD

**Issue by IoannesC** [ublue-os/bazzite#1207]
### Describe the bug

When I Try to use the automatic orientation option in screen settings of desktop mode, the screen flips to the right. 

### What did you expect to happen?

I expect a normal use, but maybe is something not solved yet. I installed Bazzite Two days algo. 

### Hardware

Legion Go

**Comment by KyleGospo** [comment]
I don't believe we've spent any time implementing auto rotation support. I can look into it sometime this week, it sounds like it needs some extra tweaking to know the proper orientation of the display relative to the gyro.
