### ISSUE TITLE
Framework 16 LUKS TPM Unlock Doesn't Prompt for Fingerprint

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#1208]
Trying out the Bazzite image for my new Framework 16. I have a fingerprint enrolled that can be used to unlock my session and for sudo prompts, but when enabling LUKS TPM unlock, the system boots without ever asking for my fingerprint OR my password.

**Comment by antheas** [comment]
LUKS TPM unlock disables the hardware encryption password. This is what it is meant to do.

It is up to you to secure your lockscreen with a fingerprint/password after the system has started.

It is possible to combine TPM with a simpler pin for additional security, which is not supported by the script. Fingerprint authentication at that stage of the boot process is not supported afaik.

**Comment by jacobranson** [comment]
I see. I was under the impression that enabling TPM LUKS unlock would replace the password auth with a fingerprint auth. I see on the Plasma 6 System Settings that logging in to a user account with a fingerprint is not implemented yet, only unlocking is. I guess that means no matter which combo I go with, I will be typing in a password after boot.

**Comment by antheas** [comment]
TPM is completely unrelated to fingerprints, it is used to verify your hard drive was not removed from your PC before unlocking it without a password. This allows you to boot without entering your hw encryption password.

As for fingerprints, only gnome supports fingerprint unlock.

**Comment by KyleGospo** [comment]
Yeah, this is just skipping the LUKS step. If you had a normal password in KDE and had LUKS you would need to enter your password twice to start your system without TPM unlock.

**Comment by antheas** [comment]
I've been waiting 3 years. The pull request is 4 years old

**Comment by KyleGospo** [comment]
> I've been waiting 3 years. The pull request is 4 years old

If that pull request is functional can you link it to me?

**Comment by antheas** [comment]
Probably not very functional. I think it was this one. Indeed 2019.
https://github.com/sddm/sddm/pull/1220
