### ISSUE TITLE
Tainted Kernel

### ISSUE THREAD

**Issue by cgcomer** [ublue-os/bazzite#1209]
### Describe the bug

Following a rebase from Fedora Kinoite 40 to Bazzite (KDE). Info Center claims the Linux Kernel is tainted.
![Screenshot_20240607_024249](https://github.com/ublue-os/bazzite/assets/112912804/06552979-6e08-4a2d-9f4d-609c97374484)

### What did you expect to happen?

Expected the Linux Kernel to remain untainted during the rebase.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:d9780944c8e32563427bdf239fbcda168aafc9f9b2b538f2e02f5326485b36bc
                  Version: 40.20240605.0 (2024-06-05T16:37:35Z)

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:d9780944c8e32563427bdf239fbcda168aafc9f9b2b538f2e02f5326485b36bc
                  Version: 40.20240605.0 (2024-06-05T16:37:35Z)
```

### Hardware

Operating System: Bazzite 40
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.8.11-301.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6900 XT
Manufacturer: ASUS
Asus Crosshair Hero VIII Wifi
Installed Main Drive: Samsung SSD 970 EVO Plus 2TB NVME (no SMART errors)
BIOS: 4805
Secure Boot: On (despite what Info Center claims)

**Comment by KyleGospo** [comment]
Expected, aftermarket kernel with akmods.

**Comment by cgcomer** [comment]
I can't find anything on the GitHub page or the COPR entry for the fsync kernel that this is expected. Could someone point me to some documentation that this is to be expected. Not saying I don't believe you I just like to understand why things work and behave the way they do.
