### ISSUE TITLE
Legion Go: Black Screen after Updating BIOS and Bazzite Update

### ISSUE THREAD

**Issue by SmoothTony** [ublue-os/bazzite#1210]
### Describe the bug

**Issue:** Used Power button and Volume + to select boot into Bazzite, the Bazzite splash screen appears... I see the circle spinning attempting to load, joysticks flash, then the Bazzite splash screen and graphic disappears to a blank screen with the backlight on.

### What did you expect to happen?

Successful boot into Bazzite

### Output of `rpm-ostree status`

```shell
Unable to do it.
```

### Hardware

Legion Go with Bazzite installed on partitioned SSD

### Extra information or context

I'm unsure if somehow updating the Legion Go BIOS caused this issue but I want to relay the information, just in case.  

1. I updated the Legion Go BIOS, rebooted without issue then installed additional Windows 11 OS updates without issue. Then shutdown the Legion Go

2. Used Power button and Volume + button to boot into Bazzite without issue, then updated a number of games. After the game updates were complete I realized there was a Bazzite update icon on the top right of the screen. I've been away from gaming for a couple of months due to work so I performed the update in this manner.

While allowing the update to complete I went to bed for the night. When I woke up, the Legion Go was on a black screen but I could see the backlight was on. I attempted to wake the device but was unable to do so, causing me to force a shutdown.

I'm able to boot into Windows without issue. Windows is set in BIOS as default boot. Bazzite is installed on partitioned SSD. Additionally I removed a microSD just in case but I'm still unable to boot into Bazzite.

**Comment by HikariKnight** [comment]
there are too many variables going around here.

Are you able to connect a keyboard (usb) to the legion go
press esc when booting bazzite and select the `ostree:1` entry (if you have 2 of it, just select the one closer to the top)

if that works then go into the terminal and run `rpm-ostree rollback` since it was clearly working before you updated so i figure this will be worth a shot.

No idea why it would get a black screen during the update though as that is not supposed to happen.

**Comment by SmoothTony** [comment]
> there are too many variables going around here.
> 
> Are you able to connect a keyboard (usb) to the legion go press esc when booting bazzite and select the `ostree:1` entry (if you have 2 of it, just select the one closer to the top)
> 
> if that works then go into the terminal and run `rpm-ostree rollback` since it was clearly working before you updated so i figure this will be worth a shot.
> 
> ~No idea why it would get a black screen during the update though as that is not supposed to happen.~ Thinking over it i suspect the legion go might have gone to sleep while updating and that might have caused something to go wrong during the update process (this is why you always have access to the previous update in the bootloader so you can do a rollback, however for non deck hardware you need a physical usb keyboard to select the option, nothing we can do about that sadly...)

What you are saying is a distinct possibility because if my memory serves me correct, when I laid down to go to sleep, I believe the update duration was 20 minutes.

I will try connecting an external monitor first, as I've heard that could alleviate the issue because I can feel a slight rumble on the gamepad as the blank screen appears. If that fails to work I'll connect a keyboard and try your steps. Either way... I'll report back with results.

**Comment by SmoothTony** [comment]
Success...

But not in the manner you would think...

After using a USB keyboard I was able to get into Grub, but was unable to interact with the menu screen to select ostree:1. The menu would "time out" then automatically display command line. Now I was able to interact. But it wasn't what I wanted.

I decided to do a bit of research to understand why I could not interact with the Grub menu and the screen would time out after a short amount of time dumping me into command line. What I read is that holding down SHIFT, instead of pressing ESC would work.

After a quick reboot I held down SHIFT then to my absolute surprise what occurred was Bazzite booting fully. I do not understand why that worked... but it did. To test I restarted without holding SHIFT and it boots into Bazzite. From now on I'll simply do ujust update in terminal instead.

**Comment by ShadowFlare** [comment]
I've never dared to let it sleep during an installation of an update, after the experience of having my Steam Deck get disconnected from wifi during SteamOS updates and stalling indefinitely, but what I do is I plug in my device to update, which changes the sleep timer (by default to 1 hour) and gives it plenty of time to finish without having to interact to keep it awake.

**Comment by KyleGospo** [comment]
It's absolutely fine to sleep or even shut down your system during an update with OSTree. I do it all the time.

**Comment by HikariKnight** [comment]
> Success...
> 
> But not in the manner you would think...
> 
> After using a USB keyboard I was able to get into Grub, but was unable to interact with the menu screen to select ostree:1. The menu would "time out" then automatically display command line. Now I was able to interact. But it wasn't what I wanted.
> 
> I decided to do a bit of research to understand why I could not interact with the Grub menu and the screen would time out after a short amount of time dumping me into command line. What I read is that holding down SHIFT, instead of pressing ESC would work.
> 
> After a quick reboot I held down SHIFT then to my absolute surprise what occurred was Bazzite booting fully. I do not understand why that worked... but it did. To test I restarted without holding SHIFT and it boots into Bazzite. From now on I'll simply do ujust update in terminal instead.

either way it is working now. :)
and as kyle said he updates and sleeps his device all the time no problem so it shouldnt be a problem.

This is why its nice to have the rollback option for ostree.

also if you get sent into the grub command line, just type "exit" and you will be sent back to the menu.
