### ISSUE TITLE
Legion GO - desktop mode screen resolution 1200*1600 fails

### ISSUE THREAD

**Issue by ClaudioVarandas** [ublue-os/bazzite#1214]
### Describe the bug

In desktop mode, i changed the resolution to 1200*1600 and the screen shows like this :

![image](https://github.com/ublue-os/bazzite/assets/457793/85b3bd94-1151-4af4-ae8e-2162d3996699)

### What did you expect to happen?

show the proper resolution

### Output of `rpm-ostree status`

```shell
cvarandas@llg-baz:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:94e054df98891bbd320d1f7048e42be36baab5a9598c25aa90ed43c84350bdca
                  Version: 40.20240607.0 (2024-06-07T17:03:13Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:40-testing-20240605
                   Digest: sha256:177fbfe8466f4d067fed0aae37b0b5a00b325a9c65ba529d859e7363d11d37e0
                  Version: 40.20240605.0 (2024-06-05T16:47:31Z)
```

### Hardware

```shell
Legion GO

cvarandas@llg-baz:~$ cat /sys/devices/virtual/dmi/id/product_name
83E1
```

### Extra information or context

I want to revert to the default resolution 1600*2560 , is there a way to do it via ssh ?

I also tried to rebase to the testing latest but no success...

**Comment by ClaudioVarandas** [comment]
Workaround to revert it : 

```
mv ~/.config/kwinoutputconfig.json ~/.config/kwinoutputconfig.json.old
```

credits to HikariKnight from ublue discord !

**Comment by gbraad** [comment]
this should be in an FAQ as this happened when i tried to duplicate the screen in desktop mode

**Comment by HikariKnight** [comment]
> this should be in an FAQ as this happened when i tried to duplicate the screen in desktop mode
> 
> switch to a console ctrl+alt+f2, login and remove the file

literally in the wiki/documentation and only affects LGO
https://universal-blue.discourse.group/docs?topic=2413#workarounds-known-issues-3
