### ISSUE TITLE
Bazzite Deck Stable - Audio keep reverting to Stereo from 5.1 Surround upon reboot

### ISSUE THREAD

**Issue by ChaosBlades** [ublue-os/bazzite#1215]
### Describe the bug

I switch to desktop. 
Go into KDE audio settings. 
Switch audio output to 5.1 surround. 
Go back into GameScope verify 5.1 surround is working. 
Reboot. 
Gamescope is only playing in Stereo.
Go back into KDE.
KDE is also back in Stereo again.

### What did you expect to happen?

Switching to 5.1 Surround Sound is retained through reboot

### Extra information or context

This was a problem back in the day on HoloISO and ChimeraOS that was fixed well over a year ago. I don't recall the commits but I reported the bug on both then it was resolved after an update without any replies to my report of the issue.

**Comment by KyleGospo** [comment]
Changes must be made to your Wireplumber config to apply to gamescope

**Comment by ChaosBlades** [comment]
Are you saying that is the fix or that is a work around until it gets fixed? Is this being categorized as an upstream gamescope issue (Valve time) or is Bazzite going to implement whatever fix HoloISO / ChimeraOS has?

**Comment by KyleGospo** [comment]
That is the fix, we are following what Valve does and have no intention of changing it.

**Comment by ChaosBlades** [comment]
Well that is unfortunate.

**Comment by ChaosBlades** [comment]
Cross post with another issue just in case someone finds this issue instead of the other one.

Wireplumber is the most convoluted thing that a normal user would need to use I have ran across in my time using linux. It is like needing to change cam timing in order to turn on your windshield wipers. Spent a week trying to get it to work with no success.

For whatever reason `wpctl status` does not list inactive sinks. Need to go old school in order to avoid further convoluted nonsense.

You don't need to use `sudo` for any of this.

`pactl list`

You are looking for the name and output you want to use. Change yours to whatever you need them to be. I will just list what I need to use.

> Name: alsa_card.pci-0000_09_00.1
> output:hdmi-surround-extra3

`nano ~/.config/systemd/user/set-surround.service
`
```
[Unit]
Description=Set Sink in PipeWire (user session)

[Service]
Type=oneshot
ExecStart=sh -c "sleep 30; /usr/bin/pactl set-card-profile alsa_card.pci-0000_09_00.1 output:hdmi-surround-extra3"

[Install]
WantedBy=default.target
```


`systemctl --user daemon-reload`
`systemctl --user enable set-surround.service`
`systemctl --user start set-surround.service`

On boot it will wait 30 seconds and switch the audio sink.

**Comment by nickusve** [comment]
> Cross post with another issue just in case someone finds this issue instead of the other one.
> 
> Wireplumber is the most convoluted thing that a normal user would need to use I have ran across in my time using linux. It is like needing to change cam timing in order to turn on your windshield wipers. Spent a week trying to get it to work with no success.
> 
> For whatever reason `wpctl status` does not list inactive sinks. Need to go old school in order to avoid further convoluted nonsense.
> 
> You don't need to use `sudo` for any of this.
> 
> `pactl list`
> 
> You are looking for the name and output you want to use. Change yours to whatever you need them to be. I will just list what I need to use.
> 
> > Name: alsa_card.pci-0000_09_00.1
> > output:hdmi-surround-extra3
> 
> `nano ~/.config/systemd/user/set-surround.service `
> 
> ```
> [Unit]
> Description=Set Sink in PipeWire (user session)
> 
> [Service]
> Type=oneshot
> ExecStart=sh -c "sleep 30; /usr/bin/pactl set-card-profile alsa_card.pci-0000_09_00.1 output:hdmi-surround-extra3"
> 
> [Install]
> WantedBy=default.target
> ```
> 
> `systemctl --user daemon-reload` `systemctl --user enable set-surround.service` `systemctl --user start set-surround.service`
> 
> On boot it will wait 30 seconds and switch the audio sink.

I had issues with an Nvidia GPU where, even though the system _says_ it is in 5.1 it would output _no_ sound until I changed it to stereo and back. This service suggestion resolved my issue. Thank you for sharing.
