### ISSUE TITLE
Sunshine activates accessibility screenreader during streams in Gnome

### ISSUE THREAD

**Issue by scottsweb** [ublue-os/bazzite#1220]
### Describe the bug

When using Sunshine to stream games to my TV, accessibility mode is activated in Gnome causing some menus and interactions to be read over the stream. 

There is a discussion upstream about this here: https://github.com/LizardByte/Sunshine/issues/1303#issuecomment-2075730721

From the looks of it, an updated unit file will resolve this issue.

### What did you expect to happen?

When streaming games, I only expect to hear audio from Steam and games.

**Comment by yodatak** [comment]
seem to be fix upstream with fixing system config shoud we make the fixto bazzite too ?

https://github.com/LizardByte/Sunshine/pull/2691

**Comment by yodatak** [comment]
seem to need to bumb version in the copr 
https://copr.fedorainfracloud.org/coprs/matte-schwartz/sunshine/package/sunshine/
