### ISSUE TITLE
can't recognize bluetooth adapter

### ISSUE THREAD

**Issue by physicsmeGH** [ublue-os/bazzite#1221]
### Describe the bug

My xbox one series controller can't get connection after a system upgrade. The xbox light keeps flashing. Holding the pairing key doen't work.
The "bluetooth" section in deck settings showed no devices.
When I got to desktop mode system settings, the bluetooth tab showed "no bluetooth adapter available".
At first I thought it might be my wireless card that's problematic but I can still see all the wi-fi SSIDs that are available in deck's network settings.

### What did you expect to happen?

I expect bluetooth to work.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:6c59a228186bdbd3417580129702a9337c2edadac0206b0d4773df53dca58413
                  Version: 40.20240611.0 (2024-06-11T17:01:53Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:a1ec3bf9d97e11671ea5c62dbb7a42bce3d8dc5e498cde4164f5f43743e8301a
                  Version: 40.20240609.0 (2024-06-09T18:10:52Z)
```

### Hardware

ryzen 7700
rx 7900xt
b650 motherboard
32GB DDR5 6000 RAM
intel AX210 wi-fi card

**Comment by HikariKnight** [comment]
Probably a bluez update upstream that has a regression again.
rollback to the older image until it is fixed
`bazzite-rollback-helper rebase  40-stable-20240609`
`40-stable-20240609` is your previous image as seen in `rpm-ostree status` and should not have the issue.

new automatic builds are made on tuesdays and thursdays.
you can go back to the current stable to check if bluez has been fixed with
`bazzite-rollback-helper rebase  stable`

**Comment by MattyPixels** [comment]
I have the same issue with also an Intel AX210.
I tried booting to my previous version, being 40.20240611.0 and it didn't fix it.
I will try rebaising to 40-stable-20240609.

**Comment by physicsmeGH** [comment]
> Probably a bluez update upstream that has a regression again. rollback to the older image until it is fixed `bazzite-rollback-helper rebase 40-stable-20240609` `40-stable-20240609` is your previous image as seen in `rpm-ostree status` and should not have the issue.
> 
> new automatic builds are made on tuesdays and thursdays. you can go back to the current stable to check if bluez has been fixed with `bazzite-rollback-helper rebase stable`

updated to 40.20240624
Still can't recognize xbox series controller on start up.
But good news is the system do recognize the bluetooth adapter now. If I go to the bluetooth page in deck UI with a keyboard, it says "looking for device" then it'll connect. But never before I do this little maneuver no matter how long I wait.
It's kind of annoying having to do this every time I boot up.

**Comment by levi2m** [comment]
i'm facing the same issue here

PC Specs:
Intel i5-11400F
32GB DDR4 Asgard ARGB
Asus RTX 2060 6Gb OC
Intel AX210 Wifi6E + BT5.2

i've done all type of manouvers, even disassemble my hole pc (which is a mini itx case that made a mess LOL) and assembling again haven't done anything.

Wifi keeps dropping, no matter what i do to the router nor the type of authentication, WPA2/WPA2-PSK/WPA3 (Havent tried WEP but cmmon guys, its 2024)

Someone got any clue? Rebasing didnt do anything and its not related to hardware issue, as it runs flawlessly the same chip on my all-amd machine.
