### ISSUE TITLE
Random noises in the discord app

### ISSUE THREAD

**Issue by UnFearHQ** [ublue-os/bazzite#1222]
### Describe the bug

I get weird random white noises coming out of my mic input while using apps that require it. The noise is not very loud and can be removed with Krisp but still annoys everyone when noise reduction is disabled

### What did you expect to happen?

I expect to get normal sound with no perturbation except some white noise sound come out of my mic. I expect only the room background sound but I get some pulsating white noise that overlap with my voice

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:cad98508dbe885768dc11db237563ef08afe59cce57b4b6b8d103ce84ecb0718
                  Version: 40.20240609.0 (2024-06-09T18:08:52Z)
          LayeredPackages: sunshine
            LocalPackages: lact-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:92dc34b4b2f259cfe0d55bd39973e7825ab6b9a799a9445f1f87ebe88a1d377c
                  Version: 40.20240607.0 (2024-06-07T16:58:02Z)
          LayeredPackages: sunshine
            LocalPackages: lact-0.5.4-0.x86_64
```

### Hardware

Computer : 
Intel I5 8400
AMD Radeon RX580
16GB Ram 2666MHz DDR4
1TB Seagate Barracuda HDD

Sound : 
PreSonus AudioBox USB 96
Rode NT1-A

Also tried and got the same bug with Razer Seiren Mini

### Extra information or context

 I know it doesn't come from my sound card of my mic though because I have a direct monitor on it and I don't hear the noise. I know someone else that has the exact same bug and they use Bazzite too, but with a different microphone and interface. Also, I don't get the noise while using other distros

Distros tried : 
- Windows
- Arch Linux
- Debian

**Comment by rekomodo** [comment]
Try changing your mic boost on `alsamixer`. Choose the audio card with `F6` and then switch to the capture device with `F4` there. Then lower the mic boost. Worked for me.
