### ISSUE TITLE
Bazzite, Doesnt work my bluetooth it never find nothing

### ISSUE THREAD

**Issue by Xgproject1** [ublue-os/bazzite#1225]
### Describe the bug

Bluetooth won find any device to pair

### What did you expect to happen?

I expect to find a device to connect

### Hardware

AMD Ryzen 5 3600 (12) @ 3.60 GHz
AMD Radeon RX 6750 XT @ 0.02 GHz 
KDE Plasma 6.0.5
Asus mother board with WIFI and Bluetooth Integrade

**Comment by physicsmeGH** [comment]
[](https://github.com/ublue-os/bazzite/issues/1221)
similar problem?

**Comment by gbraad** [comment]
Please provide more in formation, such as motherboard's model, dmesg, lsusb, or other debug information.

**Comment by rafaelmotac** [comment]
I have the same problem but in Legion Go Bazzite-OS

**Comment by KyleGospo** [comment]
> I have the same problem but on Legion Go Bazzite-OS

Can you provide more details? I am completely unable to reproduce that on my Legion Go.

**Comment by rafaelmotac** [comment]
> > I have the same problem but on Legion Go Bazzite-OS
> 
> Can you provide more details? I am completely unable to reproduce that on my Legion Go.

I bought a Legion Go this Saturday, brand new, installed Bazzite OS on it.

Everything was working fine, but today, Bluetooth cannot find and pair any device.

Bluetooth on Bazzite Legion Go use to be working fine.. I connected my Bluetooth headphone, Nintendo Switch Joycon, Xbox controller.

But now it's not working anymore.

I still have Windows on dual boot

**Comment by jimmt41** [comment]
This bug recently happen to me. I am on the latest update on Legion Go. Was working then stopped. Scanning for device does not find any thing. Bluetooth does work in Windows.
