### ISSUE TITLE
Chromium based browser glitch

### ISSUE THREAD

**Issue by MNylif** [ublue-os/bazzite#1228]
On "Bazzite Nvidia Asus KDE" Browsers like brave, chromium and even chrome bug out pretty bad on the latest version.

It was installed on a Asus gaming laptop as a dual boot and seems to work fairly well other than the occasional app glitching.

Also, I have had applications like boxes bug out and not close completely. 

I have not tested any other versions yet.

**Comment by KyleGospo** [comment]
Nvidia?

**Comment by MNylif** [comment]
Changing it to X11 helped some and definitely made it significantly more usable, but it's still not the smoothest experience.

**Comment by MNylif** [comment]
> Are you using X11? You can switch to it from the login screen.

Changing it to X11 helped some and definitely made it significantly more usable, but it's still not the smoothest experience.

**Comment by KyleGospo** [comment]
Next driver update for Nvidia will fix the issues under Wayland, and we'll remove X11 automatically at the same time so there should be no further input required.

**Comment by Poltergeisen** [comment]
This isn't fixed for me. Sometimes when I resize chrome the top bar just disappears and the entire webpage is shifted up, but my mouse behaves weirdly with it. I have to keep resizing until it fixes itself.

Any idea how to fix this?

**Comment by Poltergeisen** [comment]
![Image](https://github.com/user-attachments/assets/61fb0b66-d539-4b1a-b7fe-7f49700264ea)
This is an example of what I'm seeing. The red here is actually what the top of my chrome looks like. I'm on nvidia/wayland and the x11 option has disappeared from my login screen

**Comment by ojarosch** [comment]
I had the same issue, though found a solution within Brave itself.
In the Setting -> Appearance -> Theme you can choose to "Use GTK".
After closing all windows and opening new ones the issue is gone.
Also at least i prefer the GTK look over the "Classic" look within Brave.

**Comment by asimard1** [comment]
I tried this fix and it worked for a little while, but now it's back to the same problem no matter which theme I use.

**Comment by elavinland** [comment]
I found a solution to be going to `chrome://flags` and searching `Preferred Ozone Platform` and setting from `Default` to `Wayland` and letting chrome restart. Hope this helps someone as it was bugging me.
