### ISSUE TITLE
Latest snapshot (June 14th) makes colors washed out on my laptop

### ISSUE THREAD

**Issue by DreamingCuttlefish** [ublue-os/bazzite#1230]
### Describe the bug

(Copying from the discord)

I updated today to the new snapshot and now my colors look quite washed out on my laptop display. Rolled back to the previous snapshot and everything looks normal as it always has up until this point. 

### What did you expect to happen?

I expected the colors to look the same as before.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/dreamingcuttlefish/laptop-bazzite:latest
                   Digest: sha256:939c39bbd67b0f4d3733b1b66082a82ecc8eeccd19bdff82652502cd3224a1c2
                  Version: 40.20240613.0 (2024-06-14T19:19:18Z)
            LocalPackages: lact-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/dreamingcuttlefish/laptop-bazzite:latest
                   Digest: sha256:ca54d56ee159f4c60abe7e647ef70f3ec7dffa2b3c076551ec81fb17c5e7ba77
                  Version: 40.20240609.0 (2024-06-10T18:17:08Z)
            LocalPackages: lact-0.5.4-0.x86_64
```

### Hardware

Asus Zephyrus G14 2022 (GA402RK) w/ Ryzen 9 6900hs + Radeon RX 6800s

### Extra information or context

The only changes I make to stock bazzite with my bluebuild image are to add vscode and mullvad vpn to the base image.

Note: This problem did not occur on my desktop, just the laptop.

**Comment by KyleGospo** [comment]
Appears to be a new Asus specific issue, you'll want to pin the previous image image until this is resolved.

**Comment by DreamingCuttlefish** [comment]
Temporary fix - run: `echo 0 | sudo tee /sys/class/drm/card*-eDP-1/amdgpu/panel_power_savings`

**Comment by DreamingCuttlefish** [comment]
Reported upstream: https://lore.kernel.org/regressions/77KAHS.13UUH2XVHQQF1@gmail.com/T/#u
