### ISSUE TITLE
I have not been able to get touch gestures on Steam deck to work in game mode

### ISSUE THREAD

**Issue by Raynor119** [ublue-os/bazzite#1240]
### Describe the bug

I'm new to bazzite and I've seen that it has the option of touch gestures in game mode to access the options menu and the other button menu (...) but I haven't been able to make it work on my Steam deck

### What did you expect to happen?

como puedo habilitar los gestos tactiles en el modo juego

### Hardware

Steam deck LCD

**Comment by 11matt556** [comment]
See the note here: https://universal-blue.discourse.group/t/bazzite-3-0-1-update-released/1426

Seems it is broken in the latest release but you can roll back to an older version for now.
