### ISSUE TITLE
Xdg-open problem

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#1244]
### Describe the package

When I try to download some games like solo Leveling arise, xdg open keeps popping up and I can't download the game, is there a way to disable it so I can download the game and other files.

![PXL_20240619_152739899.jpg](https://github.com/ublue-os/bazzite/assets/43518479/96aeb584-c0fb-4cfc-ae28-734a3aeb6ed4)

![PXL_20240619_153133377.jpg](https://github.com/ublue-os/bazzite/assets/43518479/7a2cd3e5-25e3-4fd7-8db4-f769ac964312)

Desktop

**Comment by Zeglius** [comment]
You need to use Lutris or similar launchers that use wine in order to install windows games.
Please read [Bazzite gaming guide](https://universal-blue.discourse.group/docs?topic=31), more specifically the "non steam games" section.

**Comment by massatt212** [comment]
I cannot download the file, that's what popup when I press download
