### ISSUE TITLE
Device is still active error

### ISSUE THREAD

**Issue by justbagd** [ublue-os/bazzite#1245]
### Describe the bug

Trying to install BazziteOs on Asus ROG Ally Z1E. When clicking begin install I get an error saying "Device is active"

### What did you expect to happen?

I made sure to partition the SSD to wipe windows

**Comment by KyleGospo** [comment]
Disable fastboot in Windows, what's happening is your device is hibernating and not shutting down.

**Comment by justbagd** [comment]
are there any other settings that I would have to disable before installing Bazzite?

**Comment by justbagd** [comment]
Before I tried this I disabled fastboot in the BIOS. That wouldn't be considered the same thing?

**Comment by justbagd** [comment]
Hey, I did a whole new install of windows and I turned off fastboot in windows setting an in BIOS and I am getting this same issue

**Comment by Zbishop90** [comment]
I had to use asus cloud recovery to clean wipe the device and clear the Bitlocker

**Comment by Nevirion** [comment]
I have tried to download bazzite twice and have cloud recovered twice on my rog ally.  I turned off all battery button settings( fast startup)  And made sure safe boot and fast boot were disabled. I am still receiving this error. Is there anyone who'd be willing to troubleshoot with me?

**Comment by colejstocks** [comment]
I was running in to this issue. Had a previous Windows install from ASUS cloud setup. Ended up grabbing the GParted LiveCD ISO & Rufus, made a GParted boot disk, targeted the drive on the Ally X, deleted everything, and restarted the Bazzite install. This works. Note I also have safe mode off, I could test with safe mode on potentially.

**Comment by NicTanghe** [comment]
Hello is plz reopen this issue until a workaround that simply disables all the hibernation during install

**Comment by NRevTech** [comment]
The only way for me to get around this is to find an older installation media that I created (honestly had no idea that I had one remaining). Now it is installing. There seems to be a problem with the current installer that I cannot wrap my head around. Not recommending using an older installer but it may help here. After I install bazzite I am going to update it and see if that works. If not, I am going to use the new installation media that I created and see if I can install the newer Bazzite.

**Comment by heckpiet** [comment]
i did this work around:



    Go into the installer

    Open the terminal using CTRL + ALT + F1 + F7

    Press the F1-F7 keys until you get the terminal saying fedora

    Use the command lsblk to list the disks

    Find the disk, it will usually be much larger than most which shows up

    Type in fdisk /dev/<NameOfYourDisk> (replace <NameOfYourDisk> with the actual name of your disk which you found using lsblk)

    Type p and ENTER to list all partitions

    Type d to delete a partition (if you have multiple fdisk will ask you which partition to delete)

        Repeat this until every partition is deleted

    Type w to write the changes you've done in fdisk

    Restart and do the install

**Comment by AmnesiaK94** [comment]
Thank you so much.  It fixed the issue for me!
