### ISSUE TITLE
HDMI CEC is stated in support, but does not wake up my tv

### ISSUE THREAD

**Issue by WeslyG** [ublue-os/bazzite#1246]
### Describe the bug

I am using a bazzite with i5 12400f + amd 7800xt (Home Theater version with GNOME). I also have an nvidia shield connected to my tv. I was very excited about the hdmi cec support in the bazzite I was hoping to get the experience of using a gaming console, with the fact that I would be able to "wake up" my tv with the gamepad, and turn off the tv by putting the console to sleep. I would like to point out that cec commands are allowed on the tv, and the Nvidia shield handles this perfectly. However, I can't get the same behavior from bazzit. Do I have to customize anything to make this work? Or is it not supposed to work? I haven't found anything other than the support description line "Support for HDMI CEC via libCEC." I don't really understand how this works internally, however I was hoping it would "work out of the box". Can you help with this?

I will clarify that neither the wake command nor the sleep command works correctly in bazzite. 

### What did you expect to happen?

Expectedly when putting the console into sleep mode - turn off the TV. When you connect a gamepad to the console, turn on the TV.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:8ae0e256851b57be2d841e118744e8203d080df2dc35883fa3abbdcb61ac0f67
                  Version: 40.20240618.0 (2024-06-18T16:59:22Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:8ae0e256851b57be2d841e118744e8203d080df2dc35883fa3abbdcb61ac0f67
                  Version: 40.20240618.0 (2024-06-18T16:59:22Z)
```

### Hardware

 i5 12400f + amd 7800xt (Home Theater version with GNOME)
tv - philips oled 807
hdmi to hdmi 2.1 cord (ugreen)

**Comment by KyleGospo** [comment]
Most desktop hardware does not have CEC support, which includes your GPU unfortunately. 

You'll need one of these:
https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter

**Comment by WeslyG** [comment]
Wow! Thank you so much, I didn't know this before!
