### ISSUE TITLE
Legion Go - Virtual Keyboard Fails to Open

### ISSUE THREAD

**Issue by pikster1** [ublue-os/bazzite#1247]
### Describe the bug

No virtual keyboard opens on the legion go in desktop mode when tapping in a text box. The only way to call this is via the physical keypresses on the controller. Thus keyboard is inaccessible in tablet mode

### What did you expect to happen?

For a virtual keyboard to load up when tapping in a text field in desktop mode

### Hardware

Legion Go using HTPC image

**Comment by KyleGospo** [comment]
Expected behavior matching the steam deck, be sure to follow our handheld set up guide to ensure the Steam keyboard is as easy as possible to open

**Comment by gbraad** [comment]
this means you need to always need the controllers around, as the Legion Go can work in tablet mode. i tried the same, as a generic on-screen on touch would be helpful
