### ISSUE TITLE
Keyboard scalling issue

### ISSUE THREAD

**Issue by dkuku** [ublue-os/bazzite#1263]
### Describe the bug

Recently my virtual keyboard scaling is off, I have no idea how to fix it. I'm using gnome if this makes any difference - I tried to run `ujust restore-gnome-de-settings` but it did not help
![1](https://github.com/ublue-os/bazzite/assets/904179/5b9af7df-2859-4aae-ba0b-d0db9f5a192f)

### What did you expect to happen?

keyboard is scaled to 100% width

### Output of `rpm-ostree status`

```shell
rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:435341862b60cb3fcefc9230de70079ccf733ca9a0150cc15e895c1fded840ba
                  Version: 40.20240619.0 (2024-06-20T01:02:55Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:435341862b60cb3fcefc9230de70079ccf733ca9a0150cc15e895c1fded840ba
                  Version: 40.20240619.0 (2024-06-20T01:02:55Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

steam deck Jupiter

**Comment by KyleGospo** [comment]
Set your display scale in GNOME to 100% and then restart

**Comment by tduarte** [comment]
Do I have to use 100% scaling if I want the virtual keyboard to work? Or is there a way to fix the 125% or 150% mode to work?
