### ISSUE TITLE
Graphical artifacts on screen then plasmashell crashes

### ISSUE THREAD

**Issue by poiioo** [ublue-os/bazzite#1267]
### Describe the bug

I am running a brand new Bazzite install. Plasmashell is crashing at seemingly random times. Usually when playing a game, but sometimes just browsing through Steam. Graphical artifacts cover the screen, green, yellow, red triangles (looks similar to failing gpu). Then the screen goes black and I have to do a hard reboot. Happens multiple times a day. It happened with Plasma 6, and it is still happening with Plasma 6.1.

### What did you expect to happen?

No plasmashell crashes multiple times a day.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:73dabc6ac45bc2c2c8e3b5c04ea33a48d7b15bfae7972f757125a4d461f46b12
                  Version: 40.20240621.0 (2024-06-21T05:11:41Z)
            LocalPackages: lact-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:ed0d7dae4c45dca10fcca514b9e5e9f30cc8c851599cc021fd649b2441f43f9c
                  Version: 40.20240619.0 (2024-06-20T01:07:01Z)
            LocalPackages: lact-0.5.4-0.x86_64
```

### Hardware

Ryzen 1600, RX 580

### Extra information or context

"Crashed Processes Viewer" shows me this for "plasmashell":
[poiioo.pdf](https://github.com/user-attachments/files/15945328/poiioo.pdf)

**Comment by KyleGospo** [comment]
Does this happen without LACT installed?

**Comment by poiioo** [comment]
I've just run "rpm-ostree uninstall lact" and restarted the computer, will let you know how it goes!

**Comment by poiioo** [comment]
> Does this happen without LACT installed?

Sorry, even without LACT the same problem just happened while browsing Steam! This time I have two crashes in "Crashed Processes Viewer", one for Xwayland and one for plasmashell (logs attached)
[plasmashell.pdf](https://github.com/user-attachments/files/15945887/plasmashell.pdf)
[Xwayland.pdf](https://github.com/user-attachments/files/15945888/Xwayland.pdf)

**Comment by poiioo** [comment]
Xwayland and plasmashell crashed again, posting logs here in case they're helpful.

Should I be using xorg instead? Or maybe rebasing to Gnome? This machine is almost unusable as is :(
[plasmashell2.pdf](https://github.com/user-attachments/files/15948589/plasmashell2.pdf)
[Xwayland2.pdf](https://github.com/user-attachments/files/15948590/Xwayland2.pdf)

**Comment by KyleGospo** [comment]
Yea you can give GNOME a try, strange issue since you're all AMD.

I wouldn't bother with X11 at all.

**Comment by poiioo** [comment]
Should I go ahead and ignore the multiple bolded warnings about rebasing to a different desktop environment? I mean, what's the worst than can happen right?

**Comment by poiioo** [comment]
Rebased to GNOME, all is well so far, will let you know if I get any more weird crashes!

**Comment by poiioo** [comment]
No problems at all with GNOME, I guess plasmashell and my computer hate eachother for some reason? Maybe I'll try rebasing back to KDE when Fedora 41 comes out. Thanks for your help!

**Comment by poiioo** [comment]
Alright so it took a long time but I got the same wierd crash using Gnome almost immediately after turning the computer back on from "Suspend". However, in Gnome, it bumped me back to the login screen automatically where I could get back to work fairly quickly. KDE used to just hang indefinitely on a black screen requiring a forced shutdown.

I don't have "Crashed Processes Viewer" on this Gnome version so I can't post a log, unless someone has another alternative?
