### ISSUE TITLE
Gamescope Getting an error with MangoHud

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#1275]
### Describe the bug

![Screenshot_20240624_085711](https://github.com/ublue-os/bazzite/assets/43518479/26874723-d0d3-40f3-85df-5fb946a27958)
![Screenshot_20240624_085733](https://github.com/ublue-os/bazzite/assets/43518479/d9423fc7-6399-4ff3-801f-1dac99c6d082)

### What did you expect to happen?

not show this caution

### Output of `rpm-ostree status`

```shell
State: busy
Transaction: upgrade 
  Initiator: client(id:cli dbus:1.929 unit:run-r89fec630f27148288c3e101a3d1bfe48.scope uid:1000)
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b5b9747ef6b7608fcca8b9813d95509b2ae9235a1ba37a1fb49ef175c46e86bb
                  Version: 40.20240621.0 (2024-06-21T05:13:33Z)
          LayeredPackages: bottles goverlay
            LocalPackages: lact-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b5b9747ef6b7608fcca8b9813d95509b2ae9235a1ba37a1fb49ef175c46e86bb
                  Version: 40.20240621.0 (2024-06-21T05:13:33Z)
          LayeredPackages: goverlay
            LocalPackages: lact-0.5.4-0.x86_64
```

### Hardware

X79 S7

### Extra information or context

Im using Lutris to launch the game, if mangohud is enable the error shows, once disabled its all good launches no problem.

**Comment by HikariKnight** [comment]
Click OK on both, game should still work (does on my steam games at least)
Gamescope is undergoing a massive refactor by valve so i expect this "issue" to go away by itself later when it is nearing completion.
However we had to update gamescope to get gamescope-session it working properly on some handhelds and newer GPUs.

mangoapp (the mangohud ui used in gamescope-session/gamemode) should not be affected.
