### ISSUE TITLE
Local build issues: packages dependencies

### ISSUE THREAD

**Issue by kean0048** [ublue-os/bazzite#1283]
### Describe the bug

when I run 'sudo just_scripts/build-iso.sh deck kde' to release a bazzite iso image,  I got errors like:
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package wine-core-9.5-1.fc40.i686 from updates requires libgstreamer-1.0.so.0, but none of the providers can be installed
  - package wine-core-9.5-1.fc40.i686 from updates requires libgstbase-1.0.so.0, but none of the providers can be installed
  - package wine-core-9.1-1.fc40.i686 from fedora requires libgstreamer-1.0.so.0, but none of the providers can be installed
  - package wine-core-9.1-1.fc40.i686 from fedora requires libgstbase-1.0.so.0, but none of the providers can be installed
  - gstreamer1-1.24.5-1.fc40.i686 from updates  does not belong to a distupgrade repository
  - gstreamer1-1.22.9-1.fc40.i686 from fedora  does not belong to a distupgrade repository
  - cannot install both gstreamer1-1.24.5-1.fc40.x86_64 from updates and gstreamer1-1.24.4-1.fc40.x86_64 from @System
  - cannot install both gstreamer1-1.22.9-1.fc40.x86_64 from fedora and gstreamer1-1.24.4-1.fc40.x86_64 from @System

Please help me review why.  which stage needs to be resolved?
Thanks.

### What did you expect to happen?

no errors happen

**Comment by KyleGospo** [comment]
This is package drift, it happens now and then. 

Should be resolved in the latest version
