### ISSUE TITLE
Wine doesn't work

### ISSUE THREAD

**Issue by MNylif** [ublue-os/bazzite#1285]
### Describe the bug

When I set up any wine tool and tried to use an .exe file, nothing would happen at all.

### What did you expect to happen?

I expected to be able to run the .exe file line on any other win supported distro.

### Extra information or context

Despite rough edges, I still love this project

**Comment by KyleGospo** [comment]
You are expected to use Lutris or WineZGUI for this purpose. The copy of wine pre-installed is wine-core, and is only enough for Lutris's dependencies and/or running winetricks on another prefix.

**Comment by MNylif** [comment]
Is there a distribution that is within the universal blue ecosystem that can use wine in the way I’m looking to use it?
I absolutely love the project, but I’m also a programmer and I’m looking for something to use for engineering as my daily driver instead of windows.
  
On Wed, Jun 26, 2024 at 6:09 PM, Kyle Gospodnetich ***@***.***&gt; wrote:  You are expected to use Lutris or WineZGUI for this purpose. The copy of wine pre-installed is wine-core, and is only enough for Lutris's dependencies and/or running winetricks on another prefix.

**Comment by MNylif** [comment]
@KyleGospo is there anything within the universal blue ecosystem that can work for developers and I will be able to utilize wine the way I'm trying to use it?

I absolutely love these projects and I think that they are 100% some of the best Linux distributions I have ever used. 

As a distribution hopper, I am actively trying to replace windows for the most part and use Linux as my daily driver.

**Comment by KyleGospo** [comment]
Bazzite is the only universal blue image that contains wine in any capacity. 

I'm not sure if your use case, but if it can't be fulfilled by Lutris, Bottles, WineZGUI, or another prefix management solution my opinion is that it shouldn't be done.
