### ISSUE TITLE
Problems with performance overlay and VRR on Rog Ally

### ISSUE THREAD

**Issue by xshower24** [ublue-os/bazzite#1286]
### Describe the bug

On the Rog Ally version, I could not understand why, despite the 60fps capped(with MangoHud) and VRR enabled, games were still prone to stuttering, even just by moving the camera. So by running several tests, I realized that by disabling the built-in performance overlay, the camera movement suddenly became smoother. I'm not sure why, but the overlay then seems to impact the framerate of some games (From my tests Burnout Paradise Remastered and Fallout New Vegas for sure).
Also: on New Vegas and eFootball, turning VRR on produces a less fluid framerate than having it off, strange or normal?

### What did you expect to happen?

I expect that the performance overlay would not impact the fluidity of games, same for VRR.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:stable
                   Digest: sha256:fd02a7c479d81c0bb3b273cfc8610fc82972c4c15b77dba80e0678ebe195dadc
                  Version: 40.20240624.0 (2024-06-24T17:11:47Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:stable
                   Digest: sha256:ef57d83cebf13ce4d2d54fa4c8667588fef45ed60ba3d1908a6fbb8a1b09c27c
                  Version: 40.20240621.0 (2024-06-21T05:11:17Z)
```

### Hardware

ROG Ally RC71L_RC71L

**Comment by KyleGospo** [comment]
Try enabling force compositing in the game mode settings. You'll need to enable developer mode to see the option.

**Comment by xshower24** [comment]
Tried right now, unfortunately didn't work

**Comment by nerdosity** [comment]
VRR is not working from a lot of time, check it. It's always on 120hz.

**Comment by Black-Seraph** [comment]
Applies to the GPD Win Mini 2024 as well.

I figure that all eDP connected VRR displays are affected by this.
