### ISSUE TITLE
Possible to overclock LCD display?

### ISSUE THREAD

**Issue by Tobe95** [ublue-os/bazzite#1287]
Just switched from Steam OS to Bazzite and loving it so far.

One thing that isn't working though is the display overclock to 70 hz. 

With the beta release of Steam OS 3.6, Valve for some reason took away the option to disable the "unified frame rate control" under display/developer settings, needed for the overclock to work. Since Bazzite is using the same packages or even newer than Steam OS 3.6, the solution from #707 no longer applies unfortunately...

Is there currently any other way or fix to overclock the LCD display?

**Comment by Globetrotter129** [comment]
is there any benefits to having bazzite vs steam os?

**Comment by Tobe95** [comment]
> is there any benefits to having bazzite vs steam os?

I think it depends on the use case. Bazzite includes lots of features by default, that on Steam OS you have to tinker with to get them working. 

For example Btrfs instead of Ext4 as filesystem, which saves lots of disk space and has deduplication. 
VkBasalt (the Linux equivalent of Reshade) and ryzenadj come pre-installed, and you get up-to-date Kernel and Mesa versions which sometimes include performance improvements.

Also Bazzite features a 1000 HZ kernel tickrate which is [said](https://github.com/ValveSoftware/SteamOS/issues/1522) to slightly save power.

Just check the main page of this repository, it lists a lot of the features, you can also use Gnome instead of KDE as desktop environment which was made with touchscreen in mind.

**Comment by Tobe95** [comment]
To get back to my problem... I've actually found a solution. 

The Chimera OS fork of gamescope (which Bazzite uses as well), added an extra environment variable to set a custom refresh rate. This is already used in Bazzite to define the refresh rate range for some Handheld devices, not sure why this is not documented anywhere.

By adding `CUSTOM_REFRESH_RATES=30-69` to _/etc/environment_ you can actually increase the refresh rate on Steam Deck LCD as well. No need for `STEAM_DISPLAY_REFRESH_LIMITS` or `GAMESCOPE_OVERRIDE_REFRESH_RATE`.

The only difference I found compared to Steam OS 3.5 and older gamescope versions is, that my screen only goes up to a maximum of 69 Hz instead of 70. 

Trying 70 Hz actually results in the screen going crazy, the colors being washed out and some tearing-like behaviour. 
If I remember correctly even prior on Steam OS, the display would never exactly reach 70 Hz but only something like 69.7 Hz. 
I suppose newer versions of gamescope just handle this differently now, hence the issues with 70 Hz.

Closing this as solved.

**Comment by lamiska** [comment]
CUSTOM_REFRESH_RATE seems to not work anymore and it is not possible to overclock SteamDeck LCD to 70Hz.
