### ISSUE TITLE
Insecure delivery pipeline

### ISSUE THREAD

**Issue by Venefilyn** [ublue-os/bazzite#1290]
Currently there is a GitHub action that builds for `testing` and `main` respectively, which is then automatically released. But there doesn't seem to be any branch security or for that matter admin security to make me believe Bazzite has a secure delivery pipeline

It looks like the creator of Bazzite, @KyleGospo (thank you for all the work btw), has rights to push to all branches even. To me it feels extremely insecure to have an operating system that is published automatically without verification before publishing as all it takes is one compromised machine from one person with rights and the whole thing crumbles down with a vulnerability. (Even checking other ublue repos we have a lack of requiring approvals on PRs so that becomes just as bad)

Even here we check a [recent commit](https://github.com/ublue-os/bazzite/commit/3b509f962dc99f6db7e42f50435c6a3f5d855163) to testing branch that shows a PR from a private user?
![image](https://github.com/ublue-os/bazzite/assets/6598829/361f46e0-fb36-42dd-837e-9d72ac0eaab4)

![image](https://github.com/ublue-os/bazzite/assets/6598829/ff0ec875-bd53-4d8d-8f95-f80ad61a14ba)

To me there should be two things to improve the security of Bazzite

- Ensure that the two branches used, `main` and `testing` are locked down
- Ensure that either releases are reviewed (to me not appealing as all it takes is missing one line in for example #1068) or individual PRs with a requirement for a contributor approval that is not the author

This is about the security of the product, for all we know there might have been a vulnerability already happened somewhere in the git history of the various images of ublue.

**Comment by KyleGospo** [comment]
> Ensure that the two branches used, main and testing are locked down
Testing and unstable are under branch protection now, main always has been. I've also restricted force pushing to nobody for those branches.

> individual PRs with a requirement for a contributor approval that is not the author
It is like this today. I had the option to force-merge but that will be changed to 2 acks, matching ublue-os/main

Thanks for the input.

**Comment by Venefilyn** [comment]
> Testing and unstable are under branch protection now, main always has been. I've also restricted force pushing to nobody for those branches.

Thank you :pray: 

> It is like this today. I had the option to force-merge but that will be changed to 2 acks, matching ublue-os/main
> 
> Thanks for the input.

Ack thank you. @bsherman can we have this done for https://github.com/ublue-os/ucore as well?

**Comment by bsherman** [comment]
> > Testing and unstable are under branch protection now, main always has been. I've also restricted force pushing to nobody for those branches.
> 
> Thank you 🙏
> 
> > It is like this today. I had the option to force-merge but that will be changed to 2 acks, matching ublue-os/main
> > Thanks for the input.
> 
> Ack thank you. @bsherman can we have this done for https://github.com/ublue-os/ucore as well?

Yep, thanks for caring enough to take a look and share some suggestions.

I've gone through and brought both the `ucore` and `ucore-kmods` repos into line with the same settings mentioned above.
