### ISSUE TITLE
Nvidia kernel arguments should be sidestepped on non Nvidia hardware

### ISSUE THREAD

**Issue by EyeCantCU** [ublue-os/bazzite#13]
Using the default kernel arguments the Steam Deck fails to properly load amdgpu

Removing Nvidia related arguments as well as nomodeset addresses this allowing amdgpu to load successfully

**Comment by KyleGospo** [comment]
May also be worth separating the nvidia builds into their own -nvidia variant, if only to save space in AMD configurations.

**Comment by EyeCantCU** [comment]
I can certainly do that sometime this week :)
