### ISSUE TITLE
bazzite-nvidia-stable.iso fails self-test (as of 2024-06-29)

### ISSUE THREAD

**Issue by krzentner** [ublue-os/bazzite#1302]
### Describe the bug

I downloaded `bazzite-nvidia-stable.iso` from bazzite.gg and burned it to a USB drive.
I checked the sha256sum of the ISO matched the website, and also checked that the contents of the USB drive matched the ISO.
Running "Test this media & install bazzite 40" results in an error message around 5% through checking.
This behavior was consistent across multiple computers and methods of writing to the USB drive.
I was able to workaround by downloading `bazzite-stable.iso`, then doing an `rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-nvidia:stable`.

### What did you expect to happen?

I expected "Test this media" to report success, as `bazzite-stable.iso` does.

### Output of `rpm-ostree status`

```shell
N/A
```

### Hardware

Consistent across an nvidia desktop and two laptops. I don't think this is hardware related.

**Comment by KyleGospo** [comment]
@noelmiller

**Comment by noelmiller** [comment]
> @noelmiller 

I will take a look at the logs for the Nvidia ISO and see if I can replicate it.

**Comment by noelmiller** [comment]
Self test did not fail when booting the ISO using a VM. USB Drives are notoriously unreliable. My suggestion would be to try a different USB drive. For posterity, I will burn the ISO to a spare USB drive I have and see if I can get it to fail in the same fashion.

**Comment by noelmiller** [comment]
Burned Bazzite-Nvidia to a fresh USB using Fedora Media Writer and ran into no issues doing the self test when booting on actual hardware. There is one other user that reported this issue in Discord. @KyleGospo I would say lets keep this issue open for now and see if we get more reports.

@krzentner Are you able to test installing using a different USB drive? Feel free to use the same ISO file.

**Comment by noelmiller** [comment]
@krzentner I was just made aware of this issue with Etcher: https://github.com/balena-io/etcher/issues/4261

Did you use Etcher to flash your USB?

**Comment by krzentner** [comment]
I had this happen with both Etcher and Fedora Media Writer. I manually checked the drive contents using `cmp` to check that they matched the iso contents, so I don't think the writer had anything to do with it. I haven't had the chance to try a second drive, so that could be related.

**Comment by krzentner** [comment]
Okay, I managed to find a second (extremely slow) USB drive, and the self test passes using the exact same iso file written via Fedora Media Writer using the same USB ports I used for the original write. Almost certainly I just have a flaky USB thumb drive.

**Comment by noelmiller** [comment]
> Okay, I managed to find a second (extremely slow) USB drive, and the self test passes using the exact same iso file written via Fedora Media Writer using the same USB ports I used for the original write. Almost certainly I just have a flaky USB thumb drive that works just enough to look correct on an initial read-back. Sorry about the erroneous report.

No worries! Glad you were able to test it with a different drive and it worked!
