### ISSUE TITLE
Red flashing sticks and the Legion go with brazzite won't boot

### ISSUE THREAD

**Issue by jonthemediocre** [ublue-os/bazzite#1311]
### Describe the bug

If I plugin Legion go I get flashing red sticks, if I don't plugit in and push the power nothing happens.  I have to unplug and hold it for 16 seconds to get it to stop flashing the sticks red, but I cannot get it to boot. 

### What did you expect to happen?

I expect it to boot. 

### Hardware

Legion go

**Comment by VorpalQ** [comment]
The blinking red lights happen when there's a dead battery. It sounds like your battery completely discharged and is too dead to boot. Plug it in directly to the USB-C charger that came with it, and leave it to charge for several hours before trying to power it on again.

**Comment by KyleGospo** [comment]
Reaffirming that this sounds like a dead battery, please reopen this if the issue persists.
