### ISSUE TITLE
3.5 deck mode hhd overlay key binding regression / crash

### ISSUE THREAD

**Issue by artw** [ublue-os/bazzite#1319]
### Describe the bug

handheld daemon overlay opens on both long and short press of R4 button now in yesterdays 3.5 deck image, which makes opening quick access menu a hassle. trying to configure the binding in the overlay results in "crash" of  hhd which kills the controller and touchscreen input essentially hanging the session. Can ctrl+alt+f2 to another tty and see that hhd process is still running. Didn't have time to troubleshoot further, but pretty sure it's hhd 3.0

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Hardware

GPD Win Mini 8840u

**Comment by artw** [comment]
aha, they fixed it. Please bump it up

https://github.com/hhd-dev/hhd/releases/tag/v3.1.0

**Comment by antheas** [comment]
https://github.com/hhd-dev/hhd-ui/releases/tag/v3.0.1 this is the crash you are referring to. You can get around it by using the touchscreen or touchpad, only the controller is broken.

I am not sure i fixed your button issue, use `ujust _hhd-dev` to check it out. Maybe i made it worse.

**Comment by artw** [comment]
thanks @antheas, ui crash is fixed. But button issue is still there in 3.1.0 apparently.  Overlay opens on short press of R4, instead of QAM and the setting in UI seems to have no effect

**Comment by antheas** [comment]
https://github.com/hhd-dev/hhd/commit/14ae5eea923d67a51f24b1d26ee67d0ba899e360

`ujust _hhd-dev` to check it out. If it works, I'll push a release. For now you can use the xbox elite controller instead, or disable shortcuts in the UI.

**Comment by artw** [comment]
Yep, you fixed it. Settings also work now  Thanks man :)

**Comment by artw** [comment]
@antheas pls include that fix in the next release, so it gets in here

**Comment by antheas** [comment]
It is included. I forgot to label the latest release but you can see it there
