### ISSUE TITLE
How did I end up downloading the GNOME version?

### ISSUE THREAD

**Issue by styromaniac** [ublue-os/bazzite#1324]
### Describe the bug

I swear I downloaded the KDE version. Might I have been confused or is the website not delivering the desired version?

### What did you expect to happen?

I expected to have the KDE version, but I already went through the installation and found out it's GNOME after the fact.

**Comment by KyleGospo** [comment]
Double checked website, could not reproduce issue. If you could screenshot what you downloaded that might help.
