### ISSUE TITLE
Legion Go Docked Game Mode

### ISSUE THREAD

**Issue by KardioidraK** [ublue-os/bazzite#1325]
### Describe the bug

when I connect my legion go to the docking station in game mode display black screen, i`ve tried to send ssh command "mv ~/.config/kwinoutputconfig.json ~/.config/kwinoutputconfig.json.old" but nothing happen

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

**Comment by KyleGospo** [comment]
Can you give the output of `rpm-ostree status`
