### ISSUE TITLE
Can't update to 3.5: "no data available"

### ISSUE THREAD

**Issue by Aqyv** [ublue-os/bazzite#1328]
### Describe the bug

Using System Update/`ujust update` leads to the following error:
```
error: Committing: Adding composefs metadata: Checking out composefs: Processing 90c81cc24ac0d9ee12a8a5b469e72f07febd6b09f9ed46afdd0e8bab64de3440: No data available
System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:273
```

### What did you expect to happen?

Update goes through.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:43a94e8b18644ac34a9c5e6f1611915c576bfe08f70504e4f602d58f2bd11312
                  Version: 40.20240625.0 (2024-06-27T02:08:13Z)
          LayeredPackages: openrazer-meta razergenie

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:f99281982c87a4d18bfdba2f2c06698a5017028af2e893c617546643ba542071
                  Version: 40.20240624.0 (2024-06-24T17:14:39Z)
          LayeredPackages: openrazer-meta razergenie
```
```


### Hardware
MS-7C56

### Extra information or context

_No response_

**Comment by jotaro75** [comment]
I am having the same problem!

**Comment by jotaro75** [comment]
Here the solution: https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689

**Comment by Aqyv** [comment]
> Here the solution: https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689

Are you sure?
Even if I do that I still run into the same error.

**Comment by castrojo** [comment]
See if an `rpm-ostree cleanup -m` clears it up.

**Comment by Aqyv** [comment]
> See if an `rpm-ostree cleanup -m` clears it up.

Nope, sadly not: the update is getting stuck at the exact same spot.

**Comment by KyleGospo** [comment]
Solution stated, if this is still broken for you please run the script and provide the full output of it in the terminal so we can take a closer look.
