### ISSUE TITLE
Issues I’ve had with bazziteos on Rog Ally Z1 Extreme

### ISSUE THREAD

**Issue by javonni1** [ublue-os/bazzite#1329]
### Describe the bug

Problems I've had with Bazziteos so far
1.VRR Causes issues like forcing 35 fps if turned on in certain games also when it does work it starts to cap frame rates for some odd reason it’s completely broken
2.I currently can't get the fan curves working in big picture mode even with the rog ally application and hhd can no longer be installed with the terminal 
3.If Vsync isn't enabled a lot of the times the frame limiter won't work
4.When I get the frame limiter to work in some games and I try to limit it to 40 fps it feels like 20 fps instead of 40 hard to explain but bad slowdown for sure
5.Some games like Spider-Man miles morales I can’t zip with L2 and R2 as something is wrong with the L2 button in-game 
This was used while dual booting so I don’t know if that plays a factor but these are just the problems I’ve had so far

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

**Comment by Globetrotter129** [comment]
It can seem like fps is slow if you use gyro mouse emulation along with gamepad controls in certain games which is a problem even on steam deck.
