### ISSUE TITLE
An update wiped the sd card

### ISSUE THREAD

**Issue by Globetrotter129** [ublue-os/bazzite#1331]
I did a client update on a legion go and it wiped the sd card previously formatted on a steam deck and formatted it into something steam os couldn't use and I had to reformat it on a steam deck (from btrfs to ext4?)

Edit: Formatted to btrfs with partition manager and now working. The Steam formatter fails.

**Comment by unicornsandcandies** [comment]
> I did a client update on a legion go and it wiped the sd card previously formatted on a steam deck and formatted it into something steam os couldn't use and I had to reformat it on a steam deck (from btrfs to ext4?)

There appears to be an issue with SD cards. If you take it out and put in again, it works

**Comment by Globetrotter129** [comment]
> > I did a client update on a legion go and it wiped the sd card previously formatted on a steam deck and formatted it into something steam os couldn't use and I had to reformat it on a steam deck (from btrfs to ext4?)
> 
> There appears to be an issue with SD cards. If you take it out and put in again, it works. Same with steam deck oled

I had to format the card to btrfs in partition manager

**Comment by HikariKnight** [comment]
Our updates (`rpm-ostree update`) do not touch external media, it only cares about the system disk that bazzite is installed on which would be the internal nvme.
