### ISSUE TITLE
bcachefs as an install image option

### ISSUE THREAD

**Issue by catleeball** [ublue-os/bazzite#1335]
### Describe the package

(please let me know if this FR would be a better fit in another repo!)

It would be wonderful if Bazzite would support [bcachefs](https://bcachefs.org) in the GUI installer usb workflow, either for the root filesystem, or for secondary storage.

Thanks!

### Image

Desktop

**Comment by KyleGospo** [comment]
This would be up to Fedora to provide, way out of scope for us I'm sorry to say.
