### ISSUE TITLE
FPS Limiter + GPU Clock Sliders not working on clean install

### ISSUE THREAD

**Issue by jtweedie** [ublue-os/bazzite#1338]
### Describe the bug

When using the QAM FPS limiter the limit isn't engaged. The FPS effectively becomes unlimited. The Manual GPU Clock slider is missing when the toggle is set to enabled.

### What did you expect to happen?

The FPS limiter should engage and the GPU Clock should be selectable.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:1411015137f25da15c373572b1bd68c54f5c5f5b81891b04b407a881bdbc687f
                  Version: 40.20240706.0 (2024-07-06T07:06:54Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:3129862c3ce46ae50b56f147ebd67d67baa4f5e4894d9f46b80af9f0698883fd
                  Version: 40.20240705.0 (2024-07-05T05:57:08Z)
```

### Hardware

Steam Deck LCD

### Extra information or context

These options seem to have worked recently, but I clean installed Bazzite-Deck on July 6th and that's when I noticed the issues.

**Comment by KyleGospo** [comment]
Both issues should be resolved in today's update.

**Comment by jtweedie** [comment]
Thanks for your hard work. It's really appreciated!
