### ISSUE TITLE
Sound settings not saved across reboots

### ISSUE THREAD

**Issue by T13nou** [ublue-os/bazzite#1339]
### Describe the bug

Hi ! 

I've got my HTPC running Bazzite pretty well but I need to set the sound device at each reboot. I'm using audio thru HDMI as my HTPC is connected to the TV.

When I go to Settings > Audio, I have 3 options
- Default (auto)
- Internal Audio
- Navi31 HDMI/DP Audio

The settings I'm using is the Navi31 HDMI as my HTPC is connected to the TV and renders video & sound thru it.

At each reboot, default (auto) is selected and I need to set again Navi31 HDMI/DP manually.

### What did you expect to happen?

That the settings I choose manually keeps the same across reboots.

### Hardware

CPU : Intel 13600K
GPU : AMD 7900 XT
DDR5 : 64 Go

**Comment by KyleGospo** [comment]
This is expected behavior, Steam game mode will always default to the output set by Wireplumber. If you need to change that default you need to modify your configs.

**Comment by T13nou** [comment]
Thanks @KyleGospo ! Can you please explain how could I do that ?

**Comment by KyleGospo** [comment]
```monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.*"
        alsa.card_name = "Wireless Controller"
      }
      {
        node.name = "~alsa_output.*"
        alsa.card_name = "Wireless Controller"
      }
    ]
    actions = {
      update-props = {
        priority.driver        = 90
        priority.session       = 90
      }
    }
  }
]
```

Here's an example config that *lowers* the priority of a given output.
By changing the priority to be the highest (Get your list of outputs and their priorities with `pactl list sinks`), you will change the default selected audio output. That same command will also list the various properties you can use to match your desired output.

**Comment by T13nou** [comment]
Thanks @KyleGospo :) Not sure about where to find this config file and how to change it. Any guidance ? 

Thanks ! 

T13nou
