### ISSUE TITLE
Create a hyprland\sway image

### ISSUE THREAD

**Issue by grisha765** [ublue-os/bazzite#1344]
### Describe the package

Please add a hyprland image so that there is wm hyprland in the image.

### Image

Deck

**Comment by KyleGospo** [comment]
We may do a sway image in the future, but it would be in the distant future. The deck user experience for a window manager would be extremely poor. 

We will at no point make a hyperland image.

**Comment by KyleGospo** [comment]
> > We may do a sway image in the future, but it would be in the distant future.
> 
> ok, but how can you try to implement this yourself?

You can create a custom image, instructions are on our website.

**Comment by KyleGospo** [comment]
> > We will at no point make a hyperland image
> 
> hello, why not

The lead developer has been banned from FreeDesktop. As a policy we will not involve ourselves with anything they create.
