### ISSUE TITLE
lenovo legion go not working bazzite-rollback-helper rebase

### ISSUE THREAD

**Issue by Raynor119** [ublue-os/bazzite#1349]
### Describe the bug

I want to revert to an older version of bazzite so I can use touch gestures in game mode but when I use the bazzite-rollback-helper rebase command I get this error

bazzite-rollback-helper rebase 40-stable-20240427
Rebasing to ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:40-stable-20240427. Continue? [y/N]:y
rebasing to bazzite-deck:40-stable-20240427
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:40-stable-20240427
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: cryptographic signature verification failed: invalid signature when validating ASN.1 encoded signature

### What did you expect to happen?

I need to know how I can return to a version of bazzite where touch gestures work or can touch gestures be made to work in the most recent stable version

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:064390c9aa477993b7c7e0189c34d45d8248366906185da8a792a764c313d75a
                  Version: 40.20240707.0 (2024-07-07T23:44:11Z)
          LayeredPackages: gnome-disk-utility

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:1e3f2b13e72fd6915eba47d42f2b9c7efe406d6d77093d3e425bbad4289e8759
                  Version: 40.20240710.0 (2024-07-10T18:28:41Z)
          LayeredPackages: gnome-disk-utility
```

### Hardware

83E1

**Comment by Evilexium** [comment]
I need this too for my ROG ALLY RGB is Broken becasue of BazziteOS , even after fresh Windows 11 Install Rainbow RGB is DARK and doesnt work i hate this

**Comment by KyleGospo** [comment]
> I need this too for my ROG ALLY RGB is Broken becasue of BazziteOS , even after fresh Windows 11 Install Rainbow RGB is DARK and doesnt work i hate this

Try the latest update for your issue

**Comment by nerdosity** [comment]
> > I need this too for my ROG ALLY RGB is Broken becasue of BazziteOS , even after fresh Windows 11 Install Rainbow RGB is DARK and doesnt work i hate this
> 
> Try the latest update for your issue

Can you please help on VRR and HDR on Rog Ally? I know how to work in linux, but never used a immutable OS before.

**Comment by Evilexium** [comment]
> > > I need this too for my ROG ALLY RGB is Broken becasue of BazziteOS , even after fresh Windows 11 Install Rainbow RGB is DARK and doesnt work i hate this
> > 
> > 
> > Try the latest update for your issue
> 
> Can you please help on VRR and HDR on Rog Ally? I know how to work in linux, but never used a immutable OS before.

There is no HDR on Rog ally , But VRR works i use CachyOS for that VRR works there on bazziteOS VRR is broken as far i know , someone maybe is up to date and know if VRR is fixed on BazziteOS
