### ISSUE TITLE
GPD Win Mini 2024 7640u: Wrong Panel Orientation

### ISSUE THREAD

**Issue by nickgarvey** [ublue-os/bazzite#1350]
### Describe the bug

The GPD Win Mini 2024 has a native landscape panel.

For the 2024 7640u model, this code looks to incorrectly set it to a right_size_up panel, like the 2023 model.

https://github.com/ublue-os/bazzite/blob/996d161bfb27432e1bd396236c63e932b5d8e981/system_files/desktop/shared/usr/libexec/bazzite-hardware-setup#L106-L110

### What did you expect to happen?

I expected my grub config not to contain video=eDP-1:panel_orientation=right_side_up 

### Output of `rpm-ostree status`

```shell
root@passim-98c2:/boot# rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:1e3f2b13e72fd6915eba47d42f2b9c7efe406d6d77093d3e425bbad4289e8759
                  Version: 40.20240710.0 (2024-07-10T18:28:41Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:064390c9aa477993b7c7e0189c34d45d8248366906185da8a792a764c313d75a
                  Version: 40.20240707.0 (2024-07-07T23:44:11Z)
```

### Hardware

root@passim-98c2:/boot# cat /sys/devices/virtual/dmi/id/product_name
G1617-01

### Extra information or context

```
root@passim-98c2:/boot# cat /proc/cpuinfo  | head
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 116
model name      : AMD Ryzen 5 7640U w/ Radeon 760M Graphics
stepping        : 1
microcode       : 0xa704104
cpu MHz         : 400.000
cache size      : 1024 KB
physical id     : 0
```

**Comment by KyleGospo** [comment]
Fixed in next build, thanks again!
