### ISSUE TITLE
batterylimit.service not respecting max_battery_charge_level

### ISSUE THREAD

**Issue by astrojuno** [ublue-os/bazzite#1355]
### Describe the bug

Edited /etc/default/batterylimit so it reads:
MAX_BATTERY_CHARGE_LEVEL=80

Started batterylimit.service by:
sudo systemctl enable batterylimit.service

Drained the battery below 80%. Plugged device in, battery charged to 100%.

### What did you expect to happen?

Battery to only charge to ~80%.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:c53a8b7cdb78233b3b13f58a6f770b18a0abb8f6f283e9cf4cf33d3c8f552a74
                  Version: 40.20240712.0 (2024-07-12T04:58:14Z)
                     Diff: 82 upgraded, 16 removed, 15 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:34717b5e0862ae1d242402807ba5b0ce7907f83e840cf6603840e489c9457a93
                  Version: 40.20240706.0 (2024-07-06T07:24:58Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:34717b5e0862ae1d242402807ba5b0ce7907f83e840cf6603840e489c9457a93
                  Version: 40.20240706.0 (2024-07-06T07:24:58Z)
```

### Hardware

Lenovo Legion Go
cat /sys/devices/virtual/dmi/id/product_name: 83E1

### Extra information or context

SSD has been upgraded, let me know if that's relevant and more details are needed.

Dual boot scenario (Windows and Bazzite). Windows has not been booted since attempting battery limit.

**Comment by KyleGospo** [comment]
That service is only for the steam deck, the feature you're looking for is present in HHD. I would disable this service and use that.
