### ISSUE TITLE
invalid signature when validating ASN.1 encoded signature

### ISSUE THREAD

**Issue by webmaster-exit-1** [ublue-os/bazzite#1356]
Running a system image update/upgrade and this happens:
```sh
rpm-ostree upgrade 
```
* **Pulling manifest**: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
* **error**: Creating importer: **_Failed_** to invoke **_skopeo_** proxy method 
* OpenImage: remote **error**: cryptographic signature **_verification failed_**: invalid signature when validating ASN.1 encoded signature

**Comment by castrojo** [comment]
Follow these directions:

https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689

**Comment by webmaster-exit-1** [comment]
the fix script worked like a charm ty. a desktop plugin specifically made for notifying users of urgent fixes would be nice. Instead of hunting it down. This would obviously be opt-in via the user installing it. I think (specially for less tech savey ppl) this would be welcomed. Thank You.

**Comment by KyleGospo** [comment]
Unfortunately this was a mistake on our end so we're not able to push an update to add such a notification, we've adjusted our policy to make sure this doesn't happen again and will work on modifying the updater so we can notify when things like this occur.

**Comment by webmaster-exit-1** [comment]
Oh it was an internal mistake, no worries. Maybe write a ci workflow file to catch these mishaps in the future would help?  Cheers
