### ISSUE TITLE
vkBasalt Not Working Globally

### ISSUE THREAD

**Issue by TheRhysWyrill** [ublue-os/bazzite#1357]
### Describe the bug

vkBasalt only appears to be working when in a game directory and not globally.

### What did you expect to happen?

For it to enable globally if it works when a config file is placed in a game directory.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:a608ad5df694a80cf1bd82fe5ad3e8bdbbb869965fbea68c11055685065eb518
                  Version: 40.20240712.0 (2024-07-12T05:19:28Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:1e3f2b13e72fd6915eba47d42f2b9c7efe406d6d77093d3e425bbad4289e8759
                  Version: 40.20240710.0 (2024-07-10T18:28:41Z)
```

### Hardware

Model: Beelink GTR6 Mini PC
CPU: Ryzen 9 6900HX
GPU: Radeon 680M
RAM: 32GB DDR5

### Extra information or context

I've tried adding environmental variables as well as trying the main config in several of the default locations listed but no matter what it just refuses to work globally and I'm out of ideas as to why.

**Comment by KyleGospo** [comment]
https://github.com/DadSchoorse/vkBasalt?tab=readme-ov-file#configure
