### ISSUE TITLE
Black screen on SDDM/Wayland on first boot with Nvidia card

### ISSUE THREAD

**Issue by agorgl** [ublue-os/bazzite#1369]
### Describe the bug

Fresh installation of latest `bazzite-nvidia` (I believe currently on version 3.5.1), boots into black screen.
This seems to be another Wayland <-> Nvidia compatibility problem because similar behavior is exibited by plasma when started manually with `startplasma-wayland` from a tty.
Both SDDM and Plasma work fine in X11 mode

### What did you expect to happen?

See SDDM in order to be able to login, login to functional Plasma environment

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:89a4a6c1383698d407404343ee36eadaea53d31e9dd19ee6791e71082757097b
                  Version: 40.20240714.0 (2024-07-14T16:27:45Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:0e152de42de6781cc8249573ad875e10804a568d3658de39e8379405440065fd
                  Version: 40.20240714.0 (2024-07-14T16:27:45Z)
```

### Hardware

```
nvidia card: RTX A1000 Laptop GPU
```

### Extra information or context

```
nvidia kernel module version: 555.58.02
```

**Comment by agorgl** [comment]
Some more notes:

The above problem was reproduced in a linux vm with pci passthrough (vfio).
It seems that the problem occurs when both a spice display and the pci passthrough are assigned to the vm.

After removing spice display and virtio video (and all their dependencies) from vm details in virt-manager, bazzite sddm/plasma with wayland seems to work normally.

**Comment by agorgl** [comment]
Keep in mind that this is something I tried for the first time, so I don't know if its a plasma-wayland with multiple video cards (virtio vga/spice + real pci card) issue or a nvidia driver issue.

In any case I'll leave it open a little bit for further feedback, and I'll close this soon because it seems irrelevant with the bazzite project.

**Comment by ageisen2000** [comment]
I'm also getting this without doing it from a VM. A maintainer on discord mentioned that this could be an HDR bug.

**Comment by agorgl** [comment]
Yeah I saw similar mentions to HDR problems with the nvidia 555 driver:
https://bbs.archlinux.org/viewtopic.php?id=297236
https://bugs.kde.org/show_bug.cgi?id=488941
https://forums.developer.nvidia.com/t/nvidia-555-52-04-plasma-6-1-wayland-screen-turn-off-on-login/297197

I'm not sure this is the case here though, because I checked in `~/.config/kwinoutputconfig.json`, and both "highDynamicRange" and "wideColorGamut" where set to false.

The problem went away only when I removed the spice/virtio device from virt-manager in my case which is really inconvenient because I need to plug a real monitor to my gpu that is being passed through in order to see the vm output

**Comment by ageisen2000** [comment]
Yes, I personally don't believe it's an HDR issue because I'm having the same problem from a live USB and it generally has HDR disabled by default. I don't know enough to troubleshoot the issue though. I can provide more logs, I just need to know what commands to run.

**Comment by ageisen2000** [comment]
This seems really close to what I've been experiencing. Looks like it's potentially a bug with KDE

https://bugs.kde.org/show_bug.cgi?id=488941

**Comment by agorgl** [comment]
Another discussion that might have relevant info:
https://forums.developer.nvidia.com/t/555-release-feedback-discussion/293652/45?page=3
