### ISSUE TITLE
The max resolution UI on legion go is a battery hog.

### ISSUE THREAD

**Issue by Globetrotter129** [ublue-os/bazzite#1381]
A 1600x1000 option would help a lot.

**Comment by HikariKnight** [comment]
> A 1600x1000 option would help a lot.

Sadly setting the panel on the legion go to anything but its max resolution in linux results in a film grain image :(
![rn_image_picker_lib_temp_a474062f-edc8-4d02-8549-8be630a10ffa](https://github.com/user-attachments/assets/c200b9a9-d1f7-44e1-ab10-778976189e0e)
