### ISSUE TITLE
ROG Ally Boots to Black Screen

### ISSUE THREAD

**Issue by Rise2gether** [ublue-os/bazzite#1382]
### Describe the bug

After updating Bazzite to v3.60 on my ROG Ally, booting presents an infinite black screen. The fans can be heard but Steam gamemode doesn't load.
I've attempted the fixes on issues #593 and #1210 to no avail. 
1) Ctrl+Alt+F2 at first led to a frozen terminal login screen but no longer does. End result is a blank screen. One thing I do remember is a short description of the system and it saying kernel 6.9.9. Idk if that's a clue of interference with the commit to force apple kernel 6.9.8?
2) Pressing ESC on boot, the regular startup is shown but ends with a blank terminal. 
In both instances the only thing that has work is Ctrl+Alt+Delete and the system restarts.

### What did you expect to happen?

Expected system to boot but leads to blank screen. Attempting to reach rollback or terminal leads to blank screen.

### Output of `rpm-ostree status`

```shell
Cannot enter system to input command.
```

### Hardware

Asus ROG Ally RC71L

**Comment by nicknamenamenick** [comment]
Rollback (spam the escape key or equivalent on the ROG Ally) as soon as the Ally is rebooted.  You will see the GRUB menu and 2-4 Bazzite entries with (:0) and (:1) displayed after a date.  Select the 2nd entry with (:1) to go to your previous boot and then update again.  There was a kernel issue on the initial Bazzite 3.6.0 build.

Read more about rolling back system updates [here](https://universal-blue.discourse.group/docs?topic=2644)
