### ISSUE TITLE
SD Card not auto mounting on boot

### ISSUE THREAD

**Issue by codevski** [ublue-os/bazzite#1383]
### Describe the bug

I'm trying to determine if this issue is hardware-related. After reboots, I need to manually mount the SD card in desktop mode or reinsert it in game mode. Fresh installs of Bazzite work fine initially, but updates cause the SD card to require manual mounting. Removing and reinserting the SD card resolves the issue temporarily. Essentially, I need to either reinsert the SD card upon reboot or manually mount it by clicking on the folder in desktop mode.

### What did you expect to happen?

Should auto mount SD card on boot. Works fine on wake from sleep or reinserting the card.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:82624ab8dc34f83515f74cdaa160683f342cc62b8dd2d485fa2d465385ec5fab
                  Version: 40.20240717.0 (2024-07-17T17:10:50Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:9dd5cf961270659215f5a20a2884eef5ce4d7c203bac4de1125cbc32aa34c6fe
                  Version: 40.20240716.0 (2024-07-16T04:58:03Z)
```

### Hardware

ROG Ally RC71L

### Extra information or context

Ran the following commands to get some logs
```
#!/bin/bash
(
  echo "Output of sudo lsblk -d /dev/mmcblk*:"
  sudo lsblk -d /dev/mmcblk*
  echo

  echo "Output of sudo blkid /dev/mmcblk*:"
  sudo blkid /dev/mmcblk*
  echo

  echo "Output of sudo e2fsck -n -f /dev/mmcblk0p1:"
  sudo e2fsck -n -f /dev/mmcblk0p1
  echo

  echo "Output of grep mmcblk /etc/fstab:"
  grep mmcblk /etc/fstab
  echo

  echo "Output of sudo journalctl -b | grep -E 'mmcblk|steamos-automount':"
  sudo journalctl -b | grep -E 'mmcblk|steamos-automount'
) | fpaste
```

Before mount: https://paste.centos.org/view/b16434b4
After Mount: https://paste.centos.org/view/bfa88203

Im noticing: `Skipping mounting /dev/mmcblk0p1 because it has not been inserted recently` not sure if thats normal

fstab:
```
#
# /etc/fstab
# Created by anaconda on Wed Jul 17 06:41:42 2024
#
# Accessible filesystems, by reference, are maintained under '/dev/disk/'.
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info.
#
# After editing this file, run 'systemctl daemon-reload' to update systemd
# units generated from this file.
#
UUID=6a5a8e29-cc41-4eee-9fe2-1d3b354f3461 /                       btrfs   subvol=root,noatime,lazytime,commit=120,discard=async,compress-force=zstd:1,space_cache=v2 0 0
UUID=422a7f2b-2ca8-469d-9de1-3031bd34d161 /boot                   ext4    defaults        1 2
UUID=676B-0059          /boot/efi               vfat    umask=0077,shortname=winnt 0 2
UUID=6a5a8e29-cc41-4eee-9fe2-1d3b354f3461 /home                   btrfs   subvol=home,noatime,lazytime,commit=120,discard=async,compress-force=zstd:1,space_cache=v2 0 0
UUID=6a5a8e29-cc41-4eee-9fe2-1d3b354f3461 /var                    btrfs   subvol=var,noatime,lazytime,commit=120,discard=async,compress-force=zstd:1,space_cache=v2 0 0
```

I have tried multiple sd cards all the same effect.

Not sure if its related: https://github.com/ValveSoftware/SteamOS/issues/1141

**Comment by KyleGospo** [comment]
This may be fixed in the latest version

**Comment by codevski** [comment]
> This may be fixed in the latest version

I think so, I have not had this issue occur
