### ISSUE TITLE
System stuck after exiting sleeping mode

### ISSUE THREAD

**Issue by SamlRx** [ublue-os/bazzite#1391]
### Describe the bug

After waking up from sleep mode, my desktop appears but everything is blocked. Moving my mouse or typing on my keyboard doesn't seem to work and I have to reboot.

I also noticed a longer startup time, I'm not sure if that's related to that.

### What did you expect to happen?

I expect to be able to properly exit sleeping mode

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:latest
                   Digest: sha256:fa31ee24ac5aa12c43f5ee6be99a6bda8cd806f34727aef6b6ecc9c7bd578e6a
                  Version: 40.20240717.0 (2024-07-17T17:34:29Z)
          LayeredPackages: alacarte coolercontrol libvirt liquidctl openrazer-meta patch
                           razergenie sunshine virt-manager
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:latest
                   Digest: sha256:58787f200ef7d5cc53bdb4e01abac333d48a0d8dd9fa85181375e0fbf61095b8
                  Version: 40.20240716.0 (2024-07-16T04:54:06Z)
          LayeredPackages: alacarte coolercontrol libvirt liquidctl openrazer-meta patch
                           razergenie sunshine virt-manager
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64
``
```

### Hardware

```
MS-7C91
```

### Extra information or context

I have never noticed this type of behavior with the previous Bazzite version

**Comment by gordon-boom** [comment]
Are you booting into Wayland or X11?

There is a bug report that matches what you're describing when using KDE with X11.

https://bugs.kde.org/show_bug.cgi?id=489846

**Comment by SamlRx** [comment]
Not sure, How can I verify that. As far as I know I'm using the last vanilla bazzite-gnome version.

**Comment by SamlRx** [comment]
I have tried the fix here: https://askubuntu.com/questions/1347924/20-04-freezes-after-waking-up-from-suspend

It seems to work, exiting from sleeping mode does not stuck my system anymore. But It takes much more time than before.

**Comment by DJKero** [comment]
Just to chime in, I have a similar issue with KDE (Wayland Session) but mine doesn't even turn on the screen and the keyboard numlock doesn't respond. I'm going to update and see if it keeps happening.

**Comment by SamlRx** [comment]
What is your GPU brand ? Did you try the fix in the link above ?

**Comment by DJKero** [comment]
> What is your GPU brand ? Did you try the fix in the link above ?

I use AMD.

Here's my HW setup:
Gigabyte B550M AORUS ELITE
AMD Ryzen 5 5600X
16GB RAM
AMD Radeon RX 6800 XT

I disabled IOMMU from my BIOS and it solved the issue, but I'd like to know why this is the case and the bug in question so I can reenable IOMMU when its fixed from upstream.
