### ISSUE TITLE
Legion go i Can no longer update an error message comes up

### ISSUE THREAD

**Issue by denver8989** [ublue-os/bazzite#1393]
### Describe the bug

remote error: cryptographic signature verification failed: invalid signature when vali dating ASN.1 encoded signature, it's been like that a few weeks I'm hoping there's a fix without having to do a clean install 🤞.

### What did you expect to happen?

I click the bazzite update icon and this error comes up.

**Comment by p5** [comment]
Hey there

We made a mistake a few weeks ago, and this resulted in broken system updates.
Please see this forum post for remediation steps.

https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689

> We have a script that will resolve the issue. You are strongly recommended to review the script first prior to running it [by inspecting it here 1.0k](https://github.com/ublue-os/config/blob/5c4144d38a2a61e44ca704ffdf2d50bbcb9ff7ed/scripts/fix-key-and-update.sh). You can either perform those steps by hand or use this following command:
> ```
> $ curl -sL https://fix.universal-blue.org/ | sudo bash
> ```
