### ISSUE TITLE
Scaling Mode & Scaling Filter Broken

### ISSUE THREAD

**Issue by Shaunathanz** [ublue-os/bazzite#1395]
### Describe the bug

In Game mode, gamescope does not respond or read Steam scaling mode or scaling filter settings. Changing the settings has no effect. The scaling mode behavior also seems to be in line with stretch setting and filtering seems linear.

### What did you expect to happen?

I would expect the per-game setting to be used, and that changing the settings would change the behavior. 

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:38727f6960f2efbaf7621e1308bff8298865db89fef55be9b0bee76535a3a454
                  Version: 40.20240722.0 (2024-07-22T14:31:39Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:38727f6960f2efbaf7621e1308bff8298865db89fef55be9b0bee76535a3a454
                  Version: 40.20240722.0 (2024-07-22T14:31:39Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:571e1c2fb00822e12a88ea0dabb631074c88356ab5213a829a7c178f3d286bfe
                  Version: 40.20240517.0 (2024-05-17T17:09:39Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
                   Pinned: yes

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:356352db7875fd4c0afc848d86d553b034bb273f14cc6cacfb2694266fd8c73c
                  Version: 40.20240508.0 (2024-05-08T22:07:02Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
                   Pinned: yes

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:d35aeeb3e69019a1bb0ee0f45ecaad186a4e8c9f4446e7fd3ca3c1200db52022
                  Version: 40.20240507.0 (2024-05-08T06:29:42Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
                   Pinned: yes

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite-deck-gnome:39-20240407
                   Digest: sha256:99f91518ceafb75094bd0e5483672af4d13baa2ed4ffc0b009f1a6ff28226dca
                  Version: 39.20240406.0 (2024-04-07T01:32:16Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
                   Pinned: yes
```

### Hardware

83E1

### Extra information or context

Lenovo Legion Go

**Comment by KyleGospo** [comment]
Working here, but it does depend on the title. What are you experiencing # this in? Some games will always use the full display resolution and do their own upscaling, which completely invalidates what Gamescope might want to do.

**Comment by Shaunathanz** [comment]
Hi Kyle! 

I am seeing the issue in Monster Hunter Rise, Resident Evil 4 Remake, Sackboy A Big Adventure to name a few. Before I updated today I was running 40.20240517.0 and my games were scaling and filtering fine. I restarted my device and it actually seems to have helped RE4R but not the other games... not sure what to make of that. MHRise and Sackboy are still not working post restart. I tried an older proton version but that didn't have an effect.

I was thinking of maybe rolling back to confirm that the old bazzite actually works but even if that's true, what artifacts would be useful in narrowing down the cause of the problem?

**Comment by ibanezbass** [comment]
I’m also seeing this with all Sony games at least. Fullscreen exclusive mode causes the picture to take up 1/4 of the screen and refuses to scale.

**Comment by LeonardoMeireles55** [comment]
<p>It is necessary to force a resolution for the scaling filters to work. For example, 1600x900 with the integrated screen option activated.</p>
<img src="https://github.com/user-attachments/assets/4ffc5d2a-2a34-4ba1-92a7-3b8243658bea" alt="Image 1" width="300">
<img src="https://github.com/user-attachments/assets/a5235b93-d1dd-4866-9594-cf28850ab12d" alt="Image 2" width="300">

**Comment by ibanezbass** [comment]
> It is necessary to force a resolution for the scaling filters to work. For example, 1600x900 with the integrated screen option activated.
> 
> <img alt="Image 1" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900089-4ffc5d2a-2a34-4ba1-92a7-3b8243658bea.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mjg2MzgsIm5iZiI6MTcyMTkyODMzOCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMDg5LTRmZmM1ZDJhLTJhMzQtNGJhMS05MmE3LTNiODI0MzY1OGJlYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTcyNTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBiODFmOWQ1ZDA3MTNhYjlkMWNiYTJjNTZhYWUxNjA3ODE5NGQ2YjNmMDhiMGY2ODgzYjhhYWRhNGJkNDUzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PvRrlTHJF1LY5-VT1EIR9jtaiKO_CaN1iX_bWefQO7s"> <img alt="Image 2" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900213-a5235b93-d1dd-4866-9594-cf28850ab12d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mjg2MzgsIm5iZiI6MTcyMTkyODMzOCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMjEzLWE1MjM1YjkzLWQxZGQtNDg2Ni05NTk0LWNmMjg4NTBhYjEyZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTcyNTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNjYWFjOTY5OTRhYzg1MDQxNTQ2MjY5ZjYwNzdlMTYzZDUyODZlNGNjYjUzNzdlNDcwOGFjYWZhNWQ5Njc5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FnjS9LEMZBHymdxrdHFOLYwg_TjGdum8UMNACTESoIY">

That doesn't do anything on the Legion Go anymore. Setting a resolution is just ignored and it defaults to full 2560x1600.

**Comment by Shaunathanz** [comment]
> It is necessary to force a resolution for the scaling filters to work. For example, 1600x900 with the integrated screen option activated.
> <img alt="Image 1" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900089-4ffc5d2a-2a34-4ba1-92a7-3b8243658bea.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mzk1NTgsIm5iZiI6MTcyMTkzOTI1OCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMDg5LTRmZmM1ZDJhLTJhMzQtNGJhMS05MmE3LTNiODI0MzY1OGJlYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMjAyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNhMTFkMDg2MTA1ZjA4NzE1ODU5Y2M0MzVhOGE3ZmVhZDQ4MjY0ZDNlNjgwZmM5N2NmNDI3ZDZiNzI3MTcwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LuK73tmUffSak1YDSlDxGDMdMiQ0KCDK1WV8VDAshuo"> <img alt="Image 2" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900213-a5235b93-d1dd-4866-9594-cf28850ab12d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mzk1NTgsIm5iZiI6MTcyMTkzOTI1OCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMjEzLWE1MjM1YjkzLWQxZGQtNDg2Ni05NTk0LWNmMjg4NTBhYjEyZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMjAyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ExZTgzYjI5MDQ0MzFjNjE2Y2JhNjU2MjUyZmRlOGEwMmZmM2Y4MjQ1YmQzZmZkZDc2MzdkNzgxZDAwNzFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XhoVlYBaU9BOnvEDdTaLsYJk99RVPeQWvADcNhMjnso">

I appreciate the images, but in my case for the affected games I was already using that setting. The fact that I'm getting stretch scaling as the default has got me confused though, that's not even the default behavior. I have yet to roll back to 40.20240517.0 because of life things but it would be interesting if another Legion Go user with current issues could see if that build fixes it for them as well to confirm it's some kind of regression.

**Comment by ibanezbass** [comment]
> > It is necessary to force a resolution for the scaling filters to work. For example, 1600x900 with the integrated screen option activated.
> > <img alt="Image 1" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900089-4ffc5d2a-2a34-4ba1-92a7-3b8243658bea.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mzk1NTgsIm5iZiI6MTcyMTkzOTI1OCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMDg5LTRmZmM1ZDJhLTJhMzQtNGJhMS05MmE3LTNiODI0MzY1OGJlYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMjAyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNhMTFkMDg2MTA1ZjA4NzE1ODU5Y2M0MzVhOGE3ZmVhZDQ4MjY0ZDNlNjgwZmM5N2NmNDI3ZDZiNzI3MTcwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LuK73tmUffSak1YDSlDxGDMdMiQ0KCDK1WV8VDAshuo"> <img alt="Image 2" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900213-a5235b93-d1dd-4866-9594-cf28850ab12d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mzk1NTgsIm5iZiI6MTcyMTkzOTI1OCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMjEzLWE1MjM1YjkzLWQxZGQtNDg2Ni05NTk0LWNmMjg4NTBhYjEyZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMjAyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ExZTgzYjI5MDQ0MzFjNjE2Y2JhNjU2MjUyZmRlOGEwMmZmM2Y4MjQ1YmQzZmZkZDc2MzdkNzgxZDAwNzFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XhoVlYBaU9BOnvEDdTaLsYJk99RVPeQWvADcNhMjnso">
> 
> I appreciate the images, but in my case for the affected games I was already using that setting. The fact that I'm getting stretch scaling as the default has got me confused though, that's not even the default behavior. I have yet to roll back to 40.20240517.0 because of life things but it would be interesting if another Legion Go user with current issues could see if that build fixes it for them as well to confirm it's some kind of regression.

I don’t think you need to go back that far. 0627 worked, I believe. It stopped working for me when I went to one of the newer builds.

**Comment by Shaunathanz** [comment]
> > > It is necessary to force a resolution for the scaling filters to work. For example, 1600x900 with the integrated screen option activated.
> > > <img alt="Image 1" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900089-4ffc5d2a-2a34-4ba1-92a7-3b8243658bea.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mzk1NTgsIm5iZiI6MTcyMTkzOTI1OCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMDg5LTRmZmM1ZDJhLTJhMzQtNGJhMS05MmE3LTNiODI0MzY1OGJlYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMjAyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNhMTFkMDg2MTA1ZjA4NzE1ODU5Y2M0MzVhOGE3ZmVhZDQ4MjY0ZDNlNjgwZmM5N2NmNDI3ZDZiNzI3MTcwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LuK73tmUffSak1YDSlDxGDMdMiQ0KCDK1WV8VDAshuo"> <img alt="Image 2" width="300" src="https://private-user-images.githubusercontent.com/123477726/351900213-a5235b93-d1dd-4866-9594-cf28850ab12d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mzk1NTgsIm5iZiI6MTcyMTkzOTI1OCwicGF0aCI6Ii8xMjM0Nzc3MjYvMzUxOTAwMjEzLWE1MjM1YjkzLWQxZGQtNDg2Ni05NTk0LWNmMjg4NTBhYjEyZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMjAyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ExZTgzYjI5MDQ0MzFjNjE2Y2JhNjU2MjUyZmRlOGEwMmZmM2Y4MjQ1YmQzZmZkZDc2MzdkNzgxZDAwNzFhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XhoVlYBaU9BOnvEDdTaLsYJk99RVPeQWvADcNhMjnso">
> > 
> > I appreciate the images, but in my case for the affected games I was already using that setting. The fact that I'm getting stretch scaling as the default has got me confused though, that's not even the default behavior. I have yet to roll back to 40.20240517.0 because of life things but it would be interesting if another Legion Go user with current issues could see if that build fixes it for them as well to confirm it's some kind of regression.
> 
> I don’t think you need to go back that far. 0627 worked, I believe. It stopped working for me when I went to one of the newer builds. 

Good to know! 0517 was the build I was on before the recent update. I was going to check out 0627 but the cryptographic signature problem prevents that I guess. Already ran the script twice, once initially and then again to allow the fated recent update. Tried running the fix again to rebase but I guess it just doesn't work like that.

**Comment by Shaunathanz** [comment]
Looks like 40.20240725 fixed it (for me at least). 

Will re-open if something that did work is still broken

**Comment by ibanezbass** [comment]
This doesn't seem to be fully fixed. Yes FSR is working again, but I still can't set resolutions in the game properties.

**Comment by Shaunathanz** [comment]
> This doesn't seem to be fully fixed. Yes FSR is working again, but I still can't set resolutions in the game properties.

The only Sony game I have is Sackboy which I've had since it launched, and I've played it on both Steam Deck and the Legion Go. That particular game has never responded to the resolution settings in the Steam game options. Not sure if the other Sony games are different but Sackboy just does its own thing which Kyle mentioned above some games are just like that. 

If you had games working before that don't work now then I would definitely create an issue assuming it's a Bazzite issue and not a game update issue where they somehow broke something with gamescope. 

All I can say in my limited testing is that integer scaling is working for me in MHRise again which means the game resolution option, scaling, and filtering are working again.
