### ISSUE TITLE
Fwupd firmware updates fail to install; seems to expect EFI boot files to be present under "EFI/bazzite/" now

### ISSUE THREAD

**Issue by TheMCNerd2017** [ublue-os/bazzite#1400]
### Describe the bug

When attempting to install firmware updates through either KDE Discover or fwupdmgr through a terminal, it fails after downloading the update with the following error: "Secure boot is enabled, but shim isn't installed to EFI/bazzite/shimx64.efi". This issue did not come up the last time I updated system firmware through fwupd, which was around a month ago and before the name of the OS as it appears in GRUB changed (it used to display "Fedora 40" but recently changed to "Bazzite"). Additionally, all of the EFI boot files are present in the folders "fedora" and "BOOT" on the EFI partition, not under the "bazzite" folder that fwupd seems to want them present in now.

I'm unsure if this issue has been caused by the OS name change in the GRUB menu, or if the default location for EFI boot files has changed sometime between now and the last time I've updated firmware through fwupd. This issue blocks at the very least updating the BIOS/UEFI from within Bazzite.

### What did you expect to happen?

Firmware updates through fwupd to install and succeed without any issues.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:df25bf842c041b001f4fb237b788a3f7fd1e822aea9d5fc5b3cd990129e6e93c
                  Version: 40.20240723.0 (2024-07-23T21:17:03Z)
          LayeredPackages: edk2-ovmf qemu virt-manager
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"'

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:25eb70d16d0754c4dd902294e43579d413919508e72a31ee8862c0bf442a9485
                  Version: 40.20240717.0 (2024-07-17T17:42:01Z)
          LayeredPackages: edk2-ovmf qemu virt-manager
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"'
```

### Hardware

Device Model: Thinkpad P16 Gen 2
CPU: Intel i9-13950HX vPro
GPU: Nvidia RTX 5000 Ada Laptop GPU
RAM: 128GB DDR5 5600Mhz ECC

### Extra information or context

Tree output of the EFI partition:
```
/boot/efi/EFI
├── bazzite
│   └── fw
│       └── fwupd-e286e826-12ed-41fd-9417-2f47d31f4bcb.cap
├── BOOT
│   ├── BOOTIA32.EFI
│   ├── BOOTX64.EFI
│   ├── fbia32.efi
│   └── fbx64.efi
└── fedora
    ├── BOOTIA32.CSV
    ├── BOOTX64.CSV
    ├── fw
    ├── fwupdx64.efi
    ├── grub.cfg
    ├── grubia32.efi
    ├── grubx64.efi
    ├── mmia32.efi
    ├── mmx64.efi
    ├── shim.efi
    ├── shimia32.efi
    └── shimx64.efi

6 directories, 16 files

```

**Comment by KyleGospo** [comment]
Looking into this, in the meantime you can disable secure boot temporarily.

**Comment by KyleGospo** [comment]
This should be fixed in the latest testing build, if you could confirm I'd very much appreciate it.

**Comment by TheMCNerd2017** [comment]
> This should be fixed in the latest testing build, if you could confirm I'd very much appreciate it.

OK I'll rebase to the latest testing build and see if that fixes it.
