### ISSUE TITLE
Gamescope not loading and Steam not saving any data.

### ISSUE THREAD

**Issue by levi2m** [ublue-os/bazzite#1404]
### Describe the bug

Hello! First of all, amazing job on this OS! I'm running this in at least 3 machines now and I love it!

But, focusing on the bug, i've installed from scratch on my Desktop PC.
Since i've installed done all sorta things. Rebased, cleaned, installed another drivers and everything.

Steam does not keep my login information, every boot it asks to login again but my installed games show on the library as soon as i sign in.

I'm using BTRFS on the NVME that the OS is installed. Even tried switching the physical drive to another NVME but, not difference.

Even tried even the solutions on [this](https://github.com/ublue-os/bazzite/issues/724) issue that's looks almost the same.

But being completely honest, would love any help i can get from this because I'm more used to any debian-based distros. 

### What did you expect to happen?

Boot into GAMESCOPE, STEAM to save my login info not asking everytime it boots and to show my bluetooth and wifi properly (It only shows the wifi and in so damn slow).

### Output of `rpm-ostree status`

```shell
l2m@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:cc7561c968cbc410b8392950ce54784b03ee0abfbf9e4b4e84d1cfe3096486af
                  Version: 40.20240723.0 (2024-07-23T21:19:35Z)
            LocalPackages: lact-0.5.5-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:cc7561c968cbc410b8392950ce54784b03ee0abfbf9e4b4e84d1cfe3096486af
                  Version: 40.20240723.0 (2024-07-23T21:19:35Z)
```

### Hardware

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/122f6466-4ef6-4967-8ffb-5ed2f445ba85">

### Extra information or context

Installing from a Ventoy drive.
Secure Boot, UEFI, VT-D, Resizable BAR and XMP enabled on the bios.

**Comment by KyleGospo** [comment]
Steam not keeping login information is a side effect of steam clearing itself when crashing. The issue is the gamemode crash. Can you attach your gamescope logs here? They're present as hidden files in your home dir, and there should be two.

**Comment by levi2m** [comment]
thanks for the help @KyleGospo !

here are the files as you requested... 

[.gamescope-cmd.log](https://github.com/user-attachments/files/16370468/default.gamescope-cmd.log)
[.gamescope-stdout.log](https://github.com/user-attachments/files/16370470/default.gamescope-stdout.log)

im seeing that the system is mounted as read-only, is that normal? again, i'm really noob at fedora-based systems haha

**Comment by levi2m** [comment]
I've tried installing fedora 40 from universal blue's iso and rebasing to Bazzite Deck and Bazzite Deck Gnome versions (tested separately). Still the same error i'm facing. 

The GPU and CPU combo works just fine with all enabled on the bios on Win11 and PopOS!.
The SecureBoot, TPM and UEFI are all enabled on all those tests.

**Comment by HikariKnight** [comment]
> I've tried installing fedora 40 from universal blue's iso and rebasing to Bazzite Deck and Bazzite Deck Gnome versions (tested separately). Still the same error i'm facing.
> 
> The GPU and CPU combo works just fine with all enabled on the bios on Win11 and PopOS!. The SecureBoot, TPM and UEFI are all enabled on all those tests.

hey @levi2m try the newest update from yesterday and onwards, it have fixed the Polaris (RX 400 and 500 series) card kerfuffle we have had the past days (Polaris cards require a different gamescope version than all other cards and the check for polaris card have been iffy until now due to the many variants of that card).

You will have to log into steam again but it shouldnt crash now meaning it will not clear the login details.

**Comment by levi2m** [comment]
that really solved the issue
thanks for all the help and good work everyone! 
this is a hell of a OS!!
