### ISSUE TITLE
SD OLED Installation Black Screen

### ISSUE THREAD

**Issue by bmfkai** [ublue-os/bazzite#1405]
Not sure how to capture a log for this but during install on Steam Deck OLED (2tb ssd upgrade) I can get to select Basic Graphics mode to begin installation but then it just goes to a black screen and sits there indefinitely.  The touchpads sound like they're working but there's nothing on the screen.  If I press power I can see it start to get to a prompt but then that too disappears. 

If I try to install normally I can get to the first install screen but of course on OLED it's the wrong resolution and I only see the top left area of the screen.

Any ideas? 

Edit: using deck-gnome
Edit: also just tried the kde image, same result

**Comment by MonXBZH** [comment]
I had to reinstall SteamOS after my screen goes black after an update on BazziteOS (KDE).

And now, same behaviour: black screen after the installer loaded. Installer appears when using the default installer entry not the basic graphic mode entry.

Using SD OLED 512Go.

**Comment by bmfkai** [comment]
I held off installing Bazzite until it was a little more stable for SDOLED but for more context I also tried various hardware configurations: official dock, aftermarket dock, different keyboards and cables, with and without a mouse, and various flash drives.  I did notice that I was able to drop to different terminals (cmd+alt+f1 f2 etc) and then get back to the install screen with cmd+alt+f6 but after getting back to the install screen this way, the keyboard and mouse were not visible.  Such that even hitting tab did not show me which section of the install screen I was highlighting until I dropped to the terminal then got back to the install screen.  Very strange... I could probably get through the install this way but it would be difficult and risky.  I also noticed, when giving up on the Bazzite install and booting back into SteamOS, when going into desktop mode the screen displayed a bunch of random vertical lines, filling up the screen, until I put the deck into sleep mode and then bring it back up.  After that I've had no issues using SteamOS.

**Comment by jccpalmer** [comment]
I'm having this issue, too. Fresh 2TB SSD, SD OLED. Like said above, I can drop into a terminal from the black screen, then get to the installer. But, there's no recognized mouse or keyboard input unless I hope back into a terminal.

Booted from Ventoy in grub2 mode, then Basic Graphics Mode. I'll try a USB on its own, but I'm not hopeful.

**Comment by Vykori** [comment]
I am seeing the same behavior. Steam deck oled, 512gb. I was able to install on the regular graphics mode, and therefore only seeing the top left of the screen, and using tab to select off-screen buttons. Plugging in an external screen lets you see a little more.
![photo_2024-08-05_01-34-17](https://github.com/user-attachments/assets/674f2d85-c6b7-4630-8d66-5724db0c2503)

**Comment by KyleGospo** [comment]
Fixed in newest ISO, also has Bazzite branding and a default username and password, eliminating the need for a keyboard (Though still highly recommended)

**Comment by KyleGospo** [comment]
![c439ac224f093144.png](https://github.com/user-attachments/assets/2830e130-4d85-45d3-81b4-f9ad72f9298a)

**Comment by valiksheva** [comment]
I'm having this problem with fresh BazziteOS installer on the OLED. 
Basic graphics mode just goes to completely black screen, and regular installer has wrong resolution
