### ISSUE TITLE
screen becomes blurred and indistinct in the Gamescope 

### ISSUE THREAD

**Issue by bairain** [ublue-os/bazzite#1406]
### Describe the bug

After reboot the computer I meet the problem that my screen becomes blurred and indistinct like the below picture.But if I move my mouse,the screen becomes normal. However when I use my controller to switch,the screen still like this.
And sometimes when I switch to desktop mode,the screen is white, with chromatic aberrations.
![WechatIMG175](https://github.com/user-attachments/assets/83b08805-e765-4f18-a1e0-0b4c95df120f)

### What did you expect to happen?

I want this problem will be sloved.

### Output of `rpm-ostree status`

```shell
State: busy
Transaction: upgrade
  Initiator: client(id:cli dbus:1.227 unit:run-r6a798f51b6df47e8a5d2058559402c45.scope uid:1000)
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:82624ab8dc34f83515f74cdaa160683f342cc62b8dd2d485fa2d465385ec5fab
                  Version: 40.20240717.0 (2024-07-17T17:10:50Z)
          LayeredPackages: nss-tools

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:9dd5cf961270659215f5a20a2884eef5ce4d7c203bac4de1125cbc32aa34c6fe
                  Version: 40.20240716.0 (2024-07-16T04:58:03Z)
          LayeredPackages: nss-tools
```

### Hardware

AMD R7-5700X
AMD RX7700XT
B550I
32G RAM

**Comment by KyleGospo** [comment]
This is an issue with HDR in GameScope, I would make sure that HDR is enabled both in your monitor and in GameScope. If you still can't get it to work, try making sure both are off.
