### ISSUE TITLE
Network Manager wireguard through gnome settings not working

### ISSUE THREAD

**Issue by tenroc** [ublue-os/bazzite#1408]
### Describe the bug

On the latest bazzite-gnome image, connecting to a wireguard vpn (added through the gnome-settings network panel)  with the quick setting toggle, or nmcli does not work. It appears as connected (VPN icon in the top panel and nmcli outputing  "Connexion activée (chemin D-Bus actif : /org/freedesktop/NetworkManager/ActiveConnection/4)", but IP adress doesn't change and I can't access machines on the VPN local network.

The wireguard config file was tested on an Open Suse Aeon desktop and confirmed as working.

### What did you expect to happen?

Toggling the VPN quicksetting should work and activate the VPN connexion.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:5abde64dd36018de28390cede26c68100c62e5f51eb5e3464f6cdc859ff56cbf
                  Version: 40.20240725.0 (2024-07-25T06:52:51Z)
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:5abde64dd36018de28390cede26c68100c62e5f51eb5e3464f6cdc859ff56cbf
                  Version: 40.20240725.0 (2024-07-25T06:52:51Z)
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:c56260e4daf9eb85397c7bbd739a54ea98d585575041a82cb99c38961d6920f6
                  Version: 40.20240723.0 (2024-07-23T21:13:32Z)
            LocalPackages: lact-libadwaita-0.5.4-0.x86_64
```

### Hardware

Thinkpad T495, with a ryzen 5

**Comment by tenroc** [comment]
The same config file is working when using the appimage here: https://github.com/leon3s/wireguard-gui?tab=readme-ov-file , on the latest bazzite-gnome image, but not when connecting through network-manager

**Comment by bazzite-fan** [comment]
Wireguard works in latest Bazzite KDE.
Use System Settings, WiFi & Networking, [+] Add new connection, Import VPN Connection from file *.conf
