### ISSUE TITLE
Steam deck OLED Locking CPU to 3500 mhz

### ISSUE THREAD

**Issue by thidguy** [ublue-os/bazzite#1413]
### Describe the bug

Im using an overclocked bios and powertools if that matters anyway I noticed that the steam deck OLED was getting rlly hot for some reason even when running nothing and downloading nothing and I checked the overlay and it's running at 3500 mhz and I have to use powertools to slow it down so it doesn't get uncomfortably hot to the touch also I use fantastic to crank up the fan because it just doesn't go faster when it gets this hot also the screen has a greenish light on the left hand side when I have an all black screen on maybe unrelated idk

### What did you expect to happen?

I expected the CPU clocks to be a little bit more dynamic or at least the fan to ramp up to take control of the 65 degree Celsius 

### Output of `rpm-ostree status`

```shell
thid@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:672441d77dd40c6bf4f8282327b1202e4c25b082b6c404015166d602e3f9256d
                  Version: 40.20240726.0 (2024-07-26T22:44:59Z)
          LayeredPackages: 'dnf-command(config-manager)' build containerd.io
                           dnf-plugins-core docker-buildx-plugin docker-ce docker-ce-cli
                           docker-compose-plugin gnome-terminal
            LocalPackages: docker-desktop-4.32.0-157355.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:9003c4e2f42c26a1a61db30b7acc2fae038b4f479712f146132c231ce2459ca6
                  Version: 40.20240726.0 (2024-07-26T19:04:04Z)
          LayeredPackages: 'dnf-command(config-manager)' build containerd.io
                           dnf-plugins-core docker-buildx-plugin docker-ce docker-ce-cli
                           docker-compose-plugin gnome-terminal
            LocalPackages: docker-desktop-4.32.0-157355.x86_64
```

**Comment by thidguy** [comment]
Ok so after doing a little more testing I found out that it just locks it on the main menu screen

**Comment by thidguy** [comment]
> I also have this on bazzite, try #1374 version.

So do I just update or what do I do with this

**Comment by KyleGospo** [comment]
I am only able to reproduce this in gaming mode. Games scale frequency exactly as you would expect

**Comment by KyleGospo** [comment]
65° is also extremely cold for a deck, they don't even thermal throttle until 100°. I don't think you need to be worried about custom fan curves or any other stuff you're doing

**Comment by KyleGospo** [comment]
65° is also extremely cold for a deck, they don't even thermal throttle until 100°. I don't think you need to be worried about custom fan curves or any other stuff you're doing

**Comment by thidguy** [comment]
> I am only able to reproduce this in gaming mode. Games scale frequency exactly as you would expect

It's on the home menu where the clocks are maxed out
