### ISSUE TITLE
bazzite-nvidia:testting - "‘/usr/lib/ostree-boot/efi/EFI/bazzite/’: No such file or directory" when trying to use fix double ostree entry script

### ISSUE THREAD

**Issue by Ascent7910** [ublue-os/bazzite#1414]
### Describe the bug

When trying to use the "Fix double ostree entry" part of the `ujust configure-script` I get this error

```
find: ‘/usr/lib/ostree-boot/efi/EFI/bazzite/’: No such file or directory
install: missing destination file operand after '/boot/efi/EFI/bazzite/'
Try 'install --help' for more information.
Generating grub configuration file ...
Found Windows Boot Manager on /dev/nvme1n1p1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for UEFI Firmware Settings ...
done
```

### What did you expect to happen?

The result of the script is to change some grub settings and regenerate the grub config for it to take effect

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:testing
                   Digest: sha256:4f2f129c3ff0143eb8109e38cd0d7e45478480bb4c1bfd2409c7ea461e16bac0
                  Version: 40.20240726.0 (2024-07-26T22:39:31Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:f0fb18337a7563f438ba3fa3b81f3dfaaea1ed0bcba4feace42d040f8a9a4cc0
                  Version: 40.20240726.0 (2024-07-26T22:44:53Z)
```

### Hardware

CPU - Intel(R) Core(TM) i5-14600K (20) @ 5.30 GHz
GPU - NVIDIA GeForce RTX 4070 SUPER [Discrete]
32Gb RAM

### Extra information or context

#1400 I saw this issue mentioned that looked a bit similar to mine in terms of EFI stuff

**Comment by KyleGospo** [comment]
Should be fixed in the latest release

**Comment by Ascent7910** [comment]
With the new release this has fixed my issue and removed my double entries thank you.
