### ISSUE TITLE
Can't reinstall again

### ISSUE THREAD

**Issue by sh4d1t0** [ublue-os/bazzite#1422]
I deleted the partitions in Windows a long time ago, now I want to try it again, but when I install it and put the partitions it tells me that it cannot be created if I put the mount points (/boot/efi or /boot). I tried to create the partitions manually but it tells me when I put the mount points that it is not possible, as before, and the installation ends, and restarts it.

hardware: Asus rog ally z1 extreme

Edit: I was read the problem is with blivet but I cannot find a solution

![image](https://github.com/user-attachments/assets/6844eed9-62ca-49d9-96f0-7cdee83c3890)

**Comment by antheas** [comment]
It is with blivet

Follow one of the many dual boot guides because unless you do exactly as they say, the installer will complain

**Comment by sh4d1t0** [comment]
> Follow one of the many dual boot guides because unless you do exactly as they say, the installer will complain

I do it exactly like in the youtube video that is in the guide, how to do it both in rog ally and legion go. But it doesn't work, I'm just at the step of assigning the 300MiB unit.

**Comment by sh4d1t0** [comment]
I used this solution in a fedora fedora forum:

-I used the KDE Partition Editor to create a blank 600MB partition and a 1024MB partition and left space for the btrfs. Then I used Custom Advanced (Blivet-GUI) to format them, add mount points (/boot/efi for the 600MB one and /boot for the 1024MB) and create the btrfs volume (and 2 subvolumes, root and home). Then Fedora finally installed without a problem.

And now I have bazzite os again in my new nvme

**Comment by sh4d1t0** [comment]
Noooooo I have a lot of problems if I use this method, I can't change between desktop and gaming mode, my old controller name is there... I don't know what's happening, I'm tired.

I don't have solution

**Comment by HikariKnight** [comment]
> Noooooo I have a lot of problems if I use this method, I can't change between desktop and gaming mode, my old controller name is there... I don't know what's happening, I'm tired.
> 
> I don't have solution

Can you try the newest update?
idk about your old controller name though

**Comment by sh4d1t0** [comment]
> > Noooooo I have a lot of problems if I use this method, I can't change between desktop and gaming mode, my old controller name is there... I don't know what's happening, I'm tired.
> 
> > 
> 
> > I don't have solution
> 
> 
> 
> Can you try the newest update?
> 
> idk about your old controller name though

Yes I used the 3.6.0 version

Sorry I mean my old Xbox controller name is there yet. If it's a new installation, isn't it supposed to be the name of the xbox controller by default?

**Comment by HikariKnight** [comment]
> > > Noooooo I have a lot of problems if I use this method, I can't change between desktop and gaming mode, my old controller name is there... I don't know what's happening, I'm tired.
> > 
> > 
> > > 
> > 
> > 
> > > I don't have solution
> > 
> > 
> > Can you try the newest update?
> > idk about your old controller name though
> 
> Yes I used the 3.6.0 version
> 
> Sorry I mean my old Xbox controller name is there yet. If it's a new installation, isn't it supposed to be the name of the xbox controller by default?

HHD emulates a controller of your choice in order for the ally controls to work, might be that one you are seeing?
Double/tripple press the button that brings up the right side menu and you can choose what controller it emulates.

**Comment by sh4d1t0** [comment]
> > > > Noooooo I have a lot of problems if I use this method, I can't change between desktop and gaming mode, my old controller name is there... I don't know what's happening, I'm tired.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I don't have solution
> 
> > > 
> 
> > > 
> 
> > > Can you try the newest update?
> 
> > > idk about your old controller name though
> 
> > 
> 
> > Yes I used the 3.6.0 version
> 
> > 
> 
> > Sorry I mean my old Xbox controller name is there yet. If it's a new installation, isn't it supposed to be the name of the xbox controller by default?
> 
> 
> 
> HHD emulates a controller of your choice in order for the ally controls to work, might be that one you are seeing?
> 
> Double/tripple press the button that brings up the right side menu and you can choose what controller it emulates.
> 
> 
> 
> PS: also when i said to try the newest update i meant to try update bazzite since we have pushed updates since 3.6.0 got released (the iso downloads will regularly get updated so they are not far behind if at all)

Oh yes the system is updated, but I have issues with the buttons sometimes the menus doesn't appear and yes I selected Xbox controller in rog ally, I put the name in controller settings on steam "Rog ally". After clean install using the method that I found in fedora forums that name in steam settings is still there yet "Rog ally".

Maybe something is Brocken in my partitions. How can I clean my nvme? And then restore in asus cloud and try a fresh install like the first time without issues. Because if I tried installing in bazzite menu I always have the same message "failed to add the device: unable to allocated requested partition scheme"

**Comment by HikariKnight** [comment]
> > > > > Noooooo I have a lot of problems if I use this method, I can't change between desktop and gaming mode, my old controller name is there... I don't know what's happening, I'm tired.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > I don't have solution
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Can you try the newest update?
> > 
> > 
> > > > idk about your old controller name though
> > 
> > 
> > > 
> > 
> > 
> > > Yes I used the 3.6.0 version
> > 
> > 
> > > 
> > 
> > 
> > > Sorry I mean my old Xbox controller name is there yet. If it's a new installation, isn't it supposed to be the name of the xbox controller by default?
> > 
> > 
> > HHD emulates a controller of your choice in order for the ally controls to work, might be that one you are seeing?
> > Double/tripple press the button that brings up the right side menu and you can choose what controller it emulates.
> > PS: also when i said to try the newest update i meant to try update bazzite since we have pushed updates since 3.6.0 got released (the iso downloads will regularly get updated so they are not far behind if at all)
> 
> Oh yes the system is updated, but I have issues with the buttons sometimes the menus doesn't appear and yes I selected Xbox controller in rog ally, I put the name in controller settings on steam "Rog ally". After clean install using the method that I found in fedora forums that name in steam settings is still there yet "Rog ally".
> 
> Maybe something is Brocken in my partitions. How can I clean my nvme? And then restore in asus cloud and try a fresh install like the first time without issues. Because if I tried installing in bazzite menu I always have the same message "failed to add the device: unable to allocated requested partition scheme"

i believe steam saves those names into your account online and associate them with the controllers you got by serial or something.
but that is a guess on my end, i do not work for valve.
