### ISSUE TITLE
Ujust Update failing after update from today

### ISSUE THREAD

**Issue by mortalglitch** [ublue-os/bazzite#1423]
### Describe the bug

During Ujust update it gets to the portion for updating brew then fails with a panic.

> ── 16:13:08 - Brew ─────────────────────────────────────────────────────────────
```
==> Updating Homebrew...
Already up-to-date.
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
The application panicked (crashed).
Message:  the output of `waydroid status` should contain `Session:`
Location: src/steps/os/linux.rs:1056
error: Recipe `update` failed with exit code 101
```

### What did you expect to happen?

Standard Update Flow.

### Output of `rpm-ostree status`

```shell
rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                   Digest: sha256:f6300eb5fcaeb5da88427692811c82929b7e2de03c86da129286b696cc54b21c
                  Version: 40.20240728.0 (2024-07-28T16:40:19Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                   Digest: sha256:5aa917ab0e0af2baf7ab41badd409065954407c7e97ccc2e30b775c1c27b5854
                  Version: 40.20240725.0 (2024-07-25T21:37:13Z)
```

### Hardware

Desktop Nvidia
AMD Ryzen 9 7950X (32) @ 5.88 GHz
NVIDIA GeForce RTX 4090 [Discrete]
64gb ram
dedicated harddrive 2TB
Multi-Monitor (currently 2)

### Extra information or context

First discovered in a VM when building/testing locally. 
Switched back to my full machine and was able to update once normally, but upon running ujust update I ran into the waydroid check panic.
When attempt to run the update from the application drawer the app seems to immediately crash.

I have never tried running or initializing Waydroid on this system previously.

**Comment by castrojo** [comment]
Looks like this might be it: https://github.com/topgrade-rs/topgrade/issues/869

**Comment by KyleGospo** [comment]
This will be fixed next update, your system is still updating as normal thanks to rpm-ostree being run first.

**Comment by mortalglitch** [comment]
@castrojo good call out that seems to be exactly what I am seeing.
@KyleGospo thank you for the reassurance. The reboot did indeed take me from OSBUILD C2DBFED to 22062C6. I was under the impression that the staging occurred later in the process.

**Comment by KyleGospo** [comment]
Fixed in latest
