### ISSUE TITLE
ACPI Bios Error，media check fail

### ISSUE THREAD

**Issue by samuelwang456** [ublue-os/bazzite#1426]
Recently I had this problem when installing bazzite on legion go，I have tried several times to download the ISO file and burn it to a USB flash drive with balenaEtcher，But the interface still appears.
I can press ESC to skip the check and install bazzite smoothly, and I can get into the system，But I've been having problems with my fan customization, it doesn't work as I set it up,I looked up a lot of information, ACPI seems to be related to the power supply，I think it may be the fan is not functioning properly willing.

My bios version is v29
I replaced a 2242 drive myself（That might not matter. I don't know...）

I tried single boot and dual boot with the same result，Now, I'm totally out of ideas
![IMG_2060](https://github.com/user-attachments/assets/acdb980e-f2dd-4642-9ffa-b4bcc819c34d)

**Comment by antheas** [comment]
Hi sam,

The ACPI error is normal. 

The media check probably means Windows didn't finish writing the ISO to your drive. You need to eject USB devices before you remove them from your computer

Your bios is too old to control the fan curves on the Legion go

The fan barely works properly as it is and now that it's summer at least in my experience will get stuck at full speed

**Comment by HikariKnight** [comment]
Antheas covered everything.

For the fan curves  you will have to update the bios through windows (unless lenovo provides a method to update it from an usb, i havent checked if they do that though)
