### ISSUE TITLE
Wake from Sleep Black Screen ROG ALLY

### ISSUE THREAD

**Issue by SuperSirLink** [ublue-os/bazzite#1429]
### Describe the bug

When waking from sleep, with the option to have the Steam Customization video play on wake, you get left with a black screen.  You can hear the steam UI sounds as you provide controller input.  

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

**Comment by KyleGospo** [comment]
This is an old steam bug, I'm afraid we can't fix it. I would recommend turning off the startup video for now.

**Comment by SuperSirLink** [comment]
ahh okay, I just wanted to share as I never experienced that on Nobara, so I assumed it was specific to Bazzite.
