### ISSUE TITLE
Why is my custom fan curve not working

### ISSUE THREAD

**Issue by samuelwang456** [ublue-os/bazzite#1430]
Here’s how I do it：

I installed bazzite following the instructions in a YouTube video
I installed decky loader in desktop mode
Then I installed the hhd decky plugin
I set up a custom fan curve in HHD（TDP is also custom）
But when I played the game, the fan didn’t work as I set it, its speed was low, and even though the CPU temperature was gradually rising, it didn’t increase the speed，It’s like a constant speed. I had to turn off the custom fan or the CPU would overheat.

I don’t know why this is, does anyone know what else I need to install to make it work?

**Comment by samuelwang456** [comment]
legion go，bios v29

**Comment by KyleGospo** [comment]
V29 is the issue, update to v29.1 and you should be good.

**Comment by samuelwang456** [comment]
> v29 is the issue, update to v29.1 and you should be good.
> 
> Also you can uninstall the HHD decky plugin, it's completely unneeded. Double tap Legion R instead.

Thank you for your reply，I tried the V32 version of bios with the same results.
