### ISSUE TITLE
ujust update fails with helix present

### ISSUE THREAD

**Issue by sbaue** [ublue-os/bazzite#1431]
### Describe the bug

Helix editor installed by homebrew or distrobox triggers topgrade to update "grammers" for this editor, this fails in the build stage with a json error due to ld not being found.

### What did you expect to happen?

Just a system update I guess.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:aa5040109801b0e6415726d077ffdbad0a125d1586e52d7413a2d45c7f9ddc2b
                  Version: 40.20240730.0 (2024-07-30T04:56:36Z)
                     Diff: 30 upgraded, 18 removed, 26 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:b09bdbe28651253e313cc458a98e9f4a02f68848ecf235062f55c0e1be3b5fdf
                  Version: 40.20240728.0 (2024-07-28T22:28:22Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:f0fb18337a7563f438ba3fa3b81f3dfaaea1ed0bcba4feace42d040f8a9a4cc0
                  Version: 40.20240726.0 (2024-07-26T22:44:53Z)
```

### Hardware

I don't think hardware is relevant here, just a HP Elitdesk with a AMD chip.

### Extra information or context

[ujust-fail.txt](https://github.com/user-attachments/files/16425683/ujust-fail.txt)

**Comment by sbaue** [comment]
Also fails when helix is in at least some distroboxes, it just gets detected by topgrade and some update atempt is made. Attached is the error with helix present in a alpine distrobox on the system.
[ujust-fail_alpine.txt](https://github.com/user-attachments/files/16425799/ujust-fail_alpine.txt)

**Comment by sbaue** [comment]
Thanks to discord I figured out how to disable the helix update part of topgrade. The file for that is /etc/ublue-os/topgrade.toml.

**Comment by HikariKnight** [comment]
for those curious coming from web search engines, i believe you add
```ini
[misc]
disable = ["helix"]
```

to `/etc/ublue-os/topgrade.toml`
