### ISSUE TITLE
DeckHQ screen orientation

### ISSUE THREAD

**Issue by marc0der** [ublue-os/bazzite#1433]
### Describe the bug

I installed Bazzite on my Steam Deck, which was modified with a DeckHQ screen. When I boot up in the deck image, the installer boots up in portrait mode, 90 degrees anticlockwise (footer on the right). After completing the installation, KDE boots with this same misconfiguration.

### What did you expect to happen?

I'd expect the installer and the installation to be in landscape mode, not like this:

![PXL_20240725_225247908 MP](https://github.com/user-attachments/assets/19e36ebb-288d-4fbf-a55a-42d1b227f0af)

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:12d9af08ffa86b928c7e3f2435fe639bbe14ff0e75cfac6343419c931cdb0fe6
                  Version: 40.20240728.0 (2024-07-28T21:46:28Z)
          LayeredPackages: htop ncdu

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f4e22243c01f2d2c7448223ed1a81c4671a2a8bcadd6573f959f03044613d6dd
                  Version: 40.20240728.0 (2024-07-28T20:11:49Z)
          LayeredPackages: htop ncdu
```

### Hardware

`Jupiter`

### Extra information or context

I'm now in the state where the boot screen starts up in portrait mode, but I've changed my screen orientation in KDE (which carries through to Steam) to correct the problem. Is there a way to change the screen orientation during the boot process so that I don't need to make the correction in KDE?

Thanks for Bazzite, and keep up the great work!

**Comment by RodoMa92** [comment]
Thanks for reminding me of this. I'll post the command to rotate the panel by default shortly, but I'll also push a patch upstream to also include DeckHD as a rotated panel by default, so no command will be needed once merged.

**Comment by marc0der** [comment]
Great stuff, I look forward to that command to set things right.

**Comment by RodoMa92** [comment]
Patch is here: https://patchwork.freedesktop.org/patch/606792/?series=136749&rev=5

I'll get the command to you shortly.

**Comment by RodoMa92** [comment]
Completely forgpt about this, sorry.

Here it is: `sudo rpm-ostree kargs --append-if-missing=video=eDP-1:panel_orientation=right_side_up`

**Comment by marc0der** [comment]
Great, thanks for getting back to me on this 🙏
