### ISSUE TITLE
Legion go controller issue

### ISSUE THREAD

**Issue by tonixwang1997** [ublue-os/bazzite#1435]
### Describe the bug

When I detach only one side of the controller, both of them will be treated as indicidual controllers,like when you split Nintendo switch controller and play them horizontally, which means joystick and button layout will be rotated. And again, this happens only when I detach one controller and leave the other one on the body.

### What did you expect to happen?

I would expect them still work together as a full controller. Or maybe even can be setup by users.

**Comment by KyleGospo** [comment]
@antheas

**Comment by antheas** [comment]
Yes I do not like it either.

It is a firmware "feature" by Lenovo. It cannot be disabled or worked around.

I would direct you to the legion go forums.
