### ISSUE TITLE
Feature request: ZFS support

### ISSUE THREAD

**Issue by MininuxDev** [ublue-os/bazzite#1438]
### Describe the package

Hi
ZFS is awesome as a filesystem, but it needs an out of tree kernel module. I saw that [bluefin](https://github.com/ublue-os/bluefin/issues/1283) managed to add it although they had to change the kernel to ucore's one. I know bazzite uses another custom kernel, still, would it be possible on bazzite ?

And thanks for the work on this project!

### Image

Desktop

**Comment by KyleGospo** [comment]
Unfortunately bluefin only supports it because they are using a slower cadence kernel. I'm afraid we can't support it here.

**Comment by MininuxDev** [comment]
Ah i see, that's unfortunate. I'm probably missing something, but shouldn't building a zfs kmod against the right kernel version in the containerfile work ? I'd like to try that once i understand how blue-build work

**Comment by elyashivhazan** [comment]
bazzite now [moved to a slower kernel releases](https://universal-blue.discourse.group/t/bazzite-3-7-0-update-released/3726#p-8917-gated-kernel-version-lenovo-legion-go-issues-fixed-7)

will zfs be considered again? or its still to fast for a supporting zfs?

**Comment by KyleGospo** [comment]
Temporarily, while 6.10 is broken. We will not be considering it.

**Comment by elyashivhazan** [comment]
oh as its written i thought it will be slower release to make sure issues like that will happen again.
thanks.

**Comment by shymega** [comment]
Just curious, but would it be possible for end-users to inject ZFS into their own Bazzite `Containerfile`, and lock the kernel+ZFS version with `rpm-ostree`?

I'm fairly comfortable with kernel modules and packaging, but I'd only be maintaining it for my own use-case. Given Bazzite doesn't intend to support ZFS, I would not be asking for help on the Bazzite channel.

I'll have a look and see how Bluefin does it though.

**Comment by jim-taylor-business** [comment]
hi i found this while invewstigating zfs on bazzite

https://github.com/coreos/layering-examples/blob/main/build-zfs-module/Containerfile

would this approach make it easier?

**Comment by shymega** [comment]
@jim-taylor-business That post is mine.

**Comment by shymega** [comment]
As for my Bazzite image, I've been experimenting with adding ZFS as an akmod, but I've now run into a conflict with libvirt and `zfs-fuse`, which makes installing the akmod impossible.

**Comment by tulilirockz** [comment]
Oh hello input-leap maintainer! I believe we have ZFS support on Bluefin:stable if you can use that instead.

cc @shymega

**Comment by shymega** [comment]
> Oh hello input-leap maintainer! I believe we have ZFS support on Bluefin:stable if you can use that instead.
> 
> It should be absolutely possible to pin the kernel and add ZFS directly to your builds tho, check out how [bluefin](https://github.com/ublue-os/bluefin/blob/35f83857f073bca6f0a2c4f7e6c737d69ffee55a/build_files/base/03-install-kernel-akmods.sh#L70) does it. (its literally what you want to do)
> 
> cc [@shymega](https://github.com/shymega)

I have attempted this, but I'm trying to add it as a 'Containerfile' with blue-build.

So far I'm running into the `zfs` and `zfs-fuse` conflict.

**Comment by saolof** [comment]
If you are running Bazzite, the machine probably isn't a server with a business depending on it and it's probably just to try out cool filesystems. In that case you might be interested in bcachefs which is in-tree and which will likely be a very solid competitor to ZFS and btrfs long term.

It is not nearly as versatile or mature as ZFS at this point though, and it won't give you ZFS homelabbing experience if that's what you are after, and I would also love to have ZFS in bazzite.

**Comment by shymega** [comment]
ZFS isn't necessarily for servers. I use it on all of my main machines, and the reason I want to use ZFS on Bazzite is so I can share the pool with my games stored on without having to split out my SSD into two partitions - ZFS and bcachefs/btrfs.

ZFS is still a valid filesystem request, and it would be good to have this issue re-opened for further investigation. Even if ZFS support is just a feature-flag, and with no promise of upstream builds.

**Comment by shymega** [comment]
I haven't had luck with my attempts to add ZFS to a Bazzite image based on another repo.

Has anyone else succeeded in adding ZFS to Bazzite? Ideally I want to add Bazzite to my _existing_ ZFS pool.

**Comment by castrojo** [comment]
Ah, another ZFS on the desktop fan, my people! It's probably going to be unfeasible for anyone to be able to reliably track this as you'd need to track zfs development branches, etc. Maybe if a few people did it together. 

However Aurora and Bluefin support ZFS because we use older, but still modern kernels. I think a custom image using a kernel swap following one of our akmods releases might do the trick? You'd lose the bazzite kernel features but most of that stuff is barely measurable. 

cc @m2Giles @bsherman

**Comment by shymega** [comment]
Yeah, I use ZFS as a zpool on my first SSD in my laptop for OSes. The
second zpool is for 'data', including Games.

I have tried to integrate ZFS into my custom build of Bazzite, but it
doesn't seem to build yet - https://github.com/shymega/shyBazzite.

Do you have any examples on kernel swaps? I'm using blue-build.

If I could install Bazzite into the OS zpool, with a separate `/boot`
(due to ZFS) for the ESP, I could work with that.

Maybe we could use some kind of CI workflow to track ZFS releases with
Bazzite kernels, and set a 'flag' if it builds, and if it doesn't, then
we just don't ship ZFS? Not sure. I'm happy to just build it in my fork
tbh.

On 14.06.2025 16:47, Jorge O. Castro wrote:
>castrojo left a comment (ublue-os/bazzite#1438)
>
>Ah, another ZFS on the desktop fan, my people! It's probably going to be unfeasible for anyone to be able to reliably track this as you'd need to track zfs development branches, etc. Maybe if a few people did it together.
>
>However Aurora and Bluefin support ZFS because we use older, but still modern kernels. I think a custom image using a kernel swap following one of our akmods releases might do the trick? You'd lose the bazzite kernel features but most of that stuff is barely measurable.
>
>cc @m2Giles @bsherman
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ublue-os/bazzite/issues/1438#issuecomment-2973360370
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
Best wishes,
--
Dom Rodriguez

**Comment by m2Giles** [comment]
Biggest issue is the Bazzite kernel moves pretty darn fast. You could theoretically hold back the kernel by swapping to an older version that zfs supports.

But we do not build the zfs kmod for older Bazzite releases.

You will need to do that and sign it (or don't use secureboot)

/boot on zfs is not supported out of the box and we do have rollback capabilities from ostree.

zfs on root I couldn't get to install originally. I do not know if zfs on /var could work

**Comment by shymega** [comment]
Yeah. Well, if anyone has pointers on how to setup a fork of the Containerfiles for using ZFS/older kernels, please do let me know!

Can we re-open this issue in the meantime?

**Comment by chklauser** [comment]
Hey @shymega, the [openzfs docs for fedora](https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora/index.html) state that `zfs-fuse` should be uninstalled:

I have [tried that](https://github.com/chklauser/bazzfsite/pull/1/files#diff-35e887fac48d0b0b860d8ae497b4e7fb1029f311d1f58d8f87b37114f497dbc2), but then we [run into](https://github.com/chklauser/bazzfsite/actions/runs/16581221080/job/46897519945#step:7:198) a conflict between the packages for the "bazzite" version of the kernel and the default version of the kernel:
```
cannot install both kernel-core-6.15.6-200.fc42.x86_64 from @commandline and kernel-core-6.15.6-105.bazzite.fc42.x86_64 from @System
```

If the [ublue-os/akmods](https://github.com/ublue-os/akmods) repository built the zfs akmods in a bazzite variant, we might get further. It is not clear to me why the ZFS is not built for "desktop" distributions like bazzite. ZFS works fine on desktop computers and is amazing to work with. For me, it would be fine if that build failed for a couple of weeks while the OpenZFS and fedora teams prepare to support a new kernel. 

 I haven't investigated, whether it would be reasonably possible to fork ublue-os/akmods (I'm specifically worried about signing keys).

**Comment by castrojo** [comment]
> ZFS works fine on desktop computers and is amazing to work with.

No one is arguing against that, as we've explained the kernel in bazzite moves to quickly to guarantee ZFS support - Aurora and Bluefin support it if ZFS is important to you.

**Comment by ruzko** [comment]
Sorry for necro-bumping, but I'm kinda stuck.

My combined desktop+server was on Bazzite-nvidia-43-stable until a few days ago, and relied on zfs for kubernetes storage. It has worked fine since ~february, when I rebased from fedora kinoite.
I rebased to Bazzite-nvidia-44-stable last week (primarily for security updates), and now the zfs kernel modules won't load anymore. I upgraded the zfs repo to fc.44, but the installed zfs package is stuck on fc.43. I can't find zfs kmod in the ublue-os/akmods copr repo.
My system has an nvidia gtx1070 gpu, which is older than what Aurora supports. The system runs various GPU workloads, so it can't use noveau.

I understand this is a situation of my own making, but I hope there's a path forward for me.

**Comment by m2Giles** [comment]
We don't build zfs for ogc kernel.

We only build for the coreos-stable and coreos-testing kernel.

**Comment by ruzko** [comment]
Thank you for your very quick reply 🙂
I see ucore -nvidia images bundle compute-only nvidia drivers.

In order for my system to keep graphics, compute and zfs as it has until now; can I do something small like building zfs for ogc kernel and install as a local package or switch to a different kernel, or do I need to make my own image from the ground up with nvidia graphics+compute and zfs, maybe using the coreos-stable kernel?
