### ISSUE TITLE
Hard to install on the Steam Deck

### ISSUE THREAD

**Issue by Linwer** [ublue-os/bazzite#144]
Don't know how realistic this will be until Red Hat finishes with the new installer, but the lack of an on-screen keyboard in current Anaconda makes it impossible to install the system without a USB keyboard - something that SteamOS can do. The hitch was on setting up a new user and having to input a username and password for one. SteamOS makes a 'deck' user out of the box with no password. Maybe there's a way to do that with Kickstart?

**Comment by Linwer** [comment]
Also the Anaconda UI doesn't fit inside the confines of the Steam Deck's 1280x800, making the installation experience more irritating, but that's a separate issue I suppose.

**Comment by castrojo** [comment]
Related: https://github.com/ublue-os/main/issues/283

**Comment by Linwer** [comment]
WORKAROUND: with the touchscreen you can select and copy text from the Timezone screen and make that your username. The username is saved each time you leave the Users and Passwords screen, so you can come back to the Timezone screen multiple times to copy the letters you want. I feel like a genius.

**Comment by EyeCantCU** [comment]
This is genuinely the coolest workaround I have ever seen on GitHub. Hopefully, when we're able to implement the new installer, we can address a lot of these pain points. I'm sorry the process currently isn't easier without an external keyboard

**Comment by simon511000** [comment]
> Also the Anaconda UI doesn't fit inside the confines of the Steam Deck's 1280x800, making the installation experience more irritating, but that's a separate issue I suppose.

I can't even do the first step since the "next" button is off the screen

**Comment by KyleGospo** [comment]
> > Also the Anaconda UI doesn't fit inside the confines of the Steam Deck's 1280x800, making the installation experience more irritating, but that's a separate issue I suppose.
> 
> I can't even do the first step since the "next" button is off the screen

The workaround for that, for now, is to plug in a keyboard and tab to that button, then press enter.

Once we have the new installer working things should be a lot smoother.

**Comment by Linwer** [comment]
> The workaround for that, for now, is to plug in a keyboard and tab to that button, then press enter.

Got you covered, the Select button corresponds to Tab.

**Comment by szescxz** [comment]
Workaround for Ventoy users (requires a keyboard):
- Select "Boot in grub2 mode" (if the normal mode stucked but except the following case)
- Once it stucks at `Kickstart file /run/install/ks.cfg is missing`:
  - <kbd>Ctrl</kbd>+<kbd>B</kbd> then <kbd>2</kbd>
  - `# /run/install/repo/kickstart/pre-install.sh`
  - `# anaconda --kickstart /run/install/repo/kickstart/ublue-os.ks --resolution 1280x800`

Non Ventoy users could probably utilize the resolution trick with the [boot option](https://anaconda-installer.readthedocs.io/en/latest/boot-options.html#inst-resolution) in the GRUB menu, but I haven't tested it yet.

**Comment by KyleGospo** [comment]
Fixed as of the latest changes, next release will get a new ISO.

**Comment by szescxz** [comment]
With the introduction of the offline ISO (which now seems to work with Ventoy) I think the resolution issue is coming back again.

**Comment by KyleGospo** [comment]
> With the introduction of the offline ISO (which now seems to work with Ventoy) I think the resolution issue (on Steam Deck) is coming back again.

@akdev1l
