### ISSUE TITLE
Wireplumber doesn't seem to respect global configs

### ISSUE THREAD

**Issue by thecalamityjoe87** [ublue-os/bazzite#1440]
### Describe the bug

This is related to this commit: https://github.com/ublue-os/bazzite/commit/d0b321e19c65ee190962c0b945711c299a5becd5

Wireplumber will respect configs in my local directory, but it seems to ignore /usr/share/wireplumber/wireplumber.conf.d. If I remove my local config files, my internal mic no longer defaults to itself. 

### What did you expect to happen?

New configs were added to the stock configuration, but aren't being seen.

### Hardware

Legion Go (lenovo-83e1)

**Comment by KyleGospo** [comment]
https://www.collabora.com/news-and-blog/blog/2022/10/27/from-lua-to-json-refactoring-wireplumber-configuration-system/#qcom2740

**Comment by thecalamityjoe87** [comment]
> https://www.collabora.com/news-and-blog/blog/2022/10/27/from-lua-to-json-refactoring-wireplumber-configuration-system/#qcom2740

OK, I figured out the issue. The global configs _are_ being respected from /usr/share/wireplumber. The problem are the files located in /etc/wireplumber/wireplumber.conf.d. Moving alsa-card0.conf to a dummy file works:

```
legion@Isaac-LegionGo:~$ wpctl inspect 69
id 69, type PipeWire:Interface:Node
    alsa.card = "1"
    alsa.card_name = "HD-Audio Generic"
    alsa.class = "generic"
    alsa.components = "HDA:10ec0257,17aa3c26,00100001"
    alsa.device = "0"
    alsa.driver_name = "snd_hda_intel"
    alsa.id = "Generic_1"
    alsa.long_card_name = "HD-Audio Generic at 0x906c0000 irq 109"
    alsa.mixer_name = "Realtek ALC257"
    alsa.name = "ALC257 Analog"
    alsa.resolution_bits = "16"
    alsa.subclass = "generic-mix"
    alsa.subdevice = "0"
    alsa.subdevice_name = "subdevice #0"
    api.alsa.card.longname = "HD-Audio Generic at 0x906c0000 irq 109"
    api.alsa.card.name = "HD-Audio Generic"
    api.alsa.path = "front:1"
    api.alsa.pcm.card = "1"
    api.alsa.pcm.stream = "capture"
    audio.adapt.follower = ""
    audio.channels = "2"
    audio.position = "FL,FR"
    card.profile.device = "0"
  * client.id = "62"
    clock.quantum-limit = "8192"
    device.api = "alsa"
    device.class = "sound"
  * device.id = "74"
    device.profile.description = "Analog Stereo"
    device.profile.name = "analog-stereo"
    device.routes = "2"
  * factory.id = "18"
    factory.mode = "split"
    factory.name = "api.alsa.pcm.source"
    library.name = "audioconvert/libspa-audioconvert"
  * media.class = "Audio/Source"
  * node.description = "Family 17h/19h HD Audio Controller Analog Stereo"
    node.driver = "true"
  * node.name = "alsa_input.pci-0000_c2_00.6.analog-stereo"
  * node.nick = "ALC257 Analog"
    node.pause-on-idle = "false"
  * object.path = "alsa:pcm:1:front:1:capture"
  * object.serial = "863"
  *** priority.driver = "8901"
  * priority.session = "8901"**
```

**Comment by thecalamityjoe87** [comment]
So, this seems like an easy fix. If whatever is creating the files in /etc/wireplumber is stopped, then these new configuration files will work. I guess it's because of the way wireplumber respects configuration files. It ranks priority in this order: `~/.config/wireplumber (first) --- /etc/wireplumber --- /usr/share/wireplumber (last)`

**Comment by KyleGospo** [comment]
Should now be fixed as of latest, had to move those files from /etc and then replace alsa-card0 with a slightly modified one as part of the legion go specific config.

**Comment by thecalamityjoe87** [comment]
> Should now be fixed as of latest, had to move those files from /etc and then replace alsa-card0 with a slightly modified one as part of the legion go specific config.

It's working for me. I haven't tried HDMI yet, but I'm assuming that's still good. 

What was creating /etc/wireplumber/wireplumber.conf.d? I was racking my brain trying to figure out which script was making that directory. I didn't think it was wireplumber-hwconfig. Is it wireplumber.spec doing it?

**Comment by KyleGospo** [comment]
> > Should now be fixed as of latest, had to move those files from /etc and then replace alsa-card0 with a slightly modified one as part of the legion go specific config.
> 
> It's working for me. I haven't tried HDMI yet, but I'm assuming that's still good. 
> 
> What was creating /etc/wireplumber/wireplumber.conf.d? I was racking my brain trying to figure out which script was making that directory. I didn't think it was wireplumber-hwconfig. Is it wireplumber.spec doing it?

Loose files in this repository that came from Steam OS in the early days. I moved the still applicable ones to /usr
