### ISSUE TITLE
last update shows black screen

### ISSUE THREAD

**Issue by fastoslinux** [ublue-os/bazzite#1447]
### Describe the bug

the following deployment has a black screen:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:fa058d1bc6e0f944b881061be5dc46dbaa4f65aa3e647603b1302dcf23374094
                  Version: 40.20240731.0 (2024-07-31T16:43:37Z)
                     Diff: 52 upgraded, 17 removed, 25 added

the previous one is ok:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:29d6591cbcb36f0dac5a7bc1c376de12c4103d79db7567dbb5b525348ce152aa
                  Version: 40.20240728.0 (2024-07-28T21:45:34Z)

### What did you expect to happen?

SteamUI loads normally

### Output of `rpm-ostree status`

```shell
$ rpm-ostree status
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:fa058d1bc6e0f944b881061be5dc46dbaa4f65aa3e647603b1302dcf23374094
                  Version: 40.20240731.0 (2024-07-31T16:43:37Z)
                     Diff: 52 upgraded, 17 removed, 25 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:29d6591cbcb36f0dac5a7bc1c376de12c4103d79db7567dbb5b525348ce152aa
                  Version: 40.20240728.0 (2024-07-28T21:45:34Z)
```

### Hardware

Dados do computador:
Fabricante: INTEL
Modelo: X99-P4
Tipo: Computador de mesa
Sem entrada de toque
Dados do processador:
Fabricante da CPU: GenuineIntel
Marca da CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Família do processador: 0x6
Modelo do processador: 0x4f
Stepping do processador: 0x1
Tipo do processador: 0x0
Velocidade: 3100 MHz
20 processadores lógicos
10 processadores físicos
HyperThreading: compatível
FCMOV: compatível
SSE2: compatível
SSE3: compatível
SSSE3: compatível
SSE4a: incompatível
SSE41: compatível
SSE42: compatível
AES: compatível
AVX: compatível
AVX2: compatível
AVX512F: incompatível
AVX512PF: incompatível
AVX512ER: incompatível
AVX512CD: incompatível
AVX512VNNI: incompatível
SHA: incompatível
CMPXCHG16B: compatível
LAHF/SAHF: compatível
PrefetchW: incompatível
Versão do sistema operacional:
"Bazzite (FROM Fedora Silverblue 40)" (64 bits)
Nome do kernel: Linux
Versão do kernel: 6.9.9-206.fsync.fc40.x86_64
Consórcio do Servidor X: The X.Org Foundation
Versão do Servidor X: 12401000
Gerenciador de janelas X: GNOME Shell
Versão do componente de tempo de execução do Steam: steam-runtime_0.20240610.91380
Placa de vídeo:
Driver: AMD AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.6, DRM 3.57, 6.9.9-206.fsync.fc40.x86_64)
Versão do driver: 4.6 (Compatibility Profile) Mesa 24.1.4
Versão do OpenGL: 4.6
Profundidade de cor da área de trabalho: 24 bits por pixel
Taxa de atualização do monitor: 74 Hz
VendorID: 0x1002
DeviceID: 0x67df
Revisão não detectada
Quantidade de monitores: 1
Quantidade de placas de vídeo lógicas: 1
Resolução do monitor primário: 1920 x 1080
Resolução da área de trabalho: 1920 x 1080
Tamanho do monitor primário: 20.87" x 11.81" (23.98" diag), 53.0cm x 30.0cm (60.9cm diag)
VRAM primária: 8192 MB
Placa de som:
Dispositivo de áudio: Realtek ALC887-VD
Memória:
RAM: 15884 MB
Hardware de RV:
Headset de RV: nenhum detectado
Outros:
Idioma da interface: Português (Brasil)
IDIOMA: pt_BR.UTF-8
Total de espaço disponível em disco: 486761 MB
Maior bloco livre do disco rígido: 116597 MB
Armazenamento:
Quantidade de SSDs: 2
Tamanho dos SSDs: 512G,240G
Quantidade de HDs: 0
Quantidade de discos removíveis: 0

### Extra information or context

after the last update I have a black screen

**Comment by HikariKnight** [comment]
Fixed in the latest update, it was a bad build from me that day sorry (There was a lot of Polaris card issues that day being worked on and they are fixed now)!
Boot into your previous deployment (`ostree:1`) go into desktop mode and pin it `sudo ostree admin pin 1` and just issue a new update with the system updater to get the newest build.
once everything is verified working on the new build you can unpin the pinned deployment with `sudo ostree admin pin --unpin 2`

**Comment by fastoslinux** [comment]
thanks, just updated and fixed it!

**Comment by HikariKnight** [comment]
great!
