### ISSUE TITLE
Surface Pen support missing when present ootb in Bluefin.

### ISSUE THREAD

**Issue by valerie-tar-gz** [ublue-os/bazzite#1449]
### Describe the bug

My Surface pen does not register properly with Bazzite after being connected. Nothing shows in settings about the tablet and no input is recognised as either mouse or pen.

### What did you expect to happen?

In Bluefin (39 & 40, gts & latest) the pen works after being connected via bluetooth for the first time as you'd expect. Wacom tablet settings show and allow you to change settings. It lets you use the pen as a mouse on the desktop. Pressure sensitivity works in Krita, using the other end of the pen works as an eraser, the button on the pen works and is bindable, the whole nine yards.

### Hardware

Surface Book 2 w/ Surface Pen.

### Extra information or context

Brand new install of Bazzite, not updated but I believe it shouldn't really matter.

I additionally tried layering opentablet driver but this did not work, nor did I use it on Bluefin.

**Comment by KyleGospo** [comment]
@castrojo any idea what you might be shipping to make this work?

**Comment by crush-hjtm** [comment]
I ran rpm -qa on my bazzite desktop and the surface and there seems to be a few surface related packages. However my surface is on bluefin-dx-surface. I'm going to rebase to the non-surface version and see if the pen stops working. If so, might just be something that should you could recommend layering, or ship in the image assuming it doesn't conflict with anything else.

**Comment by castrojo** [comment]
It'd be in here somewhere, but the packages we just added are for libcamera support. Maybe something in the config files? 

https://github.com/ublue-os/hwe/tree/main/surface

**Comment by crush-hjtm** [comment]
Upon rebasing to the non-surface image the pen no longer worked

**Comment by crush-hjtm** [comment]
Running rpm -qa | grep "surface" on the bluefin surface image yields:
`kernel-surface-default-watchdog-6.9.9-1.surface.fc40.x86_64
kernel-surface-modules-core-6.9.9-1.surface.fc40.x86_64
kernel-surface-core-6.9.9-1.surface.fc40.x86_64
kernel-surface-modules-6.9.9-1.surface.fc40.x86_64
kernel-surface-6.9.9-1.surface.fc40.x86_64
kernel-surface-modules-extra-6.9.9-1.surface.fc40.x86_64
libwacom-surface-2.12.2-1.fc40.x86_64
kmod-wl-6.9.9-1.surface.fc40.x86_64-6.30.223.271-51.fc40.x86_64
kmod-v4l2loopback-6.9.9-1.surface.fc40.x86_64-0.13.1-1.fc40.x86_64
kmod-xone-6.9.9-1.surface.fc40.x86_64-0.0.git.115.fdbb71f1-1.fc40.x86_64
kmod-openrazer-6.9.9-1.surface.fc40.x86_64-100.0.0.git.530.886f986d-1.fc40.x86_64
kmod-xpadneo-6.9.9-1.surface.fc40.x86_64-0.9.6-2.20240423git73be2eb.fc40.x86_64
kmod-evdi-6.9.9-1.surface.fc40.x86_64-1.14.5-1.fc40.x86_64
kmod-kvmfr-6.9.9-1.surface.fc40.x86_64-0.0.git.22.68286efd-1.fc40.x86_64
`

I'm assuming the libwacom stuff is the key.

**Comment by crush-hjtm** [comment]
Apparently libwacom-surface is a library for libwacom which IS included with Bazzite, and the two shouldn't conflict. Gonna reinstall Bazzite and see if this fixes my issue. If it does, might be possible to include with the base image.

**Comment by Potajito** [comment]
I'm not sure that it could be related, but there is also this issue with ublue images related to tablets: https://github.com/ublue-os/main/issues/622

**Comment by Saroufim** [comment]
Surface Pen 2 doesn't work for me until I install iptsd. Maybe that package is being pulled?
