### ISSUE TITLE
Using Search with the Steam Deck keyboard on GNOME

### ISSUE THREAD

**Issue by Linwer** [ublue-os/bazzite#145]
Using GNOME on the Steam Deck feels snappy and intuitive (especially once you figure out you can use backplate buttons for Activities overview and workspace switching), however, there is a major issue with GNOME Search on the Steam Deck. Instead of being drawn over the Activities overview, the Steam Deck keyboard window is created in the active workspace and is only present there.

https://github.com/ublue-os/bazzite/assets/25704588/febd15a5-bd57-4986-94ab-facf55485635

**Comment by KyleGospo** [comment]
Much appreciated, looking into how best to fix this.

**Comment by KyleGospo** [comment]
I don't see an easy way to fix the keyboard, but we can move the search out of overview to fix it, I'm working on that now.

The issue of GNOME keyboard popping up is also fixed.

**Comment by KyleGospo** [comment]
Search now fixed by inclusion of Search Light until keyboard can be addressed
