### ISSUE TITLE
Bluetooth Failing After Suspend

### ISSUE THREAD

**Issue by Jules2390** [ublue-os/bazzite#1453]
### Describe the bug

When I suspend and then resume on ASUS ROG Ally, the Bluetooth fails--it no longer detects Bluetooth devices, including previously paired ones. To reconnect, I have to reboot the machine. 

### What did you expect to happen?

For devices connected pre-suspend to be remembered, and possibly even reconnect automatically. 

### Hardware

ASUS ROG Ally Z1 Extreme

**Comment by SmoothMcBeats** [comment]
Yes I'm having this on my ally x. If you go to desktop mode and back it fixes it as well, so it's just in game mode. No devices show up. You don't have to fully reboot.

**Comment by KyleGospo** [comment]
Latest update may fix this

**Comment by SmoothMcBeats** [comment]
I think you're right. Literally right as you posted that steam said a system update was needed. Applied and works. I'll keep testing it.

**Comment by SmoothMcBeats** [comment]
So far so good.

**Comment by Jules2390** [comment]
Hello Bazzite friends,

The issue is resolved, so far as I can tell. Thank you! I've really enjoyed
using Bazzite -- I use it on my desktop PC as well, dualbooting with
Windows-- and it's great stuff.

Thank you!!
