### ISSUE TITLE
Can't boot Bazzite after "Updating kargs" message during startup

### ISSUE THREAD

**Issue by Aqyv** [ublue-os/bazzite#1454]
### Describe the bug

Yesterday, and the weeks before, Bazzite was working just fine, but booting it today on my desktop leads to the following:

1. Normal Bazzite startup screen
2. During startup there's a very short message regarding "Updating kargs"
3. A few seconds later I get a black screen with my mainboard manufacturer logo showing, but nothing happening

### What did you expect to happen?

Bazzite booting like it used to.

### Hardware

Nvidia GPU.

### Extra information or context

Regardless of what ostree I select during startup I always get the above result.
I updated everything that could be updated via topgrade yesterday.

Dual-booting Windows works as usual.

**Comment by HikariKnight** [comment]
Can you press ESC which will show you what is going on during boot.
if it is still "stuck" on updating kargs, just wait and let it finish, the first boot takes time as it is configuring the system for you

**Comment by gjm19761** [comment]
i have same problem with amd ryzen with vega graphics, just black screen after that

**Comment by HikariKnight** [comment]
> i have same problem with amd ryzen with vega graphics, just black screen after that

is this using the deck image?

**Comment by gjm19761** [comment]
yes, works fine on my hp g4 mini with ryzen 3 pro 2200ge , but not on my ryzen 3200ge both have same vega graphics

**Comment by HikariKnight** [comment]
Ok for @gjm19761 make a new issue and provide the info below (incase the original posters issue is nvidia specific), especially since you are on the deck image which has no support for nvidia.

```
rpm-ostree status
cat ~/.gamescope-cmd.log
cat ~/.gamescope-stdout.log
```

you can maybe get this from CTRL+ALT+F4

for @Aqyv 
try CTRL+ALT+F4
and give me the output of
```
journalctl -b 0 | fpaste
sudo dmesg | fpaste
rpm-ostree status
```

**Comment by gjm19761** [comment]
ok well im trying the gnome deck stable now, im doing this through a capture card now too so can see anything  that happens

**Comment by Aqyv** [comment]
I already reinstalled shortly after opening the issue, as I had work to do and still had backups.

So far no issues since the reinstall.
