### ISSUE TITLE
get black screen after reboot after kargs section finishes

### ISSUE THREAD

**Issue by gjm19761** [ublue-os/bazzite#1455]
### Describe the bug

after the reboot from the karg bit, i get bios etc, and booting bazzite etc, but then black screen

### What did you expect to happen?

im using a hp 700 g5 3200ge system which is amd vega graphics, i also have a hp 405 g4 which has a ryzen 2200ge chip with same vega graphics, and that works fine. ctrl alt f4 isnt doing anything atm with gnome deck stable, i can get a kde desktop after installing that one, but it black screens when going into gaming mode. ill reinstall the kde one and then i can get to those logs.

### Hardware

hp 700 g5 ryzen 3200ge with vega graphics, 32gb  ddr4

**Comment by gjm19761** [comment]
[gamescope] [[0;34mInfo[0m]  [0;37mconsole:[0m gamescope version 3.14.24+
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m selecting physical device 'AMD Radeon Vega 8 Graphics (RADV RAVEN)': queue family 1 (general queue family 0)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m physical device supports DRM format modifiers
[Gamescope WSI] Forcing on VK_EXT_swapchain_maintenance1.
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/headless/backend.c:67] Creating headless backend
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/session/session.c:108] Successfully loaded libseat session
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m opening DRM node '/dev/dri/card1'
[gamescope] [[0;31mError[0m] [0;37mdrm:[0m Immediate flips disabled from environment
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m Connector DP-4 -> SAM - SAMSUNG
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: r 0.640000 0.330000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: g 0.300000 0.600000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: b 0.150000 0.060000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: w 0.312700 0.329000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m Connector DP-4 -> SAM - SAMSUNG
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: r 0.640000 0.330000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: g 0.300000 0.600000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: b 0.150000 0.060000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: w 0.312700 0.329000
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m Connectors:
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m   DP-4 (connected)
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m   DP-2 (disconnected)
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m   DP-3 (disconnected)
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m   DP-1 (disconnected)
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m selecting connector DP-4
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m selecting mode 3840x2160@60Hz
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m No orientation quirks have been applied
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m supported DRM formats for sampling usage:
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AR24 (0x34325241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XR24 (0x34325258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB24 (0x34324241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB24 (0x34324258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   RG16 (0x36314752)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   NV12 (0x3231564E)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB4H (0x48344241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB4H (0x48344258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB48 (0x38344241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB48 (0x38344258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB30 (0x30334241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB30 (0x30334258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AR30 (0x30335241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XR30 (0x30335258)
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m Running compositor on wayland display 'gamescope-0'
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/headless/backend.c:17] Starting headless backend
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/backend.c:88] Starting libinput backend
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding Power Button [0:1]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding Video Bus [0:6]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding Power Button [0:1]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding SEMICO USB Keyboard [6700:19550]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding SEMICO USB Keyboard Consumer Control [6700:19550]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding SEMICO USB Keyboard System Control [6700:19550]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding SEMICO USB Keyboard [6700:19550]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding ZY.Ltd ZY Control [6421:4167]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding ZY.Ltd ZY Control Mouse [6421:4167]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding ZY.Ltd ZY Control Consumer Control [6421:4167]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding ZY.Ltd ZY Control System Control [6421:4167]
[gamescope] [[0;35mDebug[0m] [0;37mwlserver:[0m [backend/libinput/events.c:69] Adding HP WMI hotkeys [0:0]
gamescope: ../src/wlserver.cpp:2478: void wlserver_mousemotion(double, double, uint32_t): Assertion `wlserver_is_lock_held()' failed.

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:5b360890a1efdb618638de46e92f302bb45877fd36195553982ea5865de42869
                  Version: 40.20240726.0 (2024-07-26T22:44:59Z)
 
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:5b360890a1efdb618638de46e92f302bb45877fd36195553982ea5865de42869
                  Version: 40.20240726.0 (2024-07-26T22:44:59Z)/usr/bin/gamescope --bypass-steam-resolution --disable-touch-click --prefer-output *,eDP-1 --xwayland-count 2 --default-touch-mode 4 --hide-cursor-delay 3000 --fade-out-duration 200 --steam -R /run/user/1000/gamescope.WyWnNAe/startup.socket -T /run/user/1000/gamescope.WyWnNAe/stats.pipe

**Comment by gjm19761** [comment]
i captured what happened and uploaded to youtube https://www.youtube.com/watch?v=hLLJFxoDrBA

I had to restart as it stayed at black screen and i dont even get desktop now, its black screen since reboot, i can however ssh in as i enabled sshd

**Comment by gjm19761** [comment]
just tried to run it in ssh changing edp-1 to edp-4

obviously its gonna fail in ssh, but this is what i get

[gjm@bazzite ~]$ /usr/bin/gamescope --bypass-steam-resolution --disable-touch-click --prefer-output *,eDP-4 --xwayland-count 2 --default-touch-mode 4 --hide-cursor-delay 3000 --fade-out-duration 200 --steam -R /run/user/1000/gamescope.WyWnNAe/startup.socket -T /run/user/1000/gamescope.WyWnNAe/stats.pipe
[gamescope] [Info]  console: gamescope version 3.14.24+
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
[gamescope] [Info]  vulkan: selecting physical device 'AMD Radeon Vega 8 Graphics (RADV RAVEN)': queue family 1 (general queue family 0)
[gamescope] [Info]  vulkan: physical device supports DRM format modifiers
[gamescope] [Info]  wlserver: [backend/headless/backend.c:67] Creating headless backend
[gamescope] [Info]  wlserver: [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[gamescope] [Info]  wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[gamescope] [Info]  wlserver: [libseat] [libseat/libseat.c:76] Backend 'logind' failed to open seat, skipping
[gamescope] [Error] wlserver: [libseat] [libseat/libseat.c:79] No backend was able to open a seat
[gamescope] [Error] wlserver: [backend/session/session.c:83] Unable to create seat: Function not implemented
[gamescope] [Error] wlserver: [backend/session/session.c:248] Failed to load session backend
[gamescope] [Error] wlserver: Failed to create session
Failed to initialize Wayland session
Failed to create backend.

**Comment by gjm19761** [comment]
ok it doesnt boot into desktop now as im having to force reboots, but getting this when there is no output at all after reboot

[gamescope] [[0;34mInfo[0m]  [0;37mconsole:[0m gamescope version 3.14.26+
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m selecting physical device 'AMD Radeon Vega 8 Graphics (RADV RAVEN)': queue family 1 (general queue family 0)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m physical device supports DRM format modifiers
[Gamescope WSI] Forcing on VK_EXT_swapchain_maintenance1.
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/headless/backend.c:67] Creating headless backend
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/session/session.c:108] Successfully loaded libseat session
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m opening DRM node '/dev/dri/card1'
[gamescope] [[0;31mError[0m] [0;37mdrm:[0m '/dev/dri/card1' is not a KMS device
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m supported DRM formats for sampling usage:
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AR24 (0x34325241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XR24 (0x34325258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB24 (0x34324241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB24 (0x34324258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   RG16 (0x36314752)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   NV12 (0x3231564E)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB4H (0x48344241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB4H (0x48344258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB48 (0x38344241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB48 (0x38344258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB30 (0x30334241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB30 (0x30334258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AR30 (0x30335241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XR30 (0x30335258)
[gamescope] [[0;31mError[0m] [0;37mvulkan:[0m failed to find Vulkan format suitable for KMS
vulkan_make_output failed

**Comment by craigers521** [comment]
Just started happening to me today after an update. I haven't rebooted in a hot minute.

**Comment by gjm19761** [comment]
yep i got no further either and had no help from ppl since opening this issue :(

**Comment by devaba** [comment]
I am getting updating kargs after booting after first install phase, then black screen and nothing happens, what to do?, PC AMD Ryzen 5 3400G with radeon graphics, screens, one is a TV.

**Comment by vbspk** [comment]
> I am getting updating kargs after booting after first install phase, then black screen and nothing happens, what to do?, PC AMD Ryzen 5 3400G with radeon graphics, screens, one is a TV.
> 
> I forced switch off and rebooted, got message "Updating kargs" then black screen, nothing happens.

I also have the same processor and thinking of installing bazzite in it.
So can you please let me know if your issue got resolved🙂?

**Comment by devaba** [comment]
Hi yes, just reinstalled after a couple of days and was then fine.
