### ISSUE TITLE
Screen flashing after resuming from sleep 

### ISSUE THREAD

**Issue by tpkee** [ublue-os/bazzite#1456]
### Describe the bug

How to reproduce: 
- use latest bazzite-deck image on a desktop
- Connect Bluetooth controller
- sleep mode
- Resume from sleep
- Reconnect controller
- to fix start a game 

### What did you expect to happen?

Resuming the sleep without a GPU simil-failure 

### Hardware

- intel 13600k
- 7900XTX
- 32GB @ 6000mhz

### Extra information or context

A video of the issue made on a relatively fresh install (I had the same problem on an older install too, though). NOTE: **heavy** flashing inside, don’t watch it if suffer from epilepsy 

https://github.com/user-attachments/assets/495a7c28-f80c-4676-8a05-11963d4f1e87

**Comment by theflakes** [comment]
Seeing the same issue, if I turn off or on VRR it fixes it.

Starting a game does not fix it for me.

AMD 7745HX CPU
AMD 7900 GRE
32GB 5200 RAM
XBox controller

**Comment by tpkee** [comment]
> Seeing the same issue, if I turn off or on VRR it fixes it.
> 
> Starting a game does not fix it for me.
> 
> AMD 7745HX CPU AMD 7900 GRE 32GB 5200 RAM XBox controller

To add on this: it’s not related to the controller *i think*, I have the same issue with a PS controller.
