### ISSUE TITLE
On screen keyboard in installer missing.

### ISSUE THREAD

**Issue by JSmaler** [ublue-os/bazzite#1463]
### Describe the bug

I tried installing Bazzite on a steam deck, and during installation, no On-screen keyboard is available.

### What did you expect to happen?

According to @KyleGospo 's comment in issue #715 , which requests an on-screen-keyboard, there should be one in the "new installer". There isn't, or if there is, there is no way to open it, or the way to do so is just not described.

I recognize that the comment i refer back to here does not state directly that one was added, but given that the issue was closed after it, I had assumed it to have been.

### Output of `rpm-ostree status`

I do not know how I would get to the terminal from the installer without a keyboard.
I am running the newest version of the bazzite deck-gnome .ISO .

### Hardware

Steam deck 256GB LCD

### Extra information or context

Bazzite naturally does not have to include an On-screen-keyboard in the installer. Continuing to not do so naturally limit the accessibility immensely, but if that is a worthwhile tradeoff is not my decision to make.
If, however, bazzite does not, and continues not to, it would be nice if the first result of googling "bazzite on screen keyboard" didn't indicate the opposite.

I am also not really used to anything surrounding GitHub, so if this issue is not seen as useful, please go ahead and remove it.

**Comment by KyleGospo** [comment]
Generic message we closed a number of issues about the installer with. There is still no keyboard and will not be one for the foreseeable future.

**Comment by JSmaler** [comment]
fair enough. i guess ill look to find a new USB hub, or stick with steamOS.
thanks for the clarification.

**Comment by JSmaler** [comment]
Fair enough. I guess ill look to find a new USB hub, or stick with steamOS.
Thanks for the clarification.
