### ISSUE TITLE
OpenRGB issues

### ISSUE THREAD

**Issue by Dark-Thoughts** [ublue-os/bazzite#1470]
### Describe the bug

The app's autostart functions do not work and the tray icon title is "AppRun.Wrapped". You can add it to the system's autostart, but that does not provide the apps autostart functions.

### What did you expect to happen?

I expected the "start at login" option to make the app start with the OS, but it didn't.
I expected the "start minimized" option to make the app start minimized, but it didn't.
I expected the "load profile" option to automatically load a profile on start, but it didn't.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:8833376d2c232931a91e85397072f75406099f24970f13902846eca3acccc394
                  Version: 40.20240807.0 (2024-08-07T07:31:29Z)
            SecAdvisories: 1 unknown severity, 1 important
                     Diff: 79 upgraded, 2 removed, 11 added
          LayeredPackages: goverlay
            LocalPackages: lact-0.5.5-0.x86_64

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:c58e6c54668614acc5620403a2daac520559f9d6fab9ba2c3ad1a07f82353a9d
                  Version: 40.20240803.0 (2024-08-04T06:31:02Z)
          LayeredPackages: goverlay
            LocalPackages: lact-0.5.5-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:c58e6c54668614acc5620403a2daac520559f9d6fab9ba2c3ad1a07f82353a9d
                  Version: 40.20240803.0 (2024-08-04T06:31:02Z)
          LayeredPackages: goverlay
            LocalPackages: lact-0.5.5-0.x86_64
```

**Comment by KyleGospo** [comment]
We don't write this software, you'll want to open an issue with them

**Comment by Dark-Thoughts** [comment]
But this happens specifically only in this distro. Or at least neither in Manjaro, EndeavourOS, nor Nobara.

**Comment by KyleGospo** [comment]
> But this happens specifically only in this distro. Or at least neither in Manjaro, EndeavourOS, nor Nobara.

Just reproduced this on a stock Fedora 40 VM. Not immutable. You can note that in your issue w/ OpenRGB.
