### ISSUE TITLE
Problem pairing XBox Bluetooth controller after reboot

### ISSUE THREAD

**Issue by Blade-pt** [ublue-os/bazzite#1471]
### Describe the bug

I pair de bluetooth xbox controller and it works fine, but after reboot, when i turm the controller on it just keeps looking to pair and never does. if at any point i enter the bluetooth menu it immediately pairs. This in game mode (same happens in desktop). I have the destop installation as it is for a htpc.

### What did you expect to happen?

Expected after boot in to game mode to pair the controller just by turning it on. Idea was to avoid keyboard all together when i connect computer to the tv as a htpc.

### Output of `rpm-ostree status`

```shell
none
```

### Hardware

ASRock X300 Motherboard with Ryzen 5600G, 16Gb DDR4 and 2 nvme drives.

### Extra information or context

clean install. Made sure to make the device trusted and have bluetooth turn on with system.

**Comment by KyleGospo** [comment]
Another user had this issue and the fix was to update their controller firmware, you may try the same.

**Comment by Blade-pt** [comment]
Thank you for the reply. Tried that and get the exact same behavior. Keeps blinking until i enter the bluetooth menu.
Is there any way to have game mode on boot to go straight to bluetooth menu? that would be a workaround i guess.

**Comment by Blade-pt** [comment]
Replacing the built in Bluetooth adapter from Intel with an external USB one fixed the issue, had the onboard one disabled and after that it works flawless.

**Comment by SoyIago** [comment]
Happened to me with an Intel `3168NGW` built-in Bluetooth module, controller wouldn't pair until visiting the Bluetooth section of SteamOS or GNOME.

Replacing it with a Realtek Radio (`2b89:8761`) over external USB fixed the issue.

Mine is built by UGREEN model number is `CM390 80889`, I think it is discontinued but any other matching the device ID above should do the trick. 

Tried changing all sort of configs and nothing but replacing it worked.

Also, Xbox Series Controller was on the latest version as of today (Jan 5 2024).
