### ISSUE TITLE
ASUS ROG Ally X: Suspending the Device Causes Weird Quirks

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/bazzite#1473]
### Describe the bug

When the device is suspended and woken up there are some interesting game breaking issues that occur:
- The top and bottom Steam Gaming Mode panel is completely missing that contained information such as the time, battery life, downloads and wifi status (top) as well as the button prompts at the bottom.
- Controls no longer work outside of Steam (including the touch screen), run a Steam game after suspending means controls no longer work.

Another interesting tidbit is that suspending from the power menu produces **no animation** yet suspending from the Steam menu plays it.  Regardless of the method, resuming from suspension still breaks the top panel and controls.

A quick fix / workaround is going to Desktop Mode and then going back to Steam Gaming Mode as opposed to rebooting the device, but that works too.

### What did you expect to happen?

I expected the device to resume from sleep and have functional controls and UI elements to stay in place.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:2b819c7d8ce57430feb53598b16afa841a7d9da011ec2089502a29d3aa74215d
                  Version: 40.20240807.0 (2024-08-07T07:32:18Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:2b819c7d8ce57430feb53598b16afa841a7d9da011ec2089502a29d3aa74215d
                  Version: 40.20240807.0 (2024-08-07T07:32:18Z)
```

### Hardware

ROG Ally X RC72LA_RC72LA

### Extra information or context

This is the last bug that I have found today.

### Edit (Solution)

Turn off the waking animation after suspending in the Steam settings.

**Comment by LOLLeela** [comment]
Hey, it's a bit of a known issue with steam.
Switch off the animation on resume and if that doesn't help you may need to remove some files.

https://github.com/ublue-os/bazzite/issues/1474

**Comment by nicknamenamenick** [comment]
> Hey, it's a bit of a known issue with steam. Switch off the animation on resume and if that doesn't help you may need to remove some files.
> 
> #1474

That is most likely it, thanks.
