### ISSUE TITLE
Gamescope looses focus resuming from suspend if resume animation present.

### ISSUE THREAD

**Issue by LOLLeela** [ublue-os/bazzite#1474]
### Describe the bug

I have found when resuming from suspend if you have any resume/suspend animation the controller can't control the game, steam works fine though.

This is with both the decky loader animation changer plugin and any files added in the UI override folder under steam manually.

If the problem happens on restore from suspend and focus is lost, then removing the files, making sure the animation on resume is off and reboot fixes it.

### What did you expect to happen?

I'd expect this to not happen and to get control back in game but it might be a problem with steam itself.

### Hardware

ROG Ally

### Extra information or context

Discussed on the ROG ally thread on discord. Several users report it worked for them

**Comment by LOLLeela** [comment]
Related

https://github.com/ValveSoftware/SteamOS/issues/1424

**Comment by LOLLeela** [comment]
The files I removed were
to deck-suspend-animation.webm or deck-suspend-animation-from-throbber.webm or jpg, from ~/.steam/root/config/uioverrides/movies/.

**Comment by KyleGospo** [comment]
If you have the feature to play your startup video when resuming from suspend, disable it. This is a known issue on steamos as well.

**Comment by bugs181** [comment]
Related? https://github.com/ublue-os/bazzite/issues/1175
