### ISSUE TITLE
Steam can't download games because "not connected to the internet"

### ISSUE THREAD

**Issue by mrhenry549** [ublue-os/bazzite#1475]
### Describe the bug

While on Game Mode, I'm connected to the Wi-Fi with internet and can't download games. I can on Desktop mode.

### What did you expect to happen?

I expected to be able to download new games from the Game Mode environment.

### Hardware

ROG Ally X

**Comment by HikariKnight** [comment]
From my experience (on the legion go) this is steam being dumb and it thinks it is in offline mode or something, it is fixed by setting steam into offline mode then back to online mode.
