### ISSUE TITLE
Nextcloud desktop client not started when entering desktop mode

### ISSUE THREAD

**Issue by redwing-bb** [ublue-os/bazzite#1477]
### Describe the bug

Installed the Nextcloud desktop sync client flatpak, launched it, made sure "Settings > Launch on system startup" is checked. 

Client does not start when switching to desktop mode from gaming mode. 

### What did you expect to happen?

Expected the Nextcloud client to launch itself when I enter Desktop mode.

Since I'm on the -deck image on my steam deck I startup in game mode so can't test this booting directly to Gnome.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:2b819c7d8ce57430feb53598b16afa841a7d9da011ec2089502a29d3aa74215d
                  Version: 40.20240807.0 (2024-08-07T07:32:18Z)
                     Diff: 111 upgraded, 17 removed, 18 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:3f94fc529f1a9dfb0a47275f87e48eb382a9f7fa239d3eaeea2be884650b9d6d
                  Version: 40.20240802.0 (2024-08-02T16:19:40Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:e83719ca3dd1f8db54403be0654fc6814a46d5a3dc748786bc39bc63c30ddc00
                  Version: 40.20240730.0 (2024-07-30T13:49:30Z)
```

### Hardware

Jupiter

**Comment by KyleGospo** [comment]
See other issue, not our software and we don't have any control over flatpaks. They use their own libraries.
