### ISSUE TITLE
Bad/no theme in Nextcloud Desktop client main dialogue on Gnome

### ISSUE THREAD

**Issue by redwing-bb** [ublue-os/bazzite#1478]
### Describe the bug

Installed nextcloud desktop client flatpak, launched it, clicked "Open main dialog" in the nextcloud menu in the top bar. 

The window themeing is dark gray text on medium gray background, very poor legibility. 

I'm using dark mode but tested with light mode, no change in the appearance of the nextcloud desktop window.

### What did you expect to happen?

Legible themeing in the UI. 

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:2b819c7d8ce57430feb53598b16afa841a7d9da011ec2089502a29d3aa74215d
                  Version: 40.20240807.0 (2024-08-07T07:32:18Z)
                     Diff: 111 upgraded, 17 removed, 18 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:3f94fc529f1a9dfb0a47275f87e48eb382a9f7fa239d3eaeea2be884650b9d6d
                  Version: 40.20240802.0 (2024-08-02T16:19:40Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:e83719ca3dd1f8db54403be0654fc6814a46d5a3dc748786bc39bc63c30ddc00
                  Version: 40.20240730.0 (2024-07-30T13:49:30Z)
```

### Hardware

Jupiter

### Extra information or context

Launching from CLI: 

        QSocketNotifier: Can only be used with threads started with QThread
        qt.qpa.qgnomeplatform: Could not find color scheme  ""
        nextcloud.gui.application: Migrating old config from "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud"
        nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud" )
        nextcloud.gui.application: Will move the individual files ("Nextcloud_sync.log")
        nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed

**Comment by KyleGospo** [comment]
I would open this issue with them, we don't make the software and it's a flatpak so we have zero control over how it functions.
