### ISSUE TITLE
Monitors Wake Up ~20 Minutes After They Go To Sleep

### ISSUE THREAD

**Issue by VHSJayden** [ublue-os/bazzite#1480]
### Describe the bug

It seems like my monitors are waking from sleep. I set my monitors to go to sleep for 8 minutes after inactivity and after 1 hour, my PC suspends. After ~20 minutes, my monitors wake up. This makes my monitors go into a loop of going to sleep and waking up, making my PC never sleep.
Once they wake up, my windows from my secondary monitor all go to the primary monitor. I'm not sure if this is a GNOME bug but id thought I'd include it here.
I tried unplugging both my keyboard and mouse but no luck.

I had installed the GNOME spin on Fedora before and none of these issues seemed to occur to my knowledge. I installed Bazzite just a few days ago.

Before, on Windows, I would have a similar issue where my GPU would make my monitors sleep for a few seconds and wake them up. I could remedy this by either rolling back to a very old driver or turning off Ultra Low Power State mode using something like MSI Afterburner. Does something like this exist on Linux? 

### What did you expect to happen?

I expected my monitors to go to sleep and stay asleep until it was time to make my PC sleep.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:bf83de8a9d9472ef15ef975330779137fc9ce066d5224d8dd9edc019b74014e1
                  Version: 40.20240809.0 (2024-08-09T05:09:23Z)
            SecAdvisories: 1 unknown severity, 1 low, 2 important
                     Diff: 56 upgraded, 1 added
          LayeredPackages: gnome-themes-extra gtk-murrine-engine openrazer-meta razergenie
                           sassc
            LocalPackages: lact-libadwaita-0.5.5-0.x86_64

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:d186cadf6e3eef7fa8f35dec31b4313efabf77ebdccd74b09998d0296ae01c90
                  Version: 40.20240807.0 (2024-08-07T07:31:06Z)
          LayeredPackages: gnome-themes-extra gtk-murrine-engine openrazer-meta razergenie
                           sassc
            LocalPackages: lact-libadwaita-0.5.5-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:d186cadf6e3eef7fa8f35dec31b4313efabf77ebdccd74b09998d0296ae01c90
                  Version: 40.20240807.0 (2024-08-07T07:31:06Z)
          LayeredPackages: gnome-themes-extra gtk-murrine-engine openrazer-meta razergenie
                           sassc
            LocalPackages: lact-libadwaita-0.5.5-0.x86_64
```

### Hardware

CPU: AMD Ryzen 9 5900X 3.7 GHz 12-Core Processor
Motherboard: Gigabyte X570S AORUS MASTER ATX AM4 Motherboard 
Memory: G.Skill Trident Z Neo 32 GB (2 x 16 GB) DDR4-3600 CL16 Memory
Video Card: XFX Speedster MERC 319 Black Radeon RX 6900 XT 16 GB Video Card 
Power Supply: SeaSonic PRIME 850 W 80+ Gold Certified Fully Modular ATX Power Supply
Monitor: LG 34GP83A-B 34.0" 3440 x 1440 144 Hz Curved Monitor
Monitor: LG 29UM67P 29.0" 2560 x 1080 60 Hz Monitor

**Comment by VHSJayden** [comment]
I wanted to troubleshoot deeper and installed Fedora GNOME on an extra drive and it went to sleep without any issues.It seems like something on Bazzite that is causing these issues.

**Comment by KyleGospo** [comment]
> I wanted to troubleshoot deeper and installed Fedora GNOME on an extra drive and it went to sleep without any issues.It seems like something on Bazzite that is causing these issues. 

I'm not able to reproduce, we will need a log to investigate this any further.

**Comment by VHSJayden** [comment]
> > I wanted to troubleshoot deeper and installed Fedora GNOME on an extra drive and it went to sleep without any issues.It seems like something on Bazzite that is causing these issues.
> 
> I'm not able to reproduce, we will need a log to investigate this any further.

Sure thing! How do I produce a log to send you? Do I need to send a log right after my monitors wake up from sleep?

**Comment by VHSJayden** [comment]
Also, it looks like the KDE spin doesn't have this issue, so the GNOME spin is the only one that does this for some reason.
