### ISSUE TITLE
Resolution changes in chrome browser after exiting a fullscreen video and everything is tiny.

### ISSUE THREAD

**Issue by Globetrotter129** [ublue-os/bazzite#1493]
It spoils an otherwise streamlined experience.

**Comment by noelmiller** [comment]
We need a bit more information in order for us to assist. 

Could you provide the following: 
1. A screenshot of what you are seeing
2. What is the process you use step by step to replicate this issue? 
3. Could you provide a link to your hardware by using the command: 
`ujust device-info`
4. How are you installing Chrome? Are you using the flatpak, distrobox, or RPM?

**Comment by romeow98** [comment]
hello @noelmiller 

i'm having an issue with Google Chrome with in Bazzite, 
here's the link to my hardware https://paste.centos.org/view/d311fca3

when you look at the screen shot, when i go into full screen, the top portion of the screen remains blank, but thats where the tabs are still places, even though they show below where the address bar is. 

![Image](https://github.com/user-attachments/assets/bab28945-00ce-41ad-a550-605e38f5f227)

**Comment by romeow98** [comment]
> hello [@noelmiller](https://github.com/noelmiller)
> 
> i'm having an issue with Google Chrome with in Bazzite, here's the link to my hardware https://paste.centos.org/view/d311fca3
> 
> when you look at the screen shot, when i go into full screen, the top portion of the screen remains blank, but thats where the tabs are still places, even though they show below where the address bar is.
> 
> ![Image](https://github.com/user-attachments/assets/bab28945-00ce-41ad-a550-605e38f5f227)

looks like this is a setting in KDE --- found the solution here 

https://forum.kde.org/full-screen-kde-4-2-apps-on-opening-t-22891.html

check systemsettings (aka configure desktop) -> window behavior -> advanced -> placement and see if it's set to maxamizing

when i checked here i found my placement was set to Centered, and not Maxamizing,
