### ISSUE TITLE
whats the error 1 in installation 

### ISSUE THREAD

**Issue by SAJAD1243** [ublue-os/bazzite#1498]
### Describe the bug

i need help

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

**Comment by HikariKnight** [comment]
Generic anaconda error that we do not control, please refer to documentation for troubleshooting during install as this has already been covered there with a video tutorial
https://universal-blue.discourse.group/docs?topic=2495
