### ISSUE TITLE
Aya Neo Next home and quick access buttons aren't mapped

### ISSUE THREAD

**Issue by tioalexis** [ublue-os/bazzite#1502]
### Describe the bug

Aya Neo Next has 2 buttons on the bottom right and neither of them works. In other distros (like chimeraos), only one of them works so I guess there's some hardware limitations but at least one of them worked as the home button. In Bazzite, neither of them works so I have no way of getting to the home screen in the middle of a game.

### What did you expect to happen?

The big button is mapped to the home screen. The small button is mapped to the quick access menu

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
ostree-image-signed:docker://ghct.io/ublue-os/bazzite-deck:stable
Digest: sha256:6ce12036986eb
Version: v3.6-40.20240809.0 (2024-08-09T21:14:34Z)
```

### Hardware

NEXT

**Comment by aarron-lee** [comment]
sounds like you should open an issue on the HHD github: https://github.com/hhd-dev/hhd

hhd is the software used to handle controllers on non-deck PC handhelds, it sounds like there needs to be some dev work for the Ayaneo Next
