### ISSUE TITLE
Auto swapping to testing build

### ISSUE THREAD

**Issue by ArnauS197** [ublue-os/bazzite#1507]
### Describe the bug

Every time I boot my Bazzite it shows I have an update becasuse is in the testing builds, I don't know why but every time I reboot it turns back to testing, it's so tedious...

### What did you expect to happen?

Just stay to stable builds.

**Comment by nicknamenamenick** [comment]
Give the output of `rpm-ostree status` in the terminal in Desktop Mode and paste it here.
