### ISSUE TITLE
Left speaker audio stops working randomly 

### ISSUE THREAD

**Issue by LianDLT** [ublue-os/bazzite#1511]
### Describe the bug

I have Bazzite OS installed on Rog Ally Z1 Extreme. When the device is turned on, restarted or wake from sleep there's a chance the left speaker stops working, sometimes it fixes itself sometimes a full restart is needed but it's been a constant issue. Family 17h/19h HD Audio Controller is selected as that's the only option there is 

### What did you expect to happen?

I expected both speakers to work properly

**Comment by Sickosicko** [comment]
This is hardware issue. I had this problem myself for months, i fixed it by reseating my speaker cable.
The cable port is under the fan, on the right side of the APU.

**Comment by Sickosicko** [comment]
It happened for me on any OS.

**Comment by Sickosicko** [comment]
Also I added some kapton tape on the metal driver on the back of speaker. Make sure it does not have contact to battery.

There is a reddit post about this: https://www.reddit.com/r/ROGAlly/comments/1bibm7d/comment/kw4uypi/

**Comment by arcathrax** [comment]
i've got this issue too

**Comment by arcathrax** [comment]
Nevermind, i just updated my ally and everything works perfectly again.

**Comment by hayschan** [comment]
I got the right speaker issue of my ROG Ally with Bazzite OS installed. The right speaker has no sound at all. All the sound comes from left speaker.
