### ISSUE TITLE
Decky loader not loading

### ISSUE THREAD

**Issue by RickS-C137** [ublue-os/bazzite#1517]
### Describe the bug

I've installed Decky Loader via ujust decky-setup install. The script execution was successful, but Decky Loader is not starting then the Steam Deck is booted.

### What did you expect to happen?

The Steam Deck boots into Game Mode and Decky loader is started.

### Output of `rpm-ostree status`

```shell
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:4b6720ea6c3c7c3436af0dda75858ca87982abd528b1667bdfbe4a28ebdac9b1
                  Version: v3.6-40.20240815.0 (2024-08-15T15:51:01Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:4b6720ea6c3c7c3436af0dda75858ca87982abd528b1667bdfbe4a28ebdac9b1
                  Version: v3.6-40.20240815.0 (2024-08-15T15:51:01Z)
```

### Hardware

Galileo - Steam Deck OLED

**Comment by norahqueen** [comment]
I think this might be affecting existing installations of Decky Loader as well. I'm missing the plugins tab from the QAM. But my custom CSS loads properly, so I think Decky is installed, it's just glitching and not displaying?

**Comment by norahqueen** [comment]
Okay, I've fixed it appearing in QAM. It seems to be a regression/breaking change introduced in the most recent release in the beta Steam Deck Client Channel. I reverted to Stable and decky loader is working and appearing properly.

**Comment by RickS-C137** [comment]
Yeah, I managed to fix it by switching to the latest pre-release of Decky Loader, just didn't have time to report it here. Thx for reminding me :)
