### ISSUE TITLE
Game Mode: Lower contrast when pointer is visible at 4K resolution

### ISSUE THREAD

**Issue by AkazaRenn** [ublue-os/bazzite#1520]
### Describe the bug

In Game Mode, when the pointer (cursor) is visible, the screen seems to have lower contrast. Seems only happening in 4K resolution. If I start the game in 1440P it works normally.
Here's the recording I made with a capture card (please ignore the audio):
https://github.com/user-attachments/assets/faa679e4-d9c4-4034-8af8-245e64944e93

Related: https://github.com/ValveSoftware/gamescope/issues/1485

### What did you expect to happen?

The image should keep consistent whether the pointer is visible or not. According to my experience, when the pointer disappears the image seems to be the correct one.

### Hardware

CPU: AMD Ryzen 7800X3D
GPU: AMD Radeon 6950XT
MB: Gigabyte B650 Elite AX
Display: 4K120Hz WOLED TV hooked with AVerMedia Live Gamer Ultra 2.1 capture card

### Extra information or context

1. It seems only happen in Game Mode, starting the same game in desktop mode doesn't have that issue, even if I've enabled "hiding cursor when inactive" in the settings
2. The games I tested were: _The Legend of Zelda: Tears of the Kingdom_ (Ryujinx), _Final Fantasy XIV Online_ (XIVLauncher), _Overwatch 2_ (Steam), they cover both Steam and non-Steam games and all have this issue, even including the Steam BPM itself
3. I've tested turning on/off the following and none had fixed the issue: HDR, VRR, performance overlay, game recording, scaling, half rate shading, 120Hz<->60Hz

**Comment by AkazaRenn** [comment]
Steam issue

**Comment by ggppjj** [comment]
Is there more info available? I am also seeing this in game mode on Bazzite on an unlocked deck with normal resolutions, but I wasn't seeing it on SteamOS.

**Comment by AkazaRenn** [comment]
@ggppjj https://github.com/ValveSoftware/gamescope/issues/1485 here's some discussion for your reference. I couldn't see it on my Steam Deck either now, it could be a Bazzite-specific issue?

**Comment by ggppjj** [comment]
Thank you for checking and reopening, I got as far as unsuccessfully trying to mess with the game-mode-plus script (if I recall the name correctly) before I had to give up on finding it myself.

**Comment by KyleGospo** [comment]
Tonight's update should resolve this

**Comment by ggppjj** [comment]
Exciting news, thank you for the update! I'm personally curious to learn what was causing the issue, if you have a commit link handy.

Thanks again either way!
