### ISSUE TITLE
Administrator user is not created during installation if nonexisting usergroup is configured

### ISSUE THREAD

**Issue by ExperimentalCyborg** [ublue-os/bazzite#1522]
### Describe the bug

If during the graphical installation setup you modify the default administrator user configuration to include mistyped or nonexistent user groups, it silently fails to create the user account during the installation process. After installation, it will be impossible to log in, since there is no user account with a configured password.

### What did you expect to happen?

I expected it to either create the user anyway but omit the invalid groups, or to warn me during the installation process and allow me to make changes to the configuration and try again.

### Output of `rpm-ostree status`

```shell
I can't log in :)
```

### Hardware

x86-64 AMD desktop

### Extra information or context

I added the dialout group (because i'd like to access usb COM ports) but apparently it does not exist by default.

**Comment by KyleGospo** [comment]
Unfortunately this will need to be fixed upstream, we just consume anaconda from the fedora project and otherwise don't change it unless absolutely necessary. There's a chance that this will improve in the future with the new UI that's in development.

**Comment by Siress** [comment]
Still relevant.... just encountered this and need to reinstall.
