### ISSUE TITLE
Legion Go: Launching SMT V causes system lock-up

### ISSUE THREAD

**Issue by RoundedMecha** [ublue-os/bazzite#1523]
### Describe the bug

After updating i was no longer able to boot up SMT V. The game will begin to launch like normal but will then go black and the system becomes completly unresponsive requiring a restart. Currently the game works completly fine on 'stable-40-20240809'.

### What did you expect to happen?

The game would launch and play like previously instead of locking up the system.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:aeeadaec946e4c32d803ef987db326cceb9e4702340f8950b5d28c4d7344084b
                  Version: v3.6-40.20240819.0 (2024-08-19T05:04:16Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:6ce12036986eb6b37658dac3d335ce826106cf46a628516be96bf966bc8f6cbf
                  Version: v3.6-40.20240809.0 (2024-08-09T21:14:34Z)
```

### Hardware

Legion Go-83E1

**Comment by KyleGospo** [comment]
Set your UMA buffer to 4GB in the BIOS.

**Comment by RoundedMecha** [comment]
That does seem to have solved the issue.

**Comment by KyleGospo** [comment]
Resolved in latest
