### ISSUE TITLE
Cyberpunk 2077 crashing shortly after launch in gamemode

### ISSUE THREAD

**Issue by Chris33333333333333333** [ublue-os/bazzite#1526]
### Describe the bug

The initial part of the issue was my mistake: I left Cyberpunk 2077 running while putting my Legion Go in the travelcase. The Legion Go shut itself down, probably due to overheating.

After this, I couldn't get Cyberpunk to work anymore in gamemode. Each time it would start, I would get into the CD:PR launcher, but from pressing play it would cut out after about a second, the display would first go black (i.e. turned off) and after a few seconds would turn on but be entirely grey. After about a minute the device would subsequently reboot.

Other games did work, reaching as much as 120fps in older games like Saints Row 4. No problem with performance or anything, but Cyberpunk kept crashing. In desktop mode it would work, but the performance was quite sluggish. 

### What did you expect to happen?

I expected the game to start as it had been doing every time I launched prior to this situation.

### Hardware

Lenovo Legion Go

### Extra information or context

I've tried about everything I could think of. I've reinstalled Bazzite several times. I've reinstalled Cyberpunk several times. I've deleted the game files and used verify to have as clean an install as possible. I've reinstalled the game with cloud-saves turned off. I've changed the download-location in Steam, so as to download from other countries. I've deleted local saves, many a settings file, and any steam-related caches I could find. I've even repeated pretty much all these steps in one final attempt to get it to work, but even after this, the game would still crash upon launching. 

A post about this on Reddit revealed at least one other person had a very similar issue on the Asus ROG Ally X https://www.reddit.com/r/Bazzite/comments/1ev80hw/cyberpunk_always_crashes_in_game_mode_even_after/
<img width="781" alt="Screenshot 2024-08-21 at 23 15 44" src="https://github.com/user-attachments/assets/2e3b9658-763d-48e7-ba58-39cc9e4ac17a">

Update: the game does work in game mode in Nobara, which seems very very similar to Bazzite. It's almost as if Cyberpunk or Steam recognises I'm trying to play on Bazzite and refuses to function, while being willing to work properly when the OS name changes :)

**Comment by KyleGospo** [comment]
Resolved in latest
