### ISSUE TITLE
Cursor Stuttering on latest version (bazzite-gnome:stable) with VRR Enabled

### ISSUE THREAD

**Issue by MattyPixels** [ublue-os/bazzite#1529]
### Describe the bug

When playing any game with GNOME VRR enabled, the cursor will stutter. I don't notice any CPU or GPU spikes.

Judging from [this](https://universal-blue.discourse.group/t/bazzite-stuttering-frequently/) post on Discourse, I'm not alone. My partner's machine also has this issue.

Note that rebasing to `40.20240807.0` completely fixed this issue, so this seems to have been introduced on version `40.20240800.0`.

### What did you expect to happen?

Cursor should not stutter in fullscreen games, nor should the games freeze.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:ca0a0e0cca1a64d92f8cad0a72d192b0127657fd81f9cf7e0014c6129daa9f2f
                  Version: v3.6-40.20240819.1 (2024-08-19T04:57:20Z)
          LayeredPackages: gparted openrgb
            LocalPackages: lact-libadwaita-0.5.5-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:a5205aedb8928a6a8cc46fdf6de2e5af69c6a1f70a682fb6c43b40109ff2c7ef
                  Version: v3.6-40.20240815.0 (2024-08-15T15:47:04Z)
          LayeredPackages: gparted openrgb
            LocalPackages: lact-libadwaita-0.5.5-0.x86_64
```

### Hardware

Specs:
- CPU: AMD Ryzen 7 7800X3D
- GPU: AMD RX 7800 XT
- RAM: 32 GB 6400 MHz
- 100 Hz screen (partner's is 170 Hz) with AMD FreeSync
- `bazzite-gnome:latest` image

**Comment by jameskimmel** [comment]
I can reproduce something I believe is the same issue. 

As soon as I enable adaptive sync (Asus TUF Gaming VG27A, Freesync and GSync compatible) in the systems menu, my mouse begins to stutter. And it is not just the mouse, also scrolling in Firefox for example. 

GPU is a 4060Ti. Bazzite 42 NVIDIA edition

**Comment by mimiteru** [comment]
> Update: I think I might have found a solution. I added `MUTTER_DEBUG_FORCE_KMS_MODE=simple` in `/etc/environment`, logged off and the cursor doesn't lag in games with VRR enabled anymore.

Please add this to the Issues & Resolution - Bazzite Documentation. I searched for days looking for a solution to the constant latency in games, low network speeds, and constant frame stuttering. This did the trick.
