### ISSUE TITLE
Waydroid loses memory every new launch

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1536]
### Describe the bug

When starting waydroid after reboot, every app loses memory and i have to log in to google every time. This doesn't happen in any other distro when using waydroid.

### What did you expect to happen?

Waydroid remembering that i logged in

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:d7e04c554c11f1cea8426aca5d481341b46f5c3ee81e1dd3dc93ada82d3947a3
                  Version: 40.20240822.0 (2024-08-23T04:09:31Z)
          LayeredPackages: hunspell-pl sg3_utils

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:1be0a2b464832afbd7d7555889c006577ee12e61addb6e9fcd5ca91aa0f6839a
                  Version: 40.20240820.0 (2024-08-21T05:02:26Z)
          LayeredPackages: hunspell-pl sg3_utils
```

### Hardware

Galileo
Steam Deck OLED

**Comment by KyleGospo** [comment]
Unable to reproduce

**Comment by unicornsandcandies** [comment]
> Unable to reproduce. Local installs have kept memory and a new install in a VM functions as expected.

What can I do to find out what the issue is? Are there any logs?

**Comment by KyleGospo** [comment]
`waydroid log`
