### ISSUE TITLE
Screen blurring when mouse is visible ingame

### ISSUE THREAD

**Issue by Sterophonick** [ublue-os/bazzite#1539]
### Describe the bug

The image in Gamescope will become blurred if the mouse is visible. Easiest to see when running at native resolution. The issue does not present itself in screenshots. Could possibly happen when docked? I've only ever seen it in handheld.

### What did you expect to happen?

Screen must remain clear

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:a1efbabfe42e9612b3cc79053a01de892a0dfd9892a3c8f2162e44449c4c98b8
                  Version: 40.20240822.0 (2024-08-23T04:11:09Z)
                 Unlocked: development

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:19aac4b0a8c4437bece477d74a48439fa1e30b2a20e4702cb9cd38ddc488385f
                  Version: 40.20240821.0 (2024-08-22T05:49:24Z)
```

### Hardware

Galileo

### Steps to reproduce
This only works in games that use the system mouse (ex: Minecraft) rather than games that make their own mouse (ex: DOOM Eternal).
Simply just get into a state where the mouse would be visible.

### Pictures
<img src="https://github.com/user-attachments/assets/b948ff40-5fa0-4556-a41f-adfa45cd36f4" alt="Correct Pixels" width="400"/>
<img src="https://github.com/user-attachments/assets/796755bc-c3d1-4a13-8326-2c6480d29cc3" alt="Blurry Pixels" width=400/><br/>
Left: Correct behavior; Right: Blurry image

**Comment by Sterophonick** [comment]
been screwing with Gamescope for a minute, cannot seem to reproduce with my own builds. Potentially an issue with clang?

**Comment by Sterophonick** [comment]
Built from `.spec` again, and forcing it to GCC fixed the issue.

**Comment by Linus-XZX** [comment]
Forwarding some info from Discord discussions (https://discord.com/channels/1072614816579063828/1270815042119405678):

- The blur is caused by the ‘composite’ rendering in Gamescope, and can be made persistent regardless of mouse presence with the ‘force composite’ option (requires developer mode).
- Last known version without the blur seems to be 20240804, and some versions between there and the current stable seem to also see performance losses.

**Comment by KyleGospo** [comment]
Should be fixed in next update

**Comment by Linus-XZX** [comment]
Can confirm that issue is resolved on current stable.
