### ISSUE TITLE
Tell me why the system is not updated?

### ISSUE THREAD

**Issue by aelev** [ublue-os/bazzite#1541]
### Describe the bug

The system stopped updating a long time ago, I don’t know why.

### What did you expect to happen?

Update 

### Hardware

7800x3d +7900xt+32gb

### Extra information or context

[file 1 of 2 63 State.md](https://github.com/user-attachments/files/16741922/file.1.of.2.63.State.md)

**Comment by KyleGospo** [comment]
Give me the output of `rpm-ostree update`

**Comment by aelev** [comment]
Sorry, could you tell me how to get the output?

**Comment by BrodyB** [comment]
Open up Ptyxis / terminal, and type in `rpm-ostree update` and copy the text here. Could also be useful to see what it spits out when you enter `rpm-ostree status`.

**Comment by aelev** [comment]
I tried but a message appears that such a command was not found. Then I type "ujust update" and it outputs the following message:

── 00:45:37 - System update ────────────────────────────────────────────────────
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: cryptographic signature verification failed: invalid signature when validating ASN.1 encoded signature
System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:273
Retry? (y)es/(N)o/(s)hell/(q)uitERROR Error reading from terminal: read interrupted

**Comment by aelev** [comment]
![image](https://github.com/user-attachments/assets/87ea589e-f4f3-4529-b537-102b47a435a7)

**Comment by KyleGospo** [comment]
https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689

**Comment by aelev** [comment]
Thank you! This helped.
