### ISSUE TITLE
Antec Core HS screen orientation is wrong

### ISSUE THREAD

**Issue by clairearmstrong** [ublue-os/bazzite#1554]
### Describe the bug

I am trying to install Bazzite on my Antec Core HS as a dual boot on a Windows 11 partition but the screen is in the wrong orientation and cuts off part of the display
![IMG_4791](https://github.com/user-attachments/assets/608fee87-c469-465a-9119-f55e82dc8159)

### What did you expect to happen?

I expected the screen to be landscape and scaled to fit my screen

### Hardware

Antec Core HS

### Extra information or context

I previously completed the installation but was unable to change the display settings. I tried installing Fedora Kinoite instead but ran into errors so am resetting Windows on my device, therefore I can't run rpm-ostree status. In the download Bazzite screen I chose other handheld PC -> KDE

**Comment by KyleGospo** [comment]
Under hardware, is that the DMI name from the command in our issue template?

**Comment by clairearmstrong** [comment]
The DMI name is SLIDE
I was able to get it working this time and changed the settings to get the correct orientation.
In Steam there are no buttons mapped to the Xbox buttons Home and Share - should I contact Handheld Daemon about that?

**Comment by clairearmstrong** [comment]
![IMG_4805](https://github.com/user-attachments/assets/16496e25-7cfe-49c2-b5ce-941a316f08f3)

**Comment by clairearmstrong** [comment]
Hello,

I'm no longer using bazzite on my device so I can't confirm if it's still
relevant.

Thanks
Claire

**Comment by moyitpro** [comment]
I have an Antec Core HS and have to close an install of Bazitte to the internal SSD to make it work. 

To fix the screen orientation issue, you need to run:

rpm-ostree kargs --append-if-missing=video=eDP-1:panel_orientation=left_side_up

(from the Ayaneo guide from the Bazitte wiki, but it needs to be left as right_side_up have the screen upside down.
