### ISSUE TITLE
VRR still broken after new release on ROG Ally non X

### ISSUE THREAD

**Issue by Sickosicko** [ublue-os/bazzite#1569]
### Describe the bug

Same frametime issue, identical to before update

### What did you expect to happen?

Expected VRR to not have frametime issues

### Output of `rpm-ostree status`

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f70eae81ad4d8cadfd03eea4b11e9c0825206f483ed02a677af9cee023f1a972
                  Version: 40.20240828.0 (2024-08-29T00:21:44Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f70eae81ad4d8cadfd03eea4b11e9c0825206f483ed02a677af9cee023f1a972
                  Version: 40.20240828.0 (2024-08-29T00:21:44Z)

### Hardware

RoG Ally Z1 Extreme Non X

### Extra information or context

Only happens at around 60fps

**Comment by thienntm** [comment]
ally X here, same problem

**Comment by LianDLT** [comment]
Ally Z1 E, same thing. VRR stutters and disables any fps cap, a few weeks ago it was working, it capped the fps 3 or 4 fps above what you set (40 fps was 43-44) but at least it was working and there was no stuttering and bad frame pacing

**Comment by Sickosicko** [comment]
I just went with nobara tbh VRR is fixed on nobara.

**Comment by Sickosicko** [comment]
Hello. VRR is now working perfectly.

RPCS3 appimage broke all my game shortcuts though and cannot be remade. Need to launch RPCS3 from game mode.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
