### ISSUE TITLE
Steam seems broken after update

### ISSUE THREAD

**Issue by Sofia-Sailors** [ublue-os/bazzite#1573]
### Describe the bug

Updated system from Steam UI, restarted, and system was stuck on "logging in". I then tried to launch from desktop with application manager and command line.

### What did you expect to happen?

I expected steam to sign in like normal. I also expected that steam would launch, either by presenting the GUI or the icon in the task bar. Neither occurred.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f70eae81ad4d8cadfd03eea4b11e9c0825206f483ed02a677af9cee023f1a972
                  Version: 40.20240828.0 (2024-08-29T00:21:44Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f23de493b70d8900546a7f485a9110c75df9c8d7529626ce4580d557b7349587
                  Version: 40.20240826.0 (2024-08-27T06:59:55Z)
          LayeredPackages: sunshine
```

### Hardware

MOBO - Z790M-ITX WiFi
CPU - 12th Gen Intel(R) Core(TM) i5-12600K (16) @ 4.90 GHz
GPU - AMD Radeon RX 7600 XT [Discrete]
Ram - 6.98 GiB / 31.10 GiB (22%)

### Extra information or context

It was working fine earlier today, before I updated. I'm assuming that the issue is with my steam client, rather than with the OS, but if it's an issue that can happen to me, it can happen to others. Before this started i was having the same issues as [this person](https://github.com/ublue-os/bazzite/issues/1538), (but only on boot, not wake from suspend). I've had no major issues before this, and anything that I *have* come across before was quickly solved or not a big deal. This suck only because it's Steam.

**Comment by KyleGospo** [comment]
Steam servers are down, disable wifi/unplug ethernet and restart in the meantime.

**Comment by Linus-XZX** [comment]
Simply put, Steam server is currently down. Disabling Internet and restarting should allow you to get into the system, but it’s up to Steam in the end…

**Comment by KyleGospo** [comment]
Fixed by Valve. Note that this was not a Bazzite specific issue, even the steam deck was affected.
