### ISSUE TITLE
Firefox and Discover opens when switching to desktop mode.

### ISSUE THREAD

**Issue by TheAwesomeGcdm** [ublue-os/bazzite#1577]
### Describe the bug

Anytime I switch from game mode to desktop mode, the Discover store and Firefox open up full screen automatically. I check the start up options in the settings app, but it's empty. 

### What did you expect to happen?

When switching from game mode to desktop mode, I expected to get to the desktop and no apps to automatically run.

### Output of `rpm-ostree status`

```shell
gcdm@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:stable
                   Digest: sha256:df6dfe0093e8d14255a87cae26dcafc059547a0b3b0c65a6f579530f6423ba31
                  Version: 40.20240828.0 (2024-08-29T00:23:19Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:stable
                   Digest: sha256:ac5a75caadca6ce2ab93012e772ad3254f74280efdbf46a01cf6bcc762746900
                  Version: 40.20240821.0 (2024-08-22T05:49:51Z)
```

### Hardware

ROG Ally Extreme

**Comment by jardon** [comment]
Two things to check if you haven't already:
1. `Settings > Startup & Shutdown > Desktop Session > On login > Restore previous session` should be disabled
2. Check the contents of `~/.config/autostart` or `/etc/xdg/autostart`

Let us know if either of those are helpful!
