### ISSUE TITLE
GPD Win Mini 2024 SteamUI / Gamescope framerate limiter does not work

### ISSUE THREAD

**Issue by SimpleHeuristics** [ublue-os/bazzite#1578]
### Describe the bug

FPS Limiter set by steam UI does not limit the in game FPS based on what the performance monitoring tools are reading.

### What did you expect to happen?

Expected framerate to be limited to what is set in the UI

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f70eae81ad4d8cadfd03eea4b11e9c0825206f483ed02a677af9cee023f1a972
                  Version: 40.20240828.0 (2024-08-29T00:21:44Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f70eae81ad4d8cadfd03eea4b11e9c0825206f483ed02a677af9cee023f1a972
                  Version: 40.20240828.0 (2024-08-29T00:21:44Z)
```

### Hardware

G1617-01

**Comment by antheas** [comment]
Yes, the limiter is broken when VRR is on unfortunately. You need to use another means to set the framerate limit for now.

**Comment by antheas** [comment]
@KyleGospo close as completed and remove dosubot
