### ISSUE TITLE
Acpi error

### ISSUE THREAD

**Issue by ghost** [ublue-os/bazzite#1608]
### Describe the bug

Hello, when running the journalctl -p err, journalctl -b command, some errors appear, such as:

set 03 13:04:29 bazzite kernel: ENERGY_PERF_BIAS: Set to 'normal', was 'performance'

set 03 13:04:28 bazzite kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0], AE_NOT_FOUND (20230628/dswload2-162)
set 03 13:04:28 bazzite kernel: ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20230628/psobject-220)
set 03 13:04:28 bazzite kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PC00.DGPV], AE_NOT_FOUND (20230628/psargs-330)
set 03 13:04:28 bazzite kernel: ACPI Error: Aborting method \_SB.PC00.PEG0.PCRP._ON due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
set 03 13:04:29 bazzite kernel: integrity: Problem loading X.509 certificate -65
set 03 13:04:28 bazzite kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0], AE_NOT_FOUND (20230628/dswload2-162)
set 03 13:04:28 bazzite kernel: ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20230628/psobject-220)
set 03 13:04:28 bazzite kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PC00.DGPV], AE_NOT_FOUND (20230628/psargs-330)
set 03 13:04:28 bazzite kernel: ACPI Error: Aborting method \_SB.PC00.PEG0.PCRP._ON due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
set 03 13:04:29 bazzite kernel: integrity: Problem loading X.509 certificate -65

set 03 16:04:34 bazzite kernel: legion PNP0C09:00: probe with driver legion failed with error -12

set 03 16:04:34 bazzite kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_TZ.ETMD], AE_NOT_FOUND (20230628/psargs-330)
set 03 16:04:34 bazzite kernel: ACPI Error: Aborting method \_SB.IETM._OSC due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
set 03 16:04:36 bazzite kernel: i801_smbus 0000:00:1f.4: Transaction timeout
set 03 16:04:36 bazzite kernel: i801_smbus 0000:00:1f.4: Failed terminating the transaction
set 03 16:04:36 bazzite kernel: i801_smbus 0000:00:1f.4: SMBus is busy, can't use it!
set 03 16:04:40 bazzite kernel: Bluetooth: hci0: Malformed MSFT vendor event: 0x02

### What did you expect to happen?

Distro compatibility with my laptop, so that acpi errors and other errors no longer exist.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:e282521ee0e418a11ae423d8cfd9c83893545c9dd2e4e7226fda1dc8f1389e6c
                  Version: 40.20240901.1 (2024-09-02T21:12:18Z)
          LayeredPackages: chromium elisa-player libreoffice vlc wine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:688da1a245efc6fdae27743964c8f5ebe380f057064844c7066d3f851e92651c
                  Version: 40.20240901.0 (2024-09-02T05:05:54Z)
          LayeredPackages: chromium elisa-player libreoffice vlc wine
```

### Hardware

Laptop Lenovo Ideapad 3 15itl6 82md
1920x1080p 60hz 
Intel i3 1115G4 
Ram 8gb (4gb soldered + soddim 4gb) 
Abnt2, ptbr utf8

### Extra information or context

I believe the bug is happening because of something missing in the kernel, which is being looked for at boot and cannot be found.

But I don't understand it in depth, I'm a common user 😄. 
But I wanted to leave this feedback to help with the optimization and compatibility of the distro.

👍

**Comment by Haxorzz** [comment]
This doesn't seem distro related. Have you tested in other distros? ACPI errors are pretty common and are often completely unimportant to the function of the computer (ACPI maps on devices are filled with tons of stuff, super buggy and a lot of it doesn't work outside Windows)
