### ISSUE TITLE
fresh install doesn't start in gaming mode 

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#1609]
### Describe the bug

I have the fresh bazzite install. The os doesn't start in gaming mode and there's no way to switch to the gaming mode either. It just blinks and returns to the desktop

### What did you expect to happen?

Os to start in gaming mode 

### Hardware

Steam deck OLED
Galileo

**Comment by KyleGospo** [comment]
That would be a crash either in Gamescope or in Steam. In your home directory there should be a log as a hidden file, if you could add that here that might help.

Make sure that steam is also starting properly in the desktop.
