### ISSUE TITLE
HDDs and flash storage (SDcard / eMMC) should have BFQ as scheduler, not Kyber

### ISSUE THREAD

**Issue by ahydronous** [ublue-os/bazzite#1611]
### Describe the bug

Currently, Kyber is set as the scheduler for all storage devices

### What did you expect to happen?

BFQ should be set as the scheduler for slow storage devices because it improves performance

### Extra information or context

As per this discussion in PopOS:
https://github.com/pop-os/default-settings/pull/149

PopOS commit: https://github.com/pop-os/default-settings/commit/0636b6cb94a0d267387caa0b4f9370ce7e82640c

**Comment by KyleGospo** [comment]
![image](https://github.com/user-attachments/assets/8b6e13d1-9ab5-40f0-beae-2b54fdcf77b0)

**Comment by KyleGospo** [comment]
HDD should be bfq, would need a good way to separately mark MicroSDs if we want to go with bfq there too.
