### ISSUE TITLE
Legion Go: controller inputs are lost by games but not steam

### ISSUE THREAD

**Issue by mvasl** [ublue-os/bazzite#1618]
### Describe the bug

When controllers state (attached/detached) is changing, games tend to lose gamepad input completely, but not steam (mouse or "FPS" mode still works in game). Also, this happens when powering up from sleep sometimes, bug seems to occur randomly. The only way to get the game to recognize controller again is to restart it.

I do not believe this is related to the specific game, but rather a steam input or os-level problem as this happens an all games I play on my lgo, I've seen this happening to Baldur's Gate 3, GTA IV, Pillars Of Eternity, It Takes Two and MGS 3 remaster.

There was no such issue before at least 3.5

### What did you expect to happen?

Controllers working after attaching/detaching them.

### Output of `rpm-ostree status`

```shell
deck@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:3b2db0c90cbce46515defce9eab4a1cc34f306d2ad7ffe715e077f770f187385
                  Version: 40.20240901.1 (2024-09-02T21:14:31Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:f133e37b4a780e72346f02b073ce877da6cd9334e8ffd4dc6144d39be54bc075
                  Version: 40.20240901.0 (2024-09-02T05:08:02Z)
```

### Hardware

Legion Go
```
deck@bazzite:~$ cat /sys/devices/virtual/dmi/id/product_name
83E1
```

**Comment by KyleGospo** [comment]
Try changing your controller type to Dual sense Edge in HHD. If that fixes it for you, this will be fixed in the next update.

**Comment by mvasl** [comment]
It already is in ds edge mode

**Comment by KyleGospo** [comment]
@antheas

**Comment by antheas** [comment]
This was a bug on the Xbox controller that is fixed in the upcoming version of Bazzite. It was not a bug on the dualsense controller.

When you detach the controllers, you have around 20 seconds to detach both of them in which the old emulated controller will remain alive. After that, the old controller is destroyed.

Games on linux break when you disconnect a controller and that is unfortunately something I cannot fix. It is something that @KyleGospo  or Valve would need to look into. As the same games that work on Windows break on Steam.

This little caching fix is the best I could do. If you still keep seeing the emulated dualsense controller once you detach the controllers it means it is working. I just tested it now and it works on my legion go. This is the same fix that works when you suspend the device.

**Comment by mvasl** [comment]
It might be the case with crashing. In some of this cases I noticed that controllers rgb is reset to white for a second and then restored as if they are reconfigured an the fly.

**Comment by antheas** [comment]
Steam sets dualsense controllers to white for 1 second when it sees a new controller 

I will look into this. For the time being I will note that if you're perhaps a bit faster it will work better

Also grab a log with `journalctl -b 0 | fpaste` after detaching the controllers and it fails

**Comment by mvasl** [comment]
If under me being faster you mean detach controllers faster, then it is not really possible, I detach them both at the same time with both hands usually. I will reproduce this and grab a log today.

**Comment by antheas** [comment]
Maybe it's too fast then. I usually do 1 at a time and never did both at the same time

**Comment by mvasl** [comment]
Got the logs
https://paste.centos.org/view/95e69b3e

**Comment by antheas** [comment]
Seems like for most of the disconnections controller if not all caching worked?

**Comment by mvasl** [comment]
This looks like it could be related
```
сен 08 10:23:30 bazzite kernel: usb 1-3: USB disconnect, device number 13 сен 08 10:23:30 bazzite kernel: xpad 1-3:1.0: xpad_try_sending_next_out_packet - usb_submit_urb failed with result -19 сен 08 10:23:30 bazzite hhd[4685]: LLGO WARNING Caching Dualsense controller to avoid reconnection. сен 08 10:23:30 bazzite hhd[4685]: LLGO ERROR Error while closing device сен 08 10:23:30 bazzite hhd[4685]: '<hhd.device.legion_go.base.SelectivePassthrough object at сен 08 10:23:30 bazzite hhd[4685]: 0x7f58a1e6e660>' with exception: сен 08 10:23:30 bazzite hhd[4685]: No such device сен 08 10:23:30 bazzite hhd[4685]: LLGO ERROR Received the following error: сен 08 10:23:30 bazzite hhd[4685]: <class 'OSError'>: [Errno 19] No such device сен 08 10:23:30 bazzite hhd[4685]: LLGO ERROR Assuming controllers disconnected, restarting after 0.5s
```

**Comment by mvasl** [comment]
Caching should have been working, steam was still recognising inputs as DS Edge, but game lost it after the last disconnect

**Comment by antheas** [comment]
Theres a failover safety that will throw away the controller if two errors happen in a row with no delay inbetween.

Perhaps it needs to be 3 or 4 errors. I will look into it.

Can you give me a % of how often this happens?

**Comment by mvasl** [comment]
I would say 1 out of three times. Maybe 1 to 5.

**Comment by mvasl** [comment]
The issue seems to be resolved with latest stable bazzite
