### ISSUE TITLE
Steam renders glitchy and small

### ISSUE THREAD

**Issue by AnityEx** [ublue-os/bazzite#1628]
### Describe the bug

here
![image](https://github.com/user-attachments/assets/6043f1dc-1780-4ac0-8e21-3cc3cdf37580) sometimes it just looks like that,
my laptop is a asus g14 ga402xv and i installed the asus nvidia bazzite, my screen is also very high dpi for its size so steam  is also small, it doesnt render correctly it only did it once while i was disabling gpu rendering and never again

### What did you expect to happen?

i expected steam to use the 180% screen scaling all the windows already use

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-asus-nvidia:stable
                   Digest: sha256:8d4e90fab4fd9f5a8bf1259d4709f0565da7121629144c3ee368df2dac2cabcc
                  Version: 40.20240901.1 (2024-09-02T21:13:48Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-asus-nvidia:stable
                   Digest: sha256:891245914daf2a37cd9abd4be24ca3cb3171e326592a9b18f180a38b8d6084d1
                  Version: 40.20240828.0 (2024-08-29T00:22:44Z)
```

### Hardware

GA402XV g14 with 4060 nvidia graphics 

### Extra information or context

i also tried edit app and adding some env variables but none work and for some reason anytime i try to change those again they do not save anymore it just says GDK_SCALE=2

**Comment by koloved** [comment]
can you try to use steam beta version? some days ago they made fx for nvda

**Comment by Haxorzz** [comment]
Yeah this seems like an esync nvidia bug, probably specific to steam (and firefox < 130)
