### ISSUE TITLE
OneXFly: Home, Turbo and Keyboard buttons do not work?

### ISSUE THREAD

**Issue by Gadg8eer** [ublue-os/bazzite#1635]
### Describe the bug

The Home button does nothing. The Turbo button does nothing. The Virtual Keyboard button does nothing.

### What did you expect to happen?

The Home button should open the steam menu in Gaming Mode and open the application list if in Desktop Mode. The keyboard  button should open a virtual keyboard regardlesss of mode. The turbo button is a bit less obvious, I think it brought up a proprietary software in Windows 11 on the OneXFly to create or use macro commands but I'd prefer to just reassign it at will to whatever I might need it for.

### Hardware

OG OneXPlayer F1 (also known as the OneXFly) with no modifications from stock hardware.

### Extra information or context

The speakers work on the OneXFly now after upgrading the bios, but I want to stick with Bazzite because ChimeraOS encountered severe issues when I renamed the system (issues that are not present with Bazzite at all, so thank you) and Bazzite seems closer to usability (if that changes I can always switch so yeah).

With almost everything else working, it's extremely cumbersome to be unable to use three of the specialized buttons on the device. Especially the Home Button, which is equivalent to a recent Xbox Controller's "Xbox" button or the Steam Deck's Steam Menu button.

**Comment by KyleGospo** [comment]
@antheas

**Comment by antheas** [comment]
I don't think you ever added any onexplayer ids to bazzite 

To save you the trouble just enable hhd for all onexplayer devices

**Comment by KyleGospo** [comment]
Just pinging in case those extra buttons need your support. A keyboard button sounds like something new and unique. 

For now, please run systemctl enable --now hhd@yourusername

**Comment by antheas** [comment]
Turbo button needs a kernel patch.

Other two buttons should work. I don't have the onexplayer dmi either

**Comment by Gadg8eer** [comment]
@KyleGospo 

`P10-ADMIN@P10-KiDSPLaYER:~$ cat /sys/devices/virtual/dmi/id/product_name
ONEXPLAYER F1`

Like this?

**Comment by KarkanAlzwayed** [comment]
I have just tried the systemctl enable --now hhd@yourusername command and I now have the home and "..." steam right side menu working on my onexplayer amd.
Operating System: Bazzite 41
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.9.0
Qt Version: 6.8.1
Kernel Version: 6.12.6-203.bazzite.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700U with Radeon Graphics
Memory: 12.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: ONE-NETBOOK TECHNOLOGY CO., LTD.
Product Name: ONE XPLAYER

**Comment by antheas** [comment]
Your onexplayer device is one of the first ones that had a different manufacturer name. So I guess the autoenable script does not have that yet

**Comment by KarkanAlzwayed** [comment]
> Your onexplayer device is one of the first ones that had a different manufacturer name. So I guess the autoenable script does not have that yet

It's an older one from 2021 with AMD. It's the onexplayer 1 AMD. It's been so painful to get things working on it. I still can't change TDP on it no matter what I tried. All the options that the bazzite team gives (HDD and the other) don't have the actual TDP numbers. I can only change power profiles using the handheld daemon app to "performing, balanced, power saving". Tried going into its BIOS, and it was literally an empty land. Meaning, there aren't many things I can change there. At least I have the "... " And steam buttons working and the " turbo" button works, too. Looks like the wattage gets limited to 15 wats when the turbo button is off and then it goes up to 35 watts when the turbo button is on. I wish I can see numbers like the onexconsole app shows on windows for this device. :/

**Comment by antheas** [comment]
Whats the CPU on it?

**Comment by KarkanAlzwayed** [comment]
> Whats the CPU on it?

Ryzen 7 5700U

**Comment by antheas** [comment]
I added your model to the list. In Handheld Daemon, go to Bug Reports -> Use HHD Beta until restart and see if it works.

It will trickle down to bazzite in a few days.

**Comment by antheas** [comment]
Also drop a bug report so I can grab your model and add the turbo button to the kernel

**Comment by KarkanAlzwayed** [comment]
> if it works 

What works? The turbo button? If so, it kinda does? But not too much. It lights up when I press it and the TDP goes higher, but there is nothing in the UI that indicates that it's working, nor is there a slider for the TDP to change it in a factor of 5s like on the steam deck. 

> Drop a bug report

About the turbo button? About the no gui indication/TDP slider? Not sure. 
Also, Everytime I reboot it, it just hangs on a black screen forever. That's another thing I'll need to dig in and see why it's happening.

**Comment by antheas** [comment]
Just use Handheld Daemon, generate a bug report and drop it here so i can get your device ID.

**Comment by KarkanAlzwayed** [comment]
[Here](https://paste.centos.org/view/09e68d77) is the bug report. Also, a couple of more things: 
1. The beta worked and I can now see the slider, but it only goes up to 30 Watts, and I know for a fact this device can do 35 (It was in their onexconsole app), but I do see a "TDP boost" checkbox, so I assume that that makes it go higher than the 30? 
2. Wifi just gone, I can never connect to wifi anymore, no network showa anymore. I can only do wired (I might do a reinstall of the system)
3. If I run the device for a while then reboot, it gets stuck on a black screen until I force it off with the power button. When it is on and I reboot right away, it reboots fine
4. I see that there is also a fan control, which I really like, as it is helping with the noise greatly, but I don't see it in game mode. Is there a way to use HHD in game mode, not only on the desktop?

**Comment by antheas** [comment]
1) Not sure that chip can handle 35W, indeed boost will do 32W though. Not a lot of devices can do 35W

2) unsure about that, grab a bug report after you reboot with the previous boot

3) press Y

**Comment by antheas** [comment]
I will also fix your turbo button with the next kernel so you can use it to open hhd and then the keyboard button will open the keyboard

**Comment by KarkanAlzwayed** [comment]
> I will also fix your turbo button with the next kernel so you can use it to open hhd and then the keyboard button will open the keyboard.


thank you so very much. I really appreciate it. 
I wouldnt mess with the keyboard button, as it is what is used to open the right menu where all the settings and decky are. one press shows the right menu. press and hold the keyboard button and it shows a cursor, which I really love and is very helpful in non steam apps like heroic games launcher. 

Also, the wifi is still turning off permenantly until i reboot the device. That happens after I wake it up from suspend (suspend takes forever to wake, too).

**Comment by KarkanAlzwayed** [comment]
Unless you're saying that the turbo button will turn into the right menu button and the keyboard button will turn into one press keyboard and press and hold cursor? Then yeah that's great.
