### ISSUE TITLE
Updating Issue On Deck

### ISSUE THREAD

**Issue by thanone2** [ublue-os/bazzite#1639]
### Describe the bug

I ran the System Update and it wouldn't update
![image](https://github.com/user-attachments/assets/5aa7763f-a0e6-445d-a8cd-2cacd753bf59)

### What did you expect to happen?

I expected it to update

### Hardware

Steam Deck LCD 512gb (64gb model)

**Comment by thanone2** [comment]
It also won't apply the september 6th steam deck patch

**Comment by KyleGospo** [comment]
It says the issue in that message, you are out of space.

**Comment by thanone2** [comment]
Oh lol

**Comment by thanone2** [comment]
Oh, odd

**Comment by thanone2** [comment]
> 3% of your drive, it's a requirement of the default OSTree config.

Would this in any way hinder buying stuff in-game perchance?

**Comment by thanone2** [comment]
Nvm
