### ISSUE TITLE
Live CD option not works

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [ublue-os/bazzite#1640]
### Describe the bug

When boot to live cd test & install the ISO boot only the install setup.

### What did you expect to happen?

If I select Install the ISO will boot the installer setup
If I choose the option Test & Install the live cd will boot the live cd version with options to explore the system and install the system.

### Hardware

Xeon 2640 v3
32GB Ram
Nvidia 1050ti

### Extra information or context

Bazzite OS. Nvidia legacy ISO version

**Comment by KyleGospo** [comment]
Fedora Atomic does not support live CDs at this time. This is working as intended
