### ISSUE TITLE
[Feature] bazzite-deck: Modify "Return to Gaming Mode" behavior

### ISSUE THREAD

**Issue by Messaiga** [ublue-os/bazzite#165]
If desktop auto-login is enabled using `just enable-desktop-autologin`, the Return to Gaming Mode desktop script won't activate Gamescope.  It's scripted to kill the KDE or Gnome session, and then it auto boots into a desktop session or gamescope-session.

Is it possible to change the scripting so it detects a KDE or GNOME session, kills it, then launches gamescope-session?  

As a bonus - a `just` script could be made later to switch gamescope-session to use the SteamOS Game Mode UI, or OpenGamepadUI.

**Comment by EyeCantCU** [comment]
The only possible thing I can think is to cache the session to return to, prompt the user through systemd to enable gamescope-autologin via systemd, then trigger a logout from where the user is logged into Gamescope... For returning from GS to that session, read the cached session, trigger that service, then proceed to log into that. Sounds like something I'll have to investigate further

**Comment by EyeCantCU** [comment]
This has now been fixed. Much simpler than I thought it would be :)
