### ISSUE TITLE
Fullscreen apps glitch in desktop mode in bazzite-deck KDE 

### ISSUE THREAD

**Issue by kajetan000** [ublue-os/bazzite#1657]
### Describe the bug

When I open any fullscreen applications in KDE desktop mode (such as Steam games or Minecraft) the app has a weird issue. The whole screen turns black for a second or two and audio disappears. This happens again if I press escape or click any sort of menu and sometimes just if i click anything. Turning the Steam Overlay off doesn't help. This also happens to non-Steam apps.

This doesn't happen to any windowed or windowed borderless apps, but does happen to all fullscreen apps (Minecraft and Steam games like Smite, Cruelty Squad, Half-Life 1 & 2, Portal 2, Cult of The Lamb etc). I am unaware of a fullscreen app that does not have this issue.

This doesn't seem to happen on my 4k LG TV, but always happens to fullscreen apps on my 4k Dell 27" S2722QC (even if set to 1080p or change the scale).

Game Mode works flawlessly and there are no other noticeable issues in Desktop Mode. I am using AMD GPU, fresh install of Bazzite.

### What did you expect to happen?

I expect this blackscreen to not appear on any fullscreen apps.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:065f8e6299d18668cd83836e79493c5c6105884d03e665f628f2b75435c1caad
                  Version: 40.20240908.0 (2024-09-09T05:04:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b8fe1ed400759df5655cc93dd1af61c4a3ca62a4377269e6b2bae4f6094666f7
                  Version: 40.20240907.0 (2024-09-08T20:18:29Z)
```

### Hardware

Operating System: Bazzite 40
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.9.12-205.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × 12th Gen Intel® Core™ i5-12400F
Memory: 15.4 GiB of RAM
Graphics Processor: AMD Radeon RX 7600 XT
Manufacturer: ASUS

### Extra information or context

I have never encountered this with any other distro. I have previously used this exact setup but this a NVIDIA GPU (bazzite-nvidia) and this glitch didn't happen.

**Comment by kajetan000** [comment]
SOULTION FOUND: I had to change an option "adaptive sync" in display settings from "automatic" to "never". Issue disappeared. "Automatic" seems to be causing the glitch. Probably shouldn't be a default.

**Comment by Haxorzz** [comment]
This might be a KDE bug, if you switch back to "automatic" or "always" do you still see an issue? Could also be a monitor bug, I myself have a monitor that falsely reports the minimum VRR refresh rate and starts blanking out on me the same way

**Comment by RickBankers** [comment]
I am having the same issue. I have a Samsung 49" monitor. As soon as I turn off adaptive  sync it works. What's really strange is if you leave adaptive sync enabled. Launch game, black screen, then alt-tab you actually see the game behind the windows. It only happens when the game has focus. Seems like a KDE issue.

**Comment by vinaysshenoy** [comment]
I am running into this same problem from `stable-41.20250131` onwards. Leaving adaptive sync to "Auto" or "Always" breaks fullscreen apps and games, HDMI signal is dropped when it launches.

Hardware info:

- Ryzen 5600
- RTX 4060 connected via HDMI 2.1
- Driver version: 570.86.16

**Comment by NiksaVel** [comment]
Same for me for external monitor on my XMG Neo E23 with RTX 4080 laptop GPU on a Corsair Xeneon Flex monitor via HDMI.

**Comment by lcow392** [comment]
Confirming I have this issue, and confirming that changing the display setting Adaptive Sync to Never does fix it.  Additionally, changing this setting to Always results in a permanent black screen.

System Info

Computer Information:
Manufacturer: ASRock
Model: X570 Steel Legend
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 7 3700X 8-Core Processor
CPU Family: 0x17
CPU Model: 0x71
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 4524 MHz
16 logical processors
8 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
BMI1: Supported
BMI2: Supported
F16C: Supported
FMA: Supported
Operating System Version:
"Bazzite 41 (FROM Fedora Kinoite)" (64 bit)
Kernel Name: Linux
Kernel Version: 6.12.12-207.bazzite.fc41.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12401003
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20241127.109674
Client Information:
Version: 1738026274
Browser GPU Acceleration Status: Disabled
Browser Canvas: Unavailable
Browser Canvas out-of-process rasterization: Disabled
Browser Direct Rendering Display Compositor: Disabled
Browser Compositing: Disabled
Browser Multiple Raster Threads: Enabled
Browser OpenGL: Disabled
Browser Rasterization: Disabled
Browser Raw Draw: Disabled
Browser Skia Graphite: Disabled
Browser Video Decode: Disabled
Browser Video Encode: Disabled
Browser Vulkan: Disabled
Browser WebGL: Unavailable
Browser WebGL2: Unavailable
Browser WebGPU: Disabled
Browser WebNN: Disabled
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 3080/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 570.86.16
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x10de
DeviceID: 0x2216
Revision Not Detected
Number of Monitors: 2
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 4769 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary VRAM: 10240 MB
Sound card:
Audio device: USB Mixer
Memory:
RAM: 15906 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 448677 MB
Largest Free Hard Disk Block: 314557 MB
Storage:
Number of SSDs: 7
SSD sizes: 2000G,2000G,2000G,2000G,2000G,500G,240G
Number of HDDs: 0
Number of removable drives: 0

**Comment by NiksaVel** [comment]
System update yesterday resolved this issue for me.

**Comment by prasannaraut2012** [comment]
i am having the same issue with gnome ,  i have recently installed   Stable (F42.20250903), on my desktop i cant find the Gsync / freesync options in nvidia settings
---
Hardware Information:
Hardware Model:                  Gigabyte Technology Co., Ltd. X470 AORUS ULTRA GAMING
Memory:                                 16.0 GiB
Processor:                               AMD Ryzen™ 7 5700X × 16
Graphics:                                 NVIDIA GeForce GTX 1080 Driver- 580.82.07

Software Information:
OS Name                                Bazzite
OS Build                                 Stable (F42.20250903)
OS Type                                  64-bit
GNOME Version                    48
Windowing System              Wayland
Kernel Version:                      Linux 6.16.4-104.bazzite.fc42.x86_64

**Comment by emitan** [comment]
I was having an issue where fullscreen applications (Spectacle, Full screen video in Discord and VLC) was causing a black screen/glitchy behavior. Turning Adaptive Sync from Automatic to Never in Display Configuration fixed the issue for me.
Operating System: Bazzite 44
KDE Plasma Version: 6.6.5
KDE Frameworks Version: 6.26.0
Qt Version: 6.11.1
Kernel Version: 7.0.9-ogc3.2.fc44.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 32 GiB of RAM (31.2 GiB usable)
Graphics Processor: AMD Radeon RX 6750 XT

**Comment by QuentiumYT** [comment]
Got some flicker like graphical glitch as well on my main screen (27" 1080p) after 6h of playing (appeared out of nowhere). I lowered my refresh rate to 144 Hz instead of 165 Hz and it got fixed
