### ISSUE TITLE
Current Documentation Issues & Notes

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/bazzite#1661]
### What needs to be done soon:
- Migrating docs: https://github.com/ublue-os/bazzite/issues/1667
- Remove some outdated information in each "Handheld Wiki" entry.
  - For example: the 'rainbow rgb bug' no longer is an issue on Bazzite.
- Better wording / grammar (FAQ is a mess: too long, awkward wording especially under the Java section).
  - Some of the information in the FAQ may need to be on its own separate page dedicated to explaining what a Fedora custom OCI image is. 
- Rebase guide needs a revamp.

### Feedback:

Comment on this thread to give feedback on the current documentation for Bazzite.

### Close this soon
See the first bullet point about migrating documentation.  There will be issues I have (as reminders for myself) in their own individual issue thread.

**Comment by Zeglius** [comment]
> * Gaming Guide Index doesn't have correct bullet point indentation.

commit 8317b0286ffc7ca04fdce6ab2730f900fd40b09e solves that, using a `just fmt` utility added in commit 6e854c76b48e468c351b9192d77371d66ced71ef
