### ISSUE TITLE
Steam Client keeps reverting to Stable

### ISSUE THREAD

**Issue by RibShark** [ublue-os/bazzite#169]
After setting Steam to use the Beta client in the game-mode session, Steam will revert back to Stable on switching between game-mode and desktop.

**Comment by KyleGospo** [comment]
If you set it in the desktop steam client does it stick, or do you get the same behavior?

**Comment by RibShark** [comment]
I get the same behaviour after setting it in the desktop client; on returning to game-mode Steam will "update" back to Stable and change my selected channel.

**Comment by Sterophonick** [comment]
Also having this issue.
Steam will even redownload the client if it's *already* on Stable.

**Comment by jtweedie** [comment]
I appear to be experiencing something similar to this, steam re-updates (to the same version it's on) both on reboot and switching either in or out of game-mode.

**Comment by KyleGospo** [comment]
Should be fixed as of the latest build.

Steam is now launched with the -steamdeck launch option even on desktop, which maintains the selected steam deck update branch for Steam.
