### ISSUE TITLE
Weird text in game-mode update menu

### ISSUE THREAD

**Issue by RibShark** [ublue-os/bazzite#170]
In the game mode update menu, the OS Update Channel is shown as "No branch script was found, bra", and the update version shown on checking for software updates is shown as a series of percentages.

![PXL_20230820_175707041 MP](https://github.com/ublue-os/bazzite/assets/1957489/50c1de0e-4f6d-400a-8ae0-479c1417ee9e)

**Comment by KyleGospo** [comment]
The branch scripts message is normal, we don't support multiple release branches yet. In the future you'll be able to select unmerged PRs to test from that menu.

The version display is definitely a bug, we'll take a look
