### ISSUE TITLE
What is keyring and Can I Disable It?

### ISSUE THREAD

**Issue by Get-A-Pear-Today** [ublue-os/bazzite#1700]
Hello,

I am new to bazzite. I just installed it on my minisforum v3. I was setting things up and getting proton vpn when I encountered a keyring pop-up when opening the application. I have set Proton VPN to launch at startup but it is getting prevented by keyring. Is there any way to stop this from happening?

**Comment by salim-b** [comment]
[`gnome-keyring`](https://gitlab.gnome.org/GNOME/gnome-keyring) is Gnome's implementation of the [Secret Service API](https://specifications.freedesktop.org/secret-service-spec/latest/), an open standard for a secure "system credential store". Other platforms provide similar functionality (e.g. *Windows Credential Store* or *macOS Keychain*).

proton vpn likely stores your user's password or token via [libsecret](https://gitlab.gnome.org/GNOME/libsecret) which in turn uses the Secret Service API if available. This is generally a good thing.

**Comment by Get-A-Pear-Today** [comment]
It isn't a good thing when it continues to spam me to set a new password every time I want to open/use ProtonVPN, as it is preventing ProtonVPN from creating a connection at startup like I want it to. I don't find it necessary to be prompted to set a password each time I go to use my vpn.

**Comment by salim-b** [comment]
Then you should report your issue to [Proton VPN ](https://github.com/ProtonVPN), I guess. This is not specific to Bazzite (or ublue images) but applies to any Linux distro supporting the Secret Service API.

**Comment by Get-A-Pear-Today** [comment]
I've never dealt with this issue in any other Linux distro that I've tried. Fedora, ZorinOS, Linux Mint, Pop!_OS, etc. Does regular Fedora even utilize this?

**Comment by KyleGospo** [comment]
> I've never dealt with this issue in any other Linux distro that I've tried. Fedora, ZorinOS, Linux Mint, Pop!_OS, etc. Does regular Fedora even utilize this?

This is a standard feature of every KDE/GNOME desktop in existence.

**Comment by Get-A-Pear-Today** [comment]
So, if that is the case, why would this issue only show it's face to me in Bazzite?

**Comment by KyleGospo** [comment]
> So, if that is the case, why would this issue only show it's face to me in Bazzite?

How it behaves is entirely on how you set up your user password and your keyring on first boot.

**Comment by Get-A-Pear-Today** [comment]
Could you perhaps guide me to where in the setup for Bazzite this is? Since I have the Bazzite-Deck version, it boots into the SteamOS-like UI and does not prompt me for a user password, even when switching over to Desktop mode.

**Comment by KyleGospo** [comment]
> Could you perhaps guide me to where in the setup for Bazzite this is? Since I have the Bazzite-Deck version, it boots into the SteamOS-like UI and does not prompt me for a user password, even when switching over to Desktop mode.

The first time you boot into the desktop and use something that needs a keyring, the keyring will prompt you to set it up. How you set it up determines this behavior.
