### ISSUE TITLE
You can boot from micro sd crd

### ISSUE THREAD

**Issue by mom123-rgb** [ublue-os/bazzite#1748]
on the install pages like [e](https://docs.bazzite.gg/General/Installation_Guide/Installing_Bazzite_for_Steam_Deck/#:~:text=A%20USB%20flash%20drive%20with%2010GB%20free%20space) It says you need a usb however you can also boot from a microsd card. if you add this then devices with a micro sd card like the steam deck would no longer need a dock

**Comment by nicknamenamenick** [comment]
I added it to the guide but please report future documentation issues [here](https://github.com/KyleGospo/docs.bazzite.gg/issues).

Thank you for confirming that it works on the Steam Deck.  I know some handhelds don't like booting from a microSD card.

**Comment by KyleGospo** [comment]
We don't recommend booting from a micro SD card under any circumstance.
