### ISSUE TITLE
Controller shortcuts not working 

### ISSUE THREAD

**Issue by mpetuska** [ublue-os/bazzite#175]
Steam controller shortcuts do not work in gamemode.

e.g. With xbox controller "Xbox Button + A" normally brings up quick settings menu, but does nothing on bazzite. Same for Xbox + X to bring up the virtual keyboard.

For context, I have bazzite-deck-gnome installed on PC.

**Comment by mpetuska** [comment]
Any workarounds or is this expected?

**Comment by KyleGospo** [comment]
Can you try tapping instead of holding the Xbox button and then pressing the other button?

If that works for you this is the same issue Chimera is having

**Comment by mpetuska** [comment]
I can't as I've just finished installing ChimeraOS 😂 But thanka for the workaround!

**Comment by noelmiller** [comment]
This is an issue with upstream SteamOS as well in how it treats xinput controllers. Kyle provided a workaround, this is something we cannot fix.
