### ISSUE TITLE
Significant performance loss

### ISSUE THREAD

**Issue by mpetuska** [ublue-os/bazzite#176]
I've migrated to Bazzite from HoloISO on my Home Theater PC and immediatelly noticed very significant performance degradation when running games from steam gameui. 

On **HoloISO** for the same games I've tried I was easily getting **140+ FPS on native 4k**, however after switching to **Bazzite** I'm lucky if I can even get **30FPS on native 4k** within the same game. Given that the hardware is literally identical, there must be something amiss withing Bazzite.

Here's my hardware as Bazzite sees it in case it helps.
![Hardware](https://github.com/ublue-os/bazzite/assets/23262603/3cd861af-b482-4d57-972b-362adab8a8d0)

**Comment by mpetuska** [comment]
GPU utilisation is also always showing as 0%

**Comment by KyleGospo** [comment]
> Could also be related to memclock being stuck (known issue on kernel 6.4)
> https://gitlab.freedesktop.org/drm/amd/-/issues/2657

Thank you for this, that explains why it doesn't apply to everyone. AMD has had a lot of problems with clocking on 6xxx and 7xxx... hopefully they fix it soon.

**Comment by noelmiller** [comment]
This issue was fixed upstream in the most recent kernel release.
