### ISSUE TITLE
Decky stuck during updating and after no more avaiable

### ISSUE THREAD

**Issue by cmalvi** [ublue-os/bazzite#177]
Decky stuck during and update and after that it doesn't work anymore even trying with reinstall from repo

Edit: reinstalling from first start wizard works but some plugins throws unexpected error

**Comment by KyleGospo** [comment]
Try:

`just get-decky`
In a terminal

**Comment by cmalvi** [comment]
Did it relaunching first boot wizard and worked but note that install from repo doesn't work
