### ISSUE TITLE
Needed more clear os update from gamemode if possible

### ISSUE THREAD

**Issue by cmalvi** [ublue-os/bazzite#178]
I've noticed that OS update from gamemode aren't very clear and doesn't show any changes. Could be useful to show the same list you can see from Software (in gnome desktop mode) or the change from this repo

**Comment by outphase** [comment]
As of now, the changelog only displays the last official SteamOS/client changelog. For now, disregard any notes in there as they are not accurate to any specific updates.

**Comment by cmalvi** [comment]
> `just changelogs` works in a terminal but we don't have a way to pipe that to anything more discoverable.

Isn't possible to replace the SteamOS update dialog with just changelogs content?

**Comment by jacobranson** [comment]
I agree that the gamemode update behavior is strange. It is very unclear what is happening when updating from gamemode. If there ends up being no way of replacing the steam update dialog with a custom one, maybe a Decky Plugin would make sense for this?

**Comment by TeamLinux01** [comment]
Is that why there is multiple "Steam Beta Updates" that need to be applied and restart the system? Is it getting other updates and applying them when doing that?

**Comment by castrojo** [comment]
I think that's a different issue, but not sure. Not sure we can hook in directly to the steam dialog (but probably not?) so maybe there's another way we can deliver changelogs:

https://github.com/ublue-os/config/issues/104

**Comment by cmalvi** [comment]
> I think that's a different issue, but not sure. Not sure we can hook in directly to the steam dialog (but probably not?) so maybe there's another way we can deliver changelogs:
> 
> 
> 
> https://github.com/ublue-os/config/issues/104

Mmm I think could be related. Steam is based under browser technology so I don't think there is some limit  viewing what some decky plugin could do. For sure using the same dialog replacing text will be the best solution if possible

**Comment by dannyglover** [comment]
I keep seeing the same Steam update from last Thursday, about once a day (even after applying the update).

I assume this is related to this issue?

**Comment by KyleGospo** [comment]
Steam is hard coded to show update change logs direct from valve, we aren't able to modify what shown there. Those updates are all real and new however.

**Comment by dannyglover** [comment]
> Steam is hard coded to show update change logs direct from Valve, we aren't able to modify what's shown there. Those updates are all real and new however.

Gotcha. Makes sense now. Thank you.
