### ISSUE TITLE
Color saturation change when opening ui during gameplay

### ISSUE THREAD

**Issue by cmalvi** [ublue-os/bazzite#179]
During gameplay, colour saturation seems lower, when i open steam ui (even qam), colours gains saturation but return the previous state when closed

**Comment by nogeenkopjethee** [comment]
I'm having a similar issue. It seems like display filters, like the color filter and night mode, do apply in some cases, like when a cursor is on screen or the Steam Big Picture UI is shown, but not while in-game.

**Comment by cmalvi** [comment]
> Enable "Force Composite" in the developer menu.

This worked, thanks

**Comment by dannyglover** [comment]
> Enable "Force Composite" in the developer menu.

This was driving me crazy. Was just about to open an issue about this. Can this be added to an FAQ section on the Bazzite page?

**Comment by outphase** [comment]
> Can this be added to an FAQ section on the Bazzite page?

That is ublue-os/website#399 linked above

**Comment by dannyglover** [comment]
> https://universal-blue.org/images/bazzite/FAQ/#why-isnt-night-mode-or-color-saturation-working-on-my-steam-deck
> 
> The FAQ exists, but it looks like it needs to be easier to find.

The page must have been cached at my end before, because I did look at the FAQ, and the last item was about "why not the Steam as a flatpak". 

Now I see the color saturation as the last item. 
Thanks :)
