### ISSUE TITLE
[FAILED] Failed to start jupiter-controller@Controller Firmware Update Service.

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [ublue-os/bazzite#1807]
### Describe the bug

[FAILED] Failed to start jupiter-controller@Controller Firmware Update Service. appeared, also the error only appears in game mode. i tried filling in the prior and then myuser@bazzite in the journalctl -u command. i just updated 10/29. (sorry for the edits, i copied the wrong thing)

### What did you expect to happen?

i expected the error not to appear. (nothing seems to be effected except x11 programs, that might be an unrelated bug.)

### Output of `rpm-ostree status`

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:beb1e4fd88b0d9d97049cf0ea391514e7e135a48db56c516e255b3aff2bb24e1
                  Version: 41.20241029.1 (2024-10-29T18:14:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:60f6adbb2243bc30cdfdbad16d4abec69a46231630e01ac099580f830114cc02
                  Version: 40.20241020 (2024-10-21T05:06:16Z)

### Hardware

steam deck LCD

### Extra information or context

it seems not to effect anything except the time taken to boot, unless it's related to X11 not functioning properly. (i will open another issue if X11 (xwayland) issues persist after restart, as that only happened on one of my boots this update) i was told to do rpm-ostree reset before this.

**Comment by borconc** [comment]
me too :( I ended up rolling back until I figure out why

**Comment by KyleGospo** [comment]
Fixed in latest update
