### ISSUE TITLE
Cannot install on Real Machine Full AMD

### ISSUE THREAD

**Issue by Labsdj** [ublue-os/bazzite#182]
I put iso with fedora writer on usb thumb the iso boot pass 100% verify correctly the checks pass and cannot pass after this check iso need a fix i try Disable Secure Boot and TPM disable booth at same time and not works i try again only with tpm enabled with UEFI disable not pass help on this iso

"""""""""""""""""""""""""""""""""""""""""""SPECTS""""""""""""""""""""""""""""""""""""""""""
- CASE: MSI ATX MAG Vampiric 100R ARGB
- CPU:AMD RYSEN 5 1600AF 3.2GHZ
- RAM:G.SKILL 16GB DDR4 3200HZ OC
- MOTHERBOARD:ASUS EX-A320M-GAMING
- GRAPHIC CARD: SAPPHIRE RX 570 NITRO+ 4GB GDDR5 
- M.2: XPG SPECTRIX S40G - 256GB 
- SSD: MSI SPATIUM S270 -480GB
- SSD: TEAM GROUP 120GB SATA III L3 EVO 
- HD: 2TB HD TOSHIBA + 1TB HD WD ELEMENTS USB 3.0
- MONITOR: LG-28TL520S-PZ 28 POL
- KEYBOARD: KROM KYRA RGB GAMING PT
- MOUSE: MARS GAMING MMW2 WIRELESS MOUSE
- SPEAKERS 2.1+SUBWOOFER 
- SOUNDBAR "ELEGIANT" 2.1
- MICROPHONE: MARS MMICKIT 7-IN-1 MICROPHONE
- GAMEPAD PC:  8BITDO ULTIMATE WIRED  CONTROLLER
- BOX TV: MINIX NEO U1(ANDROID 5.1) 
- MOBILE PHONE: XIAOMI REDMI 5(ANDROID 8.1) MIUI 11(Black)
- GAMEPAD ANDROID: MOCUTE 050 BLUETHOOT
- GAMEPAD ANDROID/PC MOCUTE 052 VR BLUETHOOT
- OCULOS VR MOBILE QLIVE
- SO: WINDOWS 11 X64 PRO PT-PT
- SO: Linux SteamOS Holo 3.4 iso for Desktop Linux Or ChimeraOS
i cannot pass on this my record video with my mobile https://www.youtube.com/shorts/h4KtL2m9tIE?feature=share

**Comment by nicknamenamenick** [comment]
The video is private, but it might be related to the kickstart.

There's a similar issue here, and I linked the workaround.  Follow the instructions here.  You might have to use a stock Fedora Kinoite installation then rebase to Bazzite once you reach the desktop to open at terminal.

https://github.com/ublue-os/bazzite/issues/109#issuecomment-1691090533

**Comment by Labsdj** [comment]
Thanks your solution works very well with me @nicknamenamenick
