### ISSUE TITLE
"Start Steam in Big Picture Mode" setup toggle fails to copy .desktop file.

### ISSUE THREAD

**Issue by TeamLinux01** [ublue-os/bazzite#183]
When selecting the "Start Steam in Big Picture Mode", it fails with the following errors:

sed: can't read /home/deck/autostart/bazzite-arch-steam-slient.desktop: No such file or directory
mv: cannot stat '/home/deck/autostart/bazzite-arch-steam-silent.desktop': No such file or directory
error: Recipe `enable-big-picture` failed with exit code 1
Installation Complete!

I installed the base Bazzite with a user called deck.
My machine is an Intel i7 4790, AMD Radeon RX 580 8GB, 32GB RAM and using a 1TB HDD for test install.

**Comment by KyleGospo** [comment]
Working on a fix for this now

**Comment by rodnheli** [comment]
> Working on a fix for this now

thank you - same issue here
