### ISSUE TITLE
Error during install - ostree container image deploy "no-signature verification"

### ISSUE THREAD

**Issue by quidamphx** [ublue-os/bazzite#184]
Used Rufus to write the install image, tried two types of media (USB flash Disk and USB SSD) Bazzite gnome Nvidia, started install using basic graphics.

After I choose the initial options, I get the error:

[Error Image](https://postimg.cc/LgJNpyRD) 

I'm not sure how to proceed with the install.

Thanks.

**Comment by quidamphx** [comment]
It says:

The following error occurred while installing the payload. This is a fatal error and installation will be aborted.

The command 'ostree container image deploy--sysroot=/mnt/sysimage--image=ghcr.io/ublue-os/bazzite-gnome-nvidia:38--no-signature-verification exited with the code 1.

**Comment by KyleGospo** [comment]
Make sure an internet connection is configured prior to install, and that your internet is stable. This is an online installer.

**Comment by quidamphx** [comment]
I thought that could be part of it and am definitely connected. It's 5G though, I'll switch to 2.4Ghz and see if it persists.

**Comment by quidamphx** [comment]
Seems like that was it. I wired in with ethernet and had no issues. Hopefully wireless will work when I'm done but that's a future problem. Thank you!

**Comment by barbarbar338** [comment]
Don't know why but had the same issue with ROG Ally, tried installing bazzite at least 10 times with a stable wifi connection, ethernet connection and my Ally was plugged in all the time. Tried one last time with plugging out the power cable and it worked. IDK why, how but keep in mind that it happened :)

**Comment by noelmiller** [comment]
> Don't know why but had the same issue with ROG Ally, tried installing bazzite at least 10 times with a stable wifi connection, ethernet connection and my Ally was plugged in all the time. Tried one last time with plugging out the power cable and it worked. IDK why, how but keep in mind that it happened :)

This no longer should be an issue with the new ISO images. They can be installed completely offline. It is recommended to have internet connection on first boot however to download updates and remaining software not on the ISO.

**Comment by barbarbar338** [comment]
> > Don't know why but had the same issue with ROG Ally, tried installing bazzite at least 10 times with a stable wifi connection, ethernet connection and my Ally was plugged in all the time. Tried one last time with plugging out the power cable and it worked. IDK why, how but keep in mind that it happened :)
> 
> This no longer should be an issue with the new ISO images. They can be installed completely offline. It is recommended to have internet connection on first boot however to download updates and remaining software not on the ISO.

IDK I was online all the time but thanks :)

**Comment by RellikZephyr** [comment]
i am getting this same error... i am definitely online with an ethernet connection, if it is offline capable then possibly it is from the fact i am trying to install on a partitioned drive with an existing Win11 installation... but either way any assistance would be appreciated, trying to replace windows with linux, but linux resists this every time

**Comment by nirmaleeswar30** [comment]
Did you fix the issue yet?

**Comment by RellikZephyr** [comment]
No... I am fairly certain this is a issue with partitioned drives... I tried to install kinoite and rebase to bazzite... But the exact same error occurs... From there I found there is a known issue with kinoite and partitioned drives

**Comment by RellikZephyr** [comment]
unfortunately did not work for me, same error

**Comment by Mneyuu** [comment]
> unfortunately did not work for me, same error

Sorry, I completely forgot to reply that I found a solution. When you're manually creating partitions, You have to create a EFI Boot partition AND a Boot partition, whereas you usually just need a EFI Boot on other distros. I found this out on a Youtube tutorial on how to install Fedora a while back. Doing this, I had no issues installing Bazzite multiple times. The Boot partition was suggested at 1000MB for size, but it might be negotiable, I don't know.

**Comment by barbarbar338** [comment]
Today I tried installing it again on my ally and had the same problem. Again unplugging the power cable fixed the problems.

**Comment by udance4ever** [comment]
I see this is known issue.  I had no problems installing the first time on my Ally and accidentally went into Steam and ended up in a “Verifying Installation” loop.

I thought I’d just reinstall and even if delete and format partitions, I keep getting the `no-signature verification` issue.  I tried both on and offline (as I was offline on the first install & verify the install can complete completely offline)

Tried 4x and always run into the same error.  Kinda bummed this is my introduction to Bazzite and Fedora after reading so many good things!

**Comment by mariafshan** [comment]
> > unfortunately did not work for me, same error
> 
> Sorry, I completely forgot to reply that I found a solution. When you're manually creating partitions, You have to create a EFI Boot partition AND a Boot partition, whereas you usually just need a EFI Boot on other distros. I found this out on a Youtube tutorial on how to install Fedora a while back. Doing this, I had no issues installing Bazzite multiple times. The Boot partition was suggested at 1000MB for size, but it might be negotiable, I don't know.

Thanks, I fixed it this way by following the boot partition setting through this video: [https://www.youtube.com/watch?v=RUES5B5j6EU&t=682s](https://www.youtube.com/watch?v=RUES5B5j6EU&t=682s)

**Comment by nstiurca** [comment]
I'm running into this too. I'm on Steam Deck OLED over wifi and powered. I don't really have a good ethernet option at the moment; also, I don't have a good not-powered option because the dock I'm using to be able to connect the install flash drive and the mouse+keyboard is actually a monitor with built-in hub and power delivery. I am attempting dual-boot with Windows 10 (already installed) and I was already following the video guide in https://github.com/ublue-os/bazzite/issues/184#issuecomment-2515709752

It seems very odd to me to close this issue when it hasn't even been root-cause'd yet. There's several scattershot workarounds which are not great IMO.

Is there a way to access any installation logs to get an actual error message? The command shown in the error is just the top level install command, and doesn't really tell us what might be wrong.

**Comment by nstiurca** [comment]
Ok so I re-downloaded the ISO, and everything worked. So it looks like it was a data corruption issue for me, probably my fault somehow.

Still, it seems to me there's like half a dozen disparage bugs all yielding the same "error" message. The problem here is that the error message should show what actually went wrong, not just the high level operation that was attempted. That way folks in the future can produce better bug reports and/or have better ways to troubleshoot and find relevant workarounds. I recommend re-opening this issue to that effect.

**Comment by Zora-Z0** [comment]
I think this might be an issue with KDE since the Gnome version seems to install fine. Mind you I have only tried this with dual booting and have tried all the steps people have mentioned above. I was able to get it to work following this video guide

https://www.youtube.com/watch?v=pbxM_1ZJCCc
