### ISSUE TITLE
Tower PC shuts of due to “low battery”

### ISSUE THREAD

**Issue by onewtonSudo** [ublue-os/bazzite#1842]
### Describe the bug

I just installed the bazzite-deck iso to an ssd when I boot it displays “low battery, please plug in or your pc will shut off” or something along those lines. Then proceeds to shut off. I have no battery because it’s a tower

### What did you expect to happen?

I expected the installer to finish setting up steam and let me play

### Output of `rpm-ostree status`

Unable to due to not fully installed

### Hardware

I5-11500
RX6750 XT
32GB ddr4-3200
4TB SSD
GbE

**Comment by onewtonSudo** [comment]
on the image picker these were my selections 
![Image](https://github.com/user-attachments/assets/0efec8d7-397c-4a79-abf8-1bc6dbfe3bdc)

**Comment by onewtonSudo** [comment]
bazzite-deck was the wrong image, bazzite.iso worked just fine

**Comment by m44rkiz** [comment]
thanks, You saved me some digging, this "Image Picker tool" is kind of useless - it suggests that if you want to boot directly to steam gaming mode on HTPC you should download deck-stable-live ISO, that prevents You from completing setup on machines without battery or not connected to UPS
