### ISSUE TITLE
Black screen on AMD with 120Hz

### ISSUE THREAD

**Issue by duhow** [ublue-os/bazzite#1844]
### Describe the bug

Connected desktop computer with HDMI cable to my display monitor `MSI Optix MPG27CQ` at `2560x1440` resolution.
🎮 AMD Radeon 780M graphics.

✅ When running at Refresh Rate **60Hz** or **85Hz** , works fine.
❌ When running at Refresh Rate **120Hz** or **144Hz**, full-screen games (RPCS3) or videos (Telegram) make the screen go **black** 🖵 .

No `dmesg` error outputs.

### What did you expect to happen?

No black screen when running in fullscreen.

### Output of `rpm-ostree status`

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:5bb32b035ce0678ada4b86f4899c7e237887c02038e077934b214f27866de14a
                  Version: 41.20241030 (2024-10-31T01:20:26Z)
          LayeredPackages: sunshine

### Hardware

- Monitor: MSI MPG27CQ
- Computer: Geekom A8 - https://linux-hardware.org/?probe=0c71662747
- CPU: AMD Ryzen 9 8945HS w/ Radeon 780M Graphics

**Comment by duhow** [comment]
✅ Fix: Disable **Adaptative Sync** / https://wiki.archlinux.org/title/Variable_refresh_rate .

![Image](https://github.com/user-attachments/assets/0e34899e-fff9-4ed5-b1b0-758cb196d011)

**Comment by Volanaro** [comment]
ill give it ago thanks! so far so good!
