### ISSUE TITLE
Black screen momenteraly on deckUI when opening menus or picking a game in Library

### ISSUE THREAD

**Issue by digitalaiz** [ublue-os/bazzite#1846]
### Describe the bug

I have just updated to f41 and i am facing this bug: while on deck ui the first 30 seconds to 1 minute the monitor will go black momentarily 3-4 times and then it will settle. then once i click to enter the launch page of a game or if i hit the menu button it will do the same. 
While gaming there are no issues at all. Once i terminate a game the same thing it will happen. 

Some personal notes:
I have the feeling it has something to do with VRR since after updating my monitor reports VRR disabled while on deckui home ( it was reported enabled on f40 while on deckui home )  and is reported enabled while in a game. Obviously both my tv and bazzite pc have it enabled.

### What did you expect to happen?

I was expecting to either have VRR enabled on the deck ui menus like it used to be or at least if for some reasson it was disabled i would expect not to cause black screens.

### Hardware

HW Specs:
5700x3d, 7900GRE, 32GB RAM, Samsung Q90B 65'' 120HZ.  

### Extra information or context

i think i read somewhere about a new bazzite feature for handhelds that limits the fps while on DeckUI menus to conserve power?! maybe related?

**Comment by antheas** [comment]
Rebase to [unstable-41.20241027.1](https://github.com/ublue-os/bazzite/releases/tag/unstable-41.20241027.1) which does not have the optimization to see if its the kernel.

**Comment by digitalaiz** [comment]
Thank you , i will test it and back with results

**Comment by digitalaiz** [comment]
Unfortunately, it didnt make any difference.

**Comment by RyzenWarrior** [comment]
I've been having this issue as well. I noticed that for me it's more of a problem at 4k 120hz (or 100hz) and less noticable at anything lower. (4k 60hz or 1440p 120hz)

**Comment by digitalaiz** [comment]
I ve read something similar in another thread about rog ally so i tried it . If I lower the  refresh rate from the deck quick settings ( the one that comes up on the right side i mean ) no difference. if i drop it from the settings and set it at 4k 60hz , the black screens are still there but i feel they are "snappier" . But of course even if they were completely gone, lowering the refresh rate  wouldnt be a viable fix for me.
I am wondering if more people have this issue and if it is going to be fix with a patch.

**Comment by digitalaiz** [comment]
it seems that vrr is enabled again on the home screen with the latest stable so no issues at all
