### ISSUE TITLE
Missing justfile recipes after rebasing from ublue/kinoite to ublue/bazzite

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/bazzite#186]
![image](https://github.com/ublue-os/bazzite/assets/121328689/7d6cd397-296a-4d01-b868-9e7f34bfcafa)

I just rebased from Universal Blue's Kinoite to the latest _bazzite_ on my desktop.  After I rebased with `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:latest` in the terminal, and rebooted.  The Bazzite Portal YAFTI application appeared as usual.  It could not find any justfile recipes for any of the exclusive Bazzite ones, like installing the Nix package manager and CoreCtrl.  

I rebooted again after finishing the firstboot sequence.  Bazzite Portal appeared once again with the same errors if I attempted to install Nix and CoreCtrl

![image](https://github.com/ublue-os/bazzite/assets/121328689/3d01ac96-ec3b-41cf-8fdb-45d706a81d62)

To confirm I am on Bazzite:
![image](https://github.com/ublue-os/bazzite/assets/121328689/a28595bd-2447-4228-ae22-a5aa303f1ce1)

I also have the preinstalled Bazzite packages like btop++ and DDC Control which I did not have preinstalled before the rebase.

**Comment by EyeCantCU** [comment]
I'll look into it. Absolute worst case, we throw the file into /etc/skel.d and copy it over in the user setup script first thing
