### ISSUE TITLE
Waydroid controller input does not work

### ISSUE THREAD

**Issue by lxpanel** [ublue-os/bazzite#1860]
### Describe the bug

When I go to gaming mode and launch waydroid, the controller input method (gamepad with joystick trackpad) does not work, although the keyboard and mouse and touchscreen inputs work.

### What did you expect to happen?

I expected the gamepad input method to work.

### Output of `rpm-ostree status`

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:0c40b912f034c9297e76125dea2d0a3417b46a3391dd9fe77dda7ba8875cd762
                  Version: 41.20241104 (2024-11-04T04:59:55Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:7e9af0bc63e8c608efb66ed32da3af4660f3dee108892109fde12a697a962c79
                  Version: 41.20241030 (2024-10-31T01:21:40Z)

### Hardware

Steam deck OLED 
Galileo

**Comment by quuinnn** [comment]
Try running `waydroid prop set persist.waydroid.uevent true` into the terminal. Then see if that works.

**Comment by lxpanel** [comment]
Entered the command and it works in gaming mode! Thanks!
