### ISSUE TITLE
Bug - game mode: the "Steam" and "•••" (quick access) button randomly spawn and control a cursor instead of opening Home and Quick Access menu

### ISSUE THREAD

**Issue by ahydronous** [ublue-os/bazzite#1866]
### Describe the bug

Randomly in game mode, the "Steam" and "•••" will spawn and control a cursor, instead of opening their respective menus.

### What did you expect to happen?

The "Steam" and "•••" button open their respective menus.

### Hardware

Steam Deck LCD

### Extra information or context

Bazzite 41.20241104

A reboot fixes the problem.

SteamOS does not have this issue.

This issue has been present for at least 3 months, probably longer.

**Comment by antheas** [comment]
Maybe your SD is drifting and activates mouse mode now.

**Comment by ahydronous** [comment]
Yes, you are right!

Somehow my stick calibration had reset from 3600-3600 to the absolute minimum (2000-2000).
