### ISSUE TITLE
Can‘t install on OXP 2 

### ISSUE THREAD

**Issue by Elcapone86** [ublue-os/bazzite#187]
![IMG_9826](https://github.com/ublue-os/bazzite/assets/40920098/6ffa2443-b618-47df-b657-01a194f31108)

I keep getting this error message, the installation always stops at this point. Have already tried various things. Installation on microSD, USB stick or external NVMe nothing works.

**Comment by EyeCantCU** [comment]
Related discussion here: https://github.com/ublue-os/bazzite/issues/189

To summarize, it could be a number of different things. It sounds like this needs to be addressed upstream

**Comment by tulilirockz** [comment]
Try installing Silverblue through their ISO then rebase to Bazzite, that generally helps? It depends really

**Comment by EyeCantCU** [comment]
We offer a set of offline installers now in our latest release if you'd like to give those a try. Should address this issue

**Comment by noelmiller** [comment]
We are currently in the process of regenerating this ISO. It is not complete yet. If you want more information, please follow this issue: https://github.com/ublue-os/main/issues/468

**Comment by KyleGospo** [comment]
We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker

Let us know if you have any issues with the new one :)
