### ISSUE TITLE
Bazzite.gg report - Confusing GPU Vendor Options for Virtual Machines

### ISSUE THREAD

**Issue by koloved** [ublue-os/bazzite#1875]
### Describe the bug

![Image](https://github.com/user-attachments/assets/2e36ffba-bd51-4651-82a2-d3aee670fc44)
The question "Who is the vendor of your primary GPU?" provides options that are not relevant for virtual machines. This is confusing, as virtual machines do not have direct access to physical GPUs and instead rely on the virtualization software's GPU driver.

### What did you expect to happen?

--

### Output of `rpm-ostree status`

```shell
--
```

**Comment by KyleGospo** [comment]
It's a gaming image, We expect you to do GPU pass through which immediately makes this relevant.
