### ISSUE TITLE
HDR makes everything green and purple

### ISSUE THREAD

**Issue by b-** [ublue-os/bazzite#1888]
### Describe the bug

![Image](https://github.com/user-attachments/assets/9e535b73-eb4e-4203-ace0-9bba436d6ca6)

This is clearly some kinda color format issue, but I’m not sure how to fix it. I have a Radeon RX580 (Polaris) and a 55-inch HiSense U7N 4K HDR TV, and the colors just turn green and purple when I turn HDR on…

HDR works Just Fine™ on Windows 11 on the same hardware.

I feel like this is probably fixable with some simple override setting I’m not aware of, but it’s my first HDR TV and I'm very unfamiliar with how HDR works on Linux and Wayland…

### What did you expect to happen?

I expected the picture to have the correct colors, and for things that aren't supposed to be green to not be green.

### Output of `rpm-ostree status`

```shell

```

### Output of `groups`

```shell

```

### Extra information or context

Cross-posted from the Support forum on Discord, because I got no replies on there. I'm not posting this from near my gaming computer at the moment, so I did not fill out the `rpm-ostree status` or `groups` fields — I'll do so later today or this weekend. 

However, before initially posting to the support forum I was on an old 40 build of `bazzite-deck:stable`, at which point I rebased to `bazzite-deck:testing`. So this occurs on the latest build of `testing` as of 11/10/2024, and if necessary I'll submit build information by this weekend.

thanks!

**Comment by HikariKnight** [comment]
Steam (or rather gamescope) and your display disagree about HDR being supported.
Enable it or disable it on both the display and steam and use the mode that works, nothing we can do to fix it.

**Comment by maikischa** [comment]
Same problem here with an LG OLED. In ChimeraOS I have the same Problem. In Windows 11 it works.
Vega64 Gou with HDMI

**Comment by Phantop** [comment]
Bumping this to report this still happening on current versions with my RX 570 against a TCL FireTV. The TV reports HDR10 and I can't see any further options to change there; and it works on my Macbook Pro on the same cable and TV input.

**Comment by b-** [comment]
I haven’t done further testing, but:

I’m not certain the RX580 actually can do 10-bit and 4K at the same time. I think this is a limitation of it, probably because of bandwidth limitations. 

I could definitely get HDR working “properly” on windows, in that the colors made some sense, but banding was weird because I couldn’t get it to properly output 4K without compromising resolution. 

I don’t think lowering the resolution in Game Mode actually lowers the output resolution, either — I’m pretty sure it scales and outputs to the screen’s native resolution, so this compromise won’t work the same way. 

All of that said, the VRAM on my RX580 failed, so I cannot do further testing. The GeForce GTX 1070 that I replaced it with does do 4K x 10-bit @ 60Hz, but I know better than to expect an old Nvidia card to do well on Linux …

**Comment by NotaInutilis** [comment]
Having the same issue on a fresh bazzite gnome install. My setup is similar, with a rx580 and a 4k tv. Everything worked fine on windows, i believe i lowered some setting to 4:2:2 and everything worked mostly fine for 4k 10bits HDR 60fps.
I tested lowering the resolution in gnome settings before enabling HDR, but the result is the same so I don't believe it's a bandwidth issue.

**Comment by NotaInutilis** [comment]
Crossposting from Discord to share some info.

> Quick update: the fix was actually changing GPU! Seems like the RX580's HDMI can't output proper HDR. Windows' AMD driver could make it work by reducing chroma subsampling but I wasn't able to find the option on Bazzite. Weird thing is that even reducing the resolution, bit depth and framerate didn't let HDR work. After replacing it with a RTX2060, no change of cables, or anything else, HDR 10 bit 4k 60fps works!

**Comment by laichiaheng** [comment]
Does any have any solution? My PC case is not big enough for a new modern GPU, otherwise I'll replace it with my old RX6750XT.
