### ISSUE TITLE
Gaming Mode (gamescope) does not launch

### ISSUE THREAD

**Issue by TKash123** [ublue-os/bazzite#1891]
### Describe the bug

I'm no tech expert so I'm not sure If I happen to make a mistake here. I did a fresh new install of Bazzite on a PC I was saving up for so I can use it as a powerful console like experience. I made sure I bought a PC that had AMD processor and GPU so that the PC would have no issues logging into gaming mode.  But gaming mode does not appear to work on my PC.

### What did you expect to happen?

I'm on the KDE Plasma version of bazzite. I see the icon to press to go to gaming mode, I click it,  it logs me out, and then It takes me back to desktop mode again.

Additionally, when I restart my PC it takes a long time before the desktop shows up, almost as if it tries to have multiple attempts to log into game mode, fails and then it just default to go back to desktop mode.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:beb1e4fd88b0d9d97049cf0ea391514e7e135a48db56c516e255b3aff2bb24e1
                  Version: 41.20241029.1 (2024-10-29T18:14:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:beb1e4fd88b0d9d97049cf0ea391514e7e135a48db56c516e255b3aff2bb24e1
                  Version: 41.20241029.1 (2024-10-29T18:14:07Z)
```

### Hardware

For my hardware I have a 24 × AMD Ryzen 9 7900X3D 12-Core Processor, AMD Radeon Graphics (I believe this is the internal gpu), and ryzen 7900 xtx gpu

### Extra information or context

Below I'm going to paste the .gamescope-stdout.log file.  I think that might give more context on any issue.

[gamescope] [[0;34mInfo[0m]  [0;37mconsole:[0m gamescope version 056b79e+ (gcc 14.2.1)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Loading scripts from: '/usr/share/gamescope/scripts'
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Loading scripts from: '/usr/share/gamescope/scripts/00-gamescope'
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Loading scripts from: '/usr/share/gamescope/scripts/00-gamescope/common'
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/common/inspect.lua' (id: 0)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/common/modegen.lua' (id: 1)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/common/util.lua' (id: 2)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Loading scripts from: '/usr/share/gamescope/scripts/00-gamescope/displays'
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/asus.rogally.lcd.lua' (id: 3)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/deckhd.steamdeck.deckhd-lcd.lua' (id: 4)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/gpd.win4.lcd.lua' (id: 5)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/valve.steamdeck.lcd.lua' (id: 6)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Running script file '/usr/share/gamescope/scripts/00-gamescope/displays/valve.steamdeck.oled.lua' (id: 7)
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Loading scripts from: '/etc/gamescope/scripts'
[gamescope] [[0;33mWarn[0m]  [0;37mscriptmgr:[0m Directory '/etc/gamescope/scripts' does not exist
[gamescope] [[0;34mInfo[0m]  [0;37mscriptmgr:[0m Loading scripts from: '/home/tabish/.config/gamescope/scripts'
[gamescope] [[0;33mWarn[0m]  [0;37mscriptmgr:[0m Directory '/home/tabish/.config/gamescope/scripts' does not exist
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m selecting physical device 'AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)': queue family 1 (general queue family 0)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m physical device supports DRM format modifiers
[Gamescope WSI] Forcing on VK_EXT_swapchain_maintenance1.
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/headless/backend.c:67] Creating headless backend
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/session/session.c:108] Successfully loaded libseat session
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m opening DRM node '/dev/dri/card2'
[gamescope] [[0;31mError[0m] [0;37mdrm:[0m Immediate flips disabled from environment
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m Connector HDMI-A-2 -> TCL - TCL
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: EDID with colorimetry detected. Using it
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: r 0.625000 0.339844
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: g 0.280273 0.594727
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: b 0.155273 0.070312
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: w 0.283203 0.297852
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m Connector HDMI-A-2 -> TCL - TCL
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: EDID with colorimetry detected. Using it
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: r 0.625000 0.339844
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: g 0.280273 0.594727
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: b 0.155273 0.070312
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m [colorimetry]: w 0.283203 0.297852
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m Connectors:
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m   DP-4 (disconnected)
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m   HDMI-A-2 (connected)
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m selecting connector HDMI-A-2
[gamescope] [[0;34mInfo[0m]  [0;37mdrm:[0m selecting mode 1920x1080@60Hz
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m supported DRM formats for sampling usage:
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AR24 (0x34325241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XR24 (0x34325258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB24 (0x34324241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB24 (0x34324258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   RG16 (0x36314752)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   NV12 (0x3231564E)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB4H (0x48344241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB4H (0x48344258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB48 (0x38344241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB48 (0x38344258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AB30 (0x30334241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XB30 (0x30334258)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   AR30 (0x30335241)
[gamescope] [[0;34mInfo[0m]  [0;37mvulkan:[0m   XR30 (0x30335258)
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m Using explicit sync when available
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m Running compositor on wayland display 'gamescope-0'
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [backend/headless/backend.c:17] Starting headless backend
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m Successfully initialized libei for input emulation!
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [xwayland/server.c:107] Starting Xwayland on :0
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m [xwayland/server.c:107] Starting Xwayland on :1
[gamescope] [[0;34mInfo[0m]  [0;37mpipewire:[0m stream state changed: connecting
[gamescope] [[0;34mInfo[0m]  [0;37mpipewire:[0m stream state changed: paused
[gamescope] [[0;34mInfo[0m]  [0;37mpipewire:[0m stream available on node ID: 42
[gamescope] [[0;34mInfo[0m]  [0;37mxwm:[0m Embedded, no cursor set. Using left_ptr by default.
[gamescope] [[0;34mInfo[0m]  [0;37mxwm:[0m Embedded, no cursor set. Using left_ptr by default.
[gamescope] [[0;34mInfo[0m]  [0;37mvblank:[0m Using timerfd.
[gamescope] [[0;34mInfo[0m]  [0;37medid:[0m Wrote new edid to: /home/tabish/.config/gamescope/edid.bin
[gamescope] [[0;34mInfo[0m]  [0;37mwlserver:[0m Updating mode for xwayland server #0: 1920x1080@60
[gamescope] [[0;33mWarn[0m]  [0;37mxwm:[0m got the same buffer committed twice, ignoring.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
Errors from xkbcomp are not fatal to the X server
[gamescope] [[0;34mInfo[0m]  [0;37medid:[0m Wrote new edid to: /home/tabish/.config/gamescope/edid.bin
radv: Updated the per-vertex VRS rate to '0'.
(EE)(EE)  failed to read Wayland events: Connection reset by peer
failed to read Wayland events: Broken pipe
[gamescope] [[0;31mError[0m] [0;37mdrm:[0m drmModeRmFB failed: Bad file descriptor
[gamescope] [[0;31mError[0m] [0;37mdrm:[0m drmModeRmFB failed: Bad file descriptor
[gamescope] [[0;31mError[0m] [0;37mdrm:[0m drmModeRmFB failed: Bad file descriptor
[gamescope] [[0;31mError[0m] [0;37mdrm:[0m drmModeRmFB failed: Bad file descriptor

**Comment by HikariKnight** [comment]
if you have multiple monitors make sure you have all of them turned on as gamemode supports only 1 monitor and will show on the first one it sees, see https://docs.bazzite.gg/Handheld_and_HTPC_edition/quirks/?h=monitor#how-do-i-specify-the-correct-monitor-for-gaming-mode-to-use-htpc-only for how to set the right display.

If you do not have multiple monitors then it might try to use the wrong gpu. Run the `export-gpu` command to force a specific gpu to be used.

It might also be steam itself, you can try `ujust fix-reset-steam` this will reset steam and **will log you out of steam and remove your login token**
It will not touch installed steam games, compatibilitytools, proton prefixes or saves.

**Comment by TKash123** [comment]
Gaming mode still didn't work form me after trying all of that out. At this point I just gave up and installed the desktop version of bazzite and then use steam big picture mode from there. Thanks HikariKnight for trying to help! 

To give context for anyone else with the same problem. I don't have multiple monitors so that wasn't an issue for me. 

I used the export-gpu command but it ended up giving me a black screen. If anyone is stuck at this point I learned you can just press  CTRL+ALT+F2 to bring up a terminal, put in your username and password, and then type "steamos-session-select plasma". I had to put that code in every single time after a reboot from that point on. Also even though I can see on the systems page that its now looking at the correct gpu, gaming mode still didn't boot after clicking the icon or restarting.

I've also tried ujust fix-reset-steam and even a complete reinstall. Neither seemed to fix the problem.

You can still get deckly loader on the desktop version of bazzite and so after you go to big picture mode, you get almost the same experience anyways.
