### ISSUE TITLE
Bluetooth Headset and XBox Controller pairing fail

### ISSUE THREAD

**Issue by dolsis** [ublue-os/bazzite#1899]
### Describe the bug

Hello,

I just installed Brazzite on my desktop computer.
One of my first actions was to try and pair both my headset and controller to play (so I can finally remove my Windows partition. Info not useful, but I wanted to play the new dragon age game. Which works really smoothly. But without my controller nor sound for now).

So Opened the Bluetooth widget and then Pair Device. I can actually see and discover both appliances. But once I want to pair them, the wizard fail.
I tried with 3 different dongles, to no avail.

The Headset is a Sony WH-1000XM5.
Controller is a Xbox One (Series 1). 

I'd be really glad and grateful if both worked. 

### What did you expect to happen?

To successfully pair the XM5 headset and be able to out sound in it.
To successfully pair my Xbox One controller and play games with it. 

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:stable
                   Digest: sha256:d2cc9a10fac4c2b0271dec3f96d8501ea1ad87700af7e84fbbbe230cf9aa2ed8
                  Version: 41.20241118 (2024-11-18T05:57:16Z)
          LayeredPackages: openrazer-meta razergenie

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:stable
                   Digest: sha256:d2cc9a10fac4c2b0271dec3f96d8501ea1ad87700af7e84fbbbe230cf9aa2ed8
                  Version: 41.20241118 (2024-11-18T05:57:16Z)
```

### Hardware

System Product Name

### Extra information or context

I just tried with someone's else headset: The Sony INZONE H9 with its dedicated dongle and it's working. But I did not have to pair this device via the Bluetooth Wizard.

**Comment by gamofly** [comment]
It's been an issue for weeks now: https://github.com/ublue-os/bazzite/issues/1865

**Comment by sekasorto93** [comment]
Can confirm connection issue with the XM5's too. 

If you're semi confident using the terminal. Try pairing using the bluetoothctl command. Has allowed me to pair and save.

**Comment by gamofly** [comment]
> Can confirm connection issue with the XM5's too.
> 
> If you're semi confident using the terminal. Try pairing using the bluetoothctl command. Has allowed me to pair and save.

What commands did you use? I've tried bluetoothctl pair <MAC Address> but didn't work. Is there a trick to it?

**Comment by sekasorto93** [comment]
So if you've already tried pairing it. Try a simple bluetoothctl connect (Mac)

**Comment by dolsis** [comment]
Thank you y'all for confirming I'm not the only one.

I tried in bluetoothctl do do a _pair \<MAC\>_ , and it partially works. The device is shown as paired inside the console and in the Bluetooth widget. However, the headset does not play the connection sound and it' s not visible as a output device.

About the controller, I plugged it with a micro usb cable and it's detected and is working.

**Comment by gamofly** [comment]
> So if you've already tried pairing it. Try a simple bluetoothctl connect (Mac). If that fails for you, I'll double check my commands when I get home from work tonight.
> 
> But for me that allows me to connect/disconnect on demand through the GUI.

Appreciate that if you could. Meanwhile I'll try that on my end too and see if bluetoothctl connect (as opposed to pair) works. Do you just write out the Mac address as it appears on the terminal? Or do you need to write out the device name as well?

**Comment by sekasorto93** [comment]
> Thank you y'all for confirming I'm not the only one.
> 
> I tried in bluetoothctl do do a _pair \<MAC\>_ , and it partially works. The device is shown as paired inside the console and in the Bluetooth widget. However, the headset does not play the connection sound and it' s not visible as a output device.
> 
> About the controller, I plugged it with a micro usb cable and it's detected and is working. 

Try bluetoothctl connect (Mac)

**Comment by sekasorto93** [comment]
> name

As it appears in terminal. Copy and paste. :)

**Comment by sekasorto93** [comment]
> Thank you y'all for confirming I'm not the only one.
> 
> I tried in bluetoothctl do do a _pair <MAC>_ , and it partially works. The device is shown as paired inside the console and in the Bluetooth widget. However, the headset does not play the connection sound and it' s not visible as a output device.
> 
> About the controller, I plugged it with a micro usb cable and it's detected and is working.

So my process as follows:

1. Set XM5's to pairing mode and attempt to pair using the system dialog (will display connecting, then fail). Close the pairing menu.
2. Open terminal, and enter: bluetoothctl scan on (find your XM5's MAC address)
3. Enter connect followed by mac. Should look like: $bluetoothctl connect 00:00:00:00:00:00
4. Disconnect from the device then reconnect using the pairing menu as normal
5. Trust & Authorise device if asked on connection

**Comment by dolsis** [comment]
@sekasorto93 Thank you very much!

Doing things in that order works for me.
So I was missing the bluetoothctl disconnect and try again in the wizard.

Only then I had the Trust & Authorize popup.
Now I can shutshown and power my headset and it's recognized.

**Comment by sekasorto93** [comment]
> [@sekasorto93](https://github.com/sekasorto93) Thank you very much!
> 
> Doing things in that order works for me. So I was missing the bluetoothctl disconnect and try again in the wizard.
> 
> Only then I had the Trust & Authorize popup. Now I can shutshown and power my headset and it's recognized.

Glad it worked :)
