### ISSUE TITLE
Consider xone for non-BT Xbox controllers

### ISSUE THREAD

**Issue by KAMiKAZOW** [ublue-os/bazzite#190]
Xpadneo does not support the Xbox wireless adapter whose non-BT wireless connection is more reliable than BT. The xone driver exist to remedy that: https://github.com/medusalix/xone/
However there is the catch that the maintainer is currently not active and a few forks exist that are currently hoping for a merge to upstream than collaborate on a fork which would mean some downstream picking of unmerged patches...:
![image](https://github.com/ublue-os/bazzite/assets/3259076/c666a349-0292-4407-925a-c1908fb2a2db)

**Comment by EyeCantCU** [comment]
As it stands, xone seems to cause weird behavior with controllers from other vendors and it doesn't look like it has been updated in a while. It would great to include in the future when the quirks are worked out and it is maintained again though. We used to include this but haven't as of late because of the prior

**Comment by KAMiKAZOW** [comment]
Yeah, I hope dlundquist, franzer and so on start collaborating on a proper fork...

**Comment by bsherman** [comment]
We do have a ticket to address this in ublue-os/akmods upstream 

https://github.com/ublue-os/akmods/issues/26

**Comment by KyleGospo** [comment]
> We do have a ticket to address this in ublue-os/akmods upstream 
> 
> https://github.com/ublue-os/akmods/issues/26

I like this solution, I'll work on this this weekend

**Comment by bsherman** [comment]
> I like this solution, I'll work on this this weekend

That's awesome if you can! I've meant to do so but had other things on my to-do list. 

I do want to learn our COPR setup a bit better but I think I have another module to use even if you do this one. 

😁

**Comment by bsherman** [comment]
I've closed the akmods issue ( https://github.com/ublue-os/akmods/issues/26 ) thanks to @KyleGospo 's efforts so this one should be closed, too.
