### ISSUE TITLE
Bad scaling on Bazzite Deck KDE installer (Bazzite Deck 41)

### ISSUE THREAD

**Issue by solemgar** [ublue-os/bazzite#1908]
### Describe the bug

Tried the installer for Bazzite Deck 41 (KDE) from the website (https://bazzite.gg/). Scaling of the installer is wrong, so it is not possible to complete the installation.

Hardware is a Steam Deck OLED.

Tried with inst.resolution=1280x800 on Grub (note the parameter was missing) but did not make any difference. Basic mode graphic installer did not boot.

Strangely, I am running Bazzite Deck Gnome (installed it a couple of week back) and do not remember having this issue.

![Image](https://github.com/user-attachments/assets/9b350773-3cda-40f0-adc7-8921cd5b3751)

### What did you expect to happen?

To have proper scaling on the installer.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:e47786f5b8a19c2501afaa32afb76072a668b86cda836e49d3e0ed336afd453f
                  Version: 41.20241118.2 (2024-11-19T02:54:35Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:1be077d9f954b19592eaf0090f6f96531353e005e8303e15fc7ff2f69b3e48df
                  Version: 41.20241112.1 (2024-11-12T23:57:05Z)
```

### Hardware

Steam Deck OLED

cat /sys/devices/virtual/dmi/id/product_name
Galileo

**Comment by valiksheva** [comment]
Same for GNOME version on SD OLED

**Comment by Linus-XZX** [comment]
Was looking into a similar issue in Discord so I played a little bit with the latest installer (SHA256 `507ddb8d7a1f4e9a5f1ef7a53fb475855cc004e07985d6777c96f18fda38ada6`).
Curiously giving `inst.resolution=800x600` seems to make the installer boot in 1280x800 resolution.
For basic graphics mode, it appears to be a black screen due to a completely incorrect modeset, as it boots for me but into a garbled screen (I have rEFInd configured to force a modeset early in booting)

**Comment by noelmiller** [comment]
Hey folks,

We just pushed some new ISOs. Please give those a try and let us know if they are scaling properly. 

Thanks, 

Noel

**Comment by Linus-XZX** [comment]
Can confirm I now get a perfect 1280x800 on internal screen (OLED Model).

**Comment by valiksheva** [comment]
Scales fine on SD OLED with GNOME installer

**Comment by solemgar** [comment]
Awesome! Thanks a lot for the quick turnaround!
