### ISSUE TITLE
Steam Virtual Keyboard doesn't work for non-English languages in gaming mode

### ISSUE THREAD

**Issue by fsworld009** [ublue-os/bazzite#1914]
### Describe the bug

In gaming mode, I've observed that virtual keyboard only works for English

For example when I added Chinese and Japanese input:
![Image](https://github.com/user-attachments/assets/278803d1-db36-421f-bafe-cf196c87c437)

The keyboard would type the corresponding English letter on a physical keyboard as-is into the textbox, instead of providing word choices:
![Image](https://github.com/user-attachments/assets/b3c6e270-5e7b-4d95-84fc-34c5ff923955)
![Image](https://github.com/user-attachments/assets/b859e7c0-8d06-4bb9-9106-f795d313fc33)

It also doesn't work in KDE Desktop mode, but I'm not sure if it is supported in KDE Wayland. As far as I know the stock SteamOS is running KDE on X11 instead.

### What did you expect to happen?

**The following screenshots are taken from my Steam Deck running stock SteamOS:**

Word / letter choices based on input is populated after typing something on the keyboard:

![Image](https://github.com/user-attachments/assets/bd0cb1f3-0a90-4c96-8405-4550c7972358)
![Image](https://github.com/user-attachments/assets/64ed36c1-8467-4493-b39c-9f11a03487e9)

And the selected word would actually be sent to the textbox:

![Image](https://github.com/user-attachments/assets/26da7089-8818-4c4c-be2d-72b77966b498)
![Image](https://github.com/user-attachments/assets/c2aed3f5-1286-41fc-a8a3-2a322d51c327)

I expect the same behavior in Bazzite gaming mode.

### Output of `rpm-ostree status`

```shell
$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:98522d63341192410178052962a2cb6084209fedb0c1a2909d6f46e76512fbc4
                  Version: 41.20241118.2 (2024-11-19T02:58:01Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:7ea28171af3cfeaadd6b07d69feff8d67e97d9a8f070770ae271be8d380612be
                  Version: 41.20241104 (2024-11-04T05:01:16Z)
```

### Hardware

GPD Win 4 2023

```
$ cat /sys/devices/virtual/dmi/id/product_name
G1618-04
```

**Comment by zhuzhichao** [comment]
That's what's bothering me.
Chinese and Japanese can't be input normally, strangely Korean can be input normally.

**Comment by fsworld009** [comment]
While I don't know any Korean, I don't think Korean input is working properly.

On Steam Deck, when I type the characters corresponding to `d` and `f` letter on US keyboard, they will be merged into one character, while on Bazzite the two characters remain separated.

SteamOS
![Image](https://github.com/user-attachments/assets/32e4d06a-3f8e-440b-8530-79469e18b104)

Bazzite
![Image](https://github.com/user-attachments/assets/cc9f8098-0cde-4fea-97b8-638f04789849)

**Comment by fsworld009** [comment]
Sharing my findings so far:

I've compared the installed packages and running processes in game mode between Bazzite and Steam Deck 

Bazzite
```
$ ps aux | grep ibus
fsworld+    2905  0.0  0.0 606288  7528 ?        Ssl  18:25   0:00 /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
fsworld+    2914  0.0  0.0 531028  7156 ?        Sl   18:25   0:00 /usr/libexec/ibus-dconf
fsworld+    2919  0.0  0.0 604828  6896 ?        Ssl  18:25   0:00 /usr/libexec/ibus-portal
fsworld+    9155  0.0  0.0 230336  2308 pts/0    S+   18:58   0:00 grep --color=auto ibus

$ rpm -qa | grep ibus
libusb1-1.0.27-4.fc41.x86_64
libusbmuxd-2.0.2^20230620git8d30a55-6.fc41.x86_64
ibus-libs-1.5.31-1.fc41.x86_64
ibus-gtk2-1.5.31-1.fc41.x86_64
ibus-gtk3-1.5.31-1.fc41.x86_64
ibus-panel-1.5.31-1.fc41.x86_64
ibus-setup-1.5.31-1.fc41.noarch
ibus-xinit-1.5.31-1.fc41.noarch
ibus-1.5.31-1.fc41.x86_64
ibus-anthy-python-1.5.16-15.fc41.noarch
ibus-anthy-1.5.16-15.fc41.x86_64
ibus-chewing-2.1.2-1.fc41.x86_64
ibus-hangul-1.5.5-6.fc41.x86_64
ibus-libpinyin-1.15.8-1.fc41.x86_64
ibus-m17n-1.4.34-1.fc41.x86_64
ibus-typing-booster-2.26.8-1.fc41.noarch
ibus-gtk4-1.5.31-1.fc41.x86_64
libuser-0.64-11.fc41.x86_64
libusb1-1.0.27-4.fc41.i686
ibus-qt-1.3.4-12.fc41.x86_64
ibus-table-1.17.8-1.fc41.noarch
ibus-table-chinese-1.8.12-6.fc41.noarch
ibus-table-chinese-cangjie-1.8.12-6.fc41.noarch
ibus-table-chinese-quick-1.8.12-6.fc41.noarch
ibus-pinyin-1.5.1-2.fc41.x86_64
```

SteamOS
```
$ ps aux | grep ibus
deck        1330  0.0  0.0 381356  8168 ?        Ssl  18:54   0:00 /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
deck        1354  0.0  0.0 306368 10492 ?        Sl   18:54   0:00 /usr/lib/ibus/ibus-dconf
deck        1358  0.0  0.0 380044  6296 ?        Ssl  18:54   0:00 /usr/lib/ibus/ibus-portal
deck        4372  0.0  0.0 240024 13700 ?        Sl   18:55   0:00 /usr/lib/ibus/ibus-engine-pinyin --ibus
deck        4486  0.2  0.2 356040 31532 ?        Sl   18:55   0:00 /usr/sbin/python /usr/share/ibus-anthy/engine/main.py --ibus
deck        4491  0.0  0.0 307020  8984 ?        Sl   18:55   0:00 /usr/lib/ibus/ibus-engine-hangul --ibus
deck        5032  0.0  0.0 232392  8080 ?        Sl   18:55   0:00 /usr/lib/ibus/ibus-engine-simple
deck        5950  0.0  0.0   6500  2432 pts/0    S+   18:58   0:00 grep --color=auto ibus

$ sudo pacman -Qs | grep ibus
[sudo] password for deck: 
local/ibus 1.5.30-1.1
local/ibus-anthy 1.5.14-4
local/ibus-hangul 1.5.5-1
local/ibus-pinyin 1.5.1-2.1
local/ibus-table 1.17.4-1
local/ibus-table-cangjie-lite 1.8.8-2
local/libibus 1.5.30-1.1
local/libusb 1.0.27-1
local/libusbmuxd 2.0.2-3
```

It looks like Bazzite has all the packages installed. However, these processes are not running:
```
ibus-engine-pinyin
ibus-anthy/engine/main.py
ibus-engine-hangul
ibus-engine-simple
```

`ibus-anthy` is Japanese IME, `ibus-hangul` is Korean IME, and `ibus-pinyin` is Chinese IME. Lacking these processes might explain why these keybords don't work in Bazzite.


I switched to Desktop mode on Bazzite (running KDE), changed IME to ibus in KDE setting and manually added these input methods, and confirmed they all work in Kate (text editor app) with physical keyboard. Observing the running process while in desktop mode:

```
$ ps aux | grep ibus
fsworld+   10760  0.0  0.4 1658680 97640 ?       Sl   19:05   0:00 /usr/libexec/kimpanel-ibus-panel
fsworld+   14839  0.4  0.2 885196 52848 ?        Sl   19:09   0:00 /usr/libexec/ibus-ui-gtk3 --enable-wayland-im --exec-daemon --daemon-args --xim --panel disable
fsworld+   14848  0.1  0.0 757712 12728 ?        Sl   19:09   0:00 ibus-daemon --xim --panel disable
fsworld+   14855  0.0  0.0 531024  7168 ?        Sl   19:09   0:00 /usr/libexec/ibus-dconf
fsworld+   14856  0.7  0.1 643484 29612 ?        Sl   19:09   0:01 /usr/libexec/ibus-extension-gtk3
fsworld+   14858  0.0  0.0 483900 16692 ?        Sl   19:09   0:00 /usr/libexec/ibus-x11 --kill-daemon
fsworld+   14867  0.0  0.0 530964  6976 ?        Ssl  19:09   0:00 /usr/libexec/ibus-portal
fsworld+   14876  0.0  0.0 457312  6924 ?        Sl   19:09   0:00 /usr/libexec/ibus-engine-simple
fsworld+   14914  6.6  0.4 796984 109508 ?       Sl   19:09   0:13 python3 /usr/share/ibus/setup/main.py ibus-setup
fsworld+   15008  0.1  0.1 578212 26276 ?        Sl   19:10   0:00 python3 /usr/share/ibus-anthy/engine/main.py --ibus
fsworld+   15014  0.1  0.2 652672 54412 ?        Sl   19:10   0:00 /usr/libexec/ibus-engine-libpinyin --ibus
fsworld+   15085  0.0  0.0 463916 11876 ?        Sl   19:11   0:00 /usr/libexec/ibus-engine-pinyin --ibus
fsworld+   15112  0.0  0.0 230336  2372 pts/1    S+   19:12   0:00 grep --color=auto ibus
```

Looks like the path is different for these ibus engines between SteamOS and Bazzite, which might explain why Steam client couldn't launch them properly in game mode.

I was trying to see if I can create symlinks to workaround it. However, `/usr/` is a protected folder under Bazzite so I don't know how to verify my assumption as of now.

**Comment by zhuzhichao** [comment]
@fsworld009  

Thank you for your attempt, I feel as if I've seen some hope.  👍 

> I was trying to see if I can create symlinks to workaround it. However, /usr/ is a protected folder under Bazzite so I don't know how to verify my assumption as of now.

I think you can temporarily disable selinux and then perform the test.

`sudo nano /etc/selinux/config`

Modify `SELINUX=enforcing` to `SELINUX=disabled`, then reboot.

Set Permission
`sudo mount -o remount,rw /usr`
(Restore permissions `sudo mount -o remount,ro /usr`)


Symlinks some files...


Sorry my steamdeck has been sold and I only have one rog ally left, so I can't try it. Looking forward to your good news.

**Comment by fsworld009** [comment]
@zhuzhichao thanks for your input. However I have some new findings to indicate that bin path differences are likely unrelated, so I won't trying to do that for now.

New observations:

When both SteamOS and Bazzite is booted, if I run `ibus engine` it would return

```
❯ ibus engine

(process:73238): IBUS-CRITICAL **: 21:33:11.677: ibus_bus_get_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
No engine is set.
```

Also `ps aux | grep ibus` shows both systems don't run ibus IME engines on boot:

```
# SteamOS
deck        1334  0.0  0.0 381092  9900 ?        Ssl  21:32   0:00 /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
deck        1357  0.0  0.0 306368  8356 ?        Sl   21:32   0:00 /usr/lib/ibus/ibus-dconf
deck        1364  0.0  0.0 380044  6144 ?        Ssl  21:32   0:00 /usr/lib/ibus/ibus-portal
deck        5449  0.0  0.0   6500  2432 pts/0    S+   21:36   0:00 grep --color=auto ibus

# Bazzite
fsworld+    2887  0.0  0.0 606324  7780 ?        Ssl  21:25   0:00 /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
fsworld+    2896  0.0  0.0 531028  6984 ?        Sl   21:25   0:00 /usr/libexec/ibus-dconf
fsworld+    2900  0.0  0.0 604828  7008 ?        Ssl  21:25   0:00 /usr/libexec/ibus-portal
fsworld+    9936  0.0  0.0 230336  2360 pts/0    S+   21:32   0:00 grep --color=auto ibus
```

However, on SteamOS, if I open virtual keyboard and click the switch IME button (the global icon) to JPN keyboard (anthy), the corresponding engine is started 

```
ps aux | grep ibus
deck        1334  0.0  0.0 381224 10156 ?        Ssl  21:32   0:00 /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
deck        1357  0.0  0.0 306368  8356 ?        Sl   21:32   0:00 /usr/lib/ibus/ibus-dconf
deck        1364  0.0  0.0 380044  6144 ?        Ssl  21:32   0:00 /usr/lib/ibus/ibus-portal
deck        5574  0.9  0.2 356040 33220 ?        Sl   21:37   0:00 /usr/sbin/python /usr/share/ibus-anthy/engine/main.py --ibus
deck        5604  0.0  0.0   6500  2304 pts/0    S+   21:38   0:00 grep --color=auto ibus
```

And `ibus engine` now returns `anthy`, indicating ibus has successfully switched to anthy input.


On Bazzite, no matter how much times I click switch IME button on the virtual keyboard, the engine process isn't run and `ibus engine` still returns `No engine is set`.

However, if I run `ibus engine anthy`, now the virtual keyboard can actually input Japanese, although it would always input Japanese no matter which keyboard I switch to on the virtual keyboard UI.

I can also confirm now the annthy engine is now running succesfully
```
$ ps aux | grep ibus
fsworld+    2887  0.0  0.0 606324  7780 ?        Ssl  21:25   0:00 /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
fsworld+    2896  0.0  0.0 531028  6984 ?        Sl   21:25   0:00 /usr/libexec/ibus-dconf
fsworld+    2900  0.0  0.0 604828  7008 ?        Ssl  21:25   0:00 /usr/libexec/ibus-portal
fsworld+   10505  5.1  0.1 578212 26240 ?        Sl   21:42   0:00 python3 /usr/share/ibus-anthy/engine/main.py --ibus
fsworld+   10428  0.0  0.0 230336  2360 pts/0    S+   21:41   0:00 grep --color=auto ibus
```

So I think the real issue is for some reason on Bazzite, ibus is not switching IMEs when you click the IME switch button on Steam Virtual keyboard.

It doesn't look like Steam client writes anything to any file in `/home/deck/.steam/steam/logs/` whcn switching IMEs, so currently no clue on how to investigate further.

**Comment by zhuzhichao** [comment]
@fsworld009 
A month has passed. 
I have given up, and switched from Bazzite to Sk-ChimeraOS, I have encountered fewer problems.
Sk-ChimeraOS is also very comprehensive, especially for the Chinese input.

Some Chinese developer have made some optimizations for the use of the Chinese environment.
<img width="864" alt="Image" src="https://github.com/user-attachments/assets/8dacdbf7-2ae8-428c-851f-ba930ac70027" />

Bazzite is also excellent, but the support for Chinese is terrible, unfortunately.

**Comment by fsworld009** [comment]
@zhuzhichao thanks for the information.

Just curious, could you check the ibus version installed in Sk-ChimeraOS? I'm wondering if the issue is caused by newer ibus version in Bazzite.

**Comment by zhuzhichao** [comment]
@zhuzhichao 

Here is Sk-ChimeraOS

```
$ sudo pacman -Qs | grep ibus
local/ibus 1.5.30-3
local/ibus-anthy 1.5.16-1
local/ibus-hangul 1.5.5-2
local/ibus-libpinyin 1.15.4-2
local/ibus-pinyin 1.5.1-2
local/ibus-rime 1.5.0-2
    Rime input method engine for ibus
local/ibus-table 1.17.4-2
local/ibus-table-chinese 1.8.12-3
    GObject wrapper for libusb1
local/libibus 1.5.30-3
local/libusb 1.0.27-1
local/libusbmuxd 2.1.0-1
```

Bazzite 

ibus-1.5.31-1.fc41.x86_64

You can try downgrading the version, maybe that will solve the problem.

**Comment by szescxz** [comment]
Downgrading `ibus` to 1.5.30 indeed resolves the issue.
```bash
# Get an empty working folder
$ mkdir ibus-fix && cd ibus-fix

# Download packages
$ wget https://kojipkgs.fedoraproject.org/packages/ibus/1.5.30/6.fc41/x86_64/ibus-1.5.30-6.fc41.x86_64.rpm
$ wget https://kojipkgs.fedoraproject.org/packages/ibus/1.5.30/6.fc41/x86_64/ibus-gtk2-1.5.30-6.fc41.x86_64.rpm
$ wget https://kojipkgs.fedoraproject.org/packages/ibus/1.5.30/6.fc41/x86_64/ibus-gtk3-1.5.30-6.fc41.x86_64.rpm
$ wget https://kojipkgs.fedoraproject.org/packages/ibus/1.5.30/6.fc41/x86_64/ibus-gtk4-1.5.30-6.fc41.x86_64.rpm
$ wget https://kojipkgs.fedoraproject.org/packages/ibus/1.5.30/6.fc41/x86_64/ibus-libs-1.5.30-6.fc41.x86_64.rpm
$ wget https://kojipkgs.fedoraproject.org/packages/ibus/1.5.30/6.fc41/x86_64/ibus-panel-1.5.30-6.fc41.x86_64.rpm
$ wget https://kojipkgs.fedoraproject.org/packages/ibus/1.5.30/6.fc41/noarch/ibus-setup-1.5.30-6.fc41.noarch.rpm

# Perform downgrade
$ sudo rpm-ostree override replace * --remove ibus-xinit

# Reboot to apply changes
# Remove the `ibus-fix` folder if you want to
```
I guess this is also why [`SK-ChimeraOS`](https://github.com/3003n/chimeraos), recommended by @zhuzhichao, [pins the `ibus` package](https://github.com/3003n/chimeraos/commit/b5f92f07d4746ebdcd6fedf5a3036827ac8ffba3).

@KyleGospo Any suggestions?

**Comment by KyleGospo** [comment]
That tracks, I'll see about downgrading it in the image

**Comment by szescxz** [comment]
After taking a closer look at `ibus` changelog, I believe `ibus` developers made [an intended change](https://github.com/ibus/ibus/commit/ee6b673fbea00fa0f4d4671fd4eaea92739a2b5c#diff-d549bde0658985c990e7af90083badcb9163a8323759ca65e3700e83dccf419d) which breaks [how the Steam OSK currently works](https://github.com/ublue-os/bazzite/issues/210#issuecomment-2537725069).
With 1.5.30, the global engine indeed gets changed as the Steam OSK changes.

Pinning the `ibus` package version seems to be the only option until Valve fixes it (I don't think we can patch their obfuscated JavaScript code easily).
