### ISSUE TITLE
Issues all the fucking way

### ISSUE THREAD

**Issue by LOLZSICKA** [ublue-os/bazzite#1917]
### Describe the bug

you guys should've worked on this much more than what it is now, what was the rush? could've kept this in the shadows UNTIL it was actually properly ready to go.

so fucking shit it failed to fully install properly twice, unintuitive install, doesn't direct user where to go, this is designed with advanced linux users in mind not gamers this fails as a gaming distro

i'd rather user debian 12 since im able to properly use prism launcher regardless of how it installs and discord since debian is accepted there but yet bazzite doesn't even have a native discord package

### What did you expect to happen?

get out ya wankers this sucks

### Output of `rpm-ostree status`

```shell

```

**Comment by p5** [comment]
Thanks for the feedback.  
Hope you have a great day.
Goodbye
