### ISSUE TITLE
Add xpadneo setup to Bazzite for Xbox Controller Bluetooth

### ISSUE THREAD

**Issue by duhow** [ublue-os/bazzite#1918]
### Describe the package

I have an Xbox Wireless Controller Shock Blue which has Bluetooth.

There is `xone` module installed, but I'd like to request `xpadneo` in order to pair and use the controller via Bluetooth.  
Otherwise I'd be playing with a short USB cable 😢 

I see there is a build in https://github.com/ublue-os/akmods , but I can't seem to build the module myself to use it.

---

✅ Solved, see below.

### Image

Desktop

**Comment by KyleGospo** [comment]
Xbox controllers are known to work over Bluetooth already, what issue are you having specifically?

**Comment by duhow** [comment]
Specific issue at the moment is "unable to find" the Xbox Bluetooth Controller in KDE, I did upgrade the 🕹  controller firmware recently to latest version 5.22.16 . Other Bluetooth devices appear without issues.

**Comment by duhow** [comment]
The issue was the battery 🔋 ... Despite the controller would light on, it did not have enough power to start the bluetooth pairing... After replacing the batteries (and even upgrade again the firmware), now it works.
