### ISSUE TITLE
Clapper Desktop File Missing

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#192]
There used to be a .desktop file for Clapper in /use/share/applications which has recently disappeared, so it does not appear in the GNOME applications list now.

**Comment by KyleGospo** [comment]
It was removed due to Clapper only being installed as a dependency for the Hanabi extension, new installs should get the GNOME Videos flatpak as a replacement.

**Comment by jacobranson** [comment]
Okay, thanks for clarifying. Is there somewhere I can see the changes made in updates for things like this in the future?

**Comment by KyleGospo** [comment]
Best place at the moment is the commit history for the main branch, since anything pushed there gets built and sent out.

That may improve in the near future.

**Comment by jacobranson** [comment]
Thanks for clarifying. I personally think it's a bit strange to ship the RPM just for the sake of an extension, and then not let the user use that RPM to play videos. I have to install the clapper Flatpak alongside the RPM if I want to actually use it on my system, having two installs of it feels strange, but it's honestly no big deal, I can just use the Flatpak install.

**Comment by KyleGospo** [comment]
Sorry for this use case being a little harmed here, what I might do is restore those .desktop files and only add a tag to hide them.

In the meantime if you get a clapper.desktop file from elsewhere you can just put it in ~/.local/share/applications and use the one that ships with the image to avoid installing it twice.

**Comment by jacobranson** [comment]
That sounds like a great compromise. Thanks!

**Comment by noelmiller** [comment]
Fixed in next release.
