### ISSUE TITLE
Streaming from Bazzite machine to steamlink no longer works

### ISSUE THREAD

**Issue by cyberfarmer-colin** [ublue-os/bazzite#1920]
### Describe the bug

On version 41.20241118.2 while trying to stream games from my bazzite host to either another computer via steamlink flatpak or phone via the android app the client gets stuck infinitely loading while the bazzite machine acts like everything is working normally.

### What did you expect to happen?

Steamlink actually loads the video stream from the host computer to the client

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:e4abb77ebd9a30e64ebac3aa6da1cd62a5c277b04cf16a456b18a0fdc65c80fd
                  Version: 41.20241118.2 (2024-11-19T02:56:07Z)
                     Diff: 145 upgraded, 1 removed, 1 added
            LocalPackages: lact-0.6.0-0.x86_64

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:568eaa6f01398dbe91c5740fbd8804bee5297ce2fa74720aed87a1a8acd0329b
                  Version: 41.20241112.1 (2024-11-12T23:57:36Z)
            LocalPackages: lact-0.6.0-0.x86_64
```

### Hardware

Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 XTX
Product Name: X570 Pro4

### Extra information or context

Steamlink still works as expected on bazzite 41.20241112.1
Streaming from the steam app not the steamlink app (both flatpak) still works on my other computer on version 41.20241118.2

**Comment by HikariKnight** [comment]
this is an issue valve has to fix in steamlink which we do not control. steamlink does not support wayland properly and is the reason why we suggest people to use sunshine instead (there is an ujust for it: `ujust setup-sunshine`)
it works in gamemode too

the client you need to use for sunshine is moonlight. however if you want it to work outside of your local network, then you need to do some port forwarding.
