### ISSUE TITLE
Update Mesa to 24.2.7 in unstable/testing

### ISSUE THREAD

**Issue by RayBa82** [ublue-os/bazzite#1921]
Mesa is not updated frequently, we are still on 24.2.4, there are various bugfixes for popular games including RDR2 which faces crashes on the current 24.2.4 version.

Please update Mesa driver version more frequent or provide an option to update the driver for the user.

**Comment by KyleGospo** [comment]
We update as often as Fedora does, we are now on this release. There is no plan for user upgradeable Mesa
