### ISSUE TITLE
Disable "disable-while-typing" on bazzite-deck for laptop users...

### ISSUE THREAD

**Issue by nadira-cpu** [ublue-os/bazzite#1924]
Opening a terminal while inside the gamemode/deck-mode you will be able to see that disable-while-typing is turned on via the output of:
libinput list-devices

Device:           SYNA88022:00 06CB:CE67 Touchpad
Kernel:           /dev/input/event7
Group:            5
Seat:             seat0, default
Size:             112x57mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a

The issue is that it causes the mouse to freeze when you play games, and it virtually makes a large number of games unplayable UNLESS you're playing them inside of KDE where this setting can be turned off.

I have tried creating a udev rule to force this blunder asunder, and without provail I did not succeed.
I have no idea how to fix this because google search engine optimization swamps me with irrelevant information no matter what operators I use, I cannot find a fix for this on reddit.

How would I address this? Thank you.

**Comment by KyleGospo** [comment]
https://github.com/ValveSoftware/gamescope/pull/1406
https://github.com/ValveSoftware/gamescope/pull/1291
