### ISSUE TITLE
Nvidia drivers included in Deck Images for EGPU / XGMobile support

### ISSUE THREAD

**Issue by TAGE7** [ublue-os/bazzite#1925]
### Nvidia support in deck images

Hello Bazzite team,

Firstly, I would like to extend my heartfelt appreciation for the incredible work you have done with the Deck image. It's a fantastic experience on my ROG Ally.

I am writing to kindly request the inclusion of official NVIDIA drivers in the Deck image. 

I understand that Handheld mode does not have official nvidia support, but it should be simple enough to switch between desktop and handheld mode to switch between egpu and onboard graphics with a few terminal commands. 

On the latest deck image, in desktop mode i can successfully get an nvidia egpu to be recognized and display but without drivers we cannot play with official egpu docks / diy egpus.

The inclusion of NVIDIA drivers would greatly benefit users with handhelds that support NVIDIA eGPUs, allowing them to utilize desktop mode for playing games offloaded to their eGPU seamlessly. This enhancement would eliminate the need to rebase and rollback when switching between docked and handheld modes, significantly improving the overall usability and convenience.

Thank you for considering this request!

### Image

Deck

**Comment by KyleGospo** [comment]
This will not happen until Nvidia puts out a driver that does not immediately crash gamemode.
