### ISSUE TITLE
Tweak default terminal workaround, so konsole is selectable 

### ISSUE THREAD

**Issue by Zeglius** [ublue-os/bazzite#1933]
Now that `ujust restore-terminal` isn't a thing anymore, it would be nice being able to select konsole as the default terminal, if the user chooses to.

**Comment by dnkmmr69420** [comment]
I think ptyix should just be installable as a flatpak for plasma variants

**Comment by dnkmmr69420** [comment]
I want konsole back. I think all system apps should use the same toolkit as the desktop enviroment. We could have an option to install pytix as a flatpak. I also think that having pytix on the image also downloads lots of libawdaitia dependencies too (not completely sure on this part)

**Comment by Zeglius** [comment]
> I want konsole back.

Konsole comes already preinstalled, it wasn't removed from the image.

> We could have an option to install pytix as a flatpak. I also think that having pytix on the image also downloads lots of libawdaitia dependencies too (not completely sure on this part)

That would  fall out of the scope of this issue. You might be interested in opening another issue.

**Comment by KyleGospo** [comment]
Konsole is being removed in favor of Ptyxis upstream
