### ISSUE TITLE
Handheld Daemon not working or not installing

### ISSUE THREAD

**Issue by BenRogBazzite** [ublue-os/bazzite#1935]
### Describe the bug

a rookie to linus so a don't know alot. installed Bazzite for my new Rod Ally X (due booted). everything seems to be working out just fine except for the Handheld Daemon. I have uninstalled and re-stalled Bazzite 3 to 4 time thing that will fix the issue but it just doesn't.  I followed the instruction on the Bazzite website to make sure i got the one for the handheld but it still does nothing. I found the Handheld Daemon app in the Lost and Found in the application menu, tried to install it and still nothing. Every video show it working right out the gate but mine doesn't. No videos on Handheld Daemon problems. Very confuted and don't know what else to do.

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Output of `rpm-ostree status`

```shell

```

**Comment by antheas** [comment]
`sudo systemctl enable --now hhd@$(whoami)`

**Comment by BenRogBazzite** [comment]
Well that fix it. Thanks a lot. couldn't have done it without your help.
