### ISSUE TITLE
Bazzite crashing in gamescope constantly

### ISSUE THREAD

**Issue by FredsMedia** [ublue-os/bazzite#1949]
### Describe the bug

Whenever doing an action in gaming mode (mainly seems to be quitting and launching a game, but it has also happened when pairing a Bluetooth device) there is a high chance the deck will crash, show verifying installation, then start back up.

### What did you expect to happen?

I expected the deck to quit, launch, and pair devices per normal and not reboot.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:8007944db4d5aad6e04952663533e2edd00db394af79216ade2e5f4de7d8fee2
                  Version: 41.20241125 (2024-11-26T03:49:41Z)
          LayeredPackages: sunshine
            LocalPackages: labymodlauncher-2.1.7-1.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:8007944db4d5aad6e04952663533e2edd00db394af79216ade2e5f4de7d8fee2
                  Version: 41.20241125 (2024-11-26T03:49:41Z)
          LayeredPackages: sunshine
```

### Hardware

Steam Deck LCD (Jupiter)

### Extra information or context

I feel this is a soft reboot as Bluetooth devices stay connected. I am using deck-GNOME and while this did happen occasionally with KDE it was nowhere near this frequent.

**Comment by FredsMedia** [comment]
Just installed KDE, same thing. Is this a hardware issue or a Bazzite issue?

**Comment by HikariKnight** [comment]
> Just installed KDE, same thing. Is this a hardware issue or a Bazzite issue?

cant replicate on my legion go or htpc
please provide logs after it has crashed once so someone can have a look at it
`~/.gamescope-stdout.log.old`
`~/.gamescope-cmd.log.old`

**Comment by FredsMedia** [comment]
I made a post on the subreddit, and we figured out it was because background game recording was on, and it is apparently an upstream issue that Valve needs to fix.
