### ISSUE TITLE
Can't install on Lenovo Legion

### ISSUE THREAD

**Issue by marcdraco** [ublue-os/bazzite#1951]
### Describe the bug

I've managed to get Bazzite working (working around the microSD bug) on the Steam Deck but when I've come to put the system on the Lenovo Legion laptop it just keeps crashing with a fatal error 

### What did you expect to happen?

Installer crashes during install with a fatal error.

I've read that some people have connected to the network to do this but I have issues with my connection that might cause incorrect responses from the HTTPS:// connections (not a clue why). 

However, I'm using the full 9gig image so presumably that doesn't need to access the web during the install.

I don't game much and don't particularly care for the Legion either (i7, RTX4060 mobile) because the thing sucks up electricity like a flat Tesla and sounds like a 747 taking off. (Ok, I'm exaggerating a little but you get the idea.)

Probably should have paid more attention to what I was buying first...

### Output of `rpm-ostree status`

```shell

```

### Extra information or context

Can't provide much more than what I have. It's getting tougher since I retired because I simply don't have time to learn all the GitHub conventions.  For that, I humbly apologize, but I'm limited to what I can read on the screen (which isn't much).

**Comment by KyleGospo** [comment]
Can you post a picture of the air you're getting in the installer?

**Comment by marcdraco** [comment]
This is a duplicate of an existing bug. 

In my case it appeared that the system had problems with the EFI partition. There are serious issues with everything from Blivet to the automated partitioner than break when (for example) there is an existing dual boot or (some have mentioned) even on a blank disk.

I assume this is upstream and not related to Bazzite directly but with such a complex system the downstream guys get the blame for upstream bugs.
