### ISSUE TITLE
Gwenview (KDE image viewer) does not support HEIF images

### ISSUE THREAD

**Issue by duhow** [ublue-os/bazzite#1961]
### Describe the package

Having bazzite `41.20241125` image:

```
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable (index: 0)
                   Digest: sha256:46200950e02bc43c67b69bc69614f47b4d2450177e9a5801be45d15e1b9cf6bc
                  Version: 41.20241125 (2024-11-26T03:49:39Z)
               BaseCommit: 886b47abc927c1f18cb4c2f5260db9e04d42da862130f78bc7f3e3d0c123f1ec
                   Commit: 8e80a6835c4c623222e1eefc21d2c57fa0b4c9e23dc423445284b266cae239c4
```

The following packages are currently installed:

```
libheif-1.18.2-4.fc41.x86_64
heif-pixbuf-loader-1.18.2-4.fc41.x86_64
qt5-qtimageformats-5.15.15-1.fc41.x86_64
qt6-qtimageformats-6.8.0-1.fc41.x86_64
kf6-kimageformats-6.8.0-1.fc41.x86_64
```

Gwenview fails to open those photo files.

![Image](https://github.com/user-attachments/assets/66604a08-7eda-4045-a8fb-6a7b7b181c98)

However, Dolphin can render thumbnail images correctly.

---

This format file is used in iPhone and some modern Android cameras.

### Image

Desktop

**Comment by HikariKnight** [comment]
Gwenview is provided as a flatpak, [this issue has to be fixed in the flatpak](https://github.com/flathub/org.kde.gwenview/issues/158) not the system.
