### ISSUE TITLE
Black screen after logging into Plasma via SDDM

### ISSUE THREAD

**Issue by Ascent7910** [ublue-os/bazzite#1969]
### Describe the bug

When I login to my PC via SDDM it just appears a black screen. The computer still works as I can enter the ttys and do cli stuff but plasma does not start unless I do `startplasma` in a tty.

### What did you expect to happen?

What I expect to happen is that when I login with SDDM it takes me to my Plasma session right after.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:testing
                   Digest: sha256:45cd7d26a4b5fa5c1a8263aefd74bddbfa3de00fddf8d70870802025bb49b117
                  Version: testing-41.20241210 (2024-12-10T08:19:43Z)
          LayeredPackages: sunshine

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:stable
                   Digest: sha256:6983413a64089ba365765c4da1e6b167230b97b61d2c884acfa9fc8e580e7f23
                  Version: 41.20241125 (2024-11-26T03:52:52Z)
          LayeredPackages: sunshine
```

### Hardware

CPU: Intel i5-14600k
GPU: Nvidia 4070 Super
RAM: 32GB

**Comment by atimeofday** [comment]
Hello,

For additional information to help track down this issue, could you confirm whether this issue is a new development upon rebasing from `41.20241125` to `testing-41.20241210` as shown in the embedded `rpm-ostree status` output? If so, as a step further, it may be helpful to perform additional rebase operations to identify precisely which version and/or branch (between those two) introduces the issue.

**Comment by Ascent7910** [comment]
Hello I have rebased the latest stable and testing which is version `41.20241210` and also the previous version in the ostree status `41.20241125`. All three have led to the same issue mentioned. If there is a way I can get logs for SDDM to maybe see what is the barrier I can also share those as well but not sure how to get it.

**Comment by Zeglius** [comment]
> Hello I have rebased the latest stable and testing which is version `41.20241210` and also the previous version in the ostree status `41.20241125`. All three have led to the same issue mentioned. If there is a way I can get logs for SDDM to maybe see what is the barrier I can also share those as well but not sure how to get it.

`journalctl -u sddm.service -r`

**Comment by Ascent7910** [comment]
Thank you for the command. When using it in a tty it shows that it starts to run `/usr/bin/startplasma-wayland` but, for some reason will not display unless triggered manually via `startplasma-wayland`.

**Comment by Ascent7910** [comment]
Update to this after removing the `sunshine` layer plasma seems to be booting up like normal. Not really sure why this would fix the issue.

**Comment by atimeofday** [comment]
> Update to this after removing the `sunshine` layer plasma seems to be booting up like normal. Not really sure why this would fix the issue.

Thanks for the update! I'll keep an eye out for that in case someone else runs into it. Do you know if the Sunshine flatpak works right on your system?

**Comment by erutan** [comment]
The flatpak version didn't work for me on bluefin a few days ago, in general sunshine seems to be something that needs a daemon going in the background to talk to and doesn't work well containerized (like LACT etc).

There is a COPR beta branch that works well on Fedora Workstation that could be rpm-ostreed, but I haven't had a chance to try it: https://github.com/ublue-os/bazzite/issues/1710#issuecomment-2546463314

Judging by https://github.com/LizardByte/Sunshine/issues/2948 the ujust method is still broken.

**Comment by Ascent7910** [comment]
Yeah have not really had any luck with the flatpak build of sunshine so not sure what to do about it.

**Comment by evrowe** [comment]
Chiming in to add that I intermittently had this issue across the last few releases and removing the sunshine layer from my install has completely addressed it. I have also had no luck with the flatpak build so hopefully their COPR beta branch will land soon!

I'm happy to test rpm-ostreeing it to see if it improves things at all.

**Comment by Ascent7910** [comment]
As of the latest stable update with sunshine being in the image the issues I had before do not exist and is working as expected. Closing this issue for now but will let the thread know if anything comes up.
