### ISSUE TITLE
pycurl failed to install

### ISSUE THREAD

**Issue by serious96** [ublue-os/bazzite#1971]
### Describe the bug

deck@bazzite:~$ pip install pycurl
Defaulting to user installation because normal site-packages is not writeable
Collecting pycurl
  Using cached pycurl-7.45.3.tar.gz (236 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "<string>", line 229, in configure_unix
        File "/usr/lib64/python3.13/subprocess.py", line 1036, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              pass_fds, cwd, env,
                              ^^^^^^^^^^^^^^^^^^^
          ...<5 lines>...
                              gid, gids, uid, umask,
                              ^^^^^^^^^^^^^^^^^^^^^^
                              start_new_session, process_group)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib64/python3.13/subprocess.py", line 1966, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/deck/.local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/deck/.local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/deck/.local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-kzzbevdo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kzzbevdo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-kzzbevdo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kzzbevdo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 997, in <module>
        File "<string>", line 658, in get_extension
        File "<string>", line 93, in __init__
        File "<string>", line 234, in configure_unix
      ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

-----------------------------------------------------------------------------------------------------------------------------------------------------------

i got this error message while installing pycurl, this is on fresh install bazzite 41.20241210

### What did you expect to happen?

installation should be finished.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:0e9c801cd216a3fab7f99a97b73f4594d54512cf0f436d7935153caa4530a2b6
                  Version: 41.20241210 (2024-12-10T08:56:00Z)
          LayeredPackages: mullvad-vpn

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b53cd439ae41171b111b0436d934b3f0814acfa4700b95786e5c4792305455bb
                  Version: 41.20241209 (2024-12-09T05:04:21Z)
          LayeredPackages: mullvad-vpn
```

### Hardware

Lenovo Legion Go KDE Image

### Extra information or context

_No response_

**Comment by atimeofday** [comment]
Hello,

This does not seem like an issue which Bazzite can or should fix. A cursory search and some testing on my end indicates that the error may have occurred because the `libcurl-devel` package is not installed. Although that could be layered, it should not be.

(https://stackoverflow.com/questions/23937933/could-not-run-curl-config-errno-2-no-such-file-or-directory-when-installing)

The recommended method of installing, managing, and using such packages is through Distrobox containers. The `distrobox-export` feature should allow packages to be seamlessly used on the host system, while retaining the various benefits of containerization. 

Please let us know if that is a viable way to install pycurl for your use case, and if there is something Bazzite could potentially do to improve the discoverability of Distrobox as a recommended tool - here is a link to the Bazzite documentation for using Distrobox:  

https://docs.bazzite.gg/Installing_and_Managing_Software/Distrobox/

**Comment by serious96** [comment]
`Building wheel for pycurl (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycurl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Using curl-config (libcurl 8.9.1)
      Using SSL library: OpenSSL/LibreSSL/BoringSSL
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-313/curl
      copying python/curl/__init__.py -> build/lib.linux-x86_64-cpython-313/curl
      running build_ext
      building 'pycurl' extension
      creating build/temp.linux-x86_64-cpython-313/src
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -O3 -fPIC -DPYCURL_VERSION=\"7.45.3\" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/usr/include/python3.13 -c src/docstrings.c -o build/temp.linux-x86_64-cpython-313/src/docstrings.o
      In file included from src/docstrings.c:4:
      src/pycurl.h:5:10: fatal error: Python.h: No such file or directory
          5 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycurl
  Building wheel for slixmpp (pyproject.toml) ... done
  Created wheel for slixmpp: filename=slixmpp-1.8.5-py3-none-any.whl size=510749 sha256=02cf9da805f6d7ee99070ae68cc8a49b0183a8a272f6eda0a2d3aabe612379de
  Stored in directory: /var/home/deck/.cache/pip/wheels/21/04/74/17114e57991b7310642fae1d9ec4142cef12439edc4dbc666a
  Building wheel for msgspec (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for msgspec (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/__init__.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/_json_schema.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/_utils.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/_version.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/inspect.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/json.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/msgpack.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/structs.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/toml.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/yaml.py -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/__init__.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/json.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/msgpack.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/structs.pyi -> build/lib.linux-x86_64-cpython-313/msgspec
      copying msgspec/py.typed -> build/lib.linux-x86_64-cpython-313/msgspec
      UPDATING build/lib.linux-x86_64-cpython-313/msgspec/_version.py
      set build/lib.linux-x86_64-cpython-313/msgspec/_version.py to '0.18.6'
      running build_ext
      building 'msgspec._core' extension
      creating build/temp.linux-x86_64-cpython-313/msgspec
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -O3 -fPIC -I/usr/include/python3.13 -c msgspec/_core.c -o build/temp.linux-x86_64-cpython-313/msgspec/_core.o
      msgspec/_core.c:9:10: fatal error: Python.h: No such file or directory
          9 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for msgspec
Successfully built bitmath Flask-Themes2 slixmpp
Failed to build pycurl msgspec
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycurl, msgspec)
`

just tried reinstall pyload python project while using layered libcurl-devel package but i still encountered error.
i will just try the distrobox method, i don't know what's changed with fedora 41 base. But last time i tried installing the  same pyload project in bazzite fedora 40, i doesn't trigger any error messages.

**Comment by atimeofday** [comment]
Hmmm, alright, thanks for the update! It is good to eliminate at least one possible cause, and very good to know that the same installation did work in Bazzite/Fedora 40.

Let me know if you run into trouble with installing or using it in a distrobox; I would be happy to try to help.

**Comment by serious96** [comment]
i'm using distrobox and using pipx to run the python project. so eerything is good just take more step than usual.
