### ISSUE TITLE
Forgotten dirs for `local` systemd-unit-files

### ISSUE THREAD

**Issue by TriMoon** [ublue-os/bazzite#1981]
### Describe the bug

See: [Forgotten dirs for local systemd-unit-files](https://github.com/fedora-selinux/selinux-policy/issues/2479) at `fedora-selinux/selinux-policy` repo.

### What did you expect to happen?

I expected for the service to start at boot without SELinux denials.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:254a17f27cead0ce16b5c08c56799c30ef6f2e07b8aa34494d9969852b5903cd
                  Version: 41.20241210 (2024-12-10T08:55:14Z)
            LocalPackages: epson-inkjet-printer-escpr-1.8.5-1.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:10ebb6e959a7574a56cd90451652eb3cc2ce6e406465661092875ea91d6318f3
                  Version: 41.20241104 (2024-11-04T05:00:08Z)
            LocalPackages: epson-inkjet-printer-escpr-1.8.5-1.x86_64 lact-0.5.6-0.x86_64
```

### Hardware

PC

### Extra information or context

I'm trying to make use of the service of [Asus X670e Ethernet Fix](https://gitlab.com/trimoon-inc/asus_x670e_ethernet_fix) under `/usr/local/lib/systemd/system`...

**Comment by KyleGospo** [comment]
https://github.com/fedora-selinux/selinux-policy/issues/2479#issuecomment-2538684583

**Comment by TriMoon** [comment]
@KyleGospo Any idea why the service isn't started at boot-up, while it shows as enabled?
Is it an SELinux problem or something that is ostree related?
