### ISSUE TITLE
Return to Gaming Mode option does not work

### ISSUE THREAD

**Issue by DrKoneko** [ublue-os/bazzite#199]
Any time I click on the "Return to gaming mode" icon on the desktop the screen goes dark followed by the startup animation. The desktop appears and then steam opens. When opened my account is signed out and by signing back in nothing happens. Big picture mode doesn't achieve the same effect because I can't use multiple features of the regular deck menu.

**Comment by EyeCantCU** [comment]
It sounds like gamescope autologin didn't get enabled. Try running `just enable-gamescope-autologin` and rebooting

**Comment by EyeCantCU** [comment]
It sounds like gamescope autologin didn't get enabled. Try running `just enable-gamescope-autologin` and rebooting

**Comment by KyleGospo** [comment]
Note that the above should have been done by virtue of finishing the bazzite portal at least once.

**Comment by Elcapone86** [comment]
Is the Gaming Mode only available in the Steam version? I now have the NVIDIA version installed on my OXP but no Gaming Mode.

**Comment by KyleGospo** [comment]
That's correct, even if the desktop version supported it it's completely broken on Nvidia GPUs.

**Comment by Elcapone86** [comment]
> That's correct, even if the desktop version supported it it's completely broken on Nvidia GPUs.

does it run in the normal version? Is there a game UI in the normal version?

**Comment by KyleGospo** [comment]
You can use big picture mode, but I believe it still has known performance issues specifically on Nvidia hardware.

**Comment by Elcapone86** [comment]
> You can use big picture mode, but I believe it still has known performance issues specifically on Nvidia hardware.

Are there also Deckyloader and Mangohud for the Big Picture Mode? I would also switch to the normal version if there is a Game Ui. I only installed the Nvidia version because of my eGpu.
