### ISSUE TITLE
When opened through a .desktop (including start menu) kate can't find lua-language-server.

### ISSUE THREAD

**Issue by Eddieddg1** [ublue-os/bazzite#2006]
### Describe the bug

When opened through a .desktop (including start menu) kate can't find lua-language-server. I made a reddit post on [r/bazzite](https://www.reddit.com/r/Bazzite/comments/1hjvlhx/kate_cant_find_lualanguageserver/).

When I open Kate from the start menu or from a .desktop it can't find lua-language-server, but if I were to open a terminal and enter "kate" it can find lua-language-server. I haven't tested any other language server since I do not need them.

I installed lua-language-server with brew.

### What did you expect to happen?

I expected kate to find the language server without a problem. Oh and I think this is a general problem with the .desktops and not necessarily a problem with kate. it could be.

### Output of `rpm-ostree status`

```shell

```

**Comment by Eddieddg1** [comment]
I just installed and tested bash-language-server and got the exact same problem.

**Comment by Zeglius** [comment]
Yeah so the problem here is that brew binaries path is not appended to PATH when a program is launched from a .desktop shortcut, as it doesn't use bash (and by extension, the brew.sh) to open an app.

**Comment by Eddieddg1** [comment]
that explains why I can't open .desktops from the terminal

**Comment by Zeglius** [comment]
A possible solution would be modifying the Kate shortcut to execute Kate inside an interactive bash session.

However that should be done by the users themselves, doing that ourselves would carry possible issues, as using interactive bash sessions willy nilly would trigger unexpected side effects.

**Comment by Eddieddg1** [comment]
yeah, I just use a terminal to spawn kate. It is simple and it works.
