### ISSUE TITLE
obs-vkcapture does not work with 32 bit games

### ISSUE THREAD

**Issue by QuickFastly** [ublue-os/bazzite#2020]
### Describe the bug

I just did a fresh install of bazzite, so everything should be as default as it gets. The only package I've layered is `mullvad-vpn`. I set up my Steam library using the preinstalled native Steam, and moved my old Bottles (flatpak) games into new Lutris (native) prefixes, then installed OBS, the VK capture plugin, and the flatpak vulkan layer through the terminal. I did NOT install OBS from the first boot portal, so if that does anything special, that might be my whole problem.

After adding `obs-gamecapture %command%` into the launch options of a couple of my games, nothing seemed to be working.

After pulling my hair out over it and troubleshooting for several hours, including testing with both `vkcube` and `glxgears` (both captured fine), I realized that apart from one game, everything I was testing was very old, so I tried loading a more recent game, and it captured fine.

I also tested installing Bottles as a flatpak and running one of my old games through that instead. It captured properly. Out of curiosity, I rebased to `testing` just to see if there's been an update that fixes whatever's going on here, but nothing changed.

That made me think that for some reason, I didn't have the 32 bit version of the native vkcapture package installed, but `rpm -qa | grep obs` returns the following:
```
obs-vkcapture-common-0.0.git.354.aa3c43a0-1.fc41.noarch
obs-vkcapture-vulkan-layer-common-0.0.git.354.aa3c43a0-1.fc41.x86_64
libobs_vkcapture-0.0.git.354.aa3c43a0-1.fc41.x86_64
libobs_glcapture-0.0.git.354.aa3c43a0-1.fc41.x86_64
libobs_vkcapture-0.0.git.354.aa3c43a0-1.fc41.i686
libobs_glcapture-0.0.git.354.aa3c43a0-1.fc41.i686
```
The 64 bit files are in `/usr/lib64` and what I assume to be the 32 bit files are in `/usr/lib`

So, in short:
- OBS installed as flatpak, including necessary flatpak plugin and vulkan layer
- 64 bit games running through native Steam or native Lutris capture as expected
- 32 bit games running through native Steam or native Lutris do NOT capture
- 32 bit games running through flatpak Bottles DO still capture
- For whatever reason, the 32 bit version of native vkcapture is not being loaded by flatpak OBS

### What did you expect to happen?

I expect to be able to enter `obs-gamecapture %command%` in the launch options of any game and have capture functionality working, regardless of whether the game is 64 or 32 bit, and regardless of vulkan or opengl.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:777e4de18ea2dd200e214723a0832cefe01cf10cb9830b05665b95f88ab8760d
                  Version: 41.20241216 (2024-12-16T05:02:15Z)
          LayeredPackages: mullvad-vpn
            LocalPackages: lact-0.6.0-0.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:testing
                   Digest: sha256:30dd06d2d4e64592505b3c5bfe9c5c1f71911aa50e0b1d978f0fa5792b368e25
                  Version: testing-41.20241225.1 (2024-12-25T06:10:57Z)
          LayeredPackages: mullvad-vpn
            LocalPackages: lact-0.6.0-0.x86_64
```

**Comment by KyleGospo** [comment]
Will be fixed in the next build

**Comment by QuickFastly** [comment]
Rebased to testing again and confirmed, updating from 354 to 355 fixed it. Thank you.
