### ISSUE TITLE
no HDR badge on moonlight Steam Deck OLED

### ISSUE THREAD

**Issue by solemgar** [ublue-os/bazzite#2027]
### Describe the bug

Not sure if this is happening to others, but when running moonlight on the steam deck OLED with HDR enabled, I do not see the HDR badge enabled on the brightness settings. This works with Chiaki, for example.

The codec information reports HEVC 10 bit hdr, so I guess HDR is ok? Wondering if this is the same for everyone or if I am doing somehting wrong

### What did you expect to happen?

Expected to see the HDR badge on the brightness settings.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:e47786f5b8a19c2501afaa32afb76072a668b86cda836e49d3e0ed336afd453f
                  Version: 41.20241118.2 (2024-11-19T02:54:35Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:1be077d9f954b19592eaf0090f6f96531353e005e8303e15fc7ff2f69b3e48df
                  Version: 41.20241112.1 (2024-11-12T23:57:05Z)
```

### Hardware

Steam Deck OLED

cat /sys/devices/virtual/dmi/id/product_name
Galileo

**Comment by solemgar** [comment]
Closing this one, PBCK.

**Comment by jcchikikomori** [comment]
> Closing this one, PBCK. Solved by installing appimage instead of flatpack (or potentially an issue with Decky, unsure). Apologies for not doing further troubleshooting before opening.

This is probably the Flatpak version is looking for the gamescope flatpak package.
