### ISSUE TITLE
[Steam Deck] Wayland cant push the same resolution/refresh rate as X

### ISSUE THREAD

**Issue by JaxiiRuff** [ublue-os/bazzite#204]
On normal X I can push 3440x1440@100hz with no issues but in Wayland I can only use 60hz. The other options black screen. 

My weaker laptop can do 100hz just fine on Wayland with the same resolution on the same dock. I think displaylink is to blame since I dont use that on my laptop and freesync is enabled on the monitor if that helps.

**Comment by RodoMa92** [comment]
Freesync is bugged on my panel and kills the output from the official Dock if it's on. Try to disable freesync and see if the situation changes.
