### ISSUE TITLE
[GNOME] Night light not working on deck

### ISSUE THREAD

**Issue by PranavSakthivel** [ublue-os/bazzite#205]
Thanks for maintaining and developing this project! 

Night light does not seem to work in game mode or desktop mode. I’ve installed bazzite-deck-gnome, happy to provide any other info that’s needed.  

Occasionally I’ve noticed night light will apply to just the steam menu when I open it from in game, but it causes severe performance issues and disable itself randomly.

**Comment by fiftydinar** [comment]
https://universal-blue.org/images/bazzite/FAQ/#why-isnt-night-mode-or-color-saturation-working-on-my-steam-deck

**Comment by fiftydinar** [comment]
Oh, you use Gnome.
Not sure how to fix that there.
Will wait for other people to chime in.

**Comment by KyleGospo** [comment]
GNOME requires a calibrated color profile for every display to change color temp, we just added two new ones for matte & reflective decks, check under color settings in GNOME and see if applying one fixes this for you.

**Comment by unicornsandcandies** [comment]
> Hi, thanks for the response. I have a 512gb matte screen and I’m not sure which profile to apply, so I went with the first one labeled “08/27/2023 - ANX7530 U #1 2023-08-27 15-02 2.2 S XYZLUT+MTX”. Unfortunately night light still does not seem to work with the color profile enabled.

Tested with every color profile and same thing

**Comment by noelmiller** [comment]
Switching to GDM will resolve this. @EyeCantCU

**Comment by EyeCantCU** [comment]
> Switching to GDM will resolve this. @EyeCantCU 

I'll take another shot at getting our autologin implementation working with GDM this week
