### ISSUE TITLE
ROG Ally controller/Audio issues

### ISSUE THREAD

**Issue by eaglemmoomin** [ublue-os/bazzite#212]
Hi,

Out of curiosity I tried installing Bazzite on my Ally yesterday using the SteamDeck install options. Sadly I think Bazzite has similar issues to the ones ChimeraOS had with the Ally. Bluetooth is working OK which was interesting, but audio is not. I read the 6.5 kernel has fixes for the audio but I was wondering if there is anyway to get the built in controller  detected as a device by the OS. As game mode isn't controllable without M+K.

**Comment by eaglemmoomin** [comment]
Nope I lied just reinstalled it. No Wifi or Bluetooth either.  Most of the Allys hardware isn't being picked up by the OS. No idea how I had bluetooth and WiFi working earlier.

**Comment by KyleGospo** [comment]
https://github.com/ublue-os/bazzite/pull/162

**Comment by KyleGospo** [comment]
`xpad` is blacklisted by `xone`, there is a renamed xpad driver with xbox one controllers removed, named `xpad-noone`.

**Comment by eaglemmoomin** [comment]
Thanks I'll take a look at xpad-noone. Thanks for the link to the PR. I was wondering how much I could get going out of the currently broken elements of the Ally going IE game controller, bluetooth, wifi, audio.

**Comment by eaglemmoomin** [comment]
So interestingly today, Bluetooth is working ok?
Also the WiFi adapter is being detected. I wonder if there is a similar suspend issue with Bazzite where some devices don't 'wake' after a sleep/suspend.

**Comment by KyleGospo** [comment]
xpad-noone, xone, and xpadneo are all pre-installed and functional out of the box, upstream xpad is blacklisted and unneeded.

**Comment by eaglemmoomin** [comment]
Ok  I understand that xone clashes with the original xpad kernel driver. But that doesn't answer the question around why Bazzite isn't able to detect the built in controller on a ROG Ally?

Looking in the code of that link I can see that xpad-noone.c contains the ID I posted the other day eg  ID 045e:028e

**Comment by eaglemmoomin** [comment]
Nope, nothing.

**Comment by eaglemmoomin** [comment]
Problem hasn't been since change.
