### ISSUE TITLE
gaming mode not working

### ISSUE THREAD

**Issue by mindtheegab** [ublue-os/bazzite#214]
fresh install on steamdeck with  latest (1.0.1)deck-gnome, first boot it gives a fatal error about steam not having internet even if internet is available.

manually launching steam fixes that but the go back to gaming mode just flashes the screen black and goes back to desktop. im also noticing a lot of black flashes while not doing anything.

also tested the deck-kde version on my desktop with amd gpu and steam behaves the same, stuck in desktop mode.

oh plus everytime you click go back to gaming mode steam gets logged out, very annoying and its preventing me from doing further tests

**Comment by KyleGospo** [comment]
Was able to reproduce this, it's an issue with the new -steamdeck launch option.

To fix this on your end, switch back to desktop mode, make sure steam has been run the point of at least showing the login screen (if not logged in), and then run "Bazzite Portal" to completion. I was able to get to game mode after that. New installs skip the bug by refusing to launch with -steamdeck until needed files are present in `~/.local/share/Steam`
