### ISSUE TITLE
Image Updates 

### ISSUE THREAD

**Issue by smerschjohann** [ublue-os/bazzite#217]
Hi guys,

first, thanks for this awesome OS works very good so far on my Steam Deck. It's fun to have a look at the sources and understand how everything fits together.
I currently read the sources to have a better understanding on Fedora Silverblue and the whole rpm-ostree approach.

While doing so, I think I found some issues in the update progress:

1. Parts of the Bazzite Portal configuration cannot be changed after they are set once. For example that's true for the "use ext4 for sdcard" part. There is no definition to reactive it. I had to look in the sources to find out how to activate it later. What is the long term approach here? Should the user be able to run the Portal multiple times or have a FAQ page with e.g. just commands for that?

2. The bazzite-hardware-setup is not rerun if it previously run (https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/lib/systemd/system/bazzite-hardware-setup.service#L10), as the file is generated after the first time. This is valid if no changes were made to the bazzite-hardware-setup, but if you would make changes to that file, it will lead to inconsistencies between first time setup and upgrades. Especially the kernel parameters can not be altered anymore. Wouldn't it be better to either save the current base image hash or the bazzite-hardware-setup hash to this done file. Or always run the script but just compare if there are any differences between currently activate kernel arguments and the desired ones?

**Comment by KyleGospo** [comment]
#2 is being addressed in open PRs right now, #1 will take some changes in Yafti but we'd love to do it.
