### ISSUE TITLE
Login scripts not running after rebasing to Bazzite

### ISSUE THREAD

**Issue by aaylnx** [ublue-os/bazzite#218]
I'm brand new to bazzite, and I'm stunned at how nice it is.  Thank you everyone who has worked on this.  

I'm having one issue. Prior to rebasing to bazzite from kinoite-ublue, I had a login script in ~/.config/autostart which would run every time I logged into KDE. After rebasing scripts and programs in ~/.config/autostart do not run at login. 

Interestingly, If I log in, then log back out, then log in again scripts in autostart DO run. The bazzite welcome/setup program (which is also in there) also runs when I do this. If anyone has any thoughts on this, I'd be very grateful.

Thanks again for all the great work!!!!

**Comment by aaylnx** [comment]
I think the problem has something to do with my script and not anything related to autostart in bazzite. I'll continue to look in on this and post back if can't get things working.

**Comment by dgmann** [comment]
I have exactly the same issue, did you find a solution for this?

**Comment by aaylnx** [comment]
@dgmann, yes I did find a solution. For me the issue was related to running graphical apps, specifically under X. Command line based applications ran fine upon startup. I'm not entirely sure why, but I needed certain environmental variables to be made explicit before the apps would start. I use one master script in ~/.config/autostart which lists all of the programs I want to autostart.

I had to add the following to the beginning of the script.

```
export DISPLAY=:0

# Find the xauth file and set XAUTHORITY
xauth_file=$(find /run/user/1000 -maxdepth 1 -type f -name 'xauth_*' | head -n 1)

if [ -n "$xauth_file" ]; then
    export XAUTHORITY="$xauth_file"
else
    echo "xauth file not found!"
fi

sleep 10
```
`export DISPLAY=:0` does what it says, namely, run programs on display 0

The rest finds and sets the XAUTHORITY file which is located in /run/user/1000.

I need all of this because I'm running X and not Wayland. I don't really know if there are issues under Wayland. If there are, none of this should work though.

Hope this helps you.

**Comment by dgmann** [comment]
@aaylnx thanks for the hint. I am on wayland and managed to fix it by creating a `.desktop` file in ~/.config/autostart: 
```
[Desktop Entry]
Exec=systemctl --user start --all *@autostart.service
Name=Launch
Type=Application
```

**Comment by aaylnx** [comment]
@dgmann Interesting. So I'm trying to figure out what this does exactly to fix things. And I'm wondering what exactly the underlying problem is. Is this a Bazzite specific problem?

**Comment by dgmann** [comment]
@aaylnx before Bazzite I used the ublue Nvidia image where I did not have this issue. So I assume it is something related to Bazzite.
