### ISSUE TITLE
Can't install Nix package manager

### ISSUE THREAD

**Issue by ToRRent1812** [ublue-os/bazzite#224]
Hi guys, I've downloaded bazzite iso yesterday to try out on a wm before full install.
When I pick to install nix package manager, console shows this message. 
![Screenshot_20230829_231354](https://github.com/ublue-os/bazzite/assets/4561094/fbdc3a3a-5c40-4a15-8e0d-1458c062605c)

**Comment by KyleGospo** [comment]
Should be fixed in the latest version, sorry for the trouble. We just switched to a new installer for this feature.
