### ISSUE TITLE
steamtinkerlaunch missing dependencies?

### ISSUE THREAD

**Issue by DylanTackoor** [ublue-os/bazzite#225]
To get `steamtinkerlaunch` working I had to `sudo pacman -Syu yad xdotool org-xwininfo`. Fwiw, I'm using gnome but am still using protonup-qt [before this commit](https://github.com/ublue-os/bazzite/commit/138e47986fe46daef70ed560f7b35b754a33c8ad) because I couldn't find an option in ProtonPlus to install it 🤷

**Comment by KyleGospo** [comment]
These dependencies weren't in bazzite-arch, they are now. Thanks!
