### ISSUE TITLE
Right menu on steam does not show up during games

### ISSUE THREAD

**Issue by mindtheegab** [ublue-os/bazzite#228]
so pressing home+A button in steam should pull up the right steam menu, on the keyboard you can access that by ctrl+2

this does not work at all via controller and the keyboard shortcut only works OUTSIDE of games. so to pull it up you have to press the home button and recall the steam overlay and then hit ctrl+2 to show the menu.

also holding the home button doesnt show the steam shortcuts

running latest version

**Comment by KyleGospo** [comment]
Try pressing home and then pressing a, rather than holding home and pressing a.

There is a similar issue open at Chimera OS that recommends doing that.
