### ISSUE TITLE
Error during install -  loading gets stuck on "deploying ghcr.io/ublue-os/bazzite-gnome-nvidia:38"

### ISSUE THREAD

**Issue by kolegaa** [ublue-os/bazzite#234]
previously installation ended with an error "the command 'ostree container image deploy --sysroot=/mnt/sysimage--image=ghcr.io/ublue-os/bazzite-gnome-nvidia:38 --no-signature-verification' exited with code 1"
i switched to ethernet (i was on wifi earlier)
the error didn't show up anymore but the loading bar got stuck on "deploying ghcr.io/ublue-os/bazzite-gnome-nvidia:38"

**Comment by kolegaa** [comment]
the issue has fixed itself

**Comment by kolegaa** [comment]
the issue has fixed itself

**Comment by ilham-Hamzah** [comment]
same issue for the deck version. So, it will resolve after a few days? whats causing it?

**Comment by Cybericecream** [comment]
How long did you leave the installer? I assume the install has failed so I reboot.
