### ISSUE TITLE
[GNOME] Unable to rollback after rebasing to Bazzite

### ISSUE THREAD

**Issue by Cr4tes** [ublue-os/bazzite#237]
Rebasing from Silverblue to Bazzite pins two rpm-ostree images disabling the posibility of rolling back to Silverblue (or whatever one previously had.
The following picture was taking fresh after install
![Screenshot from 2023-08-31 10-46-20](https://github.com/ublue-os/bazzite/assets/13031251/23f8b335-2bf2-4292-8486-71aaf56b2ded)
Here's what I got just after a rebase
![image](https://github.com/ublue-os/bazzite/assets/13031251/900fb155-f467-410b-8aa2-204c2cc0545d)
This is happening inside Gnome Boxes but it also happened when I first rebased from Silverblue.

**Comment by kubepy** [comment]
seems ostree has 2 deployment, do you try to `pin` your deployment `ostree admin pin <index number>` for keeping the old deployment?

**Comment by kubepy** [comment]
> No, my expectation was that if I run 1 transaction, I would be able to undo it by rollback. Am I making a wrong assumption here? I can also run that test if you think it's relevant, @kubepy

Due to the ostree remains 2 deployments by default, I just guess whether after executed `rpm-ostree rebase`, your old deployment is deleted automatically (if that's index is >= 2)

Use `ostree admin pin <index: number>` to keep the old deployment.
```
$ sudo rpm-ostree status -vvv
[sudo] password for deck: 
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:38 (index: 0)
                   Digest: sha256:99e1ec8654a897b70f5e1e0495dbe9d2fc0a7d1759527a41c2b86fe52decfa38
                  Version: 38.20230829.0 (2023-08-30T06:12:34Z)
               BaseCommit: c479b66c7e13c4e210c0ce4e31836cc1b3c836c6afb13b1db42dd23f00b4c8a2
                   Commit: cd0384bed4aa828ff601d2624f73c2dc3f5fd61fbf82c707879b1548153fc52a
                   Staged: no
                StateRoot: default
            LocalPackages: yuzu-20230828-1.fc38.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:38 (index: 1)
                   Digest: sha256:99e1ec8654a897b70f5e1e0495dbe9d2fc0a7d1759527a41c2b86fe52decfa38
                  Version: 38.20230829.0 (2023-08-30T06:12:34Z)
               BaseCommit: c479b66c7e13c4e210c0ce4e31836cc1b3c836c6afb13b1db42dd23f00b4c8a2
                   Commit: 77583a1020d846190d4275efca2b9f883b15b4fdbbc5d313469df7139413ecb5
                           ├─ fedora (2023-04-13T20:37:10Z)
                           ├─ fedora-cisco-openh264 (2023-03-14T10:56:46Z)
                           ├─ fedora-modular (2023-04-13T20:30:47Z)
                           ├─ rpmfusion-free (2023-04-14T11:37:11Z)
                           ├─ rpmfusion-free-updates (2023-08-26T15:09:45Z)
                           ├─ rpmfusion-nonfree (2023-04-14T12:02:51Z)
                           ├─ rpmfusion-nonfree-updates (2023-08-26T15:38:13Z)
                           ├─ updates (2023-08-30T01:24:18Z)
                           ├─ updates-archive (2023-08-30T02:25:43Z)
                           └─ updates-modular (2023-08-19T01:34:25Z)
                StateRoot: default
   InactiveLocalOverrides: gamemode-1.7-2.fc38.x86_64
            LocalPackages: yuzu-20230828-1.fc38.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:38 (index: 2)
                   Digest: sha256:99e1ec8654a897b70f5e1e0495dbe9d2fc0a7d1759527a41c2b86fe52decfa38
                  Version: 38.20230829.0 (2023-08-30T06:12:34Z)
               BaseCommit: c479b66c7e13c4e210c0ce4e31836cc1b3c836c6afb13b1db42dd23f00b4c8a2
                   Commit: 111fe98bf4b5fd6185615ee387011cf2ece52f77a88ce8605d72e0a54b0f5b85
                           ├─ fedora (2023-04-13T20:37:10Z)
                           ├─ fedora-cisco-openh264 (2023-03-14T10:56:46Z)
                           ├─ fedora-modular (2023-04-13T20:30:47Z)
                           ├─ rpmfusion-free (2023-04-14T11:37:11Z)
                           ├─ rpmfusion-free-updates (2023-08-26T15:09:45Z)
                           ├─ rpmfusion-nonfree (2023-04-14T12:02:51Z)
                           ├─ rpmfusion-nonfree-updates (2023-08-26T15:38:13Z)
                           ├─ updates (2023-08-30T01:24:18Z)
                           ├─ updates-archive (2023-08-30T02:25:43Z)
                           └─ updates-modular (2023-08-19T01:34:25Z)
                StateRoot: default
            LocalPackages: yuzu-20230828-1.fc38.x86_64
                   Pinned: yes
```

**Comment by castrojo** [comment]
You should probably always pin an explicit version before rebasing. This is in the upstream documentation but I'm having a hard time finding it at the moment.

**Comment by Cr4tes** [comment]
> What is the results when use the command `sudo rpm-ostree status -vvv` after you did the `rpm-ostree rebase`, is that 2 deployment are same?

![image](https://github.com/ublue-os/bazzite/assets/13031251/66d34765-f43e-4a6d-b7ac-c08f03b524c3)

Here it is!

@castrojo No need to search I'll take your word for it. I was just wondering if you guys consider this an issue or it's just business as usual.
Least we can do is add instructions to pin existing version before rebasing on the documentation. (I could submit a PR)

**Comment by kubepy** [comment]
`-vvv` looks index: 0 and index: 1 are difference.
Index: 0 is including rpm db cache that its details is listing the yum repos.

**Comment by castrojo** [comment]
I consider this an issue since the reason we didn't write it down was because it was in the upstream docs and we prefer to send people there.

But we should really document how to pin, rollback, and do that kind of basic admin stuff. There used to be a page upstream that recommended the pinning and had examples of rolling back, so we might as well write it up since we're using the OCI method and all the upstream examples will be ostree so the output will end up looking different anyway. 

We should have it as part of the user's guide: https://universal-blue.org/guide/admin

PRs appreciated! https://github.com/ublue-os/website/

(And then we should move the autoupdate adjustments and other things under there too, but simple rpm-ostree commands is a great start. Thanks!

**Comment by noelmiller** [comment]
Review kubepy's response about explicitly pinning a deployment for rpm-ostree. At this point, there is no ability to roll back.
