### ISSUE TITLE
Partition issue

### ISSUE THREAD

**Issue by tss110** [ublue-os/bazzite#245]
I was at first trying to use cryo utilities to increase my swap size but that didn’t work so I tried to do it threw kde partition manager. From there it was basically unusable whatever I did or changes I thought I would be doing wouldn’t take and would remain the same. Any ideas to fix this or is it something to be patched later

**Comment by KyleGospo** [comment]
Cryoutilities is not supported and there is no swap file by default. The ability to go back to a swap file is in Bazzite Portal (Called Legacy Memory Config and labeled as not recommended), and you can customize the size of it via just.

**Comment by tss110** [comment]
I figured it out I had to edit it had to edit it from a bootable disk while the disk was unmounted
