### ISSUE TITLE
DualSense Trackpad Stuck in Mouse Mode

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#248]
I think there may be a conflict between the Linux drivers for the DualSense Trackpad and Steam Input. The trackpad is exclusively treated as a mouse, and Steam Input cannot override the behavior, regardless of how you configure a controller profile. This is on Deck, if that matters.

**Comment by KyleGospo** [comment]
There's a package preinstalled from SteamOS that's supposed to fix this, can you check this for me:

`systemctl status ds-inhibit`

**Comment by jacobranson** [comment]
https://paste.centos.org/view/299b4dc0
https://paste.centos.org/view/226409c2

**Comment by jacobranson** [comment]
I just checked, this issue only occurs upon rebooting without visiting the desktop at least once. If I switch to desktop mode and then switch back to gaming mode, the touchpad works as expected.

**Comment by KyleGospo** [comment]
Very interesting, I'll look into it.

I can at least confirm that package is completely unmodified from how it's shipped in SteamOS 3.5
