### ISSUE TITLE
[Feature Request] Customize Gamescope Hide Cursor Delay

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#249]
The default behavior of Gamescope is to autohide the cursor after 3 seconds. There is no way to customize this in SteamOS at this point. Could there be something exposed to users that allows them to customize this value?

This is actually a rather frustrating default behavior from SteamOS, because you can specify an action set for when the cursor is visible, and a different action set for when it is hidden, but the cursor auto hides after 3 seconds, necessitating a random cursor movement every 3 seconds, else your action set will be switched automatically when you wouldn't expect it to.

I think just exposing an environment variable and using that as the arg to --hide-cursor-delay in the gamescope-session-script should do the trick. Maybe could also expose a just command and tack it on to the Bazzite Portal to make it visible to users?

**Comment by KyleGospo** [comment]
This will be available next update
https://github.com/KyleGospo/gamescope-session/commit/be96c16eaf80a7e402f82cea4fbce841f979c012

Toss this in `/etc/environment` for a 5 second delay:
`GAMESCOPE_OVERRIDE_CURSOR_DELAY=5000`

**Comment by jacobranson** [comment]
You are a legend for implementing this! Tried it out and it works perfectly. Thank you so much!
