### ISSUE TITLE
Waydroid Configuration Not Working

### ISSUE THREAD

**Issue by noey-drew** [ublue-os/bazzite#250]
Hi,

I am in the process of trying to get Waydroid working in the gamepad ui, following [this](https://universal-blue.org/images/bazzite/waydroid/) documentation, and I'm getting stuck. I am using bazzite-deck-gnome for an HTPC.

I completed step 6, adding Weston to steam but it won't launch. Waydroid does work on it's own after enabling Wayland.

When running step 7, I get this:

>$ just configure-waydroid
Cloning into '/tmp/waydroid_script'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 48 (delta 0), reused 29 (delta 0), pack-reused 0
Receiving objects: 100% (48/48), 5.00 MiB | 8.71 MiB/s, done.
[sudo] password for noey: 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/waydorid_script/requirements.txt'
Traceback (most recent call last):
  File "/tmp/waydroid_script/main.py", line 2, in <module>
    from InquirerPy import inquirer
ModuleNotFoundError: No module named 'InquirerPy'
$ 

Am I missing anything? Is anyone else getting this?

**Comment by KyleGospo** [comment]
This should be fixed as of the latest update

**Comment by noey-drew** [comment]
> This should be fixed as of the latest update

You're right, after running  `sudo rpm-ostree upgrade` the command works
