### ISSUE TITLE
[bazzite-deck] Gpu stuck at 15W

### ISSUE THREAD

**Issue by lamarios** [ublue-os/bazzite#255]
I'm trying to use bazzite on an htpc (i7-8086k / rx6600xt) and used the deck image as recommended by the readme but my gpu is stuck at 15w which is obviously not enough to power a desktop gpu as performance is terrible. 

I installed corectrl to confirm the power and it was limited to 15W.

Is there anything I need to do to bypass this? I already disabled the deck services with just.

**Comment by drokath** [comment]
May be fixed with #68 as the gamescope UI is specific to Steam Deck and cap is hardcoded to 15W

**Comment by KyleGospo** [comment]
Looking into this, get back to you soon

**Comment by KyleGospo** [comment]
Working on a better fix for this, for now on you end you can do:
`sudo rm /etc/udev/rules.d/30-steamdeck.rules`, or use a decky plugin to customize Steam's TDP limits if you want to use them but not be forced into a 15W maximum.

**Comment by lamarios** [comment]
Unfortunately none of the solution worked. The decky plugin PoerTools doesn't offer GPU options.

**Comment by KyleGospo** [comment]
You positive your issue is TDP then?
https://github.com/ublue-os/bazzite/issues/176

**Comment by lamarios** [comment]
hmm yeah you're right. it's the memory clock issue :(  Is there a way to install older kernel to fix this temporarily ?

**Comment by KyleGospo** [comment]
Afraid not, next kernel should fix it but in the meantime using a different refresh rate can correct the issue.
In the future should something like this happen again you'll be able to rebase to an older version of bazzite tagged by date, they're kept for 6 months. But every stable version ATM is on this kernel release.

**Comment by lamarios** [comment]
I tried changing the refresh rate to 50hz to test and memory clock does indeed goes all the way to 1000Mhz, but GPU frequency is still stuck at like 400mhz and 25W max.  I'll revert back to chimera os for the time being. Hopefully i can come back to bazzite later. I like silverblue a lot.

**Comment by massatt212** [comment]
This a problem holoiso had in the past, I'll send the fix for it, since I can't remove or edit the file that causes the limiter.

**Comment by massatt212** [comment]
https://github.com/HoloISO/holoiso_install_main/commit/cf139a129e58a2c57c27d6c0fad68daba8a71984
