### ISSUE TITLE
[FEATURE] Add RetroDECK support

### ISSUE THREAD

**Issue by Lx32** [ublue-os/bazzite#258]
Hi, I am part of the team of RetroDECK, another way of installing emulators with the main scope to the Steam Deck. RetroDECK comes installed as a flatpak and, thanks to this, can be used without problem both on handheld devices and desktop linux (with some manual tweak at the moment), updating all the emulators with a single package update.
We think that adding the possibility of installing RetroDECK on installation, like you do with EmuDECK, will be really cool giving the possibility to the user to choose on launch which software to use.
Thanks for your work.

**Comment by KyleGospo** [comment]
Hi, thanks for reaching out!
This is available under the Emulation page of Bazzite Portal. @EyeCantCU found your app and added it 3 months ago. EmuDeck is in a separate section due to it not being a flatpak. I'll update the readme to mention it explicitly.
