### ISSUE TITLE
HTPC Build (CPU 13600K, GPU 7900XT), very low performance

### ISSUE THREAD

**Issue by T13nou** [ublue-os/bazzite#260]
Hi !

Just installed Bazzite in my living room "console" equipped with Intel 13600K and AMD 7900XT.

I followed the tutorial and installed the "deck" version to boot directly into the right UI.

Everything installed ok, but performance is very very very low (10fps when I got 100fps on other distros).

Anyone has a hint or experienced this behavior ?

Thanks,

T13nou

**Comment by KyleGospo** [comment]
Sounds like you're affected by this upstream kernel bug:
https://github.com/ublue-os/bazzite/issues/176

Should be fixed next kernel release

**Comment by T13nou** [comment]
Thanks @KyleGospo ! You mean 6.5 integration ? Any ETA on this ?

**Comment by KyleGospo** [comment]
@T13nou I hope so on 6.5, and we'll get it the same time Fedora does. Maybe another week at most.

**Comment by vyktorjonas** [comment]
Same here after trying Batocera, yuzu can do 2x resolution , 7940HS, on Bazzite 1x resolution at most
