### ISSUE TITLE
Missing lutris icon from exported apps

### ISSUE THREAD

**Issue by dannyglover** [ublue-os/bazzite#262]
After installing bazzite, I ran the Bazzite portal that launches after the initial install.

After completing the wizard, I had two icons on the desktop, lutris and steam.

Lutris is missing its icon on both the desktop and the system menu (under games/all apps), but Steam has its icon in both places.

What's the fix?

Thank you.

Edit:

* installed bazzite desktop (the first option in the grub menu)
* Using the default KDE
* System: Ryzen 5800X3D, RX 6750XT, 32GB DDR4, 1TB Nvme.

**Comment by NjlsShade** [comment]
I witnessed this as well, but I think this may have been a short-lived bug with the **Bazzite Portal**'s bazzite-arch installation script, or with the bazzite-arch container (not sure how either could have caused the issue, but it does not seem to be a problem any longer).

If you're still missing the icon and would like to fix it, you can reinstall the container by first removing it using the command below, then reinstalling via the **Bazzite Portal**.

First run the stop command twice to make sure the podman container fully shutsdown.
```
distrobox stop bazzite-arch
distrobox stop bazzite-arch
```


Then remove the bazzite-arch container.
```
distrobox rm bazzite-arch
```


You can then open the **Bazzite Portal** to install the container again, or you can use the steps here to do so manually: https://github.com/ublue-os/bazzite-arch
