### ISSUE TITLE
Xone driver not working?

### ISSUE THREAD

**Issue by dannyglover** [ublue-os/bazzite#266]
I have bazzite installed on my PC, and use the official Microsoft Xbox wireless adapter. My controller refuses to connect in bazzite, but the Xbox adapter is listed under lsusb.

After fighting with this and failing for a while, I gave arch a quick spin via manjaro to see if it worked there. Neither the AUR xone or xone-git packages worked. However, after manually installing xone from this fork, it did work: https://github.com/dlundqvist/xone

Is xone installed in distrobox or under fedora on bazzite? Has anyone else got it working out of the box on bazzite?

Thank you.

**Comment by KyleGospo** [comment]
If you're using secure boot, make sure you've added the needed ublue key. Without it none of our kmods can load.

`sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der`

**Comment by dannyglover** [comment]
> If you're using secure boot, make sure you've added the needed ublue key. Without it none of our kmods can load.
> 
> `sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der`
> 
> xone, xpadneo, and xpad-noone are all included OOTB here.

I disabled secure boot prior to installing bazzite. Should it be working, or is secure boot required for the kmods to load?

Thank you.

**Comment by KyleGospo** [comment]
With no secure boot it should be working OOTB.

**Comment by dannyglover** [comment]
> With no secure boot it should be working OOTB.

What steps do I need to take to diagnose the issue? Thanks again.

**Comment by beefchimi** [comment]
This is probably an incredibly noob question, but... @KyleGospo - when you run `sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der` then `Enroll MOK` on reboot, it asks for a password. Is that _any password of your choosing..._ or is there a specific password needed for this cert?

**Comment by KyleGospo** [comment]
> > With no secure boot it should be working OOTB.
> 
> What steps do I need to take to diagnose the issue? Thanks again.

I would start with the basics, just make sure the modules exist and are loaded:
`modinfo xone`
`sudo modprobe xone`

**Comment by KyleGospo** [comment]
> This is probably an incredibly noob question, but... @KyleGospo - when you run `sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der` then `Enroll MOK` on reboot, it asks for a password. Is that _any password of your choosing..._ or is there a specific password needed for this cert?



> `udo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der` then `Enroll MOK`

`ublue-os`
https://universal-blue.org/installation/?h=secure+boot#secure-boot

**Comment by karmeleon** [comment]
I'm getting the same issue with a fresh install, `modinfo xone` and `sudo modprobe xone` both fail to find the kernel modules.

**Comment by NateTheGreat68** [comment]
> I'm getting the same issue with a fresh install, `modinfo xone` and `sudo modprobe xone` both fail to find the kernel modules.

Same here. It looks like commit 080e40c from 5 days ago disabled xone/xpad/xpadneo by default. `ujust configure-gamepads ublue` seems to undo what that commit did, but xone still doesn't work for me (`modinfo xone` returns "modinfo: ERROR: Module xone not found." even after a reboot, so that at least isn't my problem. I'm on bazzite-gnome version 39.20240116.0 with digest a0dca8 for reference.

**Comment by karmeleon** [comment]
`ujust config-gamepads ublue` worked for me! I had to do it twice with a reboot in between, though. Not entirely sure what's going on there but seems to work well enough. Thank you!

**Comment by massatt212** [comment]
i didnt want to post here, but i want to use my gamesir controller audio out, it was fixed in the latest xone driver so i want to know how to enable it or use it on bazzite steamdeck or can we have it added as a future feature?

**Comment by VranaCat** [comment]
I’m having this same issue using Bazzite 40 and an 8BitDo Ultimate C Wired controller. The listed ujust commands do not exist in Bazzite 40, so I cannot use them to fix this issue. As reported by others in this thread, doing a modprobe does not show the xone driver to be installed. I’d appreciate any help as to updated instructions for fixing this issue.
