### ISSUE TITLE
[Critical Bug] Unable to upgrade when installing offline iso

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/bazzite#275]
![Screenshot_20230908_093505](https://github.com/ublue-os/bazzite/assets/104856296/8e64a837-cdea-4a12-a5cd-fc58bd277809)
This pretty much says it all. It is tested in a vm and I am using the regualr plasma image.

**Comment by KyleGospo** [comment]
Bazzite Portal's first step should be to sign the image, which fixes this issue and gets you onto a signed image automatically.

**Comment by dnkmmr69420** [comment]
ok that's good. I was unaware of that
