### ISSUE TITLE
Deck not turning off screen or going to sleep. Gnome/Gaming mode

### ISSUE THREAD

**Issue by dab** [ublue-os/bazzite#276]
Installed Gnome edition to steam deck (deck was updated to 3.5 mainline, bios was updated as well). Screen stays on all the time. Changing setting not affecting this anyhow. Tested in Gaming mode with same result. Screen stays enabled all the time.

**Comment by KyleGospo** [comment]
@EyeCantCU could use your assistance on this one

**Comment by EyeCantCU** [comment]
Investigating... I looked through evlaV's GitLab to see if anything has changed there that would potentially cause this earlier and didn't find anything. Also have been running the latest GNOME image on my Deck without issue

I wonder if this is something specific to people that migrated from 3.5

In the meantime, I'm going to see what I can find

**Comment by KyleGospo** [comment]
My main deck was migrated from the main branch, I'm able to confirm that dim after 1 minute and sleep after 5 are both working in Gamemode. Testing desktop next.

**Comment by KyleGospo** [comment]
@dab Try running these commands:
https://github.com/ublue-os/bazzite/commit/23347190c7d43f32714d41cd8d10fe150215d1bb

**Comment by KyleGospo** [comment]
I can confirm suspend after 5 minutes works on my GNOME Deck with those settings in place.

**Comment by dab** [comment]
Thanks for getting back! Reverted to `F7A0116` from `F7A0117`, executed all the commands, still not turning off the screen. Not sure what can it be if you have similar config and it's working as expected :cry:

**Comment by KyleGospo** [comment]
Just updating this that the issue ceased randomly after discussions in Discord.

**Comment by dab** [comment]
Closing since not reproducible anymore. Thanks for suggestions!

**Comment by Rafa12996** [comment]
I would like to open this issue again. Problem is happening with the screen off function, suspend is fine.
