### ISSUE TITLE
Unresponsive after pulling Onscreen Keyboard in Activity Menu (DECK)

### ISSUE THREAD

**Issue by IMThammoud** [ublue-os/bazzite#278]
The Deck goes into an unresponsive state if i try to search something up with the Onscreen Keyboard of the Deck. When i press the button "b" it goes back to normal but it wont let me search for anything ( in activity menu)

**Comment by KyleGospo** [comment]
Unfortunately normal behavior, Steam keyboard is an application window and GNOME doesn't offer a way to keep it above the activities screen. At the moment you can use the included search light extension or use the keyboard built into GNOME if you don't mind losing trackpad typing.

**Comment by KyleGospo** [comment]
For anyone seeing this and wanting to contribute, an extension that can get that window to display above activities or an extension that adds dual trackpad input to Caribou would be much appreciated :)
