### ISSUE TITLE
Deck offline installer 1.1.0 utterly broken

### ISSUE THREAD

**Issue by Janrupf** [ublue-os/bazzite#283]
The newly releases 1.1.0 offline installer seems to be broken in all possible ways. The first thing I noticed was that `anaconda` does not scale properly. Looking at the kernel command line, it also seems none of the command line options were applied.

I could never get the installation to finish properly. For now I fell back to the older installers, which work flawlessly for me and scale properly on the Steam Deck.

**Comment by sean-work** [comment]
They're aware of this and it will be fixed for the next release.

Temporary workarouns from user stephenz on the discord:

`use the e key at the 1.10 grub menu, then type inst.resolution=1280x800 before quiet on the linux line and type ctrl-x to continue boot.  This will fix Anaconda scaling for the install.`

**Comment by GabrielJustus** [comment]
same here, had a ton of problems, even thought there was something wrong with my deck, glad to know the online ones work, will be trying them

**Comment by noelmiller** [comment]
We are currently in the process of regenerating this ISO. It is not complete yet. If you want more information, please follow this issue: https://github.com/ublue-os/main/issues/468

**Comment by KyleGospo** [comment]
We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker

Let us know if you have any issues with the new one :)
