### ISSUE TITLE
Trouble pairing PS5 DualSense controllers

### ISSUE THREAD

**Issue by rayrayrayraydog** [ublue-os/bazzite#295]
I have installed bazzite 1.1.0 from the ISO available @ https://ublue.download/bazzite-deck-38-x86_64.iso on an all AMD HTPC build that I had previously been using with holoISO.  I am having trouble pairing either of my PS5 DualSense gamepads with the system on bazzite, where they had worked in the prior OS without issue.

Here are the lines from bluetoothctl when trying to pair a DualSense using the BT UI in KDE - System Settings - Bluetooth.  DualSense pairing initiated by starting up with Home+Create per Sony's docs.
```[CHG] Device D0:BC:C1:61:7E:C8 RSSI is nil
[CHG] Device A4:C1:38:36:86:AC RSSI is nil
[CHG] Device 88:C6:26:5D:57:D3 RSSI is nil
[CHG] Controller E8:EA:6A:8C:0B:88 Discovering: no
[CHG] Device D0:BC:C1:61:7E:C8 Connected: yes
[CHG] Device D0:BC:C1:61:7E:C8 Bonded: yes
[CHG] Device D0:BC:C1:61:7E:C8 ServicesResolved: yes
[CHG] Device D0:BC:C1:61:7E:C8 Paired: yes
[CHG] Device D0:BC:C1:61:7E:C8 Trusted: yes
[CHG] Device D0:BC:C1:61:7E:C8 ServicesResolved: no
[CHG] Device D0:BC:C1:61:7E:C8 Connected: no
```

The last line ("Connected: no") occurs immediately after the pairing process seems to complete.  I also see the error "br-connection-page-timeout" in the Bluetooth System Settings GUI.  

I can successfully pair an 8bitdo SN30 Pro+ controller via the KDE Bluetooth GUI, but then when switching to Gamescope it has a similar behavior where the controller is disconnected immediately when trying to connect.

System details:
- AMD R5 5600
- AMD RX 6700XT
- 32GB DDR4
- ASRock B550M PG RIPTIDE motherboard
- Bluetooth dongle: **0bda:8771 Realtek Semiconductor Corp. Bluetooth Radio**

**Comment by KyleGospo** [comment]
I'm able to reproduce this, looking into it. Seems like an upstream Fedora bug as there's similar reports in /r/Fedora

**Comment by rayrayrayraydog** [comment]
This is super weird, but I got out another Bluetooth dongle just to try it, and this one worked on the first try with the DualSense.  Oddly, it's also the same hardware string: **0bda:8771 Realtek Semiconductor Corp. Bluetooth Radio** (???)

This is the one I just now tried that worked: https://www.amazon.com/dp/B0BQYL2PK3
This one didn't work: https://www.amazon.com/gp/product/B0B2737HPS

And just to be sure, I switched back to the Star-Tech branded one and it fails to connect.

**Comment by rayrayrayraydog** [comment]
Okay, it seems to have less to do with one dongle versus the other, but rather unplugging and re-plugging the dongle after the system starts.  The hid_playstation module is also not automatically loaded at boot in the system.  Just loading it does not solve the problem, however.

I've got a workaround hack set up on my machine that seems to be the answer so far in my limited testing...

`/etc/systemd/system/hack-restart-bluetooth-at-boot.service`

```[Unit]
Description=Hack to restart BT to get DualSense to work in Fedora
Requires=multi-user.target
After=multi-user.target
AllowIsolate=yes

[Service]
ExecStart=/bin/bash -c /usr/local/bin/restart-bluetooth.sh

[Install]
WantedBy=default.target
```

`/usr/local/bin/restart-bluetooth.sh`

```rmmod hid_playstation;  systemctl stop bluetooth; modprobe hid_playstation; systemctl start bluetooth;
```

**Comment by unicornsandcandies** [comment]
> Okay, it seems to have less to do with one dongle versus the other, but rather unplugging and re-plugging the dongle after the system starts. The hid_playstation module is also not automatically loaded at boot in the system. Just loading it does not solve the problem, however.
> 
> I've got a workaround hack set up on my machine that seems to be the answer so far in my limited testing... the test is that the previously paired DualSense can be connected after Gamescope loads.
> 
> `/etc/systemd/system/hack-restart-bluetooth-at-boot.service`
> 
> ```
> [Unit]
> Description=Hack to restart BT to get DualSense to work in Fedora
> Requires=multi-user.target
> After=multi-user.target
> AllowIsolate=yes
> 
> [Service]
> ExecStart=/bin/bash -c /usr/local/bin/restart-bluetooth.sh
> 
> [Install]
> WantedBy=default.target
> ```
> 
> `/usr/local/bin/restart-bluetooth.sh`
> 
> ```
> rmmod hid_playstation;  systemctl stop bluetooth; modprobe hid_playstation; systemctl start bluetooth;
> ```

It gives me this error:

libkmod: ERROR libkmod/libkmod-config.c:712 kmod_config_parse: /etc/modprobe.d/default-disable-broadcom-wl.conf line 3: ignoring bad line starting with 'wl'

**Comment by unicornsandcandies** [comment]
> I don't have this file on my system. `/etc/modprobe.d/default-disable-broadcom-wl.conf`
> 
> Are you saying the DualSense drops connection after a while? I will admit I haven't sat and played for an extended period yet with the hack in place.

Should I delete or something? How is it possible on an image based distro that we have different files

**Comment by rayrayrayraydog** [comment]
My hack stopped working again and I'm still not sure why.  I found the most reliable workaround is to unplug/replug the Bluetooth dongle after gamescope loads.  In my case it's in a front port on my HTPC case so that isn't a big deal.

**Comment by sinedoOo** [comment]
I have exactly the same issue. From logs I can see the pairing is successful, but connecting no. Any of suggested here solutions helped me. Any idea what's causing this? PS controllers are very popular, so I'm very surprised that nobody else reported it :P

**Comment by rayrayrayraydog** [comment]
I am now waiting until gamescope loads, unplug the BT dongle, use a KB/mouse to turn off Bluetooth, turn it on again, and the plug the dongle back in.  At that point the DualSense pairs.  As stated earlier this is an upstream Fedora 38 problem, I'm hoping once we get bazzite on F39 this will go away.

**Comment by sinedoOo** [comment]
Unfortunately I cannot unplug it, coz I'm using integrated Intel Killer bluetooth.

**Comment by rayrayrayraydog** [comment]
That sucks, a hack script *better than mine* might be the key here.  Disabling the Bluetooth service via script did work for me at first.  I didn't expend any great amount of effort troubleshooting it when it stopped.

**Comment by rayrayrayraydog** [comment]
This issue has persisted in bazzite on Fedora 39 unfortunately.
