### ISSUE TITLE
Use 2 gpu 

### ISSUE THREAD

**Issue by bmsi77** [ublue-os/bazzite#296]
Hi 
 I have 2 gpu one amd rx 6600 and one rtx 4080 is there anyway to run gamescope on rx 6600 and run game on rtx 4080

**Comment by nicknamenamenick** [comment]
I can't see this actually working.  If it does work it might require a ton of environment variables and I don't know where to even begin.  Gamescope nests the programs you run, so it's going to be very complicated to get this to work.  You either have to deal with no gamescope and use the Nvidia GPU, or use the AMD GPU and gamescope.

I apologize, but maybe someone else could try figuring that out, but I'm not even sure where to begin personally.

**Comment by ACCESSDENIIED** [comment]
The devs over on ChimeraOS managed to do this by creating a utility called "export-gpu". It's available in their gamescope-session.

Basically, if you have an igpu and dgpu you can tell gamescope to use the igpu and then proton will use the dgpu for the games.

**Comment by bmsi77** [comment]
Tnx that fantastic
 keep good work
