### ISSUE TITLE
Performance on 7940HS

### ISSUE THREAD

**Issue by vyktorjonas** [ublue-os/bazzite#298]
In comparison with Batocera, the performance is much worse on the mobile AMD 7940HS
For example, I can do 2x resolution on Yuzu/Batocera, Bazzite can barely handle 1x, I can't even play Mario 3D with stock settings
Stray(Proton) on Batocera: 1080p everything on High, on Bazzite everything medium 30fps
is there something I need to do or is that just how those different distros perform?

**Comment by EyeCantCU** [comment]
What image are you running?

**Comment by vyktorjonas** [comment]
Deck

**Comment by KyleGospo** [comment]
```cat /sys/class/hwmon/hwmon0/power1_cap
cat /sys/class/hwmon/hwmon0/power2_cap``

Can you give the output of this for me?

**Comment by vyktorjonas** [comment]
whether I paste thrm separately or together, the output was always thr same
cat: /sys/class/hwmon/hwmon0/power1_cap: No such file or directory
cat: /sys/class/hwmon/hwmon0/power2_cap: No such file or directory
