### ISSUE TITLE
Cannot Update

### ISSUE THREAD

**Issue by trigg** [ublue-os/bazzite#302]
Attempts to update or rebase hang after 'custom layers' and do not progress- even overnight
```
$ rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite:latest --download-only
Pulling manifest: ostree-unverified-image:docker://ghcr.io/ublue-os/bazzite:latest
Importing: ostree-unverified-image:docker://ghcr.io/ublue-os/bazzite:latest (digest: sha256:f2b8f265bc005debfeddbcbe2b9cb245882d0e79fe4a699b1919a666969b8878)
ostree chunk layers already present: 4
ostree chunk layers needed: 61 (2.2 GB)
custom layers needed: 2 (966.3 MB)
```

**Comment by trigg** [comment]
Attempts to rebase to kionite work fine 
```
$ rpm-ostree rebase fedora:fedora/38/x86_64/kinoite
⠒ Receiving metadata objects: 477/(estimating) 363.8 kB/s 121.5 MB    
```

**Comment by trigg** [comment]
```
$ rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/cinnamon-main:latest
Pulling manifest: ostree-unverified-image:docker://ghcr.io/ublue-os/cinnamon-main:latest
Importing: ostree-unverified-image:docker://ghcr.io/ublue-os/cinnamon-main:latest (digest: sha256:ccebdd6afa9eeb42ef34ff9a762c7eef63a5e30ee4ef249f659a14ecfac0f04f)
ostree chunk layers already present: 23
ostree chunk layers needed: 42 (1.0 GB)
custom layers needed: 2 (1.0 GB)
```

```
$ rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/cinnamon-main:latest
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/cinnamon-main:latest
Importing: ostree-image-signed:docker://ghcr.io/ublue-os/cinnamon-main:latest (digest: sha256:ccebdd6afa9eeb42ef34ff9a762c7eef63a5e30ee4ef249f659a14ecfac0f04f)
ostree chunk layers already present: 19
ostree chunk layers needed: 46 (1.2 GB)
custom layers needed: 2 (1.0 GB)
```
Attempts to use other ublue images also fail, this might not be the right place for this issue then?

**Comment by bigpod98** [comment]
Ehat kind of internet speed do you have as rpm-ostree appears tobhave lowered its verbosity level to minimum which leads to thinking its not doing anything but in most of my cases it has updated in timely manner

**Comment by trigg** [comment]
Internet speed isn't great here, but it was left running for 10 hours overnight on one of my machines with no effect.

That said, as of about 10 minutes ago one of them has managed to pass this point and completed an update, on wifi, while the wired machine still sits idle.

I'll mark as complete as it certainly looks like it is connection issues somewhere rather than an issue with bazzite itself

**Comment by KyleGospo** [comment]
@trigg glad you got this working, weird about the speed though. We've had a couple reports like this, everything's hosted at ghcr so it should be very fast.

By the way, we just added built-in discover overlay support, it automatically launches as long as you have Discord installed. Thank you for working on that!

**Comment by trigg** [comment]
Thanks! 

The irony here is palpable as I've just finished switching all my own machines to bazzite and taught myself to use toolbox to develop discover overlay.
