### ISSUE TITLE
Impossible to edit SteamOS configs located in /usr

### ISSUE THREAD

**Issue by IrneRacoonovich** [ublue-os/bazzite#306]
Configs like jupiter-fan-control are impossible to edit under Bazzite due to ostree mandating `/usr` as read-only with no ability to alter it other than installing packages on top, but not with raw file edits.

**Comment by KyleGospo** [comment]
This is also true under SteamOS, this is an immutable operating system and you won't be able to change files under usr under any circumstance.

I would recommend using the fan control plugin for decky loader.

**Comment by IrneRacoonovich** [comment]
Under steamos it is possible to temporarily make the system writable with the `steamos-readonly disable` command. However it is impossible to do so with Bazzite.

I am not trying to disable the fan service, but to modify the config. It's not only about this specific config, it's just an example. There's no way of overlaying a file change over `/usr`.

**Comment by dnkmmr69420** [comment]
why isn't there a config for it in `/etc`?
