### ISSUE TITLE
impossible to install games on SD card 

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#311]
There's something wrong with install process on SD cards formatted into btrfs. When I try to install any bigger game, it looks like this:

- downloading my game, everything looks normal
- there's "installing" that stucks after a moment, telling me to wait weeks for my game to install
- no change whatsoever

It works normally on steamos with ext4

**Comment by KyleGospo** [comment]
Your write speed is lower with btrfs because of compression, it certainly won't take weeks but it does take longer. The same thing happens when using steamos-btrfs on SteamOS, which we pull patches from.


You can edit `/etc/default/steamos-btrfs` to switch Bazzite over to ext4 if you prefer.

**Comment by unicornsandcandies** [comment]
> Your write speed is lower with btrfs because of compression, it certainly won't take weeks but it does take longer. The same thing happens when using steamos-btrfs on SteamOS, which we pull patches from.
> 
> You can edit `/etc/default/steamos-btrfs` to switch Bazzite over to ext4 if you prefer.

Ext4 works like a charm but I swear it stays like this on btrfs. There's something wrong. I literally left it there for two hours and nothing. I wished to use btrfs but I just couldn't make it work

**Comment by smerschjohann** [comment]
The default zstd compression level is too high for my taste. Yes, it leads to a little bit less space consumption, but to which price?

"The ZSTD support includes levels 1 to 15, a subset of full range of what ZSTD provides. Levels 1-3 are real-time, 4-8 slower with improved compression and 9-15 try even harder though the resulting size may not be significantly improved." (https://btrfs.readthedocs.io/en/latest/Compression.html)

some stats (not specific to steam deck): https://gist.github.com/braindevices/fde49c6a8f6b9aaf563fb977562aafec

I went with zstd:1, the same as the rest of the OS.

One additional note: After copying 400GB of (previously backuped) content to my 1TB sdcard. I had to defragment the btrfs filesystem. Maybe that is also a reason for your slowdown?

**Comment by EyeCantCU** [comment]
I've used a few different cards with my Steam Deck and have yet to run into this. BTRFS has worked fine and I've been getting accurate ETAs during game installation. There was one weird instance really early on where I had an ETA of over a year back in June, but after a reboot I never ran into it again

The problem probably comes down to the SD card. There's lots of variability between cards. However, I'll try to replicate this with the cards that I have

**Comment by EyeCantCU** [comment]
> Yes, it leads to a little bit less space consumption, but to which price?

Looking at these stats and the compression that we're using, a very low price ;)

This is going to depend more on the card and less on the reader used by the Steam Deck

**Comment by KyleGospo** [comment]
> > Yes, it leads to a little bit less space consumption, but to which price?
> 
> Looking at these stats and the compression that we're using, a very low price ;)
> 
> This is going to depend more on the card and less on the reader used by the Steam Deck

The reason zstd:4 was chosen was CPU usage consideration rather than SD card speed. On the Deck's CPU even zstd:6 is still faster than native A2 MicroSD cards.

**Comment by smerschjohann** [comment]
The Steam installation/download process has a very high CPU load on some games, as they have their own extraction/patching logic on top of just downloading. I saw differences between the compression levels. I did not quantify them, but in the end I don't care much about a few GB extra if it otherwise hits my download rate / wait time.

But for that reason you can configure it yourself, I don't say you have to change the default ;)
