### ISSUE TITLE
Fresh install has systemd-module-load failure 

### ISSUE THREAD

**Issue by breningham** [ublue-os/bazzite#312]
Just installed Bazzite on my Desktop, Full AMD (Ryzen R9 7950X3D + 7800XTX + 64GB Ram). 
when booting my PC i notice a systemd unit has failed `systemd-modules-load.service`

See below Image. 
![image](https://github.com/ublue-os/bazzite/assets/23170786/46b383aa-9351-4a98-bca0-d2d5cb34026d)

for what it's worth, I've done all of the bazzite portal stuff too. 

seems to be related to secure-boot, but im not sure how to resolve this.

**Comment by KyleGospo** [comment]
Instructions for enrolling our secure boot key are at the very top of the release notes.

**Comment by breningham** [comment]
i had actually ran the `just enroll-secure-boot-keys` - i apparently just used the wrong password (though, weirdly enough, no error from that it just doesn't do anything)

running with the correct password of `ublue-os` does seem to have worked. 

maybe we could get that tid-bit into the main README?

**Comment by KyleGospo** [comment]
> i had actually ran the `just enroll-secure-boot-keys` - i apparently just used the wrong password (though, weirdly enough, no error from that it just doesn't do anything)
> 
> running with the correct password of `ublue-os` does seem to have worked. 
> 
> maybe we could get that tid-bit into the main README? 

That's a good call, I'll add that right away. I'll put it in the title of the just command as well.
