### ISSUE TITLE
can't make the screen go off when docked

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#315]
No matter what I do, both in desktop and gaming mode, screen goes black but not off. It's still lighted. Even when I turned it off in gnome settings. Is there a way to fix it? On steamos it was always turning off when docked in game mode and I had to choose what to do in the desktop mode. Here it's either turned black but not off or turned on, both in gnome desktop and the actuall gamescope.

**Comment by KyleGospo** [comment]
This issue affects upstream SteamOS 3.5 right now as well. When they patch it we'll be sure to pull in those fixes.

**Comment by unicornsandcandies** [comment]
> This issue affects upstream SteamOS 3.5 right now as well. When they patch it we'll be sure to pull in those fixes.

But why does it affect gnome also?

**Comment by KyleGospo** [comment]
It's not gamescope specific, affects KDE on SteamOS 3.5 as well.

**Comment by RodoMa92** [comment]
It's a kernel issue, if you want to track the progress for fixing this, follow this issue [here](https://gitlab.freedesktop.org/drm/amd/-/issues/2765).

**Comment by unicornsandcandies** [comment]
> It's a kernel issue, if you want to track the progress for fixing this, follow this issue [here](https://gitlab.freedesktop.org/drm/amd/-/issues/2765).

There's an update in there, saying:

"The issue should be fixed by the following patch: https://patchwork.freedesktop.org/patch/563412/ "

I'm not sure what it means. When can we expect it in the kernel? Should we wait a couple days for patch to become upstream and that's it? Or does said patch need to be merged by bazzite team into kernel?

**Comment by KyleGospo** [comment]
Depends on when it's merged and if they decide to backport. Hopefully in the next dot release.

**Comment by RodoMa92** [comment]
Yeah, this is the fix, since Valve also have fixed it shortly before. Still no sources tho.
