### ISSUE TITLE
[Steam] Cannot launch games after sleep

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#321]
One thing that I have noticed is happening consistently is that Steam games will not launch if I have put `bazzite` into `sleep mode`.

Take `System Shock (remake)` for example:
- On a fresh boot, I can play the game just fine.
- After waking my computer from `sleep`:
  - Attempting to launch the game will flip the `Launch` action to `Cancel`.
  - Shaders will get processed.
  - Then the `Cancel` action just flips back to `Launch`.

I am not quite sure what is at fault here... but it is consistently happening with any game that I have tried so far.

### Specs from `neofetch`

```sh
OCI: Bazzite (Desktop Edition) x86_64 
OS: Fedora Linux 38.20230906.0 (Bazzite) x86_64 
Kernel: 6.4.13-200.fc38.x86_64 
Packages: 1868 (rpm), 14 (steam), 71 (flatpak)
Shell: bash 5.2.15 
Resolution: 3440x1440 @ 99.98Hz 
DE: Plasma 5.27.7 [KF5 5.109.0] [Qt 5.15.10] (x11) 
WM: KWin 
CPU: AMD Ryzen 7 7800X3D (16) @ 4.2GHz 
GPU: NVIDIA GeForce RTX 4090 
Memory: 5.59 GiB / 62.51 GiB (8%) 
```

**Comment by KyleGospo** [comment]
This is an upstream steam issue, a workaround is being researched:
https://github.com/89luca89/distrobox/issues/947

**Comment by KyleGospo** [comment]
If you're affected by this, make sure you're on the absolute latest and `just reset-bazzite-arch`
