### ISSUE TITLE
Bazzite

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#331]
how do i enable game mode, its not in the portal and im using latest bazzite iso
https://ublue.download/bazzite-38-x86_64.iso

**Comment by KyleGospo** [comment]
Gamemode is only present in the -deck images, which can work on HTPCs and desktops so long as they have an AMD or recent Intel GPU. Nvidia is unsupported due to their driver not following standards, which is also why it's not present in the desktop release.

**Comment by massatt212** [comment]
One more question, since we cannot use rpm, is there a fan controller I can use, I normally use lact, but I cannot install it.

**Comment by KyleGospo** [comment]
You have rpm-ostree which can install anything rpm or dnf could. Simply reboot after installing.

**Comment by massatt212** [comment]
One more question, how domi write read-only file system the steamos-priv-writw file needs to edited.tomfix the 15w limited for GPU, how do I unlock it to fix this problem, cause.i know the problem.

**Comment by KyleGospo** [comment]
You don't, but there's other solutions for that in https://github.com/ublue-os/bazzite/issues/320
