### ISSUE TITLE
No network connection since 09-12 image

### ISSUE THREAD

**Issue by Tripp024** [ublue-os/bazzite#333]
If I boot the 0908 image internet works again. No wifi and no ethernet on the newer releases.
Edit: I'm using the Steam Deck version.

**Comment by KyleGospo** [comment]
Working fine here, what hardware are you running the deck version on?

**Comment by Tripp024** [comment]
I'm using it on a Steam Deck. You think maybe a reinstall can help?

**Comment by KyleGospo** [comment]
To be clear, when you say no wifi or Ethernet do you mean they don't appear as options, or that the internet access with them isn't working?

We ship DNS over TLS by default, could be blocked on your end. There was a change to make sure it applied properly on that date.

**Comment by Tripp024** [comment]
I'm also using DNS over TLS on my router and I enabled DNS director so that individual apps can't bypass the DoT servers I configured. I'll try to disable that and let you know if it works.

**Comment by t9999clint** [comment]
how do you disable DoT?
it's causing a bunch of issues
