### ISSUE TITLE
Bazzite portal doesn't work

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#334]
![Screenshot from 2023-09-20 01-02-50](https://github.com/ublue-os/bazzite/assets/112720004/d3af529d-f808-4392-84dc-4fb0ebe2705e)

**Comment by KyleGospo** [comment]
Is this a fresh install? Can you give me the contents of your `~/.justfile`?

**Comment by unicornsandcandies** [comment]
> Is this a fresh install? Can you give me the contents of your `~/.justfile`?

!include /usr/share/ublue-os/just/custom.just
!include /usr/share/ublue-os/just/main.just
!include /usr/share/ublue-os/just/nvidia.just
!include /usr/share/ublue-os/just/custom.just
!include /usr/share/ublue-os/just/custom.just


For example there's a "main.just" content:
default:
    @just --unstable --list

# Boot into this device's BIOS/UEFI screen
bios:
  systemctl reboot --firmware-setup

# Clean up old containers and flatpaks
clean:
  podman system prune -a
  flatpak uninstall --unused
  rpm-ostree cleanup -bm

# Show the changelog
changelogs:
  rpm-ostree db diff --changelogs

# Create an Arch container
distrobox-arch:
  echo 'Creating Arch distrobox ...'
  distrobox create --nvidia --image quay.io/toolbx-images/archlinux-toolbox:latest -n arch -Y

# Create a Bazzite container
distrobox-bazzite:
  #!/usr/bin/env bash
  echo 'Creating Bazzite distrobox ...'
  if command -v /usr/bin/mutter > /dev/null; then
    distrobox create --nvidia --image ghcr.io/ublue-os/bazzite-arch-gnome --name bazzite-arch
  else
    distrobox create --nvidia --image ghcr.io/ublue-os/bazzite-arch --name bazzite-arch
  fi
  echo 'Check out the docs for exportable apps and instructions: https://github.com/ublue-os/bazzite-arch'

# Create an Alpine boxkit container
distrobox-boxkit:
  echo 'Creating Boxkit distrobox ...'
  distrobox create --nvidia --image ghcr.io/ublue-os/boxkit -n boxkit -Y

# Create a Debian container
distrobox-debian:
  echo 'Creating Debian distrobox ...'
  distrobox create --nvidia --image quay.io/toolbx-images/debian-toolbox:unstable -n debian -Y

# Create a Fedora container
distrobox-fedora:
  echo 'Creating Fedora distrobox ...'
  distrobox create --nvidia --image registry.fedoraproject.org/fedora-toolbox:38 -n fedora -Y

# Create an openSUSE container
distrobox-opensuse:
  echo 'Creating openSUSE distrobox ...'
  distrobox create --nvidia --image quay.io/toolbx-images/opensuse-toolbox:tumbleweed -n opensuse -Y

# Create an Ubuntu container
distrobox-ubuntu:
  echo 'Creating Ubuntu distrobox ...'
  distrobox create --nvidia --image quay.io/toolbx-images/ubuntu-toolbox:22.04 -n ubuntu -Y

# Enroll secure boot key
enroll-secure-boot-key:
    sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der

# Update system, flatpaks, and containers all at once
update:
  rpm-ostree update
  flatpak update -y
  distrobox upgrade -a

# Enable xwaylandvideobridge
fixscreenshare:
  cp /usr/share/applications/org.kde.xwaylandvideobridge.desktop $HOME/.config/autostart/

**Comment by noelmiller** [comment]
Please try on latest release and let us know if you have anymore issues!
