### ISSUE TITLE
Suggestion for some EAC games

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#335]
Some eac games like Rogue Company needs a Patch in glibc

`https://github.com/Frogging-Family/glibc-eac`

And Shipping Lact with corectrl, Lact works in gamemode (steamos3), u get amd overclocking, fan curve and profile selection for performance

`sudo systemctl enable --now lactd`

i install lact the way you told me, but i cant overlock my gpu cause its not install in system.

**Comment by KyleGospo** [comment]
Working on lact, and I'll see about glibc, trying to avoid changing upstream too much so I'm hoping this is resolved either there or in the application.

**Comment by massatt212** [comment]
Ok thx you so much 🙏

**Comment by massatt212** [comment]
is there update on the EAC patch and LACT?

**Comment by massatt212** [comment]
by any chance do we have AMDVLK as a 2nd support, some games run a lil smoother on it.
