### ISSUE TITLE
Gamemode ROG Ally Controller Issue

### ISSUE THREAD

**Issue by eaglemmoomin** [ublue-os/bazzite#340]
I ran an update last night and I noticed that HandyGCCS has been added. Which is fantastic. However I think on an ROG Ally there might be some config required. On my Ally which boots straight into gaming mode, specific buttons are not detected and the Xbox 360 controller seems to not be registering correctly. I'm assuming that for each 'type' of PC handheld the config file needs manual editing to set it up?

**Comment by castrojo** [comment]
Support is inprogress: https://github.com/ublue-os/bazzite/pull/162

**Comment by eaglemmoomin** [comment]
Oh right so is that a driver issue for the non 'standard' xbox 360 components of the Allys controller and HandyGCCS falling over. I really should have a look to see what the logs look like.

Previously after a mishap with secure boot interfering with the ability to load the 360 driver, once I sorted that out the controller part of the Ally had been behaving itself. So I'm assuming the HandyGCCS being recently added means the 'new'  service is interfering in some fashion.

**Comment by noelmiller** [comment]
Merge completed, closing.
