### ISSUE TITLE
Signing bazite doesn't sign on deck.

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#344]
Hi after installation on steam deck using 1.1.0 installer the signing bazite screen just sits there endlessly looping the progress bar animation show console button displays just an empty console box.. not sure if it is even doing anything but the work around i found is to close it and open bazite portal. Not sure what the issue is.

**Comment by KyleGospo** [comment]
This is now done and available in the latest builds.

You can update from gamemode or via the terminal with `rpm-ostree update` or `ublue-update`.
