### ISSUE TITLE
Feralgamemode for Deck-Image

### ISSUE THREAD

**Issue by Brunvik** [ublue-os/bazzite#348]
Hello everyone, I just switched to bazzite from ChimeraOS 

Currently I try to get feralgamemode working but It just does not want to. 

If I try to overlay it, it tells me that it is already requested, but actually using is impossible, since the command for gamemode can't be found. Starting games in Steam with gamemode also does not work

**Comment by KyleGospo** [comment]
We intentionally removed it in favor of system76-scheduler.

I'll have to look and see why it can't be layered, should since it's not there.

**Comment by Brunvik** [comment]
Weird thing is, either it tells me that Gamemode is already provided by the version for Fedora 38 or that the package is already requested. This does not change after a restart. Confusing thing

**Comment by Brunvik** [comment]
Quick Update: after layering libgamemode.so.0 everything works!
