### ISSUE TITLE
[Steam Deck] Updates and switching to desktop are now broken

### ISSUE THREAD

**Issue by JaxiiRuff** [ublue-os/bazzite#349]
Updating through game mode nor switching to desktop mode work anymore. Even tried after rebooting and nothing works. 

I have checked recent changes and it seems a lot of information referencing image or files have been changed or altered. No idea how I can provide logs of some kind since I cant use desktop mode.

**Comment by KyleGospo** [comment]
Thank you for the report and apologies for the issue, this is fixed in newer builds.

On your end, the best way you can fix this is to plug in a keyboard and do control + alt + F4, enter your username and password, and then enter `rpm-ostree update`. Once that's complete reboot with `sudo systemctl reboot`

**Comment by burakcan** [comment]
I’ve done this but it’s stuck at “custom layers needed: 4 (2.3GB)”. Is it doing something in the background? Is there a option to run this as “verbose”? It was a fresh install before I turned off the device.

**Comment by KyleGospo** [comment]
Yes that's normal, there's no progress bar for the download, just have to wait for it to finish.

**Comment by SaberJ2X** [comment]
It stayed there for a good while and i think it froze downloading stuff... but after a reboot and running rpm-ostree update again, it installed stuff and rebooted with command and...

*Rebooting*

Can confirm desktop mode is working again with bazzite deck 20230923!

**Comment by JaxiiRuff** [comment]
> It stayed there for a good while and i think it froze downloading stuff... but after a reboot and running rpm-ostree update again, it installed stuff and rebooted with command and...
> 
> _Rebooting_
> 
> Can confirm desktop mode is working again with bazzite deck 20230923!

I had the same issue and had to reboot since the deck went to sleep during the process. The download takes a very very long time.

However the way this OS updates has safeguards for those things by splitting the download and saving your progress. So once it actually finishes everything works as it should again.
