### ISSUE TITLE
justfile contains no recipes 

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#354]
I was trying to update the system through terminal but it doesn't seem to work. In fact, any of the just commands are not available.

```
deck@steamdeck ~]$ just update-system
error: Justfile does not contain recipe `update-system`.
[deck@steamdeck ~]$ just
error: Justfile contains no recipes.
```

It's worth mentioning that I followed the steps from issue as the last "tinkering" thing I did before seeing this issue:
https://github.com/ublue-os/bazzite/issues/349

**Comment by KyleGospo** [comment]
`rpm-ostree update`

**Comment by unicornsandcandies** [comment]
> `rpm-ostree update`

Can confirm it works now. Thank you!
