### ISSUE TITLE
Waydroid runs perfect on desktop but not under Weston

### ISSUE THREAD

**Issue by burakcan** [ublue-os/bazzite#358]
Hello,
I've followed the guide for Waydroid (on deck). It runs perfectly on desktop mode. But when run under Weston from game-mode, the touch interactions are weird. I think it's treating touches as mouse input. Also there is a mouse cursor shown. 
Other than that, the buttons on the Steam Deck doesn't work but they work again under desktop mode.
I'm not very familiar with modern Linux tools so I'm a bit lost. Anyone have any pointers?

**Comment by DarkenLX** [comment]
> Hello, I've followed the guide for Waydroid (on deck). It runs perfectly on desktop mode. But when run under Weston from game-mode, the touch interactions are weird. I think it's treating touches as mouse input. Also there is a mouse cursor shown. Other than that, the buttons on the Steam Deck doesn't work but they work again under desktop mode. I'm not very familiar with modern Linux tools so I'm a bit lost. Anyone have any pointers?

Just as a suggestion until someone official or with more knowledge can comment on this.. did you try to enable native touchscreen via the steam controller remapping... Go to the controller remapping press Steam button> Controller> controller settings (on the bottom of the screen) (i would map it to one of the grip buttons) > find "enable grip buttons" switch it on if it is not> pick whatever button then in the next screen select system with the LB/RB there should be a selectable pre set box that says something like enable native touchscreen or something like that it will map it to that button now back out back to waydroid and press the newly mapped button and test the touchscreen in waydroid.. any difference?

**Comment by KyleGospo** [comment]
The entire Waydroid experience was recently redone, let me know if you can still reproduce this after this coming update.
