### ISSUE TITLE
Add ASUS Ally and ASUS Laptop support

### ISSUE THREAD

**Issue by KyleGospo** [ublue-os/bazzite#362]
Previous PR: https://github.com/ublue-os/bazzite/pull/162

Repo that will contain this work;
https://github.com/ublue-os/asus/

Current status: Fails to boot with ASUS kernel installed.

**Comment by kubepy** [comment]
@KyleGospo Thank you for you and the team working this project! I would like to inquire when the estimated time for the Bazztie installation on ASUS Ally? I have borrowed my friend's ASUS Ally for a period, and he is very interested in installing Bazztie on it.
Also I was seeing and look like [ghcr.io/ublue-os/onyx-asus:39](http://ghcr.io/ublue-os/onyx-asus:39) image is building for asus device. Could it try to run on ASUS Ally?

**Comment by castrojo** [comment]
If you click the watch button on the asus repo you'll be able to follow along as it happens:

![image](https://github.com/ublue-os/bazzite/assets/1264109/8e767a3c-192a-4169-b9e1-7de649e8650c)

**Comment by KyleGospo** [comment]
Laptop support is there, Ally has controller issues left to work out.
