### ISSUE TITLE
Command 'just patch-tf2-tcmalloc' does nothing and TF2 requires another manual fix for Fedora systems

### ISSUE THREAD

**Issue by JaxiiRuff** [ublue-os/bazzite#364]
1.) I dont know why your patch doesnt work but to fix tf2 manually I had to install the files and copy them from /usr/lib directory. I believe these packages should `just` be installed by default and a small guide for how to copy the files until Valve fixes things.
```
rpm-ostree install gperftools gperftools-devel gperftools-libs.i686
```
2.) Voice lines in the game do not work unless you enter command:
```
setsebool -P allow_execheap 1
``` 
No idea why, but consider enabling it by default. Since this is a really old issue that neither Fedora or Valve seem to remedy by default. https://github.com/ValveSoftware/Source-1-Games/issues/2855#issuecomment-541447775

**Comment by noelmiller** [comment]
Due to the lack of activity on this issue, I am going to close this issue. Please try the latest build and reopen the issue if you are still having problems.
