### ISSUE TITLE
[ Deck Gnome ] Gnome color adjustments for steam deck don't seem to do anything 

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#365]
To turn on the night mode on gnome, we need to add display color profiles for deck under settings. Unfortunately none of the deck profiles works. They are there and the files names check out, it just doesn't seem to do anything at all.

**Comment by KyleGospo** [comment]
I believe this is due to us using SDDM on the deck rather than GDM.

**Comment by unicornsandcandies** [comment]
> I believe this is due to us using SDDM on the deck rather than GDM.

Is there any workaround for this?

**Comment by KyleGospo** [comment]
@EyeCantCU another issue fixed by GDM

**Comment by EyeCantCU** [comment]
> @EyeCantCU another issue fixed by GDM

Awesome! All the more a reason for me to work on this this week
