### ISSUE TITLE
Deck stuck on "21 September" update

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#366]
No matter what I do, steam deck wants to update to this patch. It's like gamescope is refusing it or something.

The update is about gyro to mouse or something and is constantly shown as an update for me.

**Comment by KyleGospo** [comment]
`rpm-ostree update`

**Comment by szescxz** [comment]
https://github.com/ublue-os/bazzite/issues/178#issuecomment-1691772159

**Comment by unicornsandcandies** [comment]
> `rpm-ostree update`

I've tried this multiple times already

**Comment by KyleGospo** [comment]
Run `ublue-update` in your terminal and give the output, this is what gamemode executes.

**Comment by unicornsandcandies** [comment]
> Run `ublue-update` in your terminal and give the output, this is what gamemode executes.

`2023-09-26 11:32:50,693] ublue_update.update_inhibitors
.hardware:INFO | System passed hardware checks
[2023-09-26 11:32:50,693] ublue_update.cli:INFO | System
 passed all update checks
[2023-09-26 11:32:50,771] ublue_update.cli:INFO | Runnin
g update script: /etc/ublue-update.d/user/00-flatpak-use
r-update.sh
[2023-09-26 11:33:01,038] ublue_update.cli:INFO | Runnin
g update script: /etc/ublue-update.d/user/01-flatpak-use
r-repair-cleanup.sh
[2023-09-26 11:33:58,792] ublue_update.cli:INFO | Running update sc
ript: /etc/ublue-update.d/user/02-distrobox-user-update.sh
[2023-09-26 11:34:00,129] ublue_update.cli:ERROR | /etc/ublue-updat
e.d/user/02-distrobox-user-update.sh returned error code: 125

                        Program output:


[2023-09-26 11:34:00,147] ublue_update.cli:INFO | Running update sc
ript: /etc/ublue-update.d/user/03-fleek-user-update.sh
[2023-09-26 11:34:01,973] ublue_update.cli:ERROR | /etc/ublue-updat
e.d/user/03-fleek-user-update.sh returned error code: 1

                        Program output:
                         [!]  Nix can't list profiles.


[2023-09-26 11:34:01,985] ublue_update.cli:INFO | Running update sc
ript: /etc/ublue-update.d/user/80-adwaita-for-steam-user-update.sh
[2023-09-26 11:34:01,988] ublue_update.cli:INFO | Running update sc
ript: /etc/ublue-update.d/user/90-mozilla-gnome-themes-user-update.
sh
[2023-09-26 11:34:02,009] ublue_update.cli:INFO | Running update sc
ript: /etc/ublue-update.d/user/99-bazzite-arch-user-update.sh
[deck@steamdeck ~]$
`

**Comment by KyleGospo** [comment]
You're getting an error while updating nix and while updating your distrobox images, this is why it's not showing your update as having completed.

Which distrobox containers have you made?

**Comment by unicornsandcandies** [comment]
> You're getting an error while updating nix via fleek and while updating your distrobox images, this is why it's not showing your update as having completed.
> 
> Which distrobox containers have you made?
> 
> As far as fleek I would open an issue with https://github.com/ublue-os/fleek or ask in #fleek in the Discord.

Fedora toolbox and bazzite arch Linux


How should I properly remove nix and fleek to not break silverblue? I'm not using them so this one can go

**Comment by KyleGospo** [comment]
For fleek just `whereis fleek` and then delete that file. You can uninstall nix with just.

For distrobox, you can update just them with `distrobox-upgrade --all` and we can go from there.

**Comment by unicornsandcandies** [comment]
> For fleek do `whereis fleek` and then delete that file. You can uninstall nix with `just remove-nix`.
> 
> For distrobox, you can update them with `distrobox-upgrade --all` and we can go from there, just give the output.

Unfortunately no luck with just command

```
[deck@steamdeck ~]$ just remove-nix
sudo /nix/nix-installer uninstall
sudo: /nix/nix-installer: command not found
error: Recipe `remove-nix` failed on line 286 with exit code 1
[deck@steamdeck ~]$
```

**Comment by noelmiller** [comment]
Due to inactivity on the issue, I am going to close this for now. Let us know if you are still having issues!
