### ISSUE TITLE
Default mic volume is super low

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#372]
I've managed to change it with opening alsamixer, picking a different sound cart and then maxing microphone volume. By default it was so quiet, you could barely hear it when talking to someone (and also choppy but that may be internet issue I guess). Can there be a way to do it with bazzite portal, just command or GUI? Preferably with more optimized settings than blindly changing "microphone" (out of so many weird labels I don't understand) like me

**Comment by RodoMa92** [comment]
On what platform? For Deck it should be already handled correctly in theory.

**Comment by jacobranson** [comment]
I am also on Deck and can confirm that this is an issue. Unfortunately, there have been multiple other issues regarding the noise level of the speakers, which is something I still manually adjust in AlsaMixer regularly, along with the mic gain.

**Comment by RodoMa92** [comment]
If anyone has the same issues as above, set up correctly your audio in alsamixer, then run sudo alsactl store -F to permanently save a config file to be reloaded on startup.

**Comment by unicornsandcandies** [comment]
> If anyone has the same issues as above, set up correctly your audio in alsamixer, then run sudo alsactl store -F to permanently save a config file to be reloaded on startup.

Could you recommend settings for non technical users? I know it may seem dumb but I don't want to randomly adjust this bars

**Comment by RodoMa92** [comment]
Sure:
1) Select the acp5x card by pressing F6
2) Press F4 to switch to only capture controls
3) The fifth bar should be called Mic, and it should be at maximum levels (100, gain of 24 dB on the top left when selected). If it's not, just press the up arrow until it's maxed out, picture here:
![immagine](https://github.com/ublue-os/bazzite/assets/16669146/a01a5c7a-f44f-4405-bb39-af35f9d385ae)
4) Exit out from it using escape on your keyboard.
5) Run `sudo alsactl store -F` once after setting this to permanently store your config into a file.

Enjoy the microphone working :)

Marco

**Comment by unicornsandcandies** [comment]
> Sure:
> 
>     1. Select the acp5x card by pressing F6
> 
>     2. Press F4 to switch to only capture controls
> 
>     3. The fifth bar should be called Mic, and it should be at maximum levels (100, gain of 24 dB on the top left when selected). If it's not, just press the up arrow until it's maxed out, picture here:
>        ![immagine](https://user-images.githubusercontent.com/16669146/272983829-a01a5c7a-f44f-4405-bb39-af35f9d385ae.png)
> 
>     4. Exit out from it using escape on your keyboard.
> 
>     5. Run `sudo alsactl store -F` once after setting this to permanently store your config into a file.
> 
> 
> Enjoy the microphone working :)
> 
> Marco

You're amazing! Thank you so much
