### ISSUE TITLE
EFI variables are not supported on this system (nvidia)

### ISSUE THREAD

**Issue by burakcan** [ublue-os/bazzite#373]
Hi,
I’m trying to install gnome-envidia on my desktop. I have an rtx 3070 gpu. When I try to run “just enroll-secure-boot-key”, I’m getting this error. 
I installed by using automatic partitioning; I guess it’s relevant. Happy to provide further information.

**Comment by KyleGospo** [comment]
Two options here, you have CSM enabled in your bios (definitely turn this off immediately), or secure boot is disabled and you can skip this step.

**Comment by burakcan** [comment]
Oh I have csm enabled yes. But I have it setup as "csm/uefi" hybrid mode or however it's called. Does it still default to legacy boot in that case?
Closing the issue.
