### ISSUE TITLE
Can't find Xbox Wireless Controller via bluetooth

### ISSUE THREAD

**Issue by burakcan** [ublue-os/bazzite#377]
Hi,
I'm trying to setup Xbox Wireless controller via bluetooth. But when I search, it doesn't find it. Updated the controller to the latest firmware via Windows. Not sure how to debug this, any ideas?

**Comment by KyleGospo** [comment]
If you're using secure boot make sure you've enrolled our signing key, the Xbox driver necessary can't load otherwise.

**Comment by burakcan** [comment]
just did it by extracting the keys from windows registry (there is an archlinux documentation about it). Now it pairs and connects but steam doesn't detect it.

**Comment by KyleGospo** [comment]
Make sure you're in the `input` group, if not add yourself to it.

Let me know if that fixes it for you and I'll automate this step in future releases.

**Comment by burakcan** [comment]
thank you @KyleGospo yeah it fixed it.

**Comment by KyleGospo** [comment]
https://github.com/ublue-os/bazzite/commit/b57ff42462eafffefc6b6a5a82123a0af7d8e736
