### ISSUE TITLE
Add XIV Launcher to Bazzite Portal

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/bazzite#380]
Hi There! 

This is a 3rd party launcher folks use to play Final Fantasy XIV on Linux (https://flathub.org/apps/dev.goats.xivlauncher) as well as Windows. It works really well! Obviously you can let folks know this is a 3rd party launcher and point them here: https://goatcorp.github.io/

I'm curious if it would be as simple as adding an entry to this yml file: 

https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml

If that's the case, I can easily do a PR for this.

Cheers, 

Noel

**Comment by KyleGospo** [comment]
That's exactly correct. If it's just a flatpak you can add it to yafti, if it needs any additional setup you can toss it in the custom just rules at:
Desktop: https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
Deck: https://github.com/ublue-os/bazzite/blob/main/system_files/deck/shared/usr/share/ublue-os/just/60-custom.just

And then point to it from the yafti.yml file. I would really appreciate the PR!

**Comment by noelmiller** [comment]
Sounds good! There is no other real config that needs to be done other than installing the flatpak in my experience. I'll see if I can put together a PR. What would be the best way of setting up a dev environment for Bazzite to make sure it works? VM maybe?

**Comment by castrojo** [comment]
https://universal-blue.org/local-testing/ has some tips on that!

Or you could just keep them in virt-manager and clone off of a template, which is also pretty fast. Might be the way to go here since it's the gui wizard thing so that might be easier than dealing with the plumbing for now.
