### ISSUE TITLE
Issue rebooting Bazzite

### ISSUE THREAD

**Issue by ErroneusMonk** [ublue-os/bazzite#383]
Using Bazzite (Steam Deck version), on a Steam Deck, and I am having issues rebooting. When I initially installed version 1.1.0, the process of rebooting would work fine. An update down the line I think caused an issue where if I try to reboot, it will start the process, things will shut down, but it will not fully reboot. The screen is off, but I can still hear the fans running.

My Deck was updated to the 118 bios recently and I undervolted, but in troubleshooting this issue, I set the voltages back to normal, and still had the same issue.

I'm not skilled enough in Linux to track down the log I may or may not need, but if I can be pointed towards it, I'll gladly provide a copy/paste.

To further clarify, I've run rpm-ostree-update, just update, ublue-update (on the 9-27 version), they all ran without issue, so I'm not sure why I am even having this problem.

**Comment by KyleGospo** [comment]
Had a similar report of this with another user on 118, given not even Valve is shipping this bios right now my recommendation is to downgrade to 116.

**Comment by ErroneusMonk** [comment]
Just run dmesg as a lone command, or are there are parameters to go along with it? I don't really mind the reboot issue, but I want to help troubleshoot this issue, simply to learn, and help you guys out in the process.

**Comment by KyleGospo** [comment]
What you can do is `dmesg | fpaste` and toss the URL it spits out here. We'll take a look from there.

**Comment by ErroneusMonk** [comment]
https://paste.centos.org/view/e40f10da

**Comment by KyleGospo** [comment]
This may be fixed now, I am on BIOS 118 on Fedora 39 and am not exhibiting this behavior

**Comment by ErroneusMonk** [comment]
Got the fedora 39 update recently, no longer having the issue. Thank you for this great OS.

**Comment by ErroneusMonk** [comment]
Did some more troubleshooting, and wound up remembering I had an undervolt applied. I had the igp at -50mv, so I backed it down to -40. In conjunction with the update, all seems fine.

It just seemed odd that this hasn't been an issue until a couple days ago, so that slipped my mind.
