### ISSUE TITLE
[Feature Request] Add Files App to Gnome Tofu Menu

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#393]
I think with Software Center and Terminal in there, this would be the only other thing I'd think should be included in that menu by default.

**Comment by KyleGospo** [comment]
Good call, I'm working on a new version of this built on a more maintained fork so I'll roll this into it.

**Comment by KyleGospo** [comment]
This will land with Fedora 39 on the 24th (or whenever upstream releases)
