### ISSUE TITLE
[Question] Underscan/overscan with Nvidia

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#395]
So far - using Bazzite as a couch-gaming distro - I havn't figured out how to get the screen to align perfectly with a 4k TV. Normally, there would be a underscan/overscan option you can configure to help deal with this.

**My question is:**
What would be the recommended "Bazzite way" to solve this problem?

Thanks.

**Comment by Tsubajashi** [comment]
i usually just use the settings provided by the TV, LG calls it JustScan, and others provide similar settings. these should be in the "Aspect Ratio" area of options.
not sure if thats the Bazzite way, but thats definitely how i would go around this issue.

**Comment by beefchimi** [comment]
`JustScan` was exactly what I needed :) Thank you!
