### ISSUE TITLE
Two small issues since I installed Bazzite on my Steam Deck.

### ISSUE THREAD

**Issue by DavidRLTG** [ublue-os/bazzite#404]
First, My XBOX ONE S controller does not work.
Basically, it appears in bluetooth, I pair it, but the controller keeps flashing and doesnt appear connected while Steam says it is, and then after 5s it disconnects from steam deck as well, but remains paired, but I cant connect. It used to work on SteamOS

Second, Bazzite can only display my TV at 4K 30hz. SteamOS was able to do it at 4K 60hz.
Any tips? Thank you.

**Comment by DavidRLTG** [comment]
And I discovered another issue, I cannot enable HDR in Gamemode, even if my TV supports it
darn

**Comment by Tsubajashi** [comment]
about the last one: HDR on Linux isnt really usable in its current state, even if you can enable it, so its more or less no difference if you can toggle it or not. it gets lots of work lately though, and probably will be good to use sometime later.

about your second issue: im not sure whats causing this, but i would first start to ask: which connector did you use / which dock do you use / what TV do you have?

**Comment by DavidRLTG** [comment]
Well, HDR did work in both desktop and game mode in SteamOS, here it works nowhere

And for the other issue, I use the official Steam Deck dock with a HDMI cable connected to my TV, through the (I think) HDMI 2.0 eARC port, and I have a Samsung QLED 4K TV, the Q60C or something, a rerelease of the 2020 model in 2023

**Comment by DavidRLTG** [comment]
I also ran into the additional issues of Steam System Update getting stuck at 00:01, Applying 99% and TF2 not launching

**Comment by KyleGospo** [comment]
> I also ran into the additional issue of TF2 not launching, And Steam launching waaaaay too late in desktop mode, leaving me with no controls for around ~20s
> Any way to fix these, if possible? thank you.

On the 99% issue, just wait it out, it's still applying.

The percentage is faked, we're not yet able to pipe the real progress into steam.

**Comment by KyleGospo** [comment]
> And I discovered another issue, I cannot enable HDR in Gamemode, even if my TV supports it
> darn

Fedora has no HDR support yet, and that's not something we're interested in porting from SteamOS given their kernel is far behind ours and it touches a huge number of packages. When HDR lands in Fedora we'll fully support it.

**Comment by DavidRLTG** [comment]
Welp, Got it! But, Any idea how exactly to fix tf2? exact commands or launch arguments or anything? and the 4K 30hz display issue

**Comment by KyleGospo** [comment]
> Welp, Got it! But, Any idea how exactly to fix tf2? exact commands or launch arguments or anything? and the 4K 30hz display issue

`patch-tf2-tcmalloc`

**Comment by DavidRLTG** [comment]
> > Welp, Got it! But, Any idea how exactly to fix tf2? exact commands or launch arguments or anything? and the 4K 30hz display issue
> 
> `just patch-tf2-tcmalloc`
> 
> No clue on the display issue, need more info. This the official dock or a third party one? You using KDE or GNOME?

Sorry for being dumb, but the TF2 command, I run it in terminal or as a launch argument for TF2?

And I have the official dock, as I mentioned, and I use KDE.

**Comment by KyleGospo** [comment]
That's in the terminal, I'll see if I can reproduce the display issue on my end then.

**Comment by DavidRLTG** [comment]
Got it! Thanks a bunch!
You were very helpful :)
I'll wait for you here now, do tell me how the uh.. display thing goes.

**Comment by dnkmmr69420** [comment]
> Got it! Thanks a bunch! You were very helpful :) I'll wait for you here now, do tell me how the uh.. display thing goes.
> 
> Edit: I did the TF2 command, TF2 will still not launch. No error or anything, I just press play, it shows stop instead of play for a few seconds then done

what is the output log for the just command? try running steam via terminal and launch tf2 and post the log here.

**Comment by DavidRLTG** [comment]
Hm, How do I run steam by terminal and launch tf2 there?
Sorry, I'm not too good with all this stuff.

**Comment by KyleGospo** [comment]
Try the latest build, this issue may be resolved for you.

**Comment by DavidRLTG** [comment]
Will do, Thank you.
And you mean, the entire issue? all I mentioned? Display? TF2? List goes on?
Sorry! Just asking, haha.

**Comment by noelmiller** [comment]
Due to the lack of activity on this issue, I am going to close this issue. Please try the latest build and reopen the issue if you are still having issues!
