### ISSUE TITLE
Audio devices not properly switching/wrong audio device labels

### ISSUE THREAD

**Issue by quickkennedy** [ublue-os/bazzite#410]
When the system has booted up without headphones connected the volume controls first control the speakers. Once headphones are plugged in, the deck volume controls continue to work on the speakers. If I go to settings and change the output device from "Default (Speakers)" to "Speakers" my headphones will suddenly work. If I switch the audio to "External Devices" before switching to my headphones, nothing will happen. Once switching to the "Speakers" option, I can no longer control the decks real speaker volume. All sound controls will only adjust volume on the headphones. Even after unplugging the headphones, volume controls is gone, reguardless of the audio device used. If at any time during this I switch to desktop mode the real values are shown.

This seems to have started happening right after I plugged in a dock that had both USB headphones and a monitor with connected speakers through the monitors audio jack.

**Comment by noelmiller** [comment]
Due to the lack of activity on this issue, I am going to close this issue. Please try the latest build and reopen the issue if you are still having problems!
