### ISSUE TITLE
CEC support with libCEC

### ISSUE THREAD

**Issue by AkazaRenn** [ublue-os/bazzite#411]
Might relate: 
https://github.com/ChimeraOS/chimeraos/pull/428
https://github.com/ChimeraOS/chimeraos/issues/358
https://github.com/ChimeraOS/chimeraos/issues/149

It would be nice to have CEC support for a better couch experience.

**Comment by KyleGospo** [comment]
https://github.com/ublue-os/bazzite/pull/412

**Comment by KyleGospo** [comment]
This will be in the next release, I'll be doing a new ISO tonight for some minor unrelated changes

**Comment by AkazaRenn** [comment]
> This will be in the next release, I'll be doing a new ISO tonight for some minor unrelated changes

Wow it was blazing fast, thanks for your work!!
