### ISSUE TITLE
On a fresh bazzite-deck-gnome:38 on httpc i got alway Welcom windows and i lost my steam login

### ISSUE THREAD

**Issue by yodatak** [ublue-os/bazzite#414]
Hi i think its a bug i got a loop and i alway get the desktop mode and not the gamerscope and i alway got bazzite welcome screen and steam login too
how can i debug it ?

**Comment by KyleGospo** [comment]
Complete the welcome screen at least once.

**Comment by yodatak** [comment]
I do it many time and it changes nothink

I think the problem seem to be a permission issues 
my user don't have the permission to execute 
this script
https://github.com/ublue-os/bazzite/blob/main/system_files/deck/shared/usr/bin/bazzite-autologin
# SteamOS SDDM config
SDDM_CONF='/etc/sddm.conf.d/steamos.conf'
AUTOLOGIN_CONF='/etc/sddm.conf.d/zz-steamos-autologin.conf'

and the autologin in bazzite 
DESKTOP_AUTOLOGIN='/etc/bazzite/desktop_autologin'
i have to delete this '/etc/bazzite/desktop_autologin
and chmod 777 /etc/sddm.conf.d/ to make it start to gamerscope by default i think its a probleme with the gnome variant

**Comment by yodatak** [comment]
I got steam unpacking at start again and again

**Comment by yodatak** [comment]
Return to gamemode don't work too when i cop the script and remove the exit i got zz-steamos-autologin.conf that get modified to gamerscope-session.dekstop

**Comment by nicknamenamenick** [comment]
> Return to gamemode don't work too when i cop the script and remove the exit i got zz-steamos-autologin.conf that get modified to gamerscope-session.dekstop

try entering `rpm-ostree update`  in the terminal.  wait for it to finish and reboot.  see if that changes anything.

**Comment by KyleGospo** [comment]
Make sure steam has also successfully launched at least once, game mode is dependent on Steam being ready to use.

**Comment by noelmiller** [comment]
Due to the lack of activity on this issue, I am going to close this issue. Please try the latest build and reopen the issue if you are still having problems!
