### ISSUE TITLE
[Controller] Xbox Elite Series 2 rumble/vibration

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#418]
I noticed that my `Xbox Elite Series 2` controller - which is paired via `Bluetooth` - does not "rumble" in games. It does vibrate upon connection _(there is a pairing confirmation rumble)_, but within Steam games, it isn't rumbling. For what it is worth, I DO NOT have the `Steam input for Xbox controller` option `checked`.

Any advice?

**Comment by HikariKnight** [comment]
Last time i checked this year, the rumble on the Xbox Elite Series 2 would at random freeze the firmware and make it stuck in permanent rumble (and whatever direction you have the stick) until you power cycle the controller.
The only way around it was to disable the rumble, not sure if this is the case still.

**Comment by beefchimi** [comment]
@HikariKnight that actually sounds a lot like what I am experiencing. Basically, no matter the game, very early on the controller will lock up and stop responding, and I have to turn it off and on again.

I only yesterday realized that the `rumble` DOES WORK in that tiny amount of time before it "locks up"... after which, the rumble no longer works 😢 

Any chance you know if this is a older firmware issue? I have never updated the firmware because I don't have a windows computer... not sure if there is a way to do it on Linux or Mac.

**Comment by HikariKnight** [comment]
> @HikariKnight that actually sounds a lot like what I am experiencing. Basically, no matter the game, very early on the controller will lock up and stop responding, and I have to turn it off and on again.
> 
> I only yesterday realized that the `rumble` DOES WORK in that tiny amount of time before it "locks up"... after which, the rumble no longer works 😢
> 
> Any chance you know if this is a older firmware issue? I have never updated the firmware because I don't have a windows computer... not sure if there is a way to do it on Linux or Mac.

back when i was looking into it, it was a problem with all firmwares up to the newest firmware (early 2023)

**Comment by EyeCantCU** [comment]
I run earlier firmware on my controller (primarily to maintain support with Mission Control over on the Switch), and I have not encountered this. Rumble seems to be fine. If you can, I'd recommend trying a firmware downgrade

**Comment by HikariKnight** [comment]
me an @EyeCantCU checked our firmware versions and they were both on the same old firmware 4.8.1908.0 so it is weird that they dont get the issue but we do :thinking:

**Comment by beefchimi** [comment]
I am still trying to get access to a Windows PC that I can do the firmware update on. Once I do, I will record both the current Firmware version - and whatever the new version is that I install. Then, I will see if the issue persists and report back :pray: haha but by the sounds of it, I shouldn't get my hopes up.

**Comment by beefchimi** [comment]
**Just an update:**

I was able to update to the latest firmware... but I can no longer get the controller to pair, so I haven't been able to determine if the firmware solved the problem or not.

I provide some more details in this recent issue: https://github.com/ublue-os/bazzite/issues/575#issuecomment-1823106644

**Comment by HikariKnight** [comment]
> **Just an update:**
> 
> I was able to update to the latest firmware... but I can no longer get the controller to pair, so I haven't been able to determine if the firmware solved the problem or not.
> 
> I provide some more details in this recent issue: [#575 (comment)](https://github.com/ublue-os/bazzite/issues/575#issuecomment-1823106644)

make sure youre on :39 or :latest
currently :38 has some bluetooth pairing issues (upstream issue with bluez i think it was)

**Comment by beefchimi** [comment]
Yea I had updated to `latest` hoping it would solve the issue after I read this: https://github.com/ublue-os/bazzite/issues/456

Sadly, it did not 😢 

I am going to try and pick up a `DualSense Edge` controller around XMas time and see if that pairs 🤞

**Comment by beefchimi** [comment]
I am FINALLY able to report back and say that the issue appears to be fixed!

I've updated my controller to the latest firmware AND I can finally pair it again in Bazzite with the most recent updates. I've played games - rumble is working and not crashing :smile:
