### ISSUE TITLE
Inconsistent plymouth change

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#426]
I've seen that you have new logo now! It's very good and I can only congratulate you for it.

I've also seen that boot animation and bazzite portal looks is different. Previously instead of "Bazzite" and your logo, there was Fedora logo and "Fedora".

Unfortunately changed logo appears only when turning off. Old boot is still there when turning on.

It's not a big issue at all but just makes the os feel inconsistent

**Comment by KyleGospo** [comment]
Definitely want to fix this, looking into where that's coming from on first boot vs any other state.

**Comment by KyleGospo** [comment]
@EyeCantCU Looks like to fix this we need to rebuild initramfs

Good news is we needed to do that anyway to get an OSK working for encrypted disks on deck, so this could be a nice intro to that.
