### ISSUE TITLE
[Deck] Gamemode fails to start and Steam is inconsistent

### ISSUE THREAD

**Issue by JaxiiRuff** [ublue-os/bazzite#427]
Something isnt letting gamemode start so it falls back to the desktop. Steam constantly displays "reconfiguring runtime environment" upon startup which causes it to forget saved logins and defaults to a really old version of the client from march.

**Comment by KyleGospo** [comment]
Make sure steam is allowed to start all the way to a login prompt, then try gamemode again.

**Comment by KyleGospo** [comment]
Found the cause for this, apologies for the inconvenience.

Update with `rpm-ostree update` and you should be good.

**Comment by Tsubajashi** [comment]
did that only happen on gnome or on KDE?
i had that issue on bazzite-deck-gnome, switched to KDE, and it seemed to work. is it "safe" to move back to gnome then?

**Comment by JaxiiRuff** [comment]
> did that only happen on gnome or on KDE? i had that issue on bazzite-deck-gnome, switched to KDE, and it seemed to work. is it "safe" to move back to gnome then?

This was happening to me on KDE.

**Comment by Tsubajashi** [comment]
ok, that was pretty weird then, havent had it on KDE for some odd reason - or i hit the rebase exactly when the bug was fixed.

**Comment by KyleGospo** [comment]
Bit of a goofy one, we updated Gamescope, and despite us installing both gamescope and gamescope.i686, only gamescope.i686 was being installed. We use this same pattern everywhere else without issue.

Updating the install line to gamescope.x86_64 and gamescope.i686 fixed it.

**Comment by rafaelvieiras** [comment]
@KyleGospo This fix is available on v1.3.0? I tried to install bazzite on my old Laptop Acer (i5-4210U, 6GB RAM & Intel HD 4400) in last weekend and I had the same @JaxiiRuff issues.
After first boot, I run all the welcome steps, and configure steam. When a reboot, they reboot on desktop with Welcome Steps again and steam log outed. 😢
