### ISSUE TITLE
[Deck] Games failing to launch through Proton

### ISSUE THREAD

**Issue by jtweedie** [ublue-os/bazzite#430]
Hi folks!
After updating Bazzite tonight all games launched through Proton fail to run on my deck. Running the games on the desktop gives the below error for every game. 

Native Linux games run as expected

Rolling back to the 38.20231008.0 image fixes the issue.

![2023-10-14_20-44](https://github.com/ublue-os/bazzite/assets/20932/865ccdc5-c718-4546-96cf-70bc7f6dd05b)

Any ideas?

**Comment by KyleGospo** [comment]
This is fixed in the latest builds, it was an issue with an update to gamescope.

**Comment by jtweedie** [comment]
Oh great! Thanks for swift reply!
