### ISSUE TITLE
[Critical Bug] Bazzite Hardware setup stuck on boot

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/bazzite#434]
I don't know if that is the exact name but it was still attempting to load that service after 6 min and 30 sec. I had to boot back into a working deployment just to boot. Before it just failed and now it tries to load it no matter what even if it takes an infinite amount of time to load.

Possible solution: Give bazzite-hardware-setup a time limit so the system can continue booting

**Comment by KyleGospo** [comment]
Let it finish

**Comment by rfrayer420** [comment]
Sitting on 62 minutes here

**Comment by hardeep1singh** [comment]
took 30-45 minutes for me and rebooted. but after that it gets stuck with error "failed to start systemd-modules-load.service"

**Comment by jasmohan-narula** [comment]
I did a fresh install with Nvidia option. After the initramfs step completed and the PC rebooted, it's stuck on a blinking _
