### ISSUE TITLE
[Bug] Audio gets scratchy when loading into game mode with headphones plugged in

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/bazzite#435]
The scratchy audio goes away when unplugging and plugging headphones back in

**Comment by unicornsandcandies** [comment]
> The scratchy audio goes away when unplugging and plugging headphones back in

I've also noticed it. It seems like there's something really wrong with audio settings. Other than this I see the issue of deck running at the full volume randomly. First few minutes after starting gamescope are buggy and do some wild things to audio.

**Comment by KyleGospo** [comment]
This is a bug in pipewire and has already been patched upstream.
Fedora 38 hasn't received it yet but I can confirm it's in Fedora 39 which we'll release in tandem with upstream.

**Comment by unicornsandcandies** [comment]
> Fedora 39 which we'll release in tandem with upstream.

This may not be the perfect place to ask but should we expect any changes regarding new Fedora? For example in gnome I think that there will be no activities button and there's a plugin replacing it. Are all modifications to fedora image ready for new version? 

What I want to ask is if we should be expecting some issues this month regarding new version

**Comment by KyleGospo** [comment]
New GNOME & KDE, the important extensions have already been ported to the newest GNOME.
