### ISSUE TITLE
[Steam] Taskbar seems to think Steam is Steam Link app?

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#438]
I did some software updates about a week ago, and afterwards, the desktop shortcuts changed to include `(on bazzite-arch)` in their names. Clicking them doesn't actually launch anything. So I have since needed to launch `Steam` from the `Applications menu`.

Doing this does launch `Steam`... however, the Taskbar seems to show the `Steam Link` icon. Not sure what exactly has gone wrong that has caused this bit of weirdness.

I would attach a screenshot... but I don't seem to be able to do that.[ I've opened a separate issue for that here.](https://github.com/ublue-os/bazzite/issues/437)

**Comment by noelmiller** [comment]
Steam should now be a layered package for Bazzite as opposed to running through Bazzite-Arch. My suggestion is to try updating to the latest build using `rpm-ostree update` and see if it resolves your issue. 

Since there is a lack of activity on this issue, I am going to close it. Please reopen it if you are still having issues!

**Comment by beefchimi** [comment]
@noelmiller This does appear to still be happening - under both `X11` and `Wayland` - on the latest updates _(as of today)_.

<details>
<summary><strong>Screenshot 1</strong></summary>

![thing](https://github.com/ublue-os/bazzite/assets/643944/0e7610ea-bde8-4606-8ccf-fab3c060a559)

</details>

Just to show that there are no unpulled updates:

<details>
<summary><strong>Screenshot 2</strong></summary>

![ups](https://github.com/ublue-os/bazzite/assets/643944/071fc252-6c06-460f-81ad-9f497b54371a)

</details>

No need to re-open this though, as there is a redundant issue here: https://github.com/ublue-os/bazzite/issues/535
