### ISSUE TITLE
[Taskbar] Various issues

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#439]
I notice that sometimes, closed apps do not disappear from the Taskbar _(area in the bottom left of the screen)_. When this happens, various strange things will occur:
1. Hover styling no longer applies _(no change in app visual when I put my cursor over it)_ .
2. Clicking an icon will launch either the wrong app, or multiple apps.
   - Example: I click on "Settings" and it launches both "Settings" and "FireFox".

FYI I am running a `Wayland` session on `Nvidia`.

**Comment by EyeCantCU** [comment]
This is an issue with running Plasma Wayland on Nvidia and unrelated to Bazzite itself. I'd suggest trying X11

**Comment by unclemarc** [comment]
Do you happen to know the issue so I could keep an eye on it? Thanks!

**Comment by noelmiller** [comment]
@EyeCantCU Do we have an update on this? I can mark this as upstream and close the issue if there is nothing that can be done on our end.

**Comment by KyleGospo** [comment]
Nothing to be done on our end, might be something KDE6 resolves
