### ISSUE TITLE
[Deck/Deck-HTPC Image] Issues with Onexplayer 2 Pro

### ISSUE THREAD

**Issue by NightHammer1000** [ublue-os/bazzite#440]
After getting the Hardware my first instinct was to slapp bazzite onto it.

Used the Deck Image because I wanted a Deck like experience.

That made me notice a few Issues right away.
I will list them here.

**Fixed by** [HandyGCCS Branch](https://github.com/ShadowBlip/HandyGCCS/tree/pastaq/oxp2) and [oxp-sensors branch](https://gitlab.com/derekjohn.clark/oxp-sensors/-/tree/oxp-pro-support?ref_type=heads) :
- [ ] No Desktop Controll via the Controller without Steam running.
- [ ] No Volume Control through Hardware Button.
- [ ] No Access to QSM in GamepadUI through one of the Left Controller Special Buttons or the Power Button ontop.

**Workarounds found:**
- [ ] USB Ports / Controller stops working after Device Disconnect
Add usbcore.autosuspend=-1 to the Kernel Parameters

**Still Unfixed / No Workaround**
- [ ] No Audio from Built in Speakers. -> Chimera has an open Issue for that:
https://github.com/ChimeraOS/chimeraos/issues/742
Kernel Bugtracker: https://bugzilla.kernel.org/show_bug.cgi?id=218097
- [ ] Installer is rotated 90°
- [ ] Bazzite Desktop after Installing is rotated 180°
- [ ] Power Button when hold down will not bring up Power Menu in Gamemode

I will gladly help Ironing those out. Just let me know what you need to know and I will provide.
I will update this list with new things once I find them.

**Comment by KyleGospo** [comment]
> No Access to QSM in GamepadUI through one of the Left Controller Special Buttons or the Power Button ontop.
This should be fixed by HandyGCCS but we've had issues getting it working, any help in debugging this would be much appreciated.

That may also fix the desktop control issue.

**Comment by NightHammer1000** [comment]
HandyGCCS apparently does not have OneXplayer 2 Pro support.
I submitted to Keycodes today.
https://github.com/ShadowBlip/HandyGCCS/issues/126

**Comment by NightHammer1000** [comment]
Adding `/etc/modprobe.d/oxp-hda-fix.conf`
with
`options snd_intel_dspcfg dsp_driver=1`

Made Audio work.

**Comment by pastaq** [comment]
> Adding `/etc/modprobe.d/oxp-hda-fix.conf` with `options snd_intel_dspcfg dsp_driver=1`
> 
> Made Audio work.

Interesting. I've only been able to confirm this on the non-pro previously.

**Comment by NightHammer1000** [comment]
Found the Turbo Button.
Its controlled through EC to switch between the Power Mode and the Hotkey mode.
After setting the EC Address 0xEB to 0x40
After that the Button sends CTRL+ALT+META (17, 18, 91)

**Comment by NightHammer1000** [comment]
Fan Control:

EC 0x4A controls the Fan. 0x00 for Automatic, 0x01 for Manual.
EC 0x4B controls the Speed

**Comment by NightHammer1000** [comment]
HandyGCCS Support will here soon thanks to an updated oxp-sensors Driver.

> This should be fixed by HandyGCCS but we've had issues getting it working
What's the Issue with in Bazzite? Does it just not run?

**Comment by NightHammer1000** [comment]
https://github.com/ShadowBlip/HandyGCCS/pull/127

**Comment by parth-menon** [comment]
> Adding `/etc/modprobe.d/oxp-hda-fix.conf` with `options snd_intel_dspcfg dsp_driver=1`
> 
> Made Audio work.

Did this work on your pro?
I tried this multiple times but still no audio on the Pro.

**Comment by NightHammer1000** [comment]
Yeah. I am starting to realize that it probably just was that I rebooted from Windows directly into Linux that made Audio work. Turning the Device off and Booting into Linux makes the Sound vanish again.

Dammit.

**Comment by NightHammer1000** [comment]
Using the latest CachyOS I now have consistent Audio!
@parth-menon @pastaq 

It runs Kernel 6.5.3-4

**Comment by NightHammer1000** [comment]
The Audio Issue is driving me mad.
6 from 10 shutdowns and reboots has Audio.
The other Time nothing.
Cant quite figure out why...

**Comment by pastaq** [comment]
This seems to affect the OXP2, OXP2 Pro, and OXP fly in the same way.

**Comment by NightHammer1000** [comment]
Some Progress on the Audio Front @pastaq 

Got Audio to work consistently. Microphone, Built-In Speakers and Audio Jack.
Volume really only starts at ~15% tho. But it works!

Heres the modprobe file i use:
`/etc/modprobe.d/alsa-base.conf`

```
options snd_intel_dspcfg dsp_driver=1
options snd_hda_intel power_save=0
options snd-hda-intel model=laptop-dmic enable=yes
```

`dsp_driver=1` made it appear in the first place.
`power_save=0` keeps it from vanishing.
`model=laptop-dmic` makes Microphone, Audio Jack and Built-In speakers work Reliably.

Hope this helps

**Comment by parth-menon** [comment]
> Some Progress on the Audio Front @pastaq
> 
> Got Audio to work consistently. Microphone, Built-In Speakers and Audio Jack. Volume really only starts at ~15% tho. But it works!
> 
> Heres the modprobe file i use: `/etc/modprobe.d/alsa-base.conf`
> 
> ```
> options snd_intel_dspcfg dsp_driver=1
> options snd_hda_intel power_save=0
> options snd-hda-intel model=laptop-dmic enable=yes
> ```
> 
> `dsp_driver=1` made it appear in the first place. `power_save=0` keeps it from vanishing. `model=laptop-dmic` makes Microphone, Audio Jack and Built-In speakers work Reliably. Even Headset Mic in the Audio Jack works.
> 
> Can you try again with this @parth-menon ?
> 
> Hope this helps
> 
> Tested on CachyOS Kernel: 6.5.9-1 sof-firmware 2023.09-1.1 alsa-utils 1.2.10-1.1

I'm on it!

**Comment by parth-menon** [comment]
> > Some Progress on the Audio Front @pastaq
> > Got Audio to work consistently. Microphone, Built-In Speakers and Audio Jack. Volume really only starts at ~15% tho. But it works!
> > Heres the modprobe file i use: `/etc/modprobe.d/alsa-base.conf`
> > ```
> > options snd_intel_dspcfg dsp_driver=1
> > options snd_hda_intel power_save=0
> > options snd-hda-intel model=laptop-dmic enable=yes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `dsp_driver=1` made it appear in the first place. `power_save=0` keeps it from vanishing. `model=laptop-dmic` makes Microphone, Audio Jack and Built-In speakers work Reliably. Even Headset Mic in the Audio Jack works.
> > Can you try again with this @parth-menon ?
> > Hope this helps
> > Tested on CachyOS Kernel: 6.5.9-1 sof-firmware 2023.09-1.1 alsa-utils 1.2.10-1.1
> 
> I'm on it!

I tried this. It didn't work for me.
Do I have to boot in from Windows?
![Uploading 20231030_141311.jpg…]()

**Comment by NightHammer1000** [comment]
No.
Can you check what kernel Version you have?

**Comment by parth-menon** [comment]
> No. Can you check what kernel Version you have?

I'm on 6.5.6.

**Comment by NightHammer1000** [comment]
Can you try a different Distro? I see you used Chimera.
It could really be that this only works on the newest Stable/Mainline Kernel.

**Comment by parth-menon** [comment]
> Can you try a different Distro? I see you used Chimera. It could really be that this only works on the newest Stable/Mainline Kernel. I don't even have Windows on my SSD anymore. So it can't be that it's only working because of First Windows Boot.
> 
> Best to try something Arch Based.

I'll try Mint. Whats the kernel version you are on?

**Comment by NightHammer1000** [comment]
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.5.8
Looking at that there are some Realtek Audio Fixes in here.
So try anything above that.
I was at 6.5.9

**Comment by NightHammer1000** [comment]
Also check what BIOS Version you are on

**Comment by parth-menon** [comment]
> Also check what BIOS Version you are on

I'm on 1.05.

**Comment by NightHammer1000** [comment]
Thanks. That seems to check out.

**Comment by parth-menon** [comment]
> > Can you try a different Distro? I see you used Chimera. It could really be that this only works on the newest Stable/Mainline Kernel. I don't even have Windows on my SSD anymore. So it can't be that it's only working because of First Windows Boot.
> > Best to try something Arch Based.
> 
> I'll try Manjaro. Whats the kernel version you are on?

I tried Manjaro but thats still on 6.5.5
I couldn't get 6.5.9 to install on it.
What linux are you using?

**Comment by parth-menon** [comment]
> > > Can you try a different Distro? I see you used Chimera. It could really be that this only works on the newest Stable/Mainline Kernel. I don't even have Windows on my SSD anymore. So it can't be that it's only working because of First Windows Boot.
> > > Best to try something Arch Based.
> > 
> > 
> > I'll try Manjaro. Whats the kernel version you are on?
> 
> I tried Manjaro but thats still on 6.5.5 I couldn't get 6.5.9 to install on it. What linux are you using? @NightHammer1000

Okay i finally got 6.6.0 installed on Manjaro but still no audio after trying the above fix.

**Comment by NightHammer1000** [comment]
Well. Thats fucked. 
Than something I did while thinkering around made it work.
One of the 1000 Things I tried.

**Comment by parth-menon** [comment]
> Well. Thats fucked. Than something I did while thinkering around made it work. One of the 1000 Things I tried.



> Well. Thats fucked. Than something I did while thinkering around made it work. One of the 1000 Things I tried.

Could you try the change on a fresh install on an external ssd, so that you don't lose your working Linux?

**Comment by NightHammer1000** [comment]
Another Issue. USB Ports get turned off sometimes if you disconnect something. Like the Detachable Controllers for example. 
Reboot needed to get them Going again.

Fix for it curtesy of Paulicat on the OneX Discord:

add `usbcore.autosuspend=-1` as a Kernel Paramenter

**Comment by FriendlyAndyC** [comment]
> Adding `/etc/modprobe.d/oxp-hda-fix.conf` with `options snd_intel_dspcfg dsp_driver=1`
> 
> Made Audio work.

Sorry for dumb question, but I cannot find oxp-hda-fix.conf. Can you kindly tell me how to add that? Thank you in advance.

**Comment by parth-menon** [comment]
> > Adding `/etc/modprobe.d/oxp-hda-fix.conf` with `options snd_intel_dspcfg dsp_driver=1`
> > Made Audio work.
> 
> Sorry for dumb question, but I cannot find oxp-hda-fix.conf. Can you kindly tell me how to add that? Thank you in advance.

You can just add a new file using
`sudo nano` or `sudo touch`

**Comment by FriendlyAndyC** [comment]
Sorry if this is off-topic. But these things doesn't seem to work on my OneXplayer Fly:
- Refresh rate control
- TDP Control and also locked at 15W
- No Audio
I believe my OneXFly has the same specs as Onexplayer 2 Pro. I couldn't find any related topics. Do you guys find any workarounds? Thank you in advance.

**Comment by parth-menon** [comment]
> Sorry if this is off-topic. But these things doesn't seem to work on my OneXplayer Fly:
> 
> * Refresh rate control
> * TDP Control and also locked at 15W
> * No Audio
>   I believe my OneXFly has the same specs as Onexplayer 2 Pro. I couldn't find any related topics. Do you guys find any workarounds? Thank you in advance.

I haven't looked into the first two but me, @NightHammer1000 and a couple of guys tried a lot to fix the audio. Because there is no support from OneNetbook to support this, we had to give up.

**Comment by NightHammer1000** [comment]
Yeah. Sold my Device and got a Legion Go instead.
Much better experience (Just not on Bazzite, that is) and even saved a bit of money.

So yeah. If you plan on SteamOS, DO NOT GET OneNetbook DEVICES.
I generally advice against it as the Community Support is non-existent.
The only time they talk to the community is when they have stuff to sell.

**Comment by parth-menon** [comment]
> Sorry if this is off-topic. But these things doesn't seem to work on my OneXplayer Fly:
> 
> * Refresh rate control
> * TDP Control and also locked at 15W
> * No Audio
>   I believe my OneXFly has the same specs as Onexplayer 2 Pro. I couldn't find any related topics. Do you guys find any workarounds? Thank you in advance.

If you want Audio to work, keep Windows dual boot with default as ChimeraOS. Boot into Windows and play some audio, force shutdown and then boot into ChimeraOS

**Comment by namquang93** [comment]
Just my 2 cents, some people on Reddit said that there is a BIOS update that fixes the audio issue for the OneXFly: https://www.reddit.com/r/OneXPlayer/comments/1fdm60d/comment/lmibmrg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

but I can't find an update for the OXP 2 Pro 7804U and I'm already on the latest build 1.0.5. Looks like the device is no longer being supported.

**Comment by parth-menon** [comment]
> Just my 2 cents, some people on Reddit said that there is a BIOS update that fixes the audio issue for the OneXFly: https://www.reddit.com/r/OneXPlayer/comments/1fdm60d/comment/lmibmrg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
> 
> but I can't find an update for the OXP 2 Pro 7804U and I'm already on the latest build 1.0.5. Looks like the device is no longer being supported.

Interesting. I will try it out and report back
