### ISSUE TITLE
Mangohud not working on bazzite-nvidia

### ISSUE THREAD

**Issue by APoorDev** [ublue-os/bazzite#445]
I previously had Mangohud working when I manually layered Goverlay and Mangohud with rpm-ostree. I saw there was an update for the nvidia image that added the bazzite version of mangohud, so I removed the layered mangohud and goverlay, and updated 'rpm-ostree' and 'just update'. 

Now mangohud seems to be broken or incomplete. If I run 'mangohud vkcube' I get the following error in the terminal with no mangohud display.

```
ERROR: ld.so: object '/usr/$LIB/mangohud/libMangoHud_opengl.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Selected GPU 0: NVIDIA GeForce GTX 1080 Ti, type: DiscreteGpu
```

If I try to layer mangohud again with rpm-ostree I get the following.
```
error: "mangohud" is already provided by: mangohud-100.bazzite.0.0.git.747.40ec1d49-1.fc38.i686 mangohud-100.bazzite.0.0.git.747.40ec1d49-1.fc38.x86_64. Use --allow-inactive to explicitly require it.
```

Any help would be appreciated!

**Comment by KyleGospo** [comment]
This should now be fixed, was an issue with our MangoHud package missing some .so files

**Comment by APoorDev** [comment]
Awesome! Thanks for the fix!
