### ISSUE TITLE
Bazzite portal isn't downloading or installing anything on a fresh install on my Steam Deck

### ISSUE THREAD

**Issue by narcester** [ublue-os/bazzite#455]
I have installed Bazzite on my Steam Deck and the portal prompted me to install the necessary apps. I clicked on which ones I wanted to install but when I clicked next and went to show console, everything was getting an error, something with distrobox not having podman or docker. I tried the next section with trying to install other apps such as web browsers, streaming etc. Again, all errors. Nothing is getting installed.

**Comment by narcester** [comment]
Somehow, it magically worked just by connecting to my wi-fi instead. No clue why.

**Comment by zakbaig** [comment]
![image](https://github.com/ublue-os/bazzite/assets/59240081/01e80a01-283e-4b71-9169-865ab46f7de3)

+1 - I'm getting the exact same issue.

**Comment by KyleGospo** [comment]
Thanks for the report, this should be fixed in the latest version.

**Comment by narcester** [comment]
Yep, everything works fine now! Thank you once again!
