### ISSUE TITLE
rpm-ostree update and just update error 

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#457]
Hi i keep receiving "error: creating importer: failed to invoke skopeo proxy method OpenImage: remote error: lstat var/ublue-os: no such file or directory" when trying the rpm-ostree update or just update command on rhe steam deck..any advice how i should resolve it this is a fresh install using offline iso.

**Comment by KyleGospo** [comment]
@gerblesh

**Comment by KyleGospo** [comment]
In the meantime, please run one of the rebase commands in our readme to resolve this issue.

**Comment by DarkenLX** [comment]
Ok thanks
