### ISSUE TITLE
[bazzite-gnome-deck] (nested) Can't launch firefox

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#463]
Thank you for adding a nested desktop feature for game mode (wish there was some easy way to keep up with bazzite new features tho). I've tried it but unfortunately I can't even launch the browser from there. It's just loading on top panel and then crashing.

**Comment by KyleGospo** [comment]
Next release should clean this up, let me know if you still see otherwise.

**Comment by unicornsandcandies** [comment]
> Next release should clean this up, let me know if you still see otherwise.

Just updated today. Still the same. Do you mean next gnome release or bazzite

**Comment by Zelaf** [comment]
I'm having a similar issue where a lot of apps won't start, terminal, Firefox, etc. A few works like OBS, Lutris, Flatseal, protonplus.
