### ISSUE TITLE
Gamescope will not launch on GPD Win Max 2020 (Intel 1035G7 iGP)

### ISSUE THREAD

**Issue by Daxiongmao87** [ublue-os/bazzite#468]
This did work at one point, albeit with some artifacts.  However, now, with the latest build (v1.3.0), trying to enter game mode only resets back to desktop.

This is all that return-to-gamemode.service log returns:
```
Oct 25 11:46:30 fedora systemd[1]: Starting return-to-gamemode.service - Return to Gaming Mode...
Oct 25 11:46:30 fedora sudo[34001]:     root : PWD=/ ; USER=steam ; COMMAND=/usr/bin/qdbus org.kde.Shutdown /Shutdown org.kde.Shutdown.logout
Oct 25 11:46:30 fedora systemd[1]: return-to-gamemode.service: Deactivated successfully.
Oct 25 11:46:30 fedora systemd[1]: Finished return-to-gamemode.service - Return to Gaming Mode.
```

GPU involved is the [Intel 1035G7 iGP, Intel Iris Plus Graphics](https://ark.intel.com/content/www/us/en/ark/products/196592/intel-core-i51035g7-processor-6m-cache-up-to-3-70-ghz.html)

**Comment by Daxiongmao87** [comment]
I believe all i need to do is enable NVIDIA_DEBUG=noccs for the gamescope session, but since this is an immutable OS and the devs don't seem to want to include a way to temporarily make it writeable like the steam deck, I'm at a loss.

**Comment by KyleGospo** [comment]
> I believe all i need to do is enable NVIDIA_DEBUG=noccs for the gamescope session, but since this is an immutable OS and the devs don't seem to want to include a way to temporarily make it writeable like the steam deck, I'm at a loss.

That launch option should only apply to Nvidia GPUs.

You can `sudo rpm-ostree usroverlay` to make this system writable until you reboot.

**Comment by Daxiongmao87** [comment]
Apologies, I meant to type INTEL_DEBUG=noccs, not NVIDIA_DEBUG.  Thanks I'll give this a go.

**Comment by KyleGospo** [comment]
https://github.com/KyleGospo/gamescope-session/blob/main/usr/share/gamescope-session-plus/gamescope-session-plus

Right now `export INTEL_DEBUG=norbc` is applied, matching ChimeraOS. If you confirm this resolves the issue for you, send me your `cat /sys/devices/virtual/dmi/id/product_name` and I'll make it also apply noccs on that hardware, plus submit to Chimera.

**Comment by Trozmagon** [comment]
Can confirm adding INTEL_DEBUG solved this issue for me on an i3 Ayaneo air plus.

The product name if you want to add it is "AIR plus"

**Comment by KyleGospo** [comment]
Latest updates to gamescope may have resolved this, please re-open if not
