### ISSUE TITLE
OpenRazer does not seem to work?

### ISSUE THREAD

**Issue by KaiserCalm** [ublue-os/bazzite#473]
I have installed OpenRazer by running `just install-openrazer`, everything seems to work and the Fedora container is installed successfully, hover after installing RazerGenie from the Software Center as a user Flatpak and running it, it tells me that it cannot find the daemon, I tried installing the Flatpak in the Fedora container directly and the issue was still present. Maybe I'm missing something?

**Comment by KyleGospo** [comment]
Openrazer is installed in distrobox, you would need to install RazerGenie in the same distrobox if you want to use it.

`distrobox enter fedora`

**Comment by KyleGospo** [comment]
You may also now just re run the openrazer just command after updating!

**Comment by gdeyoung** [comment]
Updated to 1.4.0 and looked and Openrazer was not in the Fedora Distrobos

So ran just install-openrazer

Everything installed.  Rebooted

Then opened razergenie, it throws an error:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

Tried starting the OpenRazer service: sudo systemctl start openrazer-daemon.service

But the system doesn't use systemd.  

How is this supposed to work again and the service set to run by default with the just command?

**Comment by AustinSaintAubin** [comment]
# Bazzite | RazerGenie w/ OpenRazer

## Install RazerGenie w/ OpenRazer
```
ujust install-openrazer
```

---

## Get Status / Error
```
openrazer-deamon --help
openrazer-deamon --foreground
```

---

## Fix group permissions (varies by package)
```
# If it says GROUP="openrazer":
sudo usermod --append --groups openrazer "$USER"

# If it says GROUP="plugdev":
sudo groupadd --force plugdev
sudo usermod --append --groups plugdev "$USER"
```

## Check  Load the kernel modules (if needed)
```
# Check:
lsmod | grep -i razer

# If they didn't autoload:
sudo modprobe razerkbd || true
sudo modprobe razermouse || true
sudo modprobe razerkraken || true

# Verify:
lsmod | grep -i razer
```

## Reboot
```
reboot
```

---

## Check if Worked
```
openrazer-deamon --help
openrazer-deamon --foreground
```

**Comment by Harrison-Bar** [comment]
This helped resolve my issue with getting Openrazer working with Polychromatic on Bazzite.  Thank you @AustinSaintAubin.
