### ISSUE TITLE
Issue: Showcase images on website are broken

### ISSUE THREAD

**Issue by Nitrousoxide** [ublue-os/bazzite#476]
The Ublue site for Bazzite has broken images for the showcase portion of the page:

<img width="1240" alt="image" src="https://github.com/ublue-os/bazzite/assets/1363931/fe9b0921-b8e9-4d83-8674-d2fc8eb32125">

**Comment by nicknamenamenick** [comment]
Oh shoot!  I'll try to fix that. Thanks!
