### ISSUE TITLE
OpenRazer still not working after the update

### ISSUE THREAD

**Issue by gdeyoung** [ublue-os/bazzite#478]
Updated to 1.4.0 and looked and Openrazer was not in the Fedora Distrobox

So ran just install-openrazer

Everything installed. Rebooted

Then opened razergenie, it throws an error:
The OpenRazer daemon is currently not available
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

Tried starting the OpenRazer service: sudo systemctl start openrazer-daemon.service

But the system doesn't use systemd.

How is this supposed to work again and the service set to run by default with the just command install for OpenRazer?

**Comment by KyleGospo** [comment]
Looking at this tonight, get back to you soon

**Comment by KyleGospo** [comment]
Newest release has a replacement service, you can run the install again to get it. It'll also add you to the needed plugged group.

**Comment by gdeyoung** [comment]
Reran the just isntall-openrazer.  I can see where it is copying the .service file.  

2023-10-29 00:34:29 (67.5 MB/s) - ‘/var/home/gdeyoung/.config/systemd/user/openrazer-daemon.service’ saved [256/256]

Reboot and still get the same error in Razergenie, the the service is not started.

Here is the full text from the just install-openrazer

if grep -qvz "fedora" <<< $(distrobox list); then distrobox-create --nvidia --image ghcr.io/ublue-os/fedora-distrobox:latest -n fedora -Y; fi && distrobox-enter -n fedora -- bash -c 'sudo wget https://download.opensuse.org/repositories/hardware:/razer/Fedora_$(rpm -E %fedora)/hardware:razer.repo -O /etc/yum.repos.d/hardware:razer.repo && sudo dnf install -y openrazer-meta razergenie && distrobox-export --app razergenie' && wget https://raw.githubusercontent.com/ublue-os/bazzite/main/post_install_files/OpenRazer/openrazer-daemon.service -O ~/.config/systemd/user/openrazer-daemon.service && systemctl --user daemon-reload && systemctl enable --user openrazer-daemon.service && if ! grep -q "plugdev" /etc/group; then sudo bash -c 'grep "plugdev" /lib/group >> /etc/group' ; fi && sudo usermod -a -G plugdev $USER && echo "Please reboot to apply needed changes."
--2023-10-29 00:34:26--  https://download.opensuse.org/repositories/hardware:/razer/Fedora_38/hardware:razer.repo
Resolving download.opensuse.org (download.opensuse.org)... 2001:67c:2178:8::13, 195.135.221.134
Connecting to download.opensuse.org (download.opensuse.org)|2001:67c:2178:8::13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 260 [application/x-download]
Saving to: '/etc/yum.repos.d/hardware:razer.repo'

/etc/yum.repos.d/hardware:razer.repo         100%[==============================================================================================>]     260  --.-KB/s    in 0s      

2023-10-29 00:34:27 (3.99 MB/s) - '/etc/yum.repos.d/hardware:razer.repo' saved [260/260]

hardware:razer (Fedora_38)                                                                                                                          4.3 kB/s | 1.6 kB     00:00    
Package openrazer-meta-3.6.1-1.1.noarch is already installed.
Package razergenie-1.1.0-1.1.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
Application razergenie successfully exported.
OK!
razergenie will appear in your applications list in a few seconds.
--2023-10-29 00:34:29--  https://raw.githubusercontent.com/ublue-os/bazzite/main/post_install_files/OpenRazer/openrazer-daemon.service
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 256 [text/plain]
Saving to: ‘/var/home/gdeyoung/.config/systemd/user/openrazer-daemon.service’

/var/home/gdeyoung/.config/systemd/user/open 100%[==============================================================================================>]     256  --.-KB/s    in 0s      

2023-10-29 00:34:29 (67.5 MB/s) - ‘/var/home/gdeyoung/.config/systemd/user/openrazer-daemon.service’ saved [256/256]

**Comment by gdeyoung** [comment]
Any ideas on this one?

**Comment by KyleGospo** [comment]
These packages are now layered instead of installed in Distrobox on the latest builds, that should resolve these issues.

**Comment by KaiserCalm** [comment]
Even with the layered version of OpenRazer and RazerGenie I get the following error:
![image](https://github.com/ublue-os/bazzite/assets/81613945/fe76eb66-dc35-408b-ab28-cdf279f3fd9d)

**Comment by rusagent** [comment]
I'm having the exact same problem. Just installed bazzite with the latest iso...
