### ISSUE TITLE
[Feature Request] Keyboardless decryption step

### ISSUE THREAD

**Issue by prx0** [ublue-os/bazzite#481]
Hi,
I'm new to Bazzite but I know Fedora. I choose Bazzite because of the Full Disk Encryption feature.
Everything looks great but it looks like I need a physical keyboard to enter my passphrase. AFAIK there is no way to get a virtual keyboard to let me enter my passphrase

It would be great to trigger a virtual keyboard when the user press some buttons (like SteamOS does in desktop mode or in game)

I don't know how much hard it is to implement. It does not look easy to add but I could really improve the user experience.

Thank you for reading

**Comment by KyleGospo** [comment]
https://github.com/ublue-os/bazzite/issues/464

This would be how we implement it, but we need to figure out supporting fbdev or re-enabling DRM on deck without consuming card0.

**Comment by KyleGospo** [comment]
FYI:

In the meantime you could use a Yubikey or other hardware unlocker method.
