### ISSUE TITLE
New Mesa Driver when?

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#482]
games like Mortal Kombat 1 not reading correct VRAM game stuck on medium graphics
alan wake needs a patch to work
`https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25659`

**Comment by noelmiller** [comment]
Due to the lack of activity on this issue, I am going to close this issue. Please try the latest build of Bazzite and reopen the issue if you are still having problems!
