### ISSUE TITLE
error starting waydroid

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#485]
this is clean waydroid setup btw on steam deck using the specific deck install.
followed the waydroid guide section in the faq/wiki
at the step "sudo waydroid shell"
konsole outputs "waydroid session is stopped"
so when running "waydroid session start" 
i get this output in the waydroid log the last two lines are the only line shown in konsole but i assume the others are relevant
(006023) [00:13:30] Starting waydroid session
(006023) [00:13:30] org.freedesktop.DBus.Error.ServiceUnknown: Could not activate remote peer: startup job failed.
(006023) [00:13:30] WayDroid container is not listening
(007985) [00:17:46] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(007985) [00:17:46] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

any idea what's wrong or a fix?

**Comment by KyleGospo** [comment]
GPS and ARM64 both work, we'll be updating the documentation soon.

**Comment by bi0shacker001** [comment]
It looks like this may be related to the bug I reported a few days ago. I overlooked it because ARM was mentioned.
Did 39 fix the problem for you? It did for me. (I'll close mine as a dup if so)

**Comment by DarkenLX** [comment]
> It looks like this may be related to the bug I reported a few days ago. I overlooked it because ARM was mentioned. Did 39 fix the problem for you? It did for me. (I'll close mine as a dup if so)

39? You mean Fedora 39/ bazzite latest? I can't figure out how to get 39 so im not sure if it fixes it sorry if theres instructions how to get 39 i can try to check but everything i downloaded so far was 38.

**Comment by bi0shacker001** [comment]
:latest is 39 now, but you can also rebase to :39 to get it specifically.
Instructions on how to rebase are located on the universalblue website (https://universal-blue.org/images/)
For example, the command for bazzite 37 is: `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:37`
The URL specifies the image, and at the end is the tag, which is separated by ":". If you wanted 38, that would be 38 instead of 37.

**Comment by DarkenLX** [comment]
> :latest is 39 now, but you can also rebase to :39 to get it specifically. Instructions on how to rebase are located on the universalblue website (https://universal-blue.org/images/) For example, the command for bazzite 37 is: `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:37` The URL specifies the image, and at the end is the tag, which is separated by ":". If you wanted 38, that would be 38 instead of 37.

Oh ok im kinda new to the Fedora and bazzite based commands vs arch or what i use on other computers (Ubuntu) so i didn't know what needed to be changed on that command to do that i didn't  think it was that simple to just change the number lol.

**Comment by bi0shacker001** [comment]
Yep! Did that fix the problem?

**Comment by DarkenLX** [comment]
> Yep! Did that fix the problem?

Not sure i am reinstalling bazzite just to make sure everything is out of box before i upgrade (just incase something causes an issue) i will report back ASAP

**Comment by bi0shacker001** [comment]
Gotcha. I'll assume this is a different error than what I'm experiencing, then

**Comment by KyleGospo** [comment]
Be sure you're using waydroid-launcher and following our guide, it's recently been updated for F39.

**Comment by DarkenLX** [comment]
> Be sure you're using waydroid-launcher and following our guide, it's recently been updated for F39.

followed it on 39 this is what i get for an error:
/usr/lib/waydroid/tools/helpers/net.py:34: SyntaxWarning: invalid escape sequence '\d'
  return re.search("(\d{1,3}\.){3}\d{1,3}\s", f.read()).group().strip()
weston: no process found
sh: -c: line 1: unexpected EOF while looking for matching `"'
Job for waydroid-container.service failed because the control process exited with error code.
See "systemctl status waydroid-container.service" and "journalctl -xeu waydroid-container.service" for details.
/usr/lib/waydroid/tools/helpers/net.py:34: SyntaxWarning: invalid escape sequence '\d'
  return re.search("(\d{1,3}\.){3}\d{1,3}\s", f.read()).group().strip()
[16:07:06] Starting waydroid session
[16:07:07] WayDroid container is not listening

nothing is outputted after this and waydroid launcher just shows a blank screen.

**Comment by AnriEvs** [comment]
> > Be sure you're using waydroid-launcher and following our guide, it's recently been updated for F39.
> 
> followed it on 39 this is what i get for an error: /usr/lib/waydroid/tools/helpers/net.py:34: SyntaxWarning: invalid escape sequence '\d' return re.search("(\d{1,3}.){3}\d{1,3}\s", f.read()).group().strip() weston: no process found sh: -c: line 1: unexpected EOF while looking for matching `"' Job for waydroid-container.service failed because the control process exited with error code. See "systemctl status waydroid-container.service" and "journalctl -xeu waydroid-container.service" for details. /usr/lib/waydroid/tools/helpers/net.py:34: SyntaxWarning: invalid escape sequence '\d' return re.search("(\d{1,3}.){3}\d{1,3}\s", f.read()).group().strip() [16:07:06] Starting waydroid session [16:07:07] WayDroid container is not listening
> 
> nothing is outputted after this and waydroid launcher just shows a blank screen.

Have the same issue, "waydroid container is not listening" has this been fixed yet or no?

**Comment by KyleGospo** [comment]
> > > Be sure you're using waydroid-launcher and following our guide, it's recently been updated for F39.
> > 
> > followed it on 39 this is what i get for an error: /usr/lib/waydroid/tools/helpers/net.py:34: SyntaxWarning: invalid escape sequence '\d' return re.search("(\d{1,3}.){3}\d{1,3}\s", f.read()).group().strip() weston: no process found sh: -c: line 1: unexpected EOF while looking for matching `"' Job for waydroid-container.service failed because the control process exited with error code. See "systemctl status waydroid-container.service" and "journalctl -xeu waydroid-container.service" for details. /usr/lib/waydroid/tools/helpers/net.py:34: SyntaxWarning: invalid escape sequence '\d' return re.search("(\d{1,3}.){3}\d{1,3}\s", f.read()).group().strip() [16:07:06] Starting waydroid session [16:07:07] WayDroid container is not listening
> > 
> > nothing is outputted after this and waydroid launcher just shows a blank screen.
> 
> Have the same issue, "waydroid container is not listening" has this been fixed yet or no?

There's nothing to fix, it works if you follow our guide.

**Comment by AnriEvs** [comment]
Thank you for the fast reply! got it working by just using ujust setup-waydroid on the terminal
