### ISSUE TITLE
Extract Waydroid to separate repository

### ISSUE THREAD

**Issue by plata** [ublue-os/bazzite#487]
Bazzite provides a bunch of tooling around Waydroid. It would be nice to have this in a separate repository such that other ublue versions (incl. startingpoint) can reuse it.

Or maybe just add it to bling?

I've tried to include Waydroid in https://github.com/plata/ublue-surface but apparently just `rpm-ostree install waydroid` isn't sufficient (see https://github.com/waydroid/waydroid/issues/1032 and https://github.com/ublue-os/main/issues/223).

**Comment by KyleGospo** [comment]
The amount of fixes needed would make it difficult to maintain elsewhere, best to bring in changes as we make them unfortunately
