### ISSUE TITLE
`just update` No Longer Prints Anything to the Terminal

### ISSUE THREAD

**Issue by KaiserCalm** [ublue-os/bazzite#490]
Running `just update` now only displays the following:
```
user@bazzite ~> just update
Starting the ublue-update service
[sudo] password for user: 
user@bazzite ~>
 ```

I might be mistaken, but I remember it printing everything it was doing to the terminal. Having an indicator that everything is working fine would be nice.

**Comment by gdeyoung** [comment]
I have the same issue, It used to print now it is hidden.  I agree I used the output to tell if everything worked correctly

**Comment by aenertia** [comment]
There is a deprecation in python that the just scripts appear to  use regarding the .re search expressions basically they need to use raw version of the same module or double escape. This affects the i.e waydroid just scripts and I assume it's also what's broken here as well

**Comment by KyleGospo** [comment]
@gerblesh

**Comment by KyleGospo** [comment]
Please open an issue at ublue-os/updater
