### ISSUE TITLE
No audio at all for ROG Ally

### ISSUE THREAD

**Issue by v1k0d3n** [ublue-os/bazzite#492]
It appears that there's absolutely zero sound for the ROG Ally at this time. Is this currently expected with where the project is currently at, or is there a potential bug workaround that I can attempt on my end?

If there's any way that I can help with this effort, please let me know. It would be pretty amazing to get Bazzite working on this device. Thanks!

**Comment by v1k0d3n** [comment]
is it safe to assume that it would be broken on future versions? I believe that I was running/testing on bios 330.

**Comment by KyleGospo** [comment]
Fixed in next release coming this weekend
