### ISSUE TITLE
[beta - 39 image] no easy way to return to game mode

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#503]
I'm using fedora 39, rebased with the help of your tutorial on the blog. Currently there's no easy way for an user to return to the game mode. 

You can log off and it seems to work but I doubt most users will think of it.

**Comment by KyleGospo** [comment]
You don't have the logo menu in the top left? Check your extension list, should be there as a system extension.

**Comment by unicornsandcandies** [comment]
> You don't have the logo menu in the top left? Check your extension list, should be there as a system extension.

That was silly of me. It works, thank you. Seems like it was turned off by default for some reason
