### ISSUE TITLE
[Deck] Disable BIOS update

### ISSUE THREAD

**Issue by FalkorTV** [ublue-os/bazzite#506]
![1699020951810132349800397984949](https://github.com/ublue-os/bazzite/assets/57044063/8f7be323-9962-421f-a8d7-2a7a772bd2ba)
Even though Bios updates are disabled, Steam downloads and installs BIOS updates. Downgrade 116 always want to update for 118

**Comment by KyleGospo** [comment]
2.0.0 features a fix for this.
