### ISSUE TITLE
Can't Control Mouse In GNOME Desktop Mode With Deck Trackpads

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#515]
I think this has something to do with the new GNOME version. I rebased to the 39 branch early, and I noticed it prompted me to allow "Remote Control" whenever I would touch the trackpad for the first time in desktop mode (only after Steam launched).  Now that I have rebased on latest and updated, it no longer prompts me for that, but the functionality of actually using the mouse cursor from Deck is lost without an external mouse.

**Comment by KyleGospo** [comment]
Fixed as of the latest commit.
