### ISSUE TITLE
Issue Fetching Updates in Game Mode

### ISSUE THREAD

**Issue by jacobranson** [ublue-os/bazzite#516]
I see that the "latest" branch is selected by default in the Game Mode update menu. Unfortunately, clicking "Check for updates" causes an error which Steam will report, but does not detail what the error is.

**Comment by KyleGospo** [comment]
The gamemode updater is just a wrapper for `ublue-update`, if you run that in a terminal do you get any errors?

Good time to also check `rpm-ostree status` and make sure you're on the `:latest` branch.

**Comment by jacobranson** [comment]
I am on latest. When I run ublue-update in Bash I get no errors. In game mode, it just says the following:

Update Error
An error was encountered during the update process, please try again.

It is worth noting that when dismissing the dialog, whatever update is available is still found. My assumption is that since the update script is broken into those different subscripts, maybe one of them is returning a non-zero exit code and Steam picks it up?

I don't use homebrew but I see there is a homebrew update script running. Maybe that hits an "unknown command brew" or something like that? Just a wild guess

**Comment by jacobranson** [comment]
Also worth noting that as of today, Game Mode only shows a "System Update Channel" set to "Stable" under the "Beta Participation" section. No longer is there two sections like before, one for Steam and one for the OS. I wonder if that is a change on Valve's side.

**Comment by DarkenLX** [comment]
> Also worth noting that as of today, Game Mode only shows a "System Update Channel" set to "Stable" under the "Beta Participation" section. No longer is there two sections like before, one for Steam and one for the OS. I wonder if that is a change on Valve's side.

Do you have developer options turned on and "show advanced update channel" toggled in game mode? That's the only way those showup.

**Comment by SerjTargarien** [comment]
Was this ever solved for you? Having the same problem with my Bazzite install at the moment.

**Comment by mpetuska** [comment]
Did a fresh install last month and the issue still persists for me sadly

**Comment by SerjTargarien** [comment]
I was thinking about doing a fresh install, but I can see that it's not guaranteed to solve the issue, so I'll wait for a while and see if there are other solutions to the problem.

**Comment by codevski** [comment]
Same issue here on fresh install update error in game mode.

**Comment by SmoothTony** [comment]
I'm having the same error in game mode. Running ublue-update I receive no errors yet still unable to update.
