### ISSUE TITLE
Can't install bazzite on some laptops

### ISSUE THREAD

**Issue by darkvadd7** [ublue-os/bazzite#519]
Due to a bug in efibootmgr, I can't install bazzite. I have the same issue with Fedora, Kinoite and Nobara.

I don't know if something can be made, like pickng an older working version of efibootmgr...

Here is the link to the bug: [https://bugzilla.redhat.com/show_bug.cgi?id=2148480](https://bugzilla.redhat.com/show_bug.cgi?id=2148480).

Thanks.

**Comment by KyleGospo** [comment]
Hi, I'm afraid to fixing this is out of scope for us but hopefully upstream is able to get this resolved soon.
