### ISSUE TITLE
[Deck] Steam "Desktop Configuration" controls not working on KDE 39 in Wayland

### ISSUE THREAD

**Issue by vagrantwinds** [ublue-os/bazzite#520]
Steam's Desktop Mode controls do not work in Wayland with the new Fedora 39 update. For example, no mouse input from the right touch pad, no up/down from the d-pad, no enter from A, no left click from R2, etc. Steam+B also does not bring up the keyboard.

However, holding the Menu button still swaps between Desktop and Gamepad Modes and the Gamepad Mode still works with no issues.

Lizard Mode (Steam not running) still works in Fedora 39 Wayand. It seems to just be Steam's Desktop Mode controls that are affected. External KB&M also still work fine.

Desktop Mode controls work as intended in X11. Desktop mode controls also worked fine in Fedora 38 in Wayland before this update.

I have no idea if this is also an issue on the Gnome version as I do not run it.

**Comment by KyleGospo** [comment]
Fixed as of the latest commit
