### ISSUE TITLE
Displaylink was removed during an upgrade, no longer available?

### ISSUE THREAD

**Issue by bi0shacker001** [ublue-os/bazzite#523]
I'm not sure if this was an intentional design choice, but in the regular versions of bazzite and bazzite-gnome, displaylink appears to be gone now.
I can see from the changelogs that it was supposed to be disabled in the asus version, was the wrong version accidentally targetted for that?

**Comment by KyleGospo** [comment]
The latest version of DisplayLink was creating extra GPU devices that broke mangoHUD and performance control in the steam overlay. I'll work on fixing that and restoring it here soon.

**Comment by KyleGospo** [comment]
You can rebase to :unstable to get a build with this restored now.

**Comment by bi0shacker001** [comment]
Functionality appears to work as expected in :unstable, so closing as RESOLVED

**Comment by bi0shacker001** [comment]
Appears functionality has disappeared again, reopening

**Comment by bi0shacker001** [comment]
After double checking, I can confirm definitively that :unstable no longer contains displaylink and evdi, nor does :latest or :39. Is there a timeline to have it readded? I use it regularly, and it was one of the main reasons I installed bazzite (it allows me to use my laptop for work, not just gaming)

**Comment by bi0shacker001** [comment]
> You can rebase to `:unstable` to get a build with this restored now.

A further development:
It's in the bazzite-deck :unstable branch, but not bazzite or bazzite-gnome. So it appears to be going back and forth. It WAS in bazzite :unstable initially, any chance it can be put back in?

**Comment by KyleGospo** [comment]
Hitting stable on Friday
