### ISSUE TITLE
[Bug/FR] Remove Input denoising : /etc/pipewire/99-input-denoising.conf From base images

### ISSUE THREAD

**Issue by aenertia** [ublue-os/bazzite#527]
This setups up an echo-sink/source pair and passes through a filter.  This is undesired default behaviour

a) Sounds terrible on most hardware
b) Increases battery drain (in several different and interesting ways)
c) Can easily be done inside a users ~/.config/asound.conf etc if desired. 
d) Creates Video/Sound sync issues with conferencing/recording software
e) Potential privacy issue ( as the Input is constantly sampling audio without the user being notified)

Please remove this as a base image config, as mentioned if post-processing/echo cancellation is desired this can easily be done inside a users profile/homedir to the same effect.

**Comment by KyleGospo** [comment]
This file exists on the deck images because it's the same thing Valve ships in SteamOS on the deck. I'm open to a PR that adds this same filter only on Jupiter hardware.
