### ISSUE TITLE
[BUG] Waydroid helper scripts no longer work on FC39 due to use of deprecated .re search filter expression

### ISSUE THREAD

**Issue by aenertia** [ublue-os/bazzite#528]
Trying to follow the waydroid config guide for bazzite  (https://universal-blue.org/images/bazzite/waydroid/ )using the 'just' scripts fails due to use of deprecated python .re search filter expression (escape sequences need to use the raw call now, or be double escaped or sequences such as /d are interpreted as literals.

This leads to Waydroid being unusable currently.

**Comment by bi0shacker001** [comment]
To counter: despite the error messages, waydroid appears to function perfectly for me n FC39, both bazzite and bazzite-gnome

**Comment by aenertia** [comment]
Not working for me on -deck or -framework

**Comment by aenertia** [comment]
Just rebased to bazzite:latest and waydroid-launcher fails still

**Comment by bi0shacker001** [comment]
After a reinstall, I can confirm I am now experiencing this.

**Comment by KyleGospo** [comment]
Fixed in latest releases
