### ISSUE TITLE
[Advice] Instructions updating to v39 (with Nvidia image)

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#529]
I installed `Bazzite` over a month ago, so I am stuck on `Bazzite 38`. I would like to update to `39` but just want to clarify a few steps.

When I did my initial installation, I used the `bazzite-nvidia` image. I would like to _also switch_ to use `gnome`, so I believe I need to rebase against `bazzite-gnome-nvidia:latest`.

Here are the steps, as I understand them. My assumption is that I am running all of these commands from the `Konsole` app once logged into the desktop.

### On fresh boot

- Optional: `sudo ostree admin pin 0`
  - This helps with rolling back, but I dont think it is necessary. I believe there are already automatic rollback points.
- `just clean-system`
- `just update` _(same as `ublue-update`?)_
- `rpm-ostree reset`
- `rpm-ostree update`
- Reboot!

### Once rebooted

- Rebase to an unsigned version first.
  - `rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bazzite-gnome-nvidia:latest`
    - Am I correct to use `bazzite-gnome-nvidia:latest` as the "image name"?
      - Or should the image name simply be `bazzite`?
- Once this rebase is complete, run the following code snippet below:
  - Is the below code snippet the exact same as `just nvidia-set-kargs`?

```sh
rpm-ostree kargs \
    --append=rd.driver.blacklist=nouveau \
    --append=modprobe.blacklist=nouveau \
    --append=nvidia-drm.modeset=1
```

- Assuming I am still logged into my desktop, reboot again!

### Once rebooted again

- Enroll secure boot key.
  - Does this need to happen if I have already enrolled the key on initial installation?
  - `sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der`
    - Is this the same as `just enroll-secure-boot-key`?
- Finally, perform the rebase to `39`:
  - `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:latest`.
- Reboot once last time!

Assuming all went well, I should:

- `Bazzite 39`.
- Have `Gnome` as me DE.
- Everything configured for Nvidia.
- All my Steam games are still installed!

Once last final point. Lately I have been finding that Bazzite does not shut down properly, and I have to hard power-down. If I get stuck when rebooting, is it safe to hard reset?

Thanks for any advice!

**Comment by bi0shacker001** [comment]
You don't need to do 90% of this once you're already running bazzite. Just rebase to the new image and reboot.

**Comment by beefchimi** [comment]
Thanks for the advice! Simply doing the rebase appears to have worked nicely. I am now on version `39` with minimal fuss 😄 

I will close this issue, but just in case anyone is reading and has some answers:
1. How often should I `rebase` off of `:latest`?
  - Is this only for major version changes _(ex: upgrading from `38` to `39`)_?
  - Or, are there more things that are not automatically updated via `just update` and/or `Discover > Software Update`?
2. Are `nvidia` drivers updated automatically, or is that something we all need to do manually?
  - Would I use `rpm-ostree` to update these drivers? And if so, any "gotchas" I should be aware of?

Thanks!

**Comment by bi0shacker001** [comment]
1:Once you're on latest, automatic updates will handle updating. You never need to rebase to the tag you're currently running. Think of tags as a way of managing updates. If you're on latest, you always have the latest stanle-ish image (besides whatever is on unstable, of course). Rebasing to :39 is only useful if you're on, say, :38. It's version control.

2: Drivers are part of the image. They are handled with the image.

It seems like you might want to do more research about silverblue/kinoite and universal-blue. The issue tracker isn't the best place for these questions (it's generally considered poor etiquette to use a bug tracker for general usage questions), and running an immutable distro if you don't understand how OCI works is probably a bad idea. You might want to check out the community section on the universalblue website for places where you can talk about the distros and images ublue hosts/manages, particularly the discord.

**Comment by castrojo** [comment]
https://universal-blue.org/images/bluefin/admin/#upgrades-and-throttle-settings

This might help, and would apply to bazzite too.
