### ISSUE TITLE
[Steam] Why is SteamLink launching everytime I launch Steam?

### ISSUE THREAD

**Issue by beefchimi** [ublue-os/bazzite#535]
This has been happening for about a month. Everytime I open Steam, instead of the Taskbar > Steam icon indicating that it is running, I instead get a SteamLink app launched and showing in my Taskbar.

![steamlink](https://github.com/ublue-os/bazzite/assets/643944/08a498a5-955e-4008-b9a3-6ad30b48fb8d)

**Comment by duhow** [comment]
Check for the content:

```shell
grep launchers ~/.config/plasma-org.kde.plasma.desktop-appletsrc
```

**Comment by beefchimi** [comment]
@duhow I finally got a chance to run the command you suggested. The return is:

```sh
launchers=applications:systemsettings.desktop,applications:org.kde.discover.desktop,preferred://filemanager,applications:org.kde.konsole.desktop,applications:org.mozilla.firefox.desktop,applications:steam.desktop,applications:org.gnome.Prompt.desktop
```

FYI this is still happening in both X11 and Wayland, on the latest version of Bazzite _(I just updated earlier today)_

**Comment by beefchimi** [comment]
Anyone have any suggestions for this issue?

**Comment by beefchimi** [comment]
I think this is finally solved. Within `~/.local/share/applications` was a `bazzite-arch-com.valvesoftware.SteamLink.desktop` file. I deleted that file, and now `Steam` appears correctly launched in the TaskBar!
