### ISSUE TITLE
reset-waydroid command  error/broken

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#553]
running ujust reset-waydroid in terminal results in:
ujust reset-waydroid
error: Unknown start of token:
    |
165 |   distrobox-create --nvidia --image quay.io/toolbx-images/centos-toolbox:latest -n centos -Y
    |                    ^

this is on bazzite-deck:latest
can't reset waydroid and running the init-waydroid presents that same error.
any fix/workaround? im not even sure what the error is even trying to tell me.

**Comment by castrojo** [comment]
Do an `rpm-ostree update` to get the fix and reboot, sorry about that!

**Comment by DarkenLX** [comment]
> Do an `rpm-ostree update` to get the fix and reboot, sorry about that!

Ah ok will that fix the system update applying stalling at 99% under system in game mode ?

**Comment by castrojo** [comment]
No that will just fix the error you have, I'm unsure about the 99% thing. I'm not too familiar with bazzite in that regard but please open an issue for that if one doesn't exist already. Thanks!
