### ISSUE TITLE
Steam GameMode system update hanging 

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#554]
In game mode there appears to be a update under system apparently a "OS" Update  attempt to install just hanging at "Applying 99% / 00:01 remaining" any way to fix/remedy this? Already tried restarting the deck same issue. On Bazzite-deck:latest

**Comment by KyleGospo** [comment]
The progress is faked, it's not paused at 99%, merely taking longer than our guess. Leave it and it'll finish.

**Comment by DarkenLX** [comment]
> The progress is faked, it's not paused at 99%, merely taking longer than our guess. Leave it and it'll finish.

Oh ok i didn't know it was faked that explains it. Thanks
