### ISSUE TITLE
`$HOME` variable should point to `/var/home/$USER`

### ISSUE THREAD

**Issue by jgierer12** [ublue-os/bazzite#555]
### Expected behavior

The `$HOME` environment variable should be set to `/var/home/$USER` rather than the symlinked `/home/$USER`. This seems to be the default on other ublue-based images (at least on my Bluefin machine) but not on Bazzite.

### Actual behavior

`$HOME` is set to `/home/$USER`. This breaks some applications which don't handle symlinks well.

### Platform

bazzite-deck-gnome:39 (2023-11-16) on Steam Deck

**Comment by KyleGospo** [comment]
This behavior is unmodified from stock Silverblue/Kinoite, I would open an issue upstream for this. Out of scope for our case.
