### ISSUE TITLE
[Feature Request] Auto update at midnight or certain time spot

### ISSUE THREAD

**Issue by AkazaRenn** [ublue-os/bazzite#556]
Add a systemd service that checks if there are any updates (OS, packages, Steam) that require restart. If no game is running by that time, it can restart Steam or even the system.

**Comment by KyleGospo** [comment]
This is present in the desktop release, but the deck builds update through steam game mode exclusively.

**Comment by AkazaRenn** [comment]
> This is present in the desktop release, but the deck builds update through steam game mode exclusively. 

Yeah what I want is exactly for Steam Deck.  When under game mode, the actual update is system updates + Steam update, and Steam update is actually applied when it starts. So if there's a way to detect if there's an update for Steam (by comparing versions maybe?), we could simply trigger all the update process and then restart the system to do the job.

**Comment by Nitrousoxide** [comment]
I don't think you want to just reboot an online desktop system automatically.  Just because a user isn't running a game doesn't mean they aren't actively using it.

**Comment by AkazaRenn** [comment]
I don't see how people are "actively using" a Steam Deck in Game Mode while not in game during a time they chose to be idle, but anyways, we can add some other detecting mechanisms like if the system is sleeping, if the screen is on, if the system is being charged, etc..

**Comment by Nitrousoxide** [comment]
I don't see why this is needed.  It should already download and prepare the deployment for the next reboot.  There's no need to try to figure out all the possible situations where someone might be actively using it when you could just rely on them to reboot when convenient.

And Bazzite has versions for non-Steamdecks too, and their usecases differ substantially and leaving a system running but not in current use are very much possibilities there.
