### ISSUE TITLE
Can't add Dual boot second drive with Windows 11 Pro

### ISSUE THREAD

**Issue by JaCh0o** [ublue-os/bazzite#560]
Hello,
There's an instruction how to dual boot on one drive. In my case I got separate drive for bazzite deck htpc edition and found out that I can add thru ujust command option to unhide-grub but still even after regenerate it doesn't see my second drive with Windows.
I've tired to install grub customizer but it can't be added only thru container so it failed (it needs grub2 which can't be added thru distrobox).
I've also tried to ujust regenerate-grub but still it didn't found drive. Any possible solutions?

Ps I would like also to remove 3 bazzite positions from my grub to leave only:
Bazzite OS (default)
Windows 11 Pro
UEFI Firmware Settings

Can someone help me out with that ?

**Comment by yoyossef** [comment]
Check if `os-prober` is installed, run it to see if it can detect your Windows drive, should output something like:

- `/dev/sda1@/EFI/Microsoft/Boot/bootmgfw.efi:Windows Boot Manager:Windows:efi`

If it does, try to do `sudo grub2-mkconfig -o /etc/grub2.cfg`, and grub should add it to your entries, that worked for me.

**Comment by JaCh0o** [comment]
Thank you for your answer. I get no output when I enter sudo os-prober. May I ask for further help?

**Comment by yoyossef** [comment]
Hm, there's your problem then, grub relies on os-probe to seek the Windows EFI partition and add the entry.

Can you identify your Windows EFI partition? I think you can troubleshoot by googling similar problems, but if it's not a setup issue you can still add the entry manually by following the steps in this guide: https://www.fosstools.net/fix-arch-os-prober-not-detecting-windows-how-to

**Comment by JaCh0o** [comment]
Ok my windows 11 pro got bitlocker. I've found out that it probably impossible to set grub to lunch W11 with bitlocker (am I missing something) ? This I s why i didn't seen partition with efi also (to grub couldn't detect it neither). Is there any way to add bitlocker windows to grub ?

And a little OT1:  is there any discord/telegram channel to ask?
OT2: on desktop version of fedora I've revoked Firefox to work in background (there was small box in bottom left after opening every new program asking do I allow this program to work in background - related to kde plasma I guess). Now it always closees immediately after open and I cant find and settings to allow Firefox to work in background and even to manage those settings, can you guide me ?
OT3: if I add contenerised app will service form this app works automatically when it boots to desktop version? I mean rustdesk/anydesk? Will this app be persistent thru bazzite updates?
OT4: is there any way to make RazerGenie working also under gamepad mode ?

**Comment by yoyossef** [comment]
Bitlocker is not a good sign, I would reinstall Windows without it if I were you (or disable it if possible), and yes there is a Discord, there's an invitation link at the end of the Readme.

**Comment by yoyossef** [comment]
I'm not familiar with this Windows stuff, I would just avoid using bitlocker altogether for a simpler setup to be honest

**Comment by JaCh0o** [comment]
Ok for now i see that on my Windows storage (even if i turn off BitLocker, theres only one partition (not EFI), only EFI partition is on storage with Bazzite but even if i point out it as in guide above it donest see mount point for windows...

**Comment by JaCh0o** [comment]
That was my bad. Issue was not gpt but MBR partitioned windows drive. After full W11 reinstall with proper partition it work as it should.
