### ISSUE TITLE
RazerGenie doesn't see keyboard while OpenRazer got it

### ISSUE THREAD

**Issue by JaCh0o** [ublue-os/bazzite#561]
Hello,
I managed to have working RazerGenie and it successfully found out my DeathAdder V2 Pro without any issue. While my keyboard is working correctly but it doesn't shows up in RazerGenie. Under OpenRazer I can find it as compatible what should I do to get this working?
This is about Deathstalker V2 Pro TKL.

And even if I set color in RazerGenie it doesn't stays when I jump back to gamepad mode.

**Comment by KyleGospo** [comment]
Should be fixed thanks to layering in the latest images

**Comment by JaCh0o** [comment]
Was this added ?
And what about two devices thru one dongle ?
