### ISSUE TITLE
Rebase and Updated to F39 from F38

### ISSUE THREAD

**Issue by Blink-Chase** [ublue-os/bazzite#562]
I was updating my steam deck with bazzite fedora 38 to verison 39 using the terminal, everything went fine and installed but as soon as I rebooted the system and was stuck in Emergency Mode. 
(Screenshot below)

![20231119_012846.jpg](https://github.com/ublue-os/bazzite/assets/128920246/6bb619f3-858f-4e90-aa13-f5730b6f9c98)

**Comment by DarkenLX** [comment]
You might want to copy the files it mentions to a usb and post the log content so someone official here could better help you with it as that screenshot doesn't provide much information.

**Comment by noelmiller** [comment]
Due to the lack of activity on this issue, I am going to close this issue. Please reply back with logs to continue troubleshooting if required.
