### ISSUE TITLE
Legion Go Black Screen after Reboot (internal Display)

### ISSUE THREAD

**Issue by Foxlcloud** [ublue-os/bazzite#563]
I tried to install the latest image on my Legion Go. I selected Deck during installation. He also installed everything and I got into the OS too.After I selected everything for the game mode to install and restarted Now the next time I reboot I suddenly only see a black screen (internal Display)and I only hear the sound as if it had gone into the Steamdeck interface. Please  help me for fix it 

If I connect the Legion Go via my monitor then I can see something.

**Comment by M7BAZ** [comment]
Hi.i have a similar issue.can hear operating systems but no screen.did you sort your issue ?

**Comment by KyleGospo** [comment]
Next update should resolve this
