### ISSUE TITLE
[Feature Request] Skip section on portal app

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#564]
Hi would it be possible to a skip button to the bazzite portal? for runs after the initial os setup for reasons mentioned below. Or possibly have the toggles automatically reflect the current setup just because it is kind of tedious to run it to install something additional and have to go through and make sure the toggles are the same as the current setup.. not sure if it will mess up something if it doesn't match.

**Comment by KyleGospo** [comment]
Please open this against https://GitHub.com/ublue-os/yafti
