### ISSUE TITLE
[CRASH]Any game crashes after deck put to sleep

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#566]
Hi this seems to happen in game mode and all games seem affected.. 
What happens? start any game steam acts normal with "launching game" screen.. you get the steam logo after with the B to abort.. then a lit black screen which apparently is some sort of terminal / konsole? because pressing buttons outputs symbols and characters after like 10 seconds screen clears to a frozen  "_" for a split second and the deck bootup screen appears with "verifying installation" this will happen everytime a game is launched unless i restart the deck.  using bazzite-deck:latest
only log i could get is from crashed processes viewer:
           PID: 8839 (gamescope-wl)
           UID: 1000 (deck)
           GID: 1000 (deck)
        Signal: 6 (ABRT)
     Timestamp: Sun 2023-11-19 19:11:24 EST (1min 33s ago)
  Command Line: /usr/bin/gamescope -e --generate-drm-mode fixed --max-scale 2 --xwayland-count 2 -O $'*,eDP-1' --default-touch-mode 4 --hide-cursor-delay 3000 --fade-out-duration 200 -R /run/user/1000/gamescope.51tf8e7/startup.socket -T /run/user/1000/gamescope.51tf8e7/stats.pipe
    Executable: /usr/bin/gamescope
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-gamescope\x2dsession\x2dplus.slice/gamescope-session-plus@steam.service
          Unit: user@1000.service
     User Unit: gamescope-session-plus@steam.service
         Slice: user-1000.slice
     Owner UID: 1000 (deck)
       Boot ID: 375be23ed7d94501a886c3906e2fef91
    Machine ID: cbf11cdcf24f4ed48349dda6e5b59a5c
      Hostname: fedora
       Storage: /var/lib/systemd/coredump/core.gamescope-wl.1000.375be23ed7d94501a886c3906e2fef91.8839.1700439084000000.zst (present)
  Size on Disk: 2.9M
       Package: gamescope/100.0.0.git.699.d5dbbe00-1.fc39
      build-id: 4384c097ee6aaeecb726befbc0b6bb6fa8f84426
       Message: Process 8839 (gamescope-wl) of user 1000 dumped core.
                
                Module libXcursor.so.1 from rpm libXcursor-1.2.1-4.fc39.x86_64
                Module libpipewire-module-session-manager.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libpipewire-module-metadata.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libpipewire-module-adapter.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libpipewire-module-client-device.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libpipewire-module-client-node.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libselinux.so.1 from rpm libselinux-3.5-5.fc39.x86_64
                Module libpipewire-module-protocol-native.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libdbus-1.so.3 from rpm dbus-1.14.10-1.fc39.x86_64
                Module libspa-dbus.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libspa-journal.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libspa-support.so from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libVkLayer_MESA_device_select.so from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libtinfo.so.6 from rpm ncurses-6.4-7.20230520.fc39.x86_64
                Module libedit.so.0 from rpm libedit-3.1-48.20230828cvs.fc39.x86_64
                Module libelf.so.1 from rpm elfutils-0.190-1.fc39.x86_64
                Module libdrm_amdgpu.so.1 from rpm libdrm-2.4.117-1.fc39.x86_64
                Module libvulkan_radeon.so from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libvulkan_panfrost.so from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libvulkan_intel.so from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libvulkan_intel_hasvk.so from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libvulkan_freedreno.so from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libxshmfence.so.1 from rpm libxshmfence-1.3-13.fc39.x86_64
                Module libxcb-sync.so.1 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libX11-xcb.so.1 from rpm libX11-1.8.7-1.fc39.x86_64
                Module libz.so.1 from rpm zlib-1.2.13-4.fc39.x86_64
                Module libvulkan_broadcom.so from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libpcre2-8.so.0 from rpm pcre2-10.42-1.fc39.2.x86_64
                Module libuuid.so.1 from rpm util-linux-2.39.2-1.fc39.x86_64
                Module libzstd.so.1 from rpm zstd-1.5.5-4.fc39.x86_64
                Module liblzma.so.5 from rpm xz-5.4.4-1.fc39.x86_64
                Module liblz4.so.1 from rpm lz4-1.9.4-4.fc39.x86_64
                Module libglib-2.0.so.0 from rpm glib2-2.78.1-1.fc39.x86_64
                Module libgobject-2.0.so.0 from rpm glib2-2.78.1-1.fc39.x86_64
                Module libgudev-1.0.so.0 from rpm libgudev-238-2.fc39.x86_64
                Module libSM.so.6 from rpm libSM-1.2.3-13.fc39.x86_64
                Module libICE.so.6 from rpm libICE-1.0.10-11.fc39.x86_64
                Module libsystemd.so.0 from rpm systemd-254.5-2.fc39.x86_64
                Module libwacom.so.9 from rpm libwacom-2.8.0-1.fc39.x86_64
                Module libevdev.so.2 from rpm libevdev-1.13.1-2.fc39.x86_64
                Module libmtdev.so.1 from rpm mtdev-1.1.6-6.fc39.x86_64
                Module libxcb-randr.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libexpat.so.1 from rpm expat-2.5.0-3.fc39.x86_64
                Module libGLdispatch.so.0 from rpm libglvnd-1.7.0-1.fc39.x86_64
                Module libXau.so.6 from rpm libXau-1.0.11-3.fc39.x86_64
                Module libXt.so.6 from rpm libXt-1.2.1-5.fc39.x86_64
                Module libXi.so.6 from rpm libXi-1.8.1-2.fc39.x86_64
                Module libxcb-res.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libxcb-icccm.so.4 from rpm xcb-util-wm-0.4.2-3.fc39.x86_64
                Module libxcb-composite.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libseat.so.1 from rpm seatd-0.8.0-1.fc39.x86_64
                Module libxcb-xinput.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libxcb-xfixes.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libxcb-shm.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libxcb-render-util.so.0 from rpm xcb-util-renderutil-0.3.10-3.fc39.x86_64
                Module libxcb-render.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libxcb-present.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libxcb-dri3.so.0 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libinput.so.10 from rpm libinput-1.24.0-1.fc39.x86_64
                Module libGLESv2.so.2 from rpm libglvnd-1.7.0-1.fc39.x86_64
                Module libgbm.so.1 from rpm mesa-23.2.1-1.fc39.bazzite.0.0.git.8.5d5a7f11.x86_64
                Module libEGL.so.1 from rpm libglvnd-1.7.0-1.fc39.x86_64
                Module libpixman-1.so.0 from rpm pixman-0.42.2-2.fc39.x86_64
                Module libudev.so.1 from rpm systemd-254.5-2.fc39.x86_64
                Module libxcb.so.1 from rpm libxcb-1.13.1-12.fc39.x86_64
                Module libffi.so.8 from rpm libffi-3.4.4-4.fc39.x86_64
                Module libdisplay-info.so.1 from rpm libdisplay-info-0.1.1-2.fc39.x86_64
                Module libpipewire-0.3.so.0 from rpm pipewire-0.3.84-4.fc39.x86_64
                Module libcap.so.2 from rpm libcap-2.48-7.fc39.x86_64
                Module libXmu.so.6 from rpm libXmu-1.1.4-3.fc39.x86_64
                Module libXtst.so.6 from rpm libXtst-1.2.4-3.fc39.x86_64
                Module libliftoff.so.0 from rpm libliftoff-0.4.1-1.fc39.x86_64
                Module libvulkan.so.1 from rpm vulkan-loader-1.3.250.0-2.fc39.x86_64
                Module libwlroots.so.11 from rpm wlroots-0.16.2-3.fc39.x86_64
                Module libSDL2-2.0.so.0 from rpm SDL2-2.26.5-2.fc39.x86_64
                Module libxkbcommon.so.0 from rpm libxkbcommon-1.6.0-1.fc39.x86_64
                Module libwayland-server.so.0 from rpm wayland-1.22.0-2.fc39.x86_64
                Module libdrm.so.2 from rpm libdrm-2.4.117-1.fc39.x86_64
                Module libXRes.so.1 from rpm libXres-1.2.1-5.fc39.x86_64
                Module libXxf86vm.so.1 from rpm libXxf86vm-1.1.5-3.fc39.x86_64
                Module libXext.so.6 from rpm libXext-1.3.5-3.fc39.x86_64
                Module libXrender.so.1 from rpm libXrender-0.9.11-3.fc39.x86_64
                Module libXcomposite.so.1 from rpm libXcomposite-0.4.5-10.fc39.x86_64
                Module libXfixes.so.3 from rpm libXfixes-6.0.0-6.fc39.x86_64
                Module libXdamage.so.1 from rpm libXdamage-1.1.5-10.fc39.x86_64
                Module libX11.so.6 from rpm libX11-1.8.7-1.fc39.x86_64
                Module libwayland-client.so.0 from rpm wayland-1.22.0-2.fc39.x86_64
                Module gamescope from rpm gamescope-100.0.0.git.699.d5dbbe00-1.fc39.x86_64
                Stack trace of thread 8886:
                #0  0x00007f5327eae834 __pthread_kill_implementation (libc.so.6 + 0x90834)
                #1  0x00007f5327e5c8ee raise (libc.so.6 + 0x3e8ee)
                #2  0x00007f5327e448ff abort (libc.so.6 + 0x268ff)
                #3  0x00007f5327e4481b __assert_fail_base.cold (libc.so.6 + 0x2681b)
                #4  0x00007f5327e54c57 __assert_fail (libc.so.6 + 0x36c57)
                #5  0x0000562d941a859e _ZL24stream_handle_add_bufferPvP9pw_buffer (gamescope + 0x9059e)
                #6  0x00007f5328510f6b impl_port_use_buffers (libpipewire-0.3.so.0 + 0x8af6b)
                #7  0x00007f53285087ea pw_impl_port_use_buffers (libpipewire-0.3.so.0 + 0x827ea)
                #8  0x00007f53247a3305 client_node_port_use_buffers (libpipewire-module-client-node.so + 0x12305)
                #9  0x00007f53247b2c57 client_node_demarshal_port_use_buffers.lto_priv.0 (libpipewire-module-client-node.so + 0x21c57)
                #10 0x00007f5325652001 process_remote (libpipewire-module-protocol-native.so + 0x16001)
                #11 0x00007f53256527e8 on_remote_data (libpipewire-module-protocol-native.so + 0x167e8)
                #12 0x00007f53256e7f16 loop_iterate (libspa-support.so + 0x8f16)
                #13 0x0000562d941a86cf _ZL12run_pipewireP14pipewire_state (gamescope + 0x906cf)
                #14 0x00007f53280e31b3 execute_native_thread_routine (libstdc++.so.6 + 0xe31b3)
                #15 0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #16 0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8839:
                #0  0x00007f5327f25b8d __poll (libc.so.6 + 0x107b8d)
                #1  0x0000562d94180097 _Z12wlserver_runv (gamescope + 0x68097)
                #2  0x0000562d94137be8 main (gamescope + 0x1fbe8)
                #3  0x00007f5327e4614a __libc_start_call_main (libc.so.6 + 0x2814a)
                #4  0x00007f5327e4620b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
                #5  0x0000562d94157515 _start (gamescope + 0x3f515)
                
                Stack trace of thread 8850:
                #0  0x00007f5327ef7163 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xd9163)
                #1  0x00007f5327f099f7 __nanosleep (libc.so.6 + 0xeb9f7)
                #2  0x00007f53236fb5e1 radv_notifier_thread_run (libvulkan_radeon.so + 0xfb5e1)
                #3  0x00007f532384dd8c impl_thrd_routine (libvulkan_radeon.so + 0x24dd8c)
                #4  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #5  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8849:
                #0  0x00007f5327ea9169 __futex_abstimed_wait_common (libc.so.6 + 0x8b169)
                #1  0x00007f5327eabb09 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8db09)
                #2  0x00007f532384de5d cnd_wait (libvulkan_radeon.so + 0x24de5d)
                #3  0x00007f532380e14b util_queue_thread_func (libvulkan_radeon.so + 0x20e14b)
                #4  0x00007f532384dd8c impl_thrd_routine (libvulkan_radeon.so + 0x24dd8c)
                #5  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #6  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8848:
                #0  0x00007f5327f25b8d __poll (libc.so.6 + 0x107b8d)
                #1  0x0000562d94185b2f _Z23flip_handler_thread_runv (gamescope + 0x6db2f)
                #2  0x00007f53280e31b3 execute_native_thread_routine (libstdc++.so.6 + 0xe31b3)
                #3  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #4  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8890:
                #0  0x00007f5327ea9169 __futex_abstimed_wait_common (libc.so.6 + 0x8b169)
                #1  0x00007f5327eabb09 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8db09)
                #2  0x00007f53280dc180 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6 + 0xdc180)
                #3  0x0000562d94160633 _Z19imageWaitThreadMainv (gamescope + 0x48633)
                #4  0x00007f53280e31b3 execute_native_thread_routine (libstdc++.so.6 + 0xe31b3)
                #5  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #6  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8885:
                #0  0x00007f5327f33ac2 epoll_wait (libc.so.6 + 0x115ac2)
                #1  0x00007f53256f5b18 impl_pollfd_wait (libspa-support.so + 0x16b18)
                #2  0x00007f53256e7e59 loop_iterate (libspa-support.so + 0x8e59)
                #3  0x00007f53284cf123 do_loop (libpipewire-0.3.so.0 + 0x49123)
                #4  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #5  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8887:
                #0  0x00007f5327f25b8d __poll (libc.so.6 + 0x107b8d)
                #1  0x0000562d941832e4 _ZL21steamCompMgrThreadRuniPPc.lto_priv.0 (gamescope + 0x6b2e4)
                #2  0x00007f53280e31b3 execute_native_thread_routine (libstdc++.so.6 + 0xe31b3)
                #3  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #4  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8889:
                #0  0x00007f5327ef7163 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xd9163)
                #1  0x00007f5327f099f7 __nanosleep (libc.so.6 + 0xeb9f7)
                #2  0x0000562d94187550 _Z15vblankThreadRunv (gamescope + 0x6f550)
                #3  0x00007f53280e31b3 execute_native_thread_routine (libstdc++.so.6 + 0xe31b3)
                #4  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #5  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                
                Stack trace of thread 8888:
                #0  0x00007f5327f258a5 __open (libc.so.6 + 0x1078a5)
                #1  0x0000562d94159403 _Z15statsThreadMainv (gamescope + 0x41403)
                #2  0x00007f53280e31b3 execute_native_thread_routine (libstdc++.so.6 + 0xe31b3)
                #3  0x00007f5327eac897 start_thread (libc.so.6 + 0x8e897)
                #4  0x00007f5327f336bc __clone3 (libc.so.6 + 0x1156bc)
                ELF object binary architecture: AMD x86-64

**Comment by nadiaholmquist** [comment]
I have this same issue, although on an HTPC (with AMD graphics) rather than a Steam Deck.

Did you ever find a fix?

**Comment by KyleGospo** [comment]
May be fixed in the next release coming this weekend, please let me know if you can still reproduce this.
