### ISSUE TITLE
"Manual GPU Clock Control" is nonfunctional

### ISSUE THREAD

**Issue by jerbmega** [ublue-os/bazzite#57]
On SteamOS, the Manual GPU Clock Control option brings up a slider where the GPU clockspeed can be forced to a specific value with a slider. On Bazzite, enabling this option never shows its respective slider.

**Comment by KyleGospo** [comment]
This may be similar to my comment in #58, or simply a needed karg to allow clock controls. Looking into this. Thanks for the report!

**Comment by KyleGospo** [comment]
If anyone else wants to test this, two things to try:
1: Disable SELinux temporarily with `sudo setenforce 0`, re-enable with `sudo setenforce 1`.
2: Enable advanced clock control in amdgpu with: `rpm-ostree kargs --append="amdgpu.ppfeaturemask=0xffffffff"` followed by rebooting.

**Comment by jerbmega** [comment]
SELinux set to permissive and that karg set doesn't seem to change anything on my end.

**Comment by KyleGospo** [comment]
Fixed as of 1845d8d
