### ISSUE TITLE
The `just` package is unusable as its aliased to `ujust` in the `usr` directory

### ISSUE THREAD

**Issue by manan-gup** [ublue-os/bazzite#576]
Hi, the `just` package provided by rpm-ostree can't be used on its own as its aliased to `ujust` and `ujust` uses the ublue-os version of the justfile.

Contents of `/usr/share/fish/vendor_conf.d/bazzite-just.fish`:
```
alias just='/usr/bin/ujust'
```

Contents of `/usr/bin/ujust`:
```
#!/usr/bin/env bash
/usr/bin/just --unstable --justfile /usr/share/ublue-os/justfile "${@}"
```

So neither can I use the base `just` command or use the file at `$HOME/.justfile` to define custom commands.

Am I missing something or is this a bug?

I'm on `bazzite-gnome:latest` version 39.20231120.0

**Comment by manan-gup** [comment]
This command works though:
`/usr/bin/just --unstable -f ~/.justfile -l`

So, should I just put this in a new alias?

**Comment by bi0shacker001** [comment]
Something tells me you're using an alternative shell, bash is configured to "just work" on that front.
The profile files in /etc/profile.d take care of some extra heavy lifting for bazzite. I use ZSH myself. Adding 
`source /etc/profile.d/*` to .zshrc set the extra variables and aliases bash has been fixing it for me (it's a bit annoying that that's not set by default, but bleh)

**Comment by bi0shacker001** [comment]
Ah, I misunderstood, you're trying to add extra just commands that aren't default.
Yeah, realiasing is pretty much the only option, though that'll break the built-in just commands.

**Comment by manan-gup** [comment]
Oh, I'm using fish, so, this wont be simple for me. 😅
Do the bazzite devs recommend not to use fish as the login shell?

**Comment by manan-gup** [comment]
For anyone having similar issues. you can override stuff in `/usr/share/fish/vendor_conf.d/` in you config at `~/.config/fish/config.fish` as described [here](https://fishshell.com/docs/current/language.html#configuration). I'm leaving this open as I still think the fish config provided by bazzite probably wasn't meant to work like this.

**Comment by manan-gup** [comment]
> Contents of `/usr/share/fish/vendor_conf.d/bazzite-just.fish`:
> 
> ```
> alias just='/usr/bin/ujust'
> ```

No idea, but this is provided by default. Not set by me.

**Comment by nicknamenamenick** [comment]
> why is `just` even aliased when there is `ujust`?

So it works with other shells like fish and zsh.

**Comment by KyleGospo** [comment]
Fixed in next release
