### ISSUE TITLE
Desktop mode crashes

### ISSUE THREAD

**Issue by Dobby36** [ublue-os/bazzite#577]
Anytime I try to do any game modding like DAO or ARMA3 my deck crashes and reboots. I haven't messed with software too much in many years so if memory serves it seems like a memory issue, as recently it is either after I download and install a few mods for arma3 I can get about 3 to 4 installed before it abruptly reboots no crash screen just a second or 2 lag. Also happens when unzipping a zip file contents may not be important but DAO mods from nexus.

**Comment by noelmiller** [comment]
This is issue does not seem related to Bazzite to me. It seems to be an issue with how much memory is available to run DAO or ARMA3 mods or modding tools. 

Due to the lack of activity on this issue, I am going to close this issue.
