### ISSUE TITLE
[Deck] Doesn't install correctly on OLED model.

### ISSUE THREAD

**Issue by JaxiiRuff** [ublue-os/bazzite#578]
I know not everyone has the OLED yet so issues are expected but I figured since its almost the same hardware I might as well try. So far the experience is less than ideal. 

The screen is oriented wrong during install and after install on bootup. So I installed it using a dock but after the initial boot to desktop mode, wifi and sound also became broken on the next startup.

![IMG_20231122_205720674_HDR](https://github.com/ublue-os/bazzite/assets/37735330/f8a2e925-5ce9-448d-a523-5045be7c0440)
![IMG_20231122_205755825_HDR](https://github.com/ublue-os/bazzite/assets/37735330/c5b9ad7f-4638-412a-84f4-b0d6fa10e724)

**Comment by Mitchou** [comment]
Same here :)

**Comment by KyleGospo** [comment]
Now working on the `:testing` branch. Expect a less-than-ideal install experience for the time being as you've already been through.
