### ISSUE TITLE
Bazzite OS + ASUS XG17AHPE incompatibility

### ISSUE THREAD

**Issue by JaCh0o** [ublue-os/bazzite#583]
Hello,
I bought this screen especially for playing on Bazzite SteamOS. Moreover screen works under Windows 11 Pro (currently, i got dual boot) and also it worked on ChimeraOS. 

Issue:
A) HDMI only: Screen shutters every few mouse movements/clicks and/or keyboard presses, later  on evry movement and lastly even without any input.
B) USB-C only: most of times it shows Bazzite pre launch screen logo (with cricle in center bottom) then black screen, sometimes it opens in Desktop Mode with distortions (nevertheless I got Deck & HTPC Version and it shouldn't o to desktop so easily)
C) HDMI & USB-C it depends on what cable is first as primary monitor and behave as above.

Hardware: Miniforum HX99G - Ryzen 9 6900HX (with igpu), Radeon RX6600M, DDR 5 32GB, NVME1 2TB (Bazzite OS Deck & Home Theater PC Edition), NVME2 (Windows 11 Pro)

Screen: ASUS XG17AHPE - 240Hz 17" 1920x1080 portable monitor with speakers. Screen can be connected thru usb-c (as power delivery + video/audio) or thru HDMI (as video/audio) and can work on its own battery for some time or take power from outlet (usb-c) or directly from pc thru second cable.

May i provide any log to solve this asap?

**Comment by JaCh0o** [comment]
![PXL_20231124_183921883](https://github.com/ublue-os/bazzite/assets/93714801/da1a5c94-6707-45f5-930c-6dcc91e151d7)
Here's USB-C output

**Comment by JaCh0o** [comment]
I've also posted this under Bazzite-help on discord (you can check videos from screen shutter (since those are to big to upload here)

**Comment by EyeCantCU** [comment]
This looks more like GPU artifacting to me. Does it work under Bazzite Deck GNOME?

**Comment by JaCh0o** [comment]
May I ask to expand a little ?? Im not an advanced linux user therfore how to check to give you proper output ?

**Comment by EyeCantCU** [comment]
> May I ask to expand a little ?? Im not an advanced linux user therfore how to check to give you proper output ?

Certainly. We offer both GNOME and KDE images. What I'd suggest trying is a fresh install or rebase to the Bazzite Deck GNOME image and seeing if your issue is persistent there. Given you don't have this issue under ChimeraOS (it uses GNOME), it may come down to some bug with the DE and I'd like to eliminate that as a possibility

So all you need to do is open a terminal and copy and paste this:

```
rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
```

Then press enter. This will take a bit. When it completes reboot and check if the issue persists. Or fully reinstall with Bazzite Deck GNOME via the installation media.

**Comment by JaCh0o** [comment]
Sorry for delay. So for now after changing to gnome HDMI issue still persists. Still shuttering checked two different cables and also two different HDMI port, same issue in every option. About usb-c it appears to work under desktop mode properly but it gives black screen in gamepad mode when starting Bazzite. To be honest I don't know how to move from desktop to gamepad mode for further tests. For no i have to turn on on HDMI, then while shuttering go to desktop then unplug HDMI (it shutters also in desktop mode) and plug usb-c then It appears to work properly in desktop mode. No shutter not weird screen issues 1920x1080 240hz. Is there any way to show "go to gamepad mode" shortcut there?

**Comment by JaCh0o** [comment]
Any news here?

**Comment by JaCh0o** [comment]
Is there any chance to get this working in any upcoming version of os ?

**Comment by KyleGospo** [comment]
I'm afraid we don't have this hardware to test against, and we don't change anything about our display stack. I would shop around and see if any Linux distro handles this properly, as that would at least give us something to go on.

**Comment by JaCh0o** [comment]
Yes, used arch in the past Ubuntu official and there are not problem with
it. Issue is related to gamepad mode mainly.

niedz., 24 mar 2024, 19:02 użytkownik Kyle Gospodnetich <
***@***.***> napisał:
