### ISSUE TITLE
Suggestion: Replace Power-Profiles-Daemon with TuneD and TuneD-GTK

### ISSUE THREAD

**Issue by enderpirate98** [ublue-os/bazzite#584]
I keep hearing from the community that TuneD works so much better that P-P-D and for my Dell XPS 15 9510 it seems to work a little bit better so please consider this for Bazzite and maybe even all the other Ublue images. Thanks in advance!

**Comment by EyeCantCU** [comment]
Drafted in a PR for now. Working on gamescope-session integration. Unstable will have it soon as it will need testing

https://github.com/ublue-os/bazzite/pull/587

**Comment by enderpirate98** [comment]
Sweet! Glad it is being considered!

**Comment by KyleGospo** [comment]
Lands this friday!
