### ISSUE TITLE
Bluetooth headphone issues

### ISSUE THREAD

**Issue by AssuredUndead** [ublue-os/bazzite#585]
I'm having issues connecting and using my Bluetooth headset (Sennheiser hd450se).  I use deck-gnome 39 on both my steam deck and htpc. I did not have issues on bazzite 38.  I've tried updating using console with not fix.  On my htpc I can pair my headset only in desktop and use it in gamecope, but  the mic does not work.  I've already tried messing with the audio settings on my htpc looking to see if I just have to select the mic but all that show up are the maltise controller and default.  Both of those do not work.  Even if I plug my headset via 3.5mm jack, the mic does not show up as an option (both on steam deck and htpc).  I'm ordering a new mic to be 100% it is not a hardware issue but the mic works perfect on my phone in both Bluetooth and 3.5mm so the new mic may just be a work around. On my steam deck the headset will not show up at all in gamesscope in Bluetooth settings, even using "show all devices" switch.  In desktop on my steam deck I can see the headset to pair and when I try to pair it, it tries for 2 minutes or so then disappears and does not connect, and does not show up again until I reboot my steam deck and headphones.

**Comment by Zelaf** [comment]
I'm also having this issue, `bluetoothctl` shows authentication errors and connection timeouts. I'm running Bazzite Deck 39 on Steam Deck. The headphones I'm trying to connect are FairBuds XL.

```
# connect 9C:0C:35:60:84:44 
Attempting to connect to 9C:0C:35:60:84:44
[CHG] Device 9C:0C:35:60:84:44 ServicesResolved: yes
Failed to connect: org.bluez.Error.Failed br-connection-timeout
Failed to pair: org.bluez.Error.AuthenticationTimeout
```

**Comment by Bu156** [comment]
I had this issue on Nobara as well, which I am using now. My solution was to, in `bluetoothctl`, unpair, disconnect and remove the device and then directly connect to it. I don't know if `bluez-hid2hci` was required, but the problem didn't go away when I first installed it.

**Comment by AstralPhnx** [comment]
Just throwing my hat into the ring here. Also having issues with getting this going with my bluetooth cans. Sennheiser HD 350BT's. I put them in pairing mode, try to connect my deck to them and it just spins for all eternity. Desktop mode is much of the same and attempts to manually connect using bluetoothctl as mentioned above have ALSO failed. 

I'm kinda at my wits end here and I'm not sure why nothing is working. Other bluetooth devices work fine like controllers, it's just my bluetooth headphones that are not having a bar of it.

I also have a laptop running regular Fedora 39 workstation and my headphones have NO issues connecting to that so it's definitely Bazzite specific
