### ISSUE TITLE
White block on screen - GNOME

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#588]
![Screenshot from 2023-11-28 03-51-16](https://github.com/ublue-os/bazzite/assets/112720004/6c9a4c04-c8ba-4d64-a710-ea53bd2fb337)
![Screenshot from 2023-11-28 03-51-01](https://github.com/ublue-os/bazzite/assets/112720004/f523b4b1-f3d5-4aa0-bba6-7af1bd82f5bb)
![Screenshot from 2023-11-28 03-50-48](https://github.com/ublue-os/bazzite/assets/112720004/438a4285-ace3-4c1f-bfc7-09eee3423a1e)

**Comment by twaananen** [comment]
I have the same after my latest update, the change must have happened in the last 1-2 weeks.

**Comment by KyleGospo** [comment]
Caused by xwaylandbridge, next update should clear this up.

**Comment by EyeCantCU** [comment]
Latest update resolves this
