### ISSUE TITLE
Power button behavior differs from SteamOS

### ISSUE THREAD

**Issue by jerbmega** [ublue-os/bazzite#59]
Not sure how fixable it is, but within a Gamescope session, the sleep animation doesn't play, and instead the Deck immediately sleeps. In and of itself, this isn't a big deal, but it causes the following issues:

* Big Picture's power menu cannot be triggered via the power button.
* When attempting a hard shutdown, the Deck immediately sleeps, then immediately turns on again. If continuing to hold down the power button, a hard shutdown will then work five seconds after the Deck wakes up again (as indicated by the haptic chime).

**Comment by KyleGospo** [comment]
Fixed in https://github.com/ublue-os/bazzite/commit/9969d3ff06f5f58c5e31af912a4284d4cd853859
