### ISSUE TITLE
[CRITICAL] No audio after latest update

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/bazzite#591]
There isn't any audio on the latest update and gamemode often won't load as well

Someone on discord said this

"I updated my Steam Deck with the latest update but the update ended up breaking up my audio. And for some reason, sometimes it  just doesn't let me boot into gamemode at all, leaving me stuck on a black screen. Rebooting it temporarily solves the issue but it still sometimes happens. "

**Comment by goyhen** [comment]
I'm in the same situation.

Plus, in have some unexpected bug to display Betterbird in full screen on the screen of my steam deck.
The screen is setup to be my second screen, with my principal screen being in 1080p.
It try to display Betterbird in maximize size but with a 1080p layout instead of an 800p layout.

**Comment by TrusterX** [comment]
the same here.

if the game scope won't load,, connect a keyboard and press CTRL+C.

it looks like there is something waiting for a confirmation or the like...

**Comment by unicornsandcandies** [comment]
I can't make the audio work in any way. Is there any fix to this? I need my deck to be usable asap.

**Comment by TrusterX** [comment]
ha, got my deck working again
in desktop mode open a cmd and execute
`rpm-ostree upgrade`
took approx 10-15 min to complete,

**Comment by unicornsandcandies** [comment]
> ha, got my deck working again in desktop mode open a cmd and execute `rpm-ostree upgrade` took approx 10-15 min to complete,

Does the audio work for you?

**Comment by TrusterX** [comment]
yeah, audio is working fine now. Also no more troubles loading game scope

**Comment by EyeCantCU** [comment]
This should be resolved in the latest update
