### ISSUE TITLE
[[CRITICAL]] Bazzite Deck Goes to Black Screen on Boot

### ISSUE THREAD

**Issue by MsGoogle-KnownCriminal** [ublue-os/bazzite#593]
As per title, steam deck is booting to black screen. This is a continuation of a prior issue. The proposed solution was to run
```rpm-ostree upgrade```

I did so at the time however at this time it is again not booting in spite of no other actions taken on my part.

**Comment by mjpaden** [comment]
According to @EyeCantCU this is fixed in the latest build, so if you upgrade to :latest it ought to be fine.

If you're still having issues, what worked for me (prior to the build fix) was:

1. press CTRL-ALT-F2 to bring up a terminal
2. enter `steamos-session-select plasma`
3. You may need to do a CTRL-ALT-F1 to get back to the initial session.
4. Hit "Return to Game Mode".

This prevented it from happening on subsequent restarts for me. Let us know what worked!

**Comment by beefchimi** [comment]
I am having this issue _(blank black screen)_ if logging into a `Wayland` session on `Nvidia` _(the latest updates added the newest `Nvidia` driver)_. `X11` appears to be fine however.

**Comment by MsGoogle-KnownCriminal** [comment]
> According to @EyeCantCU this is fixed in the latest build, so if you upgrade to :latest it ought to be fine.
> 
> If you're still having issues, what worked for me (prior to the build fix) was:
> 
> 1. press CTRL-ALT-F2 to bring up a terminal
> 2. enter `steamos-session-select plasma`
> 3. You may need to do a CTRL-ALT-F1 to get back to the initial session.
> 4. Hit "Return to Game Mode".
> 
> This prevented it from happening on subsequent restarts for me. Let us know what worked! (If either does!)

I tried since it just happened again (it hadn't happened at all in the intervening month), and got hit with a login screen which didn't respond to the credentials I remember setting up

**Comment by Viktini** [comment]
This also occurs if you run Bazzite in a VMware virtual machine if you don't enable GPU acceleration. Thought I'd share even if the issue is closed.

**Comment by styromaniac** [comment]
I'm aware that this is in development for OLED models, but I'm wondering how to get around this.

**Comment by Saroufim** [comment]
HDR now works for me but 3D acceleration doesn't. Stardew Valley runs at 30 fps (down from 60+ fps) and no proton games launch. They all complain about missing DirectX drivers. If I switch to GNOME, everything works fine. This is exactly what happened right before HDR stopped working.

**Comment by c4v3m2n** [comment]
This just happened to me. I got to the terminal with ctrl+alt+f2

Entered rpm-ostree upgrade and we’ll see what happens, it’s fetching super slowly…

It also says I have 12 chunks present but need 61 chunks(5gb)
