### ISSUE TITLE
Just command has "brew-remove" but no "brew"

### ISSUE THREAD

**Issue by Nitrousoxide** [ublue-os/bazzite#594]
The justfile has brew-remove but no brew.  There is a `just distrobox-brew` command but this create a container with brew installed but does not export the command to the host meaning you cannot run it without first dipping into the container.

You should either remove the "brew-remove" just command as it is unnecessary, alter the distrobox-brew command to export the binary to the host so you can install without directly dipping in there, or add the `just brew` command so it can be installed normally.

**Comment by castrojo** [comment]
https://universal-blue.discourse.group/t/heads-up-change-on-the-homebrew-setup/157 for more info!
