### ISSUE TITLE
The PowerTools Decky Loader plugin is nonfunctional.

### ISSUE THREAD

**Issue by jerbmega** [ublue-os/bazzite#60]
Not sure how fixable it is, but no options have any effect at all. May be related to #57?

**Comment by KyleGospo** [comment]
This should be universal, it's used by various other handhelds for hardware controls. You may try disabling SELinux with `sudo setenforce 0` to test if this begins working as expected.

**Comment by jerbmega** [comment]
No change, at least according to MangoHUD. The karg in #57 also had no effect.

**Comment by KyleGospo** [comment]
Powertools should be creating a log at `/tmp/powertools.log`, can you provide that?

**Comment by jerbmega** [comment]
https://paste.rs/NOc0O
Main thing I tried was changing the GPU clock speed (as a workaround for the BPM toggle not working right now). It looks like it's expecting the GPU to be present under card0, but on Bazzite it shows up as card1. For what it's worth, that matches the behavior on my custom Universal Blue image on my desktop with an RDNA2 graphics card as well. The battery errors are similar, expecting a device to show up with a specific hwmon number, but Bazzite's values don't match SteamOS here.

These settings appear to be hardcoded within PowerTools source code at https://github.com/NGnius/PowerTools/tree/main/backend/src/settings/steam_deck. I think this line of the log is particularly notable: `02:17:07 [INFO] Detected device automatically, starting with driver: SteamDeck (This can be overriden)`

Maybe setting this to a generic driver would be good enough?

**Comment by KyleGospo** [comment]
Very strange that they use hardcoded hwmon paths. I'll try messaging Ngnius and see if we can get some direction here.

**Comment by NGnius** [comment]
For now it would be best to use a different device driver. These can be forced by editing the game config you want changed in `~/.config/powertools` (options are `steam-deck`, `generic`, `generic-amd`, `unknown`, `gabe-boy`). The underlying issue is that PowerTools has hard coded paths since it expects everyone on Steam Deck to be using SteamOS.

**Comment by EyeCantCU** [comment]
Every option I've tested seems to have some effect (monitored in mangohud), but there are errors thrown for a couple toggles

https://paste.centos.org/view/3a861d0b

**Comment by NGnius** [comment]
Changing the driver should simply hide the UI elements that won't work. The only alarming error that I see in that log is that the battery current limit can't be set correctly by the steam deck driver, which is consistent with the rest of this issue.

**Comment by KyleGospo** [comment]
Steam Deck's vpower service is ported now which throws some battery data in /run.

That should put us at absolute feature parity with the only issue being the differing hwmon paths, which should change often here.

**Comment by aarron-lee** [comment]
> This should be universal, it's used by various other handhelds for hardware controls.

As far as I know, PowerTools has never been functional on other hardware and distros. You might be mixing up PowerTools with [PowerControl](https://github.com/oliverchang/PowerControl)

For ChimeraOS, HoloISO, etc, PowerControl has been the plugin to use on alternative hardware. Unfortunately, it's not available in the Decky store so it has to be manually installed.

**Comment by NGnius** [comment]
PowerTools does have limited support for other handhelds, but since I only own a Steam Deck that's got the best support. The rest is mostly accomplished by me blindly changing things and crossing my fingers, and the occasional contribution from others. I try not to buy unnecessary electronics since they're expensive and bad for the environment, but occasionally fun overrides my good judgement.
