### ISSUE TITLE
Xbox One Controller Not Recognized by Steam But Works Everywhere Else in Bazzite

### ISSUE THREAD

**Issue by crash101g** [ublue-os/bazzite#602]
Xbox one controller is able to successfully bluetooth pair with Bazzite/Fedora and works without any issues with other gaming apps like Yuzu within Bazzite, but Steam does not recognize the Xbox one controller.  I've tried flashing the Xbox one controller to the latest firmware, but Steam does not recognize the Xbox One controller.  I've tried connecting the Xbox One controller via tethered cable to Bazzite, but Steam does not recognize the controller.  If I place a different SSD running a different operating system (e.g. ChimeraOS), then everything works (including Steam).  I don't have any issues with the XBox controller working on other computers or the Xbox one console.  There must be some kind of Steam or Bazzite setting/configuration somewhere that I cannot figure out.  Will gladly post any requested logs and perform any additional troubleshooting.

**Comment by atonal440** [comment]
I have a similar problem with a xbox-compatible controller (8bitdo pro 2) where steam sees the controller is connected but no input is sent. I can see input events in the kde controller settings window, but steam isn't receiving them.

**Comment by marcopq** [comment]
Same happen to me in bottles. Using cable it works.

**Comment by HikariKnight** [comment]
@atonal440 @marcoceppi @crash101g 
open terminal and type `ujust use-stock-gamepads` and see if it works after a reboot once you have run that command

**Comment by crash101g** [comment]
@HikariKnight just tried running ujust use-stock-gamepads at the Konsole and rebooted but does not seem to work for me.  Any other suggestions or logs you may need?

**Comment by HikariKnight** [comment]
@crash101g not sure as i was just going after what has been the most common solution so far with some of these controllers

**Comment by crash101g** [comment]
After many hours I figured out as a not so great work-around involving starting Steam, unplugging my USB bluetooth adapter while in Steam, and re-inserting my USB bluetooth dongle.  This temp workaround only works until I exit out of the current session of steam app and must do it all over again if I restart steam.

Other observations:
  -I'm running Bazzite Fedora on an older Dell Optiplex that does not have built-in integrated bluetooth so I have to use a USB-based bluetooth (BT) adapter.  I use the older Dell Optiplex and USB-BT with various other operating systems (windows and linux) with no problems.
  -Bazzite Fedora and other operating systems (like ChimeraOS when I swap out the SSD but still on the same hardware) is able to recognize the xbox controller at the OS level without any noticeable problems.
  -Yuzu Switch Emulator on Bazzite has no issues recognizing the xbox controller or playing various switch emulated games.
  -Steam sees my xbox one controller as xbox 360, but the "test input devices" does not see the controller so it really does not  work in Steam.
  -While in steam if I physically unplug the USB Bluetooth adapter and plug it back it, then steam recognizes the xbox controller and the "test input devices" works as well as the ability to play steam games or to navigate around with the xbox controller in big picture mode.
  -If I exit steam and restart steam, then it doesn't work unless I physically unplug and plug back in the USB-BT adapter.
  -On other operating systems (Windows and various linux distros), I have no problem using the USB bluetooth adapter and no issues with steam so the problems lies somewhere with Bazzite, Steam, and using USB BT dongle.  Note:  I've tried a different USB BT 4.0 dongle and have the same problem/workaround in Bazzite.  For reference in case you want to know my USB-BT adapters are a TP-Link UB500 using rtl8761 chipset and the other one is a broadcom BCM20702A

Would still like to continue working with anyone that may have any insight on how to get my xbox controller working in Bazzite without physically unplugging and plugging back in the USB-BT adapter.

**Comment by HikariKnight** [comment]
Thats weird, i am not having this issue with any of my bluetooth dongles. out of curiosity can you check which dongle it is with the `lsusb` command?
here is mine
`ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)`
my other one is `ID 0bda:8771 Realtek Semiconductor Corp. [unknown]` the unknown part is there because of a bug in the kernel atm that gives some usb devices the wrong names...

**Comment by crash101g** [comment]
@HikariKnight  yeah - you have my BT dongle IDs listed above but I'll paste it again here.  I tried it a few more times with both BT dongles and did more testing to confirm this is reproducible every time for me.

- Bus 001 Device 003: ID 2357:0604 TP-Link [unknown]

and on the same PC using  a different USB BT dongle with the same issue

- Bus 001 Device 005: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0

The lsusb output is the same in Bazzite and in ChimeraOS (with the small exception of Bazzite showing [unknown] due to that bug you mentioned.  I do not have any problems with Steam recognizing and immediately working with my xbox wireless controller on ChimeraOS on the same PC-hardware.  In Bazzite, Steam will not work with my xbox wireless controller unless I do the weird newly discovered workaround (start steam > either use the BT system tray to disconnect/reconnect the xbox controller or run at the terminal "sudo systemctl restart bluetooth".  This issue with Bazzite is only with Steam so far as I have no issues with other apps like Yuzu (switch emulator) on Bazzite immediately working with my xbox controller.

It's the same Steam client version my setup in both Bazzite and ChimeraOS:
Steam Version:  1702079146
Steam Client Build Date:  Thu, Dec 7 6:33 PM UTC -08:00
Steam Web Build Date:  Fri, Dec 8 5:30 PM UTC -08:00
Steam API Version:  SteamClient021

I'll gladly work with anyone with any suggestions or provide any further details, logs, or suggestions.

**Comment by gashoneil** [comment]
> @HikariKnight yeah - you have my BT dongle IDs listed above but I'll paste it again here. I tried it a few more times with both BT dongles and did more testing to confirm this is reproducible every time for me.
> 
> * Bus 001 Device 003: ID 2357:0604 TP-Link [unknown]
> 
> and on the same PC using a different USB BT dongle with the same issue
> 
> * Bus 001 Device 005: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0
> 
> The lsusb output is the same in Bazzite and in ChimeraOS (with the small exception of Bazzite showing [unknown] due to that bug you mentioned. I do not have any problems with Steam recognizing and immediately working with my xbox wireless controller on ChimeraOS on the same PC-hardware. In Bazzite, Steam will not work with my xbox wireless controller unless I do the weird newly discovered workaround (start steam > either use the BT system tray to disconnect/reconnect the xbox controller or run at the terminal "sudo systemctl restart bluetooth". This issue with Bazzite is only with Steam so far as I have no issues with other apps like Yuzu (switch emulator) on Bazzite immediately working with my xbox controller.
> 
> It's the same Steam client version my setup in both Bazzite and ChimeraOS: Steam Version: 1702079146 Steam Client Build Date: Thu, Dec 7 6:33 PM UTC -08:00 Steam Web Build Date: Fri, Dec 8 5:30 PM UTC -08:00 Steam API Version: SteamClient021
> 
> I'll gladly work with anyone with any suggestions or provide any further details, logs, testing.

I can't help, but I am getting the exact same issue using an Xbox One S controller on the latest Bazzite and xpadneo driver.  The controller pairs, shows up in the Game Controllers panel and seems to work.  Steam sees it as a 360 pad but with no input.  My laptop has built in Bluetooth, its an Dell XPS 2 in One 9310.  Your workaround doesn't seem to work, the pad re-pairs but no input.

**Comment by gashoneil** [comment]
> > @HikariKnight yeah - you have my BT dongle IDs listed above but I'll paste it again here. I tried it a few more times with both BT dongles and did more testing to confirm this is reproducible every time for me.
> > 
> > * Bus 001 Device 003: ID 2357:0604 TP-Link [unknown]
> > 
> > and on the same PC using a different USB BT dongle with the same issue
> > 
> > * Bus 001 Device 005: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0
> > 
> > The lsusb output is the same in Bazzite and in ChimeraOS (with the small exception of Bazzite showing [unknown] due to that bug you mentioned. I do not have any problems with Steam recognizing and immediately working with my xbox wireless controller on ChimeraOS on the same PC-hardware. In Bazzite, Steam will not work with my xbox wireless controller unless I do the weird newly discovered workaround (start steam > either use the BT system tray to disconnect/reconnect the xbox controller or run at the terminal "sudo systemctl restart bluetooth". This issue with Bazzite is only with Steam so far as I have no issues with other apps like Yuzu (switch emulator) on Bazzite immediately working with my xbox controller.
> > It's the same Steam client version my setup in both Bazzite and ChimeraOS: Steam Version: 1702079146 Steam Client Build Date: Thu, Dec 7 6:33 PM UTC -08:00 Steam Web Build Date: Fri, Dec 8 5:30 PM UTC -08:00 Steam API Version: SteamClient021
> > I'll gladly work with anyone with any suggestions or provide any further details, logs, testing.
> 
> I can't help, but I am getting the exact same issue using an Xbox One S controller on the latest Bazzite and xpadneo driver. The controller pairs, shows up in the Game Controllers panel and seems to work. Steam sees it as a 360 pad but with no input. My laptop has built in Bluetooth, its an Dell XPS 2 in One 9310. Your workaround doesn't seem to work, the pad re-pairs but no input.
> 
> Bus 001 Device 002: ID 0bda:58f4 Realtek Semiconductor Corp. [unknown]

I just noticed in Game Controllers there are two entries -

Xbox Wireless Controller (/dev/input/js0)
Microsoft X-Box 360 pad 0 (/dev/input/js1)

I am not sure if this is normal behaviour, there are two entries created in /dev/input when the controller pairs

**Comment by gashoneil** [comment]
> > @HikariKnight yeah - you have my BT dongle IDs listed above but I'll paste it again here. I tried it a few more times with both BT dongles and did more testing to confirm this is reproducible every time for me.
> > 
> > * Bus 001 Device 003: ID 2357:0604 TP-Link [unknown]
> > 
> > and on the same PC using a different USB BT dongle with the same issue
> > 
> > * Bus 001 Device 005: ID 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0
> > 
> > The lsusb output is the same in Bazzite and in ChimeraOS (with the small exception of Bazzite showing [unknown] due to that bug you mentioned. I do not have any problems with Steam recognizing and immediately working with my xbox wireless controller on ChimeraOS on the same PC-hardware. In Bazzite, Steam will not work with my xbox wireless controller unless I do the weird newly discovered workaround (start steam > either use the BT system tray to disconnect/reconnect the xbox controller or run at the terminal "sudo systemctl restart bluetooth". This issue with Bazzite is only with Steam so far as I have no issues with other apps like Yuzu (switch emulator) on Bazzite immediately working with my xbox controller.
> > It's the same Steam client version my setup in both Bazzite and ChimeraOS: Steam Version: 1702079146 Steam Client Build Date: Thu, Dec 7 6:33 PM UTC -08:00 Steam Web Build Date: Fri, Dec 8 5:30 PM UTC -08:00 Steam API Version: SteamClient021
> > I'll gladly work with anyone with any suggestions or provide any further details, logs, testing.
> 
> I can't help, but I am getting the exact same issue using an Xbox One S controller on the latest Bazzite and xpadneo driver. The controller pairs, shows up in the Game Controllers panel and seems to work. Steam sees it as a 360 pad but with no input. My laptop has built in Bluetooth, its an Dell XPS 2 in One 9310. Your workaround doesn't seem to work, the pad re-pairs but no input.
> 
> Bus 001 Device 002: ID 0bda:58f4 Realtek Semiconductor Corp. [unknown]

I just noticed in Game Controllers there are two entries -

Xbox Wireless Controller (/dev/input/js0)
Microsoft X-Box 360 pad 0 (/dev/input/js1)

I am not sure if this is normal behaviour, there are two entries created in /dev/input when the controller pairs

**Comment by crash101g** [comment]
I just looked at my Game Controller after you posted about js0 and js1.  This is what I see:

**Under game controllers (before starting steam):**
Xbox Wireless Controller (/dev/input/js0)

**Under game controllers (after starting steam - but controller isn't working in steam):**
Xbox Wireless Controller (/dev/input/js0)
Microsoft X-Box 360 pad 0 (/dev/input/js1)

**Under game controllers (after starting steam - and restarting bluetooth service so the xbox controller works with steam):**
Xbox Wireless Controller (/dev/input/js0)
Microsoft X-Box 360 pad 0 (/dev/input/js1)
extest fake device (/dev/input/js2)

Maybe these are hints to someone that knows what's going on for a better working fix.

**Comment by crash101g** [comment]
I just spent many countless hours testing different installs of Bazzite, Fedora Workstation 39, and Fedora Kinoite 39 on different PC hardware I have.  Here are my observations:

**New fresh installs of Bazzite with KDE and again with Gnome as the DE on different PC hardware**
-Created ISO from:  https://github.com/ublue-os/bazzite/releases/download/v2.1.0/bazzite-39-x86_64-20231213.iso
-Bazzite has no issues BT pairing with the wireless xbox controller at the OS level but Steam has issues seeing it.
-Must run:
-At the terminal "ujust use-stock-gamepads" + reboot  (if I don't run this command then Steam never sees controller)
-Start Steam > "sudo systemctl restart bluetooth" (with Steam running in background) in order for Steam to properly see/use the wireless xbox controller (note:  steams sees the controller as xbox 360)

**New fresh Fedora Workstation 39 on various different systems**
-Created ISO from:  https://download.fedoraproject.org/pub/fedora/linux/releases/39/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-39-1.5.iso
-BT pair wireless xbox controller
-Install Steam via flatpak
-Xbox wireless controller immediately recognized/works in Steam and is identified as "Xbox One S Controller""

**Fedora Kinoite 39 on the Original system**
-Created ISO from https://github.com/ublue-os/main/releases/download/v2.0.0/universalblue-39-x86_64-20231108.iso
-BT pair wireless xbox controller
-Install Steam via flatpak
-Xbox wireless controller immediately recognized/works in Steam as #controller_xboxone or "Xbox One S Controller"

Whatever issue my various PC systems and xbox controller I have is specifically related to Bazzite as I don't have any issues using my Xbox wireless controller in Steam on Fedora Workstation 39 or Fedora Kinoite 39.  Will gladly post any logs or try anything else for a better fix.

**Comment by nobodywatchin** [comment]
Having a similar issue, other controllers like a wired 360 controller work after `ujust use-stock-gamepads` but the wireless xbox one controller is not detected by steam

**Comment by nobodywatchin** [comment]
Update:
After `ujust use-stock-gamepads` I still couldn't get it to work with steam, I ended up updating the firmware of the controller through windows.
After that, the controller works perfectly and it is detected as an xbox 360 controller

**Comment by Ci7rix** [comment]
I had the same issue using an Xbox One controller. Turns out I was using secure boot and the key wasn't enrolled. Had to `ujust enroll-secure-boot-key`, after rebooting, the controller is working fine.

**Comment by nergdron** [comment]
AHA! this is what's been messing up all my controllers! I use an XBox One gamepad, which wouldn't even pair after switching from stock to bazzite, and a DS5, which wouldn't do trackpad mouse controls. after doing `ujust use-stock-gamepads`, they both work properly again. not sure what stuff you're doing under the hood that breaks every gamepad I own, but I'd definitely suggest making stock gamepad support the default, as it works way better.

**Comment by HikariKnight** [comment]
> AHA! this is what's been messing up all my controllers! I use an XBox One gamepad, which wouldn't even pair after switching from stock to bazzite, and a DS5, which wouldn't do trackpad mouse controls. after doing `ujust use-stock-gamepads`, they both work properly again. not sure what stuff you're doing under the hood that breaks every gamepad I own, but I'd definitely suggest making stock gamepad support the default, as it works way better.

stock is going to be the default with the update next week :)
Also for reference to anyone coming here later, the command has been updated to `ujust configure-gamepads` as of friday
The option you want is `Default Fedora drivers`

or you can just do `ujust configure-gamepads stock`

**Comment by justgeig** [comment]
> I don't have `ujust use-stock-gamepads` anymore nor do I have `ujust configure-gamepads` (and controller support is broken again for me)

Same here on the desktop image. Why is that recipe gone now after the most recent update? I want to love Bazzite so much, but I can't use my controllers right now.

**Comment by HikariKnight** [comment]
> > I don't have `ujust use-stock-gamepads` anymore nor do I have `ujust configure-gamepads` (and controller support is broken again for me)
> 
> Same here on the desktop image. Why is that recipe gone now after the most recent update? I want to love Bazzite so much, but I can't use my controllers right now.

i believe it was removed because the drivers got changed out with one that shouldnt cause that issue. maybe @KyleGospo knows something we can try since i dont think doing what those commands did will fix the issue now.

**Comment by crash101g** [comment]
I can actually say good things must have made it to some of the recent updates in the past week.  At least for me, after running "sudo rpm-ostree upgrade" and rebooting that my xbox controller now finally works in Steam and without any work-arounds.  I'm also seeing that my controller is now properly identified in Steam as "Xbox One S Controller" instead of "xbox 360".  

If it makes a difference, the lsusb output on my system with my BT dongle now shows "TP-Link UB500 Adapter" instead of the previous "TP-Link [unknown]".

Maybe for others  try checking to ensure the firmware on your xbox controller is running the latest.  I could not find an easy way of doing it in Linux, but it is easy to do this in Windows via "Xbox Accessories app" or on an Xbox game console.

Thanks to everyone for whatever updates or changes were made into Bazzite!!!

**Comment by justgeig** [comment]
> > I don't have `ujust use-stock-gamepads` anymore nor do I have `ujust configure-gamepads` (and controller support is broken again for me)
> 
> Same here on the desktop image. Why is that recipe gone now after the most recent update? I want to love Bazzite so much, but I can't use my controllers right now.

Issue seems to be resolved for me now.
I ran ujust upgrade again even though I just had done so and it pulled in more updates. Back to loving Bazzite lol Thanks to all the devs, I love the whole idea of Bazzite and what it stands for

**Comment by underwoo16** [comment]
Adding another data point that this is also working for me now after recent updates, using an Xbox Elite Wireless controller. Thanks for the fix whatever it was!

**Comment by HikariKnight** [comment]
Starting to think people were just on older images and did not have the newer modules 😅

**Comment by KyleGospo** [comment]
Appreciate the feedback everyone! If you're on the latest version and having issues do let us know so we can dig deeper.

**Comment by xkhoax** [comment]
Why this happens:

Bazzite (and Linux in general) stores Bluetooth pairing info under /var/lib/bluetooth. If a previous pairing with the controller failed or broke, the system may silently ignore that device instead of showing it again in the scan. The GUI doesn’t show any error, it just “doesn’t see” the controller.

What fixed it for me:

Turn Bluetooth OFF

Delete the old controller data (this part uses the terminal)

Open a terminal

First, list what’s inside /var/lib/bluetooth:

**sudo ls /var/lib/bluetooth**

You should see a folder that looks like your controller MAC address, for example:

54:8D:5A:D8:1B:BF

That folder is the stored data for your controller. Remove it:

**sudo rm -rf /var/lib/bluetooth/54:8D:5A:D8:1B:BF**

(Replace 54:8D:5A:D8:1B:BF with whatever folder name you actually see.)

Turn On Bluetooth and Scan again.
