### ISSUE TITLE
Hanabi broken on Wayland

### ISSUE THREAD

**Issue by shuja-u** [ublue-os/bazzite#606]
Latest update broke Hanabi on Wayland for me. Rolling back with rpm-ostree makes it fully functional again. It also works fine on X11 on the latest update.

Here's what it looked like before the update:
![Screenshot from 2023-12-05 22-24-19](https://github.com/ublue-os/bazzite/assets/64989755/e5aeba58-5396-45a6-814f-c49e1de84fd9)

Here's what it looks like after the update:
![Screenshot from 2023-12-05 22-24-46](https://github.com/ublue-os/bazzite/assets/64989755/94f050d3-53dd-43fe-8a9f-0d0f069891ba)

I've tested with other videos and the issue persists.

**Comment by KyleGospo** [comment]
This may be fixed now, if you still see issues please be sure to report it upstream.
