### ISSUE TITLE
Black screen when using Steam Link in desktop mode

### ISSUE THREAD

**Issue by Gethec** [ublue-os/bazzite#607]
I've encountered an issue with Steam Link as of a few weeks ago.  When I connect to the Deck while in handheld mode, it works perfectly.  When, however, I connect while in desktop mode, all that is rendered on the client device is a black screen.  Mouse and keyboard commands are still sent, but I only ever get a black screen.

I've tested to see if this is a configuration issue by reformatting the Deck and installing fresh Bazzite, as well as completely removing and reinstalling Steam Link on my client device, but have the same problem.  I've also adjusted HEVC, hardware decoding, etc. to see if those play a factor, but get the same results.  Finally, I reverted to the stock SteamOS image and confirmed that Steam Link works as expected.  Is anyone else experiencing this issue?

**Comment by goncalossilva** [comment]
Same issue here. The server is Bazitte running on a desktop machine, the client is a Steam Deck running Steam OS. I haven't tried configuration changes yet.

**Comment by mpetuska** [comment]
I've been having same issues with any steam client even before steam deck came out. Most likely it's due to wayland compositor being used, try switching to x11 desktop session. Also once you launch a game in bazzite, your steam deck client should no longer be black.

**Comment by ULilBagel** [comment]
I believe steam requires the -pipewire-dmabuf flag to be passed for Wayland sharing support. This is how GE does it for Nobara. He doesn't put it as a default, but he added a shortcut that relaunches steam with that argument for the specific purpose of steam remote play.

**Comment by mpetuska** [comment]
https://nobaraproject.org/docs/steamdeck-edition/adjusting-steamdeck-edition-for-streaming-to-other-devices/
