### ISSUE TITLE
Would it be possible to revert to Nvidia driver version 535?

### ISSUE THREAD

**Issue by KaiserCalm** [ublue-os/bazzite#608]
The latest nvidia driver update has made gaming on Wayland a complete [nightmare](https://forums.developer.nvidia.com/t/545-29-02-ghosting-artifacting-stuttering-on-fullscreen-when-below-monitor-framerate/271853). Is it possible to revert the to the older driver version for the time being?

**Comment by nobodywatchin** [comment]
I'm also having a similar issue, the new update is making games flicker like crazy, can't figure out a fix

**Comment by HikariKnight** [comment]
rpmfusion sadly removed the 535 driver which makes it problematic to make a 535 image since it is no longer available

**Comment by EyeCantCU** [comment]
When RPM Fusion drops an NVIDIA driver release, we no longer produce images with it. Unfortunately, the only way to get the older release would be to rebase to an older Bazzite image which I highly recommend against
