### ISSUE TITLE
Enabling LUKS encryption in the Deck installer causes first boot to fail

### ISSUE THREAD

**Issue by audreytoskin** [ublue-os/bazzite#609]
Attempting to install:

- Bazzite/Fedora 39, image v2.0.2 (2023-11-08),
- selecting either the plain Deck or the Deck-GNOME variants,
- onto my Steam Deck (LCD) 512-GB model,
- and choosing auto storage formatting, the default partitioning,
- but also clicking the check box to enable LUKS encryption...

The installer runs without any apparent errors, it reports successful completion, but then first the first boot fails. It hangs at the Plymouth decryption password prompt, and doesn't respond to any key inputs.

Getting more detailed boot logs is difficult when it never actually finishes booting, but I'm guessing the first-time initramfs generation and LUKS decryption are interfering with each other somehow. Let me know if there's any other information I can get for you.

**Comment by KyleGospo** [comment]
Thank you for the report, I'll be looking into this more once we've finished integrating unl0kr.

**Comment by SMNFXCN** [comment]
This still might be an issue on Bazzite in general?
I've tried it on my gaming laptop, bazzite-gnome-nvidia and after typing in the LUKS password it's just stuck at the spinning logo. I would try to wait it out however it's been almost ~20 minutes on an M.2 drive.

**Comment by audreytoskin** [comment]
Depending on how complicated implementing unl0kr support is, perhaps a simpler workaround in the meanwhile would be to just... let Bazzite Deck users plug in a USB keyboard to boot and decrypt, if they decide to enable LUKS in the Bazzite installer.

Setting up LUKS with a key file on a USB drive, or using a YubiKey, could be another way to do keyboardless boot of encrypted systems --- though I dunno if the Anaconda installer menus have a way of configuring that.
