### ISSUE TITLE
After "fleek init" konsole opens to /var/home/ prompt.?

### ISSUE THREAD

**Issue by DarkenLX** [ublue-os/bazzite#610]
Hi for some reason after running "fleek init" (ublue-update kept erroring out saying i had to run that.)
Anytime Konsole now opens it has (i just used deck for a user name.) In title bar deck:bash and in the window:
/var/home/deck
> _

Is this normal?
I thought it was supposed to be something like "user@fedora:" or similar... I feel like something got mucked with one of the .bash files in home but i have not touched them.. though i can still run commands normally it seems weird.
Pic of what I am seeing
![P_20231211_173121](https://github.com/ublue-os/bazzite/assets/8977130/ea99fd4d-265d-4033-8abc-89a4f476955c)

**Comment by m2Giles** [comment]
That's the starship prompt.
