### ISSUE TITLE
apps with elevated privileges don't use dark theme in kde plasma

### ISSUE THREAD

**Issue by Renner0E** [ublue-os/bazzite#614]
Apps like gparted, timeshift, btrfs-assistant use the light theme if the dark theme (as your regular user) is configured in systemsettings.

![plasma_dark_no_fix](https://github.com/ublue-os/bazzite/assets/80410025/35ad4578-26ff-40b8-aa40-b14569787744)

To fix it for apps with elevated privileges run this command:

`$ sudo pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true dbus-launch systemsettings5`

Fix elevated GTK2/3 apps:
Then open the newly opened system settings and choose the breeze dark theme in quick settings.
Go to appearance > application style > configure GNOME/GTK Application Style and select breeze > apply

If you leave it at the Default/Adwaita Theme/greyed out gparted will still be light mode and have broken icons.

Fix icons:
appearance > icons > breeze dark > apply

Reopen your affected applications

![plasma_dark_fix](https://github.com/ublue-os/bazzite/assets/80410025/951aff20-f73e-4c0e-8eea-21b05e6f7780)

alternatively you could _probably_ run these commands but I don't know for certain if this works.
```
sudo cp -r .config/kde* /root/.config
sudo cp -r .config/gtk* /root/.config
```

Is someone interested in a just command or something for this?
This is not bazzite/fedora specific but Just wanted to share maybe it helps someone.
Feel free to close.

**Comment by spaceguybob** [comment]
This is not an issue exclusive to bazzite, and in most cases it's intentional to tell elevated apps from non elevated apps. You're not supposed to run GUI apps under elevated privileges

**Comment by EyeCantCU** [comment]
This is intentional behavior. However, if you'd like to document this process we have a Discourse [here](https://universal-blue.discourse.group/)
