### ISSUE TITLE
Update Channel switched/bugged?

### ISSUE THREAD

**Issue by 0lm** [ublue-os/bazzite#616]
Hi

Somehow, I get more updates on bazzite than on the normal SteamOS 3.5. I also have Dock Firmware Update on Brazzit, while I don't have any on SteamOS 3.5. (I can test this, because a friend also has Steam Deck, he has SteamOS, I have Bazzite installed).

All Channels are set to "Stable" for me, but it feels like I also get Preview/Beta updates. I did not pay attention to this until now. But when I suddenly got a Dock Firmware update notification, that made me suspicious. (since dock firmware updates are really rare) - this is about the original Steam deck Dock btw.

Just wanted to tell this. maybe something went wrong/mixed.

**Comment by KyleGospo** [comment]
More updates to be expected, the updater updates the operating system as well when we push updates far more often than valve does.
