### ISSUE TITLE
Bazzite-deck-gnome MangoHUD not working in game mode.

### ISSUE THREAD

**Issue by KaiserCalm** [ublue-os/bazzite#617]
I noticed that enabling the performance overview seems to do nothing. Changing from off to 1 through 4 does nothing both in just Steam and in games as well.

**Comment by KyleGospo** [comment]
We had a single build go out with this bug, if you update it should resume working as normal

**Comment by KaiserCalm** [comment]
Yup, after the update it's all good again. Thank you!
