### ISSUE TITLE
Missing `...` menu in GameMode

### ISSUE THREAD

**Issue by Kidswiss** [ublue-os/bazzite#619]
Hi

I've just installed a clean version of the `bazzite-gnome-deck` image using the 2.0.2 installer on an all AMD PC and updated to the latest stable version.

But in the GameMode I'm not able to access the performance settings or anything under the `...` menu.

The GUI doesn't show the `...` button at all and pressing xbox+a on the controller doesn't do anything either.

Am I missing some packages or configuration?

**Comment by Mitchou** [comment]
Got the same thing, try `xbox` then `a` instead of `xbox+a`
Work for me

**Comment by Kidswiss** [comment]
Thanks @Mitchou that actually works!

But I'd still argue that the current behaviour is a bug though. There's no indication that the menu is actually available when in GameMode.

**Comment by HikariKnight** [comment]
> Thanks @Mitchou that actually works!
> 
> But I'd still argue that the current behaviour is a bug though. There's no indication that the menu is actually available when in GameMode.

it is an issue with the xinput driver in linux and it affects multiple linux systems (including stock steamOS last time i checked)
It does not affect playstation controllers and switch controllers

The fact that there is no indication that the menu is available is a Steam issue, bazzite has no control over that sadly

**Comment by Kidswiss** [comment]
I see, then we can only wait.

Thanks for clarifying!

**Comment by HikariKnight** [comment]
no problem :smile:

**Comment by ZainAjam** [comment]
when I'm using a tv-style remote for keyboard/mouse (i.e. pepper job remote), the missing ... at the bottom means I can't click on it to open the menu and I have to actually connect the xbox controller to do xbox+a. We need the ... for controllers without a guide/nexus button like the pepper jobs remote

**Comment by HikariKnight** [comment]
This is not something we can add to steam, only valve can do it.

You can open the right menu with CTRL+2 however that does not work when an application/game is running, this is something that valve will have to fix.
