### ISSUE TITLE
Auto brightness nonfunctional

### ISSUE THREAD

**Issue by jerbmega** [ublue-os/bazzite#62]
In Gamescope Big Picture's display settings, the "Enable Adaptive Brightness" setting is greyed out and cannot be activated.

**Comment by KyleGospo** [comment]
This may be resolved by 1386380a484adc44f1443148748491a853c25f3a

**Comment by KyleGospo** [comment]
Night mode/Vibrant deck working with an older build of gamescope, last remaining issue is auto brightness.

**Comment by KyleGospo** [comment]
This may be resolved by https://github.com/KyleGospo/gamescope-session/commit/147855c77bfe3e3546ec50005baad383963bbc65
