### ISSUE TITLE
sddm changed: no user avatars to select, freeform username input

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/bazzite#625]
I dont know if this is a custom SDDM theme?

It looks like Breeze but not really. It lacks the user avatars and the username is freeform, so you need to know how it is typed exactly

**Comment by KyleGospo** [comment]
We only ship the SDDM theme on deck builds, which should also have auto login.

**Comment by firefoxlover** [comment]
Yeah but it was regular bazzite and there was no autologin. So this is not true.
