### ISSUE TITLE
Cant reinstall Firefox:

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/bazzite#626]
```
rpm-ostree install firefox firefox-langpacks
# error: already requested
```

something like that. There has to be an issue in how the removal is done. Flatpak Firefox is not as secure (lack of internal Sandbox), has no native messaging, drag&drop, etc.

This made Bazzite unusable for me

**Comment by KyleGospo** [comment]
Upstream issue, nothing we can do to resolve. Firefox is best kept as a flatpak for update reasons.

**Comment by firefoxlover** [comment]
okay I will add a comment in a probably existing issue in rpm-ostree
