### ISSUE TITLE
Bluetooth Pairing broken in GUI

### ISSUE THREAD

**Issue by 0x4d6165** [ublue-os/bazzite#631]
Essentially, I can only pair Bluetooth devices after the first (why the first works I'm not sure) via bluetoothctl in the terminal but the game interface and KDE guis for pairing Bluetooth devices result in a long wait and then an error code. It's strange because it's not blocking Bluetooth entirely (everything works fine when my headphones are connected via the command line), it's only having issues in the GUI. I'm on the LCD version of the stream deck running the latest build.

**Comment by DonnyTheDuck** [comment]
This is the same issue as #585 https://github.com/ublue-os/bazzite/issues/585

**Comment by KyleGospo** [comment]
Closing as duplicate, upstream has had a lot of bluez related issues and we'll fix them as patches are made.
