### ISSUE TITLE
LACT in HTPC version

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#634]
Can you put LACT in Steam Deck / HTPC Version, i really want to control my GPU fan, from a tropical country and it gets very hot here.

**Comment by KyleGospo** [comment]
LACT is avaialable in the Bazzite Portal, you may also run `ujust install-lact`

**Comment by massatt212** [comment]
----7@fedora:/var/home/----7$ ujust install-lact
error: Justfile does not contain recipe `install-lact`.
----@fedora:/var/home/----7$

**Comment by massatt212** [comment]
> LACT is avaialable in the Bazzite Portal, you may also run `ujust install-lact`

i think this portal not updated cause there is no LACT in there or in the terminal, and the 15w big still persist with my rx 6400

**Comment by KyleGospo** [comment]
LACT was added to just over a month ago, please make sure you're up to date before opening an issue.

**Comment by massatt212** [comment]
> LACT was added to just over a month ago, please make sure you're up to date before opening an issue.

everything is updated, and lact is not on the steamdeck / htpc i think you should take a look at it, or we are getting different updates from you.
