### ISSUE TITLE
DisplayLink D6000

### ISSUE THREAD

**Issue by nokry56** [ublue-os/bazzite#635]
Hi all,

I’m having an issue where my Dell D6000 dock constantly loses communication with my monitor over HDMI

Important to note that over DisplayPort my monitor is never detected at all. 

The losing connection issue sounds similar to the description here (https://github.com/displaylink-rpm/displaylink-rpm#dell-d6000 ) but the default.pa file does not exist on my system 

I have rebased to unstable to make sure I have DisplayLink installed. (bazzite-deck:unstable)

So two questions:
1. How can I get this monitor to consistently work over HDMI (ideally at 60hz)?
2. Any additional fix to have the DisplayPort connection work?

Thank you!

**Comment by nokry56** [comment]
Just an update that disabling and stopping the DisplayLink service does allow my dock to work, albeit at the none DisplayLink refresh rate of 30hz

**Comment by bi0shacker001** [comment]
Displaylink is always a bit crashy on linux, and I've been seeing the same on my dock setup. It's likely not a distro issue, displaylink's linux drivers tend to be unstable and picky.
Make sure you have a 10gbps or higher rated cable (yes, that does matter), try not to run at 4k if you want 60hz, be careful how many other things you have plugged into the dock, and if you have switchable nvidia graphics, you'll probably want to disable the nvidia graphics (displaylink works via transmitting a compressed frame buffer, and using the nvidia card adds an additional step to copy the buffer to system ram before transferring it). 
Displaylink is just not a great solution in general if you want fluid performance. It'll put things on the screen, eventually.
