### ISSUE TITLE
HTPC Version RX 6400 problem

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#636]
Still have the same problem since launch my RX 6400 is still reading 15 watts, how do i fix this, i really want to use this os but its the main problem, 11fps on street fighter 6 lol

**Comment by KyleGospo** [comment]
Please give me the output of `rpm-ostree status` and `cat /etc/default/steam-hardware-control`

**Comment by massatt212** [comment]
I already used this guy fix to get the tdp up, so when I reinstall I'll send it.

**Comment by KyleGospo** [comment]
Based on your other issue (https://github.com/ublue-os/bazzite/issues/634) it appears you are using a very old build of Bazzite. Please ensure you're up to date before opening issues. TDP control was disabled for all but Steam Deck hardware on September 4th.

**Comment by massatt212** [comment]
i use the latest iso and fresh installation how do i update?

**Comment by KyleGospo** [comment]
`rpm-ostree update`

`rpm-ostree status`

**Comment by massatt212** [comment]
![Screenshot_20231230_154400](https://github.com/ublue-os/bazzite/assets/43518479/066e2da9-244f-4874-a822-96ec10047c6a)
or there is more to do?

**Comment by massatt212** [comment]
ill send results im trying the 2 commands

**Comment by massatt212** [comment]
```
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:3da22ce2b8e631005eb30d980599290be9e2c332b6664e170bc092813fbe6e64
                  Version: 39.20231229.0 (2023-12-29T17:38:37Z)
          LayeredPackages: cargo gnome-disk-utility rust
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:3da22ce2b8e631005eb30d980599290be9e2c332b6664e170bc092813fbe6e64
                  Version: 39.20231229.0 (2023-12-29T17:38:37Z)
          LayeredPackages: gnome-disk-utility
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"
```

Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
Checking out tree 0f6b046... done
Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:ublue-os:staging fedora-cisco-openh264 updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree updates-archive
Importing rpm-md... done
rpm-md repo 'copr:copr.fedorainfracloud.org:ublue-os:staging' (cached); generated: 2023-12-30T04:04:12Z solvables: 94
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:57:01Z solvables: 4
rpm-md repo 'updates' (cached); generated: 2023-12-30T01:13:27Z solvables: 17253
rpm-md repo 'fedora' (cached); generated: 2023-11-01T00:12:39Z solvables: 70825
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2023-12-29T16:50:04Z solvables: 110
rpm-md repo 'rpmfusion-free' (cached); generated: 2023-11-04T16:49:08Z solvables: 445
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2023-12-29T17:05:04Z solvables: 56
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2023-11-04T17:26:32Z solvables: 208
rpm-md repo 'updates-archive' (cached); generated: 2023-12-30T01:43:15Z solvables: 19868
Resolving dependencies... done
No upgrade available.

**Comment by massatt212** [comment]
fresh installation, still no LACT and GPU still on 15w, something is not working, either your patches are not being sent you doing something wrong
