### ISSUE TITLE
SELinux is preventing Everest (Modded Celeste) from functioning

### ISSUE THREAD

**Issue by KaiserCalm** [ublue-os/bazzite#647]
After installing the Olympus flatpak,  setting the installation folder of Celeste,  installing Everest into it and attempting to launch modded Celeste, the game crashes and instead a text editor opens up with the text:

```
Monocle Engine Error Log
==========================================

01/04/2024 16:55:19
System.ComponentModel.Win32Exception (13): SELinux execheap probe failed! Please ensure Everest has this permission, then try again
   at Celeste.Mod.BOOT.Main(String[] args) in /home/vsts/work/1/s/Celeste.Mod.mm/Mod/Everest/BOOT.cs:line 65

```

**Comment by KyleGospo** [comment]
Unfortunately you'll need to either move the location of this executable to a more proper location, set SELinux to permissive, or make a SELinux rule for this. I would recommend trying /usr/local/bin.

**Comment by HappiePlant** [comment]
I have the same issue, but just on regular Fedora, does anyone how to make a SELinux rule for this?
