### ISSUE TITLE
Xbox Series X Controller won't appear on bluetooth settings when set to pair, neither it shows on the "sudo bluetoothctl" command

### ISSUE THREAD

**Issue by shakezineo** [ublue-os/bazzite#648]
I'm using the Bazzite-gnome-nvidia variation and with it i can't in any way get my controller to show up for me to pair via bluetooth, via cable it works but it doesn't show when i set it to pair via bluetooth

**Comment by beefchimi** [comment]
I've been having a similar issue _(using KDE Nvidia image)_ - but only with the `Xbox Series X Controller`. I was unable to fix this issue, so I recently bought a Sony DualSense Edge and that so far has been working/pairing perfectly.

**Comment by KyleGospo** [comment]
Please retest this after our next release and let me know if you can still reproduce this behavior

**Comment by Nitrousoxide** [comment]
Same thing here.  Connecting via bluetooth appears to have two xbox controllers pop up, an xbone one and a 360 one.  Steam tries to use use the 360 entity which recieves no inputs, though the xbone controller device is recieving them fine.  Connecting via wire works correctly, and connecting a ps5 controller via bluetooth works fine.

2 Devices
https://cdn.discordapp.com/attachments/1200828470842900683/1201172600634736650/2024-01-28_09-29-14.mp4

It might also be misidentifying the face buttons too even with the xbone controller, as it seems to think x/y are North and West
https://cdn.discordapp.com/attachments/1200828470842900683/1201173860482044005/2024-01-28_09-33-22.mp4

actually plug in the controller and it works fine in steam
https://cdn.discordapp.com/attachments/1200828470842900683/1201174642132533278/2024-01-28_09-37-48.mp4

a ps5 controller works fine when connected via bluetooth
https://cdn.discordapp.com/attachments/1200828470842900683/1201176025304944720/2024-01-28_09-44-00.mp4

**Comment by beefchimi** [comment]
Finally, things seem to be working again :smile: No more issues pairing my controller!
