### ISSUE TITLE
sunshine not finding any encoder

### ISSUE THREAD

**Issue by zqpvr** [ublue-os/bazzite#649]
![image](https://github.com/ublue-os/bazzite/assets/96351311/e84ea23d-cdd9-42d3-8810-55bbcfb75a09)

here is the error log `https://paste.ee/p/FrXhy`

I am using unstable branch of bazzite on bazzite-deck image and installed sunshine with `just install-sunshine`

**Comment by m2Giles** [comment]
Try :testing. There is a workaround to give sunshine the proper capabilities and I don't think that has been merged into :unstable.

**Comment by m2Giles** [comment]
Can you post an updated log from after you swapped over to :testing.

**Comment by m2Giles** [comment]
You are on :testing?

Check to see if sunshine-workaround.service successfully ran. If it did, check if sunshine actually has CAP_SYS_ADMIN.

**Comment by m2Giles** [comment]
Okay the workaround didn't work as expected. I'll try and merge a fix later.

Thank you for the report.

**Comment by m2Giles** [comment]
The service isn't running?

**Comment by m2Giles** [comment]
You do not have an image with the new commit on it yet.

**Comment by m2Giles** [comment]
Did you reboot? 

You have the updated file. But the condition says failed.

**Comment by m2Giles** [comment]
I'll try something different.

**Comment by m2Giles** [comment]
Okay didn't realize the just command was installing the flatpak version of sunshine.

Make sure the following ran:
```
flatpak run --command=additional-install.sh dev.lizardbyte.sunshine
```
This should of ran as part of the just command.

**Comment by KyleGospo** [comment]
> Okay didn't realize the just command was installing the flatpak version of sunshine.
> 
> Make sure the following ran:
> ```
> flatpak run --command=additional-install.sh dev.lizardbyte.sunshine
> ```
> This should of ran as part of the just command.

It does currently but evidently that has issues, we will likely begin to recommend layering it with the fix in place.

**Comment by nobodywatchin** [comment]
Having the exact same issue. Rebased to testing and getting the exact result on desktop

**Comment by m2Giles** [comment]
Yes

**Comment by nobodywatchin** [comment]
Layered sunshine does work, even on :latest
