### ISSUE TITLE
No audio after sleep/desktop mode on OLED deck

### ISSUE THREAD

**Issue by crispywaffles666** [ublue-os/bazzite#666]
All audio will stop after putting the deck to sleep then moving from gaming mode to desktop mode or vice versa.

This is on `gnome:testing`

Upon checking sound output settings in Gnome Settings, the output device "Speaker - ACP/ACP3X/ACP6x Audio Coprocessor" can no longer be found.

The only way to restore audio that I have found is a reboot.

There are two other users in the discord that have reported the same issue. Both of which reported using an OLED deck. I am not sure if they are using Gnome or KDE - though one of them mentions 'Van gough' audio device and the audio applet which sound like KDE things. So perhaps this bug effects KDE as well.

Happy to provide additional information if needed.

**Comment by Raltay** [comment]
Adding to what author said.

Summary
========
All audio stops 'being produced' after either:

- If in gamescope mode - putting device to sleep, waking it up from sleep and going from gamescope to desktop mode.
- If in desktop mode - putting device to sleep and waking it up.

Initial analysis
============
Before reproduction, respective input and output devices for 'Van Gogh ACP/ACP3X/ACP6x' are detected and set as default audio devices upon boot. Audio works as expected here.

After successful reproduction (of the issue), above mentioned 'Van Gogh' entries for input/output devices disappear from list of options (changing selected entries to sink/source chain respectively). Additionally, new 'Van Gogh' entry appears on the list of 'Disabled devices', with only 2 'state options' available - 'Off' and some 'Pro Audio Profile' (selecting the latter seems to have no effect on fixing/circumventing the issue).

Neither restarting Pipewire/Pipewire-Pulse/Wireplumber systemd user services nor switching between gamescope/desktop modes (and vice versa) fixes the issue. Only HW reboot fixes it - until chain of events (mentioned above) is executed again, which causes the issue to reappear.

HW/SW versions
================
Hardware: Steam Deck OLED
BIOS version: F7G0107
Kernel version: 6.6.9-201.fsync.fc39.x86_64
Ostree-Image version: bazzite-deck-gnome:testing - 2024-01-09T04:16:46Z (though this issue also reproduced on bazzite-deck:testing when I had it on OLED about a week ago)

SW Setup
========
1) Install bazzite-deck-gnome:testing (by editing grub entry) directly from the installer on OLED.
2) After install, perform (and finish) initial OS setup via Bazzite Portal (nothing additional which isn't included in Bazzite Portal was performed on OS).
3) Back in gamescope, login into Steam.
4) After waiting a bit, turn off device.

Bug reproduction
================

Test Steps
----------
1) Boot SD.
2) Wait until it boots into Gamescope mode.
3) Put to sleep.
4) Wake from sleep.
5) Go into desktop mode.

Expected Outcome
----------------
- Audio work as intended (i.e. as in Gamescope mode), system sounds are present, music plays etc.
- 'Van Gogh' input/output audio devices are present on the list of available input/output audio devices (for selection) and are selected by default for both.

Present Outcome
---------------
- Audio doesn't work at all, no sound is produced.
- 'Van Gogh' input/output audio devices are missing from the list of available input/output audio devices (for selection).
- Respective source/sink chain devices are selected.
- New 'Van Gogh' device appears on the list of 'Disabled devices', with only 2 'state options' available - 'Off' and some 'Pro Audio Profile' (selecting the latter seems to have no effect on fixing/circumventing the issue).

If any additional info is needed, please get in touch with me either here or in Discord.

Best Regards.

**Comment by teddy74eva** [comment]
OP of the issue on Discord, just to add to the fantastic writeup above:

1. Issue is not present on the latest SteamOS so HW fault is unlikely,
2. Here is a snippet of running `dmesg` right after replicating the issue:

```[ 2012.995072] PM: resume devices took 0.698 seconds
[ 2012.995706] OOM killer enabled.
[ 2012.995710] Restarting tasks ... done.
[ 2012.999438] random: crng reseeded on system resumption
[ 2013.001041] PM: suspend exit
[ 2016.693973] wlo1: authenticate with 04:42:1a:78:f2:b4
[ 2016.741927] wlo1: send auth to 04:42:1a:78:f2:b4 (try 1/3)
[ 2016.745381] wlo1: authenticated
[ 2016.746505] wlo1: associate with 04:42:1a:78:f2:b4 (try 1/3)
[ 2016.749159] wlo1: RX AssocResp from 04:42:1a:78:f2:b4 (capab=0x1011 status=0 aid=19)
[ 2016.770358] wlo1: associated
[ 2028.659705] snd_sof_amd_vangogh 0000:04:00.5: ipc tx error for 0x60010000 (msg/reply size: 108/20): -22
[ 2028.659713] snd_sof_amd_vangogh 0000:04:00.5: HW params ipc failed for stream 1
[ 2028.659716] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -22
[ 2028.679485] snd_sof_amd_vangogh 0000:04:00.5: ipc tx error for 0x60010000 (msg/reply size: 108/20): -22
[ 2028.679492] snd_sof_amd_vangogh 0000:04:00.5: HW params ipc failed for stream 1
[ 2028.679495] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -22
[ 2028.681088] snd_sof_amd_vangogh 0000:04:00.5: ------------[ DSP dump start ]------------
[ 2028.681091] snd_sof_amd_vangogh 0000:04:00.5: DSP panic!
[ 2028.681093] snd_sof_amd_vangogh 0000:04:00.5: fw_state: SOF_FW_BOOT_COMPLETE (7)
[ 2028.681157] snd_sof_amd_vangogh 0000:04:00.5: reason: runtime exception (0x6)
[ 2028.681160] snd_sof_amd_vangogh 0000:04:00.5: trace point: 0x0dead006
[ 2028.681161] snd_sof_amd_vangogh 0000:04:00.5: panic at @:268435464
[ 2028.681164] snd_sof_amd_vangogh 0000:04:00.5: error: DSP Firmware Oops
[ 2028.681166] snd_sof_amd_vangogh 0000:04:00.5: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
[ 2028.681168] snd_sof_amd_vangogh 0000:04:00.5: EXCCAUSE 0x0000000d EXCVADDR 0xe010082c PS       0x00060f25 SAR     0xfff7e5ff
[ 2028.681171] snd_sof_amd_vangogh 0000:04:00.5: EPC1     0x20000fa7 EPC2     0x00000000 EPC3     0x20000a6e EPC4    0x00000000
[ 2028.681173] snd_sof_amd_vangogh 0000:04:00.5: EPC5     0x20000a6e EPC6     0xff9e7dff EPC7     0x00000000 DEPC    0x00000000
[ 2028.681175] snd_sof_amd_vangogh 0000:04:00.5: EPS2     0x00000000 EPS3     0x00060d20 EPS4     0x00000000 EPS5    0x00060d20
[ 2028.681178] snd_sof_amd_vangogh 0000:04:00.5: EPS6     0x00081080 EPS7     0x00000000 INTENABL 0x01820402 INTERRU 0x00000045
[ 2028.681180] snd_sof_amd_vangogh 0000:04:00.5: stack dump from 0xe00e0980
[ 2028.681183] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e0980: 57487000 65efa008 6cb03800 c7a9f4f6
[ 2028.681186] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e0990: 3fe8f53e 3ff97be8 000003ff e00e09a0
[ 2028.681188] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09a0: e00e0980 3ff97be8 9ecd9607 3fe8f53e
[ 2028.681190] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09b0: 3feaa370 df800000 3fe149f4 9f400000
[ 2028.681192] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09c0: 3ff93331 9364290b 00000000 41a00000
[ 2028.681195] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09d0: 20000fa7 40000e11 d4000000 40008d4f
[ 2028.681197] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09e0: df000000 4527d27d 3ff2e64b 204f65ec
[ 2028.681199] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09f0: 3feaa370 df800000 3fe149f4 9f400000
[ 2028.681201] snd_sof_amd_vangogh 0000:04:00.5: ------------[ DSP dump end ]------------
[ 2028.732160] input: Steam Deck as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-3/3-3:1.2/0003:28DE:1205.0003/input/input50
[ 2029.004190] [drm] Failed to add display topology, DTM TA is not initialized.
[ 2029.185739] snd_sof_amd_vangogh 0000:04:00.5: ipc tx timed out for 0x30010000 (msg/reply size: 140/0)
[ 2029.185753] snd_sof_amd_vangogh 0000:04:00.5: ------------[ IPC dump start ]------------
[ 2029.185767] snd_sof_amd_vangogh 0000:04:00.5: dsp_msg = 0x0 dsp_ack = 0x0 host_msg = 0x0 host_ack = 0x0 irq_stat = 0x1
[ 2029.185773] snd_sof_amd_vangogh 0000:04:00.5: ------------[ IPC dump end ]------------
[ 2029.185777] snd_sof_amd_vangogh 0000:04:00.5: IPC timeout
[ 2029.185782] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget SMART_AMP2.0
[ 2029.185791] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30110000 failed: -19
[ 2029.185797] snd_sof_amd_vangogh 0000:04:00.5: failed to free widget PIPELINE.2.ACPHS1.OUT
[ 2029.185802] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30210000 failed: -19
[ 2029.185806] snd_sof_amd_vangogh 0000:04:00.5: failed to free widget BUF2.0
[ 2029.185811] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30020000 failed: -19
[ 2029.185815] snd_sof_amd_vangogh 0000:04:00.5: failed to free widget PCM1P
[ 2029.185819] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
[ 2029.185826] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
[ 2029.185833] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -110
[ 2029.185868]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -110
[ 2029.185877]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -110
[ 2029.186021] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
[ 2029.186026] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget PCM1P
[ 2029.186029] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
[ 2029.186034] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
[ 2029.186038] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -19
[ 2029.186049]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -19
[ 2029.186053]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -19
[ 2029.186136] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
[ 2029.186140] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget PCM1P
[ 2029.186144] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
[ 2029.186148] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
[ 2029.186152] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -19
[ 2029.186162]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -19
[ 2029.186166]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -19
[ 2029.186804] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
[ 2029.186812] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget PCM1P
[ 2029.186816] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
[ 2029.186820] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
[ 2029.186824] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -19
[ 2029.186838]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -19
[ 2029.186843]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -19
[ 2029.186917] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
```

Those last few blocks of messages are repeated until device is rebooted. As above, I'm more than happy to help with this so please do hit me up if needed.

**Comment by KyleGospo** [comment]
Let me know if you can still reproduce this on the latest testing update.

**Comment by teddy74eva** [comment]
@KyleGospo Just gave it a spin, unfortunately the issue is still present after a fresh install of the latest testing image of `bazzite-deck`. Only had time to take a glance at `dmesg` and it stayed the same as well.

**Comment by KyleGospo** [comment]
Found this upstream
https://github.com/thesofproject/sof/issues/8721

**Comment by bhiregoudar** [comment]
> OP of the issue on Discord, just to add to the fantastic writeup above:
> 
> 1. Issue is not present on the latest SteamOS so HW fault is unlikely,
> 2. Here is a snippet of running `dmesg` right after replicating the issue:
> 
> ```
> [ 2012.995706] OOM killer enabled.
> [ 2012.995710] Restarting tasks ... done.
> [ 2012.999438] random: crng reseeded on system resumption
> [ 2013.001041] PM: suspend exit
> [ 2016.693973] wlo1: authenticate with 04:42:1a:78:f2:b4
> [ 2016.741927] wlo1: send auth to 04:42:1a:78:f2:b4 (try 1/3)
> [ 2016.745381] wlo1: authenticated
> [ 2016.746505] wlo1: associate with 04:42:1a:78:f2:b4 (try 1/3)
> [ 2016.749159] wlo1: RX AssocResp from 04:42:1a:78:f2:b4 (capab=0x1011 status=0 aid=19)
> [ 2016.770358] wlo1: associated
> [ 2028.659705] snd_sof_amd_vangogh 0000:04:00.5: ipc tx error for 0x60010000 (msg/reply size: 108/20): -22
> [ 2028.659713] snd_sof_amd_vangogh 0000:04:00.5: HW params ipc failed for stream 1
> [ 2028.659716] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -22
> [ 2028.679485] snd_sof_amd_vangogh 0000:04:00.5: ipc tx error for 0x60010000 (msg/reply size: 108/20): -22
> [ 2028.679492] snd_sof_amd_vangogh 0000:04:00.5: HW params ipc failed for stream 1
> [ 2028.679495] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -22
> [ 2028.681088] snd_sof_amd_vangogh 0000:04:00.5: ------------[ DSP dump start ]------------
> [ 2028.681091] snd_sof_amd_vangogh 0000:04:00.5: DSP panic!
> [ 2028.681093] snd_sof_amd_vangogh 0000:04:00.5: fw_state: SOF_FW_BOOT_COMPLETE (7)
> [ 2028.681157] snd_sof_amd_vangogh 0000:04:00.5: reason: runtime exception (0x6)
> [ 2028.681160] snd_sof_amd_vangogh 0000:04:00.5: trace point: 0x0dead006
> [ 2028.681161] snd_sof_amd_vangogh 0000:04:00.5: panic at @:268435464
> [ 2028.681164] snd_sof_amd_vangogh 0000:04:00.5: error: DSP Firmware Oops
> [ 2028.681166] snd_sof_amd_vangogh 0000:04:00.5: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
> [ 2028.681168] snd_sof_amd_vangogh 0000:04:00.5: EXCCAUSE 0x0000000d EXCVADDR 0xe010082c PS       0x00060f25 SAR     0xfff7e5ff
> [ 2028.681171] snd_sof_amd_vangogh 0000:04:00.5: EPC1     0x20000fa7 EPC2     0x00000000 EPC3     0x20000a6e EPC4    0x00000000
> [ 2028.681173] snd_sof_amd_vangogh 0000:04:00.5: EPC5     0x20000a6e EPC6     0xff9e7dff EPC7     0x00000000 DEPC    0x00000000
> [ 2028.681175] snd_sof_amd_vangogh 0000:04:00.5: EPS2     0x00000000 EPS3     0x00060d20 EPS4     0x00000000 EPS5    0x00060d20
> [ 2028.681178] snd_sof_amd_vangogh 0000:04:00.5: EPS6     0x00081080 EPS7     0x00000000 INTENABL 0x01820402 INTERRU 0x00000045
> [ 2028.681180] snd_sof_amd_vangogh 0000:04:00.5: stack dump from 0xe00e0980
> [ 2028.681183] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e0980: 57487000 65efa008 6cb03800 c7a9f4f6
> [ 2028.681186] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e0990: 3fe8f53e 3ff97be8 000003ff e00e09a0
> [ 2028.681188] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09a0: e00e0980 3ff97be8 9ecd9607 3fe8f53e
> [ 2028.681190] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09b0: 3feaa370 df800000 3fe149f4 9f400000
> [ 2028.681192] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09c0: 3ff93331 9364290b 00000000 41a00000
> [ 2028.681195] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09d0: 20000fa7 40000e11 d4000000 40008d4f
> [ 2028.681197] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09e0: df000000 4527d27d 3ff2e64b 204f65ec
> [ 2028.681199] snd_sof_amd_vangogh 0000:04:00.5: 0xe00e09f0: 3feaa370 df800000 3fe149f4 9f400000
> [ 2028.681201] snd_sof_amd_vangogh 0000:04:00.5: ------------[ DSP dump end ]------------
> [ 2028.732160] input: Steam Deck as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-3/3-3:1.2/0003:28DE:1205.0003/input/input50
> [ 2029.004190] [drm] Failed to add display topology, DTM TA is not initialized.
> [ 2029.185739] snd_sof_amd_vangogh 0000:04:00.5: ipc tx timed out for 0x30010000 (msg/reply size: 140/0)
> [ 2029.185753] snd_sof_amd_vangogh 0000:04:00.5: ------------[ IPC dump start ]------------
> [ 2029.185767] snd_sof_amd_vangogh 0000:04:00.5: dsp_msg = 0x0 dsp_ack = 0x0 host_msg = 0x0 host_ack = 0x0 irq_stat = 0x1
> [ 2029.185773] snd_sof_amd_vangogh 0000:04:00.5: ------------[ IPC dump end ]------------
> [ 2029.185777] snd_sof_amd_vangogh 0000:04:00.5: IPC timeout
> [ 2029.185782] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget SMART_AMP2.0
> [ 2029.185791] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30110000 failed: -19
> [ 2029.185797] snd_sof_amd_vangogh 0000:04:00.5: failed to free widget PIPELINE.2.ACPHS1.OUT
> [ 2029.185802] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30210000 failed: -19
> [ 2029.185806] snd_sof_amd_vangogh 0000:04:00.5: failed to free widget BUF2.0
> [ 2029.185811] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30020000 failed: -19
> [ 2029.185815] snd_sof_amd_vangogh 0000:04:00.5: failed to free widget PCM1P
> [ 2029.185819] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
> [ 2029.185826] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
> [ 2029.185833] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -110
> [ 2029.185868]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -110
> [ 2029.185877]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -110
> [ 2029.186021] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
> [ 2029.186026] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget PCM1P
> [ 2029.186029] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
> [ 2029.186034] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
> [ 2029.186038] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -19
> [ 2029.186049]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -19
> [ 2029.186053]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -19
> [ 2029.186136] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
> [ 2029.186140] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget PCM1P
> [ 2029.186144] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
> [ 2029.186148] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
> [ 2029.186152] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -19
> [ 2029.186162]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -19
> [ 2029.186166]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -19
> [ 2029.186804] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
> [ 2029.186812] snd_sof_amd_vangogh 0000:04:00.5: Failed to setup widget PCM1P
> [ 2029.186816] snd_sof_amd_vangogh 0000:04:00.5: Failed to set up connected widgets
> [ 2029.186820] snd_sof_amd_vangogh 0000:04:00.5: error: failed widget list set up for pcm 1 dir 0
> [ 2029.186824] snd_sof_amd_vangogh 0000:04:00.5: ASoC: error at snd_soc_pcm_component_hw_params on 0000:04:00.5: -19
> [ 2029.186838]  I2SHS: ASoC: error at __soc_pcm_hw_params on I2SHS: -19
> [ 2029.186843]  I2SHS: ASoC: error at dpcm_fe_dai_hw_params on I2SHS: -19
> [ 2029.186917] snd_sof_amd_vangogh 0000:04:00.5: ipc3_tx_msg_unlocked: ipc message send for 0x30010000 failed: -19
> ```
> 
> Those last few blocks of messages are repeated until device is rebooted. As above, I'm more than happy to help with this so please do hit me up if needed.

I think the new stream has started before topology is loaded which has probably caused exception in DSP. The sequence of stream start needs to be taken care.

**Comment by manglinslax** [comment]
no fix to this unfortunately then

**Comment by bhiregoudar** [comment]
> no fix to this unfortunately then

This is not in our scope to fix it.
