### ISSUE TITLE
Add Custom Animation to KDE Login and Game Mode Bootup

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/bazzite#672]
Sean on the Universal Blue Discord was kind enough to create an animation which looks very nice! It would be awesome to see this set as the default for login of Desktop Mode and starting up Game Mode. 

https://discord.com/channels/1072614816579063828/1087140957096517672/1195185037612687360

**Comment by SuperRiderTH** [comment]
Hi, that is me! I attached the webm here for reference outside of Discord.

[Bazzite.webm](https://github.com/ublue-os/bazzite/assets/5368844/4cc3fec0-86cc-4629-ad02-4eb3e0a1fd92)

**Comment by noelmiller** [comment]
> Hi, that is me! I attached the webm here for reference outside of Discord.
> 
>  Bazzite.webm

You are awesome! Thanks so much for contributing this!
