### ISSUE TITLE
Bazzite's justfile should not be `60-custom.just`

### ISSUE THREAD

**Issue by noahdotpy** [ublue-os/bazzite#679]
### Describe the bug

The custom justfile that bazzite uses is `60-custom.just`, which is the same name that custom distro images would use. I expect it to be something different (`bazzite.just`?)

### What did you expect to happen?

I expected the justfile that adds bazzite-specific recipes would be a different file name, like `bazzite.just`.

### Extra information or context

This would be useful for people who use custom images, like I do

**Comment by noahdotpy** [comment]
we could achieve this by creating a script to extend /usr/share/ublue-os/justfile at the image build step

**Comment by KyleGospo** [comment]
Fixed in next update
