### ISSUE TITLE
ROG Ally defaults to 90 degrees counterclockwise when opening desktop mode

### ISSUE THREAD

**Issue by Xe** [ublue-os/bazzite#680]
### Describe the bug

When I open desktop mode on the Ally running Bazzite, it defaults to 90 degrees counterclockwise. I think this is trying to compensate for portrait displays like the LCD Deck.

### What did you expect to happen?

The display to not be rotated 90 degrees counterclockwise.

### Output of `rpm-ostree status`

```shell
xe@aoi:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:testing
                   Digest: sha256:8de32e906d8f2a78f6136554e24283791f8fda17e377785f8400765fb2c70ff4
                  Version: 39.20240112.0 (2024-01-13T10:00:26Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:testing
                   Digest: sha256:5f1e71322e369dde9cedfb3698cda5470e500947378b5f5611f30340b26179d9
                  Version: 39.20240112.0 (2024-01-12T18:48:35Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

xe@aoi:~$ cat /sys/devices/virtual/dmi/id/product_name
ROG Ally RC71L_RC71L

### Extra information or context

![image](https://github.com/ublue-os/bazzite/assets/529003/4fe4d94e-0f8f-4eed-9be9-2672ac44c99c)

**Comment by KyleGospo** [comment]
Are you using Wayland or X11?

**Comment by Xe** [comment]
Wayland

**Comment by KyleGospo** [comment]
> Wayland

Probably needs the same fix the Legion does, can you let me know which rotation resolves the issue for you?
`kscreen-doctor output.1.rotation.left`
