### ISSUE TITLE
 Black screen  after installing the custom packages

### ISSUE THREAD

**Issue by HexRebuilt** [ublue-os/bazzite#687]
### Describe the bug

After installing the custom packages and rebooting, the screen goes black until the system shuts down on its own.  Prior to that i can hear the GPU fan speeding up and concequentially, slowing down after it shuts off.

If i try to turn it off by sending the command to shutdown, the screen comes back to life with the same boot animation for bazzlite.

### What did you expect to happen?

I expected to be able to login and use the system

### Hardware

I'm running Bazzite inside of proxmox, with 6 cores and an A2000 GPU. below the current configuration (i've tried also the UEFI bios+disk with the same outcome). 
The GPU was perfectly detected by the system before the reboot
![image](https://github.com/ublue-os/bazzite/assets/32871843/e7b3bac2-a7bd-43be-8157-beb9c014532b)

### Extra information or context

If I access the GRUB config by pressing E at the startup i obtain this configuration:
![image](https://github.com/ublue-os/bazzite/assets/32871843/9b12e595-9798-4f96-a466-8445d5524b1c)

Interestingly, if i add _ rd.live.check _ to the GRUB i'm able to reach the credential screen, loggin in and get to the same black screen. 

If i try to remove the GPU i'm able to reach the login screen but after i insert the credentials, i can see for a brief moment the top bar, then i get promped with the credentials again. after a frew tries i'm able to login. 

The solutions listed [here](https://universal-blue.discourse.group/docs?topic=34) do not work.

After reinstalling the os for 4 times i've made backups right after the install was completed and after the packages were installed, before rebooting

**Comment by HexRebuilt** [comment]
Just to try, i've installed fedora and later added bazzlite, as indicated by the guide linked above. 
It seems like in that case i'm able to use the machine normally but the nvidia driver are not  loaded. the grub seems a bit different.

i've tried to add a couple of entries but i'm not that familiar with GRUB.  
![image](https://github.com/ublue-os/bazzite/assets/32871843/ca50b864-7d4a-468a-ab5d-a2322394932c)

**Comment by HikariKnight** [comment]
> Just to try, i've installed fedora and later added bazzlite, as indicated by the guide linked above. It seems like in that case i'm able to use the machine normally but the nvidia driver are not loaded. the grub seems a bit different.
> 
> i've tried to add a couple of entries but i'm not that familiar with GRUB. ![image](https://private-user-images.githubusercontent.com/32871843/297217432-ca50b864-7d4a-468a-ab5d-a2322394932c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTQ0NzUsIm5iZiI6MTcwNTYxNDE3NSwicGF0aCI6Ii8zMjg3MTg0My8yOTcyMTc0MzItY2E1MGI4NjQtN2Q0YS00NjhhLWFiNWQtYTIzMjIzOTQ5MzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDIxNDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OGIyYmFlZjJjZmMxZWE1NmNhMGNmNjE3ZjRhNGM3ZDExOGRlM2I2ZWQxMmQ5MDQxOWViMGFkNTQ5MjU2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3AamG41YrijCcofv6m9t0xm9ExsbsacKPqd08rL0YI)
> 
> Plus, each time i open up the terminal i get this ![image](https://private-user-images.githubusercontent.com/32871843/297217941-fe9a8d01-aefd-420e-ba8e-100b6c20c3c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTQ0NzUsIm5iZiI6MTcwNTYxNDE3NSwicGF0aCI6Ii8zMjg3MTg0My8yOTcyMTc5NDEtZmU5YThkMDEtYWVmZC00MjBlLWJhOGUtMTAwYjZjMjBjM2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDIxNDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZjg4NDU2Y2IxZjUyNDk3MzBlNzc3NjA1NWM5ZTdiZDVkOTM5NzQyZDc0MTZjMDQ5MzQwYmVhNzY5OTliMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.24zcrq8kAmrFC-Z4TTxMpeb_aK0oTidVVfj6BTvL8xE) ![image](https://private-user-images.githubusercontent.com/32871843/297218040-e4a29a08-cc71-48e9-a6e2-0a59941a688b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTQ0NzUsIm5iZiI6MTcwNTYxNDE3NSwicGF0aCI6Ii8zMjg3MTg0My8yOTcyMTgwNDAtZTRhMjlhMDgtY2M3MS00OGU5LWE2ZTItMGE1OTk0MWE2ODhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDIxNDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGVmZDRjNmY4YTVmYTkzOTE5MGQ1YTQ3ZTI0ZDRkOTJmYWVkNjUxNTY3OGIxYjEwYzBkZTU1NmIyZGY1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JtSFktxTzcc9BWUFib5gnoJ4HoIeHTXccGvWRkj7Hik)

Hi, the nvidia kargs can be set with `ujust configure-nvidia`, this changed a few days ago and the documentation just needs to be updated (this is on me as i am the one who did the rework of these commands).
If you need to add kernel arguments yourself at a later time you can use `rpm-ostree kargs` look at the `rpm-ostree kargs --help` for usage info.

proxmox doesnt use secure boot by default so you can ignore the message in the terminal.

**Comment by HexRebuilt** [comment]
Hi,

After the last install i did change the HW in proxmox and it seems to use secure boot now.

If, via the remote console, i try to send over a (CTRL+ALT+DEL) the system resets. don't know if this is linked to the issue or not.

After running the terminal over SSH since the screen has only a blinking line and the mouse pointer i get this:

```
hexrebuilt@fedora:~$ ujust configure-nvidia
Configuring Nvidia drivers
What would you like to do?
/usr/bin/nvidia-smi
==== AUTHENTICATING FOR org.projectatomic.rpmostree1.bootconfig ====
Authentication is required to change boot configuration
Authenticating as: ------ (hexrebuilt)
Password:
==== AUTHENTICATION COMPLETE ====
No changes.
hexrebuilt@fedora:~$ ujust configure-nvidia
Configuring Nvidia drivers
What would you like to do?
Trying to pull docker.io/nvidia/samples:vectoradd-cuda11.2.1...
Getting image source signatures
Copying blob fe72fda9c19e done   |
Copying blob d22d2dfcfa9c done   |
Copying blob d519e2592276 done   |
Copying blob b25f8d7adb24 done   |
Copying blob b3afe92c540b done   |
Copying blob ddb025f124b9 done   |
Copying blob c88b7b7dd6ba done   |
Copying blob f2c9b54e36bc done   |
Copying blob 50333516d41c done   |
Copying config 02c32dc6d0 done   |
Writing manifest to image destination
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
hexrebuilt@fedora:~$ ujust configure-nvidia
Configuring Nvidia drivers
What would you like to do?
hexrebuilt@fedora:~$ rpm-ostree kargs
rhgb quiet root=UUID=42b2cf6e-f76b-425f-9685-1bbe98a98755 rootflags=subvol=root rw ostree=/ostree/boot.1/fedora/801d7b61b87e3701d298106d66f98e7692aa7ef2c69ef002a54a5b68328fda11/0 rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1
```

I've also tried to update everything, but no updates are available. 

> PS: also as i see you are going to do gpu passthrough to the VM, i highly recommend you to have a way to remotely access the screen as noVNC might not work properly once the gpu is passed to the VM

What would be your suggestion? because for me, after the initial set-up i would have used the system with stetam link

**Comment by HikariKnight** [comment]
I would remove the gpu from the VM, enable auto login with x11 (remote desktop in linux does not like the login screen) and make sure i can connect to the VM using a normal VNC or RDP first.
on KDE you can setup krfb, on Gnome you might have to install gnome-remote-desktop and configure that

krfb uses vnc, gnome-remote-desktop uses rdp. For krfb you need to make sure it runs at login.
once you have that working then plug in the gpu and see if you can connect using normal VNC or RDP to finish the configuration like that and pair with steam link (since i doubt it will work without the physical gpu due to encoding)

These steps would be what i do each time i setup a windows VM with gpu passthrough. i have never actually setup and used bazzite or linux in a VM with gpu passtrough, so i am not familiar with the quirks of that (if any).

**Comment by HikariKnight** [comment]
The os should not really care of it's in a VM with a real GPU or not. But it is not something we test for

**Comment by HexRebuilt** [comment]
i see.
Just for the sake of it i did try with a dummy plug for the display output with no difference.
I really don't know what else should i try/do on this issue.
The driver is loaded but, also with a display attatched to it, no video is shown.

what i get is this.
```
[    6.442611] iTCO_wdt iTCO_wdt.1.auto: Found a ICH9 TCO device (Version=2, TCOBASE=0x0660)
[    6.443698] iTCO_wdt iTCO_wdt.1.auto: initialized. heartbeat=30 sec (nowayout=0)
[    6.566396] snd_hda_intel 0000:06:10.1: Disabling MSI
[    6.568093] snd_hda_intel 0000:00:1b.0: no codecs found!
[    6.568651] systemd-journald[756]: /var/log/journal/7fe2dfc8bc2e41e8a7f956068d9d457f/system.journal: Journal file uses a different sequence number ID, rotating.
[    6.568662] systemd-journald[756]: Rotating system journal.
[    6.600609] input: HDA NVidia HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1e.0/0000:05:01.0/0000:06:10.1/sound/card1/input7
[    6.600733] input: HDA NVidia HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1e.0/0000:05:01.0/0000:06:10.1/sound/card1/input8
[    6.600862] input: HDA NVidia HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:1e.0/0000:05:01.0/0000:06:10.1/sound/card1/input9
[    6.601028] input: HDA NVidia HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:1e.0/0000:05:01.0/0000:06:10.1/sound/card1/input10
[    9.072183] RPC: Registered named UNIX socket transport module.
[    9.072187] RPC: Registered udp transport module.
[    9.072189] RPC: Registered tcp transport module.
[    9.072190] RPC: Registered tcp-with-tls transport module.
[    9.072191] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   10.792823] NET: Registered PF_QIPCRTR protocol family
[   13.466926] nvidia: module license 'NVIDIA' taints kernel.
[   13.466948] Disabling lock debugging due to kernel taint
[   13.466966] nvidia: module license taints kernel.
[   13.850017] pipewire[1364]: memfd_create() called without MFD_EXEC or MFD_NOEXEC_SEAL set
[   14.119252] nvidia-nvlink: Nvlink Core is being initialized, major device number 236

[   14.121960] nvidia 0000:06:10.0: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=none
[   14.163689] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  545.29.06  Thu Nov 16 01:59:08 UTC 2023
[   14.300201] nvidia_uvm: module uses symbols nvUvmInterfaceDisableAccessCntr from proprietary module nvidia, inheriting taint.
[   14.505115] nvidia-uvm: Loaded the UVM driver, major device number 234.
[   14.596841] tun: Universal TUN/TAP device driver, 1.6
[   14.606008] ACPI Warning: \_SB.PCI0.SF0.S08.S80._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20230628/nsarguments-61)
[   14.622730] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  545.29.06  Thu Nov 16 01:47:29 UTC 2023
[   15.827072] [drm] [nvidia-drm] [GPU ID 0x00000610] Loading driver
[   17.276674] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:06:10.0 on minor 1
[   17.437391] fbcon: Deferring console take-over
[   17.437399] nvidia 0000:06:10.0: [drm] fb1: nvidia-drmdrmfb frame buffer device
[   18.550933] systemd-journald[756]: Time jumped backwards, rotating.
[   22.749029] show_signal_msg: 38 callbacks suppressed
[   22.749039] sddm-greeter[1409]: segfault at 178 ip 00007fc4e6e15a80 sp 00007ffcd3ccb910 error 4 in libnvidia-eglcore.so.545.29.06[7fc4e6427000+bc3000] likely on CPU 0 (core 0, socket 0)
[   22.749054] Code: fe e8 d4 d5 0b 00 eb 8a 66 90 48 8b 78 10 4c 89 fe ff d2 e9 7a ff ff ff 66 90 55 48 89 fd 53 48 83 ec 08 48 8b 87 e0 03 00 00 <48> 39 b8 78 01 00 00 0f 84 eb 00 00 00 48 8b bd e8 03 00 00 48 85
```

Since i don't know what else to try, i think we can close the issue for the moment.
