### ISSUE TITLE
[SB+nVidia] missing akmods-MOK key on fresh install.

### ISSUE THREAD

**Issue by TriMoon** [ublue-os/bazzite#688]
### Describe the bug

Fresh install from bazzite-ISO on USB stick renders a boot with a black screen, due to a **different MOK-key** used in the ISO and latest bazzite ostree for `akmods`
- See similar with Kionite: [My post on uB-Discourse](https://universal-blue.discourse.group/t/secure-boot-notice/405/7?u=trimoon)

### What did you expect to happen?

Proper installation and startup.

### Hardware

[My new system for 2024: HAF700-EVO with ROG STRIX X670E-E GAMING WIFI](https://forum.linux-hardware.org/index.php?topic=123.0)

### Extra information or context

Workaround is:
1. Install Bazzite-nVidia (Latest)
2. Reboot into firmware and **Disable** SecureBoot.
_(This will allow the drivers to be loaded by the kernel)_
3. Boot bazzite.
4. Execute `sudo just enroll-secure-boot-key`.
5. Reboot into firmware and **Enable** SecureBoot again.
6. You will be prompted by the MokManager to enroll the new key, and reboot.
7. Booting into bazzite should now work again with SecureBoot enabled :wink:

**Comment by TriMoon** [comment]
PS: I totally freaking :100: :cupid: LOVE this Bazzite version of Linux, and have decided to make it my MAIN system :+1:

**Comment by KyleGospo** [comment]
Should be fixed by next release's ISO on Friday

**Comment by TriMoon** [comment]
@KyleGospo 
> Should be fixed by next release's ISO on Friday

I have been struggling with the new ISO, but seems it is **NOT** fixed yet...
- The MOK key installed by the installer is still the wrong one.
Due to this, a fresh install is **unable** to boot, you get an error after selecting a menu entry from the grub menu.
- After booting with SecureBoot **OFF** and enrolling the new MOK key, you can boot again with SB-ON.

So nothing really changed, the only diff is that this time the rogue MOK key that was enrolled in previous version is not enrolled anymore.

> [!Note]
Both enrolled MOK keys are for `akmods`, but have different serial numbers...
