### ISSUE TITLE
System Monitor does not display bandwidth stats

### ISSUE THREAD

**Issue by Xuerian** [ublue-os/bazzite#689]
### Describe the bug

System Monitor Upload/Download columns unpopulated

### What did you expect to happen?

Them to be populated

### Extra information or context

https://discuss.kde.org/t/in-system-monitor-why-the-app-specific-upload-download-rates-might-not-work/5860/6

Seems like it might be relevant.

**Comment by KyleGospo** [comment]
Thanks, this will be fixed when the new update goes live Friday
