### ISSUE TITLE
no gamemode at all

### ISSUE THREAD

**Issue by MakaiHanta** [ublue-os/bazzite#690]
### Describe the bug

After installation, initial setup, and reboot, nothing happens. Bazzite runs in the KDE plasma environment like a run-of-the-mill distribution

### What did you expect to happen?

When you install a distro that is "just like steam-os!" you expect to get steamOS, not a stripped down version of manjaro.

**Comment by KyleGospo** [comment]
Install the deck version if you want game mode, read the README, provide the details requested of the issue template.
