### ISSUE TITLE
ujust restore-original-terminal seems to not restore Konsole on KDE Desktop

### ISSUE THREAD

**Issue by RodoMa92** [ublue-os/bazzite#693]
### Describe the bug

After updating to latest testing, it seems that the default for KDE Desktops is Prompt as terminal emulator. Running restore-original-terminal and rebooting didn't bring Konsole back, it still keeps opening Prompt.

### What did you expect to happen?

I would like to keep using Konsole when right clicking on a folder and selecting Open Terminal

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:testing
                   Digest: sha256:fc1a2dc19dfb635b4aa6f4066f473d352b21ed47bc71a2c276b3f25b88911898
                Timestamp: 2024-01-18T22:52:06Z
          LayeredPackages: android-tools bluez-tools cargo comskip docker glances gnome-color-manager i2c-tools
                           java java-17-openjdk-devel powerline-fonts rust setroubleshoot-server tldr valgrind wavemon
                           wireshark-cli yt-dlp zsh
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:testing
                   Digest: sha256:0362f0b55894ff39f10c410a81d30658640ac6c157c155804a5b8b20881c8c50
                Timestamp: 2024-01-18T07:45:49Z
          LayeredPackages: android-tools bluez-tools comskip docker glances gnome-color-manager i2c-tools java
                           java-17-openjdk-devel powerline-fonts setroubleshoot-server tldr valgrind wavemon wireshark-cli
                           yt-dlp zsh
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Jupiter

**Comment by KyleGospo** [comment]
@RodoMa92 That command only restores the desktop icon, to change the default you can do that from KDE settings. You may need to re-log for Dolphin to respect the default change.

**Comment by RodoMa92** [comment]
Doh, I'm dumb. Found in default applications in settings. Thanks @KyleGospo, all good now. Closing.

**Comment by KyleGospo** [comment]
> Doh, I'm dumb. Found in default applications in settings. Thanks @KyleGospo, all good now. Closing.

I'll add a note after that command runs about that
