### ISSUE TITLE
Adding another disk/partition to fstab breaks boot

### ISSUE THREAD

**Issue by rcarmo** [ublue-os/bazzite#700]
### Describe the bug

When I added a second volume (for my game library) to /etc/fstab, the system went into a boot loop and I was unable to login as root.

(the mistake was due to the fact that I cannot use Gnome Disks to set a mountpoint and it keeps erroring out - a secondary issue here is that there should be documentation on where I can create a mount point and how I can add a second BTRFS volume without breaking things)

### What did you expect to happen?

I expected to be able to login as root, at least. All I got was "Press Enter to continue" where a rescue prompt should be.

### Output of `rpm-ostree status`

```shell
Cannot take one, system is broken
```

**Comment by TriMoon** [comment]
> Cannot take one, system is broken

Undo the change(s) you did for the `/etc/fstab` modification, and next time try to use systemd-mount units to keep your system bootable...
:vulcan_salute:

**Comment by rcarmo** [comment]
I ended up reimaging the machine.
