### ISSUE TITLE
In gamemode it stays on only 24 hour time even if you tick the option to turn it off.

### ISSUE THREAD

**Issue by zqpvr** [ublue-os/bazzite#706]
### Describe the bug

This happens on steamdeck In gamemode it stays on only 24 hour time even if you tick the option to turn it off.

### What did you expect to happen?

It to be 12 hour time

**Comment by KyleGospo** [comment]
Not able to reproduce here, making as upstream as the clock display is provided by Steam.

**Comment by codevski** [comment]
Same issue here fresh install
