### ISSUE TITLE
Images newer than 20240116 boot to black screen

### ISSUE THREAD

**Issue by janoxakes** [ublue-os/bazzite#708]
### Describe the bug

After updating from 20240116 to 20240122, the login screen no longer appears, instead it shows a black screen. This same behaviour occurred with two upgrades (main installation and a second in a older test install) and also on a fresh new install using the 2.2.0 images.
Secure boot is disabled, using EFI, no layered packages and just configure-nvidia shows nothing to do.

Some image newer than 20240116 managed to boot (enough to see the new terminal application), but after rebooting it stopped working again. I have rebased the new fresh install to 39-20240116 in order to have it functional. Later dates seem to not work.

### What did you expect to happen?

At least fresh install with no modifications should boot to desktop.

### Output of `rpm-ostree status`

```shell
From the current working system on 20240116:

jano@fedora:/var/home/jano$ mokutil --sb-state
SecureBoot disabled
Platform is in Setup Mode
jano@fedora:/var/home/jano$ [ -d /sys/firmware/efi ] && echo UEFI || echo BIOS
UEFI
jano@fedora:/var/home/jano$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:39-20240116
                   Digest: sha256:2ceb3c8b416a75a005bd565dba99c62b995b1dce40a45c5291af0f96b95d4665
                  Version: 39.20240116.0 (2024-01-16T16:56:40Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/nvidia.conf"' 

  ostree-unverified-image:docker://ghcr.io/ublue-os/bazzite-nvidia:39-20240116
                   Digest: sha256:2ceb3c8b416a75a005bd565dba99c62b995b1dce40a45c5291af0f96b95d4665
                  Version: 39.20240116.0 (2024-01-16T16:56:40Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/nvidia.conf"' 

  ostree-unverified-image:docker://ghcr.io/ublue-os/bazzite-nvidia:39-20240116
                   Digest: sha256:2ceb3c8b416a75a005bd565dba99c62b995b1dce40a45c5291af0f96b95d4665
                  Version: 39.20240116.0 (2024-01-16T16:56:40Z)
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 
                   Pinned: yes
```

### Hardware

CPU: i5-6600 CPU
GPU: NVIDIA GeForce RTX 3070
MOBO: ASRock B250M-HDV

### Extra information or context

I believe at some point while trying to rescue the old installation I tried to rebase to the branch I am currently using and didn't work (still blank screen). 
I can get rpm-ostree status for latest if required

**Comment by KyleGospo** [comment]
Try the latest build, this may be fixed. Issue was an upstream change to xwayland for security reason that unfortunately broke patches for explicit sync on nvidia. Newer builds default to X11 on nvidia 545 so this is no longer needed.

**Comment by janoxakes** [comment]
@KyleGospo, latest tag is now working, and survives multiple reboots. There's a message that the nvidia kernel arguments aren't set and will use noveau instead, but it loads just fine.
Closing as seems fixed. 

Thanks!
