### ISSUE TITLE
Add touch keyboard to installer

### ISSUE THREAD

**Issue by bradycodemaster** [ublue-os/bazzite#715]
cant contue instaler without keyboard please add touch keyboard in next reasle

**Comment by KyleGospo** [comment]
We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker

Let us know if you have any issues with the new one :)

**Comment by 123wfrwe** [comment]
> We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker
> 
> Let us know if you have any issues with the new one :)

**Comment by joacofrate00** [comment]
I see this has been closed as completed. How can we enable the virtual keyboard during install? I'm asking for the ROG Ally specifically.

**Comment by JSmaler** [comment]
Yea, this is not fixed at all.
Marking it fixed was a mistake.
 There still is no way to install Bazzite on a steam deck without a hole heap of dongles to connect a keyboard, which naturally exponentially reduces Bazzites accessibility to the normal user, that may not have a USB hub at hand.
