### ISSUE TITLE
bazzite-flatpak-manager won't work if flathub remote is not present

### ISSUE THREAD

**Issue by hanipaganda** [ublue-os/bazzite#716]
If bazzite-flatpak-manager cannot find a flathub system remote, it won't add it automatically.
It's not a bug but maybe a missing feature.
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

**Comment by KyleGospo** [comment]
Is this a custom image? The other setup scripts should always add that repo.

**Comment by hanipaganda** [comment]
I'm using kinoite rebased to bazzite.

**Comment by hanipaganda** [comment]
Just did another test.
Deleted all programs, deleted flathub system remote and deleted flathub user remote.
Tried to run bazzite-flatpak-manager  and got this error:

```Flatpak manager v17 has already ran. Exiting ...```

Sometimes, I don't even get that error and it prints:

```cat: /etc/bazzite/flatpak_manager_version: No such file or directory
error: Remote "flathub" not found in the system installation```

but the results are the same: No system flathub remote added in both ocassions.

In both ocassions, I don't have any other option than adding flatpak system remote by myself manually.
If by some reason  ```Flatpak manager v17 has already ran. Exiting ...``` is shown: I have to do `$ sudo rm /etc/bazzite/flatpak_manager_version`. And then of course add flathub system remote manually.

**Comment by hanipaganda** [comment]
Just tested the new commits. Removed all the programs, deleted all remotes (system and user), did a reboot and found out:
Flathub system remote was added and flatpaks were installing automatically. And flathub user remote was also added automatically.

Seems everything is working now. Thank you @KyleGospo

**Comment by KyleGospo** [comment]
Beat me to notifying you, glad to hear it! No idea why flathub wasn't in /etc for you since we explicitly add it, but that's the nature of writable partitions, so at least those safety checks will keep things going smoothly.
