### ISSUE TITLE
Flickering with some apps

### ISSUE THREAD

**Issue by Infer4Y** [ublue-os/bazzite#719]
### Describe the bug

When i launch minetest or other aplications that might try to use hardware acceleration the window or app flickers

### What did you expect to happen?

I'd expect semi smooth or non flickering windows

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:1401010b60153adf5ffa66dfb7bf3de5baeaf7d997e412047908d47a2fb2ba69
                  Version: 39.20240116.0 (2024-01-28T08:35:49Z)
                     Diff: 6 upgraded
          LayeredPackages: neofetch
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:f238621e1640dc44eec5b48f2b05495f1bbcf6c3acd132e428962e915ae81db9
                  Version: 39.20240116.0 (2024-01-27T22:12:24Z)
          LayeredPackages: neofetch
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

  ostree-unverified-image:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:f238621e1640dc44eec5b48f2b05495f1bbcf6c3acd132e428962e915ae81db9
                  Version: 39.20240116.0 (2024-01-27T22:12:24Z)
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"'
```

### Extra information or context

R9 7950x
96 GB of ddr5 ram
evga 3060 12GB

**Comment by KyleGospo** [comment]
Switch to X11 on Nvidia, 545 has issues with Wayland that need to be fixed upstream.

**Comment by Infer4Y** [comment]
How might I do that? Not used to messing with nvidia on linux as much.

**Comment by Infer4Y** [comment]
Found it at the bottom left to switch to x11. Blanked out my screen for a little bit.

**Comment by Infer4Y** [comment]
Switching to the x11 side stopped having a video out in general so unfortunately I couldn't get any information out of it

**Comment by angeluserrare** [comment]
> There's a new Beta from Nvidia, it might fix Wayland. Or it might not. It's Nvidia. But its worth a try

What's the proper way to update the driver on bazzite?

**Comment by KyleGospo** [comment]
> > There's a new Beta from Nvidia, it might fix Wayland. Or it might not. It's Nvidia. But its worth a try
> 
> What's the proper way to update the driver on bazzite? 

Since it's part of the image, you can't. 550 should hit RPM Fusion soon.

**Comment by achengli** [comment]
I have the same issue but I'm not using Nvidia drivers since I am using Bazzite on my steam deck. Randomly, when I'm watching a Youtube video, it starts flickering showing the same frames like a glitch for about 5 to 10 seconds

I'm using Wayland too and I am not wondering switching to X11
