### ISSUE TITLE
Login delay before input works (Bazzite GNOME)

### ISSUE THREAD

**Issue by another-sapiens** [ublue-os/bazzite#727]
### Describe the bug

 After booting the system, when the Login screen shows up, there is a 5-10 second delay before the mouse or keyboard can be used to select the user and input the password.

The pointer is not visible during this delay, either.

### What did you expect to happen?

Mouse and keyboard work as soon as GDM shows up; the user can be selected immediately.

### Extra information or context

This happened in a fresh rebase from vanilla Silverblue (soon after install). It did not occur before.

After rebasing to `ghcr.io/ublue-os/silverblue-main:latest`, the issue is gone.

Everything else in Bazzite was working perfectly.

**Comment by KyleGospo** [comment]
This is a feature of Steam Input, same delay occurs during startup of steam on KDE and in SteamOS.

**Comment by another-sapiens** [comment]
Thanks for your quick response. Is there a way I can change this on my system?

**Comment by KyleGospo** [comment]
> Thanks for your quick response. Is there a way I can change this on my system?
> 
> Edit: Strange, I saw an answer stating it was due to Steam Input, but I can't see it anymore. It disappeared.

Sorry about that, that was me. I had missed the part about this happening during login so it was not applicable to you.

I'm going to see if I can reproduce this and get back to you

**Comment by another-sapiens** [comment]
It should be noted I'm not using a Steam Deck or a powerful gaming device, just a regular desktop PC.

**Comment by Juno-ko** [comment]
I have this exact same problem with my laptop. Fresh Bazzite installation.
