### ISSUE TITLE
Virtual Keyboard not working ROG Ally

### ISSUE THREAD

**Issue by LegendaryURZU7** [ublue-os/bazzite#730]
### Describe the bug

There is currently no way to access the virtual keyboard on KDE Bazzite Ally ISO. i tried enabling it through system settings and nothing shows up.

### What did you expect to happen?

i expected to tap on a search icon and have a virtual keyboard pop up but for whatever reason its not working

### Output of `rpm-ostree status`

```shell
ROG Ally RC71L_RC71L
```

### Hardware

                 Digest: sha256:69c64cdf05aedfdd4bce0c7cb0339030581ccb39d24edf1d78398c0531df8a71
                  Version: 39.20240131.0 (2024-02-01T15:23:51Z)
                     Diff: 3 upgraded, 37 added
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:latest
                   Digest: sha256:952c0115f4ab83ebddca3f72117e816fbeb38526695ae0d1b67e1d10c792cb93
                  Version: 39.20240131.0 (2024-02-01T07:35:48Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:latest
                   Digest: sha256:c34c4bc9fee9b00fd57aa5f1e04c5ebf7cb92c0451df0105390704615d72c823
                  Version: 39.20240130.0 (2024-01-31T05:46:41Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'

**Comment by frohrbaugh** [comment]
@KyleGospo Hi Kyle appreciate all the help and support. I tried to read through the documentation. 

I just wasn't sure, if I installed bazzite+kde on a Rog ally is it not possible to get steam keyboard? 

I guess the question is it possible to use steam keyboard with HHD and bazzite? Apologies still learning the OS and its dependencies/plugins.

**Comment by KyleGospo** [comment]
The Ally has a hardware limitation that requires you to press Steam and then X, rather than Steam plus X

**Comment by frohrbaugh** [comment]
Thank you! I appreciate the knowledge. Have a great weekend and I'll do just that.

**Comment by Black-Seraph** [comment]
@KyleGospo what hardware limitation are we talking about here? 

Any information out there what the actual problem is? 

Having worked with uinput before I see no reason why multiple split devices can't just be merged by spawning a helper device.

**Comment by diggerdu** [comment]
> The Ally has a hardware limitation that requires you to press Steam and then X, rather than Steam plus X.
> 
> I would also ensure your desktop binds in Steam have just pressing X as open keyboard.

Which button of ROG ALLY is steam button?

**Comment by keefeere** [comment]
https://github.com/keefeere/vboard for desktop mode
