### ISSUE TITLE
Genesis Plus GX under RetroDeck causing reboots on Steam Deck?

### ISSUE THREAD

**Issue by ErroneusMonk** [ublue-os/bazzite#733]
### Describe the bug

When playing Sonic 2 & Knuckles under retrodeck using Genesis Plus GX, if "Interlaced mode 2 output" is changed to Double Field, The emulator, and system has frozen, then rebooted after about 10 seconds multiple times. 

It seemed to have stopped, after multiple attempts at changing the option, but I still feel a report is warranted.

### What did you expect to happen?

Being able to change the interlaced output without it rebooting

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39
                   Digest: sha256:b985b8141f5a5f96eb895a2428f6265450944d5f8eb94977fdf5b3ff575df294
                Timestamp: 2024-02-01T15:23:32Z
                Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf'

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39
                   Digest: sha256:3899a7b5bacd5419656c2008c938b93d2789499939b7a49874b52cff9fb35876
                Timestamp: 2024-01-31T05:45:08Z
                Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf'
```

### Hardware

Jupiter

### Extra information or context

I'm on the latest version of RetroDeck and bazzite, as I ran ujust update today, but I'm unsure as to what is causing this. It's also happened when I ran nested desktop to run Firefox while playing Yakuza Kiwami 2.

**Comment by ErroneusMonk** [comment]
Starting to see a trend now. It seems If I do anything that puts a load on the GPU, the screen will at times, randomly go blank twice, freeze, then eventually reboot. I have powertools installed, and have profiles set for most applications I use, so I'm not discounting that as a possibility, but it has only started happening recently. 

Could it be an issue with an update, powertools, or a driver issue? I don't know how to do a btrfs rollback to see if it was an update.

**Comment by KyleGospo** [comment]
Run an `rpm-ostree update` for me and let me know if this still occurs.

**Comment by ErroneusMonk** [comment]
Disabled powertools, and ran the update. Hasn't happened yet after trying out multiple games. Get to do the shoot part of troubleshooting now. Should I close this?

**Comment by KyleGospo** [comment]
No rush, feel free to leave it open until you're totally satisfied. We're in no hurry here

**Comment by ErroneusMonk** [comment]
Did some more troubleshooting, and wound up remembering I had an undervolt applied. I had the igp at -50mv, so I backed it down to -40. In conjunction with the update, all seems fine.

It just seemed odd that this hasn't been an issue until a couple days ago, so that slipped my mind.
