### ISSUE TITLE
gamescope: Update or backport patches to fix crash on HTPCs

### ISSUE THREAD

**Issue by nadiaholmquist** [ublue-os/bazzite#735]
### Describe the bug

In the version of gamescope you are currently shipping, there is a bug that causes it to crash on wake from suspend on some systems (likely mainly HTPC use-cases) because of two minor oversights in some of the code that gathers display info.

This has been fixed since that version, so it would be greatly appreciated if you could either upgrade gamescope or backport the patches I've linked below.

### What did you expect to happen?

When waking from sleep, gamescope should not crash.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:d7f7f74a7f42c1bdba8638f36d668f19ba28f3b066b58df54f99c23eb135609e
                Timestamp: 2024-02-02T02:33:18Z
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'

  ostree-unverified-image:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:d7f7f74a7f42c1bdba8638f36d668f19ba28f3b066b58df54f99c23eb135609e
                Timestamp: 2024-02-02T02:33:18Z
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Desktop PC, connected to a TV

Intel Core i5-6600K
AMD Radeon RX 6650 XT
32 GB RAM

### Extra information or context

https://github.com/ValveSoftware/gamescope/commit/0868a4ab5e763b7e23ad97a84792a4fe60b0a74d
https://github.com/ValveSoftware/gamescope/commit/b0ce622a8ef095796daeb98f7882e19ba7d4f994
These are the relevant commits that fix the issue so you can backport them if there are reasons that you are not able to upgrade to a newer version.

**Comment by KyleGospo** [comment]
Great catch! Have this live soon, newer version is in the pipe and should launch once the crash with newer Xwayland is fixed
