### ISSUE TITLE
Cannot select CA certificate when installing and configuring wifi

### ISSUE THREAD

**Issue by FredsMedia** [ublue-os/bazzite#736]
### Describe the bug

When I go to configure the wifi in the installer, I need to use a CA certificate. However I cannot mount any drives to select the certificates.

### What did you expect to happen?

I expected to plug in a USB and it automatically mount it so I can select the required certificate to set up the network

### Output of `rpm-ostree status`

```shell
Cannot run as I cannot install
```

### Hardware

Cannot run as I cannot install

### Extra information or context

I have only tried fat32 drives (could potentially be the issue) and I’ve tried both on my steam deck and an old laptop that was sitting around. I cannot use Ethernet and this is the only wifi I can connect to.

**Comment by KyleGospo** [comment]
We are working on a new installer, in the meantime I would recommend installing stock Silverblue or Kinoite and then rebasing since they don't need an internet connection.

**Comment by FredsMedia** [comment]
Thanks Kyle, would there be an ETA on this new installer, and how would it differ from the current one?

**Comment by KyleGospo** [comment]
We now have a new offline installer that can be downloaded at https://bazzite.gg/#image-picker

Let us know if you have any issues with the new one :)

**Comment by FredsMedia** [comment]
Ooh wonderful, I’ll try it out and let you know how it goes!

**Comment by FredsMedia** [comment]
@KyleGospo I do have an issue actually. I’ve posted it under a separate issue (#808)
