### ISSUE TITLE
Internal screen frozen and no signal on external screen when docked in gaming mode

### ISSUE THREAD

**Issue by pippaine** [ublue-os/bazzite#738]
### Describe the bug

The first time the device is plugged in after entering gaming mode, this sequence will occur:
* The internal screen will flash black for about 2 seconds
* The internal screen may be controllable for about 2 seconds before the image freezes

Subsequent times it is plugged in:
* The image on the internal screen will freeze for about 2 seconds
* The UI elements will briefly jitter, as if rapidly changing resolution
* The internal screen is controllable for about 2 seconds before the image freezes

The external screen will display no signal at any point during or after these sequences.
UI sounds can be heard if you attempt to navigate the UI while the image is frozen.

### What did you expect to happen?

The external screen should display a signal.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:e784647f8bbd589fa73c26a28a004ee2bc9e5785a75801e4fbf60acc271eb4eb
                Timestamp: 2024-02-02T02:27:47Z

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:e784647f8bbd589fa73c26a28a004ee2bc9e5785a75801e4fbf60acc271eb4eb
                Timestamp: 2024-02-02T02:27:47Z
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Steam Deck OLED
Steam Deck™ Docking Station

```
$ cat /sys/devices/virtual/dmi/id/product_name
Galileo
```

### Extra information or context

This issue does not occur when using my Steam Deck LCD with SteamOS.

Workaround:

1. Enter desktop mode
2. Plug the device into the docking station
3. Wait for a display signal on the external monitor
4. Enter gaming mode

After unplugging the device, the workaround will need to be repeated.

Running `rpm-ostree reset` and restarting the device did not affect the bug.

**Comment by pippaine** [comment]
The issue seems to be intermittent. I've attempted docking to my external display many dozens of times after some updates and just twice it did work as expected. I've ordered a JSAUX dock (HB0603) to see if the issue is specific to the official docking station.

**Comment by Saghen** [comment]
I hit a similar issue with external screens not connecting, although the internal screen acted a bit different than what you're describing. The following thread helped me find a workaround on my Samsung Smart TV: https://www.reddit.com/r/SteamDeck/s/p61DtjD0op

> For everyone having this issue, try plugging in the deck to dock with only the HDMI plugged in and no power cable. This worked for my TCL TV. Once the screen screen shows on the TV, you can plug the power cable back in and it should still work

**Comment by jipiboily** [comment]
Same issue with my Legion Go.

```
deck@fedora:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39-20240220
                   Digest: sha256:cd910c16932197ac6a7c646da4a48d7b0fc7f5dbd60b04d34963d2841fad5edc
                  Version: 39.20240220.0 (2024-02-20T17:01:39Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:248148043bcaf46be5a318e2d706350ce84a893cae296ff14fa247d87a7528ba
                  Version: 39.20240226.0 (2024-02-27T00:26:49Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 
deck@fedora:~
```
