### ISSUE TITLE
Proton 8 and Proton Experimental will not launch anything

### ISSUE THREAD

**Issue by pippaine** [ublue-os/bazzite#740]
### Describe the bug

When selecting Proton Experimental or any variant of Proton 8 (incl. 8GE) as the compatibility layer, any game I have tried will fail to launch. This issue occurs in both gaming mode and desktop mode.

### What did you expect to happen?

Compatible games should run

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:e784647f8bbd589fa73c26a28a004ee2bc9e5785a75801e4fbf60acc271eb4eb
                Timestamp: 2024-02-02T02:27:47Z

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:e784647f8bbd589fa73c26a28a004ee2bc9e5785a75801e4fbf60acc271eb4eb
                Timestamp: 2024-02-02T02:27:47Z
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Steam Deck OLED

```
$ cat /sys/devices/virtual/dmi/id/product_name
Galileo
```

### Extra information or context

This issue does not occur on my Steam Deck LCD with SteamOS

Workaround:

* Use a version of Proton 7 or lower.

**Comment by nadiaholmquist** [comment]
I'm pretty sure I have this same issue on an HTPC with a RDNA2 GPU connected to an HDR TV. If HDR is enabled, any game using Proton will fail to launch.

**Comment by KyleGospo** [comment]
Try adding `DXVK_HDR=0` and `ENABLE_GAMESCOPE_WSI=0` to `/etc/environment` and see if that fixes it.

**Comment by nadiaholmquist** [comment]
Doesn't seem to work around it in my case.

**Comment by pippaine** [comment]
Nor mine

**Comment by jcll** [comment]
Having this issue as well.
