### ISSUE TITLE
[SecureBoot] Unable to boot after BIOS update.

### ISSUE THREAD

**Issue by TriMoon** [ublue-os/bazzite#741]
### Describe the bug

I just had to update my motherboards BIOS, and after that i got an error from `grub` telling me i need to load the kernel first.
This is ofcourse due to the fact that all MOK keys were cleaned by the BIOS update.

### What did you expect to happen?

Someway to easily re-emport the MOK-Keys used via the mok manager at boot.
Both for the Kernel itself and the dkms modules like nVidia drivers.

### Extra information or context

The above problem, although not a common but surely one that will popup sooner or later for most users, made me aware of a weak point of the `uBlue` system.

I would propose that these MOK-keys are installed inside the ESP alongside the kernels, so the user can easier find and r-import them again in such cases.
Be it using the Mokmanager or via `mokutil` from any Live-ISO...

**Comment by KyleGospo** [comment]
This was solved in discord. For others, disable secure boot and re-enroll the key with ujust before enabling it.
