### ISSUE TITLE
Updates for Bazzite have been stale for a while now

### ISSUE THREAD

**Issue by td5038** [ublue-os/bazzite#742]
### Describe the bug

When I expect an updated image, I only get a stale one from Jan. 16th.

### What did you expect to happen?

I expected a recent update, but got a stale one instead.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-asus-nvidia:latest
                   Digest: sha256:d257cabe24bbdb73a04306dd7baa282247875603d6fc0ede221cdf506345a5b1
                  Version: 39.20240116.0 (2024-02-02T02:28:01Z)
          LayeredPackages: lld openrazer-meta python-devel razergenie
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-asus-nvidia:latest
                   Digest: sha256:d257cabe24bbdb73a04306dd7baa282247875603d6fc0ede221cdf506345a5b1
                  Version: 39.20240116.0 (2024-02-02T02:28:01Z)
          LayeredPackages: lld openrazer-meta python-devel razergenie
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

```

### Hardware

I am using a lenovo 15ach6

### Extra information or context

I have layered packages installed.

**Comment by td5038** [comment]
@KyleGospo did you forget to update PipeWire in the bazzite repos?

**Comment by castrojo** [comment]
The images are still publishing normally so not sure what's going on there: https://github.com/ublue-os/bazzite/pkgs/container/bazzite-asus-nvidia

**Comment by td5038** [comment]
Maybe look at recent GitHub Actions runs?

**Comment by td5038** [comment]
I'll grab the output from the latest one now

**Comment by td5038** [comment]
Maybe it was a temporary issue

**Comment by td5038** [comment]
Sorry for wasting your time

**Comment by td5038** [comment]
Closing due to mis-ID
