### ISSUE TITLE
Solaar's .desktop file does not accept arguments when installed via ujust

### ISSUE THREAD

**Issue by MonkeyCrumpets** [ublue-os/bazzite#744]
### Describe the bug

When running Solaar installed via `ujust install-solaar` from its .desktop file, any flags entered into the "Arguments" field (in my case `--window=hide`, so I can have it autostart cleanly) fail to apply. 

I assume this is due to the fact that it runs from a Distrobox container? As a workaround I installed it as a layered package and it works as expected.

### What did you expect to happen?

The `--window=hide` argument should make Solaar hide its' GUI on startup.

### Output of `rpm-ostree status`

```shell
~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:6b8f9409ca74161bf28640b9c8ea0b0eb6f96762ac9a29124e64402cf183d0e9
                  Version: 39.20240116.0 (2024-02-04T00:09:55Z)
          LayeredPackages: solaar
            LocalPackages: sunshine-0.21.0-1.x86_64
                   Pinned: yes

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:6b8f9409ca74161bf28640b9c8ea0b0eb6f96762ac9a29124e64402cf183d0e9
                  Version: 39.20240116.0 (2024-02-04T00:09:55Z)
```

**Comment by KyleGospo** [comment]
ujust installs it as a layer now instead, can you confirm yours is still in distrobox so I can give tips on where to go from here?

**Comment by MonkeyCrumpets** [comment]
I just went to reproduce and realised I forgot to wrap `solar --window=hide` in quotes because its nested as an argument for `distrobox-enter`.

`distrobox-enter -n fedora -- /bin/sh -l -c 'solaar --window=hide'` functions as it should. Marking as closed...
