### ISSUE TITLE
Add a ujust command to have the same desktop experience as silverblue

### ISSUE THREAD

**Issue by yodatak** [ublue-os/bazzite#746]
### Describe the bug

I want to have vanilla gnome experience but when i rebase to bazzite i got the hot corners disable 

### What did you expect to happen?

Have a possiblity to just have a silverblue vanilla plus gaming addons and if people want more tweak enable them

**Comment by KyleGospo** [comment]
Hot corners are disabled in favor of hot edge, apply pressure to the bottom of your screen with your mouse -- you may prefer that workflow as I have.

If you want the default behavior, re-enable hot corners in settings:
![image](https://github.com/ublue-os/bazzite/assets/10704358/71297e21-04c8-4fdc-bcc9-8dca1683147b)

And disable hot edge in Extension Manager:
![image](https://github.com/ublue-os/bazzite/assets/10704358/17c3539b-88fb-40c4-b240-1a54efbaa914)
