### ISSUE TITLE
[gnome-nvidia] Anyway to Reimplement the Nvidia Patches?

### ISSUE THREAD

**Issue by JoshuaMacklin** [ublue-os/bazzite#752]
### Describe the bug

As a wayland user and more specifically a X11 avoider (for security concerns), is there anyway to reimplement the [Nvidia Patchs](https://github.com/ublue-os/bazzite/commit/57d87bc6bc6d9f03f0bb0aec971c4e68dd4bd784)? These patches were the only thing that kept my wayland session on the Nvidia 545 driver from flickering, now that its been removed, I hope theres a way to bring it back, maybe using Just or perhaps a package I can install.

### What did you expect to happen?

No gpu flickering on wayland

**Comment by KyleGospo** [comment]
This is now present once again in the latest builds

**Comment by craigers521** [comment]
@KyleGospo just updated to latest stable gnome nvidia with bazzite 3.0 / fedora40 and the flickering is back.  Steam UI is especially bad but its happening a bit in game as well.  Before i rollback i just wanted to check to see if those patches for wayland were still in the new build or if mutter is having some issue

**Comment by KyleGospo** [comment]
It's going to be broken until Nvidia fixes it mid-may, the patches we previously included were upstreamed and are still included.
