### ISSUE TITLE
Dual GPU

### ISSUE THREAD

**Issue by FML128** [ublue-os/bazzite#757]
### Describe the bug

I have a Intel iGPU (for quicksync) and a AMD RX 7900 XT.
Gamescope seems to be running on the Intel iGPU.

`glxinfo | grep 'OpenGL renderer'` does return the correct AMD gpu.

I run the bazzite-deck image

### What did you expect to happen?

That gamescope and games would run on the dGPU

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:26353d54cc504fb318a98bfe3eca6e68addc70603b15b368ed65f45ef535ec5d
                  Version: 39.20240209.0 (2024-02-10T04:36:23Z)
          LayeredPackages: htop intel-gpu-tools
            LocalPackages: lact-0.5.2-0.x86_64 sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:26353d54cc504fb318a98bfe3eca6e68addc70603b15b368ed65f45ef535ec5d
                  Version: 39.20240209.0 (2024-02-10T04:36:23Z)
          LayeredPackages: intel-gpu-tools
            LocalPackages: lact-0.5.2-0.x86_64 sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

MINISFORUM AR900i - Intel Core i9 13900HX
AMD RX 7900 XT

**Comment by KyleGospo** [comment]
`/usr/bin/export-gpu` is included in gamescope-session for this purpose.

**Comment by FML128** [comment]
Sadly this does not seem to work.  Or to be exact, it might work for gamescope. It shows the process on the intel GPU, but no noticeable utilisation, so gamescope could be running on the AMD GPU. Do you know of a way to check on what it is currently running?
However, depending on which game I try to start it will still use the iGPU.
For example Hogwarts Legacy starts on the iGPU, Sackboy launches on AMD. Both are using Proton.

**Comment by Jan200101** [comment]
That is odd.
Do you have more information available about those two games, like which Rendering API they use, etc.
The output of `vulkaninfo | grep -A 1 deviceType` would also be helpful to know what type mesa has assigned your devices.

**Comment by FML128** [comment]
Sure:

Both games run on Unreal Engine 4 with DirectX 12.


`vulkaninfo | grep -A 1 deviceType`
```shell
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib64/libvulkan_nouveau.so supports Vulkan 1.3, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Manifest ICD for "/usr/lib64/libvulkan_nouveau.so" contained a 1.1 or greater API version, but vkEnumerateInstanceVersion returned 1.0, treating as a 1.0 ICD
        deviceType        = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName        = AMD Radeon RX 7900 XT (RADV NAVI31)
--
        deviceType        = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName        = Intel(R) Graphics (RPL-S)
```

**Comment by Jan200101** [comment]
Alright.
Since the game uses DX12 it probably uses vkd3d, which appears to have fixed this relatively recently (https://github.com/HansKristian-Work/vkd3d-proton/issues/1809).

Could you try with [GE-Proton8-32](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton8-32)?

**Comment by FML128** [comment]
I just tried multiple versions of proton, including experimental. It still used the iGPU.

**Comment by SamlRx** [comment]
Not sure if that's relevant in your case, but did you try to disabled your laptop screen and only output on the screen connected to your egpu ?

**Comment by FML128** [comment]
It isn't a Laptop. However, the HDMI is directly connected to the dGPU and this is the only video output.

**Comment by TriMoon** [comment]
https://github.com/ublue-os/bazzite/issues/757#issuecomment-1947418541, this is interesting, because i have a different order...
_(In my case i have a AMD iGPU and nVidia dGPU)_
```
$ vulkaninfo | grep -A 1 deviceType
	deviceType        = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName        = NVIDIA GeForce GTX 1080 Ti
--
	deviceType        = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName        = AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)
```
