### ISSUE TITLE
how do i get the iso?

### ISSUE THREAD

**Issue by figsgksss** [ublue-os/bazzite#760]
### Describe the bug

how to get the iso

### What did you expect to happen?

i tought that the iso was here but its not here

**Comment by SamlRx** [comment]
It's written in the front page of this repo.

You can find it here in the release page : https://github.com/ublue-os/bazzite/releases

The latest ISO can be downloaded here : https://github.com/ublue-os/bazzite/releases/download/v2.2.0/bazzite-39-x86_64-20240119.iso
