### ISSUE TITLE
Broken gyro support for ROG Ally

### ISSUE THREAD

**Issue by so1ar** [ublue-os/bazzite#767]
### Describe the bug

First of all, thank you all for the amazing work. When I first installed bazzite on my ROG Ally, everything works perfectly including back buttons and gyro. But the gyro has been broken since recent updates. I suspect this happens due to kernel 6.7 update.

### What did you expect to happen?

Gyro works as intended.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:stable
                   Digest: sha256:7a6928058d13ad1e20cd7df1671098b435d6ad853dfed4b12eadb355e4df61e0
                  Version: 39.20240212.0 (2024-02-13T01:41:49Z)
          LayeredPackages: deluge v2raya
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:stable
                   Digest: sha256:719a78c37f255eb7f6a84362f7c25d74f61a71c5a06abe3cc79f8eeda2d7c235
                  Version: 39.20240210.0 (2024-02-11T07:14:43Z)
          LayeredPackages: deluge v2raya
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Asus ROG Ally with latest version of bios and without any modding except 2TB SN740 SSD replacement.

**Comment by KyleGospo** [comment]
We'll check into it, for the time being you can rebase to the previous kernel by date, or by pinning the previous deployment if you just updated.

**Comment by so1ar** [comment]
Just updated bazzite a few minutes ago, and the gyro works again.
