### ISSUE TITLE
[Steam Deck OLED] Always boots to unresponsive black screen

### ISSUE THREAD

**Issue by pippaine** [ublue-os/bazzite#771]
### Describe the bug

The system will boot into one of two states:

1. Black screen with a single white "_" (underscore) character in the top left. Other TTYs cannot be accessed in this state -- any keyboard or gamepad inputs do not do anything. The system is still accessible through SSH.

2. Black screen with no underscore character i.e. completely blank. Other TTYs can be accessed in this state, but attempting to run `steamos-session-select plasma` or `gamescope` causes the screen to freeze and the system to become unresponsive to any keyboard or gamepad inputs. The system is still accessible through SSH.

Once, after running `ujust toggle-autologin`, `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:39-20240205`, `systemctl reboot`, the system entered this state:

3. Black screen with no underscore character i.e. completely blank. Other TTYs can not be accessed in this state. The system is not accessible through SSH.

The system returned to intermittently booting between states 1 and 2 after three force-shutdowns.

### What did you expect to happen?

I expect the system to be accessible in gaming mode upon startup.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:cc09fb538f3d06d1d62b12733e43f06b53ab305c5733c0bc04ca73dbdbb87f7c
                  Version: 39.20240213.0 (2024-02-14T09:29:32Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:39-20240214
                   Digest: sha256:cc09fb538f3d06d1d62b12733e43f06b53ab305c5733c0bc04ca73dbdbb87f7c
                  Version: 39.20240213.0 (2024-02-14T09:29:32Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Steam Deck OLED

```
$ cat /sys/devices/virtual/dmi/id/product_name
Galileo
```

### Extra information or context

I do not know a workaround for this issue. My device has been rendered completely unusable.

I noted this issue first about 16 hours ago. In the ~24 hour period between when:
1. I last used the device in a working state
2. I first experienced the issue after running `ujust update` then `systemctl reboot`

the device sat on my desk undisturbed.

I have tried restarting the system after running the following commands:

* `ujust update` on `bazzite-deck-gnome:latest`
* `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:39-20240214`
* `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:39-20240213`
* `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:39-20240212`
* `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:39-20240205`
* `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39-20240214`
* `rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39-20240205`

The issue persisted across every version. This is particularly odd, because the device did not have this issue on 39-20240212 and prior.

Running `gamescope` in tty2 provides this output before the screen freezes:
```
vblank: Using timerfd.
wlserver: [backend/headless/backend.c:67] Creating headless backend
wlserver: [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
_
```

**Comment by KyleGospo** [comment]
I am not successful in reproducing this on my OLED, I'll see if I can get any other hardware to do it.

**Comment by pippaine** [comment]
Thanks. I'm baffled by this issue. I've spent some man-hours trying to inspect further into this but never really got anywhere since I lack domain knowledge

Fortunately I've at least figured out a workaround to un-brick my device.

To enter gaming mode from ttyN:

```
gamescope-session-plus steam
```

To enter desktop mode from ttyN:

```
XDG_SESSION_TYPE=wayland dbus-run-session gnome-session
```

"Switch to Desktop Mode" and "Return to Gaming Mode" buttons no longer work so this requires plugging in a keyboard to return to tty but I was able to launch a game and adjust audio with device buttons.

**Comment by pippaine** [comment]
User Alex&Indie on the #bazzite discord channel notes this same issue happening on their LCD model

**Comment by sean-work** [comment]
I'm on the discord as bear.fox, I'm having the same issue as above on my LCD Deck. Been on Bazzite since August last year. I was on a December or January bazzite-deck build before I decided to system update via gamemode system settings. Since I have had a black screen or blank tty. I can use the controls to navigate menus and boot into desktop mode. I have tried rollbacks and a rebase to bazzite-deck39:20240113.0 (used the exact command from the docs actually). Unfortunately the issue still prevails. Here is my .gamescope-stdout.log 
https://pastebin.com/5ePZB3UP

Thanks for your time.

**Comment by sean-work** [comment]
On a cold boot after rebasing to the Jan 13th build, I'm actually getting a message that Jupiter fan control service failed to start. I  unhid grub and am able to boot into the more recent deployment build released yesterday, but the black screen gamescope issue persists.

**Comment by sean-work** [comment]
Upgraded to latest build (24th Feb), same behavior. Debased to 5th Feb build, same behavior. Disabled decky loader, same behavior.

I have found that if I enter desktop mode via blind menu navigation or tty, then from there the .desktop file to return to gamemode will consistently load gamescope/gamemode successfully.

**Comment by dnkmmr69420** [comment]
I am having issues with this as well

**Comment by dnkmmr69420** [comment]
A reinstall reduced this error happening dramatically. It only appears once in a while.

**Comment by Kidswiss** [comment]
I also have this issue on an all AMD PC.

However it seems to happen a lot more with DisplayPort than with HDMI. I'm using the deck-gnome image.
