### ISSUE TITLE
Feral Gamemode is missing?

### ISSUE THREAD

**Issue by Mastodonot** [ublue-os/bazzite#777]
### Describe the bug

After the latest update and reboot, I found that every game on Steam using "gamemoderun %command%" ceased to work.
When I look into it further in the terminal using `gamemoded -t` the results is `gamemoded -t: Command not found.` , as if it was never installed.

This happens on both Bazzite-default installed on the desktop and can also be reproduced on Bazzite-GNOME-NVIDIA on the laptop.

### What did you expect to happen?

"Feral Gamemode" would remain installed and run as intended.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:latest
                   Digest: sha256:07a393a7468f0eded7799307d4dab26cabe20eadb8bfd2fbae77efe00309e726
                  Version: 39.20240215.0 (2024-02-16T08:55:11Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:latest
                   Digest: sha256:bd8c0a989ccf538cb388adefd7d66aa6a3bda7d69b1ea4547675e78de3419178
                  Version: 39.20240215.0 (2024-02-15T16:25:44Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"'
```

### Hardware

Desktop:
Intel Arc A770 16GB
Ryzen 5700X

Laptop:
Nvidia 840M
i7-4710MQ

### Extra information or context

"Feral Gamemode" was included in Bazzite by default before updating.

**Comment by KyleGospo** [comment]
It's inclusion was an oversight that affected only desktop images. Feral gamemode is completely replaced by the existence of System76 scheduler and joystickawake, both of which require no manual setup on the part of the end user.

**Comment by Mastodonot** [comment]
Ah, that does explain it.
I'll redo Steam and Heroic then as their settings were preserved from Kinoite, before the image was rebased.

I really appreciate the clarification and will close this as "resolved"!

**Comment by PVermeer** [comment]
> It's inclusion was an oversight that affected only desktop images. Feral gamemode is completely replaced by the existence of System76 scheduler and joystickawake, both of which require no manual setup on the part of the end user.
> 
> You can simply remove that from your launch options.

I'm no expert but I tested some applications with System76 Scheduler as a replacement and they performed significantly worse.

### Example:
I have the moonlight appImage and flatpak on my media center pc. For some reason this system does not perform well with moonlight on high bitrates (40+). It constantly stutters with network errors. Running with gamemode I can stream in 4k with 150 bitrate  with no issues. High performance in gnome-settings also improves streaming.

I tested switching to only the system76 scheduler and assigned them to the a high performance profile. Checked if the profile was applied while streaming. This resulted in the same issues as above.

### Test system
Up to date Fedora 39 Gnome
Kernel 6.7.5
Intel i5-7600K
AMD RX 6500 XT
Asus PRIME z270-P
16GB RAM

### Conclusion
It's my understanding that `gamemode` and `System76 Scheduler` should be able to work together and provide different optimizations as I also found in my test. `gamemode` Boosts my CPU (govenor) and my GPU (if set in gamemode.ini). I don't think `System76 Scheduler` does this. So there are some applications and games that still perform better on certain systems with `gamemode`. I think this CPU aggressively clocks down while streaming thats causing issues.

So in my opinion, again I'm no expert, I think they both have a place in `Bazzite`. There are systems that benefit greatly from gamemode and less from `System76 Scheduler`.

I was thinking of moving to `Bazzite` also for my media center but I prefer not to layer `gamemode`.

I could be doing something wrong, but if not I'm would prefer that gamemode is provide again in `Bazzite`. At least the in the desktop images.

**Comment by shuja-u** [comment]
I can confirm that I've had significantly worse performance in Rocket League since the removal of Feral gamemode.

**Comment by KyleGospo** [comment]
If you want to change the governor you can do so from your desktop environment via PPD, note that setting this to performance mode from the default of balanced can actually lower your performance due to reduced single core performance while the rest of the CPU is clocked higher.

**Comment by nicknamenamenick** [comment]
@shuja-u @PVermeer @Mastodonot Your mileage may vary with this workaround and I hope this doesn't cause other issues, but if you open a host terminal and enter:
```
rpm-ostree Install libgamemode.so.0 libgamemodeauto.so.0
```
Then this should layer Feral Game Mode to your image.  If there are issues with this in the future with updating/conflicts, then I would suggest removing those layers or resetting rpm-ostree with `rpm-ostree reset`.

Someone in our Discord mentioned this method and if you prefer Feral Game Mode, then this _should_ work.

**Comment by PVermeer** [comment]
Hey @nicknamenamenick, @KyleGospo,

Thanks for the response.

I did a little research and I believe that gamemode still has a place in Bazzite, at least without having to layer it. I don't need it at all on my modern AMD gaming system but on older systems it can still significantly boost performance for some applications and games as in my example above with the Intel i5-7600K CPU.
It does set the system to maximum performance (cpu and gpu) which System76 scheduler and Tuned do not. It also allows for start and end scripts to further optimize settings.
Also some games and emulators have integrations with gamemode. Allowing users to use this would be good imo.

A little research revealed that gamemode does not conflict with system76 scheduler as it does different things. It has some overlap by the option to set a nice level but this is disabled by default.

I know bazzite is an opiniated gaming fedora spin but in my opinion it should be up to the user to use gamemode or not, without layering. I would like to ask you to reconsider the decision to completely remove it.

I personally don't use it anymore on my gaming pc, but it would be nice to have the option at my fingertips, at least for the desktop versions. Using the PPD option feels like an unnecessary manual step that also does not set the GPU profile to high and also has to be set back to balanced again. For the GPU I would then need another app to do this automatically.

It would be great to have it as a "if all fails" option.

Anyways many thanks for the work on bazzite, I really love it. It's the first distro where everything just works for gaming.

Thanks!

**Comment by KyleGospo** [comment]
Gamemode directly conflicts with system76-scheduler due to them fighting over nice values, the only feature of gamemode that would be missing is the CPU governor change which I believe to be an anti-feature due to the mentioned drop in single threaded performance.

We will always support people layering packages for those that desire to use gamemode over system76 for one reason or another. My recommendation in that case is to disable the system76 scheduler entirely.
