### ISSUE TITLE
HHD - Desktop Steam Input Profiles

### ISSUE THREAD

**Issue by rawdatafeel** [ublue-os/bazzite#778]
### Describe the bug

I am using HHD on a ROG Ally and desktop controls are not configured out of the box in Desktop Mode. 

The Steam Deck includes a Steam Input profile that allows you to hold start to flip between desktop and gamepad configs. The Steam Deck configs also include pressing `X` for a virtual keyboard and a couple of other neat button combos. 

Since HHD encompasses three types of configs (Dualsense, Dualsense Edge, and Xbox) and these configs apply to any handheld device using HHD, Bazzite could ship a desktop Steam input profile for these three types allowing for OOTB desktop configs.

I exported one of my Steam input profiles and it looks like it landed in `~/.local/share/Steam/steamapps/common/Steam Controller Configs/<STEAMID>/config/413080/`

If 413080 is a static number for desktop configs, I'm guessing the only non-static number is the STEAMID. 

If there is a way to automatically copy these profiles for devices using HHD to the 413080 folder and there is interest from the Bazzite team, I can upload a set of configs that mirror the Steam Deck configs. 

### What did you expect to happen?

Desktop configs

**Comment by KyleGospo** [comment]
If you can upload those I will definitely take a look. Thanks!

**Comment by jonfive** [comment]
just installed, working on finding out what the default buttonmaps and combinations are. This is less of an issue and more me trying to figure out how things work here:

When you're talking about desktop mode, are you talking about holding down the button just above the right stick and below the 3line start button? 

It seems like when i enable (press and hold) that i get the mouse to work, but all of the other buttons change. Like to open the keyboard i have to switch back by holding that button down and clicking left stick.

**Comment by KyleGospo** [comment]
Yes that's stock steam deck behavior, holding down the steam button switches the key set to a desktop oriented one until let go of for games that have menus that quickly require a mouse.

By desktop profile, what's generally meant is the controller profile set in steam settings on the desktop
