### ISSUE TITLE
Cemu: can't write in provided home path for "MLC Path"

### ISSUE THREAD

**Issue by duhow** [ublue-os/bazzite#791]
### Describe the bug

Running [Cemu](https://cemu.info/), I try to set a custom **MLC Path** (system dump) to `$HOME/ROMS/WiiU/MLC Dump`, but the application does not allow it, says `path is read-only`.

However, if I copy the same content to `/var/home/duhow/.var/app/info.cemu.Cemu/data/Cemu/mcl01` (provided by flatpak app default path), it does work.

My home directory has chmod 775 / 664 , but it doesn't seem to do anything.

### What did you expect to happen?

Allow setting other path.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:0c779386100258771e5947e913348d072935e2683f8301ca5c256d4b8f44bbb0
                  Version: 39.20240116.0 (2024-02-20T17:03:54Z)
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:latest
                   Digest: sha256:48c4a0b0e2837e6e1317d889bd2886f964e6b0c396b35756a135ace5a3257135
                  Version: 39.20240116.0 (2024-02-19T07:26:50Z)
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"'
```

**Comment by KyleGospo** [comment]
Since this is a flatpak, have you whitelisted the path you want the ROMs stored at? We ship flatseal to make this easy.

**Comment by duhow** [comment]
Ok, enabling **flatseal** with option `filesystem=home` works :)

![image](https://github.com/ublue-os/bazzite/assets/1145001/9031514c-e0b7-451d-9607-6496da8132f3)
