### ISSUE TITLE
Offline installer Steam deck image doesnt boot

### ISSUE THREAD

**Issue by FredsMedia** [ublue-os/bazzite#808]
### Describe the bug

While booting the offline installer for Steam Deck/HTPC with KDE i encountered errors.

### What did you expect to happen?

I expected to greet an installer screen.

### Output of `rpm-ostree status`

```shell
N/A
```

### Hardware

Steam Deck LCD

### Extra information or context

It sat on Started cancel-multi-path-wait-nvme0n1.service for a while (>2mins)

dracut-initqueue: timeout, still waiting for following initqueue hooks:
ADD HOOKS LATER

####Anaconda installer errors begin####

It seems that the boot has failed. Possible causes include missing inst.stage2 or inst.repo on the kernel command line. Please verify you have specified inst.stage2 or inst.repo.
Please also note that the 'inst.' prefix is now mandatory.

####Installer errors encountered during boot:####

Reason unknown

####Anaconda installer errors end####

(I typed all this out as i couldnt find where the file saved.) (I will add the hooks tomorrow if i remember)

**Comment by MakandaDEV** [comment]
This is true, the offline installer is currently **_broken_** on the Steam Deck!

**Comment by KyleGospo** [comment]
Make sure USB mode is set to xhci in the bios, this is the default

**Comment by FredsMedia** [comment]
> Make sure USB mode is set to xhci in the bios, this is the default

Can this be done on the Steam Deck?

**Comment by nicknamenamenick** [comment]
> > Make sure USB mode is set to xhci in the bios, this is the default
> 
> Can this be done on the Steam Deck?

In the BIOS, yeah.

**Comment by FredsMedia** [comment]
> > > Make sure USB mode is set to xhci in the bios, this is the default
> > 
> > 
> > Can this be done on the Steam Deck?
> 
> In the BIOS, yeah.

Thanks, I'll try when i get home. If it is set to xhci what should i do?

**Comment by noelmiller** [comment]
Boot to Bios by turning the steam deck completely off and then holding the + button and pressing the power button. 

You will get to this screen. Select setup utility
![PXL_20240226_005242500.jpg](https://github.com/ublue-os/bazzite/assets/4983138/25b64ecd-abfa-489e-b66a-34ffd7fa59e4)

Go to advanced > USB configuration

![PXL_20240226_005326126.jpg](https://github.com/ublue-os/bazzite/assets/4983138/e341f8a1-bbc5-4737-ae7b-d586e81715e1)

Then select XHCI for USB dual role device

![PXL_20240226_005337897.jpg](https://github.com/ublue-os/bazzite/assets/4983138/e6b90424-e40c-43f4-990d-47decf7765fe)

Then try to boot. It fixed the issue on my OLED deck.

**Comment by FredsMedia** [comment]
I'll try this in ~1hr. This should probably be in the instructions somewhere (if it isnt already, i couldve missed it!)

**Comment by FredsMedia** [comment]
![image](https://github.com/ublue-os/bazzite/assets/106362296/f460585f-8acc-49f3-8c4f-de3ef4498a37)
Would you look at that! The USB mode was the problem! Just wondering, what would have needed me to change the usb mode to DRD?

**Comment by FredsMedia** [comment]
In summary, make sure USB mode is set to XHCI in the BIOS under Advanced > USB dual role device. Thanks @noelmiller @KyleGospo @nicknamenamenick and @MakandaDEV You legends!

**Comment by noelmiller** [comment]
> ![image](https://github.com/ublue-os/bazzite/assets/106362296/f460585f-8acc-49f3-8c4f-de3ef4498a37)
> Would you look at that! The USB mode was the problem! Just wondering, what would have needed me to change the usb mode to DRD?

According to @KyleGospo, Valve shipped it with DRD by default at one point and switched it to XHCI going forward. My model and yours must have never gotten the memo :D

**Comment by FredsMedia** [comment]
> > ![image](https://private-user-images.githubusercontent.com/106362296/307669932-f460585f-8acc-49f3-8c4f-de3ef4498a37.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjU1NDUsIm5iZiI6MTcwODkyNTI0NSwicGF0aCI6Ii8xMDYzNjIyOTYvMzA3NjY5OTMyLWY0NjA1ODVmLThhY2MtNDlmMy04YzRmLWRlM2VmNDQ5OGEzNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwNTI3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjBhZGYxOTZmYWZmOTBjMjc0Zjg0Y2M4ZmRmNDIwOTUwNzZlNmJiYmNkOTk4OTcxZDk1M2Y4ZWE4MDBlMWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7AKPFDTuZJUKutRiUyIwCBeBK4akweIX7orDk565LFo)
> > Would you look at that! The USB mode was the problem! Just wondering, what would have needed me to change the usb mode to DRD?
> 
> According to @KyleGospo, Valve shipped it with DRD by default at one point and switched it to XHCI going forward. My model and yours must have never gotten the memo :D

Fair enough! Now is there any fix to the resolution if the installer (i can’t even hit the next button!) (you can see it in the photo)

**Comment by noelmiller** [comment]
We just dropped a fix for that in the ISO this evening. Go ahead and download a new ISO and try it!

**Comment by FredsMedia** [comment]
Finally, is there ever going to be some kind of on-screen keyboard in the installer as i only have a bluetooth one and im going to have to go rummaging around to find a USB one.

**Comment by FredsMedia** [comment]
> We just dropped a fix for that in the ISO this evening. Go ahead and download a new ISO and try it! (You will still need an external keyboard for now)

Just the Steam deck iso being updated or all of them?

**Comment by noelmiller** [comment]
> > We just dropped a fix for that in the ISO this evening. Go ahead and download a new ISO and try it! (You will still need an external keyboard for now)
> 
> Just the Steam deck iso being updated or all of them?

Just the steam deck ISOs are getting the resolution fix.

**Comment by noelmiller** [comment]
> Finally, is there ever going to be some kind of on-screen keyboard in the installer as i only have a bluetooth one and im going to have to go rummaging around to find a USB one.

That is a harder problem to solve. One I'm actively interested in solving at some point, but it might be a bit.

**Comment by FredsMedia** [comment]
> > > We just dropped a fix for that in the ISO this evening. Go ahead and download a new ISO and try it! (You will still need an external keyboard for now)
> > 
> > 
> > Just the Steam deck iso being updated or all of them?
> 
> Just the steam deck ISOs are getting the resolution fix.

Cool, i was gonna say i dont want to have to redownload all the iso options (you never know when you might need one!)

**Comment by FredsMedia** [comment]
> > Finally, is there ever going to be some kind of on-screen keyboard in the installer as i only have a bluetooth one and im going to have to go rummaging around to find a USB one.
> 
> That is a harder problem to solve. One I'm actively interested in solving at some point, but it might be a bit.

I'd be interested in solving that too (somehow...)

**Comment by FredsMedia** [comment]
<img width="452" alt="Screenshot 2024-02-26 at 4 49 05 pm" src="https://github.com/ublue-os/bazzite/assets/106362296/9ed7e4a1-dc55-4a84-a753-8068c59dcfc7">
nice job!

**Comment by Antagram** [comment]
Hi, I downloaded the gnome image for Steam Deck today and I have this resolution issue

**Comment by nicknamenamenick** [comment]
> Hi, I downloaded the gnome image for Steam Deck today and I have this resolution issue

If you're talking about the installer not scaling properly, then it's a known issue and warned in the installation guide for the Steam Deck. The scaling patch for the installer only works if you flash it with Ventoy and is currently being investigated.

**Comment by Antagram** [comment]
> > Hi, I downloaded the gnome image for Steam Deck today and I have this resolution issue
> 
> If you're talking about the installer not scaling properly, then it's a known issue and warned in the installation guide for the Steam Deck. The scaling patch for the installer only works if you flash it with Ventoy and is currently being investigated.

Thanks for the reply. I was using Ventoy indeed, but I didn't realised that ther was a newer version. Worked for me on 1.97, on 1.96 it doesn't work.
