### ISSUE TITLE
Docment that fix-screenshare is removed for Gnome users

### ISSUE THREAD

**Issue by themaster567** [ublue-os/bazzite#811]
### Describe the bug

When attempting to run `just fix-screenshare` you get the following error

```
cp /usr/share/applications/org.kde.xwaylandvideobridge.desktop $HOME/.config/autostart/
cp: cannot stat '/usr/share/applications/org.kde.xwaylandvideobridge.desktop': No such file or directory
error: Recipe `fix-screenshare` failed on line 506 with exit code 1
```

### What did you expect to happen?

I expect the listed command to properly function.

### Extra information or context

If fix-screenshare has been removed for the gnome release (This is only mentioned on the entirety of the internet by a single discord post by a volunteer that was a response to someone else saying the command didn't work, in December), does that mean the fix it is providing does not function on Gnome at all?

If so, I wish that could have been better communicated, as it's a rather critical omission that people should be aware of before installing the Gnome version of Bazzite.

It is not warned in the documentation anywhere that the command doesn't function in Gnome. I think it's rather unfair to the end user to have a particular command not function without explanation, forcing them to track down a single discord post from months ago to be aware of this.

**Comment by KyleGospo** [comment]
This feature was causing other issues in gnome, it may also disappear from KDE.
