### ISSUE TITLE
Installer scaling makes it unusable. Bazzite-Deck-Stable ISO on Steam Deck LCD

### ISSUE THREAD

**Issue by TeamLinux01** [ublue-os/bazzite#812]
### Describe the bug

The screen looks like it is using a scale factor of 175% on the 800p screen of the Steam Deck LCD.
This makes the buttons to install render off the screen.

### What did you expect to happen?

I expected the installer to use 100% scaling and that the installer fit on the entire screen.

### Hardware

Steam Deck LCD model.

### Extra information or context

![IMG_20240225_132924](https://github.com/ublue-os/bazzite/assets/43735175/19680384-508d-4a98-9d03-b87fbb710c18)
Photo of the first screen of the installer on Steam Deck LCD.

It is currently docked in the official Steam Deck Dock with no monitors attached, but it does the same thing when both HDMI and DP monitors are plugged in at the same time.

Booted from Ventoy 1.0.97 using normal mode.

**Comment by TeamLinux01** [comment]
I tried the troubleshooting boot option `basic graphics` with the monitors attached and it output to the HDMI monitor, so I could finish the installation.

**Comment by noelmiller** [comment]
Hi @TeamLinux01,

Thanks for reporting this bug! We are aware of the issue and are currently working on a fix to resolve it. 

In the meantime, you can enter `inst.resolution=1280x800` at the GRUB screen to fix the scaling. 

Let us know if you run into anything else! 

Noel

**Comment by KyleGospo** [comment]
Fixed in the latest ISO, thanks!

**Comment by zwaldowski** [comment]
I saw this regress in the 3.0.0 ISO on Deck.

**Comment by GuardianLiarus** [comment]
> I saw this regress in the 3.0.0 ISO on Deck.

Can confirm, faced exactly this trying to install bazzite on my deck today
