### ISSUE TITLE
CPU Govnor

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#814]
### Describe the bug

When i change CPU power to performance, it doesn't work after i reboot

### What did you expect to happen?

I expected the CPU to run at Max MHz, because games like Dota 2 Street Fighter 6 and MK1 need CPU to run at max frequency or it wil cause stutter when spells and skills are used

### Hardware

i5-6500
RX 6400 RX 580 RX 6600 and RX 5600

### Extra information or context

The Commands i entered

```
sudo cpupower frequency-set -g performance
sudo systemctl enable cpupower
```

**Comment by KyleGospo** [comment]
Changes to cpu frequency don't survive reboots -- stock behavior.
