### ISSUE TITLE
Switch controller issues

### ISSUE THREAD

**Issue by unicornsandcandies** [ublue-os/bazzite#818]
### Describe the bug

When I use the option to sygnalize controller order on my pad, the LEDs are flashing randomly. It works fine on steamos. Seems like it's a driver issue of sorts. 

Is there any way for me to repair this? 

### What did you expect to happen?

I expected LEDs on the pad to light up according to controller order in steam. The same way it works on steamos.

### Hardware

Steam Deck OLED
8bitdo ultimate bluetooth controller and switch pro controller 

### Extra information or context

(There are 4 green LEDs on switch pads, they should be lighting according to controller order set in steam)

**Comment by yeahJwczjzlTest** [comment]
> ### Describe the bug
> When I use the option to sygnalize controller order on my pad, the LEDs are flashing randomly. It works fine on steamos. Seems like it's a driver issue of sorts.
> 
> Is there any way for me to repair this?
> 
> ### What did you expect to happen?
> I expected LEDs on the pad to light up according to controller order in steam. The same way it works on steamos.
> 
> ### Output of `rpm-ostree status`
> _No response_
> 
> ### Hardware
> Steam Deck OLED 8bitdo ultimate bluetooth controller and switch pro controller
> 
> ### Extra information or context
> (There are 4 green LEDs on switch pads, they should be lighting according to controller order set in steam)

我的也是 switch pro controller 
出现的问题和上面一样
更具体点 连接很不稳定
在终端运行命令 journalctl -f -u bluetooth 观察后发现日志: 
profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info 
上述日志出现在 switch pro controller  连接后

使用 systemctl status bluetooth 查看发现如下状态

'''● bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Mon 2024-03-11 18:11:09 CST; 16h ago
       Docs: man:bluetoothd(8)
   Main PID: 4758 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 13806)
     Memory: 4.2M
        CPU: 995ms
     CGroup: /system.slice/bluetooth.service
             └─4758 /usr/libexec/bluetooth/bluetoothd

3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/faststream
3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/faststream_duplex
3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSink/opus_05
3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/opus_05
3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSink/opus_05_duplex
3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/opus_05_duplex
3月 12 09:58:16 legiongo4jay bluetoothd[4758]: src/adv_monitor.c:btd_adv_monitor_power_down() Unexpected NULL btd_adv_monitor_manager object upon power down
3月 12 09:58:55 legiongo4jay bluetoothd[4758]: profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info
3月 12 10:06:00 legiongo4jay bluetoothd[4758]: src/adv_monitor.c:btd_adv_monitor_power_down() Unexpected NULL btd_adv_monitor_manager object upon power down
3月 12 10:09:24 legiongo4jay bluetoothd[4758]: profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info'''

**Comment by unicornsandcandies** [comment]
> > ### Describe the bug
> > When I use the option to sygnalize controller order on my pad, the LEDs are flashing randomly. It works fine on steamos. Seems like it's a driver issue of sorts.
> > Is there any way for me to repair this?
> > ### What did you expect to happen?
> > I expected LEDs on the pad to light up according to controller order in steam. The same way it works on steamos.
> > ### Output of `rpm-ostree status`
> > _No response_
> > ### Hardware
> > Steam Deck OLED 8bitdo ultimate bluetooth controller and switch pro controller
> > ### Extra information or context
> > (There are 4 green LEDs on switch pads, they should be lighting according to controller order set in steam)
> 
> 我的也是 switch pro controller 出现的问题和上面一样 更具体点 连接很不稳定 在终端运行命令` journalctl -f -u bluetooth` 观察后发现日志: `profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info ` 上述日志出现在 switch pro controller 连接后
> 
> 使用 `systemctl status bluetooth `查看发现如下状态
> 
> ```
> ● bluetooth.service - Bluetooth service
>      Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; preset: enabled)
>     Drop-In: /usr/lib/systemd/system/service.d
>              └─10-timeout-abort.conf
>      Active: active (running) since Mon 2024-03-11 18:11:09 CST; 16h ago
>        Docs: man:bluetoothd(8)
>    Main PID: 4758 (bluetoothd)
>      Status: "Running"
>       Tasks: 1 (limit: 13806)
>      Memory: 4.2M
>         CPU: 995ms
>      CGroup: /system.slice/bluetooth.service
>              └─4758 /usr/libexec/bluetooth/bluetoothd
> 
> 3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/faststream
> 3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/faststream_duplex
> 3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSink/opus_05
> 3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/opus_05
> 3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSink/opus_05_duplex
> 3月 11 18:11:13 legiongo4jay bluetoothd[4758]: Endpoint registered: sender=:1.55 path=/MediaEndpoint/A2DPSource/opus_05_duplex
> 3月 12 09:58:16 legiongo4jay bluetoothd[4758]: src/adv_monitor.c:btd_adv_monitor_power_down() Unexpected NULL btd_adv_monitor_manager object upon power down
> 3月 12 09:58:55 legiongo4jay bluetoothd[4758]: profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info
> 3月 12 10:06:00 legiongo4jay bluetoothd[4758]: src/adv_monitor.c:btd_adv_monitor_power_down() Unexpected NULL btd_adv_monitor_manager object upon power down
> 3月 12 10:09:24 legiongo4jay bluetoothd[4758]: profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info
> ```

Have you found anything? Is there anything I can install? Some fix?
