### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zqpvr** [ublue-os/bazzite#820]
Is KDE 6 in bazzite yet?

**Comment by KyleGospo** [comment]
Not yet, it'll land with Fedora 40

**Comment by KyleGospo** [comment]
> unrelated question, but since this is an issue for questions I'll ask here.
> 
> I'm in need of a fresh installation of python. Things are messing up with python dependent apps. attempting to override uninstall through rpm-ostree causes it to complain about dependent packages relying upon it which prevents it from working. It appears I have an entire but-load of python3 related subpackages or whatever but their individual packages and there are a lot of them.
> 
> I want to replace the python installation with something that.......functions....properly. I've had other Linux installlations over the years and using python in those instances, when things went sideways, a re-installation of python would fix everything as some Package Managers and distros don't maintain the same working versions or they install things differently. Either way, reinstalling has always been the starting point for me to correct these issues....
> 
> any advice would be appreciated.
> 
> ![SS_Python3_pkgs_related](https://github.com/ublue-os/bazzite/assets/119357189/6d68968d-d1b3-44f7-8e30-76f8d74bc467)
> 

That would be a use case for Distrobox for sure.

**Comment by KyleGospo** [comment]
> I understand your advice is centered around bazzite maintainers use case for me, but that doesn't fix anything which relies upon python3 to work.....
> 
> I need a working python3 installation on the system

That advice is centered around users. Installing Python in a distrobox and running your various python needs through that distrobox is exactly the use case it's for.

**Comment by KyleGospo** [comment]
> I understand your advice is centered around bazzite maintainers use case for me, but that doesn't fix anything which relies upon python3 to work.....
> 
> I need a working python3 installation on the system
