### ISSUE TITLE
[Legion Go] Cant Open Nested desktop in game mode

### ISSUE THREAD

**Issue by gt2416** [ublue-os/bazzite#821]
### Describe the bug

When launching nested desktop from game mode, it gets stuck on the splash screen of the app opening. It never goes past that, this is a clean install.
However if I run it in desktop mode it opens as expected. 

### What did you expect to happen?

Nested desktop app opens and I can see the desktop

**Comment by KyleGospo** [comment]
Can you provide the rpm-ostree output requested in the issue template?

**Comment by SuperPhenotype** [comment]
you can try removing it from your steam library, and then click the "add steam shortccut" button on the desktop mode application for it from the context menu to see if that helps. Otherwise I'd check the properties for it from within gamemode and make sure it's launching properly.

**Comment by gt2416** [comment]
Fixed it by setting per game profile to 60hz.
Fix was mentioned on the Legion Go tricks github.
