### ISSUE TITLE
Lockups & sudden power-off

### ISSUE THREAD

**Issue by SuperPhenotype** [ublue-os/bazzite#825]
### Describe the bug

In the terminal, compressing an archive of some files while using the web-browser and attempting to output stream to a file in VLC + other misc related things. System suddenly shuts off. I power back up the machine to find my archive I was compressing for the last 1 hour is now completely gone.....just vanished. 

### What did you expect to happen?

1) Compression of files completes successfully after a couple more hours.

2) Continued functional operation of the device.

3) Great amusement upon finishing the file stream output given the changes I had made. 

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:4151c51fe4e5e394de97987a47600a09b0866a38569baeadccd88b146ea9875c
                  Version: 39.20240224.0 (2024-02-25T07:25:06Z)
          LayeredPackages: cargo libvirt micro mpv rclone rclone-browser rust snapd
                           virt-manager vlc
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:latest
                   Digest: sha256:4151c51fe4e5e394de97987a47600a09b0866a38569baeadccd88b146ea9875c
                  Version: 39.20240224.0 (2024-02-25T07:25:06Z)
      RemovedBasePackages: python-unversioned-command python3-tkinter 3.12.1-2.fc39
                           python3-file-magic 5.44-5.fc39 python3-langtable 0.0.65-1.fc39
                           python3-regex 2023.12.25-1.fc39
                           python3-simpleaudio 1.0.4-11.fc39
          LayeredPackages: cargo libvirt micro mpv rclone rclone-browser rust snapd vlc yad
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Lenovo Legion Go

### Extra information or context

DMESG Output:
[dmesg_out.txt](https://github.com/ublue-os/bazzite/files/14452255/dmesg_out.txt)

RPM-OSTREE Ootput:
[rpm-ostree_status.txt](https://github.com/ublue-os/bazzite/files/14452269/rpm-ostree_status.txt)

**Comment by SuperPhenotype** [comment]
It should be noted that I've been experiencing lockups basically since the beginning when I started  using Bazzite. Not often enough to really complain, but enough times that it's caught my attention.

**Comment by KyleGospo** [comment]
A dmesg containing logs for this would be helpful

**Comment by SuperPhenotype** [comment]
> A dmesg containing logs for this would be helpful

I'm sorry I don't understand, is that different that just "sudo dmesg > dmesg_out.txt", because I have that one uploaded above. You can find it under Extra Information or context: DMESG Output:[dmesg_out.txt](https://github.com/ublue-os/bazzite/files/14452747/dmesg_out.txt)

**Comment by KyleGospo** [comment]
Apologies, couldn't see that from my phone for some reason. I'll take a look!

**Comment by SuperPhenotype** [comment]
I'll submit this as well just in case, not sure what's going on but there are segfaults with something called gldriverquery.
[journalctl_dmesg.txt](https://github.com/ublue-os/bazzite/files/14453104/journalctl_dmesg.txt)

**Comment by SuperPhenotype** [comment]
Hey, so I just recalled that part of what I was doing, I had forgotten about momentarily, but I've found my vanished archive files.....I had forgotten I'd mounted an external drive to the folder in my user home that I was checking. I'm still locking up somewhat frequently however.

**Comment by SuperPhenotype** [comment]
bazzite has a tendency of automounting drives to odd locations without user input upon detection despite having the setting turned off in the KDE Settings app.
