### ISSUE TITLE
Other distros of Bazzite?

### ISSUE THREAD

**Issue by thanone2** [ublue-os/bazzite#828]
Can I suggest giving other versions of Linux with Bazzite? Like Debian, or Arch-Linux?

**Comment by SamlRx** [comment]
There is already other distos based on other distros. You can look to Nobara or ChimeraOS. It depends what you are looking for.

**Comment by thanone2** [comment]
> There are already other distos based on other distros. You can look to Nobara or ChimeraOS. It depends what you are looking for.

ok, thanks! I'll check those out.
