### ISSUE TITLE
Cannot layer Firefox

### ISSUE THREAD

**Issue by PVermeer** [ublue-os/bazzite#842]
### Describe the bug

`rpm-ostree install firefox`:
```sh
Inactive requests:
  firefox (already provided by firefox-123.0-2.fc39.x86_64)
```
It's not layered if continued also there is no trace of a native firefox on the filesystem.

### What did you expect to happen?

To be able to layer native firefox that was removed from the upstream container.

### Output of `rpm-ostree status`

```shell
ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:latest
                   Digest: sha256:0469c8265a5360fdc4297e26748c99db60ffe41162153424dd6db062a7ab2a23
                  Version: 39.20240301.0 (2024-03-02T00:17:39Z)
          LayeredPackages: code containerd.io docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin gnome-boxes grsync mullvad-vpn
                           nautilus-dropbox nautilus-megasync nextcloud-client-nautilus sunshine
            LocalPackages: megasync-4.12.2-2.1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:latest
                   Digest: sha256:0469c8265a5360fdc4297e26748c99db60ffe41162153424dd6db062a7ab2a23
                  Version: 39.20240301.0 (2024-03-02T00:17:39Z)
          LayeredPackages: code containerd.io docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin gnome-boxes grsync mullvad-vpn
                           nautilus-dropbox nautilus-megasync nextcloud-client-nautilus sunshine
            LocalPackages: megasync-4.12.2-2.1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"'
```

### Hardware

# System Details Report
---

## Report details
- **Date generated:**                              2024-03-02 23:53:10

## Hardware Information:
- **Hardware Model:**                              ASUS PRIME B550-PLUS
- **Memory:**                                      32,0 GiB
- **Processor:**                                   AMD Ryzen™ 5 5600X × 12
- **Graphics:**                                    AMD Radeon™ RX 6650 XT
- **Disk Capacity:**                               3,1 TB

## Software Information:
- **Firmware Version:**                            3205
- **OS Name:**                                     Fedora Linux 39.20240301.0 (Bazzite GNOME)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.6-201.fsync.fc39.x86_64

### Extra information or context

I assume native Firefox is removed in favor of the flatpak but I'm having issues with vaapi hardware decoders. I think it's an outdated libva or missing codecs on flatpak. `vainfo` On flatpak is missing some codecs (mainly vp9). Running firefox in a container works fine but has a very long startup (4 seconds).

https://github.com/ublue-os/bazzite/blob/2f687cc38f449777a2f3073cfdbd655c10f52888/Containerfile#L217-L229

I can layer htop just fine so I don't know what's going on.

**Comment by KyleGospo** [comment]
Upstream limitation, you cannot layer a package we explicitly override remove.

This is a safety thing, you want your browser to update more often than your base OS for security reasons.
