### ISSUE TITLE
Steam deck cannot connect to Bluetooth keyboard

### ISSUE THREAD

**Issue by FredsMedia** [ublue-os/bazzite#843]
### Describe the bug

When I attempt to connect to my Logitech K380 (Bluetooth) keyboard the Bluetooth wizard takes a while and then says it failed.

### What did you expect to happen?

I expected my keyboard to connect and work fine.

### Output of `rpm-ostree status`

```shell
State: busy
Transaction: install -y -A ./teamviewer.x86_64.rpm 
  Initiator: client(id:cli dbus:1.223 unit:run-r0ab376a329b2467d9e88a9f4fab17a35.scope uid:0)
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:3f5b838c5a96ab04972ced136c4c1602f5d68f58d900836d6ede4ad426ec8714
                  Version: 39.20240301.0 (2024-03-02T00:21:09Z)
          LayeredPackages: sunshine
            LocalPackages: nomachine-8.11.3-4.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 


  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:3f5b838c5a96ab04972ced136c4c1602f5d68f58d900836d6ede4ad426ec8714
                  Version: 39.20240301.0 (2024-03-02T00:21:09Z)
          LayeredPackages: sunshine
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 
```

### Hardware

Jupiter (Steam deck LCD)

### Extra information or context

My keyboard worked fine on SteamOS and on other devices. I have tried resetting the keyboard and pairing both through desktop and game mode, and through bluetoothctl

**Comment by FredsMedia** [comment]
I have ended up switching back to SteamOS for the time being. If a solution can be figured out then i will easily go back to bazzite.

**Comment by RodoMa92** [comment]
It's a bluez bug. You need to keep insisting on pairing until it will bind from bluetoothctl. See [here](https://github.com/bluez/bluez/issues/654).

**Comment by FredsMedia** [comment]
> It's a bluez bug that might be related to bluetooth kernel regression on the latest stable kernel. You need to keep insisting on pairing until it will bind from bluetoothctl. See [here](https://github.com/bluez/bluez/issues/654).

does it matter if i use the GUI to pair it or the command line?

Doing a quick read over makes it seem that even if i pair it, i may not get any key presses across. Lovely...

**Comment by FredsMedia** [comment]
After an hour, finally it asked for the pin and it’s working!

**Comment by RodoMa92** [comment]
Yep, same issue. Maybe try to pile on that issue and see if someone can help fix this.

**Comment by FredsMedia** [comment]
Sure. Thanks for the help!
