### ISSUE TITLE
Controller Desktop profile on Steam Deck doesn't reactivate from sleep mode

### ISSUE THREAD

**Issue by mxp83** [ublue-os/bazzite#844]
### Describe the bug

When I restore the steam deck from sleep while in desktop my profile doesn't work (left trackpad has toggle options), it defaults to what I assume is Bazzites setting

### What did you expect to happen?

Should go back to my defined desktop controller settings

**Comment by KyleGospo** [comment]
I'm not able to reproduce this on my LCD or my OLED. Are you able to select the controller profile in Steam to resolve the issue after you come back from sleep?

**Comment by mxp83** [comment]
Yes I can bring it up. Once I go into controller settings and view profile it resets. It is nothing breaking, just slightly annoying.
