### ISSUE TITLE
Topgrade pipx failed error

### ISSUE THREAD

**Issue by tootbrute** [ublue-os/bazzite#845]
### Describe the bug

When running `just update` or `topgrade` pipx fails. I recently rebased from ublue silverblue-main. I'm running `bazzite-gnome-asus:stable` now.

I don't need pipx to work but I just want it to complete `just update` without failing.

**Error message:**
```
── 20:08:07 - pipx ─────────────────────────────────────────────────────────────
pipx failed: 
   0: Command failed: `pipx --version`

      Stderr:
      Traceback (most recent call last):
        File "/var/home/USER/.local/bin/pipx", line 5, in <module>
          from pipx.main import cli
      ModuleNotFoundError: No module named 'pipx'
   1: `pipx` failed: exit status: 1

Location:
   src/steps/generic.rs:383
Retry? (y)es/(N)o/(s)hell/(q)uit
...
error: Recipe `update` failed with exit code 1
```

### What did you expect to happen?

`just update` and `topgrade` should finish and pipx should be upgraded.

### Output of `rpm-ostree status`

```shell
$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: inactive
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-gnome-asus:stable
                   Digest: sha256:8d43b6069280f5020ab6498d4bc38a193b36f96c8ca4f16d45c85bf19e5d0d99
                  Version: 39.20240302.0 (2024-03-03T02:15:13Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"' 

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite-gnome-asus:stable
                   Digest: sha256:28eced9c87c8fdc96f6b5a91cddd7897bc9220ba2767be2328362f0d0f0ffa8b
                  Version: 39.20240301.0 (2024-03-02T00:19:13Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"'
```

### Hardware

$ neofetch --off
USER@olympus 
------------- 
Host: VivoBook_ASUSLaptop X415EA_X415EA 1.0 
OCI: Bazzite (Desktop Edition) x86_64 
OS: Fedora Linux 39.20240302.0 (Bazzite GNOME) x86_64 
Kernel: 6.7.6-201.fsync.fc39.x86_64 
Uptime: 6 mins 
Packages: 2267 (rpm), 7 (steam), 160 (flatpak) 
Shell: bash 5.2.26 
Resolution: 1920x1080, 1920x1080 
DE: GNOME 45.4 (wayland) 
WM: Mutter 
WM Theme: Bazzite 
Theme: adw-gtk3-dark [GTK2/3] 
Icons: breeze-dark [GTK2/3] 
Terminal: BlackBox 
CPU: 11th Gen Intel i5-1135G7 (8) @ 4.2GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 3.30 GiB / 23.16 GiB (14%)

**Comment by KyleGospo** [comment]
You can run `rpm-ostree update` to update just Bazzite, as for this error it appears you have an incomplete pipx install topgrade is trying to update, you'll need to clear that out to fix this.

**Comment by KyleGospo** [comment]
You can run `rpm-ostree update` to update just Bazzite, as for this error it appears you have an incomplete pipx install topgrade is trying to update, you'll need to clear that out to fix this.

**Comment by tootbrute** [comment]
I tried updating and rebooting. No change in the behaviour. I guess I'll wait until another rpm-ostree update and try rebooting. I guess eventually it will 'fix itself'.

**Comment by KyleGospo** [comment]
The pipx install would be something in your home dir, IE not affected by updates.

**Comment by tootbrute** [comment]
> The pipx install would be something in your home dir, IE not affected by updates.

ok sorry if I'm a bit dense, but how do I fix this? i only rebased to this image. I didn't install pipx myself.

Baring fixing the problem, is there a way to comment out the pipx stuff in the `just update` recipe? i want the topgrade / just update command to finish without error.

I found the folder:
~/.local/pipx/

Not sure what I can do to it though.

**Comment by tootbrute** [comment]
Reinstalled from the bazzite ISO. Fixed all my problems. I guess the main thing here is never every rebase to another desktop environment.

**Comment by Jay2645** [comment]
FWIW - I also encountered this issue, after rebasing from Kinoite. I actually didn't discover it immediately after a rebase - instead I discovered it after I installed a package with `pip install -U` (not knowing `pipx` was a thing).

After using `ujust update` after installing that pip package, it failed with the exact same message. Pipx wasn't installed on my system at all, so my guess is that the rebase operation somehow doesn't flag pipx for install for some reason.

I used `rpm-ostree install pipx` to layer it into my packages:
```
jay@Bomu-Bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:27a2080fa23ac2152ebaa61bbd3f504fc60e57a7f29f6e7ea1f77f8842a7b969
                  Version: 40.20240921.1 (2024-09-22T12:36:54Z)
          LayeredPackages: cronie firefox kvantum openrazer-meta pipx razergenie
            LocalPackages: go-hass-agent-10.2.1-1.x86_64 zoom-6.0.12.5501-1.x86_64

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:ddff1ab2b039b132667213ef3aec735cd3e08e4be30bc56a2c3d1bad70970196
                  Version: 40.20240914.0 (2024-09-15T21:04:01Z)
          LayeredPackages: cronie firefox kvantum openrazer-meta razergenie
            LocalPackages: go-hass-agent-10.2.1-1.x86_64 zoom-6.0.12.5501-1.x86_64
```

Now I had a new problem, in that pipx thought I had installed `openconnect-sso` for some reason:

```
── 14:02:20 - pipx ─────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/jay/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/main.py", line 1176, in cli
    return run_pipx_command(parsed_pipx_args, subparsers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/main.py", line 345, in run_pipx_command
    return commands.upgrade_all(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/commands/upgrade.py", line 250, in upgrade_all
    _upgrade_venv(
  File "/usr/lib/python3.12/site-packages/pipx/commands/upgrade.py", line 173, in _upgrade_venv
    versions_updated += _upgrade_package(
                        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/commands/upgrade.py", line 45, in _upgrade_package
    venv.upgrade_package(
  File "/usr/lib/python3.12/site-packages/pipx/venv.py", line 459, in upgrade_package
    pip_process = self._run_pip(["--no-input", "install"] + pip_args + ["--upgrade", package_or_url])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/venv.py", line 476, in _run_pip
    return run_subprocess(cmd, run_dir=str(self.root))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 183, in run_subprocess
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/var/home/jay/.local/pipx/venvs/openconnect-sso/bin/python'
pipx failed: 
   0: Command failed: `/home/jay/.local/bin/pipx upgrade-all --include-injected --quiet`
   1: `/home/jay/.local/bin/pipx` failed: exit status: 1
```

Interestingly, attempting to install it myself caused a different issue:

```
jay@Bomu-Bazzite:~$ pipx install openconnect-sso
'openconnect-sso' already seems to be installed. Not modifying existing installation in '/var/home/jay/.local/pipx/venvs/openconnect-sso'. Pass '--force' to force installation.
```

So, as requested, I used --force:

```
jay@Bomu-Bazzite:~$ pipx install --force openconnect-sso
Installing to existing venv 'openconnect-sso'
  installed package openconnect-sso 0.8.1, installed using Python 3.12.6
  These apps are now globally available
    - openconnect-sso
done! ✨ 🌟 ✨
```

From there, `ujust update` worked fine. Leaving this here since I found it from Google and wanted to offer a solution that wasn't just "reinstall from ISO". ;)
