### ISSUE TITLE
"collect2: fatal error: cannot find ‘ld'" ld is missing from image (KDE Desktop Environment)

### ISSUE THREAD

**Issue by 44thPrince** [ublue-os/bazzite#848]
### Describe the bug

When compiling with gcc, it throws the error collect2: "fatal error: cannot find ‘ld.'"

### What did you expect to happen?

ld should be included as part of the binutils package, but whereis shows only manual/info pages. On Kinoite whereis locates it in /usr/bin where it is meant to be, and throws no errors, so this is only a Bazzite issue.
Output of '$ whereis ld':
'ld: /usr/share/man/man1/ld.1.gz /usr/share/info/ld.info.gz`

### Output of `rpm-ostree status`

```shell
: idle
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:32d95cb4840b2370eab09ce47ba2ff448b012f54f5f1e14d18c7e86282c85191
                  Version: 39.20240302.0 (2024-03-03T02:12:46Z)
          LayeredPackages: binutils emacs gcc
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"' 

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:32d95cb4840b2370eab09ce47ba2ff448b012f54f5f1e14d18c7e86282c85191
                  Version: 39.20240302.0 (2024-03-03T02:12:46Z)
          LayeredPackages: emacs firefox
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"'
```

### Hardware

VivoBook_ASUSLaptop TP420U
AMD Ryzen 5 5500U
8GB Ram

**Comment by KyleGospo** [comment]
I would use distrobox for this use case.

**Comment by 44thPrince** [comment]
Thank you, I exported the ld binary in my arch container and it worked.

**Comment by 44thPrince** [comment]
Actually I'm afraid this has created a new issue, now I get the error `error loading plugin: /usr/libexec/gcc/x86_64-redhat-linux/13/liblto_plugin.so: cannot open shared object file: No such file or directory`, and this file is nowhere to be found either in the host system or my arch container.

**Comment by zhouxingoddog312** [comment]
:smile: The same question. I think which file gcc really need is **/usr/bin/ld.gold**. And `PATH` include `~/bin`. So ,i make a symbolic link from `/usr/bin/ld.gold` to `~/bin/ld`. It seems worked.

**Comment by ic3man5** [comment]
This is still an issue and I can't seem to add a symbolic link because the file system is read-only.

```bash
sudo ln -sf /usr/bin/ld.gold /usr/bin/ld
ln: failed to create symbolic link '/usr/bin/ld': Read-only file system
```

**Comment by ic3man5** [comment]
Okay I "fixed" this by making the symbolic link inside a directory inside my home.

```bash
mkdir ~/path
ln -sf /usr/bin/ld.gold ~/path/ld
PATH=$PATH:~/path
```

**Comment by zhouxingoddog312** [comment]
> This is still an issue and I can't seem to add a symbolic link because the file system is read-only.
> 
> sudo ln -sf /usr/bin/ld.gold /usr/bin/ld
> ln: failed to create symbolic link '/usr/bin/ld': Read-only file system

I think `/usr/local/share/` and `~/.local/share/` are both writeable. You can use one of them.
