### ISSUE TITLE
40HZ Refresh rate works on desktop but no works on Game Mode (AYN LOKI MAX)

### ISSUE THREAD

**Issue by franciscorubenmanzano** [ublue-os/bazzite#852]
Hello again, is there a simple way to activate 40hz in game mode?

I am using the Bazzite distro and in desktop mode I do have the 40hz option but not in game mode.

some help?
![f8fabd1e-c388-4d53-ab85-7cf7128d1369](https://github.com/ublue-os/bazzite/assets/152093816/72b1ac59-6cbd-4c03-82a8-527208fbb6f8)
![5152b96d-c818-4a82-b88e-3e398b1cd2b5](https://github.com/ublue-os/bazzite/assets/152093816/d83b3be2-aa1c-4ea2-aa4d-9b18e18834fc)

ramsay@fedora:~$ cat /sys/devices/virtual/dmi/id/product_name
Loki Max

**Comment by KyleGospo** [comment]
Need DMI name entry, was in issue template.

**Comment by franciscorubenmanzano** [comment]
ramsay@fedora:~$  cat /sys/devices/virtual/dmi/id/product_name
Loki Max

**Comment by franciscorubenmanzano** [comment]
> ramsay@fedora:~$ cat /sys/devices/virtual/dmi/id/product_name
> Loki Max

**Comment by franciscorubenmanzano** [comment]
> Need DMI name entry, command to get was in issue template.

ramsay@fedora:~$  cat /sys/devices/virtual/dmi/id/product_name
Loki Max
