### ISSUE TITLE
add yuzu and citra back.

### ISSUE THREAD

**Issue by zqpvr** [ublue-os/bazzite#857]
### Describe the bug

https://github.com/RyzenDew/Lime-3DS-Emulator https://github.com/pineappleEA/pineapple-src are backups.

### What did you expect to happen?

a

**Comment by badlydrawnface** [comment]
These forks are not on flathub, and Citra and yuzu's flatpaks are no longer published (their manifests are archived)

it shouldn't be too hard to get the forks appimages running through Gear Lever, right?

**Comment by KyleGospo** [comment]
Given the iffy nature of the future of these, we will only add them if another team picks them up and gets them on flathub.

**Comment by badlydrawnface** [comment]
I'd recommend not trying to share around the fork until its more established, otherwise the Big N will probably take action, but until its on Flathub, it will not be added back.
