### ISSUE TITLE
[bazzite-nvidia] Steam Client graphical errors in normal & big picture mode on Wayland KDE with “Enable GPU accelerated rendering in web views” on.

### ISSUE THREAD

**Issue by v7rzlhb3xg** [ublue-os/bazzite#860]
### Describe the bug

Steam normal view and big picture mode have unusable graphical bugs and screen tearing with the GPU accelerated rendering in web views option enabled.

Disabling this option allows Steam to render normally however this causes drastic performance decrease in big picture mode. 

![IMG_0530](https://github.com/ublue-os/bazzite/assets/18043024/bf83306e-015c-453f-9a87-db20dd57087c)

### What did you expect to happen?

For Steam to behave normally.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:ba92d96283babdc08f4a4c0e7bb6695ad3c75f96f77658f360974c5e350579a7
                  Version: 39.20240116.0 (2024-03-07T02:58:46Z)
          LayeredPackages: falkon
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:ba92d96283babdc08f4a4c0e7bb6695ad3c75f96f77658f360974c5e350579a7
                  Version: 39.20240116.0 (2024-03-07T02:58:46Z)
          LayeredPackages: falkon
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"'
```

### Hardware

CPU: AMD Ryzen 5 7600
GPU: RTX 4070 connected to monitor via DP
Memory: Corsair DDR5 2x16GB 
SSD: Samsung 980 PRO 2TB

### Extra information or context

None

**Comment by HikariKnight** [comment]
Nvidia driver specific issue to my knowledge, please correct me if i am wrong

**Comment by KyleGospo** [comment]
Unfortunately this is. It should be fixed soon but for the time being you are best to served by X11.

**Comment by Fmstrat** [comment]
Now does one switch to X11 in GNOME?

**Comment by KyleGospo** [comment]
Big picture mode is broken on Nvidia in the absolute best case scenario, there is nothing we can do to support this.

**Comment by KyleGospo** [comment]
> Now does one switch to X11 in GNOME?

Can switch from the bottom right of the login screen after selecting your user.

**Comment by Fmstrat** [comment]
> > Now does one switch to X11 in GNOME?
> 
> Can switch from the bottom right of the login screen after selecting your user.

My user is password-less, so if I select the user it just logs in immediately.

**Comment by Fmstrat** [comment]
> Big picture mode is broken on Nvidia in the absolute best case scenario, there is nothing we can do to support this.

@KyleGospo This isn't true at all.

- In Debian 12.5 with Wayland, nVidia driver 525.147.05, and Steam set to use GPU for web views, Big Picture runs perfectly.
- I also had it running perfectly with Ubuntu 20.04 and X11.
- I am only having this problem with Bezzite.

**Comment by KyleGospo** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/10858
https://github.com/ValveSoftware/steam-for-linux/issues/9589
