### ISSUE TITLE
[bazzite-nvidia] Black screen with frozen cursor in center after logging into Wayland KDE session from SDDM

### ISSUE THREAD

**Issue by v7rzlhb3xg** [ublue-os/bazzite#861]
### Describe the bug

After entering username and password in SDDM greeter screen for a Wayland KDE session, the screen turns black and the mouse cursor is frozen in the middle. Connected directly to RTX 4070 via DP. Plasma X11 is able to start without issue.

### What did you expect to happen?

I expected to log into Wayland plasma shell without issues.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:230db8f7aa173cb4cea30c4cb53331a9dc6ed7375ea6e783aa26eee2fe3e6be5
                  Version: 39.20240116.0 (2024-03-05T05:21:29Z)
          LayeredPackages: sunshine
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:230db8f7aa173cb4cea30c4cb53331a9dc6ed7375ea6e783aa26eee2fe3e6be5
                  Version: 39.20240116.0 (2024-03-05T05:21:29Z)
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf"'
```

### Hardware

CPU: AMD Ryzen 5 7600
GPU: RTX 4070 connected to monitor via DP
Memory: Corsair DDR5 2x16GB
SSD: Samsung 980 PRO 2TB

### Extra information or context

This occurs even on a fresh install.

**Comment by schabpiotr** [comment]
I also have this issue on this config:
CPU: Ryzen 5 3600
GPU: ASUS TUF Gaming RTX3060Ti
MB: MSI MPG Gaming Plus B550

Problem happens after fresh install.

**Comment by sayiarin** [comment]
Same for me after a fresh install on:
CPU: Intel i7 12700K
GPU: MSI Suprim RTX 4090
Memory: Corsair DDR5 2x16GB
MB: Asus PRIME Z690-P
Storage: NVMe Samsung SSD 980 Pro 1TB

**Comment by Dylancyclone** [comment]
Also happens for me on a fresh install
CPU: AMD Ryzen 9 5900X
GPU: EVGA FTW3 GeForce RTX 3070
Memory: G.Skill Ripjaws V 32 GB (4 x 8 GB) DDR4-3600
Motherboard: ASRock X570 Taichi

Interestingly, I have two monitors plugged directly into the graphics card. The main screen (plugged in display port) has the issue where it is black with a frozen cursor in the center, but the other screen (plugged in HDMI) works fine. I can move my mouse to the other screen and interact with it normally. I can even open up the display settings and see the primary screen there, but trying to change any settings either does nothing or freezes the computer

**Comment by schabpiotr** [comment]
> Also happens for me on a fresh install CPU: AMD Ryzen 9 5900X GPU: EVGA FTW3 GeForce RTX 3070 Memory: G.Skill Ripjaws V 32 GB (4 x 8 GB) DDR4-3600 Motherboard: ASRock X570 Taichi
> 
> Interestingly, I have two monitors plugged directly into the graphics card. The main screen (plugged in display port) has the issue where it is black with a frozen cursor in the center, but the other screen (plugged in HDMI) works fine. I can move my mouse to the other screen and interact with it normally. I can even open up the display settings and see the primary screen there, but trying to change any settings either does nothing or freezes the computer
> 
> EDIT: installing the gnome version did not have this issue

Ok, it seems that my problem is simmilar, I've got an HDMI VirtualMonitor dongle connected to my GPU via HDMI and my main monitor via DP due to Moonlight not seeing my screen when I turn off the monitor. I'll check wether disconnecting the HDMI VM dongle will help.

**Comment by Dylancyclone** [comment]
> Ok, disconnecting the HDMI VM dongle helped, I logged in and I'm setting up Bazzite on my desktop :D
It seems that the system is displaying the screen on the "External" monitor. After reconnecting the HDMI monitor into the GPU system displays a window where the screen will be shown, on "External" monitor or "Laptop" monitor, the "Laptop" monitor is the DisplayPort connected monitor, the "External" one is the HDMI connected one. So it seems that KDE wants to display the screen on the "External" one instead the "Laptop" one by default.

When I unplug my second monitor and log in, the first monitor works just fine. I can then plug in my second monitor and it comes up with the "how would you like to connect this display (external, extend to left/right etc)" the first time.

However when I reboot the original issue happens again, and I have to reboot again and unplug the monitor to get into the desktop properly, then I can plug in the second screen again.

So getting closer :D
It's just cumbersome to unplug/replug the monitor each reboot on a desktop

**Comment by schabpiotr** [comment]
> > Ok, disconnecting the HDMI VM dongle helped, I logged in and I'm setting up Bazzite on my desktop :D
> > It seems that the system is displaying the screen on the "External" monitor. After reconnecting the HDMI monitor into the GPU system displays a window where the screen will be shown, on "External" monitor or "Laptop" monitor, the "Laptop" monitor is the DisplayPort connected monitor, the "External" one is the HDMI connected one. So it seems that KDE wants to display the screen on the "External" one instead the "Laptop" one by default.
> 
> When I unplug my second monitor and log in, the first monitor works just fine. I can then plug in my second monitor and it comes up with the "how would you like to connect this display (external, extend to left/right etc)" the first time.
> 
> However when I reboot the original issue happens again, and I have to reboot again and unplug the monitor to get into the desktop properly, then I can plug in the second screen again.
> 
> So getting closer :D It's just cumbersome to unplug/replug the monitor each reboot on a desktop

Yeah, it seems that HDMI gets priority over DP even when You set the DP monitor as the main one.

**Comment by Dylancyclone** [comment]
> Yeah, it seems that HDMI gets priority over DP even when You set the DP monitor as the main one.

Not just that but it's locking up the other screen, and I haven't been able to fix it without rebooting

**Comment by slmcrs** [comment]
I have been dealing with this for the past few days, I have 2 display port monitors connected directly into the GPU. DP-4 as primary and DP-2 as secondary. DP-4 was freezing, even on SDDM before I logged in. Recently upgraded to the testing branch which is on 40 with KDE/plasma 6 and it seems more stable the first few hours I have been using it.

**Comment by salty2011** [comment]
I am also seeing a similar issues with duel screen connected via display port. Can login and get to desktop but the second screen seems to be its own desktop session.

Making refresh rate changes on either monitor results in a hard lock for the whole system or changing to extend lef/right also seems to hard lock the whole system.

This is a fresh install on my friends computer with a 4090

**Comment by morgy59** [comment]
This is bug and i get a black screen(xrandr shows display as DP) with cursor and freezing every after manually login but autologin works fine without a display connected to the HDMI 

laptop specs
Lenovo LOQ 15IRH8
CPU: Intel core i7 13630H
GPU: Nvidia RTX 4060
Ram: 32gb ram
Wireless: Intel AX200 160mhz

**Comment by Dylancyclone** [comment]
Booting into Fedora 40 today I didn't have this issue :tada:

**Comment by ethanaobrien** [comment]
(Off topic comment) just wanted to share that this issue has gotten so popular even Google search is suggesting to go talk here!
![image0](https://github.com/ublue-os/bazzite/assets/77750390/cd5c161a-30ba-4d7c-b8b5-9f40c392b9eb)
