### ISSUE TITLE
I can't remove my app

### ISSUE THREAD

**Issue by zhouxingoddog312** [ublue-os/bazzite#862]
### Describe the bug

after enter "sudo dnf install ...", I installed a application(RPM). Now i want to remove it, I enter "sudo dnf remove or uninstall". It can't work. I can't remove the application. How can I do for that?

### What did you expect to happen?

I expect to remove my application.

**Comment by fiftydinar** [comment]
Are you sure that you installed the application?

Because the proper command for Fedora Atomic distributions is:  
`rpm-ostree install`
`rpm-ostree uninstall`

**Comment by zhouxingoddog312** [comment]
> Are you sure that you installed the application?
> 
> Because the proper command for Fedora Atomic distributions is: `rpm-ostree install` `rpm-ostree uninstall`

Thank!!! I made a mistake.
