### ISSUE TITLE
I lost my fonts?

### ISSUE THREAD

**Issue by zhouxingoddog312** [ublue-os/bazzite#864]
### Describe the bug

I had used `rpm-ostree install` to install the vscode. And then I install the same rpm package by  **BoxBuddy** into the container. Now it seems like this. And all other applications like this ,too.
![截图 2024-03-09 11-40-45](https://github.com/ublue-os/bazzite/assets/32806975/8e53b703-98a3-47ed-bbea-1056865fb609)
![截图 2024-03-09 11-44-46](https://github.com/ublue-os/bazzite/assets/32806975/ab88eac6-6fae-4ec8-9df1-57cc3415a293)
![截图 2024-03-09 11-45-25](https://github.com/ublue-os/bazzite/assets/32806975/17217a50-5100-4333-a0ce-123340b08345)

### What did you expect to happen?

Use my applications. :smi

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:dc0eaac7e6c42fe2aa1fd939171ac44ee126f56726914bc4b41d85e3d51b8ab3
                  Version: 39.20240306.0 (2024-03-07T03:02:47Z)
          LayeredPackages: cmake gdb lua lynx nss-tools
            LocalPackages: linuxqq-3.2.5_21453-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:dc0eaac7e6c42fe2aa1fd939171ac44ee126f56726914bc4b41d85e3d51b8ab3
                  Version: 39.20240306.0 (2024-03-07T03:02:47Z)
          LayeredPackages: cmake gdb lua lynx nss-tools
            LocalPackages: electerm-1.38.11-1.x86_64 linuxqq-3.2.5_21453-1.x86_64 lx-music-desktop-2.6.0-1.x86_64 wps-office-11.1.0.11711-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

**Comment by KyleGospo** [comment]
`rm ~/.cache/fontconfig`

Use layering as a last resort, it's always preferable to use distrobox and flatpak when possible.

**Comment by zhouxingoddog312** [comment]
@KyleGospo Thank you very much , it's useful. I have installed the package **wps-office** into distrobox. But when i launch it, there is no response. This is the reason why I must use layering.
