### ISSUE TITLE
Black screen on boot legion go + gpd g1

### ISSUE THREAD

**Issue by Riannoni** [ublue-os/bazzite#866]
### Describe the bug

Hello
When I connect the gdp g1 and try to load the game mode, everything hangs on a black screen, while I can press control + shift + f2 and boot into desktop mode, the video card is detected there successfully
Judging by the logs, the download hangs at this stage:
`The error [drm] cannot find any crtc or sizes`

### What did you expect to happen?

Successful boot with external video card into game mode

### Output of `rpm-ostree status`

```shell
Tried it on the images bazzite-deck:39-20240205 and bazzite-deck:39-20240220

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39-20240220
                   Digest: sha256:cd910c16932197ac6a7c646da4a48d7b0fc7f5dbd60b04d34963d2841fad5edc
                  Version: 39.20240220.0 (2024-02-20T17:01:39Z)
          LayeredPackages: 'supergfx*'
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 
 
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:39-20240205
                   Digest: sha256:e8ab11196e0ff23889f5d967a861357a435e5c3785532ba285a00f52dcc45008
                Timestamp: 2024-02-05T09:00:42Z
          LayeredPackages: 'supergfx*'
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

83E1

**Comment by jipiboily** [comment]
Having the same issue! Did you find a solution or workaround by any chance?

**Comment by Gotcha007** [comment]
Having the same problem as well. For now the gpd g1 is quite unusable in gaming mode unfortunately

**Comment by Serbroda** [comment]
I also have the same problem

**Comment by paindespik** [comment]
I am still having this issue as of today
