### ISSUE TITLE
Nothing happens during the 'building kargs' first-boot setup on Nvidia hybrid graphics/laptop hardware

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/bazzite#867]
### Describe the bug

After setting up the installer, it will appear the screen will be stuck at "building kargs" for eternity. 

This is most likely a red herring, and building is done but the driver is causing issues to make it appear "paused" here forever.

### What did you expect to happen?

Build kernel arguments only taking less than 40 minutes to complete and making it to the desktop.

### Hardware

This specifically affects **Nvidia hardware with hybrid graphics** (most reports come from laptops specifically)

### Extra information or context

This bug has most likely been introduced in the new Nvidia [stable drivers](https://www.gamingonlinux.com/2024/02/nvidia-550-54-14-driver-released-as-stable/) since reports started happening after Bazzite added these drivers to the image.

### Workaround

The **workaround** is plugging a monitor into the laptop if you can.  This should resolve the issue.  Reports of using the older, unreliable online ISO may work too, but this has mixed results.

**Comment by dkpoulsen** [comment]
same
