### ISSUE TITLE
add some files

### ISSUE THREAD

**Issue by zhouxingoddog312** [ublue-os/bazzite#869]
### Describe the bug

I know it's a readonly filesystem. But， is there any way to add some files to `/usr/share/fonts/`. :smiling_face_with_tear:

### What did you expect to happen?

I expected to add some file to `/usr/share/fonts/`.

**Comment by PVermeer** [comment]
I believe `/usr/local/share/fonts/` is used for system wide fonts otherwise use `~/.local/share/fonts/`.

They should both be writeable.

**Comment by HikariKnight** [comment]
@zhouxingoddog312 use the 2 locations @PVermeer mentioned, everything in `/usr/local` is writable with sudo if you need it system-wide, otherwise use `~/.local/share/fonts/`
