### ISSUE TITLE
Lenovo Legion Go - Post Update Broken Boot

### ISSUE THREAD

**Issue by SuperPhenotype** [ublue-os/bazzite#870]
### Describe the bug

When I updated, I rebooted the system, but instead of completing successfully, it drops to an emergency shell, tells me to press enter to continue, and when I do, it then says the root account is locked and fails, then loops through that.

### What did you expect to happen?

Boot successfully completes to steam OS GameMode.

### Output of `rpm-ostree status`

```shell
Not Accessible
```

### Hardware

Lenovo Legion Go

### Extra information or context

Directly prior to rebooting I had been performing disk operations on an external nvme drive connected to the thunderbolt port. I was using KDE Disk Partitioning app from flatpak that comes as default. It was attempting to perform disk operations on non-existent disk partitions, on the wrong disks.
Initramfs was set to local generation.
Legion go was experiencing intermittent lockups (once every 5-10 hours on average).
Upon inspection of the drive. The home partition, root partition, and boot partition are still present.

**Comment by KyleGospo** [comment]
Given the level of potential damage and the nature of an Atomic system, it may be best to reinstall and bring your old home directory along to the new install. Otherwise you'd be left trying to piece together missing partitions which is harder on an atomic system.

**Comment by KyleGospo** [comment]
https://universal-blue.discourse.group/t/opinions-on-answering-this-is-not-a-distro/509/22
