### ISSUE TITLE
HTPC Steam Deck-Gaming Mode: Force native Resolution possible?

### ISSUE THREAD

**Issue by lm209** [ublue-os/bazzite#871]
### Describe the bug

It is possible to force the native Resolution for the Gaming Mode without to Change each Game Settings?

It would be a very cool feature that ChimeraOS also uses in their gamescope plus.

### What did you expect to happen?

Same as above

### Output of `rpm-ostree status`

```shell
Unknown
```

**Comment by KyleGospo** [comment]
This patch is already implemented and working for me, what issues are you having?

**Comment by lm209** [comment]
> This patch is already implemented and working for me, what issues are you having?

When I connect my Steam Deck to the TV (gaming mode), I have to set the properties and resolution of each game from default to native.  otherwise it does not allow a resolution higher than 720/800p

**Comment by KyleGospo** [comment]
> > This patch is already implemented and working for me, what issues are you having?
> 
> When I connect my Steam Deck to the TV (gaming mode), I have to set the properties and resolution of each game from default to native.  otherwise it does not allow a resolution higher than 720/800p

Can you `rpm-ostree status` for me?

**Comment by KyleGospo** [comment]
Oh hold on, Steam Deck.
This is stock Valve behavior. Let me see if there's a way to override that and use the Chimera behavior.

**Comment by lm209** [comment]
> Oh hold on, Steam Deck. This is stock Valve behavior. Let me see if there's a way to override that and use the Chimera behavior.

That´s the status.

deck@fedora:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:a0c8b3c6d8db35c53617209b90559099d7d11b91281171e7bae89ad9cc65ecdd
                  Version: 39.20240312.0 (2024-03-12T16:59:25Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:0a2204f5a96e9eb14affec41d09cf6035777626d190bfaabb9de48c954aca0f5
                  Version: 39.20240311.0 (2024-03-12T08:05:37Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'

**Comment by lm209** [comment]
> Oh hold on, Steam Deck. This is stock Valve behavior. Let me see if there's a way to override that and use the Chimera behavior.

That would be awesome, If you can Override this👍

**Comment by kubepy** [comment]
I'm using environment to set up my device output resolution.
```
$ mkdir -p ~/.config/environment.d/
$ vim ~/.config/environment.d/resolution.conf 
export RESOLUTION=" -W 1280 -H 720 "
```

Maybe it could try to export `RESOLUTION` environment to change the native resolution.
e.g. game resolution with -w & -h, and 
output resolution with -W & -H parameters ?

```
$ vim ~/.config/environment.d/resolution.conf 
export RESOLUTION=" -w 1920 -h 1080 -W 1920 -H 1080 "
```

**Comment by KyleGospo** [comment]
Sorry for the long wait on this, was busy at a conference

Add: `GAMESCOPE_ENABLE_720P_RESTRICT=0` to your `/etc/environment` file

**Comment by lm209** [comment]
> Sorry for the long wait on this, was busy at a conference
> 
> Add: `GAMESCOPE_ENABLE_720P_RESTRICT=0` to your `/etc/environment` file

Yes that worked. Thank you. Do you plan to add this in future Updates?

**Comment by KyleGospo** [comment]
This is such so that the Deck can match stock Valve behavior, and other devices can use whatever their native is. We'll just want to document this better.
