### ISSUE TITLE
Black screen on boot

### ISSUE THREAD

**Issue by zhouxingoddog312** [ublue-os/bazzite#875]
### Describe the bug

Sometimes, when I power on the computer, everything hangs on a black screen. But the curser is still blink. Then i force shutdown, power on again, things be ok.

### What did you expect to happen?

Successful boot.

### Hardware

GPD win4, inserted a micro sd card(1tb).

**Comment by massatt212** [comment]
this happens to me a lot also, if i change the pc name, install an app with rpm-ostree or even update the system, i must hold the power button down, some 2 hard shutdown required, any changes causes this.

**Comment by al12gamer** [comment]
This should be fixed now. Are you booting from MicroSD or SSD?

**Comment by zhouxingoddog312** [comment]
This still happens sometimes. Yes, I’m booting from SSD.
