### ISSUE TITLE
Virtualization is not supported on Steam Deck

### ISSUE THREAD

**Issue by zqpvr** [ublue-os/bazzite#877]
### Describe the bug

deck@steamdeck:~$ ujust setup-virtualization 
Virtualization is not supported on Steam Deck
deck@steamdeck:~$ 

### What did you expect to happen?

I expect it to work as I use vm's before on my steam deck, this message is wrong.

### Output of `rpm-ostree status`

```shell
deck@steamdeck:~$ rpm-ostree status
State: busy
Transaction: install -y virt-manager edk2-ovmf qemu 
  Initiator: client(id:cli dbus:1.3176 unit:run-r732c5d90fccb46d98519ccad1df5f2b6.scope uid:1000)
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:a0c8b3c6d8db35c53617209b90559099d7d11b91281171e7bae89ad9cc65ecdd
                  Version: 39.20240312.0 (2024-03-12T16:59:25Z)
                     Diff: 1 added
          LayeredPackages: dnscrypt-proxy htop sunshine xdelta
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:a0c8b3c6d8db35c53617209b90559099d7d11b91281171e7bae89ad9cc65ecdd
                  Version: 39.20240312.0 (2024-03-12T16:59:25Z)
               LiveCommit: f7e9582b012c08827fafae5e5083d146c8a3980314ce273cf362006daf31e534
                 LiveDiff: 1 added
          LayeredPackages: htop sunshine xdelta
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 
                 Unlocked: transient

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:22d963175ca12c3f19e5b6997f2fb7a273dc3451076d3459f950e6e4b3d54561
                  Version: 39.20240302.0 (2024-03-03T02:14:15Z)
          LayeredPackages: discord htop sunshine xdelta
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

Steam Deck.

**Comment by KyleGospo** [comment]
The virtualization script fails because Valve intentionally disables IOMMU on the Steam Deck, which is a big part of that script. If you just want to run a VM with no GPU passthrough you can do that the same way you would on SteamOS. I would recommend GNOME Boxes to keep things simple.

**Comment by KyleGospo** [comment]
It's intentionally disabled by Valve, we're just following their example. You don't want IOMMU on.

**Comment by HikariKnight** [comment]
> I am not using gnome boxes, I use virt-manager + gnome boxes can't do the things that I want to do in it.

`ujust --show setup-virtualization | grep -A3 "rpm-ostree install -y virt"`
run those commands, it will grab the install commands for virt manager and the required kargs as a bare minimum.

I can move the check to only be on IOMMU/VFIO in the future

**Comment by kubepy** [comment]
I was enable Virtualization on my 32G RAM steamdeck successully.

1. Vol+ & PowerON goto  bios for enable IOMMU

2. Mount bind override the script
```
cat <<'EOF' > /tmp/valve-hardware.overrides
exit 1
EOF

sudo mount -o bind /tmp/valve-hardware.overrides /usr/libexec/hardware/valve-hardware
```
3. Install virtualization
```
ujust setup-virtualization
```

5. Add kvm & libvirtd group to 1000 user for running not root
```
sudo vim /etc/libvirt/libvirtd.conf 
unix_sock_group = "libvirt"
```
```
sudo bash -c 'grep "kvm" /lib/group >> /etc/group'
sudo bash -c 'grep "libvirt" /lib/group >> /etc/group'
```

**Comment by HikariKnight** [comment]
> I was enable Virtualization on my 32G RAM steamdeck successully.
> 
> 1. Vol+ & PowerON goto  bios for enable IOMMU
> 2. Mount bind override the script
> 
> ```
> cat <<'EOF' > /tmp/valve-hardware.overrides
> exit 1
> EOF
> 
> sudo mount -o bind /tmp/valve-hardware.overrides /usr/libexec/hardware/valve-hardware
> ```
> 
> 3. Install virtualization
> 
> ```
> ujust setup-virtualization
> ```
> 
> 5. Add kvm & libvirtd group to 1000 user for running not root
> 
> ```
> sudo vim /etc/libvirt/libvirtd.conf 
> unix_sock_group = "libvirt"
> ```
> 
> ```
> sudo bash -c 'grep "kvm" /lib/group >> /etc/group'
> sudo bash -c 'grep "libvirt" /lib/group >> /etc/group'
> sudo usermod -a -G kvm $USER
> sudo usermod -a -G libvirt $USER
> ```
> 
> ![Screenshot from 2024-03-19 00-53-20](https://private-user-images.githubusercontent.com/43437760/313768130-990ffb04-64cc-4e9c-afa9-8f43497b9ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzE4MDgsIm5iZiI6MTcxMDgzMTUwOCwicGF0aCI6Ii80MzQzNzc2MC8zMTM3NjgxMzAtOTkwZmZiMDQtNjRjYy00ZTljLWFmYTktOGY0MzQ5N2I5Y2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2NTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5Zjc4ZDI2MTdjYzU0MjJlMDFlMDk4NTMxNGIxMTllMzI4ZDBmNDdjMTZkNzZmNjc0OTE3ZGM2MDM3YzBlNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hmBPuor9TaM6MWOsvmVZY9mzLjZbZKdemeFV5yG_1sQ)

new build would let you avoid having to do this in the future :)

**Comment by BryanJacobs** [comment]
> what does vfio even do anyway

vfio lets you create a VM running, say, Windows, and attach a device (say, your graphics card) to it using hardware virtualization.

You plug a monitor into the graphics card and you've got Windows there on it. Games run at ~1-2% overhead from native. The guest has direct access to the device without going through the host OS. USB devices plugged into the graphics card are "connected to" the guest, again without any real overhead.

This is a useful feature if you have something with Anticheat that doesn't work on Linux.

**Comment by DeepNestedSpider** [comment]
The Steam Deck firmware includes an "Enable IOMMU" option. I want to explore VFIO to run Autodesk Inventor directly on the device without dual-booting. Currently, I run Inventor inside a VM using Qemu/KVM + VirtIO (3D Accelerated-ish), but performance is limited. Is there a way to test IOMMU or enable VFIO without the script disrupting the workflow with the scripting restrictions and warnings like "WARNING: Virtualization is not properly supported on Steam Deck by Valve" and "IOMMU is not supported on Steam Deck"? Otherwise, please clarify the HOW (in what way) does Valve does not fully support this feature?

**Comment by zqpvr** [comment]
You can try single gpu passthrough, it may or may not be easy, I have done it to some extent before. You may need to do the script manually.

**Comment by HikariKnight** [comment]
> The Steam Deck firmware includes an "Enable IOMMU" option. I want to explore VFIO to run Autodesk Inventor directly on the device without dual-booting. Currently, I run Inventor inside a VM using Qemu/KVM + VirtIO (3D Accelerated-ish), but performance is limited. Is there a way to test IOMMU or enable VFIO without the script disrupting the workflow with the scripting restrictions and warnings like "WARNING: Virtualization is not properly supported on Steam Deck by Valve" and "IOMMU is not supported on Steam Deck"? Otherwise, please clarify the HOW (in what way) does Valve does not fully support this feature?

the steamdeck does not support egpus so vfio cannot be used for gpus on it.
when that warning was made, IOMMU was not even exposed in the bios for the deck. however since it has been added it can only be used for network cards i believe, and i have no idea if the iommu groups for the deck would even allow it, so it changes really nothing.
