### ISSUE TITLE
No gpu control

### ISSUE THREAD

**Issue by lowpayne** [ublue-os/bazzite#880]
### Describe the bug

After update I cant control manuały gpu clock, i Have tried steam patch but didnt help

### What did you expect to happen?

Solution

### Hardware

Lenovo legion go

**Comment by lowpayne** [comment]
Yes it was working with a bit of lag while adjusting.Now after toggle it on it nothing happens and shows up.

**Comment by KyleGospo** [comment]
We don't use steam patch here, I would completely remove that and then make sure you follow the alternative handheld section of the readme.

**Comment by lm209** [comment]
Yes alternative SimpleDeckyTDP or PowerControl

**Comment by lowpayne** [comment]
> We don't use steam patch here, I would completely remove that and then make sure you follow the alternative handheld section of the readme.

How can remove the patch , there is no terminal path for this on github legion tricks.Thank you

**Comment by lm209** [comment]
Yes nothing explain a completed uninstalling. The easiest way is a Clean Install. It's not Recommended to use this anymore. Lenovo Legion Go is stable enough on Bazzite

**Comment by lowpayne** [comment]
> Yes nothing explain a completed uninstalling. The easiest way is a Clean Install. It's not Recommended to use this anymore. Lenovo Legion Go is stable enough on Bazzite. So my experience is Clean Install and Install SimpleDeckyTDP. That's the best way.

So let be it. Good news is that bazzite dont erase windows partition like chimera os so clean install is pretty easy .Back in days i was force to install windows from scratch and that was painful expirence

**Comment by lowpayne** [comment]
Can confirm fresh install fixed gpu control.Kudos for bazzite developers 🫶

**Comment by lm209** [comment]
> Can confirm fresh install fixed gpu control.Kudos for bazzite developers 🫶

Perfect. Issue fixed👍

**Comment by SeeDborg** [comment]
I have the same issue.
