### ISSUE TITLE
Steam Streaming not working properly in Bazzite

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/bazzite#882]
### Describe the bug

Currently, steam streaming does not work, I get a black screen when attempting to use it under wayland.

### What did you expect to happen?

I expected to not get a black screen

### Hardware

Custom built PC

### Extra information or context

We talked about this with Glorious Eggroll and he fixed it in Nobara. Please use that fix! :D

**Comment by c1p0** [comment]
Hope this will get fixed soon. Wasn't expecting Steam Streaming to not work

**Comment by KyleGospo** [comment]
> Hope this will get fixed soon. Wasn't expecting Steam Streaming to not work

This issue is ancient and has been fixed in the latest steam client. You can also use sunshine which we prefer.
