### ISSUE TITLE
Mangohud AMD GPU not showing any statistic like gpu load (Bazzite-Gnome)

### ISSUE THREAD

**Issue by blonde0091** [ublue-os/bazzite#883]
### Describe the bug

When using MangoHud on Steam or any program everything but the GPU is shown a statistic 

Here is the overlay used in vkcube

![image](https://github.com/ublue-os/bazzite/assets/118260621/3db81bfc-f72f-4836-aaf8-a7ea31e94fe0)

```
max@linuxpc:~$ mangohud vkcube
Selected GPU 0: AMD Radeon RX 6600 (RADV NAVI23), type: DiscreteGpu
```

### What did you expect to happen?

When using MangoHud and the default config the usual setup should be gpu, cpu, ram, vram usage etc but everything but everything but the gpu usage stat is shown

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:c6b007b680ecd77886d6776fd622070f9de617a161a07ee776419ff71897e502
                  Version: 39.20240313.0 (2024-03-14T00:44:07Z)
          LayeredPackages: coolercontrol gnome-shell-extension-pop-shell intel-gpu-tools
                           libnatpmp liquidctl podman-compose
            LocalPackages: lact-libadwaita-0.5.2-0.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:6abfef984f8e08f596cafa7e967328e59194aece8b4dc95772e32a48c3822b6f
                  Version: 39.20240312.0 (2024-03-12T17:04:38Z)
          LayeredPackages: coolercontrol gnome-shell-extension-pop-shell intel-gpu-tools
                           libnatpmp liquidctl podman-compose
            LocalPackages: lact-libadwaita-0.5.2-0.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"'
```

### Hardware

GPU: AMD RX 6600 and iGPU from the Intel CPU
CPU: Intel Core i5-14600k
RAM: 64GB

### Extra information or context

When using something like GOverlay it will show GPU stat but for the iGPU via ``intel_gpu_top`` from the ``intel-gpu-tools`` package that was layered to fix a error in the terminal

**Comment by HikariKnight** [comment]
change the layout in `goverlay` or change your presets in `.config/MangoHud/presets.conf`

as an example here is my presets.conf
```ini
[preset 2]
legacy_layout=0
horizontal
fps
frametime=0
frame_timing=1
gpu_stats
gpu_temp
cpu_stats
cpu_temp
#cpu_power
gpu_power
ram
time
time_format=%H:%M
hud_no_margin
table_columns=14
```

**Comment by blonde0091** [comment]
Hello I tried your config and still received the same result as previously mentioned. Also tried using goverlay to generate a config with all the gpu toggles on and no visual stat is showing

Should have posted my MangoHud config before but here is mine generated with goverlay

```
################### File Generated by GOverlay ###################

toggle_fps_limit=F1


legacy_layout=false
gpu_stats
gpu_temp
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_text=GPU
cpu_stats
cpu_temp
cpu_load_change
core_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_color=2e97cb
cpu_text=CPU
io_color=a491d3
vram
vram_color=ad64c1
ram
ram_color=c26693
fps
engine_color=eb5b5b
gpu_color=2e9762
wine_color=eb5b5b
frame_timing=1
frametime_color=00ff00
media_player_color=ffffff
background_alpha=0.4
font_size=24

background_color=020202
position=top-left
text_color=ffffff
round_corners=0
#GOVERLAY_THEME=mangohuddefault
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
upload_log=F5
output_folder=/home/max
media_player_name=spotify
```


![Screenshot from 2024-03-19 12-05-23](https://github.com/ublue-os/bazzite/assets/118260621/2fdb2f9a-467e-4ba4-ac5d-d3543a06dab8)

**Comment by HikariKnight** [comment]
At which point i will just say wait for mangohud to fix it as this sometimes happens

**Comment by blonde0091** [comment]
Hello,

Since my last post I reinstalled bazzite-stable and it seems to be normal now I do not know what happen in the background

**Comment by HikariKnight** [comment]
ok thats good then
