### ISSUE TITLE
Performance after suspend

### ISSUE THREAD

**Issue by lowpayne** [ublue-os/bazzite#885]
### Describe the bug

Hello 
I Got sometimes problem with performance after waking up device from sleep mode.I was playimg Dmc V fps cpunter 48 when I woke up device fps was udner 40, Bazzite os stable 

### What did you expect to happen?

Solution

### Hardware

Legion go

**Comment by lm209** [comment]
You can install SimpleDeckyTDP for Decky Loader and change to Performance Mode
