### ISSUE TITLE
Make the Super Key of keyboard to open the menu in GameMode

### ISSUE THREAD

**Issue by Ganipotes** [ublue-os/bazzite#886]
### Describe the bug

Without a controller, in game mode it's not possible to open the menu after opening a game or an app.

Is it possible to make the super key/ windows key as an steam input to open the menu, to go back to home or to juste shutdown ?

### What did you expect to happen?

I expected the super key to open the menu like an steam input.

### Hardware

I'm using a home theater pc

**Comment by HikariKnight** [comment]
This is not something we control, this is a steam issue
