### ISSUE TITLE
Wrong language layout of physical keyboard in Game Mode

### ISSUE THREAD

**Issue by Ganipotes** [ublue-os/bazzite#887]
### Describe the bug

I prefer using azerty instead of qwerty.

In desktop mode I have the correct layout for my physical keyboard, in game mode I have the correct layout for the virtual keyboard.

But I don't have the correct layout in game mode for my physical keyboard.

### What did you expect to happen?

I expected in game mode that my physical keyboard to have the azerty layout like the virtual keyboard and like the physical keyboard in desktop mode. 

### Hardware

I'm using a home theater pc

**Comment by lm209** [comment]
You can Change it in settings-keyboard

**Comment by Ganipotes** [comment]
> [lm209](/lm209)

It changes only the virtual Keyboard

**Comment by lm209** [comment]
> > [lm209](/lm209)
> 
> It only modifies the virtual keyboard

Sry i readed it wrong. You can try to Add your Keyboard Layout in the Desktop Mode under settings-keyboard. There is a Tab for Layouts. Make Sure that your Layout is selected.

**Comment by HikariKnight** [comment]
this is an upstream gamescope issue, gamescope defaults to US keyboard and no way to change it.
you might have luck if you set the environment variable `XKB_DEFAULT_LAYOUT=no` replacing `no` with the correct layout for you.
you can add this to `/etc/environment` but i would recommend testing this in desktop mode first before applying it to the whole system.

This works on desktop mode for things running in nested gamescope, but it has its own quirks (like `altgr+2` to write `@` on the norwegian layout will still not work, but the basic keyboard layout works as long as i do not need to use `altgr` which in normal typing you will not need it, at least for the norwegian layout)
not sure if the same thing will work for gamescope-session though

**Comment by Ganipotes** [comment]
> this is an upstream gamescope issue, gamescope defaults to US keyboard and no way to change it. you might have luck if you set the environment variable `XKB_DEFAULT_LAYOUT=no` replacing `no` with the correct layout for you. you can add this to `/etc/environment` but i would recommend testing this in desktop mode first before applying it to the whole system.
> 
> This works on desktop mode for things running in nested gamescope, but it has its own quirks (like `altgr+2` to write `@` on the norwegian layout will still not work, but the basic keyboard layout works as long as i do not need to use `altgr` which in normal typing you will not need it, at least for the norwegian layout) not sure if the same thing will work for gamescope-session though

THANK YOU A LOT!

It worked!

And as a bonus, altgr works for the french layout

**Comment by HikariKnight** [comment]
> And as a bonus, altgr works for the french layout
lucky, im jealous 😂

**Comment by unchartedpopsicle** [comment]
Just popping in to say that altgr+2 properly types "@" on my Norwegian keyboard in game mode with "XKB_DEFAULT_LAYOUT=no".

**Comment by HikariKnight** [comment]
> Just popping in to say that altgr+2 properly types "@" on my Norwegian keyboard in game mode with "XKB_DEFAULT_LAYOUT=no".

huh i need to check, maybe it has been fixed finally
EDIT: you are correct, altgr is now fixed in the norwegian layout in gamescope 🎉
