### ISSUE TITLE
40 hz option Legion Go

### ISSUE THREAD

**Issue by lowpayne** [ublue-os/bazzite#890]
### Describe the package

Hi it is pościele to set 40 hz refresh rate on legion go ? I rember playing it on steam deck and it was sweet spot for playing i thosesettings.Ps i realy realiy like bazzite great work 

### Image

Desktop

**Comment by lm209** [comment]
> ### Describe the package
> Hi it is pościele to set 40 hz refresh rate on legion go ? I rember playing it on steam deck and it was sweet spot for playing i thosesettings.Ps i realy realiy like bazzite great work
> 
> ### Image
> Desktop

I don't know if this working on the Legion go, but try to deactivate "unified frame limit management" in the Developer Settings.

**Comment by lowpayne** [comment]
No its not working , you can adjust refresh rate between 60 and 144 but everything betwen those values crashes screen so I was wondering is there any fix or posibility in the future
