### ISSUE TITLE
Hello!  how to update wine from 7 to the latest version?

### ISSUE THREAD

**Issue by aelev** [ublue-os/bazzite#891]
### Describe the bug

I can't install a Windows application on my desktop.  Wine from an outdated version of the store, winezgui crashes immediately after turning it on, which does not allow you to perform any actions in the program.  Installing the repository from the console gives an error.

### What did you expect to happen?

I expected that, as in the example on Ubuntu, everything would work without any problems

**Comment by KyleGospo** [comment]
Use Lutris or WineZGUI, wine-core is only present for Lutris dependency reasons.

**Comment by HikariKnight** [comment]
> The point is that you need to add an application, not a game. The games work out of the box and that's cool. I've tried different distributions, but they are not very stable. Yours is the most stable and easy to install. Am I correct in understanding that you are not planning to add full support for Wine? And I will try the bottles as you advise me.

bottles works fine for applications, you should never have to use system wine.
