### ISSUE TITLE
Rog Ally Gyroscope not working properly

### ISSUE THREAD

**Issue by frohrbaugh** [ublue-os/bazzite#894]
Issue with Gyroscope on latest baste install with KDE desktop on Rog Ally. 

Seems gyro is there, but it doesn't properly move joystick or mouse functionality. Calibration doesn't help in the steam OS either.

For example, you turn on the gyro with toggle and it kinda kicks on but goes in weird directions briefly then stops.

**Comment by antheas** [comment]
Can you join the discord and open a help thread? We are lacking too much context here. As of the latest Bazzite, even steam calibration should work.

If not, try to post a video of advanced calibration settings showing the gyro moving.

**Comment by frohrbaugh** [comment]
Thank you will do! I'm lp reimagine the Rog Ally with a new hard drive, so I will see if it persists if not I'll close the issue and mark it as user error.

**Comment by frohrbaugh** [comment]
Yep, I just botched some install steps. Thank you guys really appreciate everything this is been so helpful in my personal life. ❤️✌️
