### ISSUE TITLE
Getting Beta Update notifications that don't apply, while on Stable Channel

### ISSUE THREAD

**Issue by dschibster** [ublue-os/bazzite#898]
### Describe the bug

I was previously facing a steam client stable channel update that failed to apply despite hitting the "Apply" button and then restarting Steam. It kept being displayed after checking for updates.

In another attempt to resolve this I temporarily switched to the Beta Client. This broke Decky, so I went back to Stable. Now I still get a notification about an update on the Beta channel. Not getting applied despite hitting the Apply Button. The Update just says "OS" without a number. Not sure if this is a Steam Client or a bazzite issue. 

### What did you expect to happen?

Expected it to either apply the update or only show me updates for the stable channel

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
* ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:75e4e3d9f49670ddde7de2cab58595158b191c47e48200b7561da82c30e7e973
                  Version: 39.20240315.0 (2024-03-15T23:48:09Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:c82a3f095b79bc57db0f48ef5863123237b13ce1b116aaa73c337564231fbf76
                  Version: 39.20240315.0 (2024-03-15T17:03:34Z)
                Initramfs: '"-I```
```

### Hardware

Lenovo Legion Go

### Extra information or context

I had issues applying updates on the stable channel too beforehand. But after changing channels once it seems like it isn't showing me the stable channel ones at all anymore

**Comment by HikariKnight** [comment]
try manually updating through `system updater` in desktop mode or using `ujust update` from the desktop terminal and see if that works first :slightly_smiling_face:

**Comment by dschibster** [comment]
Good to know! `ujust update` also did the trick of removing the notification as it seems.
