### ISSUE TITLE
Wrong version of packages `kernel-headers` and `kernel-devel`

### ISSUE THREAD

**Issue by napaalm** [ublue-os/bazzite#899]
### Describe the bug

Today I tried to build a kernel module but its Makefile couldn't find my KDIR.
After a bit of investigation I checked the versions of kernel-related packages with `rpm -qa | grep kernel`, and as you can see `kernel-headers` and `kernel-devel` have the wrong version.
```
kernel-tools-libs-6.7.9-200.fc39.x86_64
kernel-tools-6.7.9-200.fc39.x86_64
kernel-modules-core-6.7.9-204.fsync.fc39.x86_64
kernel-uki-virt-6.7.9-204.fsync.fc39.x86_64
kernel-modules-6.7.9-204.fsync.fc39.x86_64
kernel-core-6.7.9-204.fsync.fc39.x86_64
kernel-6.7.9-204.fsync.fc39.x86_64
kernel-modules-extra-6.7.9-204.fsync.fc39.x86_64
kernel-headers-6.7.9-207.fsync.fc39.x86_64
kernel-devel-6.7.9-207.fsync.fc39.x86_64
kernel-srpm-macros-1.0-20.fc39.noarch
```

### What did you expect to happen?

The output of `rpm -qa | grep kernel` should contain packages that have the same version number.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:d0599bed0fcc05527392d9ce95ff758de1f0ddf48e1ef059815498f65b962d25
                  Version: 39.20240116.0 (2024-03-19T17:03:05Z)
          LayeredPackages: htop sunshine
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" '

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:142881fb1b347c93c76ab9485ebf0f2a617ae90423f814e587ca2bcde2f4a2bc
                  Version: 39.20240116.0 (2024-03-19T07:34:28Z)
          LayeredPackages: htop sunshine
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" '
```

**Comment by napaalm** [comment]
Here's the output of other methods I tried to install the right version.
```
$ sudo rpm-ostree install kernel-devel-uname-r
error: "kernel-devel-uname-r" is already provided by: kernel-devel-6.7.9-207.fsync.fc39.x86_64. Use --allow-inactive to explicitly require it.
```
```
$ sudo rpm-ostree install kernel-devel-6.7.9-204.fsync.fc39.x86_64
Checking out tree 8cb7d6b... done
Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:matte-schwartz:sunshine copr:copr.fedorainfracloud.org:sentry:kernel-fsync updates fedora rpmfusion-free-updates-testing rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates-testing rpmfusion-nonfree-updates rpmfusion-nonfree updates-archive
Importing rpm-md... done
rpm-md repo 'copr:copr.fedorainfracloud.org:matte-schwartz:sunshine' (cached); generated: 2024-03-14T11:25:33Z solvables: 2
rpm-md repo 'copr:copr.fedorainfracloud.org:sentry:kernel-fsync' (cached); generated: 2024-03-25T09:10:03Z solvables: 42
rpm-md repo 'updates' (cached); generated: 2024-03-25T01:01:46Z solvables: 24485
rpm-md repo 'fedora' (cached); generated: 2023-11-01T00:12:39Z solvables: 70825
rpm-md repo 'rpmfusion-free-updates-testing' (cached); generated: 2024-03-24T12:21:43Z solvables: 0
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2024-03-24T12:21:36Z solvables: 170
rpm-md repo 'rpmfusion-free' (cached); generated: 2023-11-04T16:49:08Z solvables: 445
rpm-md repo 'rpmfusion-nonfree-updates-testing' (cached); generated: 2024-03-24T12:46:45Z solvables: 4
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2024-03-24T12:45:42Z solvables: 73
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2023-11-04T17:26:32Z solvables: 208
rpm-md repo 'updates-archive' (cached); generated: 2024-03-25T01:29:06Z solvables: 37501
error: Packages not found: kernel-devel-6.7.9-204.fsync.fc39.x86_64
```
Can I actually use this mismatched version of `kernel-devel` to build my kernel module?

**Comment by KyleGospo** [comment]
We're intentionally holding fsync updates back for stability reasons, so you'll need to be explicit about versioning when installing the headers.

Testing as of today has the newest fsync if you want to rebase.

**Comment by napaalm** [comment]
> We're intentionally holding fsync updates back for stability reasons, so you'll need to be explicit about versioning when installing the headers.

@KyleGospo unfortunately I'm not able to install the correct version, as `rpm-ostree` returns
```
error: Packages not found: kernel-devel-6.7.9-204.fsync.fc39.x86_64
```

**Comment by napaalm** [comment]
Also, I think there's a misunderstanding here as I didn't install anything: the base image itself ships with these mismatched packages.

**Comment by napaalm** [comment]
https://github.com/ublue-os/bazzite/blob/2c8bfc371b6a5e93364a5680ca6d6333b4d0b6fd/Containerfile#L45-L57

I see that here you don't install `kernel-devel` and `kernel-headers` explicitly, so how are these included in the image, @KyleGospo?

**Comment by naanlizard** [comment]
Still broken, afaict

**Comment by KyleGospo** [comment]
> Still broken, afaict
> 
> ```
> garrett@garrettbazzite:/var/home/garrett$ rpm-ostree install kernel-devel-matched
> Checking out tree a56a2e5... done
> Enabled rpm-md repositories: copr:copr.fedorainfracloud.org:matte-schwartz:sunshine copr:copr.fedorainfracloud.org:rodoma92:kde-cdemu-manager copr:copr.fedorainfracloud.org:rodoma92:rmlint copr:copr.fedorainfracloud.org:rok:cdemu fedora-cisco-openh264 updates fedora rpmfusion-free-updates-testing rpmfusion-free-updates rpmfusion-free copr:copr.fedorainfracloud.org:jstaf:onedriver updates-archive
> Importing rpm-md... done
> rpm-md repo 'copr:copr.fedorainfracloud.org:matte-schwartz:sunshine' (cached); generated: 2024-08-12T09:06:28Z solvables: 2
> rpm-md repo 'copr:copr.fedorainfracloud.org:rodoma92:kde-cdemu-manager' (cached); generated: 2024-04-20T12:39:00Z solvables: 12
> rpm-md repo 'copr:copr.fedorainfracloud.org:rodoma92:rmlint' (cached); generated: 2024-05-10T10:16:28Z solvables: 4
> rpm-md repo 'copr:copr.fedorainfracloud.org:rok:cdemu' (cached); generated: 2024-07-09T09:13:21Z solvables: 23
> rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-03-12T11:45:42Z solvables: 3
> rpm-md repo 'updates' (cached); generated: 2024-09-05T04:02:32Z solvables: 25968
> rpm-md repo 'fedora' (cached); generated: 2024-04-14T18:51:11Z solvables: 74881
> rpm-md repo 'rpmfusion-free-updates-testing' (cached); generated: 2024-09-03T10:25:26Z solvables: 5
> rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2024-09-03T10:25:02Z solvables: 156
> rpm-md repo 'rpmfusion-free' (cached); generated: 2024-04-20T12:11:51Z solvables: 422
> rpm-md repo 'copr:copr.fedorainfracloud.org:jstaf:onedriver' (cached); generated: 2024-02-12T13:50:08Z solvables: 4
> rpm-md repo 'updates-archive' (cached); generated: 2024-08-21T03:52:59Z solvables: 36142
> Resolving dependencies... done
> error: Could not depsolve transaction; 1 problem detected:
>  Problem: conflicting requests
>   - package kernel-devel-matched-6.10.7-200.fc40.x86_64 from updates requires kernel-core = 6.10.7-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.8.5-301.fc40.x86_64 from fedora requires kernel-core = 6.8.5-301.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.10.3-200.fc40.x86_64 from updates-archive requires kernel-core = 6.10.3-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.10.4-200.fc40.x86_64 from updates-archive requires kernel-core = 6.10.4-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.10.5-200.fc40.x86_64 from updates-archive requires kernel-core = 6.10.5-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.8.10-300.fc40.x86_64 from updates-archive requires kernel-core = 6.8.10-300.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.8.11-300.fc40.x86_64 from updates-archive requires kernel-core = 6.8.11-300.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.8.7-300.fc40.x86_64 from updates-archive requires kernel-core = 6.8.7-300.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.8.8-300.fc40.x86_64 from updates-archive requires kernel-core = 6.8.8-300.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.8.9-300.fc40.x86_64 from updates-archive requires kernel-core = 6.8.9-300.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.10-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.10-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.11-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.11-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.12-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.12-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.4-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.4-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.5-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.5-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.6-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.6-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.7-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.7-200.fc40, but none of the providers can be installed
>   - package kernel-devel-matched-6.9.9-200.fc40.x86_64 from updates-archive requires kernel-core = 6.9.9-200.fc40, but none of the providers can be installed
>   - cannot install both kernel-core-6.10.7-200.fc40.x86_64 from updates and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.8.5-301.fc40.x86_64 from fedora and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.10.3-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.10.4-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.10.5-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.8.10-300.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.8.11-300.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.8.7-300.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.8.8-300.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.8.9-300.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.10-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.11-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.12-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.4-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.5-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.6-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.7-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
>   - cannot install both kernel-core-6.9.9-200.fc40.x86_64 from updates-archive and kernel-core-6.9.12-205.fsync.fc40.x86_64 from @System
> garrett@garrettbazzite:/var/home/garrett$ uname -r
> 6.9.12-205.fsync.fc40.x86_64
> garrett@garrettbazzite:/var/home/garrett$ lsb_release -a
> LSB Version:    n/a
> Distributor ID: Bazzite
> Description:    Bazzite 40 (FROM Fedora Kinoite)
> Release:        40
> Codename:       Holographic
> ```

Need to install the fsync repo and kernel-ba repo, they aren't included OOTB.

**Comment by naanlizard** [comment]
Could you point me in the right direction for how to do that? I'm only particularly experienced with debian/apt, and especially not atomic stuff like rpm-ostree
