### ISSUE TITLE
Steam Deck (updated today 2024-03-25) Quick Settings -> Power == failure / hang

### ISSUE THREAD

**Issue by dperson** [ublue-os/bazzite#913]
### Describe the bug

On my Steamdeck running a just updated Steam and Bazzite (from the desktop mode), when selecting Quick Settings (... button) -> Power goes to a black screen saying:

Something went wrong while displaying this content. Refresh
Error Reference: Shared SteamUI_8784974_ee66de96e7c0db0e
Cannot read properties of undefined (reading 'Title')

### What did you expect to happen?

I expected to get a menu with power management options for the Steamdeck.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:79d763a11d2c16957bfb18cc1129bc9ec62b23909ad37f42ce94996eeacb00e9
                  Version: 39.20240323.0 (2024-03-24T06:07:55Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:7aed142e6e6de844a38a5519c921be255cc4687efe9a7fc9c2249e107b8f6c60
                  Version: 39.20240322.0 (2024-03-22T16:57:45Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" '
```

### Hardware

Steamdeck (original non-OLED) with 2tb Micron NVME

**Comment by KyleGospo** [comment]
Are you using the beta steam client or any plugins via decky? I am unable to reproduce this on my LCD or OLED.

**Comment by dperson** [comment]
Sorry, yes I've been on the beta stream since my pre-ordered Steamdeck finally arrived.

**Comment by dperson** [comment]
Changed to stable and it works! But FYI, decky will break soon...

**Comment by gclawes** [comment]
I'm getting this on a stable install of `bazzite-deck-gnome`

**Comment by KyleGospo** [comment]
> I'm getting this on a stable install of `bazzite-deck-gnome`

On a steam deck?

**Comment by gclawes** [comment]
Yes
