### ISSUE TITLE
Decky plugin desktop install toggle no longer there

### ISSUE THREAD

**Issue by denver8989** [ublue-os/bazzite#914]
### Describe the bug

Silly one After reinstalling bazzite kde I lost the decky install toggle from the desktop and for some reason it didn't load whilst I was offline, maybe steam updated so I couldn't fix it I'm not sure that would have worked offline though. 

### What did you expect to happen?

If I'm being silly and this is a dum maybe explain a way around this.

**Comment by KyleGospo** [comment]
Decky is present in ujust, you can reinstall from there.
