### ISSUE TITLE
Back of the list bust top of my wishlist fsr3 mods

### ISSUE THREAD

**Issue by denver8989** [ublue-os/bazzite#915]
### Describe the bug

Fsr 3 mod from lukefz working perfectly on deck following all the same instructions fails to work on bazzite os with a legion go running decky plug in and hdd legion go remapper simpletdp

### What did you expect to happen?

Does anyone out there on the dev team have any idea what could be causing this, I'm hoping for a Linux genius fan of handhelds steam os and fsr3 to come out and say why know why this is happening well fingers crossed.

**Comment by KyleGospo** [comment]
Closed as duplicate
