### ISSUE TITLE
Back of the list top of my wishlist fsr3 mods steamos. 

### ISSUE THREAD

**Issue by denver8989** [ublue-os/bazzite#916]
### Describe the bug

Fsr 3 mod from lukefz working perfectly on deck following all the same instructions fails to work on bazzite os with a legion go running decky plug in and hdd legion go remapper simpletdp

### What did you expect to happen?

Does anyone out there on the dev team have any idea what could be causing this, I'm hoping for a Linux genius fan of handhelds steam os and fsr3 to come out and say why know why this is happening well fingers crossed.

**Comment by KyleGospo** [comment]
Can you provide the instructions you followed?

**Comment by denver8989** [comment]
Hi thank you so much for even replying to my silly issues you probably have bigger issues, I followed these instructions for the horizon forbidden west a YouTube and discord member by the name of grown up gaming and lukefz discord info for other mods which all worked on windows before hand needed extra launch instructions and a protontricks reg enable file.
https://youtu.be/phhPPPaSJO4
I love your work with bazite and aarron tricks too

**Comment by nicknamenamenick** [comment]
@denver8989 There's other channels outside of announcements.  

Here is the link directly to the Bazzite channel: 
https://discord.bazzite.gg/
