### ISSUE TITLE
Adding CDEmu for easier CD image mounting experience for old games

### ISSUE THREAD

**Issue by RodoMa92** [ublue-os/bazzite#919]
### Describe the package

I'd like to request the package `cdemu` because a lot of older/abandonware games need ISO mounting and the current experience is usually be forced to first convert them back to ISO (if even possible) and then mount them. On KDE desktops it's even more jank since half of the times when right clicking and mounting an image it will not show up on the dolphin resources page and you will have to close Dolphin and reopen it again each time.

The current supported images and container formats can be found here: https://cdemu.sourceforge.io/about/libmirage/
A GUI companion app to manage the daemon is provided for GTK desktops: https://cdemu.sourceforge.io/about/gcdemu/
A GUI companion app for KDE desktops is provided instead as a third party software: https://www.linux-apps.com/p/998461

A good starting point to port this to Bazzite is the official Fedora copr repository provided by CDEMU itself: https://copr.fedorainfracloud.org/coprs/rok/cdemu

### Image

Deck

**Comment by if-shouldrs** [comment]
for anyone landing here from a search:
this was added as a ujust command `ujust setup-cdemu`, so just run that and install.

could find that out navigating the linked PR's and comments but yeah was personally pretty confused when landing here

**Comment by megas64** [comment]
> for anyone landing here from a search: this was added as a ujust command `ujust setup-cdemu`, so just run that and install.
> 
> could find that out navigating the linked PR's and comments but yeah was personally pretty confused when landing here

was this removed as entering the command brings back a does not exist error

**Comment by RodoMa92** [comment]
> > for anyone landing here from a search: this was added as a ujust command `ujust setup-cdemu`, so just run that and install.
> > could find that out navigating the linked PR's and comments but yeah was personally pretty confused when landing here
> 
> was this removed as entering the command brings back a does not exist error

AFAIK no, I'll check it when I can.

**Comment by if-shouldrs** [comment]
> > for anyone landing here from a search: this was added as a ujust command `ujust setup-cdemu`, so just run that and install.
> > could find that out navigating the linked PR's and comments but yeah was personally pretty confused when landing here
> 
> was this removed as entering the command brings back a does not exist error

I no longer see the option when grep'ing ujust on one of the latest updates, so yes I believe it's been removed

**Comment by RodoMa92** [comment]
Yeah, found the source here: https://github.com/ublue-os/bazzite/commit/06eee209666aad5888330ddd4035f5a0e5119590. Not sure why, since you still can manually install it. Maybe @KyleGospo can shed light on it.

**Comment by megas64** [comment]
would be nice to know how i can go about installing it as i just cannot get the vhba module to install due to bazzite been immutable

**Comment by RodoMa92** [comment]
Yeah, I've tested it again and it does seem to have issues installing the module on Fedora 44. I'll let you know if I can understand why it's not installing.

**Comment by RodoMa92** [comment]
@megas64 @if-shouldrs Feel free to follow #5137 for updates, seems that either akmods are unsupported on the new ogc kernel or the removal from [here](https://github.com/ublue-os/akmods/pull/414) broke the install for them.
