### ISSUE TITLE
Signal problem

### ISSUE THREAD

**Issue by aelev** [ublue-os/bazzite#920]
### Describe the bug

Bazzite OS is installed on a PC connected to the TV.. If you first turn on the PC and then the TV, then the black screen, if in the reverse order, then everything is fine. The only thing that helps is rebooting with the power button or the keyboard shortcut Ctrl+Alt+Del.

### What did you expect to happen?

I don't think this should happen.

**Comment by SamlRx** [comment]
Is it working using a different linux distribution or using Windows ? Did you try with another HDMI cable ?

**Comment by aelev** [comment]
Before this, I installed Chimera OS with the same cable and did not experience such a problem.
