### ISSUE TITLE
Ability to change CPU govnor

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#923]
### Describe the package

can you give us the ability to change cpu govnor, some games that drop cpu frequency tend to stutter or have low fps cause the cpu is at 12mhz instead of max when gaming, in dota i look almost 20fps and when figth starts it drops to like the 40s, but when i enter performance mode everything works really well.

### Image

Desktop

**Comment by KyleGospo** [comment]
There are numerous third party tools you can use to do this, and TuneD can be adjusted as well. 

By default we recommend balanced, performance can actually reduce gaming performance on modern CPUs due to reduced headroom for single core clock boosting.

**Comment by massatt212** [comment]
TuneD doesnt save on reboot, thats my main problem.

**Comment by KyleGospo** [comment]
> TuneD doesnt save on reboot, thats my main problem.

You can change the profile set in boot in tuned-ppd. Again, we highly recommend leaving it at balanced for gaming.

**Comment by massatt212** [comment]
> > TuneD doesnt save on reboot, thats my main problem.
> 
> You can change the profile set at boot in tuned-ppd. Again, we highly recommend leaving it at balanced for gaming.

well my cpu at balance works terrible in almost every game, i think you should give us a choice, like an option that can be turned on or off.

**Comment by massatt212** [comment]
i have an i5-6500 and its terrible when playing fighting games and dota, all i want is the ability to permanently set cpu govnor to performance, so i dont have to get a keyboard to go to desktop mode and launch a game in performance mode, im sure others will love the option to enable and disable performance mode.
