### ISSUE TITLE
[bazzite-deck-gnome 39.20240328] Waydroid fails to start: [gbinder] WARNING: Service manager /dev/binder has died

### ISSUE THREAD

**Issue by jpwchang** [ublue-os/bazzite#925]
### Describe the bug

After I ran a system upgrade to bazzite-deck-gnome 39.20240328, my previously working Waydroid installation now fails to start. Running Waydroid (whether through `waydroid-launcher` or directly through `waydroid show-full-ui` in desktop mode) causes the Android boot animation to appear for a few seconds before the window closes. On the command line, I see the error message `[gbinder] WARNING: Service manager /dev/binder has died`.

Some things I tried, which did not solve the problem:
- Upgrading the Waydroid image
- Adding the `psi=1` kernel parameter, per https://github.com/waydroid/waydroid/issues/136

I can also confirm that if I boot into my previous deployment, 39.20240323, Waydroid runs fine there, so it definitely seems to be a problem caused by something in this system update. It is worth noting that the latest bazzite image, where Waydroid is not working, is on kernel version 6.7.9-207, whereas my previous deployment 39.20240323, where Waydroid works fine, is on kernel version 6.7.9-204. I wonder if this might be related, given that the discussions about the error on the Waydroid github all seem to suggest that the error arises from various kernel-related issues.

### What did you expect to happen?

Waydroid should start / the binder service should not die

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:bc18ac57e443ab2f930af7025d02fa9c4ac7d8fabd98d99047a7ce0e5bd99b9c
                  Version: 39.20240328.0 (2024-03-28T22:31:50Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:bc18ac57e443ab2f930af7025d02fa9c4ac7d8fabd98d99047a7ce0e5bd99b9c
                  Version: 39.20240328.0 (2024-03-28T22:31:50Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:758742680bc0f70d2be8ee22f35e3e01c25af9a21990254c479b40e8019456f4
                  Version: 39.20240323.0 (2024-03-24T06:08:25Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 
                   Pinned: yes
```

### Hardware

Steam Deck LCD
```
$ cat /sys/devices/virtual/dmi/id/product_name
Jupiter
```

**Comment by HikariKnight** [comment]
Upstream issue with waydroid itself.
current solution is wait for them to fix it or rebase to older image

It broke sometime late last month so an image around 20240325 should get you a working waydroid until they fix it upstream

**Comment by MaderHatt3r** [comment]
I couldn't figure out how to override the kernel mostly because I couldn't find a download for the known working kernel, but I was able to rollback to the image listed by OP and can confirm that PSI works on this image/ kernel and that waydroid can startup.

**Comment by HikariKnight** [comment]
@MaderHatt3r @jpwchang managed to verify it myself while i was at work (conveniently had an older image installed due to holidays and remote work) and i have forwarded the issue to the correct person on the team

**Comment by Barrettloganj13** [comment]
It also effects the kde version as well.

**Comment by HikariKnight** [comment]
> please fix

this is not helpful, especially when the bug has been identified and forwarded to the right people.

Either way from what i understood there was a new scheduler included in the kernel build which wiped out the PSI config entirely, even though we had set `CONFIG_PSI=y` the whole config got just deleted during the build due to the scheduler not being compatible with it.

a new build is now available which fixes waydroid and uses a different compatible scheduler

**Comment by KyleGospo** [comment]
Fixed in the latest build
