### ISSUE TITLE
Legion go Terminal apps will no longer launch as well as bazzite update

### ISSUE THREAD

**Issue by denver8989** [ublue-os/bazzite#929]
### Describe the bug

Legion go bazzite kde I can no longer launch the following apps ptyxis or other terminal and bazzite up so I can't update unless I do a fresh install, I haven't done anything much since installing I don't know what caused this. Error E Plasma Desktop Workspace
Launching Ptyxis (Failed)
Could not activate remote peer: unit failed.
![IMG_20240330_215946](https://github.com/ublue-os/bazzite/assets/134750112/76b71322-f7ef-4dca-bdf3-78c047558871)

### What did you expect to happen?

Tips on how to fix this report it if it's a known issue. 

### Hardware

Legion go

**Comment by KyleGospo** [comment]
This was a dependency issue found in yesterday's build and is already fixed. You can correct it by:

- Updating from gaming mode
- Updating from a TTY (`Control+Alt+F4`, enter username & password, `rpm-ostree update`)
- Waiting for an automatic update (Desktop builds only)

**Comment by denver8989** [comment]
Thank you that did the trick thank you :).
