### ISSUE TITLE
No configuration window after install 

### ISSUE THREAD

**Issue by Brunvik** [ublue-os/bazzite#93]
Had to reinstall bazzite (rebased from regular Kinoite) and the window to configure what you want installed doesn’t pop up

**Comment by KyleGospo** [comment]
Some things may be in flux as we prepare for a proper release, this is working for me in current builds but I'll update this issue when we're live for a re-test.

**Comment by Brunvik** [comment]
Did try again and it opened but seemingly problems with everything except Flatpak. But it opened!

**Comment by EyeCantCU** [comment]
@Brunvik what problems are you running into?

**Comment by KyleGospo** [comment]
Latest release for desktop should be all fixed, apologies again for the issues, made some breaking changes getting GNOME builds out before we move to a stable release schedule.

**Comment by Brunvik** [comment]
@KyleGospo I personally thank you! 

@EyeCantCU the script that should have been running after rebasing did not really work, at 2nd attempt did start but hat problems like not installing the Distrobox container for Steam and Lutris

**Comment by EyeCantCU** [comment]
This is probably because we unfortunately realized after introducing GNOME that DE specific files weren't being copied over. I wouldn't be surprised if an update fixes that

**Comment by EyeCantCU** [comment]
> @KyleGospo I personally thank you!
> 
> @EyeCantCU the script that should have been running after rebasing did not really work, at 2nd attempt did start but hat problems like not installing the Distrobox container for Steam and Lutris

Can you confirm if this is still a problem for you with the latest image? It should be worked out but I'd like to be sure

**Comment by EyeCantCU** [comment]
This is fixed now and a shortcut has been added to force yafti to run if for whatever reason theres weirdness
