### ISSUE TITLE
A virtual keyboard for the non nested desktop mode

### ISSUE THREAD

**Issue by denver8989** [ublue-os/bazzite#930]
### Describe the package

Hi I'm not so good with Linux and I failed to find anything good to install as a virtual keyboard the only way I've been able to use one is through the nested desktop, however I can't seem to do everything in the nested mode. This would be a game changer for me if there's an easy fix please let me know I'm using bazzite on a legion go with kde. 

### Image

Desktop

**Comment by KyleGospo** [comment]
Steam provides this, if you check the controller settings in the steam desktop app you should be able to bind a button to open the keyboard. I recommend X.

**Comment by denver8989** [comment]
Hi yes in nested desktop mode but not when switched to desktop mode and certain times I need to copy files tweak things and random errors come in nested mode as opposed to desktop mode.

**Comment by KyleGospo** [comment]
This should work in normal desktop mode too, so long as it's bound in Steam. Both the bound button and Steam + X. 

Could you post a screenshot of your controller settings while in the normal non-nested desktop?

**Comment by denver8989** [comment]
Oh wow completely missed this in the main settings my settings for desktop were disabled by default, found a legion go community layout works a treat thanks again! I feel like it's the perfect setup now the only drawbacks to using this os on a handheld "for me at least" are not being able to use fsr3 mods lossless upscaler and future amd afmf maybe there's an easy fix for the mod maybe the last 2 will have official implementations.
