### ISSUE TITLE
Start building against Fedora 40

### ISSUE THREAD

**Issue by FlyinPancake** [ublue-os/bazzite#934]
### Describe the bug

Fedora 40 Beta is now available <https://www.redhat.com/en/blog/fedora-40-beta-now-available>

Fedora 40 now ships KDE 6 which supports HDR for gaming, so it is crucial to start testing as soon as possible, since there are some breaking changes introduced.

`ublue/main` now builds a fedora 40 image <https://github.com/ublue-os/main/pkgs/container/kinoite-main/198110346?tag=40>

### What did you expect to happen?

I'd like to see `40-testing` images built against `ublue/main`.

**Comment by FlyinPancake** [comment]
Upstream tracks the issue over here

<https://github.com/ublue-os/main/issues/529>

**Comment by bsherman** [comment]
Done.
