### ISSUE TITLE
Gnome Files is not registered as a File Mananger

### ISSUE THREAD

**Issue by DonnyTheDuck** [ublue-os/bazzite#937]
### Describe the bug

I changed the icon for nautilus and now this notification keeps popping up every time I boot into to desktop.  Ive checked mimeapps.list and my MimeType in the .dekstop file is populated but i dont really know what looks right.  Nautilus works fine and it opens files as it should.
![Screenshot from 2024-04-02 12-47-17](https://github.com/ublue-os/bazzite/assets/152117371/2174970a-2676-4191-9a2a-d1f00a554dd6)

### What did you expect to happen?

I do not expect to see this notification every time i boot into desktop.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:bc18ac57e443ab2f930af7025d02fa9c4ac7d8fabd98d99047a7ce0e5bd99b9c
                  Version: 39.20240328.0 (2024-03-28T22:31:50Z)
                Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:latest
                   Digest: sha256:758742680bc0f70d2be8ee22f35e3e01c25af9a21990254c479b40e8019456f4
                  Version: 39.20240323.0 (2024-03-24T06:08:25Z)
                Initramfs: '-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf'
```

### Hardware

LCD Steam Deck 256gb upgraded to 1tb.

**Comment by KyleGospo** [comment]
Have you tried undoing your changes? I imagine you made a new desktop file to accomplish this.

**Comment by DonnyTheDuck** [comment]
Yes that was the first thing I did.  I can't make sense of it.  Apparently that error is from desktop gtk4 icons extension.  When I disable it, no more error, so I'll just use the original DING. Still a weird issue though

**Comment by DonnyTheDuck** [comment]
Yes that was the first thing I did.  I can't make sense of it.  Apparently that error is from desktop gtk4 icons extension.  When I disable it, no more error, so I'll just use the original DING, which works without the error. 
 Still a weird issue though, I'll probably keep playing with it
