### ISSUE TITLE
Onexplayer X1: Rotated screen on Gamescope 

### ISSUE THREAD

**Issue by Vibearz** [ublue-os/bazzite#940]
### Describe the bug

When on gamescope, the screen is rotated to the left. 
![IMG_7318](https://github.com/ublue-os/bazzite/assets/127532062/a1c52f58-0707-4f17-bed4-e5e184669012)

### What did you expect to happen?

It has to be on landscape mode

### Output of `rpm-ostree status`

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:fcad6fdb62c486723e6c4b71ed41fb0983a514fb940f086523428a3f2ff2c22d
                  Version: 39.20240329.0 (2024-03-30T05:28:57Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:fcad6fdb62c486723e6c4b71ed41fb0983a514fb940f086523428a3f2ff2c22d
                  Version: 39.20240329.0 (2024-03-30T05:28:57Z)

### Hardware
ONEXPLAYER X1 i

### Extra information or context

I can change to landscape on desktop mode, but it don’t persists when change to gamemode.

**Comment by toorukt** [comment]
Same situation for GPD Win Mini (2024).
I guess bacause these devices are with landscope display.

**Comment by steelbrain** [comment]
Fly-by comment: Adding this kernel arg would probably help here: https://github.com/ublue-os/bazzite/pull/1273/files#diff-ff316c0aa527a318cf3d8b45189e81674b7fc9b4b812fa07500c53e3b3efba33R112
