### ISSUE TITLE
No sound device on Onexplayer X1

### ISSUE THREAD

**Issue by Vibearz** [ublue-os/bazzite#941]
### Describe the bug

No sound device detected on OnexplayerX1 (Intel Ultra 7 155H)
![Screenshot_20240403_150502](https://github.com/ublue-os/bazzite/assets/127532062/f4b17cf6-5248-4cc2-9afa-c601c832da5f)

### What did you expect to happen?

It works on windows, but no on Bazzite. Also tried with CachyOS (Arch Based distro) and it doesn´t work here too.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:fcad6fdb62c486723e6c4b71ed41fb0983a514fb940f086523428a3f2ff2c22d
                  Version: 39.20240329.0 (2024-03-30T05:28:57Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:fcad6fdb62c486723e6c4b71ed41fb0983a514fb940f086523428a3f2ff2c22d
                  Version: 39.20240329.0 (2024-03-30T05:28:57Z)
```

### Hardware

ONEXPLAYER X1 i

**Comment by Zetarancio** [comment]
Have you tried the hdajackretask solution that I described here? 
https://www.reddit.com/r/ayaneo/comments/1bzwa15/linux_on_ayaneo_geek_1s2s_just_works/

**Comment by Vibearz** [comment]
> Have you tried the hdajackretask solution that I described here? https://www.reddit.com/r/ayaneo/comments/1bzwa15/linux_on_ayaneo_geek_1s2s_just_works/

It’s a known issue exclusive from this Onexplayer. It has an Harman audio amp that hasn’t been yet kernel implemented AFAIK.

**Comment by FearlessSpiff** [comment]
is this fixed by now?

**Comment by fss-hacks** [comment]
Please fix this. Onexplayer F1 Pro with no sound across all Linux distros.
