### ISSUE TITLE
[bazzite-nvidia] Constant freezing with kernel 6.7.11-201.fsync.fc39.x86_64 with heavy games

### ISSUE THREAD

**Issue by ZariTen** [ublue-os/bazzite#949]
### Describe the bug

This entire week i was playing games normally, without any problems. After todays update, any CPU heavy game is causing audio stutters and with Horizon: Zero Dawn my entire computer is freezing and on the system monitor i can see my CPU usage jumping to 100% and freezing the entire computer, often needing a reboot. Checking what happened today, i saw an update of the kernel and other components.

### What did you expect to happen?

Still play games normally, without any constant freezing and audio stutters.

### Output of `rpm-ostree status`

```shell
State: idle
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:f0354289abd57f60413e9b4a461298083d73118106ce2289defe081c888ec1c6
                  Version: 39.20240116.0 (2024-04-05T17:01:07Z)
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:330ecb5fbda007d21a5ed8d0b3c66d0c761f3eb7e220e0b1625cb068151003a4
                  Version: 39.20240116.0 (2024-04-05T03:56:53Z)
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" '
```

### Hardware

CPU: Intel i5 8400
GPU: Nvidia RTX 3060 12GB
RAM: 32 GB

**Comment by sarcasticgoat** [comment]
This is also occurring on the bazzite:latest image on my 5800x3d / 6900xt rig. I've reverted back to 39.20240329.0 temporarily.

**Comment by ZariTen** [comment]
Latest update to kernel 6.7.11-202.fsync.fc39.x86_64 seems to have fixed this issue. Might wanna test again @sarcasticgoat . Closing this issue!
