### ISSUE TITLE
Firefox Picture in Picture does not Stay On Top

### ISSUE THREAD

**Issue by slrgt** [ublue-os/bazzite#958]
### Describe the bug

When I click the Picture in Picture button on Firefox for videos they dont Stay On Top unless you right click and then click Stay On Top every time you launch a PiP video. 

### What did you expect to happen?

This usually happens by default when clicking PiP on videos on firefox.

**Comment by nicknamenamenick** [comment]
This is the default behavior for Firefox on Wayland.  Not sure if you're using KDE Plasma or GNOME, but there are workarounds for this.  

For KDE Plasma, read this: https://www.reddit.com/r/kde/comments/osjt3p/firefox_wayland_pip_workaround_or_how_i_learned/

If you're on GNOME, there's an extension.

**Comment by slrgt** [comment]
why was it closed though? A workaround isnt a fix
