### ISSUE TITLE
every other boot boots with usb and bluetooth broken and cant shut down

### ISSUE THREAD

**Issue by slrgt** [ublue-os/bazzite#960]
### Describe the bug

Every other time I boot into bazzite my wireless usb mouse\keyboard doesnt work, bluetooth doesnt work, and if i use kdeconnect to control the mouse and click shutdown the screen goes black with the bazzite logo on the bottom and stays frozen forever. I can't press esc to check boot messages because the mouse\keyboard dont work and kdeconnect disconnects at this point. 

### What did you expect to happen?

This only happens every other time i boot into bazzite. When this happens I forcefully shut off my pc and then it boots like normal and everything works.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                   Digest: sha256:2afc445458e106aab2db13cfea78afa908c0599516b5b9207d3c44b796a09859
                  Version: 39.20240116.0 (2024-04-07T01:32:51Z)
          LayeredPackages: nemo ulauncher
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                   Digest: sha256:2afc445458e106aab2db13cfea78afa908c0599516b5b9207d3c44b796a09859
                  Version: 39.20240116.0 (2024-04-07T01:32:51Z)
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" '
```

### Extra information or context

heres some screenshots from the Logs application (not sure if theyre relevant) and ill copy paste the sudo dmesg too

![Screenshot from 2024-04-08 13-21-15](https://github.com/ublue-os/bazzite/assets/114287507/50ff48d1-03b8-480f-8ba9-da197a0d066d)
![Screenshot from 2024-04-08 13-21-47](https://github.com/ublue-os/bazzite/assets/114287507/ec578789-432e-49cb-b07d-14cb5c67ff91)
![Screenshot from 2024-04-08 13-22-03](https://github.com/ublue-os/bazzite/assets/114287507/2f052bd7-3617-4ad6-9187-65d43e720ca3)

https://pastebin.com/rja07gwF

**Comment by aelev** [comment]
I have ongoing problems with the connection; my SteamController and Dualsense controller periodically fall off. It's very difficult to reconnect. There are strong stutters and delays when connecting. The microphone of the Bluetooth headset is also not displayed - the HFS/HFP profile is missing. In ChimeraOS the microphone was detected.

**Comment by KyleGospo** [comment]
> I'm having ongoing connection problems. My SteamController works via USB, the Dualsens controller via Bluetooth and both periodically fall off. It's very difficult to reconnect. There are strong stutters and delays when connecting. The microphone of the Bluetooth headset is also not displayed - the HFS/HFP profile is missing. In ChimeraOS the microphone was detected by default.

I don't see what any of this has to do with this issue, please open a new one or post in a similar one.

**Comment by kityr** [comment]
Kind of same here, but instead it's like every boot? My wireless mouse doesn't work over the usb dongle, I can't do usb tethering, and I cant properly shutdown or reboot. Also the webcam doesnt work either

**Comment by MrShelbySann** [comment]
I also have this issue, fresh install of Bazzite (AMD) yesterday. Card is Intel AX200 integrated to the motherboard.
dmesg output:
![Capture d’écran du 2024-04-11 11-10-54](https://github.com/ublue-os/bazzite/assets/132308328/60cbb2fc-6fc1-47e6-9b4a-cbf3e78e2458)

**Comment by Nitrousoxide** [comment]
I am also having this issue.  Able to enter in my decryption password fine and select a deployment, but once it gets to the login screen for Fedora it won't accept any USB or Bluetooth input.  Rebooting one or more times seems to fix it at least for a while.

```
rpm-ostree status
State: idle
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:ca205fdd24ad7ecbfad8f2a3ee5335dbf9ab2ddbfe29b85fb6fdc6821b0154ef
                  Version: 39.20240406.0 (2024-04-07T01:31:06Z)
          LayeredPackages: btrfs-assistant snapper
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"' 
```

**Comment by kityr** [comment]
> It could be kernel related. Vanilla Fedora is having that issue too, though a kernel update seems to be resolving it for them.
> 
> https://discussion.fedoraproject.org/t/unable-to-shut-down-system-after-latest-kernel-update/111543

Seems to be the case, since bazzite is stuck on 6.7.11 for now because of suspend issues on some device

**Comment by Nitrousoxide** [comment]
Issue still present in:
Kernel: Linux 6.7.11-202.fsync.fc39.x86_64
in the April 14th update.

**Comment by Nitrousoxide** [comment]
Since the update to the Linux 6.7.12-201.fsync.fc39.x86_64 kernel in 
```
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:90bdb9362b3f7a3e485f01047ffb6bb15f8d7d67d8b2e100e2fc22d7bfb22097
                  Version: 39.20240415.0 (2024-04-16T02:19:19Z)
          LayeredPackages: btrfs-assistant snapper
            LocalPackages: sunshine-0.21.0-1.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"'
```
I've not had any issues with booting or my usb/bluetooth.  If other folks also report it being remedied we might be able to close this issue.

**Comment by twaananen** [comment]
Trying a few reboots with the most recent version, booting and bluetooth issues seem to be fixed for me too.

**Comment by MattyPixels** [comment]
Looking good here too, on 6.7.12.

**Comment by slrgt** [comment]
now my wifi card isnt being detected on any boot so I can't update to 6.7.12

**Comment by telorand** [comment]
On an OLED Deck.

Rebased from `gnome:39-20240328` to `gnome:stable` (`39-20240415`) after seeing #950 closed. Bluetooth and sleep worked after the first reboot. I was excited, so I tried connecting my Steam Controller via BT. After everything seemed like it was working, I turned the controller off.

That's when the problems started. The built-in controller started going haywire: the Steam button was erratic, Dpad was intermittent, and when I went into the Settings to do a button test, all the inputs except the trackpads and sticks were detected. So I did a reboot again to try to fix it.

This time, navigating the menus was even harder. All the inputs except B, Option, Start, and the Dpad were detected (with B eventually stopping, too). Additionally, I could not get it to shutdown, restart, or boot into Desktop Mode, and there was no sound. The system menu showed no locale, no timezone, Bluetooth had no profiles, and the built-in controller was no longer detected. I forced a shutdown via long-press, and after reboot, BT is no longer working and sleep is still broken (possibly still related to #950 ).

A simple workaround for the Sleep issue seems to be:

- Turn off Bluetooth
- Reboot

This should re-enable Sleep mode until BT is turned on again.

**Comment by Moe1369** [comment]
Yup problem still occuring.  Any workarounds? Does arch based chimera have the same issue?

**Comment by telorand** [comment]
Again, on OLED Deck:

Bluetooth and Sleep/Suspend seem to be working again on `40-20240427`. There's still an outstanding issue with BT controllers causing BT to crash, but cycling BT off/on brings it back up. Audio devices seem to work correctly, and certain devices that couldn't pair before are now able to do so (https://github.com/bluez/bluez/issues/805).
