### ISSUE TITLE
Prism launcher or polymc does not work

### ISSUE THREAD

**Issue by grisha765** [ublue-os/bazzite#961]
### Describe the bug

I launch prism launcher or polymc via flatpack andget the error: 
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.qgnomeplatform: Could not find color scheme  ""
QtLockedFile::lock(): file is not opened
QtLockedFile::lock(): file is not opened

### What did you expect to happen?

Running program

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:99f91518ceafb75094bd0e5483672af4d13baa2ed4ffc0b009f1a6ff28226dca
                  Version: 39.20240406.0 (2024-04-07T01:32:16Z)
          LayeredPackages: htop libvirt virt-manager
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:b80881eba5a32958b67e9a2197cf1ce1958d6f19b726582d8f11976fe6d87317
                  Version: 39.20240406.0 (2024-04-06T22:25:27Z)
          LayeredPackages: htop libvirt virt-manager
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf" '
```

### Hardware

Jupiter

**Comment by KyleGospo** [comment]
Not able to reproduce here, maybe try a flatpak repair?

**Comment by KyleGospo** [comment]
![image](https://github.com/ublue-os/bazzite/assets/10704358/b95ef696-0fdf-4b71-bffd-06fc63b7cdc7)

**Comment by grisha765** [comment]
> flatpak repair

Tried it, didn't help
