### ISSUE TITLE
Asus ROG Ally Suspend issue

### ISSUE THREAD

**Issue by Toffy2323** [ublue-os/bazzite#966]
### Describe the bug

Hi, so I'm using the latest update of Rog ally Bazzite. I'm getting issues where if I press the power button, it fails to sleep, meaning the screen turns off but fans run and screen won't turn back on untill I hard reset. I checked if there was any updates but there are none. Using stable version.

### What did you expect to happen?

Suspend feature to turn screen off when pressing power button and turn back on when pressed again

### Output of `rpm-ostree status`

deck@fedora:~$ rpm-ostree status State: idle Deployments: o ostree-image-signedzdocker://ghcr.1o/ublue-os/bazzite-ally:stable Digest; sha256:3811db850410ff4c62176e1f5f6934ec6af2e261ea3eb2d03868bca55ad5107d Version: 39,20240406,0 (2024-04-07T01:33:19Z) Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf_ fetc/modprobe.d/deck-blackltst-conf" " ostree-image-signed;dockert//ghcr,1o/ublue-os/bazzfte-ally:stable Digest; sha256;3811db850410ff4c62176e1f5f6934ec6af2e261ea3eb2d03868bcassads1Q7d vers1on; 39,29249496,0 (2024-94-07701:331192) Initramfss ""-I /etc/crypttab /etc/modprobe.d/aldgpu.conf_/etc/modprobe.d/deck-blacklist.conf""

**Comment by Toffy2323** [comment]
Note reverted to rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:39-stable-20240220 to see if it fixes temporarily

**Comment by KyleGospo** [comment]
> Note reverted to rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:39-stable-20240220 to see if it fixes temporarily

Any luck with this image?

**Comment by Toffy2323** [comment]
Hi, the image works and no issues but there is performance issues with this one that was fixed by the newest one, wondering what to do?

**Comment by Toffy2323** [comment]
Also like to add, the work is amazing and I can't go back to windows on Rog ally again, you have a gold mine here if you can get it working universally

**Comment by Toffy2323** [comment]
Please do let me know a fix, would like to use the newest version if it didn't have suspend issues

**Comment by Toffy2323** [comment]
I'd like to report this old image is worse, power controls are not fixed compared to the newer, will have to switch back to newer and wait for a fix for suspend issues..

**Comment by Toffy2323** [comment]
Agreed with above, hope there's a fix soon. When it works it's amazing, there's slow down if you've left it suspended for a while, games just dont respond IE frames drop hard and even setting it to 30watts, so a restart fixes. I reinstalled the latest update and deleted some games which has resolved most suspend issues but get that slow down after resuspending so need to restart anyways

**Comment by acuteaura** [comment]
I'm seeing some other issues. Resume works most of the time, but the Ally-specific buttons break, making quick settings and the "Steam" button unavailable.

```
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-ally:stable
                   Digest: sha256:0ff1966f5cc33725bef997f04328591e91c3d851a4d09d92a88aca6681441ca3
                  Version: main (2024-04-25T06:48:54Z)
          LayeredPackages: 1password firefox
```
