### ISSUE TITLE
bazzite.gg marked as mallicious on virustotal

### ISSUE THREAD

**Issue by Mightymike033** [ublue-os/bazzite#971]
### Describe the bug

see https://www.virustotal.com/gui/url/fc99750cf9ccb3d733b4a1d345696a309d71a81881c8e4a15ee842eadde39e4e?nocache=1 

### What did you expect to happen?

That no antivirussoftware marks bazzite.gg as malicious.

**Comment by KyleGospo** [comment]
False positive, already submitted tickets and waiting for them to fix it.

**Comment by KyleGospo** [comment]
Heard back, should be fixed now. Waiting for change to propagate.

**Comment by KyleGospo** [comment]
Gonna close this, couple still consider it malicious but I can't fix bad code that isn't mine.
