### ISSUE TITLE
Mouse stopped working as of Version: 39.20240414.0 

### ISSUE THREAD

**Issue by DreamingCuttlefish** [ublue-os/bazzite#972]
### Describe the bug

When I booted into the new snapshot released today, April 14th 2024, my mouse (Logitech G900) was no longer responsive and the cursor would not move around when I moved my mouse. I tried different USB ports but that didn't make a difference, then I booted back into 20240406 and it worked fine. I've checked this twice and the same thing occurs. Oddly enough the mouse works fine when in wireless mode, but when in wired this issue occurs.

### What did you expect to happen?

I expected to be able to move my mouse on boot

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite
                   Digest: sha256:7375d08ac151a65a0c80cd8dece65aa42da500f3f0eb35041816cc1f805f13df
                  Version: 39.20240414.0 (2024-04-14T21:08:27Z)
            LocalPackages: lact-0.5.3-0.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf" ' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite
                   Digest: sha256:7c9d16a34d8192df6ba824198c2e2343faa8108d9b53e949cebeed4d849e2395
                  Version: 39.20240406.0 (2024-04-07T01:29:50Z)
            LocalPackages: lact-0.5.3-0.x86_64
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf" ' 
                   Pinned: yes
```

### Hardware

CPU: Ryzen 7800x3d
GPU: Radeon RX 6950xt
32gb Kingston RAM DDR5 6000
2tb Samsung 980pro
Gigabyte b650 gaming x ax motherboard.

### Extra information or context

I am not using solaar to manage mouse settings

**Comment by KaiserCalm** [comment]
Same here, both my mouse and keyboard do not function after booting into the latest update on kde on bazzite nvidia.

**Comment by KaiserCalm** [comment]
Strangely, this hae happened before at some point, but after a reboot it fixed itself. Not on this latest upeate though.

**Comment by DreamingCuttlefish** [comment]
> Same here, both my mouse and keyboard do not function after booting into the latest update on kde on bazzite nvidia.

Sorry to hear this but that's also interesting. What type of keyboard do you have? Mine's a Corsair K70 and works fine on this update.

**Comment by KaiserCalm** [comment]
> > Same here, both my mouse and keyboard do not function after booting into the latest update on kde on bazzite nvidia.
> 
> Sorry to hear this but that's also interesting. What type of keyboard do you have? Mine's a Corsair K70 and works fine on this update.

Yeah, it is. I have a Corsair K55.

**Comment by KyleGospo** [comment]
Is she found, it's upstream and effects Fedora as well. Patch is in the next kernel which is building now, we'll have a release out soon.

**Comment by boobbeepboop** [comment]
The mouse and keyboard don't work for me either. I can neither log in nor can I boot in text mode. This has never happened to me with F39 Silverblue and before and also under the new F40 Beta SB. I even did a complete reinstallation. Too bad, it's super annoying and funny at the same time that such an error happens at all.Maybe next year ;)

**Comment by DreamingCuttlefish** [comment]
> The mouse and keyboard don't work for me either. I can neither log in nor can I boot in text mode. This has never happened to me with F39 Silverblue and before and also under the new F40 Beta SB. I even did a complete reinstallation. Too bad, it's super annoying and funny at the same time that such an error happens at all. So this bug is still present in your Bazitte image.

That's odd. It resolved for me with the April 15th snapshot. I'll reopen the issue for you.

**Comment by mwdomino** [comment]
Fresh install today, downloaded `bazzite-nvidia-latest.iso` and install worked fine but after rebooting into the install USB Keyboard/Mouse are not working at all. Corsair mouse + Razer keyboard.

Would grab additional details but I can't log in to get them :)
