### ISSUE TITLE
upgrade success but reboot failed

### ISSUE THREAD

**Issue by zhouxingoddog312** [ublue-os/bazzite#978]
### Describe the bug

When i upgrade the system, then reboot it, it show this picture
![IMG_1535](https://github.com/ublue-os/bazzite/assets/32806975/4f7bde5e-bcb4-4dbd-9509-e616a3af40ef)

The information is like this
```
[
OK
1 Finished plymouth-quit-wait.servichold until boot process finishes up.
OK
1 Finished plymouth-quit service - Terminate Plymouth Boot Screen.
[FAILEDI
Failed to start tailscaled.service - Tailscale node agent.
[FAILEDI
Failed to start cups.service - CUPS Scheduler.
[FAILEDI
Failed to start wireplumber-sysconf.service - Hardware Specific Wireplumber Configuration.
[FAILED!
Failed to start
tailscaled.service - Tailscale node agent.
[FAILED]
Failed to start
cups. service - CUPS Scheduler.
[FAILED!
Failed to start
systemd-uconsole-setup.service - Virtual Console Setup.
LPAILEDI
Failed to start
tailscaled.service - Tailscale node agent.
```

### What did you expect to happen?

I expected reboot system.

### Hardware

GPD win4 7840U

**Comment by KyleGospo** [comment]
Might be related to https://github.com/ublue-os/bazzite/issues/972

**Comment by zhouxingoddog312** [comment]
> Might be related to #972

Thanks! But, Does it means that, i have to reinstall the system, and can't retain my data? Because i can't boot into the system now. 🥲

**Comment by zhouxingoddog312** [comment]
Today, I reinstall the system, it’s still like this.
![IMG_1542](https://github.com/ublue-os/bazzite/assets/32806975/e0888b41-eed1-4337-8d35-3165ea72b439)

**Comment by HikariKnight** [comment]
> > Might be related to #972
> 
> Thanks! But, Does it means that, i have to reinstall the system, and can't retain my data? Because i can't boot into the system now. 🥲

previous update should be in the boot menu
marked `ostree:1` at the end

if your grub menu is hidden you press esc at boot to show the menu.

**Comment by zhouxingoddog312** [comment]
> > > Might be related to #972
> > 
> > 
> > Thanks! But, Does it means that, i have to reinstall the system, and can't retain my data? Because i can't boot into the system now. 🥲
> 
> previous update should be in the boot menu marked `ostree:1` at the end
> 
> if your grub menu is hidden you press esc at boot to show the menu.

I entered grub command line, but which command can boot into “ostree:1”? I’m unfamiliar with grub.

**Comment by HikariKnight** [comment]
> > > > Might be related to #972
> > > 
> > > 
> > > Thanks! But, Does it means that, i have to reinstall the system, and can't retain my data? Because i can't boot into the system now. 🥲
> > 
> > 
> > previous update should be in the boot menu marked `ostree:1` at the end
> > if your grub menu is hidden you press esc at boot to show the menu.
> 
> I entered grub command line, but which command can boot into “ostree:1”? I’m unfamiliar with grub.

https://universal-blue.discourse.group/docs?topic=36#rollbacks-13

**Comment by zhouxingoddog312** [comment]
> > > > > Might be related to #972
> > > > 
> > > > 
> > > > Thanks! But, Does it means that, i have to reinstall the system, and can't retain my data? Because i can't boot into the system now. 🥲
> > > 
> > > 
> > > previous update should be in the boot menu marked `ostree:1` at the end
> > > if your grub menu is hidden you press esc at boot to show the menu.
> > 
> > 
> > I entered grub command line, but which command can boot into “ostree:1”? I’m unfamiliar with grub.
> 
> https://universal-blue.discourse.group/docs?topic=36#rollbacks-13

Thanks. But it’s not useful. I can boot into the previous update, but when I get system update, still failed to boot into system.

**Comment by ClaudioVarandas** [comment]
Same here on my Legion GO, after upgrading and also in a new install ...

**Comment by zhouxingoddog312** [comment]
> Same here on my Legion GO, after upgrading and also in a new install ...

Can you show me the informations? Is the same problem as this?

**Comment by ClaudioVarandas** [comment]
Sure, here it is :

![image](https://github.com/ublue-os/bazzite/assets/457793/9beed84f-f23f-48c9-8d4f-5f2d20ba91af)

**Comment by zhouxingoddog312** [comment]
> Sure, here it is :
> 
> ![image](https://private-user-images.githubusercontent.com/457793/324204303-9beed84f-f23f-48c9-8d4f-5f2d20ba91af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTY1NDIsIm5iZiI6MTcxMzY1NjI0MiwicGF0aCI6Ii80NTc3OTMvMzI0MjA0MzAzLTliZWVkODRmLWYyM2YtNDhjOS04ZDRmLTVmMmQyMGJhOTFhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMzM3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzFlZDllNTg0ZGJmMjg1YTFkMTY1YmU0YWFmZGZjOTc5NWQ0YWQ1Nzg5ZmQ1YTBiNDc2ZWJkZDBlMzExYzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xvxrfcXMe1ND5FydNANrs7Xzco-HNtKxRPP2ZXm2v8k)

You can click esc once immediately, when you power on the computer. As this, you can see the boot menu. Select the ostree:1 to boot into previous version. But if you update to the newest version, problem is still here.

**Comment by RitschiRitsch** [comment]
Yeah and as soon as you’re system is up with the working version you may enter in Terminal: _rpm-ostree rollback_ to keep that version as your main os and to boot directly to that. Afaik there‘s a bug with the current 20240415 release with some devices (I‘m using Loki Max). You have to rollback to an earlier version (I‘m currently on 20240406, which works well so far).

**Comment by ClaudioVarandas** [comment]
> Yeah and as soon as you’re system is up with the working version you may enter in Terminal: _rpm-ostree rollback_ to keep that version as your main os and to boot directly to that. Afaik there‘s a bug with the current 20240415 release with some devices (I‘m using Loki Max). You have to rollback to an earlier version (I‘m currently on 20240406, which works well so far).

I only have the 20240415 option on grub ... i will instal a previous one.
Is there a way to install a previous image or should install the 2.4.0 20240314 and manage from there ?

**Comment by RitschiRitsch** [comment]
> > Yeah and as soon as you’re system is up with the working version you may enter in Terminal: _rpm-ostree rollback_ to keep that version as your main os and to boot directly to that. Afaik there‘s a bug with the current 20240415 release with some devices (I‘m using Loki Max). You have to rollback to an earlier version (I‘m currently on 20240406, which works well so far).
> 
> I only have the 20240415 option on grub ... i will install a previous iso from scratch. Is there a way to install a previous image version build or should install the 2.4.0 20240314 and manage from there ?

Yeah you should install 2.4.0. afterwards you may manually update to a more recent version if you wish. But you have to do it through Terminal commands to get the correct update. When you update through Steam Gaming Mode it will always install the most recent stable one.

**Comment by ClaudioVarandas** [comment]
> > > Yeah and as soon as you’re system is up with the working version you may enter in Terminal: _rpm-ostree rollback_ to keep that version as your main os and to boot directly to that. Afaik there‘s a bug with the current 20240415 release with some devices (I‘m using Loki Max). You have to rollback to an earlier version (I‘m currently on 20240406, which works well so far).
> > 
> > 
> > I only have the 20240415 option on grub ... i will install a previous iso from scratch. Is there a way to install a previous image version build or should install the 2.4.0 20240314 and manage from there ?
> 
> Yeah you should install 2.4.0. afterwards you may manually update to a more recent version if you wish. But you have to do it through Terminal commands to get the correct update. When you update through Steam Gaming Mode it will always install the most recent stable one.

Here can i download the 2.4.0 iso ?  tried to build myself , also tried to rebase on fedora atomic , but i can't or i dont know how to fetch the 2.4.0 tag. The only tags i can use is stable or testing which are both broken on my desktop and LLGO ...

Really want to use bazzite but its hard to have a working system...

**Comment by ClaudioVarandas** [comment]
Managed to generate isos from bazzite tags by `docker run --rm --privileged --volume ./iso:/build-container-installer/build ghcr.io/jasonn3/build-container-installer:latest VERSION=39 IMAGE_NAME=bazzite IMAGE_TAG=39-20240314 VARIANT=Kinoite IMAGE_REPO=ghcr.io/ublue-os`

**Comment by zhouxingoddog312** [comment]
Did v3.0.0 fixed this bug?

**Comment by ClaudioVarandas** [comment]
> Did v3.0.0 fixed this bug?

yeap! At least for me the desktop bazzite stable 3.0.0 works fine, upgraded and boots correctly. 👍 tx!

**Comment by zhouxingoddog312** [comment]
OK, the bug seems to have been solved.
