### ISSUE TITLE
Bazzite Installer is rotated and dual screen on Steam Deck OLED

### ISSUE THREAD

**Issue by spayne** [ublue-os/bazzite#982]
### Describe the bug

When I boot into the "Install Bazzite Deck Deck - 39" on Steam Deck OLED, using Dock with HDMI monitor. 

Half the screen is visible half is not.

It is still possible to start the installation, but some prompts are not visible.

Install Bazzite Deck Deck - 39
![PXL_20240415_213207953](https://github.com/ublue-os/bazzite/assets/82259/20fee26e-36e4-40e5-aeae-045de4f39292)

### What did you expect to happen?
I didn't expect to have to use the monitor at all.   I expected both to be on the same screen.  Ideally it would be rotated in Landscape mode.

### Hardware

Steam Deck OLED

### Extra information or context

You have a comment at: https://universal-blue.discourse.group/t/bazzite-initial-setup-and-installation-guide/30#installer-requirements-15
> Steam Deck OLED users: The installer only displays properly in Basic Graphics Mode.

However you don't explain how to enter this mode.  ... Is this the issue?  If it is, could you let me know how to get into this mode please.  e.g. is it a kernel param?

**Comment by KyleGospo** [comment]
Basic graphics mode is a selection you make at the very start of the install process. At this time we do not support the OLED deck due to numerous issues with refresh rate control and sound. Once those are resolved we will modify the installer to handle OLEDs gracefully.
