### ISSUE TITLE
The Mission link in MOTD is broken

### ISSUE THREAD

**Issue by fat0troll** [ublue-os/bazzite#985]
### Describe the bug

Sometimes when I open the terminal, I see a motd with the text

```
  󰋼 This isn't a distro, this is a custom image built on  Fedora Atomic Desktop technology                           
  View our mission https://ublue.it/mission/  
  ```
  
  When I click on the link, it shows 404.

![image](https://github.com/ublue-os/bazzite/assets/371254/2b720551-4c21-4b19-b703-9db8fa457bd1)

### What did you expect to happen?

I want to read your Mission page :)

### Output of `rpm-ostree status`

```shell
$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:4ea40ad6889447efbaab1c09692f148e805043697800aee9f8290c6170e3534c
                  Version: 39.20240116.0 (2024-04-16T02:29:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:e0f0adbc720be6b000d4fc9d9366ed32724698d30d8ddb88ecb12609af6c326e
                  Version: 39.20240116.0 (2024-04-15T15:45:38Z)
```

### Hardware

Nvidia desktop box, doesn't matter in this case.

### Extra information or context

Thank you for making Bazzite! It is mostly a pleasure to use it (nvidia drivers notwithstanding)...

**Comment by KyleGospo** [comment]
Thanks, fixed
