### ISSUE TITLE
Legion Go suspend not working while game is running

### ISSUE THREAD

**Issue by gyorgys** [ublue-os/bazzite#993]
### Describe the bug

While running Dishonored in Game Mode, pressing the power button will not suspend the system. The system will ostensibly try to go to suspend (screen blanks, power LED blinks) but it wakes up immediately.

No problem sleeping while in Steam UI

### What did you expect to happen?

Pressing the power button will should suspend the system.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b3e8d6e3cb7ed88de6dfe20dcf1f82a38eff42e02226d68897ea051a90ec7fa7
                  Version: 39.20240418.0 (2024-04-18T20:08:16Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:b3e8d6e3cb7ed88de6dfe20dcf1f82a38eff42e02226d68897ea051a90ec7fa7
                  Version: 39.20240418.0 (2024-04-18T20:08:16Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf /etc/modprobe.d/deck-blacklist.conf"'
```

### Hardware

83E1

Lenovo Legion Go

### Extra information or context

I have been playing Dishonored before updating and suspend worked fine

**Comment by Shaunathanz** [comment]
Weird question but can you try disconnecting the True Strike controllers and then try to suspend it? I've been having suspend issues since the last update and it doesn't seem to be game specific for me, but the controllers being connected (specifically the left one) seems to be the deciding factor when the issue is occurring.

**Comment by gyorgys** [comment]
The issue went away with the 4/19 build

**Comment by gyorgys** [comment]
The issue went away with the 4/19 build

**Comment by gyorgys** [comment]
The issue is back on 4/19 build with a different game (CP77). I detached the controllers per @Shaunathanz suggestion and were able to suspend that way
