### ISSUE TITLE
Asus keyboard backlight does not work

### ISSUE THREAD

**Issue by derproid** [ublue-os/bazzite#997]
### Describe the bug

When booting the backlight is on until after the Bazzite logo appears. At this point trying to set the led-mode with asusctl results in the following:

```
abonasera@fedora:~$ asusctl led-mode rainbow

Error: org.freedesktop.DBus.Error.Failed: Asus Platform error: /dev/hidraw2 Broken pipe (os error 32)

asusctl version: 5.0.10
 Product family: ROG Zephyrus Duo 15 SE
     Board name: GX551QR

Supported interfaces:

[
    "Aura",
    "FanCurves",
    "Platform",
]

Supported properties:

[
    ChargeControlEndThreshold,
    DgpuDisable,
    PanelOd,
    ThrottlePolicy,
    PptPl1Spl,
    PptPl2Sppt,
]
```

### What did you expect to happen?

I expected the backlight to turn on

### Output of `rpm-ostree status`

```shell
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite-asus-nvidia:stable
                   Digest: sha256:2c99637957ba83e0a0eb13fd19bdfd8ed73b9d38a98aa8402d05f7ef2d15cd56
                  Version: 39.20240116.0 (2024-04-18T20:13:11Z)
          LayeredPackages: input-remapper k3s-selinux sunshine wine-mono
            LocalPackages: mullvad-vpn-2024.1-1.x86_64
                Initramfs: '"-I /etc/crypttab /usr/lib/modprobe.d/nvidia.conf" '
```

### Hardware

ROG Zephyrus Duo 15 SE GX551QR_GX551QR

### Extra information or context

Backlight and led settings were working fine as recently as the 2024-04-07 update. I had updated to 2024-04-18 where the backlight stopped working it so I reverted to 2024-04-07. After shutting down going to sleep and rebooting however the backlight worked on 2024-04-18 on first boot. After updating to 2024-04-19 the backlight stopped working again and reverting to 2024-04-18 did not result in the backlight working.

**Comment by derproid** [comment]
Oh also here is the result of ```journalctl -b -u asusd > ~/asusd.log``` which the asusctl repo says to post when reporting an issue
[asusd.log](https://github.com/ublue-os/bazzite/files/15050686/asusd.log)

**Comment by neverender** [comment]
Wow thanks for solving this issue guys!

What a great project
