### ISSUE TITLE
Fan control?

### ISSUE THREAD

**Issue by Toffy2323** [ublue-os/bazzite#999]
### Describe the bug

Fans get loud, is there fan control?

### What did you expect to happen?

Fan curve management

**Comment by Toffy2323** [comment]
Hi, is there fan control  on Rog ally Bazzite, if so, how

**Comment by massatt212** [comment]
> Hi, is there fan control on Rog ally Bazzite, if so, how

try lact, idk if it will work
ujust install-lact

**Comment by Toffy2323** [comment]
> > Hi, is there fan control on Rog ally Bazzite, if so, how
> 
> try lact, idk if it will work ujust install-lact

Hi , what is lact, does it allow fan control? Thanks :)

**Comment by KyleGospo** [comment]
Please ignore the fact suggestion, that's completely wrong. 

Follow https://github.com/ublue-os/bazzite#alternative-handhelds

**Comment by Toffy2323** [comment]
> Please ignore the lact suggestion, that's completely wrong.
> 
> Follow https://github.com/ublue-os/bazzite#alternative-handhelds
> 
> Our guides cover fan control.

This is not completed? Incomplete the issue, atleast above he gave a suggestion, what kind of suggestions is a link to the info page? What suggestion can you give for fan control
